### ISSUE TITLE
bibtex unicode error

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#10000]
```
galaxy.managers.citations ERROR 2020-07-15 11:36:09,469 [p:25488,w:2,m:0] [uWSGIWorker2Core3] Failed to fetch bibtex for DOI 10.1038/nmeth.3869
Traceback (most recent call last):
  File "lib/galaxy/managers/citations.py", line 144, in to_bibtex
    self.raw_bibtex = self.doi_cache.get_bibtex(self.__doi)
  File "lib/galaxy/managers/citations.py", line 55, in get_bibtex
    return self._cache.get(key=doi, createfunc=createfunc)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/site-packages/beaker/cache.py", line 322, in get
    return self._get_value(key, **kw).get_value()
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/site-packages/beaker/container.py", line 332, in get_value
    self.namespace.acquire_read_lock()
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/site-packages/beaker/container.py", line 208, in acquire_read_lock
    self.open('r', checkcount=True)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/site-packages/beaker/container.py", line 240, in open
    self.do_open(flags, replace)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/site-packages/beaker/container.py", line 673, in do_open
    self.hash = pickle.load(fh)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 561: ordinal not in range(128)
```

**Comment by mvdbeek** [comment]
Remove the citation cache (database/citations), this happens when the citation cache has originally been created on python 2.

**Comment by bernt-matthias** [comment]
Thanks. This worked.
