### ISSUE TITLE
Filters not properly working on tests or workflows, testing on ThermoRawFileConverter tool

### ISSUE THREAD

**Issue by CarlosHorro** [galaxyproject/galaxy#10006]
Hi,

As far as I know, this problem happens in all galaxies I've tried.
I'm having problems managing filters with functions to work when executing tests and when creating workflows.

This is the scenario: the tool ThermoRawFileConverter has different outputs which, simplifying, could be grouped into two groups: 

1. one group focused on returning single files, 
2. another group focused on returning collections. 

Using one output types or the others depends on the number of input files (raw files) received, so:

1. When 1 (raw) file is received as input, one output returning 1 file (the converted mgf or mzml file) should be used.
2. When 2 or more (raw) files are received as inputs, one output_collection output is used in order to return the converted files as a collection.

The problem is that, when running tests (the first and most basic test is representative of this) for returning just one file (mgf), it generates correctly one output file but a collection output (which return a mgf collection) is also present. This is happening because one filter present into the collection is True although the input files were just 1 and it was supposed to be True just when there were more than 1 input files:

```
<collection name="output_mgf_collection" type="list" label="${tool.name} on ${on_string}: MGF">
            <filter>output_format == "0"</filter>
            <filter>len(input) > 1</filter>
            <discover_datasets pattern="(?P&lt;designation&gt;.+)\.mgf" directory="output_folder" ext="mgf"/>
        </collection>
```

In order to bypass this, the current (no-really-orthodox) production code uses:

```

<collection name="output_mgf_collection" type="list" label="${tool.name} on ${on_string}: MGF">
            <filter>output_format == "0"</filter>
            <filter>(str(input)).count(',') > 0</filter>
            <discover_datasets pattern="(?P&lt;designation&gt;.+)\.mgf" directory="output_folder" ext="mgf"/>
        </collection>

```

Here the filter just counts the number of commas, so, indirectly, it is counting the number of input files. This works (ie: in the example test I mentioned, just the single output is returned and not the collection one) when running tests. 

But now we need to connect ThermoRawFileConverter to another tool using a workflow.

When creating the workflow, I can see in the diagram the input and the output for returning single files, but I cannot access to any collection output. 
I was trying to create a workflow just for managing multiple files, ie: establishing some input files for ThermoRawFileConverter, but there are no collection outputs shown whatever I do.

The "funniest" thing about this is, if I use again the filter syntax
`
<filter>len(input) > 1</filter>
`

for the collection outputs, these outputs are properly shown when managing the diagram...
Could someone clarify me if I'm doing something wrong, please?

Greetings,
Carlos

**Comment by bernt-matthias** [comment]
First I have to ask if there is a difference in calling the converter 
- for the single files separately and 
- jointly for all files

If not it might be better not to allow multiple inputs at all, i.e. making it a batch input field.

The solution to your problem is probably `isinstance(input, list) and len(input) > 1`, because in case of a single data set `input` is probably a string which also has a length. See for instance here https://github.com/galaxyproject/tools-iuc/blob/6085b7d47fcb47ad1587ac2542abdef782f61fe4/tools/gffcompare/gffcompare.xml#L162

**Comment by bernt-matthias** [comment]
Odd thing is that you already have `expect_num_outputs` in the tests. That should have detected the problem, isn't it?

**Comment by CarlosHorro** [comment]
Thank you @bernt-matthias for your answer :-)

Yes, there is a difference using the converter especially when you use workflows programatically. We need to send all data at a time to SearchGUI input, and not file by file as it would happen if trying to execute the converter file by file.

Also, `expect_num_outputs` is playing here a really interesting role as it has shown some unexpected errors but, when I finally got all the tests working, workflow's outputs are still not well managed for multiple files.



On the other hand, this topic is really confusing. I'm printing the `typeof` `input` when executing the tests, and it is `DataListWrapper` in all cases. But, if I just use as filter in the single output:

`<filter>isinstance(input_files, list) and len(input_files) == 1 </filter>
`

I receive an assertion error when executing the 2 first tests (related to single outputs). Instead, if I use 

`<filter>(isinstance(input, list) is False) or (isinstance(input, list) and len(input_files) == 1) </filter>
`
for the single outputs, all tests pass correctly :-?
So there seems to be some internal discrepancy about the type of `input` when receiving just 1 file...

So, I've been able to execute all the tests successfully with these filters:

For output and output_metadata outputs:
`<filter>(isinstance(input, list) is False) or (isinstance(input, list) and len(input_files) == 1) </filter>
`

For output_mgf_collection, output_mzml_collection, output_indexedmzml_collection and output_metadata_collection:
`isinstance(input_files, list) and len(input_files) > 1
`

But the problem again is that, when connecting the tool using a workflow, it is not possible to link any collection output from ThermoRawFileConverter as they are not shown at all. I've tried to represent some fake inputs to ThermoRawFileConverter in the workflow in order to simulate the proper conditions to generate a collection, but collection outputs are not shown either.

As an intermediate solution I'm thinking about the possibility of adding a new optional parameter called "Force data output as collection", disabled by default but, when enabled, it would force the tool to produce collections no matter the number of inputs it has. 
As this would work basically as an input boolean and it could be checked easily in the filters, it could be easily managed from the workflow tool and I think the collection outputs would be properly shown...

Greetings,
Carlos

**Comment by bernt-matthias** [comment]
> Yes, there is a difference using the converter especially when you use workflows programatically. We need to send all data at a time to SearchGUI input, and not file by file as it would happen if trying to execute the converter file by file.

But that's something that you should change in the SearchGUI wrapper or in the workflow (i.e. the way how you connect the steps).

Would you be able to provide a mock tool that reproduces the behavior, i.e. the working and not working cases? Then I could investigate what is going on.

> But the problem again is that, when connecting the tool using a workflow, it is not possible to link any collection output from ThermoRawFileConverter as they are not shown at all.

Do you use a collection input or a simple input?

**Comment by CarlosHorro** [comment]
> > Yes, there is a difference using the converter especially when you use workflows programatically. We need to send all data at a time to SearchGUI input, and not file by file as it would happen if trying to execute the converter file by file.
> 
> But that's something that you should change in the SearchGUI wrapper or in the workflow (i.e. the way how you connect the steps).

Well, SearchGUI wrapper works fine, the error is in the way ThermoRawFileConverter outputs are being shown in the workflow editor, so I think this is what must be fixed (collection outputs are not being shown when choosing multiple input files, although the filters are configured to do so)
Finally, I'm afraid I've checked that it is not even possible to use batch mode in workflows, probably because of what I mentioned (you would be using one tool multiple times in the same workflow, whilst those outputs should be received by the same instance of the next tool).
 
> 
> Would you be able to provide a mock tool that reproduces the behavior, i.e. the working and not working cases? Then I could investigate what is going on.

I can try but, apart from the extra work, I think ThermoRawFileConverter is really a simple tool to test this behaviour... You can just try to include this tool in a workflow as it is (the current filters, although ugly, work on tests and perfectly reproduce this behaviour) and you will see the single output but not the collection outputs even when including multiple inputs in the diagram.

> 
> > But the problem again is that, when connecting the tool using a workflow, it is not possible to link any collection output from ThermoRawFileConverter as they are not shown at all.
> 
> Do you use a collection input or a simple input?

Collection input or multiple inputs.

**Comment by bernt-matthias** [comment]
My suggestion is the following: 

1. Make the input `multiple="false"` here: https://github.com/galaxyproteomics/tools-galaxyp/blob/542fee4158c3dbd0c5ad8cd7e97b77f55982e0bf/tools/ThermoRawFileParser/thermo_converter.xml#L52
2. Keep only the single data set outputs: `output` and `output_metadata` 

The workflow takes then a collection of raw files, ThermoRawFileParser processes the raw files in parallel, SearchGUI processes the mgf( or mzml?) files jointly. 

The only difference is that, the user needs to create the raw file collection at first, but this can be documents. Advantages: easier to test and faster (due to batch mode of the processor). 

Still it might be interesting to debug the original problem.

**Comment by bernt-matthias** [comment]
A mock tool adapter from the converter produces this error when a workflow is run on collection:

```
Traceback (most recent call last):
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/modules.py", line 1660, in execute
    collection_info = self.compute_collection_info(progress, step, all_inputs)
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/modules.py", line 335, in compute_collection_info
    progress, step, all_inputs
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/modules.py", line 353, in _find_collections_to_match
    data = progress.replacement_for_input(step, input_dict)
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 328, in replacement_for_input
    replacement = [self.replacement_for_connection(c) for c in connection]
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 328, in <listcomp>
    replacement = [self.replacement_for_connection(c) for c in connection]
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 364, in replacement_for_connection
    raise Exception(message)
Exception: Workflow evaluation problem - failed to find output_name output in step_outputs {'output_collection': <galaxy.model.HistoryDatasetCollectionAssociation(6) at 0x7ff7946edfd0>}
galaxy.workflow.run ERROR 2020-07-20 18:25:52,093 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/tmp/tmppigj3vbc/galaxy-dev/lib/galaxy/workflow/run.py", line 353, in replacement_for_connection
    replacement = step_outputs[output_name]
KeyError: 'output'
```

The workflow editor always shows the `output` connection and never the one for `output_collection`, regardless if a simple data set or a collection is used.

The workflow takes a collection input and feeds it through 2x the mock tool: 


```
<tool id="thermo_raw_file_converter" name="Thermo" version="1.2.3">
    <description>RAW file converter</description>
    <command>
<![CDATA[
#import re
#if len($input) > 1
    mkdir out/
    #for $inp in $input:
        #set $input_name = re.sub('[^\w\-\.]', '_',$inp.element_identifier.split('/')[-1].replace(".raw", ""))
        && cp '${inp}' './out/${input_name}'
    #end for
#else:
    cp '${input[0]}' 'output_file.out'
#end if

&& echo "${type($input)}"
]]>
    </command>
    <inputs>
        <param name="input" type="data" format="txt" multiple="true" optional="False" />
    </inputs>
    <outputs>

        <!-- We use simple data outputs if we just have one file, for backwards compatibility -->

        <data name="output" format="txt" from_work_dir="output_file.out" label="${tool.name} on ${on_string}">
            <filter>(str(input)).count(',') == 0</filter> <!-- funny way of counting the number of input files! -->
        </data>

        <!-- We use collections if we have multiple input files -->

        <collection name="output_collection" type="list" label="${tool.name} on ${on_string}: MGF">
            <filter>(str(input)).count(',') > 0</filter>
            <discover_datasets pattern="(?P&lt;designation&gt;.+)\.txt" directory="out" ext="txt"/>
        </collection>

    </outputs>

    <tests>
        <!-- Basic test -->
        <test expect_num_outputs="1">
            <param name="input" value="1.txt" ftype="txt"/>
            <output name="output" file="1.txt" ftype="txt"/>
        </test>

        <!-- Basic mzml collection test -->
        <test expect_num_outputs="1">
            <param name="input" value="1.txt,2.txt,3.txt" ftype="txt"/>
            <output_collection name="output_collection" type="list" count="3"/>
        </test>
    </tests>
    <help>
    </help>
    <citations>
    </citations>
</tool>
```

**Comment by mvdbeek** [comment]
If there is any way that you can avoid the use of filters for this kind of output switching, please try that. I doubt this can be made to work reliably, and it is difficult to reason about.

```
Exception: Workflow evaluation problem - failed to find output_name output in step_outputs {'output_collection': <galaxy.model.HistoryDatasetCollectionAssociation(6) at 0x7ff7946edfd0>}
```
used to be the most common workflow-related error when we were still showing all outputs without filter.
We do that now, the code is here: https://github.com/mvdbeek/galaxy/blob/8e466ef916f3cf0f442ed2c4949a8f622cb9cfb1/lib/galaxy/workflow/modules.py#L1436

You might be able to augment the state inputs somehow ... but I think it would be much easier to reason about the output if you either followed https://github.com/galaxyproject/galaxy/issues/10006#issuecomment-660957956 or you went the other route and always produced a collection.

**Comment by CarlosHorro** [comment]
Thank you very much for all your feedback @mvdbeek @bernt-matthias 

Considering 1) the different issues we have been managing when connecting ThermoRawFileParser single outputs to other tools (especially, SearchGUI), 2) keeping single outputs in last versions of this tool was just a matter of backwards compatibility with old versions, and 3) the application itself was programmed for a good performance when managing multiple input files at a time, I think the best option by far is to always produce collections, so I will work on this direction to update the tool and fix its behaviour when used into workflows.

Thank you very much again :-)
Carlos

**Comment by bernt-matthias** [comment]
> so I will work on this direction to update the tool and fix its behavior when used into workflows

Up to you and certainly a good idea. Still I would do the opposite and go for batch mode :). 

Even if "the application itself was programmed for a good performance when managing multiple input files at a time" I tend to think of future applications and of scalability. There will be more and more data. Hence an approach that scales better might be preferable. 

With batch mode the runtime for 1, 10, 100, ... datasets will be the same (given the compute hardware). With joint processing you will need to wait 10x, 100x ... longer.

**Comment by bernt-matthias** [comment]
Another follow up: When one crates a node with the tool the filters run, but get an instance of `galaxy.tools.parameters.basic.RuntimeValue` (a wrapper to note a value that is not yet set, but will be required at runtime) which is just a plain object without any properties. 

If one connect an Input (e.g. collection) the filters do not run again. 

Wondering if they should, since after the connection to a InputDataset, InputCollection, or InputValue the workflow node has more information...?
