### ISSUE TITLE
500 error when downloading a dataset

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#10026]
when attempting to download a html file from a collection from galaxy I get a 500 error:
this is on galaxy 3850e736cdea413de271628a53be2c592fb806b8

10.255.255.215 - - [22/Jul/2020:11:22:14 -0400] "GET /datasets/b49b278fda5da70b/display?to_ext=data&hdca_id=e16eb456769fc8dd&element_identifier=25-VAC0101-B HTTP/1.1" 500 - "http://galaxy.neb.com/histories/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/home/galaxy/galaxy/.venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/galaxy/galaxy/.venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 145, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 224, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/dataset.py", line 187, in display
    return data.datatype.display_data(trans, data, preview, filename, to_ext, offset=offset, ck_size=ck_size, **kwd)
  File "lib/galaxy/datatypes/data.py", line 449, in display_data
    return self._archive_composite_dataset(trans, data, **kwd)
  File "lib/galaxy/datatypes/data.py", line 271, in _archive_composite_dataset
    params = util.Params(kwd)
  File "lib/galaxy/util/__init__.py", line 834, in __init__
    self.__dict__[key] = sanitize_param(value)
  File "lib/galaxy/util/__init__.py", line 603, in sanitize_param
    raise Exception('Unknown parameter type (%s)' % (type(value)))
Exception: Unknown parameter type (<class 'galaxy.model.HistoryDatasetCollectionAssociation'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 164, in __call__
    exc_info)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 70, in replacement_start_response
    return start_response(status, headers, exc_info)
SystemError: <built-in function uwsgi_spit> returned a result with an error set

**Comment by nekrut** [comment]
@bwlang can this replicated using fastqc html outputs?

**Comment by jmchilton** [comment]
Possibly fixed by https://github.com/galaxyproject/galaxy/pull/10330 ?
