### ISSUE TITLE
Can't delete user that was created with SSO

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#1002]
I recently enabled "delete user" for admin users and attempted to delete and purge a user created with LDAP (since we cannot reset their password [#1001](https://github.com/galaxyproject/galaxy/issues/1001) and LDAP needed to be temporarily deactivated [#972](https://github.com/galaxyproject/galaxy/issues/972) for some automation with bioblend). I've run a manual cleanup with the "cleanup_datasets" scripts (which to my knowledge only targets datasets) and restarted the server. When I look into the admin view for this user, their status reads "external: yes, status: purged, activated: no" and I cannot create this user or delete them. Additional requests for deletion or purge produce no errors (beyond the standard broken pipe/socket errors that never go away). A green icon displays that the deletions/purges are successful and yet the user persists and cannot be deleted or created. 

Upon deletion:

```
Exception happened during processing of request from ('1.3.3.7', 34824)
Traceback (most recent call last):
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
----------------------------------------
Exception happened during processing of request from    self.finish_request(request, client_address)
 ('1.3.3.7', 34823)  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish()

 Traceback (most recent call last):
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
----------------------------------------  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish

Exception happened during processing of request from ('1.3.3.7', 34827)    self.wfile.close()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
    self.flush()
    self.finish_request(request, client_address)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request

  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish_request(request, client_address)
error: [Errno 32] Broken pipe
    self.finish()
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request
----------------------------------------
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish
    self.RequestHandlerClass(request, client_address, self)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__
    self.wfile.close()
    self.finish()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
    self.flush()
----------------------------------------  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

error: [Errno 32] Broken pipe
 ----------------------------------------
```

Upon purge:

```
1.4.4.7 - - [29/Oct/2015:11:24:21 -0400] "GET /admin/users?status=done&message=Purged+1+users%3A+purged.user__at__domain.com+ HTTP/1.1" 200 - "http://galaxy.domain.com/admin/users?status=done&message=Deleted+1+users%3A++purged.user__at__domain.com+" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"
------------------------------------------------------------------------------------------------------------------------


Exception happened during processing of request fromException happened during processing of request from  Exception happened during processing of request from('1.3.3.7', 34896)('1.3.3.7', 34895) ('1.3.3.7', 34897)

Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.RequestHandlerClass(request, client_address, self)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__

    self.finish_request(request, client_address)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.finish()
Traceback (most recent call last):
    self.RequestHandlerClass(request, client_address, self)
  File "/apps/sys/galaxy/galaxy_env/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
    self.finish_request(request, client_address)
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish
    self.RequestHandlerClass(request, client_address, self)
    self.wfile.close()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 653, in __init__
    self.flush()
    self.flush()
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
    self.finish()
  File "/apps/sys/python/2.7.8/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
error: [Errno 32] Broken pipe
  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 279, in close
    self.flush()
----------------------------------------  File "/apps/sys/python/2.7.8/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

error: [Errno 32] Broken pipe
----------------------------------------

```

**Comment by MatthewRalston** [comment]
In my galaxy.ini configuration, "auth_config_file" was disabled/commented but "use_remote_user" was true at the time that the user was created.

**Comment by hexylena** [comment]
> LDAP needed to be temporarily deactivated #972 for some automation with bioblend).

many sites have an API exception for this exact use case. https://galaxyproject.org/admin/config/nginx-external-user-auth/#api-exception

we're fixing user purging to really remove them. The other option is to edit the purged column in the database. But otherwise this should be working better in the past years, sorry :(
