### ISSUE TITLE
Data Libraries upload via Upload_from_Galaxy_filesystem() method stays "queued" forever...

### ISSUE THREAD

**Issue by DanBerrios** [galaxyproject/galaxy#10081]
I'm using Bioblend to mass-upload files from various differently-typed files on the server in S3-mounted buckets into data libraries in our Galaxy system. The files appear in the libary, with correct sizes, but remain in "queued" state forever... they cannot be used in histories. Any ideas why? The "queued" jobs to upload each file have no assigned job runners. Other job types run fine...  I'm using the "upload_from_galaxy_filesystem" method and not setting type (since the files all have different types).

**Comment by mvdbeek** [comment]
Hi @DanBerrios, are regular upload jobs working correctly on this Galaxy instance ? Which version of Galaxy are you using, and can you post an excerpt from your Galaxy logs when you try to add new datasets ?

**Comment by DanBerrios** [comment]
@mvdbeek Yes, other "regular" jobs are working fine...the get the default local job runner.  We are using v20.01.  I tried to search logs for these added datasets.... I didn't see anything.  What keywork should I be looking for?

**Comment by mvdbeek** [comment]
And "regular" jobs include the upload1 tool ? Can you follow the logs while you try to upload via bioblend ?

**Comment by DanBerrios** [comment]
@mvdbeek OK, I see this stack trace in the logs:


galaxy.web.framework.decorators ERROR 2020-08-10 10:56:26,760 [p:6601,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 257, in create
    status, output = self._upload_library_dataset(trans, library_id, real_folder_id, **payload)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 344, in _upload_library_dataset
    **kwd)
  File "lib/galaxy/actions/library.py", line 128, in _upload_dataset
    job, output = upload_common.create_job(trans, tool_params, tool, json_file_path, data_list, folder=library_bunch.folder, job_params=job_params)
  File "lib/galaxy/tools/actions/upload_common.py", line 429, in create_job
    for name, value in tool.params_to_strings(params, trans.app).items():
  File "lib/galaxy/tools/__init__.py", line 1625, in params_to_strings
    return params_to_strings(self.inputs, params, app, nested)
  File "lib/galaxy/tools/parameters/__init__.py", line 206, in params_to_strings
    value = params[key].value_to_basic(value, app)
  File "lib/galaxy/tools/parameters/grouping.py", line 665, in value_to_basic
    current_case = rval['__current_case__'] = self.get_current_case(value[self.test_param.name])
  File "lib/galaxy/tools/parameters/grouping.py", line 660, in get_current_case
    raise ValueError("No case matched value:", self.name, str_value)
ValueError: ('No case matched value:', 'files_metadata', '')

Any ideas about this?

**Comment by DanBerrios** [comment]
@mvdbeek Update: I changed the "file_type" param for the uploads from empty to "auto".... and this seems to have kicked some upload jobs off to a running state.  I will post an update if they succeed.
