### ISSUE TITLE
Error handling when a Keycloak response misses email

### ISSUE THREAD

**Issue by VJalili** [galaxyproject/galaxy#10165]
1. Login to Keycloak using a local account who does not have `email` attribute set; 
2. Head to Galaxy's login (assuming you've not logged in yet) and click on the "Login with Keycloak" button; 
3. Keycloak will respond with a token containing the AuthN info of the local user account. Since this account does not have `email` attribute, Galaxy will fail with the following error: 

```shell
Traceback (most recent call last):
  File "lib/galaxy/authnz/managers.py", line 289, in callback
    return success, message, backend.callback(state_token, authz_code, trans, login_redirect_url)
  File "lib/galaxy/authnz/custos_authnz.py", line 90, in callback
    email = userinfo['email']
KeyError: 'email'
```

The above error is show on the console; however, on the UI the following error is shown which is not intuitive: 

> The following error occurred when handling callback from `keycloak` identity provider: 'email'

We may implement either of the following:

- Update the error message for an intuitive one, suggesting user to set `email` property for the Keycloak account;
- Do not require the `email` claim, so do not throw an error when it is missing.

I suggest we keep `email` as required and just make the error message more intuitive.

**Comment by dannon** [comment]
Yeah, Galaxy is going to need email.  Error just needs to bubble up better.  xref #10075, Juleen is working on more informative user feedback in other authn spots too
