### ISSUE TITLE
galaxy-tool-util  throws exception

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10186]
Python 3.8.5
pip install galaxy-tool-util
```
> mulled-search --destination docker conda --search vsearch
Traceback (most recent call last):
  File "/home/nolan/Projects/galaxy-container/venv/bin/mulled-search", line 10, in <module>
    sys.exit(main())
  File "/home/nolan/Projects/galaxy-container/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/mulled/mulled_search.py", line 321, in main
    conda_results[item] = conda.get_json(item)
  File "/home/nolan/Projects/galaxy-container/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/mulled/mulled_search.py", line 123, in get_json
    raw_out, err, exit_code = run_command(
TypeError: 'NoneType' object is not callable
```

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/10465 .
