### ISSUE TITLE
Job resource params failing in 20.05 but works in 20.01

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#10267]
We have the job resource params working on 20.01. On a separate installation, the same job resource params configuration for 20.05 fails with the following message repeated more than 75 times when starting Galaxy:

```
galaxy.datatypes.registry ERROR 2020-09-22 17:00:12,853 [p:37012,w:0,m:0] [MainThread] Error loading converter (/general/sw/galaxy/lib/galaxy/datatypes/converters)
Traceback (most recent call last):
  File "lib/galaxy/datatypes/registry.py", line 616, in load_datatype_converters
    converter = toolbox.load_tool(config_path, use_cached=use_cached)
  File "lib/galaxy/tools/toolbox/base.py", line 855, in load_tool
    tool = self.create_tool(config_file=config_file, tool_shed_repository=tool_shed_repository, guid=guid, tool_cache_data_dir=tool_cache_data_dir, **kwds)
  File "lib/galaxy/tools/__init__.py", line 302, in create_tool
    tool = self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
  File "lib/galaxy/tools/__init__.py", line 320, in _create_tool_from_source
    return create_tool_from_source(self.app, tool_source, **kwds)
  File "lib/galaxy/tools/__init__.py", line 238, in create_tool_from_source
    tool = ToolClass(config_file, tool_source, app, **kwds)
  File "lib/galaxy/tools/__init__.py", line 512, in __init__
    self.populate_resource_parameters(tool_source)
  File "lib/galaxy/tools/__init__.py", line 1316, in populate_resource_parameters
    resource_xml = self.app.job_config.get_tool_resource_xml(root.get('id'), self.tool_type)
  File "lib/galaxy/jobs/__init__.py", line 574, in get_tool_resource_xml
    fields = [self.resource_parameters[n] for n in fields_names]
  File "lib/galaxy/jobs/__init__.py", line 574, in <listcomp>
    fields = [self.resource_parameters[n] for n in fields_names]
KeyError: 'cores'
```

Our 20.05 is at this commit:
```
commit 44c1653b283ff18a0829470fbc92662842cd6795
Date:   Mon Sep 21 23:37:25 2020 -0400
```

Setting the default here in the job_conf.xml is what causes the error messages in 20.05 (it works fine in 20.01)
```
    <resources default="cores_time">
      <group id="cores_time">cores,time</group>
    </resources>
```
In 20.05, if the default resources are not set like `<resources>`, then the errors do not occur but the Job Resource Parameters do not show up with the tools.
In 20.01, if I don't set the default resources as cores_time then the Job Resource Parameters do not show up with the tools.
For both of these installations, the default destination is: `<destinations default="dynamic_cores_time">`

**Comment by jmchilton** [comment]
We didn't notice this problem on other servers, is it possible there is some other difference in the job conf? We have some test cases for this also that we haven't seen fail. But there have been a lot of tool changes so there might be a problem in there I don't know what would be causing it though. Maybe I could try to improve the exception there to help.

**Comment by code4dna** [comment]
I was able to get it working. The description for job_resource_params_file is misleading. This is the default value in the galaxy.yml and if I leave it like that then there are no errors (this is how we have it in 20.01).
```
  # The value of this option will be resolved with respect to
  # <config_dir>.
  #job_resource_params_file: job_resource_params_conf.xml
```
But if I remove the comment for the parameter without changing the parameter then starting Galaxy fails (which is the original error I reported for 20.05):
```
  # The value of this option will be resolved with respect to
  # <config_dir>.
  job_resource_params_file: job_resource_params_conf.xml
```
But if I add the config as part of the relative path, then it works.
```
  # The value of this option will be resolved with respect to
  # <config_dir>.
  job_resource_params_file: config/job_resource_params_conf.xml
```
In both 20.01 and 20.05 we did not change config_dir
`  #config_dir: null`

**Comment by jmchilton** [comment]
Ahh okay - I think the default handling around that may have changed. That makes sense - I was thinking it would be a job change but it was a configuration loading change.

@ic4f do you think the configuration documentation here needs to be changed?

**Comment by code4dna** [comment]
This error does not occur in our 20.09 install and the following uncommended line works fine in 20.09, it just was not working in 20.05:
`job_resource_params_file: job_resource_params_conf.xml`

**Comment by ic4f** [comment]
@code4dna thanks for clarifying! I've just verified the same on my local instance. So yes, it was a bug in 20.05 (not 20.01) that has been fixed. We shouldn't have to prefix the file with `config/` - when Galaxy looks for that file it looks in the config directory (regardless of what the directory name is). If the value in `galaxy.yml` is still prefixed with `config/`, Galaxy will strip it away before checking - so if you change your config directory to something else (e.g. `myconfig/`), but forget to change the `config/` prefix in the value of `job_resource_params_file`, Galaxy would still check in `myconfig/job_resource_params_file`. 

@jmchilton the configuration docs are correct; however we definitely should add a line about paths being resolved to parent directories to such config options! I'll open a separate issue.
