### ISSUE TITLE
Tool output produces encoding related error on job handler

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#10354]
Running Alevin on Galaxy 20.05 produces an encoding issue:

```
galaxy.jobs.command_factory INFO 2020-10-02 16:31:50,729 Built script [/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/job_working_directory/000/6/tool_script.sh] for tool command [[ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8')" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . '/Users/pmoreno/miniconda3/bin/activate' '/Users/pmoreno/miniconda3/envs/mulled-v1-98d3118e419b1cc7a1a0dd314446a6d832c0ac4077b856227bc3b5e6b9d739d8' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; mkdir ./index && mkdir ./output && salmon index -i ./index --kmerLen '31' --gencode --transcripts '/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/files/000/dataset_5.dat' && cp '/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/files/000/dataset_3.dat' ./mate1.fastq.gz && gunzip ./mate1.fastq.gz && cp '/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/files/000/dataset_4.dat' ./mate2.fastq.gz && gunzip ./mate2.fastq.gz  && ln -s '/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/files/000/dataset_1.dat' ./alevinmap.tsv && salmon alevin -l ISR -i ./index -1 ./mate1.fastq -2 ./mate2.fastq -o ./output -p "${GALAXY_SLOTS:-4}" --dropseq --tgMap ./alevinmap.tsv --keepCBFraction '1.0'   --dumpFeatures  --dumpMtx --freqThreshold '3']
galaxy.jobs.runners ERROR 2020-10-02 17:39:49,369 (6/) Job wrapper finish method failed
Traceback (most recent call last):
  File "/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 540, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1686, in finish
    self._finish_dataset(
  File "/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1544, in _finish_dataset
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/private/var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpmydpkzhy/galaxy-dev/lib/galaxy/datatypes/tabular.py", line 1270, in set_meta
    for i, l in enumerate(dataset_fh):
  File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The above is from planemo, but we have seen the issue in usegalaxy.eu. @bgruening is also investigating it. I could imagine that many tools could write stuff with undesired encoding, so I presume that we need to be more defensive here maybe? Here is an example history https://humancellatlas.usegalaxy.eu/u/wendi.bacon/h/copy-of-ebi-training-scrna-fastq--anndata-mouse-example-with-geneids with and without the error. The error started appearing when usegalaxy.eu moved to 20.05, before that the same datasets worked (as the history shows). On the history, they were run with an older version of the tool, but the error happens as well with the new version.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/10062

**Comment by mvdbeek** [comment]
nevermind, same problem but that lines also needs a fix.

**Comment by mvdbeek** [comment]
Nope, this is fine, that's a bug in alevin. https://github.com/bgruening/galaxytools/blob/5dfee8ad03865f59c3e1ac9dd5865fd40e4616ef/tools/salmon/alevin.xml#L158
You can't write out a compressed file and assign it a uncompressed datatype.
This just happened to work on python 2, but I don't think we can fix this in Galaxy.

**Comment by pcm32** [comment]
thanks for the tip @mvdbeek, you rock, well get to it.

**Comment by nomadscientist** [comment]
Yes, Marius, this has been destroying me for months! Yay!
