### ISSUE TITLE
ValueError: Tool requires inputs to be in valid state

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10388]
I am having trouble with jobs transiently failing. I have a job stuck in 'queued' state, rerunning the workflow I am now encountering this exception:

Galaxy 20.09, k8s job runner

Workflow scheduler log:
```
galaxy.tools.execute DEBUG 2020-10-09 04:34:55,829 Executed 1 job(s) for tool toolshed.g2.bx.psu.edu/repos/brinkmanlab/awkscript/awkscript/1.0 request (177.971 ms)
galaxy.workflow.run DEBUG 2020-10-09 04:34:55,859 Workflow step 1814 of invocation 350 invoked (231.522 ms)
galaxy.workflow.run DEBUG 2020-10-09 04:34:55,938 Workflow step 2007 of invocation 348 invoked (2434168.716 ms)
galaxy.workflow.run DEBUG 2020-10-09 04:34:55,975 Marking step 2010 outputs of invocation 348 delayed (tool [__BUILD_LIST__] inputs are not ready, this special tool requires inputs to be ready)
galaxy.workflow.run DEBUG 2020-10-09 04:34:56,021 Marking step 2012 outputs of invocation 348 delayed (dependent step [2010] delayed, so this step must be delayed)
galaxy.workflow.run DEBUG 2020-10-09 04:34:56,035 Marking step 2014 outputs of invocation 348 delayed (dependent step [2012] delayed, so this step must be delayed)
galaxy.workflow.run ERROR 2020-10-09 04:34:56,469 Failed to schedule Workflow[id=107], problem occurred on WorkflowStep[index=10,type=tool].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1742, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2770, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2767, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.run ERROR 2020-10-09 04:34:56,506 Failed to schedule Workflow[id=114,name=IslandCompare unpacked w. BLAST (imported from uploaded file) (imported from uploaded file)], problem occurred on WorkflowStep[index=28,type=subworkflow].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 511, in execute
    subworkflow_invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1742, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2770, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2767, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.run ERROR 2020-10-09 04:34:56,506 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 511, in execute
    subworkflow_invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1742, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2770, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2767, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.scheduling_manager DEBUG 2020-10-09 04:34:56,570 Workflow invocation [348] scheduled
```

**Comment by innovate-invent** [comment]
This may be due to a race condition in the internal metadata fallback.
All jobs are currently failing to generate metadata.
The metadata step appears to be missing from the job script.

**Comment by innovate-invent** [comment]
@afgane @almahoud @nuwang Are any of you able to confirm that the k8s runner depends on the metadata fallback?

**Comment by innovate-invent** [comment]
Setting `retry_job_output_collection = 10` in the galaxy config sidesteps this issue. I will leave this open as there should be better handling and logging of this situation.

**Comment by innovate-invent** [comment]
Setting `retry_job_output_collection = 10` and `retry_metadata_internally = false` yields the following:

```
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1742, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2773, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2770, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.run ERROR 2020-10-13 22:00:21,836 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1742, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2773, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2770, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.scheduling_manager DEBUG 2020-10-13 22:00:21,894 Workflow invocation [388] scheduled
galaxy.jobs DEBUG 2020-10-13 22:04:49,554 Pausing Job '232722', Input dataset 'ERR1036024.gbk Record Info' failed to properly set metadata, Input dataset 'ERR1036025.gbk Record Info' failed to properly set metadata, Input dataset 'ERR1036026.gbk Record Info' failed to properly set metadata
```

**Comment by nuwang** [comment]
@innovate-invent I don't think we've run into this, but then, we haven't started using 20.09 yet. I assume you're only seeing this on 20.09?

Regarding metadata, I've not looked much into the internals of Galaxy's metadata handling, and therefore, can't really provide any particularly useful reply, but my running assumption was also that the k8s runner depends on the fallback, and that was what triggered the whole job id issue - a metadata job was being generated with the same job name as the original job.

**Comment by innovate-invent** [comment]
I am only able to test it on 20.09 due to https://github.com/galaxyproject/galaxy/issues/10245.

How is the metadata job scheduled? What container is being used? I believe the fallback runs within the workflow scheduler instance.

**Comment by pcm32** [comment]
What is a metadata job? is it something like changing a dataset's datatype? Shouldn't that run in the local runner really (since it requires galaxy code for that) or are metadata jobs something different? Thanks!

**Comment by innovate-invent** [comment]
I am not sure, you referred to it
> a metadata job was being generated

**Comment by innovate-invent** [comment]
@mvdbeek you could answer @pcm32 question more accurately

**Comment by innovate-invent** [comment]
Galaxy 21.01 also throws this error, no workflow jobs are marked as 'paused'
```
galaxy.workflow.run ERROR 2021-05-25 08:55:16,296 [pN:galaxy-worker-7d464bbf5-n8vs4,p:6,tN:WorkflowRequestMonitor.monitor_thread] Failed to schedule Workflow[id=7,name=IslandCompare], problem occurred on WorkflowStep[index=15,type=tool].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 268, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1744, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 22, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2787, in check_inputs_ready
    check_dataset_state(input_dataset.state)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2784, in check_dataset_state
    raise ValueError(f"Tool requires inputs to be in valid state, but dataset {input_dataset} is in state '{input_dataset.state}'")
ValueError: Tool requires inputs to be in valid state, but dataset <galaxy.model.HistoryDatasetAssociation(235869) at 0x7f3db24d6fd0> is in state 'error'
galaxy.workflow.run ERROR 2021-05-25 08:55:16,298 [pN:galaxy-worker-7d464bbf5-n8vs4,p:6,tN:WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 268, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1744, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 22, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2787, in check_inputs_ready
    check_dataset_state(input_dataset.state)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2784, in check_dataset_state
    raise ValueError(f"Tool requires inputs to be in valid state, but dataset {input_dataset} is in state '{input_dataset.state}'")
ValueError: Tool requires inputs to be in valid state, but dataset <galaxy.model.HistoryDatasetAssociation(235869) at 0x7f3db24d6fd0> is in state 'error'
galaxy.workflow.scheduling_manager DEBUG 2021-05-25 08:55:16,352 [pN:galaxy-worker-7d464bbf5-n8vs4,p:6,tN:WorkflowRequestMonitor.monitor_thread] Workflow invocation [64] scheduled
```

**Comment by mvdbeek** [comment]
Can you check the logs for the job that created HistoryDatasetAssociation 235869 ? https://github.com/galaxyproject/galaxy/blob/release_21.01/lib/galaxy/jobs/runners/__init__.py#L769 should log why the job failed.

If the metadata job failed the job would be set to `metadata_failed` and this would have a yellow notification in the UI, so this looks like the job failed because of filesystem problems.

**Comment by mvdbeek** [comment]
Assuming this doesn't happen anymore I'd think the problem was a possible double-scheduling fixed in https://github.com/galaxyproject/galaxy/pull/12763/

**Comment by innovate-invent** [comment]
You might be right. The k8s runner does still depend on the metadata collection fallback but things appear to be working with whatever configuration I worked out back then.

**Comment by innovate-invent** [comment]
I do still see similar errors following a properly failed tool, the workflow has already failed though so it isn't a blocking problem.

```
galaxy.workflow.run ERROR 2022-09-08 08:41:36,703 [pN:galaxy-worker-0,p:8,tN:WorkflowRequestMonitor.monitor_thread] Failed to schedule Workflow[id=328,name=Pairwise align sequences from tree], problem occurred on WorkflowStep[index=5,type=tool].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 148, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 215, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1816, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 92, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 22, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2987, in check_inputs_ready
    check_dataset_state(input_dataset.state)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2984, in check_dataset_state
    raise ValueError(f"Tool requires inputs to be in valid state, but dataset {input_dataset} is in state '{input_dataset.state}'")
ValueError: Tool requires inputs to be in valid state, but dataset <galaxy.model.HistoryDatasetAssociation(1543701) at 0x7f75f32e74c0> is in state 'paused'
```
