### ISSUE TITLE
Tool download broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#10392]
When downloading a tool from the tool form as admin user (Options -> Download) I get:

on 20.05:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 170, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 402, in download
    tool_tarball = trans.app.toolbox.package_tool(trans, id)
  File "lib/galaxy/tools/toolbox/base.py", line 931, in package_tool
    return tool.to_archive()
  File "lib/galaxy/tools/__init__.py", line 1943, in to_archive
    for input_value in test.inputs[input]:
TypeError: 'TestCollectionDef' object is not iterable
```

on dev:

```
[ERROR] Unhandled object from iterator: '' (0x2b8e444e1ab0)
```

**Comment by nsoranzo** [comment]
Similar issue: https://github.com/galaxyproject/galaxy/issues/5959
