### ISSUE TITLE
Permission denied: 'database/object_store_cache' when using Google Cloud Storage

### ISSUE THREAD

**Issue by chrlarsen** [galaxyproject/galaxy#10547]
Hello,

I'm trying to configure Galaxy to use Google Cloud Storage as my backend after having local disk used as the main storage backend. 

When I try and upload data to test I receive the following error:
```
Traceback (most recent call last):
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 388, in __handle_waiting_jobs
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     self.dispatcher.put(self.job_wrappers.pop(job.id))
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 987, in put
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     self.job_runners[runner_name].put(job_wrapper)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 152, in put
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     job_wrapper.enqueue()
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/jobs/__init__.py", line 1461, in enqueue
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     self._set_object_store_ids(job)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/jobs/__init__.py", line 1483, in _set_object_store_ids
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     object_store_populator.set_object_store_id(dataset)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/objectstore/__init__.py", line 1098, in set_object_store_id
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     self.object_store.create(data.dataset)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/objectstore/__init__.py", line 276, in create
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     return self._invoke('create', obj, **kwargs)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/objectstore/__init__.py", line 270, in _invoke
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     return self.__getattribute__("_" + delegate)(obj=obj, **kwargs)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/server/lib/galaxy/objectstore/cloud.py", line 568, in _create
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     os.makedirs(cache_dir)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/venv/lib/python3.6/os.py", line 210, in makedirs
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     makedirs(head, mode, exist_ok)
Oct 23 21:09:29 galaxy-main uwsgi[7720]:   File "/srv/galaxy/venv/lib/python3.6/os.py", line 220, in makedirs
Oct 23 21:09:29 galaxy-main uwsgi[7720]:     mkdir(name, mode)
Oct 23 21:09:29 galaxy-main uwsgi[7720]: PermissionError: [Errno 13] Permission denied: 'database/object_store_cache'
```

My `object_store_conf.xml` is:
```xml
<?xml version="1.0"?>
<object_store type="hierarchical">
    <backends>
	    <object_store type="cloud" provider="google" order="0">
    		<auth credentials_file="/home/clarsen/galaxy-storage-key.json" />
    		<bucket name="bucket-name-here" use_reduced_redundancy="False" />
    		<cache path="database/object_store_cache" size="1000" />
    		<extra_dir type="job_work" path="database/job_working_directory_gce"/>
    		<extra_dir type="temp" path="database/tmp_gce"/>
	    </object_store>
	    <object_store type="disk" id="secondary" order="1">
                <files_dir path="database/files"/>
                <extra_dir type="temp" path="database/tmp"/>
                <extra_dir type="job_work" path="database/job_working_directory"/>
            </object_store>
    </backends>
</object_store>
```

Also I'm using ansible to deploy galaxy so my `galaxyservers.yml` is (some parts removed):
```yml
galaxy:
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    file_path: /data
    check_migrate_tools: false
    tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
  uwsgi:
    socket: 127.0.0.1:8080
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static={{ galaxy_server_dir }}/static
      - /favicon.ico={{ galaxy_server_dir }}/static/favicon.ico
    static-safe: client/galaxy/images
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2

galaxy_config_templates:
  - src: templates/galaxy/config/job_conf.xml.j2
    dest: "{{ galaxy_config.galaxy.job_config_file }}"
  - src: templates/galaxy/config/object_store_conf.xml.j2
    dest: "{{ galaxy_config.galaxy.object_store_config_file }}"
```

Thanks for you help with this.

**Comment by chrlarsen** [comment]
Thanks @mvdbeek I added a pre-task in my playbook to modify the permissions on the database folder and now it's working.
