### ISSUE TITLE
build-in Galaxy tool updates are confusing workflows

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#10566]
This workflow https://training.galaxyproject.org/training-material/topics/metabolomics/tutorials/msi-analyte-distribution/workflows/ has on older filter tool included.

![](https://files.gitter.im/598b5526d73408ce4f70baa7/DNzi/grafik.png)

Executing the workflow on this history https://usegalaxy.eu/u/bgruening/h/test-history will yield the following error.

```
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: Traceback (most recent call last):
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/error.py", line 153, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: app_iter = self.application(environ, sr_checker)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "/opt/galaxy/venv/lib64/python3.6/site-packages/paste/recursive.py", line 85, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.application(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/statsd.py", line 33, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: req = self.application(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "/opt/galaxy/venv/lib64/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.application(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/base.py", line 141, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.handle_request(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/base.py", line 220, in handle_request
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: body = method(trans, **kwargs)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/decorators.py", line 56, in call_and_format
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: rval = func(self, trans, *args, **kwargs)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/webapps/galaxy/controllers/authnz.py", line 135, in get_cilogon_idps
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: allowed_idps = trans.app.authnz_manager.get_allowed_idps()
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/authnz/managers.py", line 170, in get_allowed_idps
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.allowed_idps
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: AttributeError: 'AuthnzManager' object has no attribute 'allowed_idps'
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: The above exception was the direct cause of the following exception:
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: Traceback (most recent call last):
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.application(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.app(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.app(environ, start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/translogger.py", line 70, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return self.application(environ, replacement_start_response)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/error.py", line 163, in __call__
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: exc_info)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: File "lib/galaxy/web/framework/middleware/translogger.py", line 69, in replacement_start_response
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: return start_response(status, headers, exc_info)
Oct 28 09:59:55 sn04.bi.uni-freiburg.de uwsgi[2381694]: SystemError: <built-in function uwsgi_spit> returned a result with an error set
```

Opening the workflow and saving it again (no changes other than opening and saving) will yield to this message.

![grafik](https://user-images.githubusercontent.com/469983/97415251-44848b00-1905-11eb-932d-ee9eb4817bac.png)

**Comment by mvdbeek** [comment]
I think that exception may not be linked to the problem ? You do need to move any of the tool boxes slightly for the editor to detect anychanges.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/10569 would make the workflow executable without any changes. There's also an API parameter that let's the frontend chose whether an exact match is necessary, we can add that as an additional option.

**Comment by bgruening** [comment]
Closing and hoping 21.01 will make this smoother :)


Thanks @mvdbeek
