### ISSUE TITLE
unable to downgrade DB

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1058]
this happens on 15.10

```
Exception: Your database has version '130' but this code expects version '129'.  Please backup your database and then migrate the schema by running 'sh manage_db.sh upgrade'.

$ sh manage_db.sh downgrade --version=129

Traceback (most recent call last):
  File "./scripts/manage_db.py", line 33, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 30, in invoke_migrate_main
    main( repository=repo, url=db_url )
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 202, in downgrade
    return _migrate(url, repository, version, upgrade=False, err=err, **opts)
  File "<string>", line 2, in _migrate
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(*a, **kw)
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 345, in _migrate
    changeset = schema.changeset(version)
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 82, in changeset
    changeset = self.repository.changeset(database, start_ver, version)
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/repository.py", line 225, in changeset
    changes = [self.version(v).script(database, op) for v in versions]
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/repository.py", line 189, in version
    return self.versions.version(*p, **k)
  File "/Users/marten/devel/git/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/version.py", line 160, in version
    return self.versions[VerNum(vernum)]
KeyError: <VerNum(130)>

```

**Comment by dannon** [comment]
Because of the way migrations work, you have to downgrade prior to swapping over to the 15.10 branch.  Then you probably also have to rm *.pyc

**Comment by martenson** [comment]
I think I did both, let me try it again.

**Comment by martenson** [comment]
You are correct @dannon I checked out the 15.10 before I downgraded so I obviously did not have the migrate script :) We might want to improve the error handling of the script in this case. Seems fairly easy to identify.
