### ISSUE TITLE
PSA: toolshed security unhappy when decoding api key 'fakekey'...

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/galaxy#10591]
20.09 Galaxy - warning to anyone trying a fake authentication id  like 'fakekey' in the toolshed.

If I hack the toolshed api key (e.g. for docker...) to the imaginative 'fakekey' value, things break when a security check shows it really is fake.

Log below from a toolshed when ephemeris shed-load is installing a tool

I will generate a proper key and use that and this will affect almost nobody so probably not worth making configurable...
However if it does bite, it will show up as an uncaught api exception in the calling Galaxy when a tool is installed and it is easy to go down the wrong rabbit hole. Trust me. Don't bother.

```
[pid: 2171748|app: 0|req: 56/74] 127.0.0.1 () {32 vars in 422 bytes} [Fri Oct 30 19:04:18 2020] GET /api/repositories?key=fakekey => generated 395 bytes in 12 msecs (HTTP/1.1 200) 2 headers in 110 bytes (1 switches on core 1)
galaxy.web.framework.decorators ERROR 2020-10-30 19:04:18,909 [p:2171748,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Odd-length string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 294, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/tool_shed/webapp/api/repositories.py", line 932, in create
    repo, message = repository_util.create_repository(app=self.app,
  File "lib/tool_shed/util/repository_util.py", line 186, in create_repository
    .get(app.security.decode_id(category_id))
  File "lib/galaxy/security/idencoding.py", line 84, in decode_id
    return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
binascii.Error: decoding with 'hex' codec failed (Error: Odd-length string)
127.0.0.1 - - [30/Oct/2020:19:04:18 +1100] "POST /api/repositories?key=fakekey HTTP/1.1" 500 - "-" "python-requests/2.24.0"
[pid: 2171748|app: 0|req: 57/75] 127.0.0.1 () {36 vars in 476 bytes} [Fri Oct 30 19:04:18 2020] POST /api/repositories?key=fakekey => generated 71 bytes in 158 msecs (HTTP/1.1 500) 2 headers in 129 bytes (1 switches on core 0)
```)

**Comment by fubar2** [comment]
ah. no. something else..

**Comment by bernt-matthias** [comment]
Seen the same on 20.05 .. I do not get your explanation. Could you help me?

**Comment by fubar2** [comment]
Hi @bernt-matthias! This was a while back but I think I was trying to write a category id mistakenly = "fakekey" api key when making a new toolshed repository with bioblend - fixed when I sorted out the call properly. I'm using fakekey for all api keys in a docker instance and it seems to work fine in 20.09 toolshed bioblend calls.
