### ISSUE TITLE
Object store cache size attribute not respected

### ISSUE THREAD

**Issue by DanBerrios** [galaxyproject/galaxy#10636]
We have this S3 Object store defined/configed into our Galaxy instance and it is functional:

```
<object_store type="cloud" provider="aws" id="primary" order="0">

...
             <cache path="database/object_store_cache" size="100" />
             <extra_dir type="job_work" path="database/job_working_directory_s3"/>
             <extra_dir type="temp" path="database/tmp_s3"/>
```

However, the size (supposedly set above to 100GB) of our `database/object store_cache dir` is currently 220 GB.  Why is the size attribute not respected? Is there documentation about this attribute and what can I do to remedy the situation?

Thanks!  Dan

**Comment by DanBerrios** [comment]
Can I manually remove files from the object store cache and not affect Galaxy function?

**Comment by DanBerrios** [comment]
Update: We see this error in our log:

```
galaxy.objectstore.cloud INFO 2020-11-04 15:47:35,905 [p:54130,w:0,m:3] [Thread-4] Initiating cache cleaning: current cache size: 175.97GB; clean until smaller than: 90.00GB
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "lib/galaxy/objectstore/cloud.py", line 274, in __cache_monitor
    self.__clean_cache(file_list, delete_this_much)
  File "lib/galaxy/objectstore/cloud.py", line 298, in __clean_cache
    deleted_amount += entry[2]
IndexError: tuple index out of range
```

We edited lib/galaxy/objectstore/cloud.py and were able to get the cache trimmed to under the specified limit by this code change:

```
for entry in file_list:
            if deleted_amount < delete_this_much:
                try:
                    deleted_amount += entry[2]
                    os.remove(entry[1])

However, now our Galaxy reports errors when trying to find some datasets in the cache:


galaxy.objectstore.cloud ERROR 2020-11-10 13:52:08,754 [p:66811,w:1,m:0] [uWSGIWorker1Core1] Problem downloading key '025/dataset_25331.dat' from S3 bucket 'arc-cio-genelab-galaxy-s3'
```
Traceback (most recent call last):
  File "lib/galaxy/objectstore/cloud.py", line 452, in _download
    key.save_content(downloaded_file_handle)
  File "/data/galaxy/.venv/lib/python3.6/site-packages/cloudbridge/base/resources.py", line 707, in save_content
    shutil.copyfileobj(self.iter_content(), target_stream)
  File "/data/galaxy/.venv/lib64/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
TypeError: write() argument must be str, not bytes
```

```

**Comment by DanBerrios** [comment]
It seems like our fix to cloud.py cache cleaning routine has caused the cache monitor to now throw intermittent errors regarding files to be deleted during cleaning, but are not found or (?) have permission violations.  I don't know that these are of any consequence, but thought I would report them.
