### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10647]
Galaxy 20.09

I have an unusual recurring log entry: `sqlitedict INFO 2020-11-06 18:12:27,098 opening Sqlite table 'unnamed' in '/data/tool_cache/cache.sqlite'`

And an exception:
```
galaxy.tools.data DEBUG 2020-11-06 18:11:35,670 Encountered a file element (<file from_config="refgenie_config_file"/>) that does not contain a path value when loading tool data table 'hisat2_indexes'.
galaxy.tools.data DEBUG 2020-11-06 18:11:35,670 Reloaded tool data table 'hisat2_indexes' from files.
galaxy.tools.data DEBUG 2020-11-06 18:11:35,673 Loaded 1 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/card/rgi/715bc9aeef69/rgi_databases.loc' for 'rgi_databases'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,677 Loaded 1 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/card/rgi/715bc9aeef69/rgi_databases.loc' for 'rgi_databases'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,677 Attempted to add fields (['card_data-2020-november-06-17:43:24', 'CARD_data-2020-November-06-17:43:24', '/data/tool-data/rgi_databases/card_data-2020-november-06-17:43:24']) to data table 'rgi_databases', but this entry already exists and allow_duplicates is False.
galaxy.tools.data DEBUG 2020-11-06 18:11:35,680 Loaded 1 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/card/rgi/715bc9aeef69/rgi_databases.loc' for 'rgi_databases'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,680 Attempted to add fields (['card_data-2020-november-06-17:43:24', 'CARD_data-2020-November-06-17:43:24', '/data/tool-data/rgi_databases/card_data-2020-november-06-17:43:24']) to data table 'rgi_databases', but this entry already exists and allow_duplicates is False.
galaxy.tools.data DEBUG 2020-11-06 18:11:35,680 Reloaded tool data table 'rgi_databases' from files.
galaxy.tools.data DEBUG 2020-11-06 18:11:35,683 Loaded 0 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/iuc/bedtools/87ee588b3d45/all_gff.loc' for 'all_gff'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,686 Loaded 0 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/iuc/bedtools/87ee588b3d45/all_gff.loc' for 'all_gff'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,689 Loaded 0 lines from '/data/shed-tool-data/toolshed.g2.bx.psu.edu/repos/iuc/bedtools/87ee588b3d45/all_gff.loc' for 'all_gff'
galaxy.tools.data DEBUG 2020-11-06 18:11:35,689 Reloaded tool data table 'all_gff' from files.
galaxy.queue_worker DEBUG 2020-11-06 18:11:35,690 Finished data table reload for ['all_fasta', 'bfast_indexes', 'blastdb', 'blastdb_p', 'blastdb_d', 'bwa_indexes', 'bwa_indexes_color', 'indexed_maf_files', 'ngs_sim_fasta', 'perm_base_indexes', 'perm_color_indexes', 'picard_indexes', 'srma_indexes', 'mosaik_indexes', 'twobit', 'igv_broad_genomes', 'liftOver', 'bam_iobio', 'vcf_iobio', 'biom_simple_display', 'intermine_simple_display', 'icn3d_simple_display', '__dbkeys__', 'fasta_indexes', 'bowtie2_indexes', 'bwa_mem_indexes', 'hisat2_indexes', 'rgi_databases', 'all_gff']
sqlitedict INFO 2020-11-06 18:11:35,786 opening Sqlite table 'unnamed' in '/data/tool_cache/tmpkscldr5wcache.sqlite.tmp'
sqlitedict.SqliteMultithread DEBUG 2020-11-06 18:11:35,834 received: --close--, send: --no more--
galaxy.tools.data_manager.manager DEBUG 2020-11-06 18:11:35,836 Loaded Data Manager: toolshed.g2.bx.psu.edu/repos/brinkmanlab/microbedb/data_manager/microbedb_all_fasta/1.0.0
galaxy.queue_worker DEBUG 2020-11-06 18:11:35,837 Data managers reloaded (1189.152 ms)
sqlitedict.SqliteMultithread DEBUG 2020-11-06 18:11:39,120 received: --close--, send: --no more--
galaxy.queue_worker INFO 2020-11-06 18:12:26,434 Instance 'galaxy-worker-df87b54f7-7f2st' received 'reload_toolbox' task, executing now.
galaxy.queue_worker DEBUG 2020-11-06 18:12:26,434 Executing toolbox reload on 'galaxy-worker-df87b54f7-7f2st'
galaxy.tools WARNING 2020-11-06 18:12:26,626 The default shed tool config file (/data/config/shed_tool_conf.xml) has been added to the tool_config_file option, if this is not the desired behavior, please set shed_tool_config_file to your primary shed-enabled tool config file
galaxy.tools.toolbox.base INFO 2020-11-06 18:12:26,626 Parsing the tool configuration /srv/galaxy/config/tool_conf.xml
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,627 Tool path for tool configuration /srv/galaxy/config/tool_conf.xml is None
galaxy.tools.toolbox.base INFO 2020-11-06 18:12:26,628 Parsing the tool configuration /data/config/shed_tool_conf.xml
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,632 Tool path for shed tool configuration /data/config/shed_tool_conf.xml is /data/shed_tools
sqlitedict INFO 2020-11-06 18:12:26,636 opening Sqlite table 'unnamed' in '/data/tool_cache/cache.sqlite'
sqlitedict INFO 2020-11-06 18:12:26,840 opening Sqlite table 'unnamed' in '/data/tool_cache/tmpyy7ix2l4cache.sqlite.tmp'
sqlitedict.SqliteMultithread DEBUG 2020-11-06 18:12:26,888 received: --close--, send: --no more--
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,981 Reading tools from config files finished (355.062 ms)
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,981 Loading section: Get Data
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,981 Loading section: Collection Operations
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,982 Loading section: Text Manipulation
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,982 Loading section: Filter and Sort
galaxy.tools.toolbox.base DEBUG 2020-11-06 18:12:26,982 Loading tool panel finished (1.682 ms)
galaxy.datatypes.registry DEBUG 2020-11-06 18:12:26,994 Loaded external metadata tool: __SET_METADATA__
galaxy.tools.special_tools DEBUG 2020-11-06 18:12:26,996 Loaded history export tool: __EXPORT_HISTORY__
galaxy.tools.special_tools DEBUG 2020-11-06 18:12:26,998 Loaded history import tool: __IMPORT_HISTORY__
galaxy.tools.special_tools DEBUG 2020-11-06 18:12:27,000 Loaded data fetch tool: __DATA_FETCH__
sqlitedict INFO 2020-11-06 18:12:27,098 opening Sqlite table 'unnamed' in '/data/tool_cache/cache.sqlite'
Exception in thread Thread-136:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/srv/galaxy/venv/lib/python3.8/site-packages/sqlitedict.py", line 396, in run
    conn.execute('PRAGMA journal_mode = %s' % self.journal_mode)
sqlite3.OperationalError: disk I/O error
```

**Comment by mvdbeek** [comment]
That happens if our tool cache backend couldn't acquire a lock on the database, for instance because the cache is on a network share. https://github.com/galaxyproject/galaxy/pull/10808 would disable the cache in that case.
