### ISSUE TITLE
Example resubmit condition invalid

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10688]
Using the k8s runner on Galaxy 20.09 with a destination resubmit tag:
```xml
<resubmit  condition="unknown_error and attempt &lt;= 4" delay="attempt * 15" />
```
I get the following exception
```
galaxy.jobs.runners ERROR 2020-11-10 20:32:25,946 Caught exception in runner state handler
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/jobs/runners/__init__.py", line 461, in _handle_runner_state
    handler(self.app, self, job_state)
  File "/srv/galaxy/lib/galaxy/jobs/runners/state_handlers/resubmit.py", line 76, in failure
    _handle_resubmit_definitions(resubmit_definitions, app, job_runner, job_state)
  File "/srv/galaxy/lib/galaxy/jobs/runners/state_handlers/resubmit.py", line 89, in _handle_resubmit_definitions
    if condition and not expression_context.safe_eval(condition):
  File "/srv/galaxy/lib/galaxy/jobs/runners/state_handlers/resubmit.py", line 203, in safe_eval
    return safe_eval(condition, self._lazy_context)
  File "/srv/galaxy/lib/galaxy/jobs/runners/state_handlers/_safe_eval.py", line 140, in safe_eval
    raise Exception("Invalid expression [%s], only a very simple subset of Python is allowed." % expression)
Exception: Invalid expression [unknown_error and attempt <= 4], only a very simple subset of Python is allowed.
```

This is nearly identical to https://github.com/galaxyproject/galaxy/blob/ba2ba1ed2747568ccdc831f387502e9862afa216/lib/galaxy/config/sample/job_conf.xml.sample_advanced#L718

**Comment by innovate-invent** [comment]
Resolved by #10709
