### ISSUE TITLE
[20.09] uploading BAM files to data libraries do not work

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#10708]
```
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: galaxy.jobs.handler INFO 2020-11-12 19:35:26,604 (12738116) Job dispatched
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: galaxy.jobs.runners ERROR 2020-11-12 19:35:26,789 (12738116) Failure preparing job
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: Traceback (most recent call last):
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1040, in unicodify
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: value = str(value)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: return getattr(self, mainMethName)()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "DynamicallyCompiledCheetahTemplate.py", line 86, in respond
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: NameMapper.NotFound: cannot find 'get' while searching for 'get'
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: During handling of the above exception, another exception occurred:
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: Traceback (most recent call last):
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1042, in unicodify
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: value = str(value)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: return getattr(self, mainMethName)()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "DynamicallyCompiledCheetahTemplate.py", line 86, in respond
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: NameMapper.NotFound: cannot find 'get'
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: During handling of the above exception, another exception occurred:
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: Traceback (most recent call last):
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 236, in prepare_job
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: job_wrapper.prepare()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1112, in prepare
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 450, in build
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: raise e
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 446, in build
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: self.__build_config_files()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 511, in __build_config_files
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: config_text, is_template = self.__build_config_file_text(content)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 600, in __build_config_file_text
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: file_sources_dict = self.app.file_sources.to_dict(for_serialization=True, user_context=user_context)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/files/__init__.py", line 144, in to_dict
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: 'file_sources': self.plugins_to_dict(for_serialization=for_serialization, user_context=user_context),
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/files/__init__.py", line 138, in plugins_to_dict
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: el = file_source.to_dict(for_serialization=for_serialization, user_context=user_context)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/files/sources/__init__.py", line 97, in to_dict
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: rval.update(self._serialization_props(user_context=user_context))
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/files/sources/_pyfilesystem2.py", line 69, in _serialization_props
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: effective_props[key] = self._evaluate_prop(val, user_context=user_context)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/files/sources/__init__.py", line 132, in _evaluate_prop
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: rval = fill_template(prop_val, context=template_context, futurized=True)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/util/template.py", line 108, in fill_template
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: raise first_exception or e
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/util/template.py", line 81, in fill_template
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: return unicodify(t)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1048, in unicodify
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: msg = "Value '{}' could not be coerced to Unicode: {}('{}')".format(value, type(e).__name__, e)
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: return getattr(self, mainMethName)()
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: File "DynamicallyCompiledCheetahTemplate.py", line 86, in respond
Nov 12 19:35:26 sn04.bi.uni-freiburg.de python[2729942]: NameMapper.NotFound: cannot find 'get'
```

**Comment by bernt-matthias** [comment]
Same happens when uploading from a link when not logged in:

```
Traceback (most recent call last): 
   File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1040, in unicodify 
     value = str(value) 
   File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__ 
     return getattr(self, mainMethName)() 
   File "cheetah_DynamicallyCompiledCheetahTemplate_1605440246_6623545_50439.py", line 86, in respond 
 NameMapper.NotFound: cannot find 'get' while searching for 'get' 
  
 During handling of the above exception, another exception occurred: 
  
 Traceback (most recent call last): 
   File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1042, in unicodify 
     value = str(value) 
   File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__ 
     return getattr(self, mainMethName)() 
   File "cheetah_DynamicallyCompiledCheetahTemplate_1605440246_6623545_50439.py", line 86, in respond 
 NameMapper.NotFound: cannot find 'get' 
  
 During handling of the above exception, another exception occurred: 
  
 Traceback (most recent call last): 
   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 236, in prepare_job 
     job_wrapper.prepare() 
   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1112, in prepare 
     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build() 
   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 450, in build 
     raise e 
   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 446, in build 
     self.__build_config_files() 
   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 511, in __build_config_files 
     config_text, is_template = self.__build_config_file_text(content) 
   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 600, in __build_config_file_text 
     file_sources_dict = self.app.file_sources.to_dict(for_serialization=True, user_context=user_context) 
   File "/opt/galaxy/server/lib/galaxy/files/__init__.py", line 144, in to_dict 
     'file_sources': self.plugins_to_dict(for_serialization=for_serialization, user_context=user_context), 
   File "/opt/galaxy/server/lib/galaxy/files/__init__.py", line 138, in plugins_to_dict 
     el = file_source.to_dict(for_serialization=for_serialization, user_context=user_context) 
   File "/opt/galaxy/server/lib/galaxy/files/sources/__init__.py", line 97, in to_dict 
     rval.update(self._serialization_props(user_context=user_context)) 
   File "/opt/galaxy/server/lib/galaxy/files/sources/_pyfilesystem2.py", line 69, in _serialization_props 
     effective_props[key] = self._evaluate_prop(val, user_context=user_context) 
   File "/opt/galaxy/server/lib/galaxy/files/sources/__init__.py", line 132, in _evaluate_prop 
     rval = fill_template(prop_val, context=template_context, futurized=True) 
   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 108, in fill_template 
     raise first_exception or e 
   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 81, in fill_template 
     return unicodify(t) 
   File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1048, in unicodify 
     msg = "Value '{}' could not be coerced to Unicode: {}('{}')".format(value, type(e).__name__, e) 
   File "/opt/galaxy/venv/lib64/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__ 
     return getattr(self, mainMethName)() 
   File "cheetah_DynamicallyCompiledCheetahTemplate_1605440246_6623545_50439.py", line 86, in respond 
 NameMapper.NotFound: cannot find 'get' 
```

**Comment by mvdbeek** [comment]
Can you make sure the cheetah C extension is properly installed ?
```
>>> from Cheetah._namemapper import NotFound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```
if that doesn't raise an exception we'd have to look further.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/issues/10595 might be the problem here as well ... at least for anonymous users.

**Comment by mvdbeek** [comment]
I suppose that's not a problem anymore ?
