### ISSUE TITLE
[20.09] Filter empty fails to schedule in subworkflow for large collections

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10738]
This is the excerpt of the subworkflow I am running:
![image](https://user-images.githubusercontent.com/1768820/99432780-7b750d80-28c1-11eb-81ea-f904b19879ff.png)

```
GET /api/invocations/{id}
8    
model_class    "WorkflowInvocationStep"
id    "9cf1173826c73159"
update_time    "2020-11-17T11:25:03.658747"
job_id    null
workflow_step_id    "fbed7d1754ce1275"
subworkflow_invocation_id    null
state    "scheduled"
action    null
order_index    8
workflow_step_label    "BLAST_Hit_Filter"
workflow_step_uuid    "67da9292-6f26-445e-b257-9647441df26e"
9    
model_class    "WorkflowInvocationStep"
id    "545812229749f3fe"
update_time    "2020-11-17T11:25:03.663948"
job_id    null
workflow_step_id    "7d14e995f1bd8ec9"
subworkflow_invocation_id    null
state    "new"
action    null
order_index    9
workflow_step_label    null
workflow_step_uuid    "059f43e7-4b59-4adb-95be-e07f8a189e61"
```

```
GET /api/invocations/{id}/steps/545812229749f3fe
model_class | "WorkflowInvocationStep"
id | "545812229749f3fe"
update_time | "2020-11-17T11:25:03.663948"
job_id | null
workflow_step_id | "7d14e995f1bd8ec9"
subworkflow_invocation_id | null
state | "new"
action | null
order_index | 9
workflow_step_label | null
workflow_step_uuid | "059f43e7-4b59-4adb-95be-e07f8a189e61"
outputs | {}
output_collections | {}
jobs | []
```

The output of the BLAST_Hit_Filter step reports success for all jobs. Manually running the Filter Empty tool on the output succeeds, removing 4 datasets. This tool fails to schedule in the workflow for a collection size of 1000 but succeeds for a collection size of 12. No error output is generated in the logs.

Possibly related to https://github.com/galaxyproject/galaxy/issues/8390

**Comment by innovate-invent** [comment]
@mvdbeek setting maximum_workflow_jobs_per_scheduling_iteration = 10 does not cause a collection of 15 datasets to fail

**Comment by innovate-invent** [comment]
I ran a smaller dataset (~700) and found this exception at a different stage of the workflow.
```
galaxy.workflow.run ERROR 2020-11-17 22:37:18,366 Failed to schedule Workflow[id=42,name=IslandCompare unpacked w. BLAST], problem occurred on WorkflowStep[index=14,type=tool].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1749, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2779, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2776, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.run ERROR 2020-11-17 22:37:18,366 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1749, in execute
    execution_tracker = execute(
  File "/srv/galaxy/lib/galaxy/tools/execute.py", line 82, in execute
    tool_action.check_inputs_ready(
  File "/srv/galaxy/lib/galaxy/tools/actions/model_operations.py", line 23, in check_inputs_ready
    tool.check_inputs_ready(inp_data, inp_dataset_collections)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2779, in check_inputs_ready
    check_dataset_instance(input_dataset)
  File "/srv/galaxy/lib/galaxy/tools/__init__.py", line 2776, in check_dataset_instance
    raise ValueError("Tool requires inputs to be in valid state.")
ValueError: Tool requires inputs to be in valid state.
galaxy.workflow.scheduling_manager DEBUG 2020-11-17 22:37:18,426 Workflow invocation [94] scheduled
```

This dataset has ran without issue on an earlier commit of 20.09
