### ISSUE TITLE
ValueError: Step with id not found in inputs_step_id 

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10899]
I just encountered this exception in the job handler log:
```
galaxy.workflow.scheduling_manager DEBUG 2020-12-10 20:39:00,150 Attempting to schedule workflow invocation [(15,)]
galaxy.workflow.run ERROR 2020-12-10 20:39:00,176 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 174, in invoke
    remaining_steps = self.progress.remaining_steps()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 316, in remaining_steps
    self._recover_mapping(invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 514, in _recover_mapping
    step_invocation.workflow_step.module.recover_mapping(step_invocation, self)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 640, in recover_mapping
    progress.set_outputs_for_input(invocation_step, already_persisted=True)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 417, in set_outputs_for_input
    raise ValueError(message)
ValueError: Step with id WorkflowStep[index=0,type=data_input] not found in inputs_step_id ({913: <galaxy.model.HistoryDatasetCollectionAssociation(8) at 0x7fceb01bdd60>, 912: 'False', 914: ''})
galaxy.workflow.scheduling_manager DEBUG 2020-12-10 20:39:00,201 Workflow invocation [15] scheduled
galaxy.jobs.runners.util.process_groups DEBUG 2020-12-10 20:39:07,165 check_pg(): No process found in process group 1382
```

I suppose the issue is that the error wasn't handled and reported back via the API.

<details><summary>invocation state</summary>

```json
{
   "model_class":"WorkflowInvocation",
   "id":"64c86c22d0c51a1b",
   "update_time":"2020-12-10T20:33:49.173067",
   "create_time":"2020-12-10T20:33:46.086145",
   "workflow_id":"302a4f7904f8e501",
   "history_id":"26ad5af7a1e8964f",
   "uuid":"0058a468-3b27-11eb-b7b3-0242ac1b0003",
   "state":"failed",
   "steps":[
      {
         "model_class":"WorkflowInvocationStep",
         "id":"56b2a5f4cbf46ef2",
         "update_time":"2020-12-10T20:33:48.100519",
         "job_id":null,
         "workflow_step_id":"37c67f9abefcf00a",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":21,
         "workflow_step_label":"Extract islands with children",
         "workflow_step_uuid":"78482ede-172b-4b3e-962a-e7c6f0c4e81b"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"8f736e7e9975bfdb",
         "update_time":"2020-12-10T20:33:48.100200",
         "job_id":null,
         "workflow_step_id":"49e5ff17e2dd84af",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":20,
         "workflow_step_label":"Generate final GFF",
         "workflow_step_uuid":"755d301c-9191-4fa7-9215-86125eb6a284"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"3ec53a5b872f89df",
         "update_time":"2020-12-10T20:33:48.099877",
         "job_id":null,
         "workflow_step_id":"939bada76d545cb2",
         "subworkflow_invocation_id":"b21d83de7e266ec1",
         "state":"new",
         "action":null,
         "order_index":19,
         "workflow_step_label":null,
         "workflow_step_uuid":"85cebc62-d27d-475c-b3eb-58eb89c5a2d4"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"232d832a061543d3",
         "update_time":"2020-12-10T20:33:48.099542",
         "job_id":null,
         "workflow_step_id":"74455ff7ff020b1c",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":18,
         "workflow_step_label":"Extract Islands",
         "workflow_step_uuid":"7e349f7a-1898-4484-b369-31d0ad7dc107"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"cc3dd3c041bb278d",
         "update_time":"2020-12-10T20:33:48.099238",
         "job_id":null,
         "workflow_step_id":"819858d83a67c04f",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":17,
         "workflow_step_label":"Merge user annotations",
         "workflow_step_uuid":"ede039a4-0975-47f7-ad2c-9cfdda3f51c1"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"ede692845b964865",
         "update_time":"2020-12-10T20:33:48.098962",
         "job_id":null,
         "workflow_step_id":"6e6640fff5df793a",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":16,
         "workflow_step_label":null,
         "workflow_step_uuid":"291adce8-c75a-4d98-b2b9-d1ad55daaa28"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"a7fe659962e7d00a",
         "update_time":"2020-12-10T20:33:48.098720",
         "job_id":null,
         "workflow_step_id":"08ec7f81f44ecf5e",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":15,
         "workflow_step_label":"Output newick",
         "workflow_step_uuid":"1578a7bf-54ae-482d-9a52-176732151f6e"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"2efa62c0e1a3ba36",
         "update_time":"2020-12-10T20:33:48.098494",
         "job_id":null,
         "workflow_step_id":"0e3010bdcbc882da",
         "subworkflow_invocation_id":"64f7e50d9a08be21",
         "state":"new",
         "action":null,
         "order_index":14,
         "workflow_step_label":"",
         "workflow_step_uuid":"ffc5dd81-366d-4ee4-9b40-26e7c2b9922c"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"b20a1a2924576801",
         "update_time":"2020-12-10T20:33:48.098267",
         "job_id":null,
         "workflow_step_id":"bf341d254250e4af",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":13,
         "workflow_step_label":null,
         "workflow_step_uuid":"af0fdfe7-02a2-45e9-a7ac-8386e2897da5"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"8df399e984591a56",
         "update_time":"2020-12-10T20:33:48.098038",
         "job_id":null,
         "workflow_step_id":"80ec89a9b2fe7885",
         "subworkflow_invocation_id":"f75fd0845bb509e8",
         "state":"new",
         "action":null,
         "order_index":12,
         "workflow_step_label":"",
         "workflow_step_uuid":"771eece7-4018-425a-b57d-44c412e33654"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"bcba9a9ef16f5458",
         "update_time":"2020-12-10T20:33:48.097806",
         "job_id":null,
         "workflow_step_id":"68db60554c75f27c",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":11,
         "workflow_step_label":null,
         "workflow_step_uuid":"a757285e-0c57-44e9-853b-32bd7bb08f37"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"1fa298f4a3066367",
         "update_time":"2020-12-10T20:33:48.097574",
         "job_id":null,
         "workflow_step_id":"9f3a84a5d3093ccd",
         "subworkflow_invocation_id":"a77fe4b4287e21fd",
         "state":"new",
         "action":null,
         "order_index":10,
         "workflow_step_label":null,
         "workflow_step_uuid":"a570bdbc-80aa-4720-ae90-f02f2842e0c3"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"5c8ddab396a6ab3b",
         "update_time":"2020-12-10T20:33:48.097324",
         "job_id":null,
         "workflow_step_id":"939563e96c92773f",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":9,
         "workflow_step_label":"Append collection ID to records",
         "workflow_step_uuid":"bac1e54e-252d-4646-a686-02069d965b89"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"bda33d974a814bf6",
         "update_time":"2020-12-10T20:33:48.097084",
         "job_id":null,
         "workflow_step_id":"1258b097aa46e925",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":8,
         "workflow_step_label":"To Fasta",
         "workflow_step_uuid":"c9a37b3f-b3df-4cde-a396-dd193bab3d29"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"3ccbd637bec39418",
         "update_time":"2020-12-10T20:33:48.096840",
         "job_id":null,
         "workflow_step_id":"787a2a45546997e6",
         "subworkflow_invocation_id":"26ad5af7a1e8964f",
         "state":"new",
         "action":null,
         "order_index":7,
         "workflow_step_label":null,
         "workflow_step_uuid":"36c34ca9-0f15-46e5-b351-e5bbf2f9bd76"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"83b228a219001c52",
         "update_time":"2020-12-10T20:33:48.096571",
         "job_id":null,
         "workflow_step_id":"3538f9b22fbc8f03",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":6,
         "workflow_step_label":"To GFF3",
         "workflow_step_uuid":"a91949e4-0b7a-4760-9e35-39c4fadeed7b"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"f644d62c039082e4",
         "update_time":"2020-12-10T20:33:48.096265",
         "job_id":null,
         "workflow_step_id":"8a630c3729e7962a",
         "subworkflow_invocation_id":null,
         "state":"new",
         "action":null,
         "order_index":5,
         "workflow_step_label":"Assign unique IDs",
         "workflow_step_uuid":"61f1a6e6-fc02-49b4-9fb2-ee2a2f428944"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"f75fd0845bb509e8",
         "update_time":"2020-12-10T20:33:47.325246",
         "job_id":null,
         "workflow_step_id":"32fde80c54da6db0",
         "subworkflow_invocation_id":"faa9b4764716b99c",
         "state":"new",
         "action":null,
         "order_index":4,
         "workflow_step_label":"",
         "workflow_step_uuid":"68296032-9ba4-42d0-bb88-aa06bf900b1a"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"a77fe4b4287e21fd",
         "update_time":"2020-12-10T20:33:47.324821",
         "job_id":null,
         "workflow_step_id":"3c7da0421805c670",
         "subworkflow_invocation_id":null,
         "state":"scheduled",
         "action":null,
         "order_index":3,
         "workflow_step_label":"Reference Genome",
         "workflow_step_uuid":"0682ba2e-a512-456b-9816-55748542b9c2"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"26ad5af7a1e8964f",
         "update_time":"2020-12-10T20:33:47.324393",
         "job_id":null,
         "workflow_step_id":"3dd65a9c9cf99e6b",
         "subworkflow_invocation_id":null,
         "state":"scheduled",
         "action":null,
         "order_index":2,
         "workflow_step_label":"Input datasets",
         "workflow_step_uuid":"633a027c-0bef-4597-8e6c-7b200350abfe"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"faa9b4764716b99c",
         "update_time":"2020-12-10T20:33:47.323927",
         "job_id":null,
         "workflow_step_id":"b7ffbb111b35d0f9",
         "subworkflow_invocation_id":null,
         "state":"scheduled",
         "action":null,
         "order_index":1,
         "workflow_step_label":"Newick Identifiers",
         "workflow_step_uuid":"151d9489-a33b-48e2-832b-86eed764a310"
      },
      {
         "model_class":"WorkflowInvocationStep",
         "id":"64c86c22d0c51a1b",
         "update_time":"2020-12-10T20:33:47.323111",
         "job_id":null,
         "workflow_step_id":"1bfca024e317559c",
         "subworkflow_invocation_id":null,
         "state":"scheduled",
         "action":null,
         "order_index":0,
         "workflow_step_label":"Phylogenetic tree in newick format",
         "workflow_step_uuid":"d3163825-4a01-4c28-86b9-0df56496c28d"
      }
   ],
   "inputs":{
      
   },
   "outputs":{
      
   },
   "output_collections":{
      
   },
   "output_values":{
      
   }
}
```

</details>

**Comment by innovate-invent** [comment]
Another attempt with the following request payload was made:
```json
{"history_id":"33bbfa2609e9c3ae","no_add_to_history":true,"inputs":{"0":{"id":"f644d62c039082e4","src":"hdca"},"1":"","3":"False"}}
```

and error:
```
galaxy.workflow.run ERROR 2020-12-10 22:38:23,661 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 174, in invoke
    remaining_steps = self.progress.remaining_steps()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 316, in remaining_steps
    self._recover_mapping(invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 514, in _recover_mapping
    step_invocation.workflow_step.module.recover_mapping(step_invocation, self)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 640, in recover_mapping
    progress.set_outputs_for_input(invocation_step, already_persisted=True)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 417, in set_outputs_for_input
    raise ValueError(message)
ValueError: Step with id WorkflowStep[index=2,type=data_input] not found in inputs_step_id ({1045: <galaxy.model.HistoryDatasetCollectionAssociation(17) at 0x7fce9169e370>, 1046: '', 1044: 'False'})
galaxy.workflow.scheduling_manager DEBUG 2020-12-10 22:38:23,681 Workflow invocation [36] scheduled
```

something is mangling the step ids

**Comment by selten** [comment]
I just encountered the same issue. I am using Galaxy 20.09. I have optional workflow inputs in place and tried to use the "full workflow form" instead of the shorthand one. It seems like the full workflow form doesn't work well with the optional data inputs.

**Comment by innovate-invent** [comment]
I tried the full workflow form with my workflow and it submits the workflow but stops scheduling as soon as it touches any step with optional inputs attached.

**Comment by selten** [comment]
In my workflow that was the first step, that's why I instantly got it

**Comment by innovate-invent** [comment]
@mvdbeek I think you mentioned that this was resolved. Can you link to the PR that resolved it?

**Comment by mvdbeek** [comment]
At this point I'm not sure what it was, but https://github.com/galaxyproject/galaxy/pull/14641 is certainly another fix that could prevent this.

**Comment by innovate-invent** [comment]
That PR looks like purely UI changes. This issue is with the API not allowing optional inputs to be omitted from the invocation request json. I have to pass null values in place of the optional inputs to the API otherwise the invocation fails.

**Comment by mvdbeek** [comment]
It is a submission change that certainly fixes https://github.com/galaxyproject/galaxy/issues/10899#issuecomment-791606529. It is supposed to work without specifying optional data inputs (https://github.com/mvdbeek/galaxy/blob/a1e446a3e9e1ca3672ffb1de7a5d848bb4190860/lib/galaxy_test/api/test_workflows.py#L3167-L3173), but I can see how that could fail if we need to delay scheduling steps with unset optional data inputs.

**Comment by mvdbeek** [comment]
Alright, I think I got this covered in https://github.com/galaxyproject/galaxy/pull/14641, the problem only occurs if scheduling has to be delayed and the optional input is not provided. https://github.com/galaxyproject/galaxy/pull/14641/files#diff-d5ce58fce5db2ae9472cdbe0c86a67aea53b0d6e503a3eac6ceb4468fe224abaR617-R652 tests this.
