### ISSUE TITLE
Downloading from local tool shed returns 500

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/galaxy#1092]
When I install a package from my local tool_shed installation, it ends up in Error state and galaxy gives the following error:

`tool_shed.util.hg_util DEBUG 2015-11-14 18:55:44,766 Error cloning repository: HTTP Error 500: Internal Server Error`

In tool_shed_webapp.log I see:

```
127.0.0.1 - - [14/nov/2015:18:55:44 +0200] "GET /repos/iuc/package_cramtools_3_0?cmd=batch HTTP/1.1" 200 42 "-" "mercurial/proto-1.0"
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 37749)
Traceback (most recent call last):
  File "/usr/local/src/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/src/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/src/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/local/src/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/usr/local/src/galaxy/.venv/local/lib/python2.7/site-packages/paste/urlmap.py", line 203, in __call__
    return app(environ, start_response)
  File "/usr/local/src/galaxy/lib/galaxy/webapps/tool_shed/framework/middleware/hg.py", line 52, in __call__
    common, _ = environ[ 'HTTP_X_HGARG_1' ].split( '&' )
ValueError: too many values to unpack
----------------------------------------
```

I hope somebody can look into this and see if this can be reproduced.

Thanks in advance,

Youri

**Comment by bgruening** [comment]
Can you please test this one? https://github.com/galaxyproject/galaxy/pull/1082

**Comment by martenson** [comment]
resolved by the mentioned PR
