### ISSUE TITLE
galaxy.exceptions.MessageException: Cannot match collection types.

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10930]
I just encountered this exception while running a workflow:

```
galaxy.workflow.run ERROR 2020-12-16 07:33:04,972 Failed to schedule Workflow[id=69,name=Pairwise align sequences from tree], problem occurred on WorkflowStep[index=8,type=tool].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1666, in execute
    collection_info = self.compute_collection_info(progress, step, all_inputs)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 340, in compute_collection_info
    collection_info = self.trans.app.dataset_collections_service.match_collections(
  File "/srv/galaxy/lib/galaxy/managers/collections.py", line 473, in match_collections
    return MatchingCollections.for_collections(collections_to_match, self.collection_type_descriptions)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 101, in for_collections
    matching_collections.__attempt_add_to_linked_match(input_key, hdca, collection_type_description, subcollection_type)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 58, in __attempt_add_to_linked_match
    raise exceptions.MessageException(CANNOT_MATCH_ERROR_MESSAGE)
galaxy.exceptions.MessageException: Cannot match collection types.
galaxy.workflow.run ERROR 2020-12-16 07:33:04,993 Failed to schedule Workflow[id=71,name=IslandCompare], problem occurred on WorkflowStep[index=14,type=subworkflow].
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 516, in execute
    subworkflow_invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1666, in execute
    collection_info = self.compute_collection_info(progress, step, all_inputs)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 340, in compute_collection_info
    collection_info = self.trans.app.dataset_collections_service.match_collections(
  File "/srv/galaxy/lib/galaxy/managers/collections.py", line 473, in match_collections
    return MatchingCollections.for_collections(collections_to_match, self.collection_type_descriptions)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 101, in for_collections
    matching_collections.__attempt_add_to_linked_match(input_key, hdca, collection_type_description, subcollection_type)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 58, in __attempt_add_to_linked_match
    raise exceptions.MessageException(CANNOT_MATCH_ERROR_MESSAGE)
galaxy.exceptions.MessageException: Cannot match collection types.
galaxy.workflow.run ERROR 2020-12-16 07:33:04,994 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 516, in execute
    subworkflow_invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 263, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans,
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1666, in execute
    collection_info = self.compute_collection_info(progress, step, all_inputs)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 340, in compute_collection_info
    collection_info = self.trans.app.dataset_collections_service.match_collections(
  File "/srv/galaxy/lib/galaxy/managers/collections.py", line 473, in match_collections
    return MatchingCollections.for_collections(collections_to_match, self.collection_type_descriptions)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 101, in for_collections
    matching_collections.__attempt_add_to_linked_match(input_key, hdca, collection_type_description, subcollection_type)
  File "/srv/galaxy/lib/galaxy/model/dataset_collections/matching.py", line 58, in __attempt_add_to_linked_match
    raise exceptions.MessageException(CANNOT_MATCH_ERROR_MESSAGE)
galaxy.exceptions.MessageException: Cannot match collection types.
galaxy.workflow.scheduling_manager DEBUG 2020-12-16 07:33:05,016 Workflow invocation [154] scheduled
```

I am not clear what could cause this. As far as I know this workflow was working previously.

**Comment by innovate-invent** [comment]
I managed to track this down to a tool that was mapped over with three single datatset inputs.
One input was receiving a list while the other two were receiving list:lists.

**Comment by mvdbeek** [comment]
That works, but what doesn't work is if the inner list length it not the same. I don't think we can infer what to do if the inner list lengths don't match (hence the `CANNOT_MATCH_ERROR_MESSAGE `).

**Comment by innovate-invent** [comment]
This error should at least be forwarded to the user

**Comment by mvdbeek** [comment]
It is if you submit a job, and it is planned for invocations.

**Comment by mvdbeek** [comment]
I should also add that if this happening because some datasets are filtered out, I think the correct thing to do in the future is to produce null values, so it becomes clear that mapping can proceed.
