### ISSUE TITLE
Exception thrown listing containers without docker

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11106]
I'm using @torfinnnome's setup with singularity only and no docker. As described here: https://training.galaxyproject.org/training-material/topics/admin/tutorials/singularity/tutorial.html

The `/admin/toolbox_dependencies` route throws an exception when trying to list containers, I guess because docker isn't installed? But docker also isn't needed to successfully run things so,

```
galaxy.web.framework.decorators ERROR 2021-01-12 09:15:53,393 [p:1190005,w:1,m:0] [uWSGIWorker1Core3] Uncaught exce[13/98772]

Traceback (most recent call last):
  File "/srv/galaxy/server/lib/galaxy/web/framework/decorators.py", line 294, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/srv/galaxy/server/lib/galaxy/web/framework/decorators.py", line 100, in decorator
    return func(self, trans, *args, **kwargs)
  File "/srv/galaxy/server/lib/galaxy/webapps/galaxy/api/container_resolution.py", line 88, in resolve_toolbox
    return self._view.resolve_toolbox(**kwds)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/views.py", line 392, in resolve_toolbox
    rval.append(self.resolve(tool_id=tool_id, **resolve_kwds))
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/views.py", line 367, in resolve
    resolved_container_description = self._app.container_finder.resolve(
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 58, in resolve
    return self.container_registry.resolve(enabled_container_types, tool_info, **kwds)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 265, in resolve
    container_description = container_resolver.resolve(enabled_container_types, tool_info, install=install, resolution_cache=

  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 342, in resolve
    return docker_cached_container_description(targets, self.namespace, hash_func=self.hash_func, shell=self.shell, resolutio

  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 202, in docker_cached_container_des

    cached_images = list_docker_cached_mulled_images(namespace, hash_func=hash_func, resolution_cache=resolution_cache)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 71, in list_docker_cached_mulled_im

    images_and_versions = unicodify(subprocess.check_output(command)).strip().splitlines()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
85.149.66.255 - - [12/Jan/2021:09:15:53 +0000] "GET /api/container_resolvers/toolbox HTTP/1.1" 500 - "https://gat-1.oz.traini
```

**Comment by bernt-matthias** [comment]
I remember a longer discussion on the admin gitter channel. @mvdbeek suggested to modify container_resolvers_conf.xml

```
<containers_resolvers>
  <explicit_singularity />
  <cached_mulled_singularity />
  <mulled_singularity auto_install="False"/>
  <build_mulled_singularity auto_install="False"/>
</containers_resolvers>
```

I also remember that this worked, but I'm not 100% sure.

**Comment by hexylena** [comment]
Ahh, ok. Interesting. That can work. Cheers.

**Comment by hexylena** [comment]
Applied change but unfortunately doesn't affect the exception that's thrown.

**Comment by bernt-matthias** [comment]
Have you set `containers_resolvers_config_file` in the galaxy config?

**Comment by hexylena** [comment]
you're right, that was it. it's too bad singularity containers aren't listed but, at least not broken with the update resolver conf.

![image](https://user-images.githubusercontent.com/458683/104432795-a6aa6f00-5589-11eb-8304-7543161b6154.png)

**Comment by mvdbeek** [comment]
Oh, they should be listed, but I think you're missing
```
mulled_singularity
```
from the resolver list in order to list images that aren't pulled yet. Once they are pulled they should appear in the panel

**Comment by hexylena** [comment]
It's there, `  <mulled_singularity auto_install="False"/>`, huh.
