### ISSUE TITLE
Galaxy requiring docker command before running mulled job containers?

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#11125]
Ran into an issue with latest 20.09 where it seems any mulled job container is being looked up on the host by Galaxy running the `docker` command. This does not work for K8s deployments, especially when using container runtime other than Docker (which CloudMan/GVL now do), and prevents just about any job from running.

The following is a traceback showing up in the job handler:
```
urllib3.connectionpool DEBUG 2021-01-13 15:26:00,421 https://quay.io:443 "GET /api/v1/repository/biocontainers/porechop HTTP/1.1" 200 4033
galaxy.tool_util.deps.containers ERROR 2021-01-13 15:26:00,499 Could not get container description for tool 'toolshed.g2.bx.psu.edu/repos/iuc/porechop/porechop/0.2.3'
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 243, in find_best_container_description
    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
  File "/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 265, in resolve
    container_description = container_resolver.resolve(enabled_container_types, tool_info, install=install, resolution_cache=resolution_cache, session=session)
  File "/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 410, in resolve
    if install and not self.cached_container_description(
  File "/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 385, in cached_container_description
    return docker_cached_container_description(targets, namespace, hash_func, resolution_cache)
  File "/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 202, in docker_cached_container_description
    cached_images = list_docker_cached_mulled_images(namespace, hash_func=hash_func, resolution_cache=resolution_cache)
  File "/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 71, in list_docker_cached_mulled_images
    images_and_versions = unicodify(subprocess.check_output(command)).strip().splitlines()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

Seems PR #10814 made some changes that could have affected this? Ping @mvdbeek.

**Comment by dannon** [comment]
I think it's this bit here:  https://github.com/galaxyproject/galaxy/pull/10814/files#diff-e05e0000579a5a947c903fc8346305cbe31d304f5132afd6c090980c55f16c32L411  that dropped the bypass in resolve

**Comment by mvdbeek** [comment]
Yes, that causes this traceback, but I don't think `destination_for_container_type` was meant as a bypass for the scenario that docker is not available on the handler. I'll see what I can do
