### ISSUE TITLE
History import does not set `importing` attribute to False when finished

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11164]
That makes imported histories not appear in histories/list, but they are present in history/view_multiple.
The column filter is here: https://github.com/galaxyproject/galaxy/blob/53b9d35863c43b7fb968bc13f6700c21aefb6738/lib/galaxy/webapps/galaxy/controllers/history.py#L148

**Comment by mvdbeek** [comment]
Our friend, hidden exception placed on the stderr of the importing job:
```
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/imp_exp/__init__.py", line 57, in cleanup_after_job
    model_store.perform_import(new_history, job=job, new_history=True)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/store/__init__.py", line 181, in perform_import
    self._import_jobs(object_import_tracker, history)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/store/__init__.py", line 692, in _import_jobs
    self._connect_job_io(imported_job, job_attrs, _find_hda, _find_hdca, _find_dce)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/store/__init__.py", line 931, in _connect_job_io
    imported_job.add_output_dataset_collection(output_name, output_hdca)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/__init__.py", line 974, in add_output_dataset_collection
    self.output_dataset_collection_instances.append(JobToOutputDatasetCollectionAssociation(name, dataset_collection_instance))
  File "<string>", line 4, in __init__
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/__init__.py", line 1476, in __init__
    self.dataset_collection_instance = dataset_collection_instance
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 272, in __set__
    self.impl.set(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1017, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1039, in fire_replace_event
    value = fn(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1449, in emit_backref_from_scalar_set_event
    instance_state(child),
AttributeError: 'str' object has no attribute '_sa_instance_state'
```

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11165
