### ISSUE TITLE
Container resolver build_mulled_singularity requires docker

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#11175]
On my quest to use singularity, I came across some tools that I have that use >1 conda packages as requirements, and that while I added that tool's repo to planemo monitor, the mulled container request never went through the multi-tool-container repo. As such, they don't get a docker:// container mapped by Galaxy that can then be translated to singularity.

I thought then that the container resolver build_mulled_singularity would come to the rescue, my containers resolver looks like:

```
<containers_resolvers>
  <explicit_singularity />
  <!-- explicit: resolves container URI for a job through explict container
       tags in the tool XML wrapper. -->

  <!-- All mulled flavors below only work if enable_beta_mulled_containers is
       set to true in the galaxy.yaml config file.

       automatic mapping, preferring cached images in the accessible docker
       engine. Requires docker engine. -->

  <cached_mulled_singularity />
  <mulled_singularity auto_install="True"/>
  <!-- cached_mulled_singularity: resolves container URI through
       bioconda to mulled automatic mapping, preferring cached singularity
       images to building local singularity images. Only works with
       enable_beta_mulled_containers set to true in the galaxy.yaml config file.
       -->

  <build_mulled_singularity auto_install="True"/>
  <!-- build_mulled_singularity: builds a singularity image locally for one
       or more package requirements listed as part of the tool's definition. -->
</containers_resolvers>
```

however, on trying to run this specific tool I get:

```
galaxy.jobs DEBUG 2021-01-18 22:05:41,633 (2088) Persisting job destination (destination id: singularity_cluster)
galaxy.jobs DEBUG 2021-01-18 22:05:41,676 (2088) Working directory for job is: /galaxy-dev/shared/galaxy_wd/wd/002/2088
galaxy.jobs.runners DEBUG 2021-01-18 22:05:41,694 Job [2088] queued (82.551 ms)
galaxy.jobs.handler INFO 2021-01-18 22:05:41,705 (2088) Job dispatched
galaxy.tool_util.deps.containers INFO 2021-01-18 22:05:42,081 Checking with container resolver [ExplicitSingularityContainerResolver[]] found description [None]
galaxy.tool_util.deps.containers INFO 2021-01-18 22:05:42,082 Checking with container resolver [CachedMulledSingularityContainerResolver[cache_directory=/galaxy-dev/server/galaxy-20.09/database/container_cache/singularity/mulled]] found description [None]
urllib3.connectionpool DEBUG 2021-01-18 22:05:42,094 Starting new HTTPS connection (1): quay.io:443
urllib3.connectionpool DEBUG 2021-01-18 22:05:44,176 https://quay.io:443 "GET /api/v1/repository?public=true&namespace=biocontainers HTTP/1.1" 200 1562773
galaxy.tool_util.deps.mulled.util INFO 2021-01-18 22:05:45,416 skipping mulled_tags_for [mulled-v2-2c112acf14fd6d41bf36888fc851d2cecd16b88d] no repository
galaxy.tool_util.deps.containers INFO 2021-01-18 22:05:45,417 Checking with container resolver [MulledSingularityContainerResolver[namespace=biocontainers]] found description [None]
galaxy.tool_util.deps.containers ERROR 2021-01-18 22:05:45,440 Could not get container description for tool 'toolshed.g2.bx.psu.edu/repos/immport-devteam/convert_fcs_to_text/convert_fcs_to_text/1.0'
Traceback (most recent call last):
  File "/galaxy-dev/server/galaxy-20.09/lib/galaxy/tool_util/deps/containers.py", line 249, in find_best_container_description
    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
  File "/galaxy-dev/server/galaxy-20.09/lib/galaxy/tool_util/deps/containers.py", line 271, in resolve
...

  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
galaxy.jobs.runners ERROR 2021-01-18 22:05:45,448 (2088) Failure preparing job
Traceback (most recent call last):
  File "/galaxy-dev/server/galaxy-20.09/lib/galaxy/jobs/runners/__init__.py", line 243, in prepare_job
    stderr_file=stderr_file,
  File "/galaxy-dev/server/galaxy-20.09/lib/galaxy/jobs/runners/__init__.py", line 275, in build_command_line
    raise Exception("Failed to find a container when required, contact Galaxy admin.")
Exception: Failed to find a container when required, contact Galaxy admin.
```

So it seems that the mulled singularity build resolver requires docker at some point of the whole process. While I'm guessing that this is because the mulled lua setup talks directly to the docker API, I guess I wasn't expecting it from the build_mulled_singularity. I guess there should be a warning in the container_resolvers XML.

**Comment by mvdbeek** [comment]
Thanks, I guess we can close with https://github.com/galaxyproject/galaxy/pull/11176 ?
