### ISSUE TITLE
Error getting display data for dataset

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11301]
Galaxy 20.09. I encountered this exception while trying to download a dataset.
```
galaxy.webapps.galaxy.api.datasets ERROR 2021-02-04 21:56:10,169 [p:33,w:1,m:0] [uWSGIWorker1Core2] Error getting display data for dataset (645e48ac270ad0b4) from history (9b56708fd00f54a7)
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/webapps/galaxy/api/datasets.py", line 422, in display
    rval = hda.datatype.display_data(trans, hda, preview, filename, to_ext, **display_kwd)
  File "/srv/galaxy/lib/galaxy/datatypes/tabular.py", line 89, in display_data
    return self._serve_raw(trans, dataset, to_ext, **kwd)
  File "/srv/galaxy/lib/galaxy/datatypes/data.py", line 347, in _serve_raw
    trans.response.headers['Content-Length'] = int(os.stat(dataset.file_name).st_size)
FileNotFoundError: [Errno 2] No such file or directory: ''
10.0.1.237 - - [04/Feb/2021:21:56:10 +0000] "GET /api/histories/9b56708fd00f54a7/contents/645e48ac270ad0b4/display?to_ext=gff3&key=8bf3d2af3355a63e96b9865779342a95 HTTP/1.1" 500 - "-" "python-requests/2.25.1"
```

**Comment by mvdbeek** [comment]
Is that a new or purged dataset ?

**Comment by innovate-invent** [comment]
This is a dataset freshly generated by a workflow

**Comment by innovate-invent** [comment]
I don't know if this is related but I encountered this issue while uploading via nginx upload module:
```
Traceback (most recent call last):
  File "/srv/galaxy/tools/data_source/upload.py", line 342, in <module>
    __main__()
  File "/srv/galaxy/tools/data_source/upload.py", line 335, in __main__
    metadata.append(add_file(dataset, registry, output_path))
  File "/srv/galaxy/tools/data_source/upload.py", line 134, in add_file
    stdout, ext, datatype, is_binary, converted_path = handle_upload(
  File "/srv/galaxy/lib/galaxy/datatypes/upload_util.py", line 42, in handle_upload
    ext, converted_path, compression_type = sniff.handle_uploaded_dataset_file_internal(
  File "/srv/galaxy/lib/galaxy/datatypes/sniff.py", line 739, in handle_uploaded_dataset_file_internal
    is_binary = check_binary(converted_path)
  File "/srv/galaxy/lib/galaxy/util/checkers.py", line 54, in check_binary
    temp = open(name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/database/tmp/upload_file_data_tqu3di8x'
```

I checked and the file was not actually there. I am not sure why it wouldn't be unless there was a race between two replicates trying to serve the same request or something.

**Comment by mvdbeek** [comment]
I guess that should then also be fixed with https://github.com/galaxyproject/galaxy/pull/12763
