### ISSUE TITLE
Jobs randomly fail

### ISSUE THREAD

**Issue by AlexandreBurel** [galaxyproject/galaxy#11328]
Hi all,

I'm encountering a strange problem, I'm not sure what to think of it. Maybe someone here will have some bright advice for me ! Before I get started, my version of Galaxy is 20.05, with Python 3.6.

My problem is that sometimes, my jobs fail for no apparent reason. I'm working on custom tools so I can also test them with the command line and they work just fine that way. But when I'm using the Galaxy GUI, sometimes they fail and sometimes they pass ! So far I thought the problem may come from my custom tools, but this morning, this exact same problem happened when I tried to upload a small Excel file and it fails a few times before it finally worked ([see image](https://user-images.githubusercontent.com/10810538/107386071-c9ca2f00-6af3-11eb-9977-b4c8db92a9bf.png))

In the log file, I find this error:
```
galaxy.jobs.mapper DEBUG 2021-02-09 11:32:42,425 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] (454) Mapped job to destination id: local
galaxy.jobs.handler DEBUG 2021-02-09 11:32:42,442 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] (454) Dispatching to local runner
galaxy.jobs DEBUG 2021-02-09 11:32:42,449 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] (454) Persisting job destination (destination id: local)
galaxy.jobs DEBUG 2021-02-09 11:32:42,450 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] (454) Working directory for job is: /data/galaxy/database/jobs_directory/000/454
galaxy.jobs.runners DEBUG 2021-02-09 11:32:42,459 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] Job [454] queued (17.171 ms)
galaxy.jobs.handler INFO 2021-02-09 11:32:42,469 [p:23150,w:1,m:0] [JobHandlerQueue.monitor_thread] (454) Job dispatched
galaxy.jobs.command_factory INFO 2021-02-09 11:32:42,578 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] Built script [/data/galaxy/database/jobs_directory/000/454/tool_script.sh] for tool command [python '/data/galaxy/tools/data_source/upload.py' '/data/galaxy' '/data/galaxy/database/jobs_directory/000/454/registry.xml' '/data/galaxy/database/jobs_directory/000/454/upload_params.json' '440:/data/galaxy/database/jobs_directory/000/454/working/dataset_af23c288-52b5-484c-a244-be49ae463d3f_files:/data/galaxy/database/objects/a/f/2/dataset_af23c288-52b5-484c-a244-be49ae463d3f.dat']
galaxy.jobs.runners DEBUG 2021-02-09 11:32:42,616 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] (454) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/galaxy/database/jobs_directory/000/454/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/galaxy/database/jobs_directory/000/454'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-02-09 11:32:42,637 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] (454) executing job script: /data/galaxy/database/jobs_directory/000/454/galaxy_454.sh
130.79.67.200 - - [09/Feb/2021:11:32:45 +0200] "GET /api/histories/f099030cd0eaf7b1/contents?details=8806660a9fa8d8a3%2Cbe4601244829a345%2C846828b387622c04%2Cb655df93c8c207ec%2Cad6b75aaa82f4ffe&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2021-02-09T10%3A32%3A41.000Z&qv=False&qv=False HTTP/1.1" 200 - "http://172.16.2.38/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
[pid: 23150|app: 0|req: 939/1882] 127.0.0.1 () {88 vars in 3084 bytes} [Tue Feb  9 11:32:45 2021] GET /api/histories/f099030cd0eaf7b1/contents?details=8806660a9fa8d8a3%2Cbe4601244829a345%2C846828b387622c04%2Cb655df93c8c207ec%2Cad6b75aaa82f4ffe&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2021-02-09T10%3A32%3A41.000Z&qv=False&qv=False => generated 487 bytes in 33 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
130.79.67.200 - - [09/Feb/2021:11:32:45 +0200] "POST /api/tools/kegg/build HTTP/1.1" 200 - "http://172.16.2.38/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
[pid: 23153|app: 0|req: 944/1883] 127.0.0.1 () {94 vars in 2742 bytes} [Tue Feb  9 11:32:45 2021] POST /api/tools/kegg/build => generated 7060 bytes in 40 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 6)
galaxy.jobs.runners.util.process_groups DEBUG 2021-02-09 11:32:48,154 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] check_pg(): No process found in process group 24969
galaxy.jobs.runners.local ERROR 2021-02-09 11:32:48,155 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] failure running job 454
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/local.py", line 139, in queue_job
    stdout_file.close()
  File "/data/galaxy/.venv/lib64/python3.6/tempfile.py", line 511, in close
    self._closer.close()
  File "/data/galaxy/.venv/lib64/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/data/galaxy/database/jobs_directory/000/454/tmpx8d8gfk7_stdout'
galaxy.tools.error_reports DEBUG 2021-02-09 11:32:48,212 [p:23150,w:1,m:0] [LocalRunner.work_thread-2] Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x7f6e18702978> generated response None
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f6dc43c3c50>>
Traceback (most recent call last):
  File "/data/galaxy/.venv/lib64/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/data/galaxy/.venv/lib64/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/data/galaxy/database/jobs_directory/000/454/tmp7qq0e6qc_stderr'
```

The FileNotFoundError on stderr appears to be the cause of my problems, as [line 139 from local.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/local.py#L139) is the line where the stderr file gets closed.
It seems like sometimes the stderr file is already deleted at this point, and sometimes it's working just fine.
This is the exact same error message that I noticed before when I had job failure on my custom tools.

It makes no sense to me, and at this stage I'm not even sure whether it's a bug in Galaxy, in Python, or the consequence of some poor choice in my galaxy.yml file, or something else.

Is it something that has already been seen before ?

Thanks !!

**Comment by AlexandreBurel** [comment]
Apparently the issue is due to my PostgreSQL database, when I switch back to SQLite jobs are working fine...
It makes no sense to me, I tried to increase the memory settings, trace the slow requests, nothing gave me a clue.

So I guess I'll close this issue since the problem is not strictly because of Galaxy...
