### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

### ISSUE THREAD

**Issue by mengxin-mx-cpu** [galaxyproject/galaxy#11337]
python version is "Python 3.8.3"

git clone -b release_20.09 https://github.com/galaxyproject/galaxy.git

then i run sh run.sh,it returns errors:

Requirement already satisfied: pathlib2!=2.3.1 in ./.venv/lib/python3.8/site-packages (from cwltool==1.0.20191225192155->-r requirements.txt (line 45)) (2.3.5)
Requirement already satisfied: setuptools in ./.venv/lib/python3.8/site-packages (from cwltool==1.0.20191225192155->-r requirements.txt (line 45)) (42.0.2)
The Galaxy client has not yet been built and will be built now.
Installing node into /home/galaxy/.venv with nodeenv.
 * Install prebuilt node (12.16.3) .
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/galaxy/.venv/bin/nodeenv", line 8, in <module>
    sys.exit(main())
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 1046, in main
    create_environment(env_dir, opt)
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 935, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 700, in install_node
    install_node_wrapped(env_dir, src_dir, opt)
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 722, in install_node_wrapped
    download_node_src(node_url, src_dir, opt)
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 553, in download_node_src
    dl_contents = io.BytesIO(urlopen(node_url).read())
  File "/home/galaxy/.venv/lib/python3.8/site-packages/nodeenv.py", line 585, in urlopen
    return urllib2.urlopen(req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

**Comment by mvdbeek** [comment]
You'll need to make sure you have SSL certificates set up for your operating system and python interpreter.

**Comment by mengxin-mx-cpu** [comment]
I compiled the Python3.5 source code with SSL,It could import ssl.
then I run "sh run.sh",it returns error.How can I solve this.

sh run.sh
The Galaxy client has not yet been built and will be built now.
Installing node into /home/galaxy-20.09/.venv with nodeenv.
 * Install prebuilt node (12.16.3) .
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1285, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1161, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1206, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1157, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 949, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 892, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1315, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/galaxy-20.09/.venv/bin/nodeenv", line 8, in <module>
    sys.exit(main())
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 1046, in main
    create_environment(env_dir, opt)
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 935, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 700, in install_node
    install_node_wrapped(env_dir, src_dir, opt)
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 722, in install_node_wrapped
    download_node_src(node_url, src_dir, opt)
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 553, in download_node_src
    dl_contents = io.BytesIO(urlopen(node_url).read())
  File "/home/galaxy-20.09/.venv/lib/python3.5/site-packages/nodeenv.py", line 585, in urlopen
    return urllib2.urlopen(req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1328, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1287, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)>
[root@localhost galaxy-20.09]# 
[root@localhost galaxy-20.09]# 


[root@localhost galaxy-20.09]# .venv/bin/python
Python 3.5.10 (default, Feb 19 2021, 11:40:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> 
>>> 
>>> 
[root@localhost galaxy-20.09]# python3
Python 3.5.10 (default, Feb 19 2021, 11:40:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> 
>>> 
>>>

**Comment by mengxin-mx-cpu** [comment]
[root@localhost ~]# openssl version
OpenSSL 1.1.1a  20 Nov 2018
[root@localhost ~]#
