### ISSUE TITLE
Job double scheduling

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11335]
While uploading a dataset, I encountered this error as Galaxy was running the upload tool.

The tool command was:
```sh
python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/217/217497/registry.xml' '/data/jobs_directory/000/217/217497/upload_params.json' '298276:/data/jobs_directory/000/217/217497/working/dataset_298276_files:/data/jobs_directory/000/217/217497/outputs/galaxy_dataset_432337f0-c6e2-4d12-b930-c0f05f86c02a.dat'
```

and I looked for `/data/jobs_directory/000/217/217497/outputs` but it did not exist by the time I got to it

**Comment by mvdbeek** [comment]
Did you forget to paste the error message ?
I guess you'll also want to give a bit more context.

**Comment by innovate-invent** [comment]
Ah, sorry. It is in the title. The dataset errored after uploading.

**Comment by mvdbeek** [comment]
Do you have anything else to add ? I don't think this is enough for us to do anything here.

**Comment by innovate-invent** [comment]
Do you know where in the upload tool it attempts to delete that folder?

**Comment by mvdbeek** [comment]
https://github.com/mvdbeek/galaxy/blob/54b7fba5379f5e9d29221e09fd1c41fdcce68afc/lib/galaxy/jobs/command_factory.py#L24

**Comment by innovate-invent** [comment]
How could rm -rf throw that error?

**Comment by mvdbeek** [comment]
I am just guessing here since it's not clear what exactly the error message and the context is. For clarity you might want to paste the error message here.

**Comment by innovate-invent** [comment]
Are you expecting an error message in the galaxy log? I was unable to find any.

**Comment by mvdbeek** [comment]
You've found an error message somewhere, right ? I don't know if that is on the job stderr or where you got this from, but the entire message with as much context as possible would be helpful.

**Comment by innovate-invent** [comment]
The title actually is the entire error message from stderr. That is all the info it provided.

**Comment by innovate-invent** [comment]
This is another simmilar error while uploading:
```json
{"model_class": "Job", "id": "9c2d00005c6779df", "state": "error", "exit_code": null, "update_time": "2021-02-10T06:25:44.866550", "create_time": "2021-02-10T06:25:39.929135", "galaxy_version": "20.09", "command_version": null, "tool_id": "upload1", "history_id": "cbe66839c6d18192", "external_id": "28018", "command_line": "python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/219/219131/registry.xml' '/data/jobs_directory/000/219/219131/upload_params.json' '299910:/data/jobs_directory/000/219/219131/working/dataset_299910_files:/data/jobs_directory/000/219/219131/outputs/galaxy_dataset_30be83d7-143f-4653-96bb-55181f3be6e5.dat'", "params": {"file_type": "\"genbank\"", "file_count": "\"auto\"", "files": "[{\"NAME\": \"ERR374814.gbk\", \"__index__\": 0, \"auto_decompress\": \"Yes\", \"dbkey\": \"\", \"file_data\": \"/data/database/tmp/upload_file_data_nsyim7nx\", \"file_type\": \"\", \"ftp_files\": null, \"space_to_tab\": null, \"to_posix_lines\": \"Yes\", \"url_paste\": \"\", \"uuid\": null}]", "force_composite": "\"false\"", "dbkey": "\"?\"", "files_metadata": "{\"__current_case__\": 394, \"file_type\": \"genbank\"}", "paramfile": "\"/data/database/tmp/upload_params_prenjw9k\""}, "inputs": {}, "outputs": {"output0": {"id": "eaf8dbf7419cf716", "src": "hda", "uuid": "30be83d7-143f-4653-96bb-55181f3be6e5"}}, "tool_stdout": "", "tool_stderr": "", "job_stdout": null, "job_stderr": null, "stderr": "", "stdout": "", "job_messages": [{"code_desc": "", "desc": "Fatal error: Exit code 127 ()", "error_level": 3, "exit_code": 127, "type": "exit_code"}], "user_email": "test@robot.com", "job_metrics": []}
```

Despite the json, the stderr was ```Job 219131's output dataset(s) could not be read```

**Comment by mvdbeek** [comment]
`Fatal error: Exit code 127 ()` looks quite different. You sure python was available ?

**Comment by innovate-invent** [comment]
After spending way too much time digging around, it looks like the network is going nuts dropping connections. This includes interrupting NFS and all sorts.

**Comment by innovate-invent** [comment]
I don't think this is actually an issue with the filesystem. It looks like the job is being scheduled twice by two different handlers:

```
galaxy.jobs.handler DEBUG 2021-03-10 21:41:54,803 Grabbed Job(s): 77218
galaxy.jobs.mapper DEBUG 2021-03-10 21:41:54,839 (77218) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-10 21:41:54,856 (77218) Dispatching to local runner
galaxy.jobs.handler DEBUG 2021-03-10 21:41:54,869 Grabbed Job(s): 77218
galaxy.jobs DEBUG 2021-03-10 21:41:54,881 (77218) Persisting job destination (destination id: local-tiny)
galaxy.jobs.mapper DEBUG 2021-03-10 21:41:54,911 (77218) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-10 21:41:54,921 (77218) Dispatching to local runner
galaxy.jobs DEBUG 2021-03-10 21:41:54,937 (77218) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-03-10 21:41:54,937 (77218) Working directory for job is: /data/jobs_directory/077/77218
galaxy.jobs.runners DEBUG 2021-03-10 21:41:54,945 Job [77218] queued (88.672 ms)
galaxy.jobs.handler INFO 2021-03-10 21:41:54,954 (77218) Job dispatched
galaxy.jobs DEBUG 2021-03-10 21:41:54,963 (77218) Working directory for job is: /data/jobs_directory/077/77218
galaxy.jobs.runners DEBUG 2021-03-10 21:41:54,972 Job [77218] queued (51.126 ms)
galaxy.jobs.handler INFO 2021-03-10 21:41:54,982 (77218) Job dispatched
galaxy.jobs.command_factory INFO 2021-03-10 21:41:55,283 Built script [/data/jobs_directory/077/77218/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/077/77218/registry.xml' '/data/jobs_directory/077/77218/upload_params.json' '100267:/data/jobs_directory/077/77218/working/dataset_100267_files:/data/jobs_directory/077/77218/outputs/galaxy_dataset_67043cfb-141e-4ccf-9c0b-ea76cc4eb1b6.dat']
galaxy.jobs.command_factory INFO 2021-03-10 21:41:55,295 Built script [/data/jobs_directory/077/77218/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/077/77218/registry.xml' '/data/jobs_directory/077/77218/upload_params.json' '100267:/data/jobs_directory/077/77218/working/dataset_100267_files:/data/jobs_directory/077/77218/outputs/galaxy_dataset_67043cfb-141e-4ccf-9c0b-ea76cc4eb1b6.dat']
galaxy.jobs.runners DEBUG 2021-03-10 21:41:55,529 (77218) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/077/77218/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/077/77218'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-03-10 21:41:55,581 (77218) executing job script: /data/jobs_directory/077/77218/galaxy_77218.sh
galaxy.jobs.runners DEBUG 2021-03-10 21:41:55,615 (77218) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/077/77218/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/077/77218'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-03-10 21:41:55,685 (77218) executing job script: /data/jobs_directory/077/77218/galaxy_77218.sh
galaxy.jobs.runners.util.process_groups DEBUG 2021-03-10 21:41:56,273 check_pg(): No process found in process group 816
galaxy.jobs.runners.local DEBUG 2021-03-10 21:41:56,289 execution finished: /data/jobs_directory/077/77217/galaxy_77217.sh
galaxy.jobs DEBUG 2021-03-10 21:41:56,328 finish(): Moved /data/jobs_directory/077/77217/outputs/galaxy_dataset_12e513ae-82f9-4e4f-828f-7051484420f0.dat to /data/database/files/000/100/dataset_100266.dat
galaxy.model.metadata DEBUG 2021-03-10 21:41:56,347 loading metadata from file for: HistoryDatasetAssociation 142641
galaxy.jobs INFO 2021-03-10 21:41:56,438 Collecting metrics for Job 77217 in /data/jobs_directory/077/77217
galaxy.jobs DEBUG 2021-03-10 21:41:56,657 job_wrapper.finish for job 77217 executed (344.347 ms)
galaxy.jobs.handler DEBUG 2021-03-10 21:42:02,223 Grabbed Job(s): 77219
galaxy.jobs.mapper DEBUG 2021-03-10 21:42:02,257 (77219) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-10 21:42:02,269 (77219) Dispatching to local runner
galaxy.jobs DEBUG 2021-03-10 21:42:02,284 (77219) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-03-10 21:42:02,322 (77219) Working directory for job is: /data/jobs_directory/077/77219
galaxy.jobs.runners DEBUG 2021-03-10 21:42:02,331 Job [77219] queued (62.403 ms)
galaxy.jobs.handler INFO 2021-03-10 21:42:02,341 (77219) Job dispatched
galaxy.jobs.runners.util.process_groups DEBUG 2021-03-10 21:42:02,517 check_pg(): No process found in process group 20030
galaxy.jobs.runners.local DEBUG 2021-03-10 21:42:02,530 execution finished: /data/jobs_directory/077/77218/galaxy_77218.sh
galaxy.tool_util.output_checker INFO 2021-03-10 21:42:02,546 Job error detected, failing job. Reasons are [{'type': 'exit_code', 'desc': 'Fatal error: Exit code 1 ()', 'exit_code': 1, 'code_desc': '', 'error_level': 3}]
galaxy.jobs DEBUG 2021-03-10 21:42:02,576 finish(): Moved /data/jobs_directory/077/77218/outputs/galaxy_dataset_67043cfb-141e-4ccf-9c0b-ea76cc4eb1b6.dat to /data/database/files/000/100/dataset_100267.dat
galaxy.jobs DEBUG 2021-03-10 21:42:02,605 (77218) setting dataset 100267 state to ERROR
galaxy.jobs.command_factory INFO 2021-03-10 21:42:02,648 Built script [/data/jobs_directory/077/77219/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/077/77219/registry.xml' '/data/jobs_directory/077/77219/upload_params.json' '100268:/data/jobs_directory/077/77219/working/dataset_100268_files:/data/jobs_directory/077/77219/outputs/galaxy_dataset_ed8a065f-2461-4cd1-beb5-53a4966f7694.dat']
galaxy.jobs INFO 2021-03-10 21:42:02,735 Collecting metrics for Job 77218 in /data/jobs_directory/077/77218
```

**Comment by mvdbeek** [comment]
Can you exclude that you have 2 handlers with the same name running ?

**Comment by innovate-invent** [comment]
The handlers are different names and there is no code running other than the app and worker threads.
If the handlers had the same name I would be seeing this occur much more often.
It happens once every ~2000 jobs, which is 50% of the time for my workflow.
The handlers use db-skip-lock assignment.
I am assuming it is two different handlers, it could be the same handler firing twice, which might explain how it is cheating the assignment process.

**Comment by innovate-invent** [comment]
```
galaxy.jobs.handler DEBUG 2021-03-13 03:32:39,101 Handler galaxy-worker-66b5cb8d65-p4qws with PID 7 grabbed Job(s): 104172
galaxy.jobs.mapper DEBUG 2021-03-13 03:32:39,136 (104172) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-13 03:32:39,145 (104172) Dispatching to local runner
galaxy.jobs DEBUG 2021-03-13 03:32:39,161 (104172) Persisting job destination (destination id: local-tiny)
galaxy.jobs.handler DEBUG 2021-03-13 03:32:39,179 Handler galaxy-worker-66b5cb8d65-vjh5k with PID 7 grabbed Job(s): 104172
galaxy.jobs DEBUG 2021-03-13 03:32:39,202 (104172) Working directory for job is: /data/jobs_directory/000/104/104172
galaxy.jobs.runners DEBUG 2021-03-13 03:32:39,210 Job [104172] queued (64.772 ms)
galaxy.jobs.mapper DEBUG 2021-03-13 03:32:39,212 (104172) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-13 03:32:39,220 (104172) Dispatching to local runner
galaxy.jobs.handler INFO 2021-03-13 03:32:39,220 (104172) Job dispatched
galaxy.jobs DEBUG 2021-03-13 03:32:39,230 (104172) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-03-13 03:32:39,246 (104172) Working directory for job is: /data/jobs_directory/000/104/104172
galaxy.jobs.runners DEBUG 2021-03-13 03:32:39,253 Job [104172] queued (32.662 ms)
galaxy.jobs.handler INFO 2021-03-13 03:32:39,258 (104172) Job dispatched
galaxy.jobs.command_factory INFO 2021-03-13 03:32:39,489 Built script [/data/jobs_directory/000/104/104172/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/104/104172/registry.xml' '/data/jobs_directory/000/104/104172/upload_params.json' '134377:/data/jobs_directory/000/104/104172/working/dataset_134377_files:/data/jobs_directory/000/104/104172/outputs/galaxy_dataset_08ac3d66-a1e2-445e-8d60-193f753111a3.dat']
galaxy.jobs.command_factory INFO 2021-03-13 03:32:39,532 Built script [/data/jobs_directory/000/104/104172/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/104/104172/registry.xml' '/data/jobs_directory/000/104/104172/upload_params.json' '134377:/data/jobs_directory/000/104/104172/working/dataset_134377_files:/data/jobs_directory/000/104/104172/outputs/galaxy_dataset_08ac3d66-a1e2-445e-8d60-193f753111a3.dat']
galaxy.jobs.runners DEBUG 2021-03-13 03:32:39,720 (104172) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/000/104/104172/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/000/104/104172'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-03-13 03:32:39,769 (104172) executing job script: /data/jobs_directory/000/104/104172/galaxy_104172.sh
galaxy.jobs.runners DEBUG 2021-03-13 03:32:39,802 (104172) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/000/104/104172/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/000/104/104172'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-03-13 03:32:39,854 (104172) executing job script: /data/jobs_directory/000/104/104172/galaxy_104172.sh
galaxy.jobs.runners.util.process_groups DEBUG 2021-03-13 03:32:46,476 check_pg(): No process found in process group 10047
galaxy.jobs.runners.local DEBUG 2021-03-13 03:32:46,488 execution finished: /data/jobs_directory/000/104/104172/galaxy_104172.sh
galaxy.jobs DEBUG 2021-03-13 03:32:46,530 finish(): Moved /data/jobs_directory/000/104/104172/outputs/galaxy_dataset_08ac3d66-a1e2-445e-8d60-193f753111a3.dat to /data/database/files/000/134/dataset_134377.dat
galaxy.model.metadata DEBUG 2021-03-13 03:32:46,552 loading metadata from file for: HistoryDatasetAssociation 196185
galaxy.jobs.runners.util.process_groups DEBUG 2021-03-13 03:32:46,636 check_pg(): No process found in process group 8822
galaxy.jobs.runners.local DEBUG 2021-03-13 03:32:46,651 execution finished: /data/jobs_directory/000/104/104172/galaxy_104172.sh
galaxy.tool_util.output_checker INFO 2021-03-13 03:32:46,671 Job error detected, failing job. Reasons are [{'type': 'exit_code', 'desc': 'Fatal error: Exit code 1 ()', 'exit_code': 1, 'code_desc': '', 'error_level': 3}]
galaxy.jobs WARNING 2021-03-13 03:32:46,713 finish(): /data/jobs_directory/000/104/104172/outputs/galaxy_dataset_08ac3d66-a1e2-445e-8d60-193f753111a3.dat not found, but /data/database/files/000/134/dataset_134377.dat is not empty, so it will be used instead
galaxy.jobs DEBUG 2021-03-13 03:32:46,734 (104172) setting dataset 134377 state to ERROR
galaxy.jobs INFO 2021-03-13 03:32:46,730 Collecting metrics for Job 104172 in /data/jobs_directory/000/104/104172
galaxy.jobs INFO 2021-03-13 03:32:46,839 Collecting metrics for Job 104172 in /data/jobs_directory/000/104/104172
galaxy.tools.error_reports DEBUG 2021-03-13 03:32:46,856 Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x7fd79a6584c0> generated response None
galaxy.jobs DEBUG 2021-03-13 03:32:46,856 job_wrapper.finish for job 104172 executed (178.585 ms)
galaxy.jobs DEBUG 2021-03-13 03:32:46,952 job_wrapper.finish for job 104172 executed (441.719 ms)
galaxy.jobs.handler DEBUG 2021-03-13 03:33:55,712 Handler galaxy-worker-66b5cb8d65-p4qws with PID 7 grabbed Job(s): 104173
galaxy.jobs.mapper DEBUG 2021-03-13 03:33:55,747 (104173) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-03-13 03:33:55,756 (104173) Dispatching to local runner
galaxy.jobs DEBUG 2021-03-13 03:33:55,771 (104173) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-03-13 03:33:55,818 (104173) Working directory for job is: /data/jobs_directory/000/104/104173
```

**Comment by mvdbeek** [comment]
Hmm, can you also try with `assign-with="db-transaction-isolation"` ? this would decrease concurrency while assigning jobs, but is probably still better than the occasional error you're seeing here, and most of the time is spent creating jobs anyway.

**Comment by innovate-invent** [comment]
I pulled the lastest changes, but I won't be able to verify until after #10429

**Comment by innovate-invent** [comment]
Running through a couple analysis, it looks like db-transaction-isolation did the trick

**Comment by innovate-invent** [comment]
I lied, looks like I just got lucky. With assign_with="db-transaction-isolation":
```
galaxy.jobs.handler DEBUG 2021-06-25 23:11:04,424 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] Grabbed Job(s): 314814
galaxy.jobs.mapper DEBUG 2021-06-25 23:11:04,480 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-06-25 23:11:04,515 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Dispatching to local runner
galaxy.jobs DEBUG 2021-06-25 23:11:04,536 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-06-25 23:11:04,574 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Working directory for job is: /data/jobs_directory/000/314/314814
galaxy.jobs.runners DEBUG 2021-06-25 23:11:04,583 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] Job [314814] queued (67.722 ms)
galaxy.jobs.handler INFO 2021-06-25 23:11:04,600 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Job dispatched
galaxy.jobs.command_factory INFO 2021-06-25 23:11:04,986 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] Built script [/data/jobs_directory/000/314/314814/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/314/314814/registry.xml' '/data/jobs_directory/000/314/314814/upload_params.json' '420557:/data/jobs_directory/000/314/314814/working/dataset_420557_files:/data/jobs_directory/000/314/314814/outputs/galaxy_dataset_c75fbbd3-3058-4adc-b53e-77ac8dfac684.dat']
galaxy.jobs.runners DEBUG 2021-06-25 23:11:05,326 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] (314814) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/000/314/314814/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/000/314/314814'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-06-25 23:11:05,490 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] (314814) executing job script: /data/jobs_directory/000/314/314814/galaxy_314814.sh
galaxy.jobs.runners.util.process_groups DEBUG 2021-06-25 23:11:05,585 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] check_pg(): No process found in process group 29708
galaxy.jobs.runners.local DEBUG 2021-06-25 23:11:05,631 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] execution finished: /data/jobs_directory/000/314/314813/galaxy_314813.sh
galaxy.jobs DEBUG 2021-06-25 23:11:05,732 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] finish(): Moved /data/jobs_directory/000/314/314813/outputs/galaxy_dataset_a5f7b6b8-87c3-4705-94c6-e1b2237c21c7.dat to /data/database/files/000/420/dataset_420556.dat
galaxy.model.metadata DEBUG 2021-06-25 23:11:05,782 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] loading metadata from file for: HistoryDatasetAssociation 613088
galaxy.jobs INFO 2021-06-25 23:11:05,942 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] Collecting metrics for Job 314813 in /data/jobs_directory/000/314/314813
galaxy.jobs DEBUG 2021-06-25 23:11:06,208 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-0] job_wrapper.finish for job 314813 executed (507.493 ms)
galaxy.jobs.runners.util.process_groups DEBUG 2021-06-25 23:11:11,941 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] check_pg(): No process found in process group 29741
galaxy.jobs.runners.local DEBUG 2021-06-25 23:11:11,961 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] execution finished: /data/jobs_directory/000/314/314814/galaxy_314814.sh
galaxy.jobs DEBUG 2021-06-25 23:11:12,029 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] finish(): Moved /data/jobs_directory/000/314/314814/outputs/galaxy_dataset_c75fbbd3-3058-4adc-b53e-77ac8dfac684.dat to /data/database/files/000/420/dataset_420557.dat
galaxy.model.metadata DEBUG 2021-06-25 23:11:12,072 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] loading metadata from file for: HistoryDatasetAssociation 613089
galaxy.jobs INFO 2021-06-25 23:11:12,227 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] Collecting metrics for Job 314814 in /data/jobs_directory/000/314/314814
galaxy.objectstore CRITICAL 2021-06-25 23:11:12,556 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] None delete error [Errno 2] No such file or directory: 'tmpcedgcovx_stderr'
galaxy.jobs DEBUG 2021-06-25 23:11:12,556 [pN:galaxy-worker-79bbb59559-nhlbw,p:6,tN:LocalRunner.work_thread-1] job_wrapper.finish for job 314814 executed (562.165 ms)
```

```
galaxy.jobs.handler DEBUG 2021-06-25 23:11:04,379 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] Grabbed Job(s): 314814
galaxy.jobs.mapper DEBUG 2021-06-25 23:11:04,442 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-06-25 23:11:04,473 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Dispatching to local runner
galaxy.jobs DEBUG 2021-06-25 23:11:04,496 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-06-25 23:11:04,578 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Working directory for job is: /data/jobs_directory/000/314/314814
galaxy.jobs.runners DEBUG 2021-06-25 23:11:04,588 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] Job [314814] queued (114.614 ms)
galaxy.jobs.handler INFO 2021-06-25 23:11:04,597 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:JobHandlerQueue.monitor_thread] (314814) Job dispatched
galaxy.jobs.command_factory INFO 2021-06-25 23:11:05,006 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] Built script [/data/jobs_directory/000/314/314814/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/000/314/314814/registry.xml' '/data/jobs_directory/000/314/314814/upload_params.json' '420557:/data/jobs_directory/000/314/314814/working/dataset_420557_files:/data/jobs_directory/000/314/314814/outputs/galaxy_dataset_c75fbbd3-3058-4adc-b53e-77ac8dfac684.dat']
galaxy.jobs.runners DEBUG 2021-06-25 23:11:05,256 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] (314814) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/000/314/314814/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/000/314/314814'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-06-25 23:11:05,317 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] (314814) executing job script: /data/jobs_directory/000/314/314814/galaxy_314814.sh
galaxy.jobs.runners.util.process_groups DEBUG 2021-06-25 23:11:12,361 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] check_pg(): No process found in process group 3179
galaxy.jobs.runners.local ERROR 2021-06-25 23:11:12,380 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] failure running job 314814
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/jobs/runners/local.py", line 138, in queue_job
    stdout_file.close()
  File "/usr/local/lib/python3.8/tempfile.py", line 499, in close
    self._closer.close()
  File "/usr/local/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/data/jobs_directory/000/314/314814/tmp81kovm71_stdout'
galaxy.jobs ERROR 2021-06-25 23:11:12,414 [pN:galaxy-worker-79bbb59559-rc8sd,p:6,tN:LocalRunner.work_thread-0] fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/data/jobs_directory/000/314/314814/outputs/galaxy_dataset_c75fbbd3-3058-4adc-b53e-77ac8dfac684.dat'
```

**Comment by innovate-invent** [comment]
Just speculating, but could the double scheduling be occurring on the tail end of the job where the lock is being released but the state has yet to be applied that would stop another thread from rescheduling it? It is mostly happening on upload jobs that execute very quickly.

**Comment by innovate-invent** [comment]
To reproduce this install [terraform](https://github.com/brinkmanlab/galaxy-container) and python3 with bioblend.

```
git clone git@github.com:brinkmanlab/galaxy-container.git

cd galaxy-container/deployment/docker
```

set `worker_replicas = 3` in `./changeme.auto.tfvars`

(If you are on a mac, see the https://github.com/brinkmanlab/galaxy-container#osx-peculiarities )

```
terraform init
./deploy.sh
cd ../../
```

Edit line 68 of test_race.py to include the admin api key outputted in the previous step.
Run test_race.py

It will hammer the server with uploads until the race condition occurs.

Go to https://localhost:8000/ and log in as `admin` to explore the uploads and error.
