### ISSUE TITLE
Galaxy job finish script moves file before it is done with it

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11421]
Galaxy 21.01
I am encountering this error:
```
galaxy.jobs.handler DEBUG 2021-02-19 18:50:54,111 Grabbed Job(s): 5377
galaxy.jobs.mapper DEBUG 2021-02-19 18:50:54,147 (5377) Mapped job to destination id: local-tiny
galaxy.jobs.handler DEBUG 2021-02-19 18:50:54,158 (5377) Dispatching to local runner
galaxy.jobs DEBUG 2021-02-19 18:50:54,174 (5377) Persisting job destination (destination id: local-tiny)
galaxy.jobs DEBUG 2021-02-19 18:50:54,215 (5377) Working directory for job is: /data/jobs_directory/005/5377
galaxy.jobs.runners DEBUG 2021-02-19 18:50:54,224 Job [5377] queued (65.351 ms)
galaxy.jobs.handler INFO 2021-02-19 18:50:54,234 (5377) Job dispatched
galaxy.jobs.command_factory INFO 2021-02-19 18:50:54,480 Built script [/data/jobs_directory/005/5377/tool_script.sh] for tool command [python '/srv/galaxy/tools/data_source/upload.py' '/srv/galaxy' '/data/jobs_directory/005/5377/registry.xml' '/data/jobs_directory/005/5377/upload_params.json' '5377:/data/jobs_directory/005/5377/working/dataset_5377_files:/data/jobs_directory/005/5377/outputs/galaxy_dataset_2e3c9e13-8821-49a6-be7b-72bf09ee66de.dat']
galaxy.jobs.runners DEBUG 2021-02-19 18:50:54,697 (5377) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/jobs_directory/005/5377/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/jobs_directory/005/5377'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-02-19 18:50:54,796 (5377) executing job script: /data/jobs_directory/005/5377/galaxy_5377.sh
galaxy.jobs.runners.util.process_groups DEBUG 2021-02-19 18:51:00,204 check_pg(): No process found in process group 11007
galaxy.jobs.runners.local DEBUG 2021-02-19 18:51:00,220 execution finished: /data/jobs_directory/005/5377/galaxy_5377.sh
galaxy.jobs DEBUG 2021-02-19 18:51:00,282 finish(): Moved /data/jobs_directory/005/5377/outputs/galaxy_dataset_2e3c9e13-8821-49a6-be7b-72bf09ee66de.dat to /data/database/files/005/dataset_5377.dat
galaxy.model.metadata DEBUG 2021-02-19 18:51:00,319 loading metadata from file for: HistoryDatasetAssociation 5377
galaxy.jobs.runners ERROR 2021-02-19 18:51:00,326 (5377/) Job wrapper finish method failed
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/jobs/runners/__init__.py", line 540, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "/srv/galaxy/lib/galaxy/jobs/__init__.py", line 1681, in finish
    self._finish_dataset(
  File "/srv/galaxy/lib/galaxy/jobs/__init__.py", line 1543, in _finish_dataset
    self.external_output_metadata.load_metadata(dataset, output_name, self.sa_session, working_directory=self.working_directory, remote_metadata_directory=remote_metadata_directory)
  File "/srv/galaxy/lib/galaxy/metadata/__init__.py", line 209, in load_metadata
    self._load_metadata_from_path(dataset, metadata_output_path, working_directory, remote_metadata_directory)
  File "/srv/galaxy/lib/galaxy/metadata/__init__.py", line 86, in _load_metadata_from_path
    dataset.metadata.from_JSON_dict(metadata_output_path, path_rewriter=path_rewriter)
  File "/srv/galaxy/lib/galaxy/model/metadata.py", line 177, in from_JSON_dict
    JSONified_dict = json.load(fh)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
galaxy.jobs ERROR 2021-02-19 18:51:00,342 fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/data/jobs_directory/005/5377/outputs/galaxy_dataset_2e3c9e13-8821-49a6-be7b-72bf09ee66de.dat'
```

It appears that the dataset is being moved to the object store before the script is done reading it.

https://github.com/galaxyproject/galaxy/blob/7ac4278febbdbc324493a8d9b1ca9fa6a7eb6b66/lib/galaxy/jobs/__init__.py#L1646 is happening before https://github.com/galaxyproject/galaxy/blob/7ac4278febbdbc324493a8d9b1ca9fa6a7eb6b66/lib/galaxy/jobs/__init__.py#L1685

**Comment by innovate-invent** [comment]
This was very likely resolved with #11335, closing for now.
