### ISSUE TITLE
Unhandled error when creating tags for histories or datasets

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11451]
I know that this is an attempt to destroy the Galaxy and not a normal use of the tags, but maybe we can sanitize a bit more strange inputs to avoid internal errors or weird results.

### Steps to reproduce
1. Create a new history
2. Edit history tags
3. Input `...` (3 dots) as tag
4. Surprise!

After the error, you can not do any operation to update the history information like renaming, enter any other tag or annotation, etc. until you refresh the page.

The log:
````python
galaxy.web.framework.decorators ERROR 2021-02-23 12:24:13,429 [p:203,w:1,m:0] [uWSGIWorker1Core2] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/histories.py", line 471, in update
    self.deserializer.deserialize(history, payload, user=trans.user, trans=trans)
  File "lib/galaxy/managers/base.py", line 741, in deserialize
    new_dict[key] = self.deserializers[key](item, key, val, **context)
  File "lib/galaxy/managers/taggable.py", line 93, in deserialize_tags
    _tags_from_strings(item, self.app.tag_handler, new_tags_list, user=user)
  File "lib/galaxy/managers/taggable.py", line 44, in _tags_from_strings
    tag_handler.apply_item_tags(user, item, unicodify(new_tags_str, 'utf-8'))
  File "lib/galaxy/model/tags.py", line 193, in apply_item_tags
    self.apply_item_tag(user, item, name, value, flush=flush)
  File "lib/galaxy/model/tags.py", line 165, in apply_item_tag
    tag = self._get_or_create_tag(lc_name)
  File "lib/galaxy/model/tags.py", line 253, in _get_or_create_tag
    tag = self._create_tag(scrubbed_tag_str)
  File "lib/galaxy/model/tags.py", line 226, in _create_tag
    tag_name = tag_prefix + self._scrub_tag_name(sub_tag)
TypeError: must be str, not NoneType
````

**Comment by jmchilton** [comment]
Sounds like this is fixed right? Thanks so much for finding this and following through!
