### ISSUE TITLE
weird interaction between workflows, toolbox filters, and possibly API

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11455]
I've found out that tools hidden using a toolbox filter do not behave consistently. 

Traceback below is from executing a `export_to_path` tool as a part of workflow using API. The user executing it is an admin, and the filter used restricts the tool to admins only. The user can run the tool via GUI.

Traceback:

```
galaxy.workflow.modules INFO 2021-02-23 16:19:04,382 [p:8059,w:0,m:1] [WorkflowRequestMonitor.monitor_thread] Exact tool specified during workflow module creation for [export_to_path] but couldn't find correct version [0.0.2].
galaxy.workflow.modules WARNING 2021-02-23 16:19:04,384 [p:8059,w:0,m:1] [WorkflowRequestMonitor.monitor_thread] The tool 'export_to_path' is missing. Cannot build workflow module.
galaxy.workflow.run ERROR 2021-02-23 16:19:04,384 [p:8059,w:0,m:1] [WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/workflow/run.py", line 174, in invoke
    remaining_steps = self.progress.remaining_steps()
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/workflow/run.py", line 306, in remaining_steps
    self.module_injector.inject(step, step_args=self.param_map.get(step.id, {}))
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/workflow/modules.py", line 1975, in inject
    module.add_dummy_datasets(connections=step.input_connections, steps=steps)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/workflow/modules.py", line 1533, in add_dummy_datasets
    tool_id=self.tool_id)
galaxy.exceptions.ToolMissingException: Tool export_to_path missing. Cannot add dummy datasets.
```

**Comment by mvdbeek** [comment]
That looks like the handler doesn't have the tool, this is not related to the toolbox filter. Any chance a restart of the workflow handler solves this ?

**Comment by martenson** [comment]
It didn't fix that yesterday, it did fix it today. :shipit:
