### ISSUE TITLE
Trackster doesn’t zoom tracks beyond certain level

### ISSUE THREAD

**Issue by lklucar** [galaxyproject/galaxy#11529]
Trackster in my galaxy installation [20.09] doesn't allow zoom-in beyond certain level. Galaxy log gives following error:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 153, in __call__
xxx.xxx.xxx.xxx - - [02/Mar/2021:22:58:45 +0200] "GET /api/genomes/hg38?data_type=data&chrom=chr2&low=120872648&high=120960364&mode=Squish&resolution=219.292409240924
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 153, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/usr/local/galaxy/.venv/lib/python3.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/usr/local/galaxy/.venv/lib/python3.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 141, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 220, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 56, in call_and_format
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/genomes.py", line 42, in show
    rval = {'dataset_type': 'refseq', 'data': region.sequence}
AttributeError: 'NoneType' object has no attribute 'sequence'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 70, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 163, in __call__
    exc_info)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 69, in replacement_start_response
    return start_response(status, headers, exc_info)
SystemError: <built-in function uwsgi_spit> returned a result with an error set
{address space usage: 3648712704 bytes/3479MB} {rss usage: 536530944 bytes/511MB} [pid: 87746|app: 0|req: 775/3095] xxx.xxx.xxx.xxx () {74 vars in 1592 bytes} [Tue Ma
    app_iter = self.application(environ, sr_checker)
  File "/usr/local/galaxy/.venv/lib/python3.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/usr/local/galaxy/.venv/lib/python3.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 141, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 220, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 56, in call_and_format
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/genomes.py", line 42, in show
    rval = {'dataset_type': 'refseq', 'data': region.sequence}
AttributeError: 'NoneType' object has no attribute 'sequence'
```
Reference sequence is also not displayed.

Any help how to fix this?

thanks
Lubos

**Comment by microfuge** [comment]
Hi,

I find that users of our instance like trackster a lot and the convenience of easy adding of datasets is unparalleled, especially for new users. This also does not need the genomes to be available externallly (like for UCSC, IGV etc). 

It seems like trackster is not able to get the sliced genome sequence which is requested after a certain zoom-in level and fails as you showed in the log. This results in the display being greyed out after that zoom level.

The same error happens when pointing the galaxy API to endpoint  requesting a slice of genome sequence  `<galaxy url>/api/genomes/<genome id>/sequences?chrom=<chrom name>&low=<start coordinate>&high=<end coordinate>` 

The following code change in my testing seems to fix this - 

```
diff --git a/lib/galaxy/visualization/genomes.py b/lib/galaxy/visualization/genomes.py
index 9931b889dd..b7ad266ced 100644
--- a/lib/galaxy/visualization/genomes.py
+++ b/lib/galaxy/visualization/genomes.py
@@ -408,6 +408,6 @@ class Genomes:
         # Read and return reference data.
         with open(twobit_file_name, "rb") as f:
             twobit = TwoBitFile(f)
-            if chrom in twobit:
-                seq_data = twobit[chrom].get(int(low), int(high))
+            if chrom.encode() in twobit:
+                seq_data = twobit[chrom.encode()].get(int(low), int(high))
                 return GenomeRegion(chrom=chrom, start=low, end=high, sequence=seq_data)
```

The errors seems to be because the [bx-python](https://github.com/bxlab/bx-python/issues/31) library returns the twoBit chromosome names in bytestrings which don't match the chromosome name strings in Galaxy. 


Post this, trackster zooms in and the nucleotide s are displayed and the API also starts working. 


![trackster](https://user-images.githubusercontent.com/22501424/185794249-330d896a-6427-4fdc-988f-5b6a8ec40729.png)

**Comment by guerler** [comment]
Closing this, since Trackster has been deprecated and replaced by IGV.
