### ISSUE TITLE
Tool testing - SQLite OperationalError: database is locked

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1158]
For production use, postgresql is recommended, with mysql as a second choice, with SQLite absolutely not a good idea. On the other hand, for local testing during tool development and continuous integration, SQLite has been a useful straightforward system.

It was recommended (although right now I can't recall when or where) to use the following environment variable setting, which I have been using with TravisCI:

```
export GALAXY_TEST_UPLOAD_ASYNC=false
```

However, it is my impression that I have been seeing far more SQLite `OperationalError` exceptions recently from TravisCI leading to test runs failing. These normally work on a retry (losing the evidence).

**Comment by peterjc** [comment]
Most recently, one of the four targets failed in this build using the `jobs` table: https://travis-ci.org/peterjc/pico_galaxy/builds/91567501 - full log https://s3.amazonaws.com/archive.travis-ci.org/jobs/92071055/log.txt - the first failure message in the overly verbose log is:

```
...
galaxy.datatypes.metadata DEBUG 2015-11-19 16:01:09,525 loading metadata from file for: HistoryDatasetAssociation 22
requests.packages.urllib3.connectionpool DEBUG 2015-11-19 16:01:09,533 "GET /api/histories/da92407cb46a61f3?key=0d2ff1fa8df9e0777a847e37c010cb52 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2015-11-19 16:01:09,535 Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool DEBUG 2015-11-19 16:01:10,824 "GET /api/histories/da92407cb46a61f3?key=0d2ff1fa8df9e0777a847e37c010cb52 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2015-11-19 16:01:10,827 Starting new HTTP connection (1): localhost
galaxy.jobs INFO 2015-11-19 16:01:12,052 Collecting metrics for Job 22
galaxy.jobs DEBUG 2015-11-19 16:01:14,089 job 22 ended (finish() executed in (5353.932 ms))
galaxy.datatypes.metadata DEBUG 2015-11-19 16:01:15,105 Cleaning up external metadata files
galaxy.jobs.handler ERROR 2015-11-19 16:01:15,453 Exception in monitor_step
Traceback (most recent call last):
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/jobs/handler.py", line 649, in monitor
    self.monitor_step()
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/jobs/handler.py", line 667, in monitor_step
    ( model.Job.handler == self.app.config.server_name ) ).all()
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'SELECT job.id AS job_id, job.create_time AS job_create_time, job.update_time AS job_update_time, job.history_id AS job_history_id, job.library_folder_id AS job_library_folder_id, job.tool_id AS job_tool_id, job.tool_version AS job_tool_version, job.state AS job_state, job.info AS jException in thread WorkflowRequestMonitor.monitor_thread:
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/python/2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/workflow/scheduling_manager.py", line 158, in __monitor
    self.__schedule( workflow_scheduler_id, workflow_scheduler )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/workflow/scheduling_manager.py", line 162, in __schedule
    invocation_ids = self.__active_invocation_ids( workflow_scheduler_id )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/workflow/scheduling_manager.py", line 191, in __active_invocation_ids
    handler=handler,
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/model/__init__.py", line 3546, in poll_active_workflow_ids
    return map( lambda wi: wi.id, query.all() )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'SELECT workflow_invocation.id AS workflow_invocation_id, workflow_invocation.create_time AS workflow_invocation_create_time, workflow_invocation.update_time AS workflow_invocation_update_time, workflow_invocation.workflow_id AS workflow_invocation_workflow_id, workflow_invocation.state AS workflow_invocation_state, workflow_invocation.scheduler AS workflow_invocation_scheduler, workflow_invocation.handler AS workflow_invocation_handler, workflow_invocation.uuid AS workflow_invocation_uuid, workflow_invocation.history_id AS workflow_invocation_history_id, workflow_invocation_step_1.id AS workflow_invocation_step_1_id, workflow_invocation_step_1.create_time AS workflow_invocation_step_1_create_time, workflow_invocation_step_1.update_time AS workflow_invocation_step_1_update_time, workflow_invocation_step_1.workflow_invocation_id AS workflow_invocation_step_1_workflow_invocation_id, workflow_invocation_step_1.workflow_step_id AS workflow_invocation_step_1_workflow_step_id, workflow_invocation_step_1.job_id AS workflow_invocation_step_1_job_id, workflow_invocation_step_1.action AS workflow_invocation_step_1_action \nFROM workflow_invocation LEFT OUTER JOIN workflow_invocation_step AS workflow_invocation_step_1 ON workflow_invocation.id = workflow_invocation_step_1.workflow_invocation_id \nWHERE (workflow_invocation.state = ? OR workflow_invocation.state = ?) AND workflow_invocation.scheduler = ? AND workflow_invocation.handler = ?'] [parameters: ('new', 'ready', 'core', 'main')]
...
```

**Comment by jmchilton** [comment]
16.01 contains dozens of sql and tool running optimizations and I have actually now seen a decrease in this - I don't see sql locking from tool running at all anymore - even for large collections of tools run simultaneously.

**Comment by peterjc** [comment]
Good news :)

Shall we close this? I don't recall having problem with locking recently but have not been running many TravisCI jobs recently.

**Comment by peterjc** [comment]
Sadly I am still seeing intermittent SQlite locking failures on TravisCI, including under Python 2.7 with the dev branch of Galaxy. e.g. https://travis-ci.org/peterjc/galaxy_mira/jobs/108283442 which I just restarted.

(Now that some of the other issues causing my tests to fail have been resolved, I will try to record a few more instances of SQLite locking failures before requesting a re-test)

**Comment by peterjc** [comment]
Here's an interesting one, from a re-run of https://travis-ci.org/peterjc/galaxy_blast/jobs/107255016 running with Galaxy dev under Python 2.6.9, where kombu had a problem and the database was locked when trying to read the `workflow_invocation` table - there were more locked error messages later in the log:

```
...
galaxy.jobs DEBUG 2016-02-17 10:05:30,853 (3) Persisting job destination (destination id: local:///)
requests.packages.urllib3.connectionpool DEBUG 2016-02-17 10:05:31,084 "GET /api/histories/529fd61ab1c6cc36?key=cc4929e54b50a1b5e56c4df1f7a02021 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2016-02-17 10:05:33,168 Starting new HTTP connection (1): localhost
kombu.mixins WARNING 2016-02-17 10:05:36,308 Connection to broker lost, trying to re-establish connection...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/mixins.py", line 199, in consume
    conn.drain_events(timeout=safety_interval)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/__init__.py", line 830, in drain_events
    item, channel = get(timeout=timeout)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/__init__.py", line 850, in _drain_channel
    return channel.drain_events(timeout=timeout)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/__init__.py", line 642, in drain_events
    return self._poll(self.cycle, timeout=timeout)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/__init__.py", line 328, in _poll
    return cycle.get()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/sqlalchemy/__init__.py", line 92, in _get
    obj = self._get_or_create(queue)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/kombu/transport/sqlalchemy/__init__.py", line 69, in _get_or_create
    .filter(self.queue_cls.name == queue).first()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2445, in first
    ret = list(self[0:1])
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
    return list(res)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT kombu_queue.id AS kombu_queue_id, kombu_queue.name AS kombu_queue_name \nFROM kombu_queue \nWHERE kombu_queue.name = ?\n LIMIT ? OFFSET ?'] [parameters: ('control.main', 1, 0)]
Exception in thread WorkflowRequestMonitor.monitor_thread:
Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/workflow/scheduling_manager.py", line 158, in __monitor
    self.__schedule( workflow_scheduler_id, workflow_scheduler )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/workflow/scheduling_manager.py", line 163, in __schedule
    invocation_ids = self.__active_invocation_ids( workflow_scheduler_id )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/workflow/scheduling_manager.py", line 192, in __active_invocation_ids
    handler=handler,
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/model/__init__.py", line 3885, in poll_active_workflow_ids
    return map( lambda wi: wi.id, query.all() )
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT workflow_invocation.id AS workflow_invocation_id, workflow_invocation.create_time AS workflow_invocation_create_time, workflow_invocation.update_time AS workflow_invocation_update_time, workflow_invocation.workflow_id AS workflow_invocation_workflow_id, workflow_invocation.state AS workflow_invocation_state, workflow_invocation.scheduler AS workflow_invocation_scheduler, workflow_invocation.handler AS workflow_invocation_handler, workflow_invocation.uuid AS workflow_invocation_uuid, workflow_invocation.history_id AS workflow_invocation_history_id, workflow_invocation_step_1.id AS workflow_invocation_step_1_id, workflow_invocation_step_1.create_time AS workflow_invocation_step_1_create_time, workflow_invocation_step_1.update_time AS workflow_invocation_step_1_update_time, workflow_invocation_step_1.workflow_invocation_id AS workflow_invocation_step_1_workflow_invocation_id, workflow_invocation_step_1.workflow_step_id AS workflow_invocation_step_1_workflow_step_id, workflow_invocation_step_1.job_id AS workflow_invocation_step_1_job_id, workflow_invocation_step_1.action AS workflow_invocation_step_1_action \nFROM workflow_invocation LEFT OUTER JOIN workflow_invocation_step AS workflow_invocation_step_1 ON workflow_invocation.id = workflow_invocation_step_1.workflow_invocation_id \nWHERE (workflow_invocation.state = ? OR workflow_invocation.state = ?) AND workflow_invocation.scheduler = ? AND workflow_invocation.handler = ?'] [parameters: ('new', 'ready', 'core', 'main')]

galaxy.jobs.runners.local DEBUG 2016-02-17 10:05:36,381 execution finished: /tmp/tmpGoJEHo/tmpDpdF8J/job_working_directory_yvL4fU/000/3/galaxy_3.sh
requests.packages.urllib3.connectionpool DEBUG 2016-02-17 10:05:36,720 "GET /api/histories/529fd61ab1c6cc36?key=cc4929e54b50a1b5e56c4df1f7a02021 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2016-02-17 10:05:36,723 Starting new HTTP connection (1): localhost
galaxy.model.metadata DEBUG 2016-02-17 10:05:36,791 loading metadata from file for: HistoryDatasetAssociation 3
...
```

**Comment by peterjc** [comment]
Another example from a rerun of https://travis-ci.org/peterjc/galaxy_blast/jobs/107255016 using Galaxy dev under Python 2.6.9:

```
...
galaxy.jobs.runners.local DEBUG 2016-02-16 13:58:23,229 (9) executing job script: /tmp/tmpLgOdh6/tmpFY89hY/job_working_directory_pocLXs/000/9/galaxy_9.sh
galaxy.jobs DEBUG 2016-02-16 13:58:23,248 (9) Persisting job destination (destination id: local:///)
requests.packages.urllib3.connectionpool DEBUG 2016-02-16 13:58:23,330 "GET /api/histories/f3f73e481f432006?key=f34fc6b602e1713b23b22fd658c057c4 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2016-02-16 13:58:26,050 Starting new HTTP connection (1): localhost
galaxy.jobs.runners.local DEBUG 2016-02-16 13:58:26,051 execution finished: /tmp/tmpLgOdh6/tmpFY89hY/job_working_directory_pocLXs/000/9/galaxy_9.sh
requests.packages.urllib3.connectionpool DEBUG 2016-02-16 13:58:26,693 "GET /api/histories/f3f73e481f432006?key=f34fc6b602e1713b23b22fd658c057c4 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2016-02-16 13:58:26,697 Starting new HTTP connection (1): localhost
galaxy.model.metadata DEBUG 2016-02-16 13:58:26,882 loading metadata from file for: HistoryDatasetAssociation 9
requests.packages.urllib3.connectionpool DEBUG 2016-02-16 13:58:26,918 "GET /api/histories/f3f73e481f432006?key=f34fc6b602e1713b23b22fd658c057c4 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool INFO 2016-02-16 13:58:26,923 Starting new HTTP connection (1): localhost
Error - <class 'sqlalchemy.exc.OperationalError'>: (sqlite3.OperationalError) database is locked [SQL: u'SELECT api_keys.id AS api_keys_id, api_keys.create_time AS api_keys_create_time, api_keys.user_id AS api_keys_user_id, api_keys."key" AS api_keys_key \nFROM api_keys \nWHERE api_keys."key" = ?'] [parameters: (u'f34fc6b602e1713b23b22fd658c057c4',)]
URL: http://localhost:9837/api/histories/f3f73e481f432006?key=f34fc6b602e1713b23b22fd658c057c4
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/base.py', line 153 in handle_request
  trans = self.transaction_factory( environ )
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/webapp.py', line 67 in <lambda>
  self.set_transaction_factory( lambda e: self.transaction_chooser( e, galaxy_app, session_cookie ) )
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/webapp.py', line 98 in transaction_chooser
  return GalaxyWebTransaction( environ, galaxy_app, self, session_cookie )
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/webapp.py', line 197 in __init__
  self.error_message = self._authenticate_api( session_cookie )
File '/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/webapp.py', line 367 in _authenticate_api
  provided_key = self.sa_session.query( self.app.model.APIKeys ).filter( self.app.model.APIKeys.table.c.key == api_key ).one()
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py', line 2473 in one
  ret = list(self)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py', line 2516 in __iter__
  return self._execute_and_instances(context)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/orm/query.py', line 2531 in _execute_and_instances
  result = conn.execute(querycontext.statement, self._params)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py', line 914 in execute
  return meth(self, multiparams, params)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/sql/elements.py', line 323 in _execute_on_connection
  return connection._execute_clauseelement(self, multiparams, params)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py', line 1010 in _execute_clauseelement
  compiled_sql, distilled_params
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py', line 1146 in _execute_context
  context)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py', line 1341 in _handle_dbapi_exception
  exc_info
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/util/compat.py', line 199 in raise_from_cause
  reraise(type(exception), exception, tb=exc_tb)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/base.py', line 1139 in _execute_context
  context)
File '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/sqlalchemy/engine/default.py', line 450 in do_execute
  cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT api_keys.id AS api_keys_id, api_keys.create_time AS api_keys_create_time, api_keys.user_id AS api_keys_user_id, api_keys."key" AS api_keys_key \nFROM api_keys \nWHERE api_keys."key" = ?'] [parameters: (u'f34fc6b602e1713b23b22fd658c057c4',)]
...
```

**Comment by dylanbstorey** [comment]
@peterjc , did you ever get a solution for this ?

**Comment by peterjc** [comment]
Not really, I still have to re-run TravisCI now and again due to the locking problems.

**Comment by hexylena** [comment]
I guess the easiest solution would be switching to postgres during testing? Travis includes some things for setting up postgresql: https://docs.travis-ci.com/user/database-setup/#postgresql
