### ISSUE TITLE
Activating virtualenv at .venv ends up up these lines..

### ISSUE THREAD

**Issue by scientistic** [galaxyproject/galaxy#11615]
The Galaxy client build is up to date and will not be rebuilt at this time.
Activating virtualenv at .venv
Traceback (most recent call last):
  File "/Users/shahid/galaxy/lib/galaxy/util/filelock.py", line 43, in acquire
    self.fd = os.open(self.lockfile, os.O_CREAT | os.O_EXCL | os.O_RDWR)
FileExistsError: [Errno 17] File exists: '/Users/shahid/galaxy/database/dependencies/conda.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/installable.py", line 70, in ensure_installed
    with FileLock(os.path.join(parent_path, desc.lower()), timeout=300):
  File "/Users/shahid/galaxy/lib/galaxy/util/filelock.py", line 68, in __enter__
    self.acquire()
  File "/Users/shahid/galaxy/lib/galaxy/util/filelock.py", line 49, in acquire
    raise FileLockException("Timeout occurred.")
galaxy.util.filelock.FileLockException: Timeout occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/manage_tool_dependencies.py", line 40, in <module>
    main()
  File "/Users/shahid/galaxy/lib/galaxy/util/script.py", line 45, in main
    action_func(args, kwargs)
  File "./scripts/manage_tool_dependencies.py", line 16, in _init_if_needed
    _build_dependency_manager_no_config(kwargs)
  File "./scripts/manage_tool_dependencies.py", line 29, in _build_dependency_manager_no_config
    dependency_manager = build_dependency_manager(app_config_dict=kwargs, conf_file=dependency_resolvers_config_file, default_tool_dependency_dir="database/dependencies")
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/__init__.py", line 90, in build_dependency_manager
    dependency_manager = DependencyManager(**dependency_manager_kwds)
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/__init__.py", line 131, in __init__
    self.dependency_resolvers = self.__parse_resolver_conf_plugins(plugin_source)
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/__init__.py", line 333, in __parse_resolver_conf_plugins
    return plugin_config.load_plugins(self.resolver_classes, plugin_source, extra_kwds, plugin_type_keys=['type', 'resolver_type'])
  File "/Users/shahid/galaxy/lib/galaxy/util/plugin_config.py", line 37, in load_plugins
    return __load_plugins_from_dicts(plugins_dict, plugin_source.source, extra_kwds, plugin_type_keys=plugin_type_keys)
  File "/Users/shahid/galaxy/lib/galaxy/util/plugin_config.py", line 81, in __load_plugins_from_dicts
    plugin = plugins_dict[plugin_type](**plugin_kwds)
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/resolvers/conda.py", line 138, in __init__
    self.disabled = not galaxy.tool_util.deps.installable.ensure_installed(conda_context, install_conda, self.auto_init)
  File "/Users/shahid/galaxy/lib/galaxy/tool_util/deps/installable.py", line 75, in ensure_installed
    raise Exception("Failed to get file lock for %s" % os.path.join(parent_path, desc.lower()))
Exception: Failed to get file lock for /Users/shahid/galaxy/database/dependencies/conda
Executing: .venv/bin/uwsgi --module 'galaxy.webapps.galaxy.buildapp:uwsgi_app()' --virtualenv /Users/shahid/galaxy/.venv --static-safe /Users/shahid/galaxy/client/src/assets --pythonpath lib --threads 4 --buffer-size 16384 --http localhost:8080 --static-map /static=/Users/shahid/galaxy/static --static-map /favicon.ico=/Users/shahid/galaxy/static/favicon.ico --die-on-term --hook-master-start 'unix_signal:2 gracefully_kill_them_all' --hook-master-start 'unix_signal:15 gracefully_kill_them_all' --enable-threads --umask 027 --py-call-osafterfork 
dyld: Library not loaded: @rpath/libpcre.1.dylib
  Referenced from: /Users/shahid/galaxy/.venv/bin/uwsgi
  Reason: image not found
run.sh: line 91: 19848 Abort trap: 6           .venv/bin/uwsgi --module 'galaxy.webapps.galaxy.buildapp:uwsgi_app()' --virtualenv /Users/shahid/galaxy/.venv --static-safe /Users/shahid/galaxy/client/src/assets --pythonpath lib --threads 4 --buffer-size 16384 --http localhost:8080 --static-map /static=/Users/shahid/galaxy/static --static-map /favicon.ico=/Users/shahid/galaxy/static/favicon.ico --die-on-term --hook-master-start 'unix_signal:2 gracefully_kill_them_all' --hook-master-start 'unix_signal:15 gracefully_kill_them_all' --enable-threads --umask 027 --py-call-osafterfork
(base) shahid@Shahids-MacBook-Pro galaxy %

**Comment by martenson** [comment]
this issue is likely very outdated, please feel free to reopen and update with new info if I am wrong
