### ISSUE TITLE
retry metadata loading (for unsynced data on NFS)

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#11875]
```
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 540, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "lib/galaxy/jobs/__init__.py", line 1682, in finish
    output_name, dataset, job, context, final_job_state, remote_metadata_directory
  File "lib/galaxy/jobs/__init__.py", line 1543, in _finish_dataset
    self.external_output_metadata.load_metadata(dataset, output_name, self.sa_session, working_directory=self.working_directory, remote_metadata_directory=remote_metadata_directory)
  File "lib/galaxy/metadata/__init__.py", line 209, in load_metadata
    self._load_metadata_from_path(dataset, metadata_output_path, working_directory, remote_metadata_directory)
  File "lib/galaxy/metadata/__init__.py", line 86, in _load_metadata_from_path
    dataset.metadata.from_JSON_dict(metadata_output_path, path_rewriter=path_rewriter)
  File "lib/galaxy/model/metadata.py", line 202, in from_JSON_dict
    value = param.from_external_value(external_value, dataset, **from_ext_kwds)
  File "lib/galaxy/model/metadata.py", line 588, in from_external_value
    alt_name=os.path.basename(mf.file_name))
  File "lib/galaxy/objectstore/__init__.py", line 294, in update_from_file
    return self._invoke('update_from_file', obj, **kwargs)
  File "lib/galaxy/objectstore/__init__.py", line 270, in _invoke
    return self.__getattribute__("_" + delegate)(obj=obj, **kwargs)
  File "lib/galaxy/objectstore/__init__.py", line 588, in _update_from_file
    raise ex
  File "lib/galaxy/objectstore/__init__.py", line 584, in _update_from_file
    shutil.copy(file_name, path)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs1/work/songalax/galaxy/database/jobs_directory/000/111/111952/metadata/metadata_temp_file_22xaz5p1'
```

From gitter:

> mvdbeek 
> I think that may happen if the tempfile is written by the worker and then collected by a handler and it hasn't fully synced yet.

> within the same _finish_dataset method we already do this: https://github.com/mvdbeek/galaxy/blob/7febfd345fe242f92d652371400524028d1e9fc6/lib/galaxy/jobs/__init__.py#L1509 ... but we don't do it for metadata temp files 
> We might want to wrap the entire _finish_dataset method in that try/except loop ...
> I also want to move that method into a celery task, which gives us retries https://github.com/galaxyproject/galaxy/issues/11721

> bernt-matthias
> Seems less work than wrapping every single file access. And the effect should be the same .. just a bit scary if there anything else that causes OSError, ObjectNotFound?

> mvdbeek
> That and we need to make sure this is idempotent until it succeeds. Maybe the quick fix is to do the same retry here: https://github.com/mvdbeek/galaxy/blob/7febfd345fe242f92d652371400524028d1e9fc6/lib/galaxy/jobs/__init__.py#L1564

**Comment by bernt-matthias** [comment]
Hey @mvdbeek .. just thought a bit about this. Wouldn't it be better to modify the code that writes those files such that it's ensured that the files are written and readable?

**Comment by mvdbeek** [comment]
I would say no, that seems like unnecessary overhead in a overwhelming majority of cases. Most of the time this isn't necessary to move on, and there isn't a reliable way to do it that I know of.
