### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by maikenp** [galaxyproject/galaxy#11917]
Using galaxy verions 20.09

Galaxy should be able to handle the cases where something went wrong with the job, instead of causing an exception: 

```May 03 10:58:50 zpath.hepp.uiocloud.no uwsgi[275473]: Traceback (most recent call last):
May 03 10:58:50 zpath.hepp.uiocloud.no uwsgi[275473]: galaxy.jobs.handler ERROR 2021-05-03 10:58:50,596 [p:275489,w:0,m:1] [JobHandlerQueue.monitor_thread>
May 03 10:58:50 zpath.hepp.uiocloud.no uwsgi[275473]: galaxy.jobs.mapper DEBUG 2021-05-03 10:58:50,588 [p:275489,w:0,m:1] [JobHandlerQueue.monitor_thread]>
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]: AttributeError: 'NoneType' object has no attribute 'id'
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:     model.Job.user_id == job.user.id,
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:   File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 594, in __verify_job_ready
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:     state, job_destination = self.__verify_job_ready(job, job_wrapper)
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:   File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 538, in __check_job_state
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:     job_state = self.__check_job_state(job)
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]:   File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 400, in __handle_waiting_jobs
May 03 10:58:49 zpath.hepp.uiocloud.no uwsgi[275473]: Traceback (most recent call last):
```

Current solution we have found is to change the state of the job in the database. But we would like Galaxy to be able to handle such jobs in a better way than the current.  

This kind of error happens for us if a user is not logged in and tries to submit a job.

**Comment by maikenp** [comment]
Suggestion patch:
```
diff --git a/lib/galaxy/jobs/handler.py b/lib/galaxy/jobs/handler.py
index acaaa1c10e..a203790f68 100644
--- a/lib/galaxy/jobs/handler.py
+++ b/lib/galaxy/jobs/handler.py
@@ -572,6 +572,18 @@ class JobHandlerQueue(Monitors):
                 log.debug("Intentionally failing job with message (%s)" % failure_message)
             job_wrapper.fail(failure_message)
             return JOB_ERROR, job_destination
+
+        try:
+            failure_message= 'You do not seem to be logged in, and can therefore not submit jobs.'
+            assert job.user is not None, failure_message
+        except AssertionError as e:
+            failure_message= 'You do not seem to be logged in, and can therefore not submit jobs.'
+            log.debug("Intentionally failing job with message (%s)" % failure_message)
+            job_wrapper.fail(failure_message)
+            state = JOB_ERROR
+            return JOB_ERROR, job_destination
+            
+            

```

**Comment by nsoranzo** [comment]
@maikenp Can you please open a pull request to make the review process easier?
