### ISSUE TITLE
IEs: Node.js proxy crash

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#1204]
Hi,
I just updated our galaxy instance to 15.10, and I'm playing with IPython. I got the following error in the node.js proxy:

```
/opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:122
        res.setHeader('Access-Control-Allow-Origin', origin);
            ^
TypeError: Object #<Socket> has no method 'setHeader'
    at Socket.res.writeHead (/opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:122:13)
    at /opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:130:13
    at ClientRequest.onOutgoingError (/opt/galaxy-dist/lib/galaxy/web/proxy/js/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:123:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
```

After that, the proxy was dead and I needed to restart it.

**Comment by hexylena** [comment]
I'll look into this later today. Thanks for the bug report! Should be a quick fix.

**Comment by bgruening** [comment]
@abretaud can you please run the proxy with --verbose and get us a little bit more information. My guess is that the requested URL can not be handled by the proxy because it looks `strange`. Would be nice if you can figure out the requested URL.

**Comment by abretaud** [comment]
Here is a full log with --verbose:

```
Listening on 0.0.0.0:8800
PROXY WS /ipython/api/kernels/7b4ed0f6-1676-436f-a7ea-d30b4bd74f85/shell to localhost:32784
Proxy error:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

/opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:122
        res.setHeader('Access-Control-Allow-Origin', origin);
            ^
TypeError: Object #<Socket> has no method 'setHeader'
    at Socket.res.writeHead (/opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:122:13)
    at /opt/galaxy-dist/lib/galaxy/web/proxy/js/lib/proxy.js:130:13
    at ClientRequest.onOutgoingError (/opt/galaxy-dist/lib/galaxy/web/proxy/js/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:123:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
```

I think I (finally) found a way to reproduce this error:
- open a ipython notebook
- kill the proxy
- a popup opens with a reconnect button, don't touch it
- start the proxy
- wait for the docker container to exit
- (I guess it's the same if restarting the proxy here)
- click on reconnect => when receiving the first WS connection, the proxy crahes

**Comment by hexylena** [comment]
Very interesting!

We should be surviving proxy restarts successfully, so that's definitely a bug.

**Comment by hexylena** [comment]
Proxy has changed in 3 years and will change more in the future
