### ISSUE TITLE
null / -1 HID? 

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12068]
Spotted today during a class.

![image](https://user-images.githubusercontent.com/458683/119989389-68a56900-bfc7-11eb-99fd-5f58f1348fea.png)

![2021-05-28_15-12](https://user-images.githubusercontent.com/458683/119989403-6e02b380-bfc7-11eb-9344-a985f7dbbe24.png)

history id b798433517f2aa48 for the european admins.

**Comment by hexylena** [comment]
I don't think that's how the student got there, the only collections in their history are multiqc outputs.

**Comment by hexylena** [comment]
https://usegalaxy.eu/u/helena-rasche/h/imported-transcriptomics

**Comment by hexylena** [comment]
And another one, different student this time.

> I also encountered the -1 in the galaxy history, see screenshot below. This happened on 3 out of 4 of the fastqc jobs that I queued on the trimmomatic datasets while trimmomatic was still running, maybe this has something to do with it?

![image](https://user-images.githubusercontent.com/458683/120005124-d5c0fa80-bfd7-11eb-8cfe-d3e5d28f21ea.png)

I don't think collections were used there either.

**Comment by bgruening** [comment]
![grafik](https://user-images.githubusercontent.com/469983/120098233-f05cb600-c134-11eb-9813-7686b1501cec.png)

This here is inside a collection. I guess this is all on usegalaxy.EU? Which is wired since we are on 21.01 and have not changed much recently besides adding the latest commits.

**Comment by gmauro** [comment]
It happens again and we realized that here https://help.galaxyproject.org/t/qualimap-multi-sample-bamqc-does-not-load-in-center-panel/6272/12
![Screenshot from 2021-07-01 16-29-46](https://user-images.githubusercontent.com/4559911/124146011-9df11b00-da8d-11eb-84bc-e74a9c7dad9f.png)
and I found this in the log
```
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]: galaxy.web.framework.decorators ERROR 2021-07-01 16:01:27,337 [pN:main.web.4,p:3852348,w:4,m:0,tN:uWSGIWorker4Core0] Uncaught exception in exposed API method:
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]: Traceback (most recent call last):
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/web/framework/decorators.py", line 312, in decorator
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     rval = func(self, trans, *args, **kwargs)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/webapps/galaxy/api/tools.py", line 129, in build
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     return tool.to_json(trans, kwd.get('inputs', kwd), history=history)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/__init__.py", line 2178, in to_json
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     self.populate_model(request_context, self.inputs, state_inputs, tool_model['inputs'])
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/__init__.py", line 2232, in populate_model
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     tool_dict = input.to_dict(request_context)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 716, in to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     cond_dict["cases"] = list(map(nested_to_dict, self.cases))
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 714, in nested_to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     return input.to_dict(trans)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 734, in to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     when_dict["inputs"] = list(map(input_to_dict, self.inputs.values()))
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 732, in input_to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     return input.to_dict(trans)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 144, in to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     repeat_dict["inputs"] = list(map(input_to_dict, self.inputs.values()))
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/grouping.py", line 142, in input_to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     return input.to_dict(trans)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:   File "lib/galaxy/tools/parameters/basic.py", line 2273, in to_dict
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]:     d['options']['hdca'] = sorted(d['options']['hdca'], key=lambda k: k['hid'], reverse=True)
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]: TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
Jul 01 16:01:27 sn06.galaxyproject.eu uwsgi[1940451]: 109.192.195.200 - - [01/Jul/2021:16:01:27 +0200] "GET /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/qualimap_multi_bamqc/qualimap_multi_bamqc/2.2.2c/build?version=2.2.2c&__identifer=vbxf0z6wog8&tool_version=2.2.2c HTTP/1.1" 500 - "https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fqualimap_multi_bamqc%2Fqualimap_multi_bamqc%2F2.2.2c&version=2.2.2c&__identifer=vbxf0z6wog8" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by mvdbeek** [comment]
Have you seen any of this recently ? I think https://github.com/galaxyproject/galaxy/pull/12721 should have fixed this.
