### ISSUE TITLE
Rule based uploader: pysam failure on bam file

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#12069]
Problem found on usegalaxy.eu and galaxy.genouest.org while preparing a [new gtn tutorial](https://github.com/galaxyproject/training-material/pull/1484).

I'm trying to upload some tiny bam files: it works well using the classic uploader, but fails when using the rule-based one, with this tab content (col1=url, col2=name, col3=type):

```
https://zenodo.org/api/files/6080d6d6-68ec-4ade-afef-bbd83f9b5e2b/BWA-MEM_K12_Mapping.bam	BWA-MEM K12 Mapping	bam
```

I see this errors in the logs on galaxy.genouest.org:

```
galaxy.jobs.runners.drmaa DEBUG 2021-05-27 10:00:16,935 [pN:main.job-handlers.2,p:11737,w:0,m:2,tN:SlurmRunner.monitor_thread] (225810/7623171) state change: job finished normally
galaxy.jobs DEBUG 2021-05-27 10:00:16,997 [pN:main.job-handlers.2,p:11737,w:0,m:2,tN:SlurmRunner.work_thread-1] finish(): Moved /blablabla/database/jobs_directory/000/225/225810/outputs/galaxy_dataset_ce766fc4-0a3c-4650-b223-6072b9ea3545.dat to /blablabla/database/files/002/758/dataset_2758199.dat
galaxy.metadata DEBUG 2021-05-27 10:00:17,028 [pN:main.job-handlers.2,p:11737,w:0,m:2,tN:SlurmRunner.work_thread-1] setting metadata externally failed for HistoryDatasetAssociation 2833260: Traceback (most recent call last):
  File "/blablabla/lib/galaxy/metadata/set_metadata.py", line 238, in set_metadata_portable
    set_meta(dataset, file_dict)
  File "/blablabla/lib/galaxy/metadata/set_metadata.py", line 132, in set_meta
    set_meta_with_tool_provided(new_dataset_instance, file_dict, set_meta_kwds, datatypes_registry, max_metadata_value_size)
  File "/blablabla/lib/galaxy/metadata/set_metadata.py", line 96, in set_meta_with_tool_provided
    dataset_instance.datatype.set_meta(dataset_instance, **set_meta_kwds)
  File "/blablabla/lib/galaxy/datatypes/binary.py", line 521, in set_meta
    pysam.index(dataset.file_name, index_file.file_name)
  File "/blablabla/.venv/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "/blablabla/database/jobs_directory/000/225/225810/outputs/galaxy_dataset_ce766fc4-0a3c-4650-b223-6072b9ea3545.dat" is in a format that cannot be usefully indexed\n'

galaxy.jobs.runners ERROR 2021-05-27 10:00:17,052 [pN:main.job-handlers.2,p:11737,w:0,m:2,tN:SlurmRunner.work_thread-1] (225810/7623171) Job wrapper finish method failed
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 541, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "lib/galaxy/jobs/__init__.py", line 1689, in finish
    output_name, dataset, job, context, final_job_state, remote_metadata_directory
  File "lib/galaxy/jobs/__init__.py", line 1546, in _finish_dataset
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "lib/galaxy/datatypes/binary.py", line 521, in set_meta
    pysam.index(dataset.file_name, index_file.file_name)
  File "/blablabla/.venv/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "/blablabla/database/files/002/758/dataset_2758199.dat" is in a format that cannot be usefully indexed\n'
galaxy.jobs ERROR 2021-05-27 10:00:17,063 [pN:main.job-handlers.2,p:11737,w:0,m:2,tN:SlurmRunner.work_thread-1] fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/blablabla/database/jobs_directory/000/225/225810/outputs/galaxy_dataset_ce766fc4-0a3c-4650-b223-6072b9ea3545.dat'
```

The bam file looks good, and anyway it works with the classic uploader.
I guess it's just that the file is empty or not where it should be when pysam tries to read it?
Any clues?

**Comment by mvdbeek** [comment]
The URL seems to be invalid, any chance that is the problem ? I'm just getting
```
{"message":"Bucket does not exist.","status":404}
```

**Comment by abretaud** [comment]
Oh damn, this zenodo record is broken now, I'll have to fix it...
I edited the url of the bam

**Comment by abretaud** [comment]
And still failing with the good url:
![image](https://user-images.githubusercontent.com/238755/120010831-e6746f00-bfdd-11eb-9f01-55b3b7ada9a7.png)

**Comment by mvdbeek** [comment]
The edited URL still seems incorrect ?

**Comment by mvdbeek** [comment]
Hey @abretaud, can you check the URL ?

**Comment by abretaud** [comment]
Hey, sorry for the delay, there was some bug on the zenodo record, url fixed above now (https://zenodo.org/api/files/6080d6d6-68ec-4ade-afef-bbd83f9b5e2b/BWA-MEM_K12_Mapping.bam)

**Comment by mvdbeek** [comment]
This seems to be an intermittent problem with zenodo, it sometimes works and sometimes it doesn't. Not sure why it always works in the browser though, but if it doesn't work the downloaded file is empty.
Can you check if `/blablabla/database/files/002/758/dataset_2758199.dat"` has any content ?

**Comment by abretaud** [comment]
The `dataset_2758199.dat` file is empty indeed.
I've looked at a job dir for one of the failed rule-based upload: interestingly, there's a `working/gxupload_0` file which is the correct and complete bam file, maybe it's just not downloaded where it should, or not moved correctly afterwards?

**Comment by abretaud** [comment]
`working/galaxy.json` looks like this:

```
{"__unnamed_outputs": [{"destination": {"type": "hdas"}, "name": "", "elements": [{"name": "BWA-MEM K12 Mapping", "filename": "gxupload_0", "dbkey": "?", "ext": "bam", "link_data_only": false, "sources": [{"source_uri": "https://zenodo.org/api/files/6080d6d6-68ec-4ade-afef-bbd83f9b5e2b/BWA-MEM_K12_Mapping.bam"}], "hashes": [], "object_id": 59201}]}]}
```

**Comment by mvdbeek** [comment]
Yeah, so the difference between working and not working is whether you assign the `bam` extension. That's something to work with at least.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/12088 should fix this

**Comment by abretaud** [comment]
Thanks so much for the fix!
