### ISSUE TITLE
Update time trigger for postgresql not postgresql 10 compatible

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12078]
From gitter:
```
INFO:migrate.versioning.api:174 -> 175...
174 -> 175...

Add history audit table and associated triggers

Traceback (most recent call last):
  File "/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "FUNCTION"
LINE 4:             FOR EACH ROW EXECUTE FUNCTION fn_audit_history_b...
```

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/12079
