### ISSUE TITLE
Unexpected URL arguments trigger internal server error on public histories/viz/etc, and shouldn't

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12157]
I think unexpected URL arguments should be ignored, rather than erroring. @shiltemann discovered this during prep for GCC21 where some URLs in the site were automatically setup with tracking parameters (`utm_*`) and this returned a blank page rather than the expected history/vis/etc. 

Other routes don't seem to have this issue (e.g. / or /workflows/list ) which confirms my suspicion that this is a bug.

```
85.149.66.255 - - [17/Jun/2021:09:04:25 +0200] "GET /u/sbray/v/hsp90-lig%5C?testing HTTP/1.1" 500 - "-" "curl/7.68.0"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/statsd.py", line 35, in __call__
    req = self.application(environ, start_response)
  File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
TypeError: display_by_username_and_slug() got an unexpected keyword argument 'testing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 164, in __call__
    exc_info)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 68, in replacement_start_response
    return start_response(status, headers, exc_info)85.149.66.255 - - [17/Jun/2021:09:04:25 +0200] "GET /u/sbray/v/hsp90-lig%5C?testing HTTP/1.1" 500 - "-" "curl/7.68.0"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/statsd.py", line 35, in __call__
    req = self.application(environ, start_response)
  File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
TypeError: display_by_username_and_slug() got an unexpected keyword argument 'testing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 164, in __call__
    exc_info)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 68, in replacement_start_response
    return start_response(status, headers, exc_info)
SystemError: <built-in function uwsgi_spit> returned a result with an error set
[pid: 3002604|app: 0|req: 36464/131154] 85.149.66.255 () {66 vars in 795 bytes} [Thu Jun 17 09:04:25 2021] GET /u/sbray
SystemError: <built-in function uwsgi_spit> returned a result with an error set
[pid: 3002604|app: 0|req: 36464/131154] 85.149.66.255 () {66 vars in 795 bytes} [Thu Jun 17 09:04:25 2021] GET /u/sbray
```

**Comment by mvdbeek** [comment]
Yikes ... yeah, ignoring is the right option, I guess.

**Comment by hexylena** [comment]
Seems fixed
