### ISSUE TITLE
Role sql query error for some users after 21.05 upgrade

### ISSUE THREAD

**Issue by moskalenko** [galaxyproject/galaxy#12171]
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/bio/galaxy/run/prod/galaxy/.venv/lib64/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/remoteuser.py", line 191, in __call__
    return self.app(environ, start_response)
  File "/bio/galaxy/run/prod/galaxy/.venv/lib64/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 194, in handle_request
    trans = self.transaction_factory(environ)
  File "lib/galaxy/webapps/base/webapp.py", line 85, in <lambda>
    self.set_transaction_factory(lambda e: self.transaction_chooser(e, galaxy_app, session_cookie))
  File "lib/galaxy/webapps/base/webapp.py", line 119, in transaction_chooser
    return GalaxyWebTransaction(environ, galaxy_app, self, session_cookie)
  File "lib/galaxy/webapps/base/webapp.py", line 236, in __init__
    self._ensure_valid_session(session_cookie)
  File "lib/galaxy/webapps/base/webapp.py", line 479, in _ensure_valid_session
    user_for_new_session = self.get_or_create_remote_user(remote_user_email)
  File "lib/galaxy/webapps/base/webapp.py", line 610, in get_or_create_remote_user
    if not self.app.security_agent.get_private_user_role(user):
  File "lib/galaxy/model/security.py", line 680, in get_private_user_role
    self.model.Role.table.c.type == self.model.Role.types.PRIVATE)) \
  File "/bio/galaxy/run/prod/galaxy/.venv/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3468, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

**Comment by moskalenko** [comment]
With SQL debugging turned on here's the query that ended up returning two results and triggering the 500 error:

SELECT role.id AS role_id, role.create_time AS role_create_time, role.update_time AS role_update_time, role.name AS role_name, role.description AS role_description, role.type AS role_type, role.deleted AS role_deleted FROM role, user_role_association WHERE user_role_association.user_id=1 AND role.id = user_role_association.role_id AND role.type='private';

**Comment by moskalenko** [comment]
The roles were different

 role_id |      role_create_time      |      role_update_time      |   role_name    |        role_description         | role_type | role_deleted                                                                   ---------+----------------------------+----------------------------+----------------+---------------------------------+-----------+--------------
       1 | 2011-08-10 02:06:45.833598 | 2011-08-10 02:06:45.833614 | jdoe@hpc.ufl.edu | Private Role for jdoe@hpc.ufl.edu | private   | f
     541 | 2015-03-10 20:44:28.203661 | 2015-03-10 20:44:28.20368  | jdoe@rc.ufl.edu  | Private Role for jdoe@rc.ufl.edu  | private   | f

Fixed in the database by removing the role with role.id=541 and reassigning all dataset and library permissions from that role id to the role.id=1.
