### ISSUE TITLE
Beta History Panel - `Export History to File` got an unexpected keyword argument `preview`

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12181]
Follow these steps to reproduce:

![BetaHistoryExportBug](https://user-images.githubusercontent.com/46503462/122806162-49e67980-d2ca-11eb-9fd3-9c3ca53de67f.gif)

The error log:
```python
[21/Jun/2021:19:55:07 +0200] "GET /history/export_archive?preview=True HTTP/1.1" 500 - "http://127.0.0.1:8080/histories/33b43b4e7093c91f/export" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
Traceback (most recent call last):
  File "/home/davelopez/dev/galaxy/lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/home/davelopez/dev/galaxy/.venv/lib/python3.9/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/davelopez/dev/galaxy/.venv/lib/python3.9/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "/home/davelopez/dev/galaxy/lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "/home/davelopez/dev/galaxy/lib/galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
TypeError: export_archive() got an unexpected keyword argument 'preview'
```

xref: https://github.com/galaxyproject/galaxy/issues/10947

**Comment by hexylena** [comment]
xref https://github.com/galaxyproject/galaxy/issues/12157

**Comment by mvdbeek** [comment]
That's working now on current 21.09
