### ISSUE TITLE
Crash in web handlers in 21.05

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#12274]
Found in our logs.

```
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]: galaxy.web.framework.decorators ERROR 2021-07-20 09:26:26,497 [pN:main.web.1,p:1455778,w:1,m:0,tN:uWSGIWorker1Core0] Uncaught exception in exposed API method:
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]: Traceback (most recent call last):
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/web/framework/decorators.py", line 312, in decorator
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     rval = func(self, trans, *args, **kwargs)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/webapps/galaxy/api/tools.py", line 129, in build
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     return tool.to_json(trans, kwd.get('inputs', kwd), history=history)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/__init__.py", line 2173, in to_json
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     populate_state(request_context, self.inputs, params.__dict__, state_inputs, state_errors)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/__init__.py", line 348, in populate_state
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     _populate_state_legacy(request_context, inputs, incoming, state, errors=errors, context=context, check=check, simple_errors=simple_errors)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/__init__.py", line 459, in _populate_state_legacy
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     value, error = check_param(request_context, input, param_value, context, simple_errors=simple_errors) if check else [param_value, None]
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/__init__.py", line 193, in check_param
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     value = param.from_json(value, trans, param_values)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/basic.py", line 1277, in from_json
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     return super().from_json(value, trans, other_values)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/basic.py", line 902, in from_json
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     legal_values = self.get_legal_values(trans, other_values, value)
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/basic.py", line 1371, in get_legal_values
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     if not set(value).issubset(set(legal_values)) and self.is_file_empty(trans, other_values):
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:   File "lib/galaxy/tools/parameters/basic.py", line 1381, in is_file_empty
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]:     if is_runtime_value(dataset) or not dataset.has_data():
Jul 20 09:26:26 sn06.galaxyproject.eu uwsgi[1339355]: AttributeError: 'dict' object has no attribute 'has_data'
```

**Comment by mvdbeek** [comment]
Do you know how this happened ? Any details on how to reproduce ?  Do you have the extended traceback data with locals ?

**Comment by bgruening** [comment]
Sorry, was not yet finished. I do not know I suspect it was triggered during the rerun of tools from a shared history where datasets have not been shared properly. 

ping @wm75

**Comment by mvdbeek** [comment]
The tool in question is a tool that select a column from a dataset (via the `data_ref="some_param_name"` attribute).

There are 2-3 possibilities, either the there is some undecoded data while we check if the dataset is empty (seems unlikely, it should happen frequently then), it could be a problem with a tool where `data_ref` references a non-data parameter (or a parameter name clash with an output for instance), or it could be some non-standard job payload (rerun could fall into that category, via the UI or the API). I think at this point we can check if it's a dict, log what we need for debugging and return False (meaning we attempt to get columns to infer legal values, and if that fails we prevent running the tool)
