### ISSUE TITLE
Startup with main's toolbox fails

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12529]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 60, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/app.py", line 257, in __init__
    self._configure_toolbox()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/config/__init__.py", line 1181, in _configure_toolbox
    self.toolbox = tools.ToolBox(self.config.tool_configs, self.config.tool_path, self)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 288, in __init__
    super().__init__(
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tool_util/toolbox/base.py", line 1274, in __init__
    super().__init__(config_filenames, tool_root_dir, app, view_sources, default_panel_view, save_integrated_tool_panel)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tool_util/toolbox/base.py", line 185, in __init__
    self._load_tool_panel_views()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tool_util/toolbox/base.py", line 489, in _load_tool_panel_views
    self._tool_panel_view_rendered[key] = view.apply_view(self._integrated_tool_panel, registry)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tool_util/toolbox/views/edam.py", line 71, in apply_view
    for path in self.edam[term]['path']:
KeyError: 'operation_3946'
```

**Galaxy Version and/or server at which you observed the bug**
21.09, current HEAD

db92ec002601ef166b882a95d509773fe8e49e89

**To Reproduce**
Mount cvmfs, start Galaxy

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/12530
