### ISSUE TITLE
Pulsar runner consumes status update messages too early on handler startup, causing lost jobs

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#12570]
**Describe the bug**

Pulsar status update AMQP queue is drained before the application is fully initialized, causing terminal job state to be permanently lost on handler startup.

```
galaxy.jobs.handler DEBUG 2021-09-27 14:30:45,879 [pN:test_handler3,p:23935,tN:MainThread] Loaded job runners plugins: slurm:jetstream_iu:jetstream_tacc:stampede:frontera:bridges:expanse:tacc_k8s
pulsar.client.amqp_exchange DEBUG 2021-09-27 14:30:45,904 [pN:test_handler3,p:23935,tN:pulsar_client_expanse_status_update_callback] [publish:695237ea-1fc9-11ec-add0-005056bacbc6] Published to key pulsar_expanse__status_update_ack
pulsar.client.manager DEBUG 2021-09-27 14:30:45,906 [pN:test_handler3,p:23935,tN:pulsar_client_expanse_status_update_callback] Handling asynchronous status update from remote Pulsar.
galaxy.jobs.runners.pulsar ERROR 2021-09-27 14:30:45,906 [pN:test_handler3,p:23935,tN:pulsar_client_expanse_status_update_callback] Failed to update Pulsar job status for job_id 1459936
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 916, in __async_update
    job, job_wrapper = self.app.job_manager.job_handler.job_queue.job_pair_for_id(galaxy_job_id)
AttributeError: 'UniverseApplication' object has no attribute 'job_manager'
pulsar.client.manager ERROR 2021-09-27 14:30:45,921 [pN:test_handler3,p:23935,tN:pulsar_client_expanse_status_update_callback] Failure processing job status update message.
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/pulsar/client/manager.py", line 135, in callback_wrapper
    callback(body)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 916, in __async_update
    job, job_wrapper = self.app.job_manager.job_handler.job_queue.job_pair_for_id(galaxy_job_id)
AttributeError: 'UniverseApplication' object has no attribute 'job_manager'
```

As you can see from the Pulsar side (and the ack message in the Galaxy output above), Galaxy acks the message so Pulsar will not resend it:

```
2021-09-27 12:28:38,547 DEBUG [pulsar.messaging.bind_amqp][[manager=expanse]-[action=postprocess]-[job=1459936]] Publishing Pulsar state change with status complete for job_id 1459936
2021-09-27 12:28:38,562 DEBUG [pulsar.client.amqp_exchange][[manager=expanse]-[action=postprocess]-[job=1459936]] [publish:1d827b4e-1fc9-11ec-9404-b02628dcd720] Begin publishing to key pulsar_expanse__status_update
2021-09-27 12:28:38,563 DEBUG [pulsar.client.amqp_exchange][[manager=expanse]-[action=postprocess]-[job=1459936]] Requesting acknowledgement of UUID 1d827b4e-1fc9-11ec-9404-b02628dcd720 on queue status_update_ack
2021-09-27 12:28:38,572 DEBUG [pulsar.client.amqp_exchange][[manager=expanse]-[action=postprocess]-[job=1459936]] [publish:1d827b4e-1fc9-11ec-9404-b02628dcd720] Have producer for publishing to key pulsar_expanse__status_update
2021-09-27 12:28:38,614 DEBUG [pulsar.client.amqp_exchange][[manager=expanse]-[action=postprocess]-[job=1459936]] [publish:1d827b4e-1fc9-11ec-9404-b02628dcd720] Published to key pulsar_expanse__status_update
2021-09-27 12:30:45,923 DEBUG [pulsar.client.amqp_exchange][consume-status_update_ack-amqp://test_pulsar:********@amqp.galaxyproject.org:5671//test_pulsar?ssl=1] Got acknowledgement for UUID 1d827b4e-1fc9-11ec-9404-b02628dcd720, will remove from store
```

As a result, this job stays permanently non-terminal because Galaxy acknowledged but failed to process or persist the status message.

**Galaxy Version and/or server at which you observed the bug**

test.galaxyproject.org running 21.09 dev (1d70a5bb586dc0d73bdb35d931d06c986f3d13e3)

**To Reproduce**
1. Submit a job to Pulsar in MQ mode
2. Wait for `running` status to be reported to Galaxy
3. Stop handler(s)
4. Wait for job to complete and final status message to be published on Pulsar side
5. Start handler(s)

**Expected behavior**
Galaxy defers processing status messages until application is fully initialized.

**Screenshots**
N/A

**Additional context**
We probably should delay consuming the queue until after the application is ready to process the messages.

**Comment by mvdbeek** [comment]
> exception occurring when handling the status message (during normal operation, not just startup)

Do you have any examples of this ? Is it feasible to fail the job in that case ?

**Comment by natefoo** [comment]
I'll look for some examples, I admit I don't know that it happens. It probably makes sense to fail the job (although it's a shame to do it if it's something that we can recover from - I guess examples will indicate that for us.
