### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12667]
**Describe the bug**

Not quite sure exactly what the context is, I think this is a regular upload. @davelopez, any ideas here ?
```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 243, in prepare_job
    job_wrapper.prepare()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1161, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 450, in build
    raise e
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 446, in build
    self.__build_config_files()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 510, in __build_config_files
    config_text, is_template = self.__build_config_file_text(content)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 598, in __build_config_file_text
    file_sources_dict = self.app.file_sources.to_dict(for_serialization=True, user_context=user_context)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/__init__.py", line 157, in to_dict
    'file_sources': self.plugins_to_dict(for_serialization=for_serialization, user_context=user_context),
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/__init__.py", line 149, in plugins_to_dict
    if not file_source.user_has_access(user_context):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/sources/__init__.py", line 80, in user_has_access
    self._user_has_required_roles(user_context)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/sources/__init__.py", line 195, in _user_has_required_roles
    return self._evaluate_security_rules(self.requires_roles, user_context.role_names)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/sources/__init__.py", line 206, in _evaluate_security_rules
    return evaluator.evaluate_expression(rule_expression)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/bool_expressions.py", line 147, in evaluate_expression
    res = self.boolExpr.parseString(expr, parseAll=True)[0]
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1943, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1844, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1716, in _parseNoCache
    tokens = fn(instring, tokensStart, retTokens)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pyparsing.py", line 1316, in wrapper
    ret = func(*args[limit[0]:])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/bool_expressions.py", line 57, in __init__
    self.value = self.evaluator.evaluate(token[0])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/bool_expressions.py", line 178, in evaluate
    return token in self.tokens
TypeError: argument of type 'NoneType' is not iterable
```
**Galaxy Version and/or server at which you observed the bug**
21.09 on usegalaxy.org

**Comment by gmauro** [comment]
It's an anonymous doing an upload.
It's happening also to us quite often, lately.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/usegalaxy-playbook/blob/main/env/common/templates/galaxy/config/file_sources_conf.yml.j2
