### ISSUE TITLE
Fix / forbid collection input with `multiple="true"`

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#12684]
**Describe the bug**

Seems that collection input with `multiple="true"` (ie `<param ...  type="data_collection" multiple="true"/>`) is possible but has some rough edges.

- its used in Galaxy tests: https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/collection_cat_group_tag.xml
- its used in IUC tools 
  - https://github.com/galaxyproject/tools-iuc/blob/a04f64b68f22ea44dbeb0423f969a7ced4736249/tools/deseq2/deseq2.xml#L122
  - https://github.com/galaxyproject/tools-iuc/blob/a04f64b68f22ea44dbeb0423f969a7ced4736249/tools/qualimap/qualimap_multi_bamqc.xml#L101
  - other examples are found in qualimap and mothur make.contigs

Problems:

- in the UI its not possible to select multiple collections.
- tests can currently not be specified: https://github.com/galaxyproject/galaxy/blob/0e15e5380828c73e18d59ade47e6961b97e8431b/lib/galaxy/tool_util/xsd/galaxy.xsd#L1472
- In the command sections the tools mentioned above seem to use the collection parameter as if `multiple="false"`.

**To Reproduce**

`planemo serve` one of the mentioned tools

**Expected behavior**

Good question. Either fix or document that multiple true is forbidden (actually nested collections could do the same) and extend the linter accordingly.

**Comment by lldelisle** [comment]
I got an issue and I think it is related:
I have an input which can be multiple:
```
<param argument="--transcripts" type="data" format="fasta" multiple="true" label="Transcripts" help="File(s) with transcripts in FASTA format."/>
```
I would like to test it with a collection so I can control the identifier names, I tried:
```
            <param name="transcripts">
                <collection type="list">
                    <element name="first transcriptome" value="transcriptome01.fasta"/>
                    <element name="second transcriptome" value="transcriptome02.fasta"/>
                </collection>
            </param>
```
But when I run planemo test I get:

```
galaxy.tools.test ERROR 2024-08-30 11:10:36,346 [pN:main,p:34726,tN:MainThread] Failed to load tool test number [0] for rna_quast
Traceback (most recent call last):
  File "/tmp/tmpg7yf3vnc/galaxy-dev/lib/galaxy/tools/test.py", line 54, in description_from_tool_object
    processed_inputs = _process_raw_inputs(
  File "/tmp/tmpg7yf3vnc/galaxy-dev/lib/galaxy/tools/test.py", line 205, in _process_raw_inputs
    _add_uploaded_dataset(context.for_state(), v, param_extra, value, required_files)
  File "/tmp/tmpg7yf3vnc/galaxy-dev/lib/galaxy/tools/test.py", line 318, in _add_uploaded_dataset
    assert input_parameter.optional, f"{name} is not optional. You must provide a valid filename."
AssertionError: transcripts is not optional. You must provide a valid filename.
```
