### ISSUE TITLE
"invalid input syntax for integer"

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1269]
```
galaxydb_1 | ERROR:  invalid input syntax for integer: "c68ff386100b838f" at character 2775
galaxydb_1 | STATEMENT:  DECLARE "c_7f88c02aec10_2666" CURSOR WITHOUT HOLD FOR SELECT history_dataset_association.id AS history_dataset_association_id, history_dataset_association.history_id AS history_dataset_association_history_id, history_dataset_association.dataset_id AS history_dataset_association_dataset_id, history_dataset_association.create_time AS history_dataset_association_create_time, history_dataset_association.update_time AS history_dataset_association_update_time, history_dataset_association.state AS history_dataset_association_state, history_dataset_association.copied_from_history_dataset_association_id AS history_dataset_association_copied_from_history_dataset_a_1, history_dataset_association.copied_from_library_dataset_dataset_association_id AS history_dataset_association_copied_from_library_dataset_d_2, history_dataset_association.name AS history_dataset_association_name, history_dataset_association.info AS history_dataset_association_info, history_dataset_association.blurb AS history_dataset_association_blurb, history_dataset_association.peek AS history_dataset_association_peek, history_dataset_association.tool_version AS history_dataset_association_tool_version, history_dataset_association.extension AS history_dataset_association_extension, history_dataset_association.metadata AS history_dataset_association_metadata, history_dataset_association.parent_id AS history_dataset_association_parent_id, history_dataset_association.designation AS history_dataset_association_designation, history_dataset_association.deleted AS history_dataset_association_deleted, history_dataset_association.visible AS history_dataset_association_visible, history_dataset_association.extended_metadata_id AS history_dataset_association_extended_metadata_id, history_dataset_association.hid AS history_dataset_association_hid, history_dataset_association.purged AS history_dataset_association_purged, history_dataset_association.hidden_beneath_collection_instance_id AS history_dataset_association_hidden_beneath_collection_ins_3, dataset_1.id AS dataset_1_id, dataset_1.create_time AS dataset_1_create_time, dataset_1.update_time AS dataset_1_update_time, dataset_1.state AS dataset_1_state, dataset_1.deleted AS dataset_1_deleted, dataset_1.purged AS dataset_1_purged, dataset_1.purgable AS dataset_1_purgable, dataset_1.object_store_id AS dataset_1_object_store_id, dataset_1.external_filename AS dataset_1_external_filename, dataset_1._extra_files_path AS dataset_1__extra_files_path, dataset_1.file_size AS dataset_1_file_size, dataset_1.total_size AS dataset_1_total_size, dataset_1.uuid AS dataset_1_uuid
galaxydb_1 |    FROM history_dataset_association LEFT OUTER JOIN dataset AS dataset_1 ON dataset_1.id = history_dataset_association.dataset_id
galaxydb_1 |    WHERE history_dataset_association.id = 'c68ff386100b838f'
```

and in my tool I see

```
Fatal error: Exit code 1 ()
Can't locate AI/FANN.pm in @INC (you may need to install the AI::FANN module) (@INC contains: /galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/lib/perl5 /galaxy/tool_dependencies/perl/5.18.1/iuc/package_perl_5_18/2590d4683481/lib/perl5 /galaxy/tool_dependencies/perl/5.18.1/iuc/package_perl_5_18/2590d4683481/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/lib/perl5/RG/Reprof.pm line 25.
BEGIN failed--compilation aborted at /galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/lib/perl5/RG/Reprof.pm line 25.
Compilation failed in require at /galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/bin/reprof line 15.
BEGIN failed--compilation aborted at /galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/bin/reprof line 15.
Traceback (most recent call last):
  File "/galaxy/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iuc/reprof/3658e4d701fc/reprof/reprof.py", line 154, in <module>
    main(**vars(args))
  File "/galaxy/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iuc/reprof/3658e4d701fc/reprof/reprof.py", line 102, in main
    data = process_reprof_report(run_reprof(tmp.name, modeldir))
  File "/galaxy/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iuc/reprof/3658e4d701fc/reprof/reprof.py", line 21, in run_reprof
    subprocess.check_call(cmd)
  File "/galaxy/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['reprof', '-i', '/var/lib/condor/execute/dir_20766/tmpQXCXQP', '--modeldir=/galaxy/tool_dependencies/reprof/1.0.1/iuc/package_reprof_1_0_1/a010d7eddc71/share/reprof', '-o', '/var/lib/condor/execute/dir_20766/tmpMIGhts']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/galaxy/database/job_working_directory/045/45379/set_metadata_j6c7XN.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/galaxy/lib/galaxy_ext/metadata/set_metadata.py", line 23, in <module>
    from sqlalchemy.orm import clear_mappers
ImportError: No module named sqlalchemy.orm
```

**Comment by jmchilton** [comment]
I think this may have been fixed in dev, can you recheck this?
