### ISSUE TITLE
mixing datasets when dragging from a collection to toolpanel

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#12729]
**Describe the bug**
I have a collection of paired fastq.gz datasets, I wanted to run a fastqc on one of the forward reads so I dragged it into the tool panel and executed fastqc. Fastqc job ended up with this error (note the first line)

```
Failed to process GROMACS solvation and adding ions on data 2 and data 4
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:87)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:159)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
```

If I click on "run this job again I have this in the toolform:

![Galaxy___Europe](https://user-images.githubusercontent.com/1814954/137620327-b47dc0ea-3f9f-4f6c-a150-79df7727d94c.png)

There is no dataset like that in my history and I am pretty sure I never ran GROMACS tool.

![Galaxy](https://user-images.githubusercontent.com/1814954/137620366-26144a88-fb88-410e-835c-92d3c1e5b807.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05 - usegalaxy.eu

**Expected behavior**
I'd expect the fastqc to be ran on `53: CB1C12_S88_R1_001.fastq.gz`

**Comment by martenson** [comment]
@wm75 not sure about this, perhaps in combination with another bug, since this is not a value that was there before -- it is a dataset owned by someone else.
