### ISSUE TITLE
Startup fails with toolbox and EDAM

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#12859]
**Describe the bug**
Getting this after upgrading from 21.05 to 21.09:

```
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 60, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 269, in __init__
    self._configure_toolbox()
  File "lib/galaxy/config/__init__.py", line 1172, in _configure_toolbox
    self.toolbox = tools.ToolBox(self.config.tool_configs, self.config.tool_path, self)
  File "lib/galaxy/tools/__init__.py", line 295, in __init__
    save_integrated_tool_panel=save_integrated_tool_panel,
  File "lib/galaxy/tool_util/toolbox/base.py", line 1274, in __init__
    super().__init__(config_filenames, tool_root_dir, app, view_sources, default_panel_view, save_integrated_tool_panel)
  File "lib/galaxy/tool_util/toolbox/base.py", line 185, in __init__
    self._load_tool_panel_views()
  File "lib/galaxy/tool_util/toolbox/base.py", line 489, in _load_tool_panel_views
    self._tool_panel_view_rendered[key] = view.apply_view(self._integrated_tool_panel, registry)
  File "lib/galaxy/tool_util/toolbox/views/edam.py", line 75, in apply_view
    t = path[0]
IndexError: list index out of range
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: dd74027

**To Reproduce**
1. Start the server, with the galaxy.genouest.org toolbox
2. See error

**Expected behavior**
It should start

**Additional context**
I'm going to try to see which tool triggers this error

**Comment by abretaud** [comment]
Getting this error on `toolshed.g2.bx.psu.edu/repos/iuc/instrain_compare/instrain_compare/1.5.3+galaxy0` and `toolshed.g2.bx.psu.edu/repos/iuc/instrain_profile/instrain_profile/1.5.3+galaxy0` with term `topic_0796`

**Comment by nsoranzo** [comment]
> Getting this error on `toolshed.g2.bx.psu.edu/repos/iuc/instrain_compare/instrain_compare/1.5.3+galaxy0` and `toolshed.g2.bx.psu.edu/repos/iuc/instrain_profile/instrain_profile/1.5.3+galaxy0` with term `topic_0796`

It seems this topic was obsoleted in EDAM in favour of `topic_0102`, should we update the tools?
