### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by animesh** [galaxyproject/galaxy#12855]
Trying to follow https://galaxyproject.org/admin/get-galaxy/ for local install and facing this error

```
sh run.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/animeshs/galaxy/lib/galaxy/dependencies/__init__.py", line 275, in optional
    conditional = ConditionalDependencies(config_file)
  File "/home/animeshs/galaxy/lib/galaxy/dependencies/__init__.py", line 37, in __init__
    self.config = load_app_properties(config_file=self.config_file)
  File "/home/animeshs/galaxy/lib/galaxy/util/properties.py", line 79, in load_app_properties
    properties = read_properties_from_file(config_file, config_section)
  File "/home/animeshs/galaxy/lib/galaxy/util/properties.py", line 109, in read_properties_from_file
    properties.update(raw_properties.get(config_section) or {})
AttributeError: 'str' object has no attribute 'get'

```
any ideas how to proceed? my setup is

```
animeshs@dmed6942:~/galaxy$ python --version
Python 3.8.8
animeshs@dmed6942:~/galaxy$ uname -a
Linux dmed6942 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by mvdbeek** [comment]
Thanks for the report, this should be `./run.sh`, not `sh run.sh`, we'll have to update the instructions there

**Comment by animesh** [comment]
OK but it didn't solve the issue it seems

```
animeshs@dmed6942:~/galaxy$ ./run.sh
...
Requirement already satisfied: pycparser in ./.venv/lib/python3.8/site-packages (from cffi>=1.1->bcrypt==3.2.0->-r ./lib/galaxy/dependencies/dev-requirements.txt (line 17)) (2.20)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/animeshs/galaxy/lib/galaxy/dependencies/__init__.py", line 275, in optional
    conditional = ConditionalDependencies(config_file)
  File "/home/animeshs/galaxy/lib/galaxy/dependencies/__init__.py", line 37, in __init__
    self.config = load_app_properties(config_file=self.config_file)
  File "/home/animeshs/galaxy/lib/galaxy/util/properties.py", line 79, in load_app_properties
    properties = read_properties_from_file(config_file, config_section)
  File "/home/animeshs/galaxy/lib/galaxy/util/properties.py", line 109, in read_properties_from_file
    properties.update(raw_properties.get(config_section) or {})
AttributeError: 'str' object has no attribute 'get'

```

**Comment by nsoranzo** [comment]
> Thanks for the report, this should be `./run.sh`, not `sh run.sh`, we'll have to update the instructions there

I think the 2 are equivalent.

**Comment by LauLauThom** [comment]
Hi,
Sorry to dig this thread out, but I had the same issue and it seems it's due to the function `yaml.safe_load` returning a string if the file is a malformed yaml (see [here](https://stackoverflow.com/a/71800932).

https://github.com/galaxyproject/galaxy/blob/9b30e9f8417fc5e7016575dbca758c6b9df2d6ca/lib/galaxy/util/properties.py#L153  

EDIT : Well for some reasons when I extract the installation zip on my machine, the symlinks in the installation directory are broken, such that config files which are symlinks to other files just have the target link as content, so literally one line of text with the path to the target.
So that explains why the library returns a string.
I am on Lubuntu and used Ark to extract the zip.

**Comment by LauLauThom** [comment]
And here is a solution : either use the `unzip` command line utility to unzip the installer bundle, or if using Ark, in settings > plugins untick `libzip`.  
Then after unzipping open a terminal in the unzipped directory and check with the command `ls -l` that files such as `requirements.txt` are indeed a symlinks pointing to another file.

**Comment by mvdbeek** [comment]
That's an interesting find. In general we recommend either installing via git or `pip install galaxy`
