### ISSUE TITLE
Tool dependency view not shown in Admin panel

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13019]
When selecting the `Manage Dependencies` option from the Admin panel an error is shown instead of the list of tool dependencies.

```Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 314, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 106, in decorator
    return func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tool_dependencies.py", line 225, in summarize_toolbox
    return self._view.summarize_requirements(**kwds)
  File "lib/galaxy/tool_util/deps/views.py", line 245, in summarize_requirements
    statuses = {r: self.get_requirements_status(tool_requirements_d={tids[0]: r},
  File "lib/galaxy/tool_util/deps/views.py", line 245, in <dictcomp>
    statuses = {r: self.get_requirements_status(tool_requirements_d={tids[0]: r},
  File "lib/galaxy/tool_util/deps/views.py", line 294, in get_requirements_status
    dependencies = self.show_dependencies(tool_requirements_d, installed_tool_dependencies, **kwd)
  File "lib/galaxy/tool_util/deps/views.py", line 61, in show_dependencies
    dependencies_per_tool = {tool: self._dependency_manager.requirements_to_dependencies(requirements,
  File "lib/galaxy/tool_util/deps/views.py", line 61, in <dictcomp>
    dependencies_per_tool = {tool: self._dependency_manager.requirements_to_dependencies(requirements,
  File "lib/galaxy/tool_util/deps/__init__.py", line 194, in requirements_to_dependencies
    requirement_to_dependency = self._requirements_to_dependencies_dict(requirements, **kwds)
  File "lib/galaxy/tool_util/deps/__init__.py", line 283, in _requirements_to_dependencies_dict
    dependency = resolver.resolve(requirement, **kwds)
  File "lib/galaxy/tool_util/deps/resolvers/galaxy_packages.py", line 79, in resolve
    return self._find_dep_versioned(name, version, type=type, **kwds)
  File "lib/galaxy/tool_util/deps/resolvers/tool_shed_packages.py", line 25, in _find_dep_versioned
    path = self._get_package_installed_dependency_path(installed_tool_dependency, name, version)
  File "lib/galaxy/tool_util/deps/resolvers/tool_shed_packages.py", line 43, in _get_package_installed_dependency_path
    tool_shed_repository = installed_tool_dependency.tool_shed_repository
  File "/Users/guerler/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/Users/guerler/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 926, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/Users/guerler/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 962, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/Users/guerler/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 861, in _load_for_state
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <ToolDependency at 0x7fc309347220> is not bound to a Session; lazy load operation of attribute 'tool_shed_repository' cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)```

**Comment by mvdbeek** [comment]
Pretty sure that'll be fixed with https://github.com/galaxyproject/galaxy/pull/13154
