### ISSUE TITLE
Migrate endpoints that use stream_template_mako to vue, replace with fill_template_mako or fix stream_template_mako to use StreamingResponse

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13016]
It seems that `stream_template_mako` doesn't work in fastAPI and fails with
```
  app_iter = self.application(environ, sr_checker)
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py', line 140 in __call__
  reraise(*_capture_exception(hub))
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/_compat.py', line 54 in reraise
  raise value
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py', line 133 in __call__
  rv = self.app(
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/middleware/statsd.py', line 35 in __call__
  req = self.application(environ, start_response)
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py', line 138 in __call__
  return self.handle_request(environ, start_response)
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py', line 223 in handle_request
  return body_renderer(trans, body, environ, start_response)
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py', line 230 in _render_body
  return body(environ, start_response)
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/base/webapp.py', line 977 in render
  template.render_context(context)
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/template.py', line 490 in render_context
  runtime._render_context(self, self.callable_, context, *args, **kwargs)
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/runtime.py', line 920 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/runtime.py', line 947 in _exec_template
  callable_(context, *args, **kwargs)
File '/srv/galaxy/test/var/cache/compiled_templates/base/base_panels.mako.py', line 36 in render_body
  __M_writer('<!DOCTYPE HTML>\n')
File '/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/base/webapp.py', line 974 in write
  response_write(d.encode('utf-8'))
TypeError: 'NoneType' object is not callable


CGI Variables
-------------
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
  HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.9'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'close'
  HTTP_COOKIE: 'galaxysession=b1251ce3b0e2e90fbc8fe171958e3587cbc92a1554662e9493e736a977cd1dfc0c9f55f5ec8d37af; _ga=GA1.2.1348474881.1638450644; _gid=GA1.2.676825799.1638450644; _gat=1; _gat_gtag_UA_45719423_17=1'
  HTTP_HOST: 'test.galaxyproject.org'
  HTTP_REFERER: 'https://test.galaxyproject.org/histories/list_published'
  HTTP_SEC_CH_UA: '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"'
  HTTP_SEC_CH_UA_MOBILE: '?0'
  HTTP_SEC_CH_UA_PLATFORM: '"macOS"'
  HTTP_SEC_FETCH_DEST: 'document'
  HTTP_SEC_FETCH_MODE: 'navigate'
  HTTP_SEC_FETCH_SITE: 'same-origin'
  HTTP_SEC_FETCH_USER: '?1'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36'
  HTTP_X_FORWARDED_FOR: '94.111.117.69'
  HTTP_X_FORWARDED_PROTO: 'https'
  HTTP_X_REAL_IP: '94.111.117.69'
  ORGINAL_REMOTE_ADDR: '94.111.117.69'
  PATH_INFO: '/u/kanwei/h/imported-tophat-psu-mouse-brain-se-reads'
  REMOTE_ADDR: '94.111.117.69'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '127.0.0.1'
  SERVER_PORT: 8080
  SERVER_PROTOCOL: 'HTTP/1.0'


WSGI Variables
--------------
  application: <sentry_sdk.integrations.wsgi.SentryWsgiMiddleware object at 0x7fd1446faaf0>
  controller_action_key: 'web.history.display_by_username_and_slug'
  is_api_request: False
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x7fd14474dee0>
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '580b3000537111ec88c7005056bacbc6'
  webob._parsed_query_vars: (GET([]), '')
  wsgi process: 'Multi process AND threads (?)'
------------------------------------------------------------
Error - <class 'TypeError'>: 'NoneType' object is not callable
urllib3.connectionpool DEBUG 2021-12-02 07:11:39,987 [pN:main,p:6062,tN:raven-sentry.BackgroundWorker] https://sentry.galaxyproject.org:443 "POST /api/2/store/ HTTP/1.1" 200 41
87.162.19.133 - - [02/Dec/2021:07:11:30 -0500] "POST /api/tools/toolshed.g2.bx.psu.edu/repos/devteam/fastq_to_fasta/cshl_fastq_to_fasta/1.0.0/build HTTP/1.0" 200 - "https://test.galaxyproject.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[2021-12-02 07:11:40 -0600] [6062] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 106, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 152, in _run_app
    raise exc from None
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 149, in _run_app
    return await callback()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 63, in __call__
    await responder(receive, send)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 94, in __call__
    raise self.exc_info[0].with_traceback(
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
    reraise(*_capture_exception(hub))
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 133, in __call__
    rv = self.app(
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/middleware/statsd.py", line 35, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py", line 223, in handle_request
    return body_renderer(trans, body, environ, start_response)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py", line 230, in _render_body
    return body(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/base/webapp.py", line 977, in render
    template.render_context(context)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/template.py", line 490, in render_context
    runtime._render_context(self, self.callable_, context, *args, **kwargs)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/srv/galaxy/test/var/cache/compiled_templates/base/base_panels.mako.py", line 36, in render_body
    __M_writer('<!DOCTYPE HTML>\n')
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/base/webapp.py", line 974, in write
    response_write(d.encode('utf-8'))
TypeError: 'NoneType' object is not callable
```

These mako's that are currently being streamed are
- [ ] `/dataset/large_file.mako`
- [ ] `/dataset/item_content.mako` (not sure that is still in use ??)
- [ ] `visualization/display_in_frame.mako` (also not sure if that is in use)
- [ ] `visualization/display.mako`
- [ ] `/workflow/item_content.mako` (unsure if used)
- [ ] `history/display.mako`

**Comment by mvdbeek** [comment]
Ultimately we've gone with https://github.com/galaxyproject/galaxy/pull/13017
