### ISSUE TITLE
Galaxy npm install fails without make installed

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#13064]
**Describe the bug**
npm install fails due to binary release not being available and not having make (and other build tools as well presumably)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: release_21.09
Commit: 799a94fbdd16c2b2d59d7fcb31617ceff4083cf3

**To Reproduce**
1. Have a Galaxy environment without make installed.
2. Run `/galaxy_venv/bin/activate && npm config set strict-ssl false && npm install && deactivate`

**Expected behavior**
npm install to complete without errors without make (et al.) installed.

**Screenshots**
Here's the output from the ansible task that is running npm install:
```
TASK [galaxyprojectdotorg.galaxyextras : Install proxy dependencies (>=19.01).] ***
fatal: [localhost]: FAILED! => {
   "changed":true,
   "cmd":". /galaxy_venv/bin/activate && npm config set strict-ssl false && npm install && deactivate",
   "delta":"0:01:15.761056",
   "end":"2021-12-13 19:54:13.628163",
   "msg":"non-zero return code",
   "rc":1,
   "start":"2021-12-13 19:52:57.867107",
   "stderr":"npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future\nnode-pre-gyp WARN Using needle for node-pre-gyp https download \nnode-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz \nnode-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.15.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) \ngyp ERR! build error \ngyp ERR! stack Error: not found: make\ngyp ERR! stack     at getNotFoundError (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:13:12)\ngyp ERR! stack     at F (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:68:19)\ngyp ERR! stack     at E (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:80:29)\ngyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:89:16\ngyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/isexe/index.js:42:5\ngyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/isexe/mode.js:8:5\ngyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)\ngyp ERR! System Linux 4.15.0-45-generic\ngyp ERR! command \"/galaxy_venv/bin/node\" \"/galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node\" \"--module_name=node_sqlite3\" \"--module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v83\"\ngyp ERR! cwd /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3\ngyp ERR! node -v v14.15.0\ngyp ERR! node-gyp -v v5.1.0\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute '/galaxy_venv/bin/node /galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/galaxy-central/lib/galaxy/web/proxy/js/node_modules/node-pre-gyp/lib/util/compile.js:83:29)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)\nnode-pre-gyp ERR! System Linux 4.15.0-45-generic\nnode-pre-gyp ERR! command \"/galaxy_venv/bin/node\" \"/galaxy-central/lib/galaxy/web/proxy/js/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3\nnode-pre-gyp ERR! node -v v14.15.0\nnode-pre-gyp ERR! node-pre-gyp -v v0.11.0\nnode-pre-gyp ERR! not ok \nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the sqlite3@4.2.0 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/galaxy/.npm/_logs/2021-12-13T19_54_13_605Z-debug.log",
   "stderr_lines":[
      "npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future",
      "node-pre-gyp WARN Using needle for node-pre-gyp https download ",
      "node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz ",
      "node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.15.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) ",
      "gyp ERR! build error ",
      "gyp ERR! stack Error: not found: make",
      "gyp ERR! stack     at getNotFoundError (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:13:12)",
      "gyp ERR! stack     at F (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:68:19)",
      "gyp ERR! stack     at E (/galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:80:29)",
      "gyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/which/which.js:89:16",
      "gyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/isexe/index.js:42:5",
      "gyp ERR! stack     at /galaxy_venv/lib/node_modules/npm/node_modules/isexe/mode.js:8:5",
      "gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)",
      "gyp ERR! System Linux 4.15.0-45-generic",
      "gyp ERR! command \"/galaxy_venv/bin/node\" \"/galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node\" \"--module_name=node_sqlite3\" \"--module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v83\"",
      "gyp ERR! cwd /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3",
      "gyp ERR! node -v v14.15.0",
      "gyp ERR! node-gyp -v v5.1.0",
      "gyp ERR! not ok ",
      "node-pre-gyp ERR! build error ",
      "node-pre-gyp ERR! stack Error: Failed to execute '/galaxy_venv/bin/node /galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)",
      "node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/galaxy-central/lib/galaxy/web/proxy/js/node_modules/node-pre-gyp/lib/util/compile.js:83:29)",
      "node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)",
      "node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)",
      "node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)",
      "node-pre-gyp ERR! System Linux 4.15.0-45-generic",
      "node-pre-gyp ERR! command \"/galaxy_venv/bin/node\" \"/galaxy-central/lib/galaxy/web/proxy/js/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"",
      "node-pre-gyp ERR! cwd /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3",
      "node-pre-gyp ERR! node -v v14.15.0",
      "node-pre-gyp ERR! node-pre-gyp -v v0.11.0",
      "node-pre-gyp ERR! not ok ",
      "npm ERR! code ELIFECYCLE",
      "npm ERR! errno 1",
      "npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`",
      "npm ERR! Exit status 1",
      "npm ERR! ",
      "npm ERR! Failed at the sqlite3@4.2.0 install script.",
      "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.",
      "",
      "npm ERR! A complete log of this run can be found in:",
      "npm ERR!     /home/galaxy/.npm/_logs/2021-12-13T19_54_13_605Z-debug.log"
   ],
   "stdout":"\n> sqlite3@4.2.0 install /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3\n> node-pre-gyp install --fallback-to-build\n\nFailed to execute '/galaxy_venv/bin/node /galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)",
   "stdout_lines":[
      "",
      "> sqlite3@4.2.0 install /galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3",
      "> node-pre-gyp install --fallback-to-build",
      "",
      "Failed to execute '/galaxy_venv/bin/node /galaxy_venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/galaxy-central/lib/galaxy/web/proxy/js/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)"
   ]
}

RUNNING HANDLER [galaxyprojectdotorg.galaxyextras : restart nginx] *************
        to retry, use: --limit @/ansible/provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=45   changed=36   unreachable=0    failed=1

The command '/bin/sh -c mkdir -p /shed_tools $EXPORT_DIR/ftp/     && chown $GALAXY_USER:$GALAXY_USER /shed_tools $EXPORT_DIR/ftp     && ln -s /tool_deps/ $EXPORT_DIR/tool_deps     && chown $GALAXY_USER:$GALAXY_USER $EXPORT_DIR/tool_deps     && apt update -qq && apt install --no-install-recommends -y ansible     && ansible-playbook /ansible/provision.yml     --extra-vars galaxy_venv_dir=$GALAXY_VIRTUAL_ENV     --extra-vars galaxy_log_dir=$GALAXY_LOGS_DIR     --extra-vars galaxy_user_name=$GALAXY_USER     --extra-vars galaxy_config_file=$GALAXY_CONFIG_FILE     --extra-vars galaxy_config_dir=$GALAXY_CONFIG_DIR     --extra-vars galaxy_job_conf_path=$GALAXY_CONFIG_JOB_CONFIG_FILE     --extra-vars galaxy_job_metrics_conf_path=$GALAXY_CONFIG_JOB_METRICS_CONFIG_FILE     --extra-vars supervisor_manage_slurm=""     --extra-vars galaxy_extras_config_condor=True     --extra-vars galaxy_extras_config_condor_docker=True     --extra-vars galaxy_extras_config_rabbitmq=True     --extra-vars galaxy_extras_config_cvmfs=True     --extra-vars galaxy_extras_config_uwsgi=False     --extra-vars proftpd_db_connection=galaxy@galaxy     --extra-vars proftpd_files_dir=$EXPORT_DIR/ftp     --extra-vars proftpd_use_sftp=True     --extra-vars galaxy_extras_docker_legacy=False     --extra-vars galaxy_minimum_version=19.01     --extra-vars supervisor_postgres_config_path=$PG_CONF_DIR_DEFAULT/postgresql.conf     --extra-vars supervisor_postgres_autostart=false     --extra-vars nginx_use_remote_header=True     --tags=galaxyextras,cvmfs -c local     && . $GALAXY_VIRTUAL_ENV/bin/activate     && pip install WeasyPrint     && deactivate     && cd $GALAXY_ROOT && ./scripts/common_startup.sh     && cd config && find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +     && find . -name '.cache' -type d -prune -exec rm -rf '{}' +     && cd /     && rm $PG_DATA_DIR_DEFAULT -rf     && python /usr/local/bin/setup_postgresql.py --dbuser galaxy --dbpassword galaxy --db-name galaxy --dbpath $PG_DATA_DIR_DEFAULT --dbversion $PG_VERSION     && service postgresql start     && service postgresql stop     && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && rm -rf ~/.cache/     && find $GALAXY_ROOT/ -name '*.pyc' -delete | true     && find /usr/lib/ -name '*.pyc' -delete | true     && find /var/log/ -name '*.log' -delete | true     && find $GALAXY_VIRTUAL_ENV -name '*.pyc' -delete | true     && rm -rf /tmp/* /root/.cache/ /var/cache/* $GALAXY_ROOT/client/node_modules/ $GALAXY_VIRTUAL_ENV/src/ /home/galaxy/.cache/ /home/galaxy/.npm' returned a non-zero code: 2
```

**Additional context**
I haven't actually tried to install make and friends to workaround this problem but with a proper resolution that shouldn't be necessary I think.

**Comment by chambm** [comment]
It works with gcc, g++ and make installed.

**Comment by eghasemy** [comment]
> 

Even after installing these, it still doesn't work for me. Any ideas on how to get past this error?

**Comment by hexylena** [comment]
@eghasemy the error usually changes, can you please share a new error output?

**Comment by eghasemy** [comment]
This is the error I'm getting. I'm working off of the master and I only changed the galaxy version to 22.01
[error.txt](https://github.com/galaxyproject/galaxy/files/8505491/error.txt)

**Comment by dannon** [comment]
In that traceback I see `"gyp ERR! stack Error: not found: make","` towards the top; if you've installed that then maybe there's a path issue going on here?

**Comment by eghasemy** [comment]
It would appear that I wasn't installing make correctly as part of the preceding tasks. The issue is now resolved for me.

**Comment by dannon** [comment]
Good to know. Thank you for the follow up!

**Comment by dannon** [comment]
Good to know. Thank you for the follow up!
