### ISSUE TITLE
planemo tests timing out and ASGI error

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13136]
**Describe the bug**

When running `planemo test` on a few (two) tools of the IUC repo I see the following error after Galaxy started and the tool test execution stalls reproducibly.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/base.py", line 65, in __call__
    task_group.cancel_scope.cancel()
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
    raise exceptions[0]
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 64, in __call__
    await responder(receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 91, in __call__
    await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 572, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 98, in sender
    await send(message)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 177, in send_nowait
    raise BrokenResourceError
anyio.BrokenResourceError
----------------------------
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 91, in __call__
    await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 131, in wsgi
    anyio.from_thread.run(
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/from_thread.py", line 35, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 847, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 177, in send_nowait
    raise BrokenResourceError
anyio.BrokenResourceError

2022-01-08 18:19:39,334 ERROR [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/base.py", line 65, in __call__
    task_group.cancel_scope.cancel()
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
    raise exceptions[0]
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 64, in __call__
    await responder(receive, send)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 91, in __call__
    await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 572, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 98, in sender
    await send(message)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 177, in send_nowait
    raise BrokenResourceError
anyio.BrokenResourceError
----------------------------
Traceback (most recent call last):
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 91, in __call__
    await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/starlette/middleware/wsgi.py", line 131, in wsgi
    anyio.from_thread.run(
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/from_thread.py", line 35, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 847, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/home/berntm/.planemo/gx_venv_3.7/lib/python3.8/site-packages/anyio/streams/memory.py", line 177, in send_nowait
    raise BrokenResourceError
anyio.BrokenResourceError
```

Tool tests stall at a line similar to (only ids differ):

```
Setup for job Job[unflushed,tool_id=macs2_callpeak] complete, ready to be enqueued (22.027 ms)
2022-01-08 18:40:41,618 INFO  [galaxy.web_stack.handlers] (Job[id=3,tool_id=macs2_callpeak]) Handler '_default_' assigned using 'HANDLER_ASSIGNMENT_METHODS.DB_SKIP_LOCKED' assignment method
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: 060ab1a487

**To Reproduce**

Run either 

- `planemo test --biocontainers --no_dependency_resolution --no_conda_auto_init --galaxy_python_version 3.7  --galaxy_source https://github.com/galaxyproject/galaxy --galaxy_branch dev tools/macs2/macs2_callpeak.xml` or
- `planemo test --biocontainers --no_dependency_resolution --no_conda_auto_init --galaxy_python_version 3.7 --galaxy_source https://github.com/galaxyproject/galaxy --galaxy_branch dev tools/pygenometracks/pyGenomeTracks.xml`

macs2 stalls at the first test and pygenoetracs at test 17

**Expected behavior**

**Screenshots**

**Additional context**

Might be the cause of the tests timing out in the tests of https://github.com/galaxyproject/galaxy/pull/13039 here  https://github.com/galaxyproject/tools-iuc/issues/4318

**Comment by nsoranzo** [comment]
Can you please check if galaxy at the commit before that also exhibit the same issue?  #13135 updated starlette and fastapi, and could be the cause for BrokenResourceError.

**Comment by bernt-matthias** [comment]
Did a `git bisect` between 21.09 and dev. It appears that the stalling and the traceback are unrelated

- the traceback started with a5b14521b08ee282c239eed6eae44c1fa95f5d63
- stalling started with 317b99364958c9a9cd00a951e7b3b80235a28b75 (https://github.com/galaxyproject/galaxy/pull/12942)

**Comment by bernt-matthias** [comment]
For https://github.com/galaxyproject/galaxy/commit/a5b14521b08ee282c239eed6eae44c1fa95f5d63 the changes in `lib/galaxy/util/__init__.py` look fishy on first glance ... try without except?

**Comment by mvdbeek** [comment]
Can you check if #13137 fixes it for you ? I could see the test hang if the metadata is in error ... . If that is true we need to find a way to error out quickly.

**Comment by mvdbeek** [comment]
@davelopez do we still need to downgrade fastAPI ? I see a lot of `anyio.BrokenResourceError` exceptions. I thought they were supposed to be fixed, but seems it's still an issue

**Comment by davelopez** [comment]
Yeah, I also thought it was fixed but I guess it is still an issue https://github.com/tiangolo/fastapi/issues/4041 so probably we should downgrade again.

**Comment by nsoranzo** [comment]
Is it a real issue of just polluting the logs?

**Comment by davelopez** [comment]
That's a good question, some people claim it is fixed and some are silencing it but I'm afraid I don't know if that's a good idea or what are the consequences.

**Comment by mvdbeek** [comment]
Yeah, all of these are kind of "logging issues". It happens when the client goes away and we write to a closed socket. You can see that the fix in https://github.com/encode/starlette/pull/1262/files is to pick up the right exception from the coroutine, I suppose that something similar should be done for the WSGI middleware we're using (and that doesn't seem to be based on BaseHTTPMiddleware). A good start might be to write a small client test

**Comment by mvdbeek** [comment]
It might not be the closed socket issue ....
```python
import time
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.wsgi import WSGIMiddleware


def wsgi_application(env, start_response):
    print('start')
    time.sleep(0.3)
    start_response("200 OK", {})
    print('done')
    return [b'bla']

app = FastAPI()
app.mount('/', WSGIMiddleware(wsgi_application))


if __name__ == "__main__":
    uvicorn.run(app="timeoutapp:app", port=8001)
```

And then `curl http://127.0.0.1:8001/ --max-time 0.1` doesn't lead to the exception. Explicitly raising an exception is also fine and doesn't print the whole anyio stacktrace ... odd. I could have sworn i've seen it in the tests recently. But I guess we can close that for now until we see it again in Galaxy.
