### ISSUE TITLE
editing subworkflows can yield a 500 error

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13253]
If you import this workflow, which containers sub-workflows, the sub-workflow can not be edited.

https://usegalaxy.eu/u/hyphy/w/rascl/

Editing yields the following stack trace.

```
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: 132.230.153.81 - - [27/Jan/2022:09:43:12 +0200] "GET /workflow/editor?workflow_id=0e642b5407dd595b HTTP/1.1" 500 - "https://usegalaxy.eu/workflow/editor?id=3057b45da0ce85b5" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: Traceback (most recent call last):
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     app_iter = self.application(environ, sr_checker)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     reraise(*_capture_exception(hub))
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     raise value
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 136, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     _sentry_start_response, start_response, transaction
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.application(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/statsd.py", line 35, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     req = self.application(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "/opt/galaxy/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.application(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/base.py", line 138, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.handle_request(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/base.py", line 217, in handle_request
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     body = method(trans, **kwargs)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/decorators.py", line 83, in decorator
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return func(self, trans, *args, **kwargs)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/webapps/galaxy/controllers/workflow.py", line 661, in editor
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     stored_workflow_id = trans.security.encode_id(stored_workflow.id)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: AttributeError: 'NoneType' object has no attribute 'id'
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: The above exception was the direct cause of the following exception:
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: Traceback (most recent call last):
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/batch.py", line 85, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.application(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.app(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.app(environ, start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/translogger.py", line 69, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return self.application(environ, replacement_start_response)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/error.py", line 164, in __call__
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     exc_info)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:   File "lib/galaxy/web/framework/middleware/translogger.py", line 68, in replacement_start_response
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]:     return start_response(status, headers, exc_info)
Jan 27 09:43:12 sn06.galaxyproject.eu uwsgi[3457173]: SystemError: <built-in function uwsgi_spit> returned a result with an error set

```

**Comment by mvdbeek** [comment]
Can you update the .eu branch ? I think it doesn't contain https://github.com/galaxyproject/galaxy/pull/13231/. Probably not the issue at hand, but maybe it is and that's a fix you want anyway.

**Comment by mvdbeek** [comment]
OK, the problem is that we don't share the embedded workflow. If you download the workflow and re-upload it then you can edit it.
