### ISSUE TITLE
Integration tests needed for openid

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13280]
test had been down with
```
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/galaxy/fast_factory.py", line 63, in factory
    gx_wsgi_webapp, gx_app = app_pair(global_conf=config.global_conf, load_app_kwds=config.load_app_kwds, wsgi_preflight=config.wsgi_preflight)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 76, in app_pair
    webapp.add_ui_controllers('galaxy.webapps.galaxy.controllers', app)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/base/webapp.py", line 130, in add_ui_controllers
    for name, module in base.walk_controller_modules(package_name):
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/web/framework/base.py", line 537, in walk_controller_modules
    module = import_module(module_name)
  File "/cvmfs/test.galaxyproject.org/deps/_conda/envs/__python@3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/webapps/galaxy/controllers/openid.py", line 8, in <module>
    from galaxy.openid.openid_manager import OpenIDManager
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/openid/openid_manager.py", line 11, in <module>
    from openid.consumer import consumer
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/openid/consumer/consumer.py", line 194, in <module>
    from openid import fetchers
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/openid/fetchers.py", line 27, in <module>
    import httplib2
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/httplib2/__init__.py", line 52, in <module>
    from . import auth
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.8/site-packages/httplib2/auth.py", line 20, in <module>
    auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'
```
we have no coverage of openid as far as I can tell.

**Comment by nsoranzo** [comment]
Closed by dropping this feature in #13281 .
