### ISSUE TITLE
SQL errors during PostgreSQL database creation

### ISSUE THREAD

**Issue by ajs6f** [galaxyproject/galaxy#13289]
**Describe the bug**

SQL `NoSuchTableError` and syntax error prevents PostgreSQL database creation.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
`release_21.09`
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)
81f27cb5878b0e353353f0eefa8a125fe1b5314e

**To Reproduce**
1. `sudo -u galaxy ./run.sh` (initial run)
2. Startup...
3. Failure with error shown at bottom of issue.

**Expected behavior**
Successful startup.

**Additional context**
PostgreSQL 9.2.24.

```
galaxy.model.migrate.check INFO 2022-02-01 12:03:40,468 [pN:MainProcess,p:42359,w:0,m:0,tN:MainThread] No database, initializing
galaxy.model.migrate.check INFO 2022-02-01 12:03:40,468 [pN:MainProcess,p:42359,w:0,m:0,tN:MainThread] Creating new database from scratch, skipping migrations
Traceback (most recent call last):
  File "lib/galaxy/model/migrate/check.py", line 88, in create_or_verify_database
    Table("dataset", meta, autoload=True)
  File "<string>", line 2, in __new__
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 601, in __new__
    metadata._remove_table(name, schema)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 596, in __new__
    table._init(name, metadata, *args, **kw)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 676, in _init
    resolve_fks=resolve_fks,
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 711, in _autoload
    _extend_on=_extend_on,
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 775, in reflect_table
    table_name, schema, **table.dialect_kwargs
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 498, in get_columns
    conn, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3589, in get_columns
    connection, table_name, schema, info_cache=kw.get("info_cache")
  File "<string>", line 2, in get_table_oid
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3468, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: dataset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "ON"
LINE 9:                     ON CONFLICT DO NOTHING;
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 60, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 225, in __init__
    super().__init__(fsmon=True, **kwargs)
  File "lib/galaxy/app.py", line 179, in __init__
    super().__init__(**kwargs)
  File "lib/galaxy/app.py", line 153, in __init__
    self._configure_models(check_migrate_databases=self.config.check_migrate_databases, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "lib/galaxy/config/__init__.py", line 1293, in _configure_models
    create_or_verify_database(db_url, config_file, self.config.database_engine_options, app=self, map_install_models=combined_install_database)
  File "lib/galaxy/model/migrate/check.py", line 92, in create_or_verify_database
    migrate_from_scratch()
  File "lib/galaxy/model/migrate/check.py", line 69, in migrate_from_scratch
    mapping.init(file_path='/tmp', url=url, map_install_models=map_install_models, create_tables=True)
  File "lib/galaxy/model/mapping.py", line 109, in init
    install_timestamp_triggers(engine)
  File "lib/galaxy/model/migrate/triggers/update_audit_table.py", line 18, in install
    execute_statements(engine, sql)
  File "lib/galaxy/model/migrate/versions/util.py", line 203, in execute_statements
    cmd.execute(bind=engine)
  File "<string>", line 2, in execute
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 117, in execute
    return bind.execute(self.against(target))
  File "<string>", line 2, in execute
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 3107, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1358, in _execute_ddl
    compiled,
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    e, statement, parameters, cursor, context
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/pool/spare/galaxy/galaxy/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "ON"
LINE 9:                     ON CONFLICT DO NOTHING;
                            ^

[SQL: 
            CREATE OR REPLACE FUNCTION fn_audit_history_by_history_id()
                RETURNS TRIGGER
                LANGUAGE 'plpgsql'
            AS $BODY$
                BEGIN
                    INSERT INTO history_audit (history_id, update_time)
                    VALUES (NEW.history_id, CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
                    ON CONFLICT DO NOTHING;
                    RETURN NULL;
                END;
            $BODY$
        ]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Comment by mvdbeek** [comment]
> PostgreSQL 9.2.24.

You'll have to update postgres to at least 9.6, but better one of the currently supported releases.
