### ISSUE TITLE
Job tracking fails with `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by ajs6f** [galaxyproject/galaxy#13297]
**Describe the bug**

Jobs sent to a cluster via the Univa connector successfully run (as checked on that cluster), but do not get tracked by Galaxy. Instead, the job goes into a "This job is currently running" state seemingly permanently. The logs show an endless cycle around a `TypeError: expected string or bytes-like object` message (log excerpts below).

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
`release_21.09`
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)
81f27cb5878b0e353353f0eefa8a125fe1b5314e

**To Reproduce**
1. Launch a simple upload task.
2. Task will complete on cluster.
3. Task will never complete in Galaxy.

**Expected behavior**
Successful job tracking to completion.

**Screenshots**

**Additional context**
Here is an excerpt of logs, showing endless cycle around the same sections. 
```
galaxy.jobs.runners.drmaa DEBUG 2022-02-02 13:08:54,636 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] (2/2739829) state change: job finished normally
10.254.127.6 - - [02/Feb/2022:13:08:54 -0400] "GET /api/histories/f597429621d6eb2b/contents?details=f597429621d6eb2b&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-02-02T18%3A08%3A50.000Z&qv=False&qv=False HTTP/1.1" 200 - "https://hydra-5.si.edu/datasets/f597429621d6eb2b/details" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
[pid: 88096|app: 0|req: 459/459] 10.254.127.6 () {86 vars in 1982 bytes} [Wed Feb  2 13:08:54 2022] GET /api/histories/f597429621d6eb2b/contents?details=f597429621d6eb2b&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-02-02T18%3A08%3A50.000Z&qv=False&qv=False => generated 2 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 139 bytes (2 switches on core 3)
lib/galaxy/jobs/handler.py:359: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(hda_not_ready),
lib/galaxy/jobs/handler.py:360: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(ldda_not_ready))
galaxy.jobs.runners.univa ERROR 2022-02-02 13:08:56,195 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] DRMAAUniva: job 2739829 has exit status 0
galaxy.jobs.runners ERROR 2022-02-02 13:08:56,196 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] Unhandled exception checking active jobs
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 707, in monitor
    self.check_watched_items()
  File "lib/galaxy/jobs/runners/drmaa.py", line 338, in check_watched_items
    if self._complete_terminal_job(ajs, drmaa_state=state) is not None:
  File "lib/galaxy/jobs/runners/univa.py", line 85, in _complete_terminal_job
    time_granted, mem_granted = _parse_native_specs(ajs.job_id, native_spec)
  File "lib/galaxy/jobs/runners/univa.py", line 572, in _parse_native_specs
    m = re.search(r"rt=([0-9:]+)[\s,]*", native_spec)
  File "/pool/spare/galaxy/galaxy/.venv/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
galaxy.jobs.runners.drmaa DEBUG 2022-02-02 13:08:57,272 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] (2/2739829) state change: job finished normally
lib/galaxy/jobs/handler.py:359: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(hda_not_ready),
lib/galaxy/jobs/handler.py:360: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(ldda_not_ready))
galaxy.jobs.runners.univa ERROR 2022-02-02 13:08:58,654 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] DRMAAUniva: job 2739829 has exit status 0
galaxy.jobs.runners ERROR 2022-02-02 13:08:58,655 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] Unhandled exception checking active jobs
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 707, in monitor
    self.check_watched_items()
  File "lib/galaxy/jobs/runners/drmaa.py", line 338, in check_watched_items
    if self._complete_terminal_job(ajs, drmaa_state=state) is not None:
  File "lib/galaxy/jobs/runners/univa.py", line 85, in _complete_terminal_job
    time_granted, mem_granted = _parse_native_specs(ajs.job_id, native_spec)
  File "lib/galaxy/jobs/runners/univa.py", line 572, in _parse_native_specs
    m = re.search(r"rt=([0-9:]+)[\s,]*", native_spec)
  File "/pool/spare/galaxy/galaxy/.venv/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
10.254.127.6 - - [02/Feb/2022:13:08:58 -0400] "GET /api/histories/f597429621d6eb2b/contents?details=f597429621d6eb2b&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-02-02T18%3A08%3A54.000Z&qv=False&qv=False HTTP/1.1" 200 - "https://hydra-5.si.edu/datasets/f597429621d6eb2b/details" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
[pid: 88096|app: 0|req: 460/460] 10.254.127.6 () {86 vars in 1982 bytes} [Wed Feb  2 13:08:58 2022] GET /api/histories/f597429621d6eb2b/contents?details=f597429621d6eb2b&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-02-02T18%3A08%3A54.000Z&qv=False&qv=False => generated 2 bytes in 31 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
galaxy.jobs.runners.drmaa DEBUG 2022-02-02 13:08:59,731 [pN:main.web.1,p:88096,w:1,m:0,tN:UnivaJobRunner.monitor_thread] (2/2739829) state change: job finished normally

```

**Comment by ajs6f** [comment]
Here is the relevant `job_conf.xml`:
```
<job_conf>
    <plugins workers="4">
        <!-- "workers" is the number of threads for the runner's work queue.
             The default from <plugins> is used if not defined for a <plugin>.
             For all asynchronous runners (i.e. everything other than
             LocalJobRunner), this is the number of threads available for
             starting and finishing jobs. For the LocalJobRunner, this is the
             number of concurrent jobs that Galaxy will run.
          -->
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner"/>
        <plugin id="uge" type="runner" load="galaxy.jobs.runners.univa:UnivaJobRunner">
            <!-- Override the $DRMAA_LIBRARY_PATH environment variable -->
            <param id="drmaa_library_path">/cm/shared/apps/uge/current/drmaa/lib/lx-amd64/libdrmaa.so</param>
        </plugin>
    </plugins>


    <handlers>
        <!-- Job handler processes - for a full discussion of job handlers, see the documentation at:
             https://docs.galaxyproject.org/en/latest/admin/scaling.html

             For documentation on handler assignment methods, see the documentation under:
             https://docs.galaxyproject.org/en/latest/admin/scaling.html#job-handler-assignment-methods

             The <handlers> container tag takes four optional attributes:

               <handlers assign_with="method" max_grab="count" ready_window_size="100" default="id_or_tag"/>

               - `assign_with` - How jobs should be assigned to handlers. The value can be a single method or a
                 comma-separated list that will be tried in order. The default depends on whether any handlers and a job
                 handler "pool" (such as uWSGI mules in a `job-handlers` farm) are configured. Valid methods are
                 explained in detail in the documentation referenced above and have the values:

                   - `mem-self` - In-memory Self Assignment
                   - `db-self`- Database Self Assignment
                   - `db-preassign` - Database Preassignment
                   - `uwsgi-mule-message` - uWSGI Mule Messaging
                   - `db-transaction-isolation` - Database Transaction Isolation
                   - `db-skip-locked` - Database SKIP LOCKED

               - `max_grab` - Limit the number of jobs that a handler will self-assign per jobs-ready-to-run check loop
                 iteration. This only applies for methods that cause handlers to self-assign multiple jobs at once
                 (db-skip-locked, db-transaction-isolation) and the value is an integer > 0. Default is to grab as many
                 jobs ready to run as possible.

               - `ready_window_size` - Handlers query for and dispatch jobs ready to run in a loop. If the number of
                 jobs in the `new` state grows very large but they cannot be dispatched due to user concurrency limits,
                 checking all of these jobs on every iteration can drastically slow down job throughput as each pending
                 job is checked and then deferred due to limits. This option limits the number of jobs per user are
                 returned by the query on each iteration. By default it is set to 100. Setting this lower can improve
                 throughput for other users when one user submits thousands of independent jobs.

                 Be aware that anonymous users are treated as a single user by this algorithm.

               - `default` - An ID or tag of the handler(s) that should handle any jobs not assigned to a specific
                 handler (which is probably most of them). If unset, the default is any untagged handlers plus any
                 handlers in the `job-handlers` (no tag) pool.
        -->
        <!-- Explicitly defined job handlers - the id should match the handler process's `server_name`. For webless
             handlers, this is the value of the `server-name` argument to `galaxy-main`.
         -->
<!--        <handler id="uge_handler">
            <plugin id="uge"/>
        </handler> -->
    </handlers> 
    <destinations default="uge-destination">
        <!-- Destinations define details about remote resources and how jobs
             should be executed on those remote resources.
         -->
        <destination id="uge-destination" runner="uge">
            <env id="SGE_ROOT">/cm/shared/apps/uge/current</env>
        </destination>

        
        <destination id="local" runner="local"/>
        <destination id="multicore_local" runner="local">
          <param id="local_slots">4</param> <!-- Specify GALAXY_SLOTS for local jobs. -->
          <!-- Warning: Local slot count doesn't tie up additional worker threads, to prevent over
               allocating machine define a second local runner with different name and fewer workers
               to run this destination. -->
          <param id="embed_metadata_in_job">True</param>
          <!-- Above parameter will be default (with no option to set
               to False) in an upcoming release of Galaxy, but you can
               try it early - it will slightly speed up local jobs by
               embedding metadata calculation in job script itself.
          -->
          <param id="metadata_strategy">directory</param>
          <!-- If set, overwrites metadata_strategy (configurable in galaxy.yml).
               Valid values are `directory` (default), `extended` and `legacy`.
               Setting metadata_strategy to `extended` requires that all object stores
               that can be written to store datasets by uuid. In `extended` mode jobs
               will decide if a tool run failed, the object stores configuration
               is serialized and made available to the job and is used for writing output
               datasets to the object store as part of the job and dynamic output discovery
               (e.g. discovered datasets <discover_datasets>, unpopulated collections, etc)
               happens as part of the job.
          -->
          <job_metrics />
          <!-- Above element demonstrates embedded job metrics definition - see
               job_metrics_conf.xml.sample for full documentation on possible nested
               elements. This empty block will simply disable job metrics for the
               corresponding destination. -->
        </destination>
    </destinations>
    <limits>
        <!-- Certain limits can be defined. The 'concurrent_jobs' limits all
             control the number of jobs that can be "active" at a time, that
             is, dispatched to a runner and in the 'queued' or 'running'
             states.

             A race condition exists that will allow destination_* concurrency
             limits to be surpassed when multiple handlers are allowed to
             handle jobs for the same destination. To prevent this, assign all
             jobs for a specific destination to a single handler.
        -->
        <!-- registered_user_concurrent_jobs:
                Limit on the number of jobs a user with a registered Galaxy
                account can have active across all destinations.
        -->
        <limit type="registered_user_concurrent_jobs">2</limit>
        <!-- anonymous_user_concurrent_jobs:
                Likewise, but for unregistered/anonymous users.
        -->
        <limit type="anonymous_user_concurrent_jobs">1</limit>
        <!-- destination_user_concurrent_jobs:
                The number of jobs a user can have active in the specified
                destination, or across all destinations identified by the
                specified tag. (formerly: concurrent_jobs)
        -->
        <limit type="destination_user_concurrent_jobs" id="local">1</limit>
        <limit type="destination_user_concurrent_jobs" tag="mycluster">2</limit>
        <limit type="destination_user_concurrent_jobs" tag="longjobs">1</limit>
        <!-- destination_total_concurrent_jobs:
                The number of jobs that can be active in the specified
                destination (or across all destinations identified by the
                specified tag) by any/all users.
        -->
        <limit type="destination_total_concurrent_jobs" id="local">16</limit>
        <limit type="destination_total_concurrent_jobs" tag="longjobs">100</limit>
        <!-- walltime:
                Amount of time a job can run (in any destination) before it
                will be terminated by Galaxy.
         -->
        <limit type="walltime">24:00:00</limit>
        <!-- total_walltime:
                Total walltime that jobs may not exceed during a set period.
                If total walltime of finished jobs exceeds this value, any
                new jobs are paused.  `window` is a number in days,
                representing the period.
         -->
        <limit type="total_walltime" window="30">24:00:00</limit>
        <!-- output_size:
                Size that any defined tool output can grow to before the job
                will be terminated. This does not include temporary files
                created by the job. Format is flexible, e.g.:
                '10GB' = '10g' = '10240 Mb' = '10737418240'
        -->
        <limit type="output_size">10GB</limit>
    </limits>
    <macros>
        <xml name="foohost_destination" tokens="id,walltime,ncpus">
            <destination id="@ID@" runner="cli">
                <param id="shell_plugin">SecureShell</param>
                <param id="job_plugin">Torque</param>
                <param id="shell_username">galaxy</param>
                <param id="shell_hostname">foohost_destination.example.org</param>
                <param id="job_Resource_List">walltime=@WALLTIME@,ncpus=@NCPUS@</param>
            </destination>
        </xml>
    </macros>
</job_conf>
```

**Comment by mvdbeek** [comment]
Can you try this patch?
```diff
diff --git a/lib/galaxy/jobs/runners/univa.py b/lib/galaxy/jobs/runners/univa.py
index 2fe1a5c76c..645a325dc2 100644
--- a/lib/galaxy/jobs/runners/univa.py
+++ b/lib/galaxy/jobs/runners/univa.py
@@ -80,7 +80,7 @@ class UnivaJobRunner(DRMAAJobRunner):
         if state in [self.drmaa.JobState.DONE, self.drmaa.JobState.FAILED]:
             # get configured job destination
             job_destination = ajs.job_wrapper.job_destination
-            native_spec = job_destination.params.get('nativeSpecification', None)
+            native_spec = job_destination.params.get('nativeSpecification', '')
             # determine time and memory that was granted for the job
             time_granted, mem_granted = _parse_native_specs(ajs.job_id, native_spec)
             time_wasted = extinfo["time_wasted"]

```

**Comment by ajs6f** [comment]
Marvelous, @mvdbeek, that seems to have done the trick! Please let me know if I can help get this into trunk or in some other way.

**Comment by nsoranzo** [comment]
Reopening for tracking purposes.

@ajs6f If you'd like, you could open a pull request with the change suggested targeting the `release_21.09` branch.

**Comment by ajs6f** [comment]
@nsoranzo happy to so do sometime later today.

**Comment by ajs6f** [comment]
@nsoranzo I have a branch ready [here](https://github.com/Smithsonian/galaxy/tree/Fixfor13297), but for some reason I cannot seem to offer a PR against `release_21.09` as suggested [here](https://github.com/galaxyproject/galaxy/blob/dev/CONTRIBUTING.md); at least the GH UI doesn't offer it as a choice. Am I missing something? Should I send a PR against some other branch?

**Comment by nsoranzo** [comment]
@ajs6f You should be able to do it from https://github.com/galaxyproject/galaxy/compare/release_21.09...Smithsonian:Fixfor13297?expand=1

**Comment by ajs6f** [comment]
Yes, how strange that it did not let me select that from the menu... oh, well.
