### ISSUE TITLE
crash in sorting collection with UnboundLocalError

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13302]
**Describe the bug**

```
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]: galaxy.tools ERROR 2022-02-03 20:58:37,457 [pN:workflow_scheduler_key_2,p:3383088,tN:WorkflowRequestMonitor.monitor_thread] Exception caught while attempting to execute tool with id '__SORTLIST__':
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]: Traceback (most recent call last):
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1770, in handle_single_execution
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:     flush_job=flush_job,
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1858, in execute
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:     return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:   File "/opt/galaxy/server/lib/galaxy/tools/actions/model_operations.py", line 61, in execute
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:     self._produce_outputs(trans, tool, out_data, output_collections, incoming=incoming, history=history, tags=preserved_tags, hdca_tags=preserved_hdca_tags)
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:   File "/opt/galaxy/server/lib/galaxy/tools/actions/model_operations.py", line 77, in _produce_outputs
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:     tool.produce_outputs(trans, out_data, output_collections, incoming, history=history, tags=tags, hdca_tags=hdca_tags, tag_handler=tag_handler)
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 3240, in produce_outputs
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]:     for dce in sorted_elements:
Feb 03 20:58:37 sn06.galaxyproject.eu python[3383088]: UnboundLocalError: local variable 'sorted_elements' referenced before assignment

```

I assume that no sorting type is specified: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L3432

**Comment by bgruening** [comment]
Magic: https://sentry.galaxyproject.org/share/issue/673dad2cd8924337978e3acbec28f296/
