### ISSUE TITLE
crash in job scheduling

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13311]
I have a few jobs scheduled by Galaxy but not handed over to the scheduler, they show this stack trace.

```
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: galaxy.jobs.runners DEBUG 2022-02-04 16:53:25,697 [pN:handler_key_3,p:34321,tN:JobHandlerQueue.monitor_thread] Job [40845203] queued (71.706 ms)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34311]: galaxy.objectstore DEBUG 2022-02-04 16:53:25,717 [pN:handler_key_4,p:34311,tN:JobHandlerQueue.monitor_thread] Using preferred backend 'files11' for creation of Job 40892081
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: galaxy.jobs.handler INFO 2022-02-04 16:53:25,721 [pN:handler_key_3,p:34321,tN:JobHandlerQueue.monitor_thread] (40845203) Job dispatched
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: galaxy.jobs.runners ERROR 2022-02-04 16:53:25,732 [pN:handler_key_3,p:34321,tN:CondorRunner.work_thread-6] (40845175) Unhandled exception calling queue_job
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: Traceback (most recent call last):
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 243, in prepare_job
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     job_wrapper.prepare()
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1153, in prepare
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 71, in set_compute_environment
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     incoming = self.tool.params_from_strings(incoming, self.app)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1872, in params_from_strings
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     return params_from_strings(self.inputs, params, app, ignore_errors)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 240, in params_from_strings
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     value = param.value_from_basic(value, app, ignore_errors)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 690, in value_from_basic
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     raise e
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 687, in value_from_basic
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     rval[input.name] = input.value_from_basic(value[input.name], app, ignore_errors)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 182, in value_from_basic
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     raise e
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 179, in value_from_basic
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     rval[input.name] = input.value_from_basic(value[input.name], app, ignore_errors)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 227, in value_from_basic
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     return self.to_python(value, app)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 428, in to_python
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     raise err
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 422, in to_python
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     return int(value)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: ValueError: invalid literal for int() with base 10: '0.0'

Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: During handling of the above exception, another exception occurred:
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]: Traceback (most recent call last):
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 142, in run_next
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     method(arg)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/condor.py", line 59, in queue_job
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     if not self.prepare_job(job_wrapper, include_metadata=include_metadata):
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 254, in prepare_job
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     job_wrapper.fail(unicodify(e), exception=True)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1328, in fail
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     if outputs_to_working_directory and not self.__link_file_check() and working_directory_exists:
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 2263, in __link_file_check
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     param_dict = job.get_param_values(self.app)
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:   File "/opt/galaxy/server/lib/galaxy/model/__init__.py", line 1248, in get_param_values
Feb 04 16:53:25 sn06.galaxyproject.eu python[34321]:     param_dict = tool.params_from_strings(param_dict, app, ignore_errors=ignore_errors)

```

sentry: https://sentry.galaxyproject.org/share/issue/f260379e712043cd8aa34dd4c6d9306f/

**Comment by mvdbeek** [comment]
These are tool states that don't match the tool. The traceback is noisy, but I don't think this is a bug.

**Comment by mvdbeek** [comment]
(in this case it's a float parameter that became a int)

**Comment by bgruening** [comment]
It should not crash, left? It should return an error at least and turn the job red. It stays gray at the moment.

**Comment by mvdbeek** [comment]
You sure that's not what is happening ?
https://github.com/galaxyproject/galaxy/blob/1b3e4b5ca8d81d15e25d73621e20d23b8b2ccf95/lib/galaxy/jobs/runners/__init__.py#L259

**Comment by bgruening** [comment]
I see it queued:

```
galaxy@sn06:/data/5/galaxy_import/galaxy_user_data/pahl/koellerer/2022-02-01$ gxadmin query queue-detail | grep 40845175
 queued  | 40845175 |          | toolshed.g2.bx.psu.edu/repos/iuc/purge_dups/purge_dups/1.2.5+galaxy4                                                                   | gallardoalba                     | 23:13:02.05347          | handler_key_3 | condor          | 1cores_4.0G                          |     1
galaxy@sn06:/data/5/galaxy_import/galaxy_user_data/pahl/koellerer/2022-02-01$ 
```


`40845175` is te ID from the traceback above. The condor ID is not assigned since it crashed before I think.

**Comment by bgruening** [comment]
More complete lifecycle of the job `40845175` https://gist.github.com/bgruening/58cf56610ae722bf6ace38a9f6f51d5b

**Comment by mvdbeek** [comment]
OK, yeah, I see it, we're failing in the fail method too.
That should fix it:
```
diff --git a/lib/galaxy/jobs/__init__.py b/lib/galaxy/jobs/__init__.py
index 7524e216ad..b1df6bec51 100644
--- a/lib/galaxy/jobs/__init__.py
+++ b/lib/galaxy/jobs/__init__.py
@@ -2188,10 +2188,10 @@ class JobWrapper(HasResourceParameters):
         method should be removed ASAP and replaced with some properly generic
         and stateful way of determining link-only datasets. -nate
         """
-        if self.tool:
+        if self.tool and self.tool.id == 'upload1':
             job = self.get_job()
             param_dict = job.get_param_values(self.app)
-            return self.tool.id == 'upload1' and param_dict.get('link_data_only', None) == 'link_to_files'
+            return param_dict.get('link_data_only') == 'link_to_files'
         else:
             # The tool is unavailable, we try to move the outputs.
             return False

```

**Comment by bgruening** [comment]
I see the same errors in the handler logs after applying this patch :(

**Comment by mvdbeek** [comment]
You sure that's exactly the same?

**Comment by bgruening** [comment]
```
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]: galaxy.jobs.runners ERROR 2022-02-04 20:05:43,812 [pN:handler_key_1,p:1438590,tN:CondorRunner.work_thread-1] (40844783) Failure preparing job
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]: Traceback (most recent call last):
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 243, in prepare_job
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     job_wrapper.prepare()
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1153, in prepare
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 71, in set_compute_environment
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     incoming = self.tool.params_from_strings(incoming, self.app)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1872, in params_from_strings
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     return params_from_strings(self.inputs, params, app, ignore_errors)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 240, in params_from_strings
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     value = param.value_from_basic(value, app, ignore_errors)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 690, in value_from_basic
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     raise e
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 687, in value_from_basic
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     rval[input.name] = input.value_from_basic(value[input.name], app, ignore_errors)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 182, in value_from_basic
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     raise e
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/grouping.py", line 179, in value_from_basic
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     rval[input.name] = input.value_from_basic(value[input.name], app, ignore_errors)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 227, in value_from_basic
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     return self.to_python(value, app)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 428, in to_python
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     raise err
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 422, in to_python
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]:     return int(value)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1438590]: ValueError: invalid literal for int() with base 10: '0.0'
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]: galaxy.jobs.runners ERROR 2022-02-04 20:05:43,812 [pN:handler_key_3,p:1450797,tN:CondorRunner.work_thread-4] (40845186) Failure preparing job
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]: Traceback (most recent call last):
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 243, in prepare_job
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]:     job_wrapper.prepare()
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1153, in prepare
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]:     tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
Feb 04 20:05:43 sn06.galaxyproject.eu python[1450797]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 71, in set_compute_environment

```

looks like it

**Comment by bgruening** [comment]
Ok, but after that crash, the jobs disappeared from the list. So I think that is ok?

**Comment by mvdbeek** [comment]
I think so. Did job and dataset end up in the error state ?

**Comment by bgruening** [comment]
```
galaxy@sn06:~$ gxadmin query job-history 40845175
             time              | state  
-------------------------------+--------
 2022-02-03 20:13:47.474329+01 | new
 2022-02-03 22:42:44.966199+01 | queued
 2022-02-04 03:17:09.18262+01  | new
 2022-02-04 06:21:02.5096+01   | queued
 2022-02-04 11:55:21.538958+01 | new
 2022-02-04 12:22:26.271422+01 | queued
 2022-02-04 15:27:02.213337+01 | new
 2022-02-04 16:53:25.418185+01 | queued
 2022-02-04 20:05:07.126252+01 | new
 2022-02-04 20:05:43.450446+01 | queued
 2022-02-04 20:05:44.0752+01   | error
(11 rows)
```
In the end it was an error.
