### ISSUE TITLE
Uppercase tool id breaks linting

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13609]
```
.. CHECK: Help contains valid reStructuredText.
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/planemo/commands/cmd_lint.py", line 53, in cli
    exit_code = lint_tools_on_path(
  File "/usr/local/lib/python3.8/dist-packages/planemo/tool_lint.py", line 46, in lint_tools_on_path
    if not lint_tool_source(tool_xml, name=basename(tool_path), **lint_args):
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/lint.py", line 19, in lint_tool_source
    lint_tool_source_with(lint_context, tool_source, extra_modules)
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/lint.py", line 58, in lint_tool_source_with
    lint_context.lint(name, value, tool_source)
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/lint.py", line 88, in lint
    lint_func(lint_target, self)
  File "/usr/local/lib/python3.8/dist-packages/galaxy/tool_util/linters/general.py", line 76, in lint_general
    if re.search(r"\s", tool_id):
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```
the problem was `<tool ID="bellerophon" name="bellerophon" version="@TOOL_VERSION@+galaxy@VERSION_SUFFIX@" profile="20.01">`. Not sure if we want to bail or not, but we do need to improve the reporting at a minimum.

**Comment by bernt-matthias** [comment]
Is the tool parser also stumbling over this?

**Comment by davelopez** [comment]
For what it's worth, the `Galaxy Tools` extension detects this `ID` as an invalid attribute because of the XSD validation :stuck_out_tongue_winking_eye: 

![Screenshot from 2022-03-30 13-13-58](https://user-images.githubusercontent.com/46503462/160822378-e18bb96d-5df9-4c73-8102-eea0b0e0f858.png)

I think this was already fixed in https://github.com/galaxyproject/galaxy/pull/12978/files#diff-645913697b6828593212abbf14cf6d4eb60d1a4ee8580f3df8e1e766cffba112R59-R60

Maybe we just need to update the planemo dependencies?

**Comment by mvdbeek** [comment]
Nice, that is probably it!

**Comment by mvdbeek** [comment]
@jmchilton can you comment on https://github.com/galaxyproject/planemo/pull/1203 please ? I think we should reach a decision there before releasing the new packages.

**Comment by davelopez** [comment]
This is no longer an issue :)
