### ISSUE TITLE
Workflow extraction fails (in specific identified cases)

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#13823]
**Describe the bug**
Extract workflow fails if input is collection output of job with multiple collections

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
I could reproduce it on usegalaxy.eu
```
version_major | "21.09"
version_minor | "1.dev0"
```

**To Reproduce**
1. Get a fastq (I used:
```
@1
ATCG
+
IIII
```
)
2. Create a collection (list) with this fastq in (the bug can only be reproduced if this is in a collection).
3. Run fastqc (this tools has 2 outputs and the bug can only be reproduced if the tool has multiple outputs)
4. Copy the "rawData" collection to a new history (what ever the way to copy the collection, the bug will be reproduced)
5. Run multiQC in this new history
6. Extract a workflow
7. No workflow is created
(I even tried to extract the workflow using bioblend but it created an empty workflow)

**Expected behavior**
Get a workflow with 2 steps fastqc and multiqc or a workflow with a single step multiqc...

**Comment by bgruening** [comment]
We have also seen this error during workflow extraction:

```
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]: [2025-09-26 16:56:06 +0200] [2987339] [ERROR] Exception in ASGI application
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]: Traceback (most recent call last):
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     result = await app(  # type: ignore[func-returns-value]
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await self.app(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await super().__call__(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 409, in _sentry_patched_asgi_app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await middleware(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 174, in _run_asgi3
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await self._run_app(scope, receive, send, asgi_version=3)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 276, in _run_app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     raise exc from None
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 271, in _run_app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await self.app(
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await self.middleware_stack(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 200, in _create_span_call
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await old_call(app, scope, new_receive, new_send, **kwargs)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     raise exc
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await self.app(scope, receive, _send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 200, in _create_span_call
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await old_call(app, scope, new_receive, new_send, **kwargs)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette_context/middleware/raw_middleware.py", line 94, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await self.app(scope, receive, send_wrapper)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 298, in _sentry_exceptionmiddleware_call
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await old_call(self, scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 200, in _create_span_call
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await old_call(app, scope, new_receive, new_send, **kwargs)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     raise exc
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await app(scope, receive, sender)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await self.middleware_stack(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await route.handle(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 460, in handle
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     await self.app(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/a2wsgi/wsgi.py", line 165, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return await responder(scope, receive, send)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/a2wsgi/wsgi.py", line 208, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     raise self.exc_info[0].with_traceback(
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/web/framework/middleware/error.py", line 167, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     app_iter = self.application(environ, sr_checker)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/web/framework/middleware/statsd.py", line 29, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     req = self.application(environ, start_response)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/paste/httpexceptions.py", line 635, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return self.application(environ, start_response)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/web/framework/base.py", line 176, in __call__
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     return self.handle_request(request_id, path_info, environ, start_response)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/web/framework/base.py", line 271, in handle_request
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     body = method(trans, **kwargs)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:            ^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/workflow.py", line 310, in build_from_current_history
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     stored_workflow = extract_workflow(
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:                       ^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 45, in extract_workflow
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     steps = extract_steps(
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:             ^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 140, in extract_steps
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     tool_inputs, associations = step_inputs(trans, job)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:                                 ^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 397, in step_inputs
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     associations = __cleanup_param_values(tool.inputs, param_values)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 458, in __cleanup_param_values
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     cleanup("", inputs, values)
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 456, in cleanup
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     cleanup(f"{prefix}{key}|", input.inputs, values[input.name])
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 456, in cleanup
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     cleanup(f"{prefix}{key}|", input.inputs, values[input.name])
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 452, in cleanup
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:     current_case = group_values["__current_case__"]
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]:                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
Sep 26 16:56:06 sn09.galaxyproject.eu gunicorn[2987339]: KeyError: '__current_case__'
