### ISSUE TITLE
galaxy_ext.metadata.set_metadata available as galaxy.metadata in pip installable package

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#14019]
I've pip installed the galaxy-test-driver package and related dependencies, for some integration testing with total-perspective-vortex. It has worked fine for the most part, barring some minor fixes: https://github.com/galaxyproject/galaxy/pull/14018

However, I ran into the following:
```
Traceback (most recent call last):
  File "/Users/nuwan/work/total-perspective-vortex/tests/test_mapper_resubmit.py", line 39, in test_default_resubmission
    self._assert_job_passes()
  File "/Users/nuwan/work/total-perspective-vortex/tests/test_mapper_resubmit.py", line 26, in _assert_job_passes
    self._run_tool_test(tool_id, resource_parameters=resource_parameters)
  File "/Users/nuwan/work/total-perspective-vortex/.tox/py3.8/lib/python3.8/site-packages/galaxy_test/driver/integration_util.py", line 163, in _run_tool_test
    return self._test_driver.run_tool_test(*args, **kwargs)
  File "/Users/nuwan/work/total-perspective-vortex/.tox/py3.8/lib/python3.8/site-packages/galaxy_test/driver/driver_util.py", line 1155, in run_tool_test
    verify_tool(
  File "/Users/nuwan/work/total-perspective-vortex/.tox/py3.8/lib/python3.8/site-packages/galaxy/tool_util/verify/interactor.py", line 1131, in verify_tool
    raise e
  File "/Users/nuwan/work/total-perspective-vortex/.tox/py3.8/lib/python3.8/site-packages/galaxy/tool_util/verify/interactor.py", line 1127, in verify_tool
    job_stdio = _verify_outputs(testdef, test_history, jobs, data_list, data_collection_list, galaxy_interactor, quiet=quiet)
  File "/Users/nuwan/work/total-perspective-vortex/.tox/py3.8/lib/python3.8/site-packages/galaxy/tool_util/verify/interactor.py", line 1301, in _verify_outputs
    raise JobOutputsError(found_exceptions, job_stdio)
galaxy.tool_util.verify.interactor.JobOutputsError: Job in error state.. tool_id: exit_code_oom, exit_code: 42, stderr:
Traceback (most recent call last):
  File "metadata/set.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
ModuleNotFoundError: No module named 'galaxy_ext'
```

The issue appears to be that the galaxy_ext.metadata package has been renamed to galaxy.metadata within the pip installable job_execution package, and therefore, the above import doesn't work. An easy fix would be to add a symlink from `lib.metadata` -> `lib.galaxy_ext.metadata` and to rename all imports to use galaxy.metadata, but I wasn't sure that was the right path, since lib generally does not have symlinks. Is there some other way to pip install galaxy_ext?

**Comment by mvdbeek** [comment]
Any chance that would be resolved by setting `use_metadata_binary: true` on your destination ? This somehow seems to have been lost from the job conf sample ...

**Comment by mvdbeek** [comment]
I'm pretty sure `use_metadata_binary: true` is the right fix here. I think the medium term thing here is to also resolve dependencies for the metadata script, then we can do away with the whole venv / galaxy-lib conservation dance we currently do in the job script.
