### ISSUE TITLE
Exception in pulsar job runner and pulsar

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14043]
From https://github.com/galaxyproject/galaxy/runs/6813117580?check_suite_focus=true#step:15:1875

```
galaxy.jobs.runners ERROR 2022-06-09 13:28:40,870 [pN:main.1,p:22032,tN:PulsarJobRunner.work_thread-1] (1) Unhandled exception calling finish_job
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/pulsar.py", line 638, in finish_job
    failed = pulsar_finish_job(**finish_args)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/client/staging/down.py", line 26, in finish_job
    collection_failure_exceptions = results_stager.collect()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/client/staging/down.py", line 68, in collect
    self.__collect_outputs()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/client/staging/down.py", line 100, in __collect_outputs
    output_generated = self.pulsar_outputs.has_output_file(output_file)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/client/staging/__init__.py", line 299, in has_output_file
    return basename(output_file) in self.output_directory_contents
TypeError: argument of type 'NoneType' is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/__init__.py", line 153, in run_next
    method(arg)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/pulsar.py", line 644, in finish_job
    self.fail_job(job_state, message=GENERIC_REMOTE_ERROR, exception=True)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/pulsar.py", line 672, in fail_job
    self.stop_job(job_state.job_wrapper)
AttributeError: 'str' object has no attribute 'job_wrapper'
galaxy.jobs.runners.pulsar DEBUG 2022-06-09 13:28:40,875 [pN:main.1,p:22032,tN:PulsarJobRunner.work_thread-1] Attempt remote Pulsar kill of job with url pulsar_embed and id 1
```

Looks like 2 different errors, one in pulsar, one in the job handler.

**Comment by mvdbeek** [comment]
I think we've fixed these some time ago.
