### ISSUE TITLE
Galaxy does not start if the MQ has problems

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14058]
I guess if we rely more and more on an MQ it's okay to fail Galaxy and not start it up. In this case please close the issue.
In this case, MQ is optional if should __not__ prevent the zerglings to start up, which is currently the case.

```
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]: Traceback (most recent call last):
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "lib/galaxy/webapps/galaxy/buildapp.py", line 63, in app_pair
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "lib/galaxy/app.py", line 475, in __init__
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self.queue_worker = self._register_singleton(GalaxyQueueWorker, GalaxyQueueWorker(self))
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "lib/galaxy/queue_worker.py", line 338, in __init__
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self.connection.connect()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/connection.py", line 275, in connect
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     return self._ensure_connection(
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/connection.py", line 434, in _ensure_connection
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     return retry_over_time(
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     return fun(*args, **kwargs)
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/connection.py", line 878, in _connection_factory
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self._connection = self._establish_connection()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/connection.py", line 813, in _establish_connection
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     conn = self.transport.establish_connection()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     conn.connect()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/amqp/connection.py", line 323, in connect
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self.transport.connect()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/amqp/transport.py", line 114, in connect
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self._init_socket(
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/amqp/transport.py", line 225, in _init_socket
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self._setup_transport()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/amqp/transport.py", line 416, in _setup_transport
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self.sock.do_handshake()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:   File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]:     self._sslobj.do_handshake()
Jun 13 11:45:05 sn06.galaxyproject.eu uwsgi[2498270]: ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)
```

**Comment by mvdbeek** [comment]
It is not optional for the queue worker, if you configured a different URL and it is not available it is the right thing to fail at startup. I also think everything should fail like that if it is setup, optional or not, since this is very hard to troubleshoot.
