### ISSUE TITLE
the value of an undefined input is wrongly inherited from the previous input

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#14169]
Consider the following `tool.xml`:

```
<command>
echo '${par1}' &&
echo '${par2}' && 
echo '${par3}'
</command>
...
<inputs>
<param name="par1" type="data" format="csv">
<param name="par2" type="data" format="csv">
<param name="par3" type="data" format="csv" optional="true">
<inputs>
...
<test>
<param name="par1" value="par1.csv"/>
<param name="par2" value="par2.csv"/>
</test>
```

This is the test output of such tool. Note the second and the third rows are equal:

```
.../dataset_118405c9-de11-445b-9a20-605ae3a131ef.dat
.../dataset_ba152208-fb65-4925-8833-3be81e6696b9.dat
.../dataset_ba152208-fb65-4925-8833-3be81e6696b9.dat
```

The tool behaves the same if the `optional="true"` is omitted.

Expected behavior:
- if `optional="true"` the `${par3}` should have a value of `None/""` or similar
- if `optional="false"` the test should quickly fail/not start as it is invalid

This works correctly when the tool is directly put in Galaxy without planemo, the value of par3 is `None`.

**Comment by nsoranzo** [comment]
Note that if `par3` is of a different incompatible format (e.g. `png`), the test will correctly fail with:

```
======================================================================
ERROR: ( test ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/functional/test_toolbox.py", line 115, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/test/functional/test_toolbox.py", line 43, in do_it
    verify_tool(
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/tool_util/verify/interactor.py", line 1242, in verify_tool
    raise e
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/tool_util/verify/interactor.py", line 1235, in verify_tool
    tool_response = galaxy_interactor.run_tool(testdef, test_history, resource_parameters=resource_parameters)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/tool_util/verify/interactor.py", line 543, in run_tool
    submit_response_object = ensure_tool_run_response_okay(submit_response, "execute tool", inputs_tree)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/tool_util/verify/interactor.py", line 914, in ensure_tool_run_response_okay
    raise RunToolException(message, inputs, dynamic_param_error=dynamic_param_error)
galaxy.tool_util.verify.interactor.RunToolException: parameter 'par2': specify a dataset of the required format / build for parameter
```

**Comment by nsoranzo** [comment]
This tool:
```xml
<tool id="test" name="Test tool" version="1.0" profile="21.05">
    <command><![CDATA[
echo '${par1}' > '${out}' &&
echo '${par2}' >> '${out}'
    ]]></command>
    <inputs>
        <param name="par1" type="data" format="csv" label="Parameter 1" />
        <param name="par2" type="data" format="csv" label="Parameter 2" />
    </inputs>
    <outputs>
        <data name="out" format="txt" />
    </outputs>
    <tests>
        <test>
            <param name="par1" value="par1.csv"/>
            <output name="out">
                <assert_contents>
                    <has_n_lines n="2" />
                    <has_line line="None" />
                </assert_contents>
            </output>
        </test>
    </tests>
</tool>
```

passes the test fine, so I don't see the issue when `optional="true"` is specified.
