### ISSUE TITLE
Tools in workflow show multiple outputs even when not produced

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1418]
## Updated Issue

This is a lie, only one of those three outputs will be produced.

![selection_518](https://cloud.githubusercontent.com/assets/458683/12095675/08c84d44-b2d6-11e5-8292-d2b21d1e761b.png)

Some of those outputs are only available as a result of parameters that are toggled within in the workflow tool config UI. 

If there are examples of output `<filter />` blocks which use **runtime**-only information, I'll close this issue as something that cannot be fixed. Otherwise it's a usability bug that multiple outputs are shown even when not produced.

```
galaxy.tools.execute DEBUG 2016-01-04 11:00:45,296 Tool [toolshed.g2.bx.psu.edu/repos/bgruening/glimmer3/glimmer_not-knowlegde-based/0.2] created job [46871] (241.262 ms)
galaxy.tools.execute DEBUG 2016-01-04 11:00:45,301 Executed all jobs for tool request: (257.670 ms)
galaxy.workflow.run DEBUG 2016-01-04 11:00:45,310 Workflow step 8846 invoked (266.932 ms)
galaxy.workflow.run ERROR 2016-01-04 11:00:45,328 Failed to schedule Workflow[id=718,name=Workflow-Bug-MWE], problem occurred on WorkflowStep[index=2,type=tool].
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1122, in execute
    collections_to_match = self._find_collections_to_match( tool, progress, step )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1208, in _find_collections_to_match
    visit_input_values( tool.inputs, step.state.inputs, callback )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 47, in visit_input_values
    prefixed_label=label_prefix + input.label )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1197, in callback
    data = progress.replacement_for_tool_input( step, input, prefixed_name )
  File "/galaxy/lib/galaxy/workflow/run.py", line 283, in replacement_for_tool_input
    replacement = self.replacement_for_connection( connection[ 0 ], is_data=is_data )
  File "/galaxy/lib/galaxy/workflow/run.py", line 303, in replacement_for_connection
    raise Exception( message )
Exception: Workflow evaluation problem - failed to find output_name prediction in step_outputs {'genes_output': <galaxy.model.HistoryDatasetAssociation object at 0x7fbb91
228490>}
galaxy.workflow.run ERROR 2016-01-04 11:00:45,328 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1122, in execute
    collections_to_match = self._find_collections_to_match( tool, progress, step )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1208, in _find_collections_to_match
    visit_input_values( tool.inputs, step.state.inputs, callback )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 47, in visit_input_values
    prefixed_label=label_prefix + input.label )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1197, in callback
    data = progress.replacement_for_tool_input( step, input, prefixed_name )
  File "/galaxy/lib/galaxy/workflow/run.py", line 283, in replacement_for_tool_input
    replacement = self.replacement_for_connection( connection[ 0 ], is_data=is_data )
  File "/galaxy/lib/galaxy/workflow/run.py", line 303, in replacement_for_connection
    raise Exception( message )
Exception: Workflow evaluation problem - failed to find output_name prediction in step_outputs {'genes_output': <galaxy.model.HistoryDatasetAssociation object at 0x7fbb91
228490>}
```

Related issue: I started from a large workflow and pared down to a MWE. The original workflow had "workflow outputs" marked because there were many non-essential steps. After paring it down, all outputs continued to be hidden, despite the fact that none were marked as such in the workflow editor. I've added this to #1387

**Comment by erasche** [comment]
Cannot reproduce this locally, investigating config differences...

**Comment by erasche** [comment]
Okay, not a config difference. This is the result of a tool with a `<filter />` available on the output, and the UI indicating that an output was available. Updating issue and retagging to reflect.

**Comment by hexylena** [comment]
Bit me again. Didn't scan the tool's config interface closely enough. Two outputs = there will be two outputs, right? Wrong!

This is a really annoying UX bug that **silently** consumes workflow steps.

**Comment by hexylena** [comment]
Related to https://github.com/galaxyproject/galaxy/issues/1724

**Comment by hexylena** [comment]
@blankclemens and I spent 15 minutes wondering why a workflow wasn't working due to this issue. It's really quite annoying...

**Comment by mvdbeek** [comment]
Yep, I think we can build the form again on the backend when we change a parameter.

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7576
