### ISSUE TITLE
Flaky S3 integration test

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14240]
This is the traceback:
```
uvicorn.error ERROR 2022-06-30 17:36:57,074 [pN:main,p:7826,tN:Thread-479] Exception in ASGI application
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/base/api.py", line 28, in dispatch
    return await call_next(request)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/fast_app.py", line 104, in add_x_frame_options
    response = await call_next(request)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 228, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/history_contents.py", line 454, in show
    fuzzy_count=fuzzy_count,
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/services/history_contents.py", line 356, in show
    return self.__show_dataset(trans, id, serialization_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/services/history_contents.py", line 1275, in __show_dataset
    return self.hda_serializer.serialize_to_view(hda, user=trans.user, trans=trans, **serialization_params.dict())
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/base.py", line 772, in serialize_to_view
    return self.serialize(item, all_keys, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/hdas.py", line 464, in serialize
    return super().serialize(hda, keys, user=user, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/datasets.py", line 670, in serialize
    serialized = super().serialize(dataset_assoc, keys, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/base.py", line 685, in serialize
    returned[key] = self.serializers[key](item, key, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/datasets.py", line 561, in <lambda>
    return lambda item, key, **context: serializer(item.dataset, proxy_key or key, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/datasets.py", line 207, in serialize_file_name
    return dataset.file_name
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/model/__init__.py", line 3495, in get_file_name
    file_name = self.object_store.get_filename(self)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/__init__.py", line 360, in get_filename
    return self._invoke("get_filename", obj, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/__init__.py", line 339, in _invoke
    return self.__getattribute__(f"_{delegate}")(obj=obj, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/__init__.py", line 776, in _get_filename
    return self._call_method("_get_filename", obj, ObjectNotFound, True, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/__init__.py", line 810, in _call_method
    return store.__getattribute__(method)(obj, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/s3.py", line 720, in _get_filename
    if self._pull_into_cache(rel_path):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/s3.py", line 447, in _pull_into_cache
    file_ok = self._download(rel_path)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/objectstore/s3.py", line 459, in _download
    if self.cache_size > 0 and key.size > self.cache_size:
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by mvdbeek** [comment]
from https://github.com/galaxyproject/galaxy/runs/7136162105?check_suite_focus=true#step:15:1716
