### ISSUE TITLE
Role and Group permissions expressions in File Source Plugins don't allow quoted values

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#14405]
**Describe the bug**

Reported by @natefoo in the Backend chat:

> I'm getting a parsing error attempting to use requires_groups in a file source plugin config, and it's due to the group name containing a space:
```
>>> from galaxy.util.bool_expressions import BooleanExpressionEvaluator
>>> BooleanExpressionEvaluator.is_valid_expression("vgp")
True
>>> BooleanExpressionEvaluator.is_valid_expression("VGP Project")
BooleanExpressionEvaluator unable to evaluate expression => VGP Project
Traceback (most recent call last):
  File "/home/nate/work/galaxy/lib/galaxy/util/bool_expressions.py", line 150, in evaluate_expression
    res = self.boolExpr.parseString(expr, parseAll=True)[0]
  File "/home/nate/work/galaxy/.venv/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'Project'  (at char 4), (line:1, col:5)
False
>>> BooleanExpressionEvaluator.is_valid_expression("'VGP Project'")
BooleanExpressionEvaluator unable to evaluate expression => 'VGP Project'
Traceback (most recent call last):
  File "/home/nate/work/galaxy/lib/galaxy/util/bool_expressions.py", line 150, in evaluate_expression
    res = self.boolExpr.parseString(expr, parseAll=True)[0]
  File "/home/nate/work/galaxy/.venv/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected 'or' term, found "'"  (at char 0), (line:1, col:1)
False
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 (and up to 21.05)
Commit: 574c8f81748b5f5b5fcbb3db2247c61a3c2ba1ac

**To Reproduce**
1. As an Admin, add a `requires_groups` expression to any of your FileSource plugins with the name of a group containing spaces and single quotes like `'My group'`.
2. Run Galaxy and observe the error above.

**Expected behavior**
Group or role names enclosed in single quotes and containing spaces should be valid.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14406
