### ISSUE TITLE
build_from_current_history crashed with a key error

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14423]
We have a reproducible history, where we are not able to extract a workflow from it. The workflows has collections and data from a DL.
The following stack trace appears in the logs:

```
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: 10.5.160.138 - - [09/Aug/2022:14:12:33 +0200] "POST /workflow/build_from_current_history HTTP/1.0" 500 - "https://usegalaxy.eu/workflow/build_from_current_history" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: Error - <class 'AttributeError'>: 'dict' object has no attribute 'hid'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: URL: https://usegalaxy.eu/workflow/build_from_current_history
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/web/framework/middleware/error.py', line 165 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   app_iter = self.application(environ, sr_checker)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/wsgi.py', line 139 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   reraise(*_capture_exception(hub))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/_compat.py', line 54 in reraise
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   raise value
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/wsgi.py', line 132 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   rv = self.app(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/venv/lib64/python3.8/site-packages/paste/recursive.py', line 85 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   return self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/web/framework/middleware/statsd.py', line 29 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   req = self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/venv/lib64/python3.8/site-packages/paste/httpexceptions.py', line 640 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   return self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/web/framework/base.py', line 166 in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   return self.handle_request(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/web/framework/base.py', line 251 in handle_request
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   body = method(trans, **kwargs)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 884 in build_from_current_history
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   stored_workflow = extract_workflow(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/workflow/extract.py', line 43 in extract_workflow
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   steps = extract_steps(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/workflow/extract.py', line 136 in extract_steps
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   tool_inputs, associations = step_inputs(trans, job)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/workflow/extract.py', line 386 in step_inputs
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   associations = __cleanup_param_values(tool.inputs, param_values)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/workflow/extract.py', line 447 in __cleanup_param_values
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   cleanup("", inputs, values)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: File '/opt/galaxy/server/lib/galaxy/workflow/extract.py', line 416 in cleanup
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   associations.append((item.hid, prefix + key))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: AttributeError: 'dict' object has no attribute 'hid'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: CGI Variables
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: -------------
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   CONTENT_LENGTH: '4571'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   CONTENT_TYPE: 'application/x-www-form-urlencoded'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.5'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_CONNECTION: 'close'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_COOKIE: 'galaxysession=11ac94870d0bb33a53e05523d46943ec551c9759b27dd31ca8e877847a0adb729b24ecd9e588e616'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_DNT: '1'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_HOST: 'usegalaxy.eu'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_ORIGIN: 'https://usegalaxy.eu'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_REFERER: 'https://usegalaxy.eu/workflow/build_from_current_history'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_SEC_FETCH_DEST: 'iframe'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_SEC_FETCH_MODE: 'navigate'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_SEC_FETCH_SITE: 'same-origin'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_SEC_FETCH_USER: '?1'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_UPGRADE_INSECURE_REQUESTS: '1'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_USER_AGENT: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_X_FORWARDED_FOR: '10.5.160.138'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   HTTP_X_FORWARDED_PROTO: 'https'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   ORGINAL_REMOTE_ADDR: '10.5.160.138'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   PATH_INFO: '/workflow/build_from_current_history'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   REMOTE_ADDR: '10.5.160.138'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   REQUEST_METHOD: 'POST'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   SERVER_NAME: 'localhost'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   SERVER_PORT: 80
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   SERVER_PROTOCOL: 'HTTP/1.0'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: WSGI Variables
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: --------------
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   application: <sentry_sdk.integrations.wsgi.SentryWsgiMiddleware object at 0x7f30f3fe2640>
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   asgi.scope: {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': None, 'client': ('10.5.160.138', 0), 'scheme': 'https', 'method': 'POST', 'root_path': '', 'path': '/workflow/build_from_current_history', 'raw_path': b'/workflow/build_from_current_history', 'query_string': b'', 'headers': [(b'host', b'usegalaxy.eu'), (b'x-forwarded-for', b'10.5.160.138'), (b'x-forwarded-proto', b'https'), (b'connection', b'close'), (b'content-length', b'4571'), (b'user-agent', b'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0'), (b'accept', b'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'), (b'accept-language', b'en-US,en;q=0.5'), (b'accept-encoding', b'gzip, deflate, br'), (b'referer', b'https://usegalaxy.eu/workflow/build_from_current_history'), (b'content-type', b'application/x-www-form-urlencoded'), (b'origin', b'https://usegalaxy.eu'), (b'dnt', b'1'), (b'cookie', b'galaxyse... 0x7f30f3f65b80>}
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   controller_action_key: 'web.workflow.build_from_current_history'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   is_api_request: False
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x7f30f3fe2e80>
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.recursive.forward: <paste.recursive.Forwarder from />
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.recursive.include: <paste.recursive.Includer from />
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.recursive.script_name: ''
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   paste.throw_errors: True
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   request_id: '8cbae3b017dc11eda994001e67d2ec02'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   webob._body_file: (<_io.BufferedReader>, <a2wsgi.wsgi.Body object at 0x7f309f1b5c10>)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   webob._parsed_post_vars: (MultiDict([('workflow_name', "Workflow constructed from history 'imported: Fariba ZFP Preprocessing'"), ('dataset_ids', '1'), ('dataset_names', 'A_overexpr_r1.fq'), ('dataset_ids', '2'), ('dataset_names', 'B_Control_r1.fq'), ('dataset_ids', '3'), ('dataset_names', 'C_overexpr_Input_(r1).fq'), ('dataset_ids', '4'), ('dataset_names', 'D_Control_Input_(r1).fq'), ('dataset_ids', '5'), ('dataset_names', 'E_overexpr_r2.fq'), ('dataset_ids', '6'), ('dataset_names', 'F_Control_r2.fq'), ('dataset_ids', '7'), ('dataset_names', 'G_overexpr_Input_(r2).fq'), ('dataset_ids', '8'), ('dataset_names', 'H_Control_Input_(r2).fq'), ('job_ids', '3357652'), ('job_ids', '3357653'), ('job_ids', '3357654'), ('job_ids', '3357655'), ('job_ids', '3357656'), ('job_ids', '3357657'), ('job_ids', '3357658'), ('job_ids', '3357659'), ('job_ids', '3358890'), ('job_ids', '3358891'), ('job_ids', '3358892'), ('job_ids', '3358893'), ('job_ids', '3358894'), ('job_ids', '3358895'), ('job_ids', '3358896'),... 0x7f30d9889770>)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   webob._parsed_query_vars: (GET([]), '')
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   webob.is_body_seekable: True
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   wsgi process: 'Multi process AND threads (?)'
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: ------------------------------------------------------------
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: [2022-08-09 14:12:36 +0200] [284725] [ERROR] Exception in ASGI application
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: Traceback (most recent call last):
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     result = await app(self.scope, self.receive, self.send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return await self.app(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await super().__call__(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/applications.py", line 124, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.middleware_stack(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise exc
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, receive, _send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 69, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await response(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 260, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await wrap(partial(self.listen_for_disconnect, receive))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise exceptions[0]
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 256, in wrap
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await func()
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 245, in stream_response
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     async for chunk in self.body_iterator:
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 58, in body_stream
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise app_exc
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 36, in coro
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, request.receive, send_stream.send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, receive, send_wrapper)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 69, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await response(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 260, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await wrap(partial(self.listen_for_disconnect, receive))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise exceptions[0]
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 256, in wrap
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await func()
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/responses.py", line 245, in stream_response
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     async for chunk in self.body_iterator:
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 58, in body_stream
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise app_exc
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 36, in coro
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, request.receive, send_stream.send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 115, in _run_asgi3
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return await self._run_app(scope, lambda: self.app(scope, receive, send))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 162, in _run_app
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise exc from None
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 159, in _run_app
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return await callback()
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise exc
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, receive, sender)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise e
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/routing.py", line 670, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await route.handle(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/starlette/routing.py", line 418, in handle
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     await self.app(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/a2wsgi/wsgi.py", line 140, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return await responder(scope, receive, send)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/a2wsgi/wsgi.py", line 179, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise self.exc_info[0].with_traceback(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/web/framework/middleware/error.py", line 165, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     app_iter = self.application(environ, sr_checker)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 139, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     reraise(*_capture_exception(hub))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     raise value
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 132, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     rv = self.app(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/paste/recursive.py", line 85, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/web/framework/middleware/statsd.py", line 29, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     req = self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/paste/httpexceptions.py", line 640, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return self.application(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/web/framework/base.py", line 166, in __call__
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     return self.handle_request(environ, start_response)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/web/framework/base.py", line 251, in handle_request
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     body = method(trans, **kwargs)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/workflow.py", line 884, in build_from_current_history
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     stored_workflow = extract_workflow(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 43, in extract_workflow
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     steps = extract_steps(
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 136, in extract_steps
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     tool_inputs, associations = step_inputs(trans, job)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 386, in step_inputs
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     associations = __cleanup_param_values(tool.inputs, param_values)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 447, in __cleanup_param_values
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     cleanup("", inputs, values)
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:   File "/opt/galaxy/server/lib/galaxy/workflow/extract.py", line 416, in cleanup
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]:     associations.append((item.hid, prefix + key))
Aug 09 14:12:36 sn06.galaxyproject.eu gunicorn[1643947]: AttributeError: 'dict' object has no attribute 'hid'
```

Adding some debug messages into https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/extract.py#L416

Yields:

```
Aug 09 16:27:00 sn06.galaxyproject.eu gunicorn[952850]: galaxy.workflow.extract DEBUG 2022-08-09 16:27:00,468 [pN:main.2,p:989127,tN:WSGI_6] build_from_current_history-crash: <galaxy.model.HistoryDatasetAssociation(29325545) at 0x7f7d33e7f9d0>
Aug 09 16:27:00 sn06.galaxyproject.eu gunicorn[952850]: galaxy.workflow.extract DEBUG 2022-08-09 16:27:00,476 [pN:main.2,p:989127,tN:WSGI_6] build_from_current_history-crash: {'values': [{'src': 'hda', 'id': '5e1b8db10ba6ba22'}]}
```

The first line is the expected value and we have a lot of those, the second line is the line that yields to the crash. 
Interestingly the if condition before (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/extract.py#L413) is not entered at all.

**Comment by mvdbeek** [comment]
Can you share that history ?
