### ISSUE TITLE
Galaxy histories exported using the history export feature cannot be imported using the provided link to other Galaxy servers

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#14447]
**Describe the bug**
Galaxy histories exported using the history export feature cannot be imported using the provided link to other Galaxy servers

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 and 21.09 (tested between pairs of 22.05 servers and a 21.09 server exporting to 22.05 server)

**To Reproduce**
1. History Menu -> Export History to File
2. Click the "Click here to generate a new archive for this history." button
3. Copy the link that is created and go to another Galaxy server
4. Select User -> Histories and Import History
5. Select the "Export URL from another Galaxy instance", paste in link and click Import History.
6. Get error

The error traceback is:

```python
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 92, in <module>
    main(options, args)
  File "/opt/galaxy/server/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 66, in main
    archive_file = stream_url_to_file(
  File "/opt/galaxy/server/lib/galaxy/files/uris.py", line 63, in stream_url_to_file
    page = urllib.request.urlopen(path, timeout=DEFAULT_SOCKET_TIMEOUT)  # page will be .close()ed in stream_to_file
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

But the error is on the sending server side. While it is possible to download the exported Galaxy history as a file by clicking on the link in the same, logged in, Galaxy session, it is not possible to download the link when not logged. One receives the error "History is not accessible by user".

**Expected behavior**
This method of exporting a link and importing it on another server should work. It is documented on GTN here: https://training.galaxyproject.org/training-material/faqs/galaxy/histories_transfer_entire_histories_from_one_galaxy_server_to_another.html 

If it is not designed to work this way, the documentation should be updated and the user interface should not offer the import from link option.

**Comment by mvdbeek** [comment]
It says in the sharing dialog that you need to publish the history, did you do that? This is definitely expected to work.

**Comment by pvanheus** [comment]
> It says in the sharing dialog that you need to publish the history, did you do that? This is definitely expected to work.

I did not publish the history - that step is not mentioned anywhere that I can see. I can verify that going to the History menu's Share or Publish option and setting "Make History accessible" to true makes the procedure documented [here](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_transfer_entire_histories_from_one_galaxy_server_to_another.html) work. None of the pages I used in exporting and importing, nor the error message from the failed import mention the need to enable this option though. So this is somewhat of a usability / documentation bug.

This is the text shown when creating an archive (on 22.05):
![image](https://user-images.githubusercontent.com/4154788/184473902-69e99221-1e99-4968-8a9f-f4c7a7aaefa4.png)

And this is the text on the import page (on 21.09):
![image](https://user-images.githubusercontent.com/4154788/184473943-6bcb7b44-7c6a-497e-a320-2c3df7229188.png)

**Comment by mvdbeek** [comment]
Hmm, yes, you're right, we used to have a little blurb saying that you need to publish the history if you want to import the history by link.

**Comment by pvanheus** [comment]
Thanks for the comment and proposed PR @mvdbeek. I think there are a few options here:

1. Text to tell user to share history
2. Export link is auto-shared (your current PR https://github.com/galaxyproject/galaxy/pull/14459)
3. Exporting implicitly flips the sharing toggle to "True"
4. A toggle or checkbox is included in the export page to enable sharing.

I personally think that (3) or (4) might be the best options because it avoids the problem that @nsoranzo [noted](https://github.com/galaxyproject/galaxy/pull/14459#issuecomment-1215932263).

**Comment by mjbludwig** [comment]
I should note that to pull a history from an old galaxy (20.01) I did need to set `require_login: false`

**Comment by gallardoalba** [comment]
It seems that it is failing also with published histories https://help.galaxyproject.org/t/importing-history-between-different-galaxy-instances-fails/8842/3
