### ISSUE TITLE
Crash during submission of a workflow the `history_dataset_association.id` tries to be a float

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14477]
It seems to be reproducible with one of the COVID workflows, so we rather assume that it is the history and not the workflow.

```
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]: The above exception was the direct cause of the following exception:
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]: Traceback (most recent call last):
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/web/framework/decorators.py", line 337, in decorator
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     rval = func(self, trans, *args, **kwargs)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/api/workflows.py", line 838, in invoke
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     workflow_invocation = queue_invoke(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/workflow/run.py", line 71, in queue_invoke
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     modules.populate_module_and_state(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/workflow/modules.py", line 2209, in populate_module_and_state
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     step_errors = module_injector.inject(step, step_args=step_args)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/workflow/modules.py", line 2192, in inject
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     state, step_errors = module.compute_runtime_state(self.trans, step, step_args)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/workflow/modules.py", line 300, in compute_runtime_state
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     visit_input_values(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 218, in visit_input_values
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     callback_helper(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 153, in callback_helper
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     new_value = callback(**args)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/workflow/modules.py", line 294, in update_value
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     value, error = check_param(trans, input, step_updates.get(prefixed_name), context)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 237, in check_param
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     value = param.from_json(value, trans, param_values)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 2105, in from_json
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     rval.append(trans.sa_session.query(HistoryDatasetAssociation).get(value))
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "<string>", line 2, in get
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return fn(*args, **kwargs)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 943, in get
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return self._get_impl(ident, loading.load_on_pk_identity)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return self.session._get_impl(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 2912, in _get_impl
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return db_load_fn(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     session.execute(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     result = conn._execute_20(statement, params or {}, execution_options)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return meth(self, args_10style, kwargs_10style, execution_options)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     return connection._execute_clauseelement(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     ret = self._execute_context(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     self._handle_dbapi_exception(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     util.raise_(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     raise exception
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     self.dialect.do_execute(
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]:     cursor.execute(statement, parameters)
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]: sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "1.0"
Aug 18 13:50:35 sn06.galaxyproject.eu gunicorn[2570469]: LINE 3: WHERE history_dataset_association.id = '1.0'

```

**Comment by mvdbeek** [comment]
That looks a lot like you have a conflict of parameter names, can you share the workflow ?
