### ISSUE TITLE
celery task setup_fetch_data fails with: Column expression or FROM clause expected

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14568]
We finally made some progress to use an external celery cluster. A few tasks are working but the `galaxy.celery.tasks.setup_fetch_data` fails with.

```
 Traceback (most recent call last):
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/galaxy/server/lib/galaxy/celery/__init__.py", line 207, in wrapper
    rval = app.magic_partial(func)(*args, **kwds)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/lagom/wrapping.py", line 28, in _bound_func
    return inner_func(*bound_args, **bound_kwargs)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/lagom/wrapping.py", line 45, in _error_handling_func
    return func(*args, **kwargs)
  File "/opt/galaxy/server/lib/galaxy/celery/tasks.py", line 176, in setup_fetch_data
    mini_job_wrapper.change_state(model.Job.states.QUEUED, flush=False, job=job)
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1528, in change_state
    job.update_output_states(self.app.application_stack.supports_skip_locked())
  File "/opt/galaxy/server/lib/galaxy/model/__init__.py", line 1673, in update_output_states
    self.update_hdca_update_time_for_job(
  File "/opt/galaxy/server/lib/galaxy/model/__init__.py", line 1551, in update_hdca_update_time_for_job
    .where(HistoryDatasetCollectionAssociation.table.c.id.in_(select(subq)))
  File "<string>", line 2, in select
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 5314, in _create
    return cls._create_future_select(*args)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 5232, in _create_future_select
    self._raw_columns = [
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 5233, in <listcomp>
    coercions.expect(
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 212, in expect
    return impl._implicit_coercions(
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 255, in _implicit_coercions
    self._raise_for_expected(element, argname, resolved)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 437, in _raise_for_expected
    return super(_SelectIsNotFrom, self)._raise_for_expected(
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 283, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression or FROM clause expected, got <sqlalchemy.sql.selectable.Select object at 0x7fc2a43bf460> object resolved from <sqlalchemy.orm.query.Query object at 0x7fc2a43bf2b0> object. To create a FROM clause from a <class 'sqlalchemy.sql.selectable.Select'> object, use the .subquery() method. (Background on this error at: https://sqlalche.me/e/14/89ve)

```

**Comment by mvdbeek** [comment]
I think I see what's happening. You're not hitting the if statement in https://github.com/galaxyproject/galaxy/blob/release_22.05/lib/galaxy/model/__init__.py#L1548, which is probably because your database doesn't support skip_locked. I'll fix that, but you might want to check out why that is. FWIW postgres 9.5 and newer should be fine, or sqlite 3.25 and newer.

The check for this is in https://github.com/galaxyproject/galaxy/blob/release_22.05/lib/galaxy/web_stack/__init__.py#L70-L79.

**Comment by bgruening** [comment]
We are using postgresql 13. This is wired.

**Comment by mira-miracoli** [comment]
We are using `postgresql://user:password@host.galaxyproject.eu/galaxy`

**Comment by mvdbeek** [comment]
Could you please check that the process is really using this ?
E.g
```
diff --git a/lib/galaxy/app.py b/lib/galaxy/app.py
index f3d208869d..d68a6ea987 100644
--- a/lib/galaxy/app.py
+++ b/lib/galaxy/app.py
@@ -394,6 +394,7 @@ class ConfiguresGalaxyMixin:
         install_db_url = self.config.install_database_connection
         combined_install_database = is_one_database(db_url, install_db_url)
         engine, install_engine = self._configure_engines(db_url, install_db_url, combined_install_database)
+        log.debug(f"Using database connection {engine.url.render_as_string(hide_password=True)}" )
 
         if self.config.database_wait:
             self._wait_for_database(db_url)
```

The startup logs from one worker would also be helpful (you'll have to run at least one task to get the app fully booted)

**Comment by mira-miracoli** [comment]
I did not find the "Using database connection" string in the logs, but I found this error, which might be interesting:
`celery[203945]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  no pg_hba.conf entry for host "10.5.68.168", user "galaxy", database "galaxy", SSL off
`
It is shown for the tasks: `setup_fetch_data`, `recalculate_user_disk_usage`, `purge_hda` and `prune_history_audit_table`

The code block you mentioned is different in our app.py:
```diff
--- old	2022-09-14 10:12:20.811864443 +0200
+++ new	2022-09-14 10:16:19.643163250 +0200
@@ -1,8 +1,13 @@
-class ConfiguresGalaxyMixin:
+    def _configure_models(self, check_migrate_databases=False, config_file=None):
+         """Preconditions: object_store must be set on self."""
+         # TODO this block doesn't seem to belong in this method
+         if getattr(self.config, "max_metadata_value_size", None):
+             custom_types.MAX_METADATA_VALUE_SIZE = self.config.max_metadata_value_size
+ 
+         db_url = self.config.database_connection
          install_db_url = self.config.install_database_connection
          combined_install_database = is_one_database(db_url, install_db_url)
          engine, install_engine = self._configure_engines(db_url, install_db_url, combined_install_database)
-         log.debug(f"Using database connection {engine.url.render_as_string(hide_password=True)}" )
  
          if self.config.database_wait:
              self._wait_for_database(db_url)

```

**Comment by mvdbeek** [comment]
So this is your diff ?
```diff
diff --git a/lib/galaxy/app.py b/lib/galaxy/app.py
--- lib/galaxy/app.py
+++ lib/galaxy/app.py
@@ -385,8 +385,9 @@
         db_url = self.config.database_connection
         install_db_url = self.config.install_database_connection
         combined_install_database = is_one_database(db_url, install_db_url)
         engine, install_engine = self._configure_engines(db_url, install_db_url, combined_install_database)
+        log.debug(f"Using database connection {engine.url.render_as_string(hide_password=True)}")
 
         if self.config.database_wait:
             self._wait_for_database(db_url)
 
```
And you're not seeing the log message ? This would be quite strange, but maybe bump up the log level to warning ?

**Comment by mira-miracoli** [comment]
no sorry for being unclear: old is yours and new is what i found in our app.py

**Comment by mira-miracoli** [comment]
I added the missing "log.debug" line now to our code and I'll check the logs next time it fails a task.

**Comment by mvdbeek** [comment]
Alright, the updated diff applies against the release_22.05_europe branch, but `FATAL: no pg_hba.conf entry for host "10.5.68.168", user "galaxy", database "galaxy", SSL off` is definitely a problem. Is the host from which you run the tasks authorized to connect to postgres (you can configure this in pg_hba.conf)?

**Comment by mira-miracoli** [comment]
I will check this, it's probably a misconfiguration in the pg_hba.conf, yes. Thank you!

**Comment by bgruening** [comment]
The error unfortunately also happend with open PG. It's just that the configuration from PG was removed during nightly updates. It's not yet in the playbook as it's a bit complicated to open PG for dynamic workers.

**Comment by mvdbeek** [comment]
Let's work on this step by step. Given it doesn't work right now you could just hardcode the one worker you want to test, make sure you actually get the right connection, then we can look into this.

**Comment by bgruening** [comment]
We do not know why exactly this is not a problem anymore, but EU is now running a celery cluster in an external cloud VM.

![grafik](https://user-images.githubusercontent.com/469983/195931108-be8aeed1-a898-40e7-bf81-f0387e0fae88.png)

Thanks to @mira-miracoli - we have now playbooks for celery, flower, and co if anyone is interested.
