### ISSUE TITLE
Error when updating dataset permissions

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14827]
**Describe the bug**
When editing dataset permissions a server error can be thrown. Noting it here in order to keep track of this.

```
Traceback (most recent call last):
  File "/Users/guerler/galaxy/lib/galaxy/web/framework/decorators.py", line 337, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/guerler/galaxy/lib/galaxy/webapps/galaxy/controllers/dataset.py", line 464, in set_edit
    self.hda_manager.update_permissions(
  File "/Users/guerler/galaxy/lib/galaxy/managers/datasets.py", line 535, in update_permissions
    self._set_permissions(trans, dataset_assoc, role_ids_dict)
  File "/Users/guerler/galaxy/lib/galaxy/managers/hdas.py", line 301, in _set_permissions
    permissions, in_roles, error, message = security_agent.derive_roles_from_access(
  File "/Users/guerler/galaxy/lib/galaxy/model/security.py", line 1230, in derive_roles_from_access
    legitimate_roles = self.get_legitimate_roles(trans, item, cntrller)
  File "/Users/guerler/galaxy/lib/galaxy/model/security.py", line 239, in get_legitimate_roles
    if admin_controller or self.ok_to_display(trans.user, role):
  File "/Users/guerler/galaxy/lib/galaxy/model/security.py", line 264, in ok_to_display
    role_type = role.type
AttributeError: 'NoneType' object has no attribute 'type'
```

**Galaxy Version and/or server at which you observed the bug**
Current dev.

**Comment by mvdbeek** [comment]
In addition to fixing this it should probably be ported to use the API, which should be available for most of the `set_edir` operations.

**Comment by martenson** [comment]
@guerler do you think this is resolved? I am not sure how to replicate this.

**Comment by guerler** [comment]
Thanks @martenson!
