### ISSUE TITLE
galaxy-tool-util: conda auto install failing with OpenSSL error

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/galaxy#14848]
We use galaxy-tool-util in cwltool to install anaconda , but lately it is failing:

https://github.com/common-workflow-language/cwltool/actions/runs/3313610185/jobs/5471825354#step:9:435
```
  Traceback (most recent call last):
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
      return func(*args, **kwargs)
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
      exit_code = do_call(args, p)
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
      module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/cli/main_create.py", line 10, in <module>
      from .install import install
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/cli/install.py", line 18, in <module>
      from ..core.index import calculate_channel_urls, get_index
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
      from .package_cache_data import PackageCacheData
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
      from .path_actions import CacheUrlAction, ExtractPackageAction
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/core/path_actions.py", line 31, in <module>
      from ..gateways.connection.download import download
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
      from requests import ConnectionError, HTTPError, Session
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/requests/__init__.py", line 95, in <module>
      from urllib3.contrib import pyopenssl
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
      import OpenSSL.SSL
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import crypto, SSL
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1553, in <module>
      class X509StoreFlags(object):
    File "/home/runner/work/cwltool/cwltool/cwltool_deps/_conda/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
      CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
  AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

Possibly the base conda version needs incrementing? https://github.com/galaxyproject/galaxy/pull/8048#issuecomment-1289170524

**Comment by nsoranzo** [comment]
Yep, we are seeing in our CI testing as well, e.g.: https://github.com/galaxyproject/galaxy/actions/runs/3313597910/jobs/5471793025

**Comment by mr-c** [comment]
Thanks @nsoranzo . Will there be a new release sent to PyPI?

**Comment by nsoranzo** [comment]
@mr-c https://pypi.org/project/galaxy-tool-util/22.1.3/ , thanks to @mvdbeek
