### ISSUE TITLE
encoded id being used in database query while changing dataset permissions

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#14883]
Even without changing the permission management role, this yields 500. Version `dev` commit f08678e3a114813b7bcd5633c6863dbfddc2275d

![Galaxy___martenson](https://user-images.githubusercontent.com/1814954/198722294-e08aa64b-363b-416b-93c9-3cec14c8ad41.png)

```
galaxy.web.framework.decorators ERROR 2022-10-28 12:52:02,478 [pN:main.1,p:994,tN:WSGI_1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "5984ba4dcfdd4d00"
LINE 3: WHERE role.id = '5984ba4dcfdd4d00'
                        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py", line 337, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/controllers/dataset.py", line 468, in set_edit
    **payload_permissions,
  File "/Users/marten/devel/git/galaxy/lib/galaxy/managers/datasets.py", line 535, in update_permissions
    self._set_permissions(trans, dataset_assoc, role_ids_dict)
  File "/Users/marten/devel/git/galaxy/lib/galaxy/managers/hdas.py", line 302, in _set_permissions
    trans, hda.dataset.id, "root", **role_ids_dict
  File "/Users/marten/devel/git/galaxy/lib/galaxy/model/security.py", line 1216, in derive_roles_from_access
    in_roles = [self.sa_session.query(self.model.Role).get(x) for x in listify(kwd[k])]
  File "/Users/marten/devel/git/galaxy/lib/galaxy/model/security.py", line 1216, in <listcomp>
    in_roles = [self.sa_session.query(self.model.Role).get(x) for x in listify(kwd[k])]
  File "<string>", line 2, in get
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 947, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 959, in _get_impl
    execution_options=self._execution_options,
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2959, in _get_impl
    load_options=load_options,
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/Users/marten/devel/git/galaxy/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "5984ba4dcfdd4d00"
LINE 3: WHERE role.id = '5984ba4dcfdd4d00'
                        ^

[SQL: SELECT role.id AS role_id, role.create_time AS role_create_time, role.update_time AS role_update_time, role.name AS role_name, role.description AS role_description, role.type AS role_type, role.deleted AS role_deleted
FROM role
WHERE role.id = %(pk_1)s]
[parameters: {'pk_1': '5984ba4dcfdd4d00'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
uvicorn.access INFO 2022-10-28 12:52:02,480 [pN:main.1,p:994,tN:MainThread] 127.0.0.1:64897 - "PUT /dataset/set_edit HTTP/1.1" 500
```

**Comment by martenson** [comment]
Just reproduced this on test.galaxyproject.org

**Comment by martenson** [comment]
Probably broken here https://github.com/galaxyproject/galaxy/commit/a5cf5df3853e1f4c54a61232cffb70fba9acba6f

**Comment by guerler** [comment]
This might also close: #14827.
