### ISSUE TITLE
Tool shed migration failure

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#14923]
At minimum, the upgrade instructions are wrong when trying to run a toolshed that is a version behind:

```
Traceback (most recent call last):
  File "/home/dannon/work/galaxy/lib/tool_shed/webapp/buildapp.py", line 69, in app_pair
    app = UniverseApplication(global_conf=global_conf, **kwargs)
  File "/home/dannon/work/galaxy/lib/tool_shed/webapp/app.py", line 71, in __init__
    create_or_verify_database(db_url, self.config.database_engine_options)
  File "/home/dannon/work/galaxy/lib/tool_shed/webapp/model/migrate/check.py", line 85, in create_or_verify_database
    raise Exception(exception_msg)
Exception: Your database has version '26' but this code expects version '27'.  Back up your database and then migrate the schema by running the following from your Galaxy installation directory:

sh manage_db.sh upgrade tool_shed

[2022-11-04 05:50:06 -0400] [30376] [INFO] Worker exiting (pid: 30376)
[2022-11-04 05:50:06 -0400] [30385] [INFO] Booting worker with pid: 30385
^C[2022-11-04 05:50:06 -0400] [30366] [INFO] Handling signal: int
[2022-11-04 05:50:06 -0400] [30366] [WARNING] Worker with pid 30385 was terminated due to signal 2
[2022-11-04 05:50:07 -0400] [30366] [INFO] Shutting down: Master

(.venv) [dannon@inneoin:~/work/galaxy] sh manage_db.sh upgrade tool_shed                                          130 ↵toolshed-bundles ✹
Activating virtualenv at .venv
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
ERROR:galaxy.model.migrations.dbscript:Can't locate revision identified by 'tool_shed'
FAILED: Can't locate revision identified by 'tool_shed'
```

**Comment by mvdbeek** [comment]
@jdavcs can you take a look at this ?

**Comment by jdavcs** [comment]
It's the wrong script: it should be `sh manage_toolshed_db.sh`. But I'm getting errors in that one - I'm looking into it.

**Comment by jdavcs** [comment]
Oh, I see - the inline comment points at that script. I'll fix it.

**Comment by dannon** [comment]
@jdavcs Thanks!  Glad it was just the instructions that were broken, and not the script.

**Comment by jdavcs** [comment]
It was just the comment. The errors I was seeing were due to my local dev setup (no tool shed database).
