### ISSUE TITLE
Exception: Could not find import model store for directory

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14931]
We have been getting a lot of error reports like:

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 628, in _finish_or_resubmit_job
    job_wrapper.finish(
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1802, in finish
    import_model_store = store.get_import_model_store_for_directory(
  File "/opt/galaxy/server/lib/galaxy/model/store/__init__.py", line 1222, in get_import_model_store_for_directory
    raise Exception(
Exception: Could not find import model store for directory [/data/jwd/main/051/948/51948333/metadata/outputs_populated] (full path [/data/jwd/main/051/948/51948333/metadata/outputs_populated])
```

This seems to be true, but it was not obvious why this has happen

```
galaxy@sn06:~$ ll /data/jwd/main/051/948/51948333/metadata/
total 148
-rw-r--r-- 1 galaxy galaxy     20 Nov  5 08:53 metadata_kwds_tab
-rw-r--r-- 1 galaxy galaxy      0 Nov  5 08:53 metadata_out_tab
-rw-r--r-- 1 galaxy galaxy      2 Nov  5 08:53 metadata_override_tab
-rw-r--r-- 1 galaxy galaxy     41 Nov  5 08:53 metadata_results_tab
-rw-r--r-- 1 galaxy galaxy  10775 Nov  5 08:53 object_store_conf.json
drwxr-xr-x 2 galaxy galaxy   4096 Nov  5 08:53 outputs_new
-rw-r--r-- 1 galaxy galaxy   1910 Nov  5 08:53 params.json
-rw-r--r-- 1 galaxy galaxy 120181 Nov  5 08:53 registry.xml
-rw-r--r-- 1 galaxy galaxy     73 Nov  5 08:53 set.py
```

At first, that seems like a problem with `metadata_strategy: 'extended'` which we have enabled by default. Disabling this revealed a problem with setting metadata in general, which is handled by celery in our setup.

It turned out that a recent Galaxy update has introduced a new dependency that was not synced to the external celery node. So celery was the problem behind this error. Fixing celery and refreshing the venv of celery fixed it.

Not sure if we can improve the initial error message, to direct admins directly to the set_metadata process.

**Comment by bgruening** [comment]
I created this issue to help others that might see similar errors. Nothing really actionable to do here I think, besides maybe improving the error message.

**Comment by mvdbeek** [comment]
That's definitely something to work on though!

**Comment by bgruening** [comment]
We do see this error again. Not sure what we can do this time.

This is also "funny":

![grafik](https://user-images.githubusercontent.com/469983/204998667-4009b146-bc07-40af-b9d4-e7e27c535ec0.png)

I'm not sure what is wrong with celery3 but I restarted it several times and it does not get better.

**Comment by bgruening** [comment]
I will stop that task handler now and see if we still get those error reports.

**Comment by bgruening** [comment]
@gallardoalba for your information.

**Comment by mira-miracoli** [comment]
Now we have many failed jobs on almost all workers, and small (200kb) upload jobs are not finished by celery.
![image](https://user-images.githubusercontent.com/86979912/205280963-c89f93b2-9669-4bc4-b7a0-79adf09aaf28.png)

**Comment by abretaud** [comment]
Hi,
We're having the same kind of traceback for some (17 this month, at least) jobs since a few days (we've switch to "extended" strategy a few weeks/months ago):

While looking at the remaining `metadata/outputs_populated/traceback.txt` files, that's what we see:

one like this:

```
Traceback (most recent call last):
  File "/galaxy/datasets2/jobs/006/597/6597xxx/metadata/set.py", line 5, in <module>
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 153, in set_metadata
    set_metadata_portable()
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 403, in set_metadata_portable
    json.load(open(filename_kwds))
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/galaxy/datasets2/jobs/006/597/6597xxx/metadata/metadata_kwds_output0'
```

another one like that:

```
Traceback (most recent call last):
  File "/galaxy/datasets2/jobs/006/663/6663xxx/metadata/set.py", line 5, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
                                                               ^^^^^^^^^^^^^^
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 153, in set_metadata
    set_metadata_portable()
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 403, in set_metadata_portable
    json.load(open(filename_kwds))
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/galaxy/datasets2/jobs/006/663/6663xxx/metadata/metadata_kwds_annotation_ffn'
```

and the most typical:

```
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 159, in get_metadata_params
    with open(metadata_params_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/galaxy/datasets2/jobs/006/663/6663xxx/metadata/params.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy/datasets2/jobs/006/663/6663xxx/metadata/set.py", line 5, in <module>
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 153, in set_metadata
    set_metadata_portable()
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 186, in set_metadata_portable
    metadata_params = get_metadata_params(tool_job_working_directory)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/galaxy/server/lib/galaxy/metadata/set_metadata.py", line 162, in get_metadata_params
    raise Exception(f"Failed to find metadata/params.json from cwd [{tool_job_working_directory}]")
Exception: Failed to find metadata/params.json from cwd [/galaxy/datasets2/jobs/006/663/6663xxx]
```

Any idea?
