### ISSUE TITLE
bed-to-tabix CONVERTER fails in GUI while tests pass

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#15034]
On usegalaxy.org (but also on my instance which is 21.01), when I run the bed-to-tabix from the graphical interface it fails.

**Galaxy Version and/or server at which you observed the bug**
{"version_major":"22.05","version_minor":"1"}

**To Reproduce**

![Peek 2022-11-19 21-20](https://user-images.githubusercontent.com/30404086/202870249-9a1edb43-f48e-43b1-aaf7-9126775c39f3.gif)

**Expected behavior**
I would expect it to work without needed to rerun it.

**Comment by bernt-matthias** [comment]
Can you check the hidden dataset that is created in the first run of the converter?

Maybe so the same while showing also hidden datasets might be helpful? 

I remember that an implicitly converted dataset is needed.

**Comment by lldelisle** [comment]
The hidden dataset is bgzip.

**Comment by lldelisle** [comment]
On usegalaxy.org ({"version_major":"22.05","version_minor":"1"}), I cannot see the hidden dataset: 
![Peek 2022-11-22 10-21](https://user-images.githubusercontent.com/30404086/203276120-0d438ad4-20cc-4f5e-9e60-782a6ce6dc77.gif)
On my local server ({"version_major": "22.01", "version_minor": "2.dev0"}), I can see the bgzip:
![Peek 2022-11-22 10-22](https://user-images.githubusercontent.com/30404086/203276277-f918aa3f-3d19-4a6d-8abb-111c3ff5d334.gif)

**Comment by mvdbeek** [comment]
I think the issue is that the UI assumes all inputs are named `input`.

**Comment by bernt-matthias** [comment]
> On usegalaxy.org ({"version_major":"22.05","version_minor":"1"}), I cannot see the hidden dataset:

This might be another bug? But I have to admit that for me the new history seems to be take time to get used to. For instance I did not manage to show hidden and non-hidden datasets at the same time. 

[sth.](https://dict.leo.org/englisch-deutsch/sth.) [takes](https://dict.leo.org/englisch-deutsch/takes) ([some](https://dict.leo.org/englisch-deutsch/some)) [getting](https://dict.leo.org/englisch-deutsch/getting) [used](https://dict.leo.org/englisch-deutsch/used) [to](https://dict.leo.org/englisch-deutsch/to)


> On my local server ({"version_major": "22.01", "version_minor": "2.dev0"}), I can see the bgzip:

Is there any related output in the logs ouf your 22.01 instance?

**Comment by lldelisle** [comment]
> I think the issue is that the UI assumes all inputs are named input.
Then why does it works when I rerun it?

**Comment by lldelisle** [comment]
> This might be another bug? But I have to admit that for me the new history seems to be take time to get used to. For instance I did not manage to show hidden and non-hidden datasets at the same time.

Me too...

> Is there any related output in the logs ouf your 22.01 instance?

So the 326453 corresponds to the bed to bgzip convertion which works.
and 326454 corresponds to the bed + bgzip to tabix which fails.
Knowing that input1 is defined here: https://github.com/galaxyproject/galaxy/blob/dd656aa3b36169209463fe8277817498d37c9d18/lib/galaxy/datatypes/converters/interval_to_tabix_converter.xml#L19

```
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.mapper DEBUG 2022-11-23 09:17:51,514 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] (99339) Mapped job to destination id: slurm
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.handler DEBUG 2022-11-23 09:17:51,524 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] (99339) Dispatching to slurm runner
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs DEBUG 2022-11-23 09:17:51,573 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] (99339) Persisting job destination (destination id: slurm)
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs DEBUG 2022-11-23 09:17:51,582 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] (99339) Working directory for job is: /data/galaxy/galaxy/jobs/099/99339
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.runners DEBUG 2022-11-23 09:17:51,598 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] Job [99339] queued (73.400 ms)
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.handler INFO 2022-11-23 09:17:51,603 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:JobHandlerQueue.monitor_thread] (99339) Job dispatched
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs DEBUG 2022-11-23 09:17:51,702 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] Job wrapper for Job [99339] prepared (80.065 ms)
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.tool_util.deps DEBUG 2022-11-23 09:17:51,703 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] Using dependency pysam version 0.15.4 of type conda
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.tool_util.deps DEBUG 2022-11-23 09:17:51,703 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] Using dependency coreutils version 8.25 of type conda
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.command_factory INFO 2022-11-23 09:17:51,781 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] Built script [/data/galaxy/galaxy/jobs/099/99339/tool_script.sh] for tool command [[ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-84cc2ce2902d7d17777c72459b5c4a6bf0f835d486c4a85a156c23c6a1bac4b0')" ] || {
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: MAX_TRIES=3
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: COUNT=0
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: while [ $COUNT -lt $MAX_TRIES ]; do
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     . '/data/galaxy/galaxy/var/dependencies/_conda/bin/activate' '/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-84cc2ce2902d7d17777c72459b5c4a6bf0f835d486c4a85a156c23c6a1bac4b0' > conda_activate.log 2>&1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     if [ $? -eq 0 ];then
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         break
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     else
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         let COUNT=COUNT+1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         if [ $COUNT -eq $MAX_TRIES ];then
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             echo "Failed to activate conda environment! Error was:"
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             cat conda_activate.log
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             exit 1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         fi
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         sleep 10s
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     fi
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: done
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: } ; [ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-84cc2ce2902d7d17777c72459b5c4a6bf0f835d486c4a85a156c23c6a1bac4b0')" ] || {
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: MAX_TRIES=3
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: COUNT=0
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: while [ $COUNT -lt $MAX_TRIES ]; do
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     . '/data/galaxy/galaxy/var/dependencies/_conda/bin/activate' '/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-84cc2ce2902d7d17777c72459b5c4a6bf0f835d486c4a85a156c23c6a1bac4b0' > conda_activate.log 2>&1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     if [ $? -eq 0 ];then
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         break
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     else
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         let COUNT=COUNT+1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         if [ $COUNT -eq $MAX_TRIES ];then
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             echo "Failed to activate conda environment! Error was:"
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             cat conda_activate.log
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:             exit 1
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         fi
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:         sleep 10s
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     fi
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: done
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: } ; python '/data/galaxy/galaxy/server/lib/galaxy/datatypes/converters/bgzip.py' -P bed '/data/galaxy/data/000/356/dataset_356469.dat' '/data/galaxy/data/000/356/dataset_356470.dat']
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.runners DEBUG 2022-11-23 09:17:51,833 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] (99339) command is: mkdir -p working outputs configs
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: if [ -d _working ]; then
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: else
Nov 23 09:17:51 updubsrv1 uwsgi[326453]:     cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: fi
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: cd working; /bin/bash /data/galaxy/galaxy/jobs/099/99339/tool_script.sh > '../outputs/tool_stdout' 2> '../outputs/tool_stderr'; return_code=$?; echo $return_code > /data/galaxy/galaxy/jobs/099/99339/galaxy_99339.ec; cd '/data/galaxy/galaxy/jobs/099/99339';
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: [ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: python "metadata/set.py"; sh -c "exit $return_code"
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.runners.drmaa DEBUG 2022-11-23 09:17:51,910 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] (99339) submitting file /data/galaxy/galaxy/jobs/099/99339/galaxy_99339.sh
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.runners.drmaa DEBUG 2022-11-23 09:17:51,911 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] (99339) native specification is: --nodes=1 --ntasks=1 --cpus-per-task=1 --mem=4000
Nov 23 09:17:51 updubsrv1 uwsgi[326453]: galaxy.jobs.runners.drmaa INFO 2022-11-23 09:17:51,914 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] (99339) queued as 23261
Nov 23 09:17:52 updubsrv1 uwsgi[326453]: galaxy.jobs.runners.drmaa DEBUG 2022-11-23 09:17:52,714 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.monitor_thread] (99339/23261) state change: job is running
Nov 23 09:17:54 updubsrv1 uwsgi[326450]: 128.178.187.187 - - [23/Nov/2022:09:17:54 +0200] "GET /api/histories/2900d6bf7c76e821/contents?details=3b97ebd1799bfd28%2C957bc09afef04004%2C9d5129546609cfe3%2Cc23e975950f15d12%2C0c0cdaca1a012dca%2Cd5cf48cdc27dffc9%2C3ce75757124de28f%2C882837c1dbf96a3a%2C3bcd53edd3200503%2C8550be1e7c99c55d%2C989b0aa531024c8e%2Cf55b7766c19b6eb0%2C8937f26bbb9cca62%2C6578d3f7cfd94fc6%2Cb2bb9015417e9f3a%2Cc49d69097da5a264&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-11-23T08%3A17%3A49.000Z&qv=False&qv=False HTTP/1.1" 200 - "https://galaxyduboule.epfl.ch/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
Nov 23 09:17:54 updubsrv1 uwsgi[326450]: [pid: 326450|app: 0|req: 97271/97271] 128.178.187.187 () {56 vars in 2288 bytes} [Wed Nov 23 09:17:54 2022] GET /api/histories/2900d6bf7c76e821/contents?details=3b97ebd1799bfd28%2C957bc09afef04004%2C9d5129546609cfe3%2Cc23e975950f15d12%2C0c0cdaca1a012dca%2Cd5cf48cdc27dffc9%2C3ce75757124de28f%2C882837c1dbf96a3a%2C3bcd53edd3200503%2C8550be1e7c99c55d%2C989b0aa531024c8e%2Cf55b7766c19b6eb0%2C8937f26bbb9cca62%2C6578d3f7cfd94fc6%2Cb2bb9015417e9f3a%2Cc49d69097da5a264&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-11-23T08%3A17%3A49.000Z&qv=False&qv=False => generated 2 bytes in 23 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
Nov 23 09:17:55 updubsrv1 uwsgi[326450]: 128.179.253.122 - - [23/Nov/2022:09:17:55 +0200] "GET /api/histories/b1fadac6e0636245/contents?details=607767a751ccb689&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-11-23T08%3A17%3A51.061Z&qv=False&qv=False HTTP/1.1" 200 - "https://galaxyduboule.epfl.ch/datasets/edit" "Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0"
Nov 23 09:17:55 updubsrv1 uwsgi[326450]: [pid: 326450|app: 0|req: 97272/97272] 128.179.253.122 () {54 vars in 1284 bytes} [Wed Nov 23 09:17:55 2022] GET /api/histories/b1fadac6e0636245/contents?details=607767a751ccb689&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2022-11-23T08%3A17%3A51.061Z&qv=False&qv=False => generated 493 bytes in 29 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
Nov 23 09:17:57 updubsrv1 uwsgi[326453]: galaxy.jobs.runners.drmaa DEBUG 2022-11-23 09:17:57,863 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.monitor_thread] (99339/23261) state change: job finished normally
Nov 23 09:17:57 updubsrv1 uwsgi[326453]: galaxy.model.metadata DEBUG 2022-11-23 09:17:57,954 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] loading metadata from file for: HistoryDatasetAssociation 346945
Nov 23 09:17:58 updubsrv1 uwsgi[326453]: galaxy.jobs INFO 2022-11-23 09:17:58,004 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] Collecting metrics for Job 99339 in /data/galaxy/galaxy/jobs/099/99339
Nov 23 09:17:58 updubsrv1 uwsgi[326453]: galaxy.jobs DEBUG 2022-11-23 09:17:58,021 [pN:main.job-handlers.1,p:326453,w:0,m:1,tN:SlurmRunner.work_thread-0] job_wrapper.finish for job 99339 executed (98.921 ms)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs.mapper DEBUG 2022-11-23 09:17:58,252 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] (99340) Mapped job to destination id: slurm
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs.handler DEBUG 2022-11-23 09:17:58,268 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] (99340) Dispatching to slurm runner
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs DEBUG 2022-11-23 09:17:58,316 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] (99340) Persisting job destination (destination id: slurm)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs DEBUG 2022-11-23 09:17:58,325 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] (99340) Working directory for job is: /data/galaxy/galaxy/jobs/099/99340
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs.runners DEBUG 2022-11-23 09:17:58,348 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] Job [99340] queued (80.128 ms)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs.handler INFO 2022-11-23 09:17:58,354 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:JobHandlerQueue.monitor_thread] (99340) Job dispatched
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.jobs.runners ERROR 2022-11-23 09:17:58,388 [pN:main.job-handlers.2,p:326454,w:0,m:2,tN:SlurmRunner.work_thread-2] (99340) Failure preparing job
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: Traceback (most recent call last):
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 248, in prepare_job
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     job_wrapper.prepare()
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/jobs/__init__.py", line 1201, in prepare
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/tools/evaluation.py", line 115, in set_compute_environment
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     visit_input_values(self.tool.inputs, incoming, validate_inputs)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 176, in visit_input_values
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 137, in callback_helper
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     new_value = callback(**args)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/tools/evaluation.py", line 113, in validate_inputs
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     value = input.from_json(value, request_context, context)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:   File "/data/galaxy/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 1933, in from_json
Nov 23 09:17:58 updubsrv1 uwsgi[326454]:     raise ParameterValueError("specify a dataset of the required format / build for parameter", self.name)
Nov 23 09:17:58 updubsrv1 uwsgi[326454]: galaxy.tools.parameters.basic.ParameterValueError: parameter 'input1': specify a dataset of the required format / build for parameter

```

**Comment by mvdbeek** [comment]
> Then why does it works when I rerun it?

Because you open the real tool form, not the converter UI.

**Comment by lldelisle** [comment]
Ahh
