### ISSUE TITLE
Flakey integration tests

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15112]
- [x] test/integration/test_containerized_jobs.py::TestDockerizedJobsIntegration::test_build_mulled https://github.com/galaxyproject/galaxy/actions/runs/3622830176/jobs/6108000537

```
Executing: '/home/runner/work/galaxy/galaxy/galaxy root/involucro' -v=3 -f '/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/mulled/invfile.lua' -set CHANNELS=conda-forge,bioconda -set TARGETS=samtools=1.3.1,bedtools=2.26.0 -set REPO=quay.io/local/mulled-v2-8186960447c5cb2faa697666dc1e6d919ad23f3e:a6419f25efff953fc505dbd5ee734856180bb619-0 -set BINDS=build/dist:/usr/local/ -set DEST_BASE_IMAGE=quay.io/bioconda/base-glibc-busybox-bash:latest -set TEST=true build-and-test
.
galaxy.web.framework.decorators ERROR 2022-12-05 18:44:40,147 [pN:main,p:7716,tN:WSGI_2] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/web/framework/decorators.py", line 337, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/web/framework/decorators.py", line 113, in decorator
    return func(self, trans, *args, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/tool_dependencies.py", line 260, in toolbox_install
    [self._view.install_dependencies(requirements=r, index=index, **install_kwds) for r in requirements]
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/tool_dependencies.py", line 260, in <listcomp>
    [self._view.install_dependencies(requirements=r, index=index, **install_kwds) for r in requirements]
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/views.py", line 125, in install_dependencies
    return self._dependency_manager._requirements_to_dependencies_dict(requirements, **kwds)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/__init__.py", line 288, in _requirements_to_dependencies_dict
    **kwds,
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 675, in resolve
    mull_targets(targets, involucro_context=self._get_involucro_context(), **self._mulled_kwds)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 318, in mull_targets
    ret = involucro_context.exec_command(involucro_args)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 385, in exec_command
    res = self.shell_exec(cmd)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/util/commands.py", line 62, in shell
    p = shell_process(cmds, env, **kwds)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/util/commands.py", line 94, in shell_process
    p = subprocess.Popen(cmds, **popen_kwds)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/runner/work/galaxy/galaxy/galaxy root/involucro'
INFO:     127.0.0.1:56574 - "POST /api/dependency_resolvers/toolbox/install HTTP/1.1" 500 Internal Server Error
```
That's a pretty strange one to be flaky ...

**Comment by nsoranzo** [comment]
I think this may due to where the `involucro` file is created, which shouldn't be the Galaxy root, so multiple tests may try to access this file.
