### ISSUE TITLE
no set_random_password in User when new user logging in to local toolshed

### ISSUE THREAD

**Issue by crutching** [galaxyproject/galaxy#15278]
I am working in v21.05.  New user is logging in to our local toolshed, below error occurs.  Authentication seems to work, though LDAP username is listed as None.  Quick fix is to add the set_random_password code to `lib/tool_shed/webapp/model/__init__.py`, this fixes the issue and allows user to get in.  Upon adding this code, LDAP username is listed correctly as "myuser" in logs.

```
galaxy.webapps.galaxy.controllers.user DEBUG 2023-01-03 15:35:04,935 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] trans.app.config.auth_config_file: /galaxy/config/auth_conf.xml
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,935 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: email is myuser@work.edu
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,936 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: username is None
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,936 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: options are {'allow-register': 'False', 'auto-register': 'True', 'allow-password-change': 'False', 'server': 'ldap://myldap.work.edu', 'login-use-username': 'False', 'continue-on-failure': 'False', 'search-fields': 'uid,mail', 'search-base': 'dc=acc,dc=work,dc=edu', 'search-filter': '(mail={email})', 'bind-user': '{dn}', 'bind-password': '{password}', 'auto-register-username': '{uid}', 'auto-register-email': '{mail}', 'redact_username_in_logs': False, 'no_password_check': False}
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,947 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: dn is uid=myuser,ou=Users,dc=blah,dc=work,dc=edu
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,947 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: search attributes are {'uid': [b'myuser'], 'mail': [b'myuser@work.edu']}
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,963 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authenticate: whoami is dn:uid=myuser,ou=Users,dc=blah,dc=work,dc=edu
galaxy.auth.providers.ldap_ad DEBUG 2023-01-03 15:35:04,963 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] LDAP authentication successful
galaxy.auth.util DEBUG 2023-01-03 15:35:04,966 [pN:main,p:50528,w:1,m:0,tN:uWSGIWorker1Core2] Email: myuser@work.edu, auto-register with username: myuser
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/galaxy/.venv/lib/python3.6/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/galaxy/.venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/galaxy/.venv/lib/python3.6/site-packages/routes/middleware.py", line 153, in __call__
    response = self.app(environ, start_response)
  File "/galaxy/.venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
  File "lib/tool_shed/webapp/controllers/user.py", line 68, in login
    response = self.__validate_login(trans, **kwd)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 139, in __validate_login
    message, user = self.__autoregistration(trans, login, password)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 97, in __autoregistration
    user = self.user_manager.create(email=email, username=username, password="")
  File "lib/galaxy/managers/users.py", line 116, in create
    user.set_random_password()
AttributeError: 'User' object has no attribute 'set_random_password'
```

**Comment by nsoranzo** [comment]
> Quick fix is to add the set_random_password code to lib/tool_shed/webapp/model/__init__.py, this fixes the issue and allows user to get in.

@jhl667 This seems a reasonable fix for me, would you mind opening a Pull Request please?
