### ISSUE TITLE
Error when running dataset cleanup file pgcleanup.py 

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#15306]
**Describe the bug**
Dataset delete script `pgcleanup.py` is throwing an error when run from another location than
`../server`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
Nicola Soranzo could not repoduce it.

**Expected behavior**
I am running a script (pgcleanup.py) and expect to get a log to stderr. I get an error instead unless the script is run from a location different than _{{ galaxy_root }}/server_

**Screenshots**
See Additional context below

**Additional context**

My setup:

- GALAXY_CONFIG_FILE=/cluster/galaxy/srv/galaxy/config/galaxy.yml
- ANSIBLE group_vars/<galaxy_vars_file> relevant lines:

    galaxy_root: /cluster/galaxy/srv/galaxy
    galaxy_server_dir: "{{ galaxy_root }}/server"

Results:

1. FROM `/cluster/galaxy/srv/galaxy/server`
```
(venv) [ec-galaxy@galaxy01 server]$ ./scripts/cleanup_datasets/pgcleanup.py -o 60 --dry-run -d --config-file=$GALAXY_CONFIG_FILE delete_datasets

==== Log opened: 2023-01-13T15:30:11.216309 ============================
Epoch time for this action: 1673620211
id: 130
==== Log closed: 2023-01-13T15:30:11.216437 ============================
```

2. FROM _galaxy_root directory_ : `/cluster/galaxy/srv/galaxy`
```
venv) [ec-galaxy@galaxy01 galaxy]$ ./server/scripts/cleanup_datasets/pgcleanup.py -o 60 --dry-run -d --config-file=$GALAXY_CONFIG_FILE delete_datasets
2023-01-13 15:37:54,800 DEBUG _set_config_directories(): Configuration directory is /cluster/galaxy/srv/galaxy/config
2023-01-13 15:37:54,801 DEBUG _set_config_directories(): Data directory is /cluster/galaxy/srv/galaxy/var
2023-01-13 15:37:54,801 DEBUG _set_config_directories(): Managed config directory is /cluster/galaxy/srv/galaxy/var/config
Traceback (most recent call last):
  File "./server/scripts/cleanup_datasets/pgcleanup.py", line 1319, in <module>
    with Cleanup() as app:
  File "./server/scripts/cleanup_datasets/pgcleanup.py", line 1121, in __init__
    self.__load_config()
  File "./server/scripts/cleanup_datasets/pgcleanup.py", line 1234, in __load_config
    self.config = galaxy.config.Configuration(**app_properties)
  File "/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/__init__.py", line 551, in __init__
    super().__init__(**kwargs)
  File "/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/__init__.py", line 130, in __init__
    self.schema = self._load_schema()  # Load schema from schema definition file
  File "/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/__init__.py", line 560, in _load_schema
    return AppSchema(config_schema_path, GALAXY_APP_NAME)
  File "/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/schema.py", line 41, in __init__
    self.raw_schema = self._read_schema(schema_path)
  File "/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/schema.py", line 48, in _read_schema
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/cluster/galaxy/srv/galaxy/server/lib/galaxy/config/../config_schema.yml'
```

3. FROM 
    _{{ galaxy_root }}/server/scripts_
    _{{ galaxy_root }}/server/scripts/cleanup_datasets_

Same error as in p.2

SOME HINTS FOR DEBUGGING:

The error (DEBUG) says:
```
2023-01-13 15:37:54,801 DEBUG _set_config_directories(): Data directory is /cluster/galaxy/srv/galaxy/var
```
yet my data directory is (as defined by ANSIBLE group_vars/<galaxy_vars_file>):
```
galaxy_lifeportal_data_dir: /cluster/galaxy/data
```

I can provide the entire _group_vars/<galaxy_vars_file>_ if this might be of some help.

**Comment by mvdbeek** [comment]
It's quite likely that most scripts in the scripts directory assume to run from galaxy's root directory in some way or another, a fix would be nice of course.

**Comment by vazovn** [comment]
@mvdbeek Exactly, it is not running from the root directory :)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15222
