### ISSUE TITLE
Post Job Action Problem Encountered on Main

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1531]
```
job traceback:
Traceback (most recent call last):
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/runners/__init__.py", line 590, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/__init__.py", line 1275, in finish
    ActionBox.execute(self.app, self.sa_session, pja.post_job_action, job)
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/actions/post.py", line 548, in execute
    ActionBox.actions[pja.action_type].execute(app, sa_session, pja, job, replacement_dict)
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/actions/post.py", line 421, in execute
    for input_dataset in [x.dataset for x in j2c.input_datasets if x.dataset.creating_job.workflow_invocation_step and x.dataset.creating_job.workflow_invocation_step.workflow_invocation == wfi]:
AttributeError: 'NoneType' object has no attribute 'creating_job'
```

Possibly related to tool optimizations, x.dataset used to exist at this point in the code and no longer does?

**Comment by dannon** [comment]
@jmchilton Your guess sounds pretty good to me.
