### ISSUE TITLE
Startup with `install_involucro` requires curl

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15355]
```
Traceback (most recent call last):
  File "/srv/galaxy/server/lib/galaxy/webapps/galaxy/buildapp.py", line 59, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/srv/galaxy/server/lib/galaxy/app.py", line 652, in __init__
    self._configure_toolbox()
  File "/srv/galaxy/server/lib/galaxy/app.py", line 330, in _configure_toolbox
    self.container_finder = containers.ContainerFinder(app_info, mulled_resolution_cache=mulled_resolution_cache)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 60, in __init__
    self.default_container_registry = ContainerRegistry(app_info, mulled_resolution_cache=mulled_resolution_cache)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 245, in __init__
    self.container_resolvers = self.__build_container_resolvers(app_info, destination_info)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 270, in __build_container_resolvers
    return self.__default_container_resolvers()
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/containers.py", line 294, in __default_container_resolvers
    build_mulled_docker_container_resolver = BuildMulledDockerContainerResolver(self.app_info)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 677, in __init__
    self.enabled = ensure_installed(self.involucro_context, auto_init)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 425, in ensure_installed
    return installable.ensure_installed(involucro_context, install_involucro, auto_init)
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/installable.py", line 68, in ensure_installed
    return _check()
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/installable.py", line 46, in _check
    if install_func(installable_context):
  File "/srv/galaxy/server/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 432, in install_involucro
    exit_code = involucro_context.shell_exec(download_cmd)
  File "/srv/galaxy/server/lib/galaxy/util/commands.py", line 62, in shell
    p = shell_process(cmds, env, **kwds)
  File "/srv/galaxy/server/lib/galaxy/util/commands.py", line 94, in shell_process
    p = subprocess.Popen(cmds, **popen_kwds)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'curl'
root@galaxy-scenario-default:/srv/galaxy/var/log# cat gunicorn.log
```
found in https://github.com/galaxyproject/ansible-galaxy/pull/178

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15356
