### ISSUE TITLE
Filter history inputs and outputs server error

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15514]
**Describe the bug**
Relates #15210. Filtering some history items' inputs and outputs returns a 500 error and not showing the filtered item itself.

https://user-images.githubusercontent.com/8046843/217040945-590716ca-5246-401d-8437-58b6dbc62819.mp4

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org (v23.0.rc1)

**To Reproduce**
1. Run the `fastqc` tool from the link below using the default preferences on a fastq file.
https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.73+galaxy0

**Expected behavior**
Show the filtered item (or explain why it's not visible)

**Comment by mvdbeek** [comment]
Can you paste the server logs ?

**Comment by mvdbeek** [comment]
Sorry, didn't see the usegalaxy.org

**Comment by mvdbeek** [comment]
Can you tell us how to reproduce this ? It does seem to work for me.

**Comment by itisAliRH** [comment]
> Can you tell us how to reproduce this ? It does seem to work for me.

You can reprodece it by running the `fastqc` tool from link below using the default prefrences on a fastq file. @mvdbeek 
https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.73+galaxy0

**Comment by mvdbeek** [comment]
Thanks! @ahmedhamidawan do you have some time to look into this?
You can reproduce this locally, this is the traceback:

```
INFO:     127.0.0.1:58156 - "GET /api/histories/b1ae48129af9af59/contents?v=dev&order=hid&offset=0&limit=100&q=related-eq&qv=340&q=deleted&qv=false&q=visible&qv=true HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette_context/middleware/raw_middleware.py", line 93, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/fast_app.py", line 103, in add_x_frame_options
    response = await call_next(request)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/api/history_contents.py", line 346, in index
    items = self.service.index(
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/services/history_contents.py", line 301, in index
    return self.__index_v2(trans, history_id, params, serialization_params, filter_query_params, accept)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/services/history_contents.py", line 943, in __index_v2
    filters = self.history_contents_filters.parse_query_filters_with_relations(filter_query_params, history_id)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/history_contents.py", line 544, in parse_query_filters_with_relations
    related = job_connections_manager.get_related_hids(history_id, qv_hid)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/job_connections.py", line 57, in get_related_hids
    result.append(item.hid)
AttributeError: 'NoneType' object has no attribute 'hid'
```

I think the critical thing here is that 3 of the 4 inputs are optional, so the JobToInputDatasetAssociation has `None` as the dataset_id.

**Comment by ahmedhamidawan** [comment]
@mvdbeek Yes, i can take a look. Just wondering, a fix could be to not include any value from `JobToInputDatasetAssociation` that has `dataset_id` as None, which would mean we would not show those datasets in the related items?

**Comment by mvdbeek** [comment]
Yes, these are optional datasets that were not provided.
