### ISSUE TITLE
tool entry point is polled also for anonymous/sessionless users

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15555]
```
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: Traceback (most recent call last):
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/web/framework/decorators.py", line 337, in decorator
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: rval = func(self, trans, *args, **kwargs)
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/webapps/galaxy/api/tool_entry_points.py", line 59, in index
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: entry_points = self.interactivetool_manager.get_nonterminal_for_user_by_trans(trans)
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/managers/interactivetool.py", line 218, in get_nonterminal_for_user_by_trans
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: trans.app.model.Job.session_id == trans.get_galaxy_session().id
Feb 10 09:31:53 galaxy-web-06.tacc.utexas.edu galaxyctl[86581]: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by martenson** [comment]
Anonymous users can run ITs so polling for them is expected and in my testing works well. #15659 will address the case where there is no user and no galaxy session.

However we shouldn't poll if the instance has ITs disabled...
