### ISSUE TITLE
dependencies installation ModuleNotFoundError

### ISSUE THREAD

**Issue by jundahuang9123** [galaxyproject/galaxy#15567]
Hi, while trying to install galaxy, the dependencies cannot be installed. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/workdir/TWOC/galaxy_demo/galaxy/lib/galaxy/dependencies/__init__.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

if i remove the import yaml line then:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/workdir/TWOC/galaxy_demo/galaxy/lib/galaxy/dependencies/__init__.py", line 16, in <module>
    from galaxy.util import (
  File "/mnt/data/workdir/TWOC/galaxy_demo/galaxy/lib/galaxy/util/__init__.py", line 47, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Not sure if I messed up the environment somehow?

**Comment by mvdbeek** [comment]
That appears to be the case. For help you can ask this question, including details on how you've set up galaxy and what you've tried so far at https://help.galaxyproject.org/
