### ISSUE TITLE
common-workflow-language cwltool does not support Python 2.6

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1571]
Summary: Galaxy still supports Python 2.6, but common-workflow-language cwltool requires Python 2.7

The following is a Galaxy tool test failure under Python 2.6.9 with the current galaxy dev branch:
https://travis-ci.org/peterjc/galaxy_blast/jobs/104093742

```
$  python ./scripts/functional_tests.py -v `python tool_list.py Continuous-Integration-Travis`
python ./scripts/functional_tests.py -v `python tool_list.py Continuous-Integration-Travis`
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 30, in <module>
    from galaxy.app import UniverseApplication
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/app.py", line 15, in <module>
    from galaxy.visualization.plugins.registry import VisualizationsRegistry
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/visualization/plugins/registry.py", line 15, in <module>
    from galaxy.visualization.plugins import plugin as vis_plugins
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/visualization/plugins/plugin.py", line 13, in <module>
    from galaxy.web.base import interactive_environments
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/base/interactive_environments.py", line 13, in <module>
    from galaxy.tools.deps.docker_util import DockerVolume
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/__init__.py", line 26, in <module>
    from galaxy.tools.actions import DefaultToolAction
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/actions/__init__.py", line 7, in <module>
    from galaxy.tools.parameters.basic import DataCollectionToolParameter, DataToolParameter
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 5, in <module>
    from basic import DataCollectionToolParameter, DataToolParameter, SelectToolParameter
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 18, in <module>
    import galaxy.tools.parser
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/__init__.py", line 4, in <module>
    from .factory import get_tool_source
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/factory.py", line 8, in <module>
    from .cwl import CwlToolSource
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/parser/cwl.py", line 14, in <module>
    from galaxy.tools.cwl import tool_proxy
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/__init__.py", line 1, in <module>
    from .parser import tool_proxy
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/parser.py", line 12, in <module>
    from .cwltool_deps import (
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/tools/cwl/cwltool_deps.py", line 11, in <module>
    from cwltool import (
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cwltool/main.py", line 382
    job_order_object.update({namemap[k]: v for k,v in cmd_line.items()})
                                             ^
SyntaxError: invalid syntax
```

Here Galaxy is to attempting to import https://github.com/common-workflow-language/cwltool/blob/master/cwltool/main.py which uses a set comprehension, and is thus not valid Python 2.6 syntax.

Presumably a recent change on Galaxy's dev branch has added a dependency on cwltool?

**Comment by jmchilton** [comment]
Before anyone panics, Galaxy does not have a dependency on cwltool. planemo has the dependency though and you run Galaxy's common_startup.sh with `--skip-venv`, I'll need to look at this more but you can't run Galaxy inside of planemo's virtualenv for other reasons also (e.g. galaxy-lib).

**Comment by peterjc** [comment]
Thanks John - should we move this to a planemo issue?

**Comment by jmchilton** [comment]
Yeah - lets move it. You can recreate an issue of there if you want or we can discuss things on the following planemo PR:

https://github.com/galaxyproject/planemo/pull/405

**Comment by peterjc** [comment]
See also issue https://github.com/galaxyproject/planemo/issues/411 as well as pull request https://github.com/galaxyproject/planemo/pull/405
