### ISSUE TITLE
Galaxy doesn't start after upgrade from release_15.7 to release_15.10

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1593]
Hello,
After I've merged to release_15.10 using git, run.sh and manage_db.sh showed the following error:

-bash-3.2$ sh manage_db.sh upgrade
Traceback (most recent call last):
  File "./scripts/manage_db.py", line 33, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 30, in invoke_migrate_main
    main( repository=repo, url=db_url )
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/shell.py", line 209, in main
    ret = command_func(*_kwargs)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, *_opts)
  File "<string>", line 2, in _migrate
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(_a, *_kw)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 342, in _migrate
    schema = ControlledSchema(engine, repository)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 45, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 416, in **new**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in **exit**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 411, in **new**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 484, in _init
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 508, in _autoload
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1972, in run_callable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1477, in run_callable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 364, in reflecttable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 582, in reflecttable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 712, in _reflect_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 481, in get_indexes
  File "<string>", line 2, in get_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 54, in cache
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/base.py", line 2701, in get_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
migrate.exceptions.DatabaseNotControlledError: (psycopg2.ProgrammingError) column i.reloptions does not exist
 [SQL: "\n              SELECT\n                  i.relname as relname,\n                  ix.indisunique, ix.indexprs, ix.indpred,\n                  a.attname, a.attnum, NULL, ix.indkey,\n                  i.reloptions, am.amname\n              FROM\n                  pg_class t\n                        join pg_index ix on t.oid = ix.indrelid\n                        join pg_class i on i.oid = ix.indexrelid\n                        left outer join\n                            pg_attribute a\n                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)\n                        left outer join\n                            pg_am am\n                            on i.relam = am.oid\n              WHERE\n                  t.relkind IN ('r', 'v', 'f', 'm')\n                  and t.oid = %(table_oid)s\n                  and ix.indisprimary = 'f'\n              ORDER BY\n                  t.relname,\n                  i.relname\n            "] [parameters: {'table_oid': 20606}]

-bash-3.2$ ./run.sh 
python path is: /home/galaxy/eggs/Babel-1.3-py2.7.egg, /home/galaxy/eggs/pytz-2013.9-py2.7.egg, /home/galaxy/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/Mako-0.4.1-py2.7.egg, /home/galaxy/eggs/kombu-3.0.30-py2.7.egg, /home/galaxy/eggs/anyjson-0.3.3-py2.7.egg, /home/galaxy/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/WebHelpers-1.3-py2.7.egg, /home/galaxy/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/WebOb-0.8.5-py2.7.egg, /home/galaxy/eggs/Routes-2.1-py2.7.egg, /home/galaxy/eggs/repoze.lru-0.6-py2.7.egg, /home/galaxy/eggs/amqp-1.4.8-py2.7.egg, /home/galaxy/eggs/wchartype-0.1-py2.7.egg, /home/galaxy/eggs/docutils-0.7-py2.7.egg, /home/galaxy/eggs/PasteDeploy-1.5.0-py2.7.egg, /home/galaxy/eggs/Paste-1.7.5.1-py2.7.egg, /home/galaxy/lib, /usr/lib64/python27.zip, /usr/lib64/python2.7, /usr/lib64/python2.7/plat-linux2, /usr/lib64/python2.7/lib-tk, /usr/lib64/python2.7/lib-old, /usr/lib64/python2.7/lib-dynload, /usr/lib64/python2.7/site-packages, /usr/lib/python2.7/site-packages, /cluster/sw/lib/python2.7/site-packages, /cluster/sw/lib64/python2.7/site-packages
galaxy.queue_worker INFO 2016-01-26 19:25:45,633 Initalizing main Galaxy Queue Worker on sqlalchemy+postgresql://galaxy:********@localhost/galaxydb
galaxy.eggs WARNING 2016-01-26 19:25:45,953 Warning: pbr (a dependent egg of sqlalchemy-migrate) cannot be fetched
Traceback (most recent call last):
...

Thanks,
Justin

**Comment by natefoo** [comment]
Hi Justin,

If you move/remove `/home/galaxy/eggs`, does this fix the problem?

**Comment by methylome** [comment]
Hi,
No it doesn't.

-bash-3.2$ ./run.sh
Initializing tool-data/shared/ucsc/manual_builds.txt from manual_builds.txt.sample
Some eggs are out of date, attempting to fetch...
Fetched http://eggs.galaxyproject.org/Mako/Mako-0.4.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/repoze.lru/repoze.lru-0.6-py2.7.egg
Fetched http://eggs.galaxyproject.org/pysam/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/ordereddict/ordereddict-1.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/Fabric/Fabric-1.7.0-py2.7.egg
Fetched http://eggs.galaxyproject.org/Babel/Babel-1.3-py2.7.egg
Fetched http://eggs.galaxyproject.org/Whoosh/Whoosh-2.4.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/Parsley/Parsley-1.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/Cheetah/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/paramiko/paramiko-1.11.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/lrucache/lrucache-0.2-py2.7.egg
Fetched http://eggs.galaxyproject.org/sqlalchemy_migrate/sqlalchemy_migrate-0.9.6-py2.7.egg
Fetched http://eggs.galaxyproject.org/NoseHTML/NoseHTML-0.4.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/pexpect/pexpect-2.4-py2.7.egg
Fetched http://eggs.galaxyproject.org/amqp/amqp-1.4.8-py2.7.egg
Fetched http://eggs.galaxyproject.org/psycopg2/psycopg2-2.5.1_9.2.4_static-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/bx_python/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/PasteDeploy/PasteDeploy-1.5.0-py2.7.egg
Fetched http://eggs.galaxyproject.org/WebHelpers/WebHelpers-1.3-py2.7.egg
Fetched http://eggs.galaxyproject.org/bioblend/bioblend-0.5.2-py2.7.egg
Fetched http://eggs.galaxyproject.org/docutils/docutils-0.7-py2.7.egg
Fetched http://eggs.galaxyproject.org/kombu/kombu-3.0.30-py2.7.egg
Fetched http://eggs.galaxyproject.org/numpy/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/mock/mock-1.0.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/raven/raven-3.1.8-py2.7.egg
Fetched http://eggs.galaxyproject.org/Beaker/Beaker-1.4-py2.7.egg
Fetched http://eggs.galaxyproject.org/PyYAML/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/SQLAlchemy/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/simplejson/simplejson-2.1.1-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/sqlparse/sqlparse-0.1.14-py2.7.egg
Fetched http://eggs.galaxyproject.org/NoseTestDiff/NoseTestDiff-0.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/poster/poster-0.8.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/python_lzo/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/wchartype/wchartype-0.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/Tempita/Tempita-0.5.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/MarkupSafe/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/ssh/ssh-1.7.14-py2.7.egg
Fetched http://eggs.galaxyproject.org/Routes/Routes-2.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/six/six-1.9.0-py2.7.egg
Fetched http://eggs.galaxyproject.org/decorator/decorator-3.1.2-py2.7.egg
Fetched http://eggs.galaxyproject.org/importlib/importlib-1.0.3-py2.7.egg
Fetched http://eggs.galaxyproject.org/WebOb/WebOb-0.8.5-py2.7.egg
Fetched http://eggs.galaxyproject.org/pycrypto/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/boto/boto-2.27.0-py2.7.egg
Fetched http://eggs.galaxyproject.org/Paste/Paste-1.7.5.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/python_daemon/python_daemon-1.5.5-py2.7.egg
Fetched http://eggs.galaxyproject.org/mercurial/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg
Fetched http://eggs.galaxyproject.org/wsgiref/wsgiref-0.1.2-py2.7.egg
Fetched http://eggs.galaxyproject.org/SVGFig/SVGFig-1.1.6-py2.7.egg
Fetched http://eggs.galaxyproject.org/pytz/pytz-2013.9-py2.7.egg
Fetched http://eggs.galaxyproject.org/nose/nose-1.3.6-py2.7.egg
Fetched http://eggs.galaxyproject.org/requests/requests-2.2.1-py2.7.egg
Fetched http://eggs.galaxyproject.org/anyjson/anyjson-0.3.3-py2.7.egg
Fetched http://eggs.galaxyproject.org/WebError/WebError-0.8a-py2.7.egg
Fetched http://eggs.galaxyproject.org/twill/twill-0.9-py2.7.egg
Fetch successful.
python path is: /home/galaxy/eggs/Babel-1.3-py2.7.egg, /home/galaxy/eggs/pytz-2013.9-py2.7.egg, /home/galaxy/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /home/galax
y/eggs/Mako-0.4.1-py2.7.egg, /home/galaxy/eggs/kombu-3.0.30-py2.7.egg, /home/galaxy/eggs/anyjson-0.3.3-py2.7.egg, /home/galaxy/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.eg
g, /home/galaxy/eggs/WebHelpers-1.3-py2.7.egg, /home/galaxy/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, 
/home/galaxy/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/numpy-1.6.0-py2.
7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /ho
me/galaxy/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs4.egg, /home/galaxy/eggs/WebOb-0.8.5-py2.7.egg, /home/galaxy/eggs/Routes-2.1-py2.7.egg, /home/galaxy/eggs/repoze.lru
-0.6-py2.7.egg, /home/galaxy/eggs/amqp-1.4.8-py2.7.egg, /home/galaxy/eggs/wchartype-0.1-py2.7.egg, /home/galaxy/eggs/docutils-0.7-py2.7.egg, /home/galaxy/eggs/PasteDeploy
-1.5.0-py2.7.egg, /home/galaxy/eggs/Paste-1.7.5.1-py2.7.egg, /home/galaxy/lib, /usr/lib64/python27.zip, /usr/lib64/python2.7, /usr/lib64/python2.7/plat-linux2, /usr/lib64
/python2.7/lib-tk, /usr/lib64/python2.7/lib-old, /usr/lib64/python2.7/lib-dynload, /usr/lib64/python2.7/site-packages, /usr/lib/python2.7/site-packages, /cluster/sw/lib/p
ython2.7/site-packages, /cluster/sw/lib64/python2.7/site-packages
galaxy.queue_worker INFO 2016-01-29 21:12:24,066 Initalizing main Galaxy Queue Worker on sqlalchemy+postgresql://galaxy:*******_@localhost/galaxydb
galaxy.eggs WARNING 2016-01-29 21:12:24,656 Warning: pbr (a dependent egg of sqlalchemy-migrate) cannot be fetched
Traceback (most recent call last):
  File "/home/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 65, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, *_kwargs )
  File "/home/galaxy/lib/galaxy/app.py", line 54, in **init**
    self._configure_models( check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file )
  File "/home/galaxy/lib/galaxy/config.py", line 843, in _configure_models
    create_or_verify_database( db_url, config_file, self.config.database_engine_options, app=self )
  File "/home/galaxy/lib/galaxy/model/migrate/check.py", line 71, in create_or_verify_database
    Table( "dataset", meta, autoload=True )
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 416, in __new__
    metadata._remove_table(name, schema)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 411, in **new**
    table._init(name, metadata, _args, *_kw)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 484, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 508, in _autoload
    self, include_columns, exclude_columns
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1972, in run_callable
    return conn.run_callable(callable_, _args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1477, in run_callable
    return callable_(self, _args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 364, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 582, in reflecttable
    include_columns, exclude_columns, reflection_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 712, in _reflect_indexes
    indexes = self.get_indexes(table_name, schema)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 481, in get_indexes
    info_cache=self.info_cache, *_kw)
  File "<string>", line 2, in get_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, *_kw)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/base.py", line 2701, in get_indexes
    c = connection.execute(t, table_oid=table_oid)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column i.reloptions does not exist
 [SQL: "\n              SELECT\n                  i.relname as relname,\n                  ix.indisunique, ix.indexprs, ix.indpred,\n                  a.attname, a.attnum, NULL, ix.indkey,\n                  i.reloptions, am.amname\n              FROM\n                  pg_class t\n                        join pg_index ix on t.oid = ix.indrelid\n                        join pg_class i on i.oid = ix.indexrelid\n                        left outer join\n                            pg_attribute a\n                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)\n                        left outer join\n                            pg_am am\n                            on i.relam = am.oid\n              WHERE\n                  t.relkind IN ('r', 'v', 'f', 'm')\n                  and t.oid = %(table_oid)s\n                  and ix.indisprimary = 'f'\n              ORDER BY\n                  t.relname,\n                  i.relname\n            "] [parameters: {'table_oid': 20615}]

-bash-3.2$ rm -r eggs
-bash-3.2$ sh manage_db.sh upgrade
Traceback (most recent call last):
  File "./scripts/manage_db.py", line 33, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 30, in invoke_migrate_main
    main( repository=repo, url=db_url )
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/shell.py", line 209, in main
    ret = command_func(*_kwargs)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, *_opts)
  File "<string>", line 2, in _migrate
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(_a, *_kw)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/api.py", line 342, in _migrate
    schema = ControlledSchema(engine, repository)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/home/galaxy/eggs/sqlalchemy_migrate-0.9.6-py2.7.egg/migrate/versioning/schema.py", line 45, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 416, in **new**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in **exit**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 411, in **new**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 484, in _init
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 508, in _autoload
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1972, in run_callable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1477, in run_callable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 364, in reflecttable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 582, in reflecttable
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 712, in _reflect_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 481, in get_indexes
  File "<string>", line 2, in get_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/reflection.py", line 54, in cache
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/base.py", line 2701, in get_indexes
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
migrate.exceptions.DatabaseNotControlledError: (psycopg2.ProgrammingError) column i.reloptions does not exist
 [SQL: "\n              SELECT\n                  i.relname as relname,\n                  ix.indisunique, ix.indexprs, ix.indpred,\n                  a.attname, a.attnum, NULL, ix.indkey,\n                  i.reloptions, am.amname\n              FROM\n                  pg_class t\n                        join pg_index ix on t.oid = ix.indrelid\n                        join pg_class i on i.oid = ix.indexrelid\n                        left outer join\n                            pg_attribute a\n                            on t.oid = a.attrelid and a.attnum = ANY(ix.indkey)\n                        left outer join\n                            pg_am am\n                            on i.relam = am.oid\n              WHERE\n                  t.relkind IN ('r', 'v', 'f', 'm')\n                  and t.oid = %(table_oid)s\n                  and ix.indisprimary = 'f'\n              ORDER BY\n                  t.relname,\n                  i.relname\n            "] [parameters: {'table_oid': 20606}]

**Comment by natefoo** [comment]
Well, this is at least a different error. What version of PostgreSQL do you happen to be using?

**Comment by methylome** [comment]
I'm using 8.1.23 on CentOs 5.9.

**Comment by natefoo** [comment]
[This is a SQLAlchemy bug](http://docs.sqlalchemy.org/en/latest/changelog/changelog_10.html#change-6bf7a5266dbb0b3f26b74d2cd173cd4d). SQLAlchemy was updated from 1.0.1 to 1.0.8 between these two releases. The bug was introduced in 1.0.6 and fixed in 1.0.9. I'll see what I can do about getting SQLAlchemy 1.0.11 eggs built.

**Comment by bgruening** [comment]
@methylome I will close this now. Please let us know if this is still a problem given Nates answer.
