### ISSUE TITLE
workflow error with "could not filter by metadata: otu not a data or collection parameter"

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#16121]
On AU and EU we see a ton of those in the workflow-handler logs:

```
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,671 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,671 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,680 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,680 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,681 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: group not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,681 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: group not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,689 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,689 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,713 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,714 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
```

xref: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/dynamic_options.py#L196

I could trace this down to some workflows and can provide them on request.
This looks to me like an error in a workflow, but either the workflows should crash or not be executed at all. Currently its sitting in our handlers.

**Comment by bgruening** [comment]
ping @cat-bro, if you want to add more details

**Comment by bgruening** [comment]
Some other mothur wiredness. I'm not super sure this is related but I found the same warning and a stacktrace. Also this is just one job, its reproducible in [this history](https://usegalaxy.eu/u/saskia/h/16s-rrna-tutoral).

I'm pretty sure I only run ONE job (`mothur_remove_seqs/1.39.5.0/`) and not a workflow here. However, I get those logs in the web handlers:

Note the following (yes I have reproduced that 3 times with just one tool start)

* why does ` '1.36.1.0' instead of version 'Unspecified' specified in this workflow.` exist? Its not a workflow, and its not that version?
* why do other mothur tools are now appearing in the logs? `mothur_screen_seqs`
* see the same `could not filter by metadata: otu not a data or collection parameter` as in the workflow handlers

```
May 19 21:12:14 sn06.galaxyproject.eu gunicorn[2832749]: uvicorn.access INFO 2023-05-19 21:12:14,116 [pN:main.3,p:2932893,tN:MainThread] 88.66.148.2:0 - "GET /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0/raw_tool_source HTTP/1.0" 200
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions INFO 2023-05-19 21:14:02,499 [pN:main.1,p:2803599,tN:WSGI_1] Handled output named fasta_out for tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0 (3.138 ms)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions INFO 2023-05-19 21:14:02,502 [pN:main.1,p:2803599,tN:WSGI_1] Handled output named count_out for tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0 (2.539 ms)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions INFO 2023-05-19 21:14:02,510 [pN:main.1,p:2803599,tN:WSGI_1] Setup for job Job[unflushed,tool_id=toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0] complete, ready to be enqueued (3.975 ms)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.execute DEBUG 2023-05-19 21:14:02,510 [pN:main.1,p:2803599,tN:WSGI_1] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0 created job None (23.009 ms)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.web_stack.handlers INFO 2023-05-19 21:14:02,559 [pN:main.1,p:2803599,tN:WSGI_1] (Job[id=60071035,tool_id=toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0]) Handler '_default_' assigned using 'HANDLER_ASSIGNMENT_METHODS.DB_SKIP_LOCKED' assignment method
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.execute DEBUG 2023-05-19 21:14:02,564 [pN:main.1,p:2803599,tN:WSGI_1] Created 1 job(s) for tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0 request (310.055 ms)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,712 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,715 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_summary_seqs/mothur_summary_seqs/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,716 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_classify_seqs/mothur_classify_seqs/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,718 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_lineage/mothur_remove_lineage/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,721 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_screen_seqs/mothur_screen_seqs/1.39.5.1: using version '1.39.5.1' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,727 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_screen_seqs/mothur_screen_seqs/1.39.5.1 output alignreport_out: dataset output filter (alignrep.alignreport) failed: 'dict' object has no attribute 'alignreport'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,728 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_screen_seqs/mothur_screen_seqs/1.39.5.1 output contigsreport_out: dataset output filter (contigsrep.contigsreport) failed: 'dict' object has no attribute 'contigsreport'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,729 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_unique_seqs/mothur_unique_seqs/1.39.5.0: using version '1.39.5.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,729 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_count_seqs/mothur_count_seqs/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,730 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster_split/mothur_cluster_split/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,732 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster_split/mothur_cluster_split/1.36.1.0 output rabund: dataset output filter (splitby['nameOrCount'].ext != "mothur.count_table") failed: 'nameOrCount'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,733 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster_split/mothur_cluster_split/1.36.1.0 output rabund: dataset output filter (splitby['matrix']['nameOrCount'].ext != "mothur.count_table") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,734 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster_split/mothur_cluster_split/1.36.1.0 output sabund: dataset output filter (splitby['nameOrCount'].ext != "mothur.count_table") failed: 'nameOrCount'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,734 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster_split/mothur_cluster_split/1.36.1.0 output sabund: dataset output filter (splitby['matrix']['nameOrCount'].ext != "mothur.count_table") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,735 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_pre_cluster/mothur_pre_cluster/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,736 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_pre_cluster/mothur_pre_cluster/1.36.1.0 output names_out: dataset output filter (name.ext != "mothur.count_table") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,737 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_pre_cluster/mothur_pre_cluster/1.36.1.0 output count_out: dataset output filter (name.ext == "mothur.count_table") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,738 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_make_shared/mothur_make_shared/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,740 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_make_shared/mothur_make_shared/1.36.1.0 output groupout: dataset output filter (intype['group'].ext == "mothur.groups") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,741 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_classify_otu/mothur_classify_otu/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,743 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_count_groups/mothur_count_groups/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,743 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_cluster/mothur_cluster/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,745 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_oturep/mothur_get_oturep/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,745 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_oturep/mothur_get_oturep/1.36.1.0 output names_out: dataset output filter (method_condition['nameOrCount'].ext == "mothur.names") failed: 'nameOrCount'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,745 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_oturep/mothur_get_oturep/1.36.1.0 output names_out: dataset output filter (method_condition['matrix_condition']['nameOrCount'].ext == "mothur.names") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,750 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_oturep/mothur_get_oturep/1.36.1.0 output count_out: dataset output filter (method_condition['nameOrCount'].ext == "mothur.count_table") failed: 'nameOrCount'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,750 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_oturep/mothur_get_oturep/1.36.1.0 output count_out: dataset output filter (method_condition['matrix_condition']['nameOrCount'].ext == "mothur.count_table") failed: 'RuntimeValue' object has no attribute 'ext'
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,753 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_dist_seqs/mothur_dist_seqs/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,754 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_split_abund/mothur_split_abund/1.39.5.0: using version '1.39.5.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,754 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_split_abund/mothur_split_abund/1.39.5.0 output abund_fasta_coll: dataset output filter (search['type'] == 'list' or (search['type'] == 'name' and split['dosplit'] == 'yes') failed: unexpected EOF while parsing (<string>, line 1)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,758 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_split_abund/mothur_split_abund/1.39.5.0 output abund_list_coll: dataset output filter (search['type'] == 'list' or (search['type'] == 'name' and split['dosplit'] == 'yes') failed: unexpected EOF while parsing (<string>, line 1)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.actions DEBUG 2023-05-19 21:14:02,760 [pN:main.4,p:2804066,tN:WSGI_4] Tool toolshed.g2.bx.psu.edu/repos/iuc/mothur_split_abund/mothur_split_abund/1.39.5.0 output rare_list_coll: dataset output filter (search['type'] == 'list' or (search['type'] == 'name' and split['dosplit'] == 'yes') failed: unexpected EOF while parsing (<string>, line 1)
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.workflow.modules DEBUG 2023-05-19 21:14:02,763 [pN:main.4,p:2804066,tN:WSGI_4] toolshed.g2.bx.psu.edu/repos/iuc/mothur_summary_tax/mothur_summary_tax/1.36.1.0: using version '1.36.1.0' instead of version 'Unspecified' specified in this workflow.
May 19 21:14:02 sn06.galaxyproject.eu gunicorn[2601116]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 21:14:02,745 [pN:main.4,p:2804066,tN:WSGI_4] could not filter by metadata: otu not a data or collection parameter

```

Meanwhile the job handlers produced this error (finally a stacktrace):
```
May 19 21:14:03 sn06.galaxyproject.eu python[1680040]: galaxy.jobs DEBUG 2023-05-19 21:14:03,931 [pN:handler_sn06_0,p:1680040,tN:JobHandlerQueue.monitor_thread] (60071035) Working directory for job is: /data/jwd01/main/060/071/60071035
May 19 21:14:03 sn06.galaxyproject.eu python[1680040]: galaxy.jobs.runners DEBUG 2023-05-19 21:14:03,950 [pN:handler_sn06_0,p:1680040,tN:JobHandlerQueue.monitor_thread] Job [60071035] queued (178.041 ms)
May 19 21:14:03 sn06.galaxyproject.eu python[1680040]: galaxy.jobs.handler INFO 2023-05-19 21:14:03,956 [pN:handler_sn06_0,p:1680040,tN:JobHandlerQueue.monitor_thread] (60071035) Job dispatched
May 19 21:14:03 sn06.galaxyproject.eu python[1680040]: pulsar.web.routes DEBUG 2023-05-19 21:14:03,999 [pN:handler_sn06_0,p:1680040,tN:PulsarJobRunner.work_thread-1] Setup job with configuration: {'job_directory': '/data/jwd01/pulsar_staging/60071035', 'working_directory': '/data/jwd01/pulsar_staging/60071035/working', 'metadata_directory': '/data/jwd01/pulsar_staging/60071035/metadata', 'outputs_directory': '/data/jwd01/pulsar_staging/60071035/outputs', 'configs_directory': '/data/jwd01/pulsar_staging/60071035/configs', 'tools_directory': '/data/jwd01/pulsar_staging/60071035/tool_files', 'inputs_directory': '/data/jwd01/pulsar_staging/60071035/inputs', 'unstructured_files_directory': '/data/jwd01/pulsar_staging/60071035/unstructured', 'path_separator': '/', 'job_id': '60071035', 'system_properties': {'separator': '/', 'galaxy_home': '/opt/galaxy/server'}, 'pulsar_version': '0.15.2', 'preserve_galaxy_python_environment': None, 'tool_id': 'toolshed.g2.bx.psu.edu/repos/iuc/mothur_remove_seqs/mothur_remove_seqs/1.39.5.0', 'tool_version': '1.39.5.0'}
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: galaxy.jobs.runners.pulsar INFO 2023-05-19 21:14:03,999 [pN:handler_sn06_0,p:1680040,tN:PulsarJobRunner.work_thread-1] pulsar_version is 0.15.2
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: RefactoringTool DEBUG 2023-05-19 21:14:04,159 [pN:handler_sn06_0,p:1680040,tN:PulsarJobRunner.work_thread-1] Refactoring auto_translate_cheetah
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: galaxy.jobs.runners.pulsar ERROR 2023-05-19 21:14:04,222 [pN:handler_sn06_0,p:1680040,tN:PulsarJobRunner.work_thread-1] failure running job 60071035
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: Traceback (most recent call last):
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 82, in fill_template
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return unicodify(t, log_exception=False)
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1184, in unicodify
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     value = str(value)
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return getattr(self, mainMethName)()
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "cheetah_DynamicallyCompiledCheetahTemplate_1684523644_2186956_82099.py", line 94, in respond
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: FileNotFoundError: [Errno 2] No such file or directory: '/data/jwd01/pulsar_staging/60071035/inputs/dataset_1d66a80c-7859-4a50-92b5-cfcebfbc3c07.dat'
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: During handling of the above exception, another exception occurred:
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: Traceback (most recent call last):
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/pulsar.py", line 484, in __prepare_job
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     job_wrapper.prepare(**prepare_kwds)
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1253, in prepare
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     ) = tool_evaluator.build()
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 558, in build
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     global_tool_logs(self._build_command_line, config_file, "Building Command Line")
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 90, in global_tool_logs
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     raise e
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 86, in global_tool_logs
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return func()
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 575, in _build_command_line
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     command_line = fill_template(
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 121, in fill_template
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return fill_template(
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 130, in fill_template
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     raise first_exception or e
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/template.py", line 82, in fill_template
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return unicodify(t, log_exception=False)
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1184, in unicodify
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     value = str(value)
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "/opt/galaxy/venv/lib64/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:     return getattr(self, mainMethName)()
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]:   File "cheetah_DynamicallyCompiledCheetahTemplate_1684522842_99605_66205.py", line 91, in respond
May 19 21:14:04 sn06.galaxyproject.eu python[1680040]: FileNotFoundError: [Errno 2] No such file or directory: '/data/jwd01/pulsar_staging/60071035/inputs/dataset_1d66a80c-7859-4a50-92b5-cfcebfbc3c07.dat'
```

**Comment by mvdbeek** [comment]
> ```
> May 19 20:27:17 sn06.galaxyproject.eu python[3376731]: galaxy.tools.parameters.dynamic_options WARNING 2023-05-19 20:27:17,714 [pN:workflow_scheduler_sn06_0,p:3376731,tN:WorkflowRequestMonitor.monitor_thread] could not filter by metadata: otu not a data or collection parameter
> ```

that's fine, the dataset may just not be ready yet. if the logging is too verbose we can decrease this to debug.



> I'm not super sure this is related

probably not, no

> * why does ` '1.36.1.0' instead of version 'Unspecified' specified in this workflow.` exist? Its not a workflow, and its not that version?

how do you know it's not a workflow ? we only log this from workflow modules.

> * why do other mothur tools are now appearing in the logs?

other people running mothur tools ?


overall that all looks like mothur bugs

**Comment by mvdbeek** [comment]
> However, I get those logs in the web handlers:

sorry, missed answering this one: that's when you build the tool module, e.g. when importing workflows, running workflows, editing workflows etc.

Is it OK to close this ?

**Comment by wm75** [comment]
> https://github.com/galaxyproject/tools-iuc/blob/main/tools/mothur/remove.seqs.xml#L14 for instance is not a valid thing to do ... that access happens in the job handler, so it fails if there's any path rewriting, but also no files should ever be touched or opened in cheetah.

Oh, that's interesting. Never thought about it, and there are in indeed a few tools in iuc that violate that it seems :(

**Comment by wm75** [comment]
./tools/datamash/datamash-transpose.xml:        #set file_size_MB = os.path.getsize(str($in_file)) / (1024 * 1024)

./tools/hicexplorer/macros.xml:        #set $temp_dir = os.path.abspath(tempfile.mkdtemp())
./tools/hicexplorer/macros.xml:            #silent os.system("ln -s %s %s.bam" % (str($i.bamfile), $temp_input_path))
./tools/hicexplorer/macros.xml:            #silent os.system("ln -s %s %s.bam.bai" % (str($i.bamfile.metadata.bam_index), $temp_input_path))
./tools/hicexplorer/macros.xml:        #set $temp_dir = os.path.abspath(tempfile.mkdtemp())
./tools/hicexplorer/macros.xml:            #silent os.system("ln -s %s %s.bw" % (str($i.bigwigfile), $temp_input_path))

./tools/mothur/remove.seqs.xml:#if $os.lstat(str($accnos)).st_size == 0:

./tools/ena_upload/ena_upload.xml:      #if os.path.isfile(os.environ.get('GALAXY_ENA_SECRETS', '')):

**Comment by hexylena** [comment]
the symlinks are easy fixes at least, the mothur case is harder. Not sure how we'd fix that.

**Comment by mvdbeek** [comment]
yikes 😨 

I wish we had a way to forbid this or detect it efficiently, but cheetah isn't super-amenable to that. It's also possible to template the command line remotely, and then this would work ... but yeah, this is better implemented with checking the file metadata. For mothur `$accnos.file_size` should work.

**Comment by mvdbeek** [comment]
(also we should use embedded pulsar with path rewriting in the IUC to at least fail tools that do this)

**Comment by hexylena** [comment]
> forbid this or detect it efficiently

grep is pretty efficient! It was a similar situation in the training materials, rather than do it "properly" we do it via a lot of greps and it works really well (perfect/enemy/good/etc.) I've started adding a lint.py script to the IUC as part of https://github.com/galaxyproject/tools-iuc/issues/4349, I'll see what I can add there.

**Comment by mvdbeek** [comment]
what I mean is that Galaxy has no idea this is happening, we can't base any automatic decisions on grep, we have no idea this isn't just an embedded string, we can't just say a tool's command line looks safe enough so that users could bring their own tools, the way in which you can violate access are practically infinite ... sometimes we do require perfect.

**Comment by mvdbeek** [comment]
also false positives: https://github.com/galaxyproject/tools-iuc/issues/4349#issuecomment-1556913653

**Comment by hexylena** [comment]
Ah yes @mvdbeek, I only meant from the IUC side. From the galaxy side, yeah, hopeless. Agreed.
