### ISSUE TITLE
Error in 'installed tools'/'manage metadata' from tool shed after Galaxy Upgrade from 20.01 to 23.0

### ISSUE THREAD

**Issue by axgraf** [galaxyproject/galaxy#16135]
**Describe the bug**
After updating Galaxy from 20.01 to version 23.0 I can not list the installed tools from the toolshed and manage metadata is not working.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 (after upgrade from 20.01)
Commit: 763b1daef9a35e2435c84153ca440dfa8f4f2dc7

**To Reproduce**
1. Go to 'Admin section'
2. Click on 'Manage Metadata' or 'Install and Uninstall' -> 'Installed only'
3. The following error occurs: "Request failed for an unknown reason" or just shows "(500)"

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/16762600/ceb06d94-d642-4229-ac13-33584cf74df2)

**Additional context**
Error from the logs:

uvicorn.access INFO 2023-05-22 16:41:15,680 [pN:main.4,p:83069,tN:MainThread] 10.163.152.42:0 - "GET /api/tool_shed_repositories?**uninstalled=False** HTTP/1.0" 500
[2023-05-22 16:41:15 +0000] [83069] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette_context/middleware/raw_middleware.py", line 93, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/data/local/galaxy/galaxy/lib/galaxy/webapps/galaxy/fast_app.py", line 103, in add_x_frame_options
    response = await call_next(request)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
 File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in 
  run_sync_in_worker_thread
    return await future
  File "/data/local/galaxy/galaxy/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data/local/galaxy/galaxy/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py", line 433, in index
    return self.service.index(request)
  File "/data/local/galaxy/galaxy/lib/galaxy/webapps/galaxy/services/tool_shed_repositories.py", line 66, in index
    index.append(self._show(repository))
  File "/data/local/galaxy/galaxy/lib/galaxy/webapps/galaxy/services/tool_shed_repositories.py", line 83, in _show
    return InstalledToolShedRepository(**tool_shed_repository_dict)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for InstalledToolShedRepository
tool_shed_status -> latest_installable_revision
  field required (type=value_error.missing)
tool_shed_status -> repository_deprecated
  field required (type=value_error.missing)

Could someone give me a hint how to solve that problem?

**Comment by dannon** [comment]
When digging, I reproduced another failure locally -- it looks like more of the model data may actually be unavailable.  In your case it looks like latest_installable_revision and repository_deprecated, and in mine it was ctx_rev.  I opened the PR linked above to start a conversation about what data is and isn't actually optional here.
