### ISSUE TITLE
media_player visualization crashes [FIX INCLUDED]

### ISSUE THREAD

**Issue by bdwheele** [galaxyproject/galaxy#16415]
**Describe the bug**
The media player visualization crashes when playing a wav file

**Galaxy Version and/or server at which you observed the bug**
23.0.4
)

**To Reproduce**
1. Fresh install of 23.0.4
2. Create user
3. Upload a wav file into the current history
4. hit the visualizations tab and select Audio Player
5. select the uploaded file from the history
6. Player comes up but doesn't play

**Expected behavior**
Audio output.

**Additional context**
Stack trace:
```uvicorn.access INFO 2023-07-18 12:30:04,862 [pN:main.7,p:14618,tN:MainThread] 10.0.2.2:46318 - "GET /datasets/1/display HTTP/1.1" 500
[2023-07-18 12:30:04 -0400] [14618] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette_context/middleware/raw_middleware.py", line 93, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
    await response(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/base.py", line 98, in body_stream
    raise app_exc
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/a2wsgi/wsgi.py", line 155, in __call__
    return await responder(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/a2wsgi/wsgi.py", line 194, in __call__
    raise self.exc_info[0].with_traceback(
  File "/home/amp/galaxy-23.0.4/lib/galaxy/web/framework/middleware/error.py", line 165, in __call__
    app_iter = self.application(environ, sr_checker)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/.venv/lib64/python3.11/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/lib/galaxy/web/framework/base.py", line 167, in __call__
    return self.handle_request(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/lib/galaxy/web/framework/base.py", line 258, in handle_request
    return body_renderer(trans, body, environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/lib/galaxy/web/framework/base.py", line 273, in _render_body
    return send_file(start_response, trans, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amp/galaxy-23.0.4/lib/galaxy/web/framework/base.py", line 545, in send_file
    trans.response.headers["content-length"] = str(end - start)
                                                   ~~~~^~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Retrieving the URL using curl works just fine, so it's likely something in the way the player is requesting the resource (likely byte range or something)

**Comment by bdwheele** [comment]
In galaxy-23.0.4/lib/galaxy/web/framework/base.py in the send_file function, this code fixes it:

```
        if trans.request.range:
            start = int(trans.request.range.start)
            file_size = int(trans.response.headers["content-length"])
            end = int(file_size if end is None else trans.request.range.end)
            trans.response.headers["content-length"] = str(end - start)
            trans.response.headers["content-range"] = f"bytes {start}-{end - 1}/{file_size}"
            trans.response.status = 206

```

**Comment by bgruening** [comment]
@bdwheele do you mind creating a Pull Request so you get properly acknowledged for your contribution?

**Comment by bdwheele** [comment]
Which branch should I do the PR against?

**Comment by bgruening** [comment]
Try release_23.1 so it gets in the next release.

**Comment by mvdbeek** [comment]
This is a bug, any branch is fine, you've seen it on 23.0 so that's a good start.

**Comment by mvdbeek** [comment]
I can fix this up, thanks for the report and fix.
