### ISSUE TITLE
galaxy-tool-test broken in 23.1 - old legacyversion tool_util code in the virtualenv?

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/galaxy#16488]
**Describe the bug**
galaxy-tool-test breaks > 23.0. It works in 23.0 but in 23.1 or dev it fails with a legacyversion error...removed in packaging 22.0 it seems. The code in .venv/..../tool_utils is not the updated code in galaxy's lib/..../tool_utils, so that might explain it.

Using 23.1 the bug is reproduced by executing galaxy-tool-test:
```
.venv) ubuntu@ross-newgrt:/evol/galaxytf231$ galaxy-tool-test 
Traceback (most recent call last):
  File "/evol/galaxytf231/.venv/bin/galaxy-tool-test", line 5, in <module>
    from galaxy.tool_util.verify.script import main
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/verify/__init__.py", line 25, in <module>
    from galaxy.tool_util.parser.util import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/parser/__init__.py", line 3, in <module>
    from .factory import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/parser/factory.py", line 19, in <module>
    from .cwl import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/parser/cwl.py", line 8, in <module>
    from galaxy.tool_util.cwl.parser import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/cwl/__init__.py", line 1, in <module>
    from .cwltool_deps import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/cwl/cwltool_deps.py", line 15, in <module>
    from cwltool import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/cwltool/job.py", line 44, in <module>
    from .builder import Builder
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/cwltool/builder.py", line 31, in <module>
    from .software_requirements import DependenciesConfiguration
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/cwltool/software_requirements.py", line 23, in <module>
    from galaxy.tool_util import deps
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/deps/__init__.py", line 24, in <module>
    from .dependencies import ToolInfo
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/deps/dependencies.py", line 15, in <module>
    from .mulled.mulled_build import DEFAULT_CHANNELS
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/deps/mulled/mulled_build.py", line 29, in <module>
    from galaxy.tool_util.deps.conda_util import (
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/deps/conda_util.py", line 87, in <module>
    class CondaContext(installable.InstallableContext):
  File "/evol/galaxytf231/.venv/lib/python3.10/site-packages/galaxy/tool_util/deps/conda_util.py", line 90, in CondaContext
    _conda_version: Optional[Union[packaging.version.Version, packaging.version.LegacyVersion]]
AttributeError: module 'packaging.version' has no attribute 'LegacyVersion'
```

`diff .venv/lib/python3.10/site-packages/galaxy/tool_util/deps/conda_util.py lib/galaxy/tool_util/deps/conda_util.py`
gives a long diff in 23.1 and dev :
```
5a6
> import platform
23c24
< import packaging.version
---
> from packaging.version import Version
24a26
> from galaxy.tool_util.version import parse_version
56c58,61
<         url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
---
>         if "arm64" in platform.platform():
>             url = "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-arm64.sh"
>         else:
>             url = "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh"
59c64,67
<             url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
---
>             if "arm64" in platform.platform():
>                 url = "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-aarch64.sh"
>             else:
>                 url = "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh"
90c98
<     _conda_version: Optional[Union[packaging.version.Version, packaging.version.LegacyVersion]]
---
>     _conda_version: Optional[Version]
135c143
<     def conda_version(self) -> Union[packaging.version.Version, packaging.version.LegacyVersion]:
---
>     def conda_version(self) -> Version:
138c146
,,,,&tc....
```
but gives no output in 23.0 - they are the same code.

**Comment by fubar2** [comment]
hmm. having trouble reproducing now...
