### ISSUE TITLE
Tool burst submission failing

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#1657]
Getting the following stack trace when attempting to use tool burst submission with 2 threads with 5 or more jobs. It submit and finishes smalt map step but complete stop after that. Workflow : http://imgur.com/Au9zb20

galaxy.workflow.run ERROR 2016-02-02 14:09:23,116 Failed to schedule Workflow[id=3,name=BETA: Snvphyl pipeline PE fastq v 0.5.1 (imported from uploaded file)], problem occurred on WorkflowStep[index=4,type=tool].
Traceback (most recent call last):
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/modules.py", line 1182, in execute
    self._handle_post_job_actions( step, job, invocation.replacement_dict )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/modules.py", line 1226, in _handle_post_job_actions
    job.add_post_job_action( pja )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/model/__init__.py", line 586, in add_post_job_action
    self.post_job_actions.append( PostJobActionAssociation( pja, self ) )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 1072, in append
    item = **set(self, item, _sa_initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 1044, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 716, in fire_append_event
    item, initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/attributes.py", line 936, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1596, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1846, in _save_or_update_impl
    self._update_impl(state)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1834, in _update_impl
    self._before_attach(state, check_identity_map=False)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1933, in _before_attach
    state.session_id, self.hash_key))
InvalidRequestError: Object '<PostJobAction at 0xf2c1c10>' is already attached to session '4' (this is '39')
galaxy.workflow.run ERROR 2016-02-02 14:09:23,231 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/modules.py", line 1182, in execute
    self._handle_post_job_actions( step, job, invocation.replacement_dict )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/workflow/modules.py", line 1226, in _handle_post_job_actions
    job.add_post_job_action( pja )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/lib/galaxy/model/__init**.py", line 586, in add_post_job_action
    self.post_job_actions.append( PostJobActionAssociation( pja, self ) )
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 1072, in append
    item = __set(self, item, _sa_initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 1044, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/collections.py", line 716, in fire_append_event
    item, initiator)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/attributes.py", line 936, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1596, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1846, in _save_or_update_impl
    self._update_impl(state)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1834, in _update_impl
    self._before_attach(state, check_identity_map=False)
  File "/Warehouse/Applications/galaxy/test_test_galaxy/galaxy/.venv/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1933, in _before_attach
    state.session_id, self.hash_key))
InvalidRequestError: Object '<PostJobAction at 0xf2c1c10>' is already attached to session '4' (this is '39')

On latest release_16.01 : 9170865dfbe0f8588ec47449e683236e5ba92a39
I have 6 handlers and uwsgi for the web workers.

**Comment by jmchilton** [comment]
For my own benefit, xref https://github.com/galaxyproject/galaxy/pull/1197/commits/7f6514a21222ea787a0676764e4a4fe825891b27.
