### ISSUE TITLE
Cannot see anymore workflow invocation

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#16626]
**Describe the bug**
When I go to https://usegalaxy.eu/workflows/invocations or to https://usegalaxy.org/workflows/invocations
I get Uncaught exception in exposed API method:

**Galaxy Version and/or server at which you observed the bug**
The bug is observed on usegalaxy.eu and usegalaxy.org
Yesterday, the bug was observed on usegalaxy.eu but not usegalaxy.org

**To Reproduce**
??????
Sorry I don´t know how to reproduce the bug as I have it constantly...
You can impersonate me: my username is ldelisle
On usegalaxy.eu the trace is:
```
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]: galaxy.web.framework.decorators ERROR 2023-08-31 10:01:21,397 [pN:main.4,p:2753337,tN:WSGI_1] Uncaught exception in exposed API method:
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]: Traceback (most recent call last):
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/web/framework/decorators.py", line 337, in decorator
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     rval = func(self, trans, *args, **kwargs)
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/api/workflows.py", line 827, in index_invocations
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     invocations, total_matches = self.invocations_service.index(trans, invocation_payload, serialization_params)
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/services/invocations.py", line 146, in index
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     invocation_dict = self.serialize_workflow_invocations(invocations, serialization_params)
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/services/invocations.py", line 215, in serialize_workflow_invocations
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     return list(
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:            ^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/services/invocations.py", line 216, in <lambda>
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     map(lambda i: self.serialize_workflow_invocation(i, params, default_view=default_view), invocations)
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/services/invocations.py", line 204, in serialize_workflow_invocation
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     as_dict["messages"] = [
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:                           ^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/services/invocations.py", line 205, in <listcomp>
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     InvocationMessageResponseModel.parse_obj(message).__root__.dict() for message in invocation.messages
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 1076, in pydantic.main.validate_model
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 1061, in pydantic.fields.ModelField._validate_singleton
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 1150, in pydantic.fields.ModelField._validate_discriminated_union
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 713, in pydantic.main.BaseModel.validate
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 577, in pydantic.main.BaseModel.from_orm
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "pydantic/main.py", line 1055, in pydantic.main.validate_model
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:   File "/opt/galaxy/server/lib/galaxy/schema/invocation.py", line 56, in get
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:     return self._obj.dependent_workflow_step.order_index
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 10:01:21 sn06.galaxyproject.eu gunicorn[2624194]: AttributeError: 'NoneType' object has no attribute 'order_index'
```

Maybe it is because I ran planemo test and forgot to specify an input parameter. For example:
```
(planemo) [ldelisle@SV-49-002 atacseq]$ planemo test --galaxy_url https://usegalaxy.org --galaxy_user_key fdc4eb99c1d05438f3992b536262bc8f atacseq.ga 
Failed to execute Galaxy activity, throwing ErrorRunResponse
Traceback (most recent call last):
  File "/home/ldelisle/planemo/lib/python3.11/site-packages/planemo/galaxy/activity.py", line 72, in execute
    return _execute(ctx, config, runnable, job_path, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ldelisle/planemo/lib/python3.11/site-packages/planemo/galaxy/activity.py", line 199, in _execute
    invocation = user_gi.workflows.invoke_workflow(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ldelisle/planemo/lib/python3.11/site-packages/bioblend/galaxy/workflows/__init__.py", line 494, in invoke_workflow
    return self._post(payload, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ldelisle/planemo/lib/python3.11/site-packages/bioblend/galaxy/client.py", line 169, in _post
    return self.gi.make_post_request(url, payload=payload, files_attached=files_attached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ldelisle/planemo/lib/python3.11/site-packages/bioblend/galaxyclient.py", line 197, in make_post_request
    raise ConnectionError(
bioblend.ConnectionError: Unexpected HTTP status code: 400: {"err_msg": "Workflow cannot be run because an expected input step '6654745' (None) is not optional and no input.", "err_code": 0}
There were problems with 1 test(s) - out of 1 test(s) executed. See tool_test_output.html for detailed breakdown.
atacseq.ga_0: failed
```

**Expected behavior**
See my workflows invocations

**Comment by mvdbeek** [comment]
and this is the original failure as it happened, which does includes the missing workflow step id: https://sentry.galaxyproject.org/share/issue/aefa105b4385489caaca16299cc8508e/

FWIW the error message there is `Failed to schedule Workflow[id=493543,name=test_cov], problem occurred on WorkflowStep[index=6,type=tool,label=pick strand2 if exists,uuid=387cb49f-2d01-45be-a642-8bb5ec3648ea,id=6653396].` and the error there is `Multiple null values found, only one allowed`

**Comment by lldelisle** [comment]
Thanks.
