### ISSUE TITLE
pysqlite missing?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1663]
Sorry for all the spam, just try to update FR-Galaxy and will post all things I will find.

```
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/base.py", line 584, in _load_tool_tag_set
    tool = self.load_tool( os.path.join( tool_path, path ), guid=guid, repository_id=repository_id, use_cached=internal )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/base.py", line 732, in load_tool
    tool = self.create_tool( config_file=config_file, repository_id=repository_id, guid=guid, **kwds )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 158, in create_tool
    tool = ToolClass( config_file, tool_source, self.app, guid=guid, repository_id=repository_id, **kwds )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 342, in __init__
    raise e
DistributionNotFound: The 'pysqlite>=2' distribution was not found and is required by the application
```

**Comment by natefoo** [comment]
Is a local tool's code file attempting to use pysqlite? There should not be any in the distribution.

**Comment by martenson** [comment]
please provide additional info to reopen
