### ISSUE TITLE
Admin UI: Job Lock broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#16651]
**Describe the bug**

If clicking `Job Lock` in the Admin UI the toggle jumps back immediately and in the logs I see

```
galaxy.queue_worker ERROR 2023-09-06 14:39:34,289 [pN:main.2,p:26116,tN:AnyIO worker thread] Error queueing async task: '{'task': 'admin_job_lock', 'kwargs': {'job_lock': False}}'. for control.*
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/queue_worker.py", line 113, in send_task
    exchange=None if local else self.exchange,
                                ^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/queue_worker.py", line 88, in exchange
    return self.queue_worker.exchange_queue.exchange
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'exchange'
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: 1ad49865fb

**To Reproduce**

See description

**Expected behavior**

Job lock can be enabled / disabled

**Comment by bernt-matthias** [comment]
This was a temporary problem on my side.
