### ISSUE TITLE
Error executing tool with id '__EXTRACT_DATASET__': 'Dataset collection has no element_identifier with key None.'

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#16736]
I found that while debugging some workflow execution of a user. I'm sure the workflows is wrong, but it should probably not fail this way, but not start at all in the first place. Or return some meaningful error message?

```
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: Traceback (most recent call last):
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1937, in handle_single_execution
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     rval = self.execute(
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:            ^^^^^^^^^^^^^
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 2034, in execute
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     return self.tool_action.execute(
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/tools/actions/model_operations.py", line 88, in execute
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     self._produce_outputs(
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/tools/actions/model_operations.py", line 119, in _produce_outputs
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     tool.produce_outputs(
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 3308, in produce_outputs
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     extracted_element = collection[incoming["which"]["identifier"]]
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/model/__init__.py", line 6394, in __getitem__
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     raise KeyError(error_message)
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: KeyError: 'Dataset collection has no element_identifier with key None.'
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: galaxy.tools.execute WARNING 2023-09-23 14:20:28,474 [pN:workflow_scheduler_sn06_0,p:3387131,tN:WorkflowRequestMonitor.monitor_thread] There was a failure executing a job for tool [__EXTRACT_DATASET__] - Error executing tool with id '__EXTRACT_DATASET__': 'Dataset collection has no element_identifier with key None.'
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: galaxy.tools.execute DEBUG 2023-09-23 14:20:28,481 [pN:workflow_scheduler_sn06_0,p:3387131,tN:WorkflowRequestMonitor.monitor_thread] Created 1 job(s) for tool __EXTRACT_DATASET__ request (93.894 ms)
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: galaxy.workflow.run ERROR 2023-09-23 14:20:28,498 [pN:workflow_scheduler_sn06_0,p:3387131,tN:WorkflowRequestMonitor.monitor_thread] Failed to schedule Workflow[id=224248,name=IceNet], problem occurred on WorkflowStep[index=20,type=tool,label=None,uuid=7876109a-7cb5-426d-8d1d-ab5bb88ba818,id=3437276].
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: Traceback (most recent call last):
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/workflow/run.py", line 233, in invoke
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     incomplete_or_none = self._invoke_step(workflow_invocation_step)
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/workflow/run.py", line 309, in _invoke_step
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     incomplete_or_none = invocation_step.workflow_step.module.execute(
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:   File "/opt/galaxy/server/lib/galaxy/workflow/modules.py", line 2323, in execute
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]:     raise exceptions.MessageException(message)
Sep 23 14:20:28 sn06.galaxyproject.eu python[3387131]: galaxy.exceptions.MessageException: Failed to create 1 job(s) for workflow step 21: Error executing tool with id '__EXTRACT_DATASET__': 'Dataset collection has no element_identifier with key None.'
```

**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
> but not start at all in the first place.

I don't think that's possible, that is a usage error where the identifier read in by `__EXTRACT_DATASET__` is actually None. Does the error message appear when you open the invocation ?
