### ISSUE TITLE
Job is green after collecting more than `max_discovered_files` output files with `discover_dataset` but collection is empty

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#17001]
Running a tool that generates a collection with over `max_discovered_files` elements (10k in my case) gives the following result in the UI:

![image](https://github.com/galaxyproject/galaxy/assets/32272674/d66a55c9-34ab-4aa9-884c-d5b9c18600dd)

i.e. an empty collection. Meanwhile the logs show:

```
Nov 08 19:25:18 galaxy3 galaxyctl[6130]: galaxy.jobs.runners.drmaa DEBUG 2023-11-08 19:25:18,107 [pN:handler_0,p:6130,tN:SlurmRunner.monitor_thread] (13903/5478) state change: job finished normally
Nov 08 19:25:18 galaxy3 galaxyctl[6130]: galaxy.job_execution.output_collect ERROR 2023-11-08 19:25:18,331 [pN:handler_0,p:6130,tN:SlurmRunner.work_thread-0] Problem gathering output collection.
Nov 08 19:25:18 galaxy3 galaxyctl[6130]: Traceback (most recent call last):
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:   File "/srv/galaxy/server/lib/galaxy/job_execution/output_collect.py", line 175, in collect_dynamic_outputs
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:     filenames = job_context.find_files(output_name, collection, dataset_collectors)
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:   File "/srv/galaxy/server/lib/galaxy/job_execution/output_collect.py", line 205, in find_files
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:     self.increment_discovered_file_count()
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:   File "/srv/galaxy/server/lib/galaxy/model/store/discover.py", line 514, in increment_discovered_file_count
Nov 08 19:25:18 galaxy3 galaxyctl[6130]:     raise MaxDiscoveredFilesExceededError(
Nov 08 19:25:18 galaxy3 galaxyctl[6130]: galaxy.model.store.discover.MaxDiscoveredFilesExceededError: Job generated more than maximum number (10000) of output datasets
Nov 08 19:25:18 galaxy3 galaxyctl[6130]: galaxy.jobs DEBUG 2023-11-08 19:25:18,478 [pN:handler_0,p:6130,tN:SlurmRunner.work_thread-0] job_wrapper.finish for job 13903 executed (297.029 ms)
```

The job should fail and the user should be informed why.

**Comment by simonbray** [comment]
I noticed the collection itself is labelled with the reason for failure (see below) but the job state is nonetheless `ok`.

```
{
  "id": "58a62ef5358d717c",
  "name": "Create PQR files from an SD-file on data 1",
  "history_id": "b0636f6e068b4021",
  "hid": 15,
  "history_content_type": "dataset_collection",
  "deleted": false,
  "visible": true,
  "type_id": null,
  "type": "collection",
  "create_time": "2023-11-08T17:46:48.346606",
  "update_time": "2023-11-08T18:25:18.406182",
  "url": "/api/histories/b0636f6e068b4021/contents/dataset_collections/58a62ef5358d717c",
  "tags": [],
  "model_class": "HistoryDatasetCollectionAssociation",
  "collection_type": "list",
  "populated_state": "failed",
  "populated_state_message": "Problem building datasets for collection.",
  "element_count": null,
  "job_source_id": "66a3edf78906127d",
  "job_source_type": "Job",
  "job_state_summary": {
    "all_jobs": 1,
    "new": 0,
    "waiting": 0,
    "running": 0,
    "error": 0,
    "paused": 0,
    "skipped": 0,
    "deleted_new": 0,
    "resubmitted": 0,
    "queued": 0,
    "ok": 1,
    "failed": 0,
    "deleted": 0,
    "upload": 0
  },
  "contents_url": "/api/dataset_collections/58a62ef5358d717c/contents/ebf17a63b5954d76",
  "collection_id": "ebf17a63b5954d76",
  "populated": false,
  "elements": [],
  "elements_datatypes": []
}
```

**Comment by mvdbeek** [comment]
@ahmedhamidawan this is essentially what I'm talking about for https://github.com/galaxyproject/galaxy/pull/16996. Look at the populated_state and populated_state_message properties
