### ISSUE TITLE
Pulsar terminal status udpate fails with `None` value `job_wrapper.tool`

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#17068]
**Describe the bug**
```
pulsar.client.manager DEBUG 2023-11-22 09:45:14,553 [pN:main_w3_handler2,p:21745,tN:pulsar_client_jetstream2_status_update_callback] Handling asynchronous status update from remote Pulsar.
galaxy.jobs DEBUG 2023-11-22 09:45:14,561 [pN:main_w3_handler2,p:21745,tN:pulsar_client_jetstream2_status_update_callback] (53844160) Working directory for job is: /corral4/main/jobs/053/844/53844160
galaxy.jobs.runners.pulsar ERROR 2023-11-22 09:45:14,564 [pN:main_w3_handler2,p:21745,tN:pulsar_client_jetstream2_status_update_callback] Failed to update Pulsar job status for job_id (53844160/53844160)
Traceback (most recent call last):
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 984, in __async_update
  job_state = self._job_state(job, job_wrapper)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 781, in _job_state
  job_state = AsynchronousJobState(
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 752, in __init__
  self.set_defaults(files_dir)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 690, in set_defaults
  if self.job_wrapper.tool.old_id:
AttributeError: 'NoneType' object has no attribute 'old_id'
pulsar.client.manager ERROR 2023-11-22 09:45:14,577 [pN:main_w3_handler2,p:21745,tN:pulsar_client_jetstream2_status_update_callback] Failure processing job status update message.
Traceback (most recent call last):
File "/cvmfs/main.galaxyproject.org/venv/lib/python3.8/site-packages/pulsar/client/manager.py", line 155, in callback_wrapper
  callback(body)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 984, in __async_update
  job_state = self._job_state(job, job_wrapper)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 781, in _job_state
  job_state = AsynchronousJobState(
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 752, in __init__
  self.set_defaults(files_dir)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 690, in set_defaults
  if self.job_wrapper.tool.old_id:
AttributeError: 'NoneType' object has no attribute 'old_id'
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.2.dev0
Commit: 8c3e4d36755e39acc0a7bee6c81b57203abb2f13

**To Reproduce**
I am not sure the exact conditions this happens under but it's repeatable for this single job at least. This a failed SPAdes run, sending back the (missing) work dir outputs fails as expected and then Pulsar sends the terminal status update, but the Pulsar runner hits the traceback above upon receipt.

**Comment by mvdbeek** [comment]
that looks like the tool is not loaded in the handler. is that possible ?

**Comment by natefoo** [comment]
Yeah, that is what I just came to realize, `app.toolbox.get_tool()` is returning `None` when creating the wrapper.

It's in the frontend at least (the tool is `toolshed.g2.bx.psu.edu/repos/nml/metaspades/metaspades/3.15.4+galaxy2`):

```
% curl -s 'https://usegalaxy.org/api/tools?in_panel=false' | jq | grep 'id":.*metaspades' | sort | uniq
    "id": "toolshed.g2.bx.psu.edu/repos/nml/metaspades/metaspades/3.15.3+galaxy2",
    "id": "toolshed.g2.bx.psu.edu/repos/nml/metaspades/metaspades/3.15.4+galaxy2",
    "id": "toolshed.g2.bx.psu.edu/repos/nml/metaspades/metaspades/3.9.0",
```

But, that version was recently added, I bet a handler restart will fix it.

**Comment by natefoo** [comment]
Restarting handlers fixed it. Maybe not the most obvious error message but it should be uncommon as well.

**Comment by mvdbeek** [comment]
We'll probably get to add a better error message when we're adding type annotations there
