### ISSUE TITLE
`dataset.file_name` removal breaks exisiting tools

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17098]
e.g. gprofiler orth `planemo test --galaxy_branch release_23.2  --biocontainers tools-iuc/tools/gprofiler/gprofiler_orth.xml`:

## Test Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" title="2 Failed or Errored">
  </div>
</div>

| Test State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 2 |
| Skipped    | 0 |

<details open><summary>Failed Tests</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; gprofiler_orth (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: gprofiler_orth, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: gprofiler_orth, exit_code: None, stderr: .
      ```
    **Traceback:**

    * ```console
      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 292, in prepare_job
          job_wrapper.prepare()
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1261, in prepare
          ) = tool_evaluator.build()
              ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 574, in build
          global_tool_logs(self._build_config_files, config_file, "Building Config Files")
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 96, in global_tool_logs
          raise e
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 92, in global_tool_logs
          return func()
                 ^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 641, in _build_config_files
          self.__write_workdir_file(config_filename, config_text, param_dict, is_template=is_template)
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 776, in __write_workdir_file
          value = fill_template(content, context=context, python_template_version=self.tool.python_template_version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        [Previous line repeated 7 more times]
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 123, in fill_template
          raise first_exception or e
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name' while searching for 'input.file_name'

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | \_\_input\_ext | ` "txt" ` |
       | chromInfo | ` "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
       | dbkey | ` "?" ` |
       | filter\_na | ` false ` |
       | max | ` "" ` |
       | numeric\_ns | ` "" ` |
       | source | ` {"__current_case__": 0, "organism": "hsapiens", "select_input_type": "select"} ` |
       | target | ` {"__current_case__": 0, "organism": "mmusculus", "select_input_type": "select"} ` |
       | tool\_settings | ` {"base_url": "http://biit.cs.ut.ee/gprofiler_archive3/e94_eg41_p11"} ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; gprofiler_orth (Test #2)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: gprofiler_orth, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: gprofiler_orth, exit_code: None, stderr: .
      ```
    **Traceback:**

    * ```console
      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 292, in prepare_job
          job_wrapper.prepare()
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1261, in prepare
          ) = tool_evaluator.build()
              ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 574, in build
          global_tool_logs(self._build_config_files, config_file, "Building Config Files")
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 96, in global_tool_logs
          raise e
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 92, in global_tool_logs
          return func()
                 ^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 641, in _build_config_files
          self.__write_workdir_file(config_filename, config_text, param_dict, is_template=is_template)
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/tools/evaluation.py", line 776, in __write_workdir_file
          value = fill_template(content, context=context, python_template_version=self.tool.python_template_version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 115, in fill_template
          return fill_template(
                 ^^^^^^^^^^^^^^
        [Previous line repeated 7 more times]
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 123, in fill_template
          raise first_exception or e
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/template.py", line 87, in fill_template
          return unicodify(t, log_exception=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/lib/galaxy/util/__init__.py", line 1153, in unicodify
          value = str(value)
                  ^^^^^^^^^^
        File "/Users/mvandenb/.planemo/gx_venv_3_release_23.2/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
          return getattr(self, mainMethName)()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "cheetah_DynamicallyCompiledCheetahTemplate_1701249081_045107_22080.py", line 118, in respond
      NameMapper.NotFound: cannot find 'file_name' while searching for 'input.file_name'

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | \_\_input\_ext | ` "txt" ` |
       | chromInfo | ` "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpskq2v3xv/galaxy-dev/tool-data/shared/ucsc/chrom/?.len" ` |
       | dbkey | ` "?" ` |
       | filter\_na | ` true ` |
       | max | ` "1" ` |
       | numeric\_ns | ` "WIKIGENE_ACC" ` |
       | source | ` {"__current_case__": 0, "organism": "mmusculus", "select_input_type": "select"} ` |
       | target | ` {"__current_case__": 0, "organism": "hsapiens", "select_input_type": "select"} ` |
       | tool\_settings | ` {"base_url": "http://biit.cs.ut.ee/gprofiler_archive3/e94_eg41_p11"} ` |

  </div></details>

</details>

DatsetFilenameWrapper likely needs to provide this. @jdavcs can you take a look at that ?

**Comment by mvdbeek** [comment]
This does prevent updating main to 23.2
