### ISSUE TITLE
Create or Update Organism Permission Denied Error 13

### ISSUE THREAD

**Issue by tylersun25** [galaxyproject/galaxy#17183]
**Describe the bug**
While running the structural workflow for a hybrid assembly and also a short-read assembly, I received a fatal error, saying that I do not have permission

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Created assembly from SPAdes and polished assembly with racon
2. Entered phage name and file (FASTA) into structural workflow
3. Ran the workflow
4. Error occurs when reaching the Create or Update Organism step

**Expected behavior**
Expected to finish workflow to start gene calling

Fatal error: Exit code 1 ()
Fatal error: 
Tool generated the following standard error:

Traceback (most recent call last):
  File "/galaxy/tools/cpt2/galaxy-tools/tools/webapollo/gga-apollo/create_or_update_organism.py", line 94, in <module>
    shutil.copytree(args.jbrowse_src, args.jbrowse, symlinks=True)
  File "/galaxy/tool_dependencies/_conda2/envs/mulled-v1-6e30e94176c826cd507c7589aec34fbb1f15b9501101942752ee5cacfab9ba49/lib/python3.9/shutil.py", line 566, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/galaxy/tool_dependencies/_conda2/envs/mulled-v1-6e30e94176c826cd507c7589aec34fbb1f15b9501101942752ee5cacfab9ba49/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/galaxy/tool_dependencies/_conda2/envs/mulled-v1-6e30e94176c826cd507c7589aec34fbb1f15b9501101942752ee5cacfab9ba49/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/apollo/data/galaxy/1087799'

![Screenshot 2023-12-13 100857](https://github.com/galaxyproject/galaxy/assets/153749210/c4b74142-7559-4a42-8e45-238ad85e7140)

**Comment by mvdbeek** [comment]
This looks like a problem with the webapollo tool, I would suggest that you report this where the galaxy webapollo is being developed (https://github.com/galaxy-genome-annotation/python-apollo/issues)

**Comment by hexylena** [comment]
It's a problem with a specific server's setup, help.galaxyproject.org  is more appropriate. @tylersun25 please let us know which server you're experiencing this on. `/galaxy/tools/cpt2/` indicates it likely isn't UseGalaxy.eu

**Comment by tylersun25** [comment]
It appears Apollo is offline for maintenance, so I don't think there's anything we can do
