### ISSUE TITLE
Postprocessing bug causing some tools with discover_datasets outputs to fail

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#17208]
**Describe the bug**
Jobs consistently fail for samtools_split and kallisto_pseudo since upgrading to release_23.1

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia, release_23.1

This is saved in the traceback field of affected jobs:
```
 Traceback (most recent call last):
   File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/runners/__init__.py", line 649, in _finish_or_resubmit_job
     job_wrapper.finish(
   File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/__init__.py", line 1941, in finish
     self.discover_outputs(job, inp_data, out_data, out_collections, final_job_state=final_job_state)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/__init__.py", line 2080, in discover_outputs
     self.tool.discover_outputs(
   File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/__init__.py", line 2270, in discover_outputs
     collected = output_collect.collect_primary_datasets(
   File "/mnt/galaxy/galaxy-app/lib/galaxy/job_execution/output_collect.py", line 531, in collect_primary_datasets
     primary_data = job_context.create_dataset(
   File "/mnt/galaxy/galaxy-app/lib/galaxy/model/store/discover.py", line 127, in create_dataset
     self.permission_provider.copy_dataset_permissions(init_from, primary_data)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/job_execution/output_collect.py", line 94, in copy_dataset_permissions
     self._security_agent.copy_dataset_permissions(init_from.dataset, primary_data.dataset, flush=False)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/model/security.py", line 1006, in copy_dataset_permissions
     self.set_all_dataset_permissions(dst, self.get_permissions(src), flush=flush)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/model/security.py", line 925, in set_all_dataset_permissions
     if not new and not dataset.shareable:
   File "/mnt/galaxy/galaxy-app/lib/galaxy/model/__init__.py", line 3935, in shareable
     return not object_store.is_private(self)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/objectstore/__init__.py", line 461, in is_private
     return self._invoke("is_private", obj)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/objectstore/__init__.py", line 413, in _invoke
     return self.__getattribute__(f"_{delegate}")(obj=obj, **kwargs)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/objectstore/__init__.py", line 976, in _is_private
     return self._call_method("_is_private", obj, ObjectNotFound, True)
   File "/mnt/galaxy/galaxy-app/lib/galaxy/objectstore/__init__.py", line 1197, in _call_method
     raise default(
 galaxy.exceptions.ObjectNotFound: objectstore, _call_method failed: _is_private on <galaxy.model.Dataset(None) at 0x7f63787a9af0>, kwargs: {}
```

From debug statements, for almost all jobs on Galaxy the output datasets have object_store_id set, but for output datasets from these jobs (samtools_split etc) the object_store_id is None at the point of the error pasted above.

We had a test instance with a hierarchical object store where this error was not occurring. After switching it to a distributed object store it has the same error as above.

The jobs started failing when Galaxy was upgraded from release_23.0 to release_23.1.  I can't replicate this error on either Galaxy Europe or Galaxy Main.

**Comment by abretaud** [comment]
Hi! We have the same error with this tool on usegalaxy.fr: https://github.com/geraldinepascal/FROGS-wrappers/blob/master/tools/frogs/phyloseq_beta_diversity.xml

**Comment by abretaud** [comment]
:tada: thanks @mvdbeek!
