### ISSUE TITLE
Workflows silently drop steps due to connection issues

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1724]
```
galaxy.workflow.run ERROR 2016-02-13 11:13:49,193 Failed to schedule Workflow[id=884,name=BICH464 PAP 2016 Part C - Functional Prediction + WA], proble
m occurred on WorkflowStep[index=29,type=tool].
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1159, in execute
    visit_input_values( tool.inputs, execution_state.inputs, callback, no_replacement_value=NO_REPLACEMENT )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 31, in visit_input_values
    visit_input_values( input.inputs, d, callback, new_name_prefix, new_label_prefix, no_replacement_value=no_replacement_value )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 31, in visit_input_values
    visit_input_values( input.inputs, d, callback, new_name_prefix, new_label_prefix, no_replacement_value=no_replacement_value )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 37, in visit_input_values
    visit_input_values( input.cases[current].inputs, values, callback, new_name_prefix, label_prefix, no_replacement_value=no_replacement_value )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 47, in visit_input_values
    prefixed_label=label_prefix + input.label )
  File "/galaxy/lib/galaxy/workflow/modules.py", line 1152, in callback
    replacement = progress.replacement_for_tool_input( step, input, prefixed_name )
  File "/galaxy/lib/galaxy/workflow/run.py", line 274, in replacement_for_tool_input
    replacement = [ self.replacement_for_connection( c ) for c in connection ]
  File "/galaxy/lib/galaxy/workflow/run.py", line 303, in replacement_for_connection
    raise Exception( message )
Exception: Workflow evaluation problem - failed to find output_name gff3_output_file in step_outputs {'output': <galaxy.model.HistoryDatasetAssociation
 object at 0x7f9021efbf10>}
galaxy.workflow.run ERROR 2016-02-13 11:13:49,193 Failed to execute scheduled workflow.
```

I think the error/result are fine, the bug is that there's no feedback to end users. Their jobs are just magically swallowed up by `/dev/null`

We're on/branched from dff94d743fd6e438f069deae5c9e8479357190cc because there were other show-stopped bugs that were introduced upstream, so if there are fixes, I won't be able to test them for ~2 weeks.

I don't have a situation to reproduce this on hand, but the way it generally goes is:
- I build a workflow (usually with my JBrowse tool). It has a dozen or so inputs
- I modify or remove a child tool
- I then add a new connection back to the jbrowse tool (though it isn't specific to jbrowse)
- this happens for the jbrowse step onwards

The problem is exacerbated for `multiple=True` on the jbrowse tool, because you don't notice if other "invisible" things are attached. With a single input, sometimes you'll try and connect and it _looks_ empty but isn't, so you hover and click the little X to remove some artefact of a connection. With multiple=True, no indication of artefacts, this happens.

**Comment by mvdbeek** [comment]
This one's also fixed by https://github.com/galaxyproject/galaxy/pull/7466
