### ISSUE TITLE
History export fails with `FileExistsError`

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17347]
This is from main:
```
Jan 18 17:41:21 galaxy07 celery[15997]: [2024-01-18 17:41:21,669: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7fc6243e9300> (args:('galaxy.write_history_to', 'f9090f12-ac5f-445c-bb0b-2518639d4c55', {'lang': 'py', 'task': 'galaxy.write_history_to', 'id': 'f9090f12-ac5f-445c-bb0b-2518639d4c55', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f9090f12-ac5f-445c-bb0b-2518639d4c55', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'request': WriteHistoryTo(model_store_format='rocrate.zip', include_files=True, include_deleted=True, include_hidden=True, target_uri='gxfiles://gxy-archiver/2024-01-18T17-41-21_bf947d1612a961de.rocrate.zip', history_id=664662, user=RequestUser(user_id=28), export_association_id=20441), 'task_user_id': 28}", 'origin': 'gen115480@galaxy-web-05', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'sentry-trace': '0c0f2a482e294f1fbcf1368f232ac0ed-a44ef6348d24a447-0', 'baggage':... kwargs:{})
Jan 18 17:41:24 galaxy07 celery[15997]: [2024-01-18 17:41:24,390: WARNING/main] Celery task execution failed for write_history_to to generate and stage a history store to file source URI write_history_to to generate and stage a history store to file source URI (2719.947 ms)
Jan 18 17:41:24 galaxy07 celery[15997]: [2024-01-18 17:41:24,722: ERROR/main] Task galaxy.write_history_to[f9090f12-ac5f-445c-bb0b-2518639d4c55] raised unexpected: FileExistsError(17, 'File exists')
Jan 18 17:41:24 galaxy07 celery[15997]: Traceback (most recent call last):
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Jan 18 17:41:24 galaxy07 celery[15997]: R = retval = fun(*args, **kwargs)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
Jan 18 17:41:24 galaxy07 celery[15997]: return self.run(*args, **kwargs)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/celery/__init__.py", line 185, in wrapper
Jan 18 17:41:24 galaxy07 celery[15997]: rval = app.magic_partial(func)(*args, **kwds)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/lagom/wrapping.py", line 28, in _bound_func
Jan 18 17:41:24 galaxy07 celery[15997]: return inner_func(*bound_args, **bound_kwargs)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/lagom/wrapping.py", line 45, in _error_handling_func
Jan 18 17:41:24 galaxy07 celery[15997]: return func(*args, **kwargs)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/celery/tasks.py", line 399, in write_history_to
Jan 18 17:41:24 galaxy07 celery[15997]: model_store_manager.write_history_to(request)
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/managers/model_stores.py", line 217, in write_history_to
Jan 18 17:41:24 galaxy07 celery[15997]: with model.store.get_export_store_factory(
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2380, in __exit__
Jan 18 17:41:24 galaxy07 celery[15997]: self._finalize()
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2748, in _finalize
Jan 18 17:41:24 galaxy07 celery[15997]: super()._finalize()
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2250, in _finalize
Jan 18 17:41:24 galaxy07 celery[15997]: datasets_attrs_out.write(to_json(datasets_attrs))
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2246, in to_json
Jan 18 17:41:24 galaxy07 celery[15997]: return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2246, in <listcomp>
Jan 18 17:41:24 galaxy07 celery[15997]: return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 389, in serialize
Jan 18 17:41:24 galaxy07 celery[15997]: return self._serialize(id_encoder, serialization_options)
Jan 18 17:41:24 galaxy07 celery[15997]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 5196, in _serialize
Jan 18 17:41:24 galaxy07 celery[15997]: self._handle_serialize_files(id_encoder, serialization_options, rval)
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 4905, in _handle_serialize_files
Jan 18 17:41:24 galaxy07 celery[15997]: serialization_options.serialize_files(self, rval)
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 377, in serialize_files
Jan 18 17:41:24 galaxy07 celery[15997]: self.serialize_files_handler.serialize_files(dataset, as_dict)
Jan 18 17:41:24 galaxy07 celery[15997]: File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 1936, in serialize_files
Jan 18 17:41:24 galaxy07 celery[15997]: add(src, dest)
Jan 18 17:41:24 galaxy07 celery[15997]: FileExistsError: [Errno 17] File exists: '/corral4/main/psufiles/003/041/dataset_3041568.dat' -> '/corral4/main/celery-archiver-scratch/tmpjvbu3_qq/export/datasets/Tophat_for_Illumina_on_data_4__splice_junctions_8.genetrack
```

**Comment by jmchilton** [comment]
I'm guessing this is an implicit conversion and would be fixed by https://github.com/galaxyproject/galaxy/pull/17346/files. I'm not sure how to verify this though.

**Comment by mvdbeek** [comment]
It's possible, but it also appears it would happen if you have history items of the same name in your history ?
`Tophat_for_Illumina_on_data_4__splice_junctions_8.genetrack` doesn't even include the dataset's hid.

**Comment by mvdbeek** [comment]
Oh, maybe, i'll check

**Comment by jmchilton** [comment]
There are more edge cases then tackled - that get more obsecure:

Extra flies might overlap - if implicitly converted:

```
arcname = os.path.join(dir_name, f"extra_files_path_{dataset_hid}")
```


And:

```
return f"{base}_{hid}.{ext}"
```

could conflict without conversion is you have a crazy history like:

```
1: my_fasta_2
2: my_fasta
```

So I'll write some test cases for those edges and try to work just generate new filenames if there are conflicts. I think these are written to disk serially so we can just see if things are already there.

**Comment by mvdbeek** [comment]
> Extra flies might overlap

I think I've seen that one before Nate moved the export to a separate handler.

**Comment by mvdbeek** [comment]
I think this was fixed some time ago
