### ISSUE TITLE
export fails when no index file & solution

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#17379]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.5.dev0
Commit: 1fe37b099f6f7da20c2483157bb2c1d94a766c67

**Describe the bug**

Related to https://github.com/galaxyproject/galaxy/issues/17372#issue-2104775142 but nothing to do with timeouts in spite of that being the error.

The error is the following
```
Traceback (most recent call last):
  File "/apps/others/galaxy/tools/data_export/export_remote.py", line 39, in write_if_not_exists
    file_source.write_from(file_source_path.path, real_data_path)
  File "/apps/others/galaxy/lib/galaxy/files/sources/__init__.py", line 300, in write_from
    self._write_from(target_path, native_path, user_context=user_context, opts=opts)
  File "/apps/others/galaxy/lib/galaxy/files/sources/_pyfilesystem2.py", line 69, in _write_from
    openfs.upload(target_path, read_file)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/fs/base.py", line 1417, in upload
    tools.copy_file_data(file, dst_file, chunk_size=chunk_size)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdavfs/webdavfs.py", line 91, in close
    super(WebDAVFile, self).close()
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdavfs/webdavfs.py", line 98, in flush
    self.res.read_from(self.data)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdav3/client.py", line 989, in read_from
    self.client.upload_to(buff=buff, remote_path=self.urn.path())
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdav3/client.py", line 67, in _wrapper
    res = fn(self, *args, **kw)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdav3/client.py", line 541, in upload_to
    self.execute_request(action='upload', path=urn.quote(), data=buff)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/webdav3/client.py", line 230, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://nextcloud.example.com/remote.php/webdav/Galaxy/somefile%20BWA-MEM.bam failed with code 408 and message: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>408 Request Timeout</title>\n</head><body>\n<h1>Request Timeout</h1>\n<p>Server timeout waiting for the HTTP request from the client.</p>\n<hr>\n<address>Apache/2.4.58 (Ubuntu) Server at nextcloud.example.com Port 443</address>\n</body></html>\n'
```

This was a nightmare to pin down...!
Turns out it occurs when the BAM file has not been indexed (not sure how this occured, dataset was created via `bwa-mem2` during a workflow). 
The server fails to transfer the last part of the BAM (`samtools quickcheck` fails) as it just timeouts waiting for the non-existent index.

What was really weird is that I think this happened even with `export metadata = false` (I'm not 100% sure as i was trying a few things while chasing the timeout error)

If you reset the metadata (which rebuilds the index) then it proceeds fine.

**Comment by alpapan** [comment]
turns out this is not true. it's part of https://github.com/galaxyproject/galaxy/issues/17372#issuecomment-1916561774
