### ISSUE TITLE
Issue about format data for Lefse

### ISSUE THREAD

**Issue by xiaojingguo666** [galaxyproject/galaxy#17397]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
[Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)](http://galaxy.biobakery.org/datasets/error)

**To Reproduce**
1. Go to ['...'](http://galaxy.biobakery.org/)
2. Click on '....'get data and upload data
3. Scroll down to 'LefSe'
4. See error Traceback (most recent call last):
  File "/usr/bin/lefse_format_input.py", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/lefse_format_input.py", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/lefse_format_input.py", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3266, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lefse==1.1.2' distribution was not found and is required by the application

**Expected behavior**

**Screenshots**
<img width="1440" alt="image" src="https://github.com/galaxyproject/galaxy/assets/158235782/98159ca1-cca2-4f91-8408-90b7680e8f5a">

**Additional context**

**Comment by hexylena** [comment]
Hi @xiaojingguo666 we don't provide support for specific servers, I'm afraid you'll need to contact the admins of your server. I checked galaxy.biobakery.org but they don't provide the support information in the usual place, but perhaps you can find some contact information here: https://huttenhower.sph.harvard.edu/lefse/
