### ISSUE TITLE
Some broken ITs on dev server with release 23.2

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#17438]
**Describe the bug**
Interactive tools ethercalc and phinch fail immediately with the job info 'Job Failed'. 

In the handler logs is a lot of traceback like this:
```
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]: Traceback (most recent call last):
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/runners/pulsar.py", line 493, in __prepare_job
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     job_wrapper.prepare(**prepare_kwds)
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/__init__.py", line 1253, in prepare
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     self.interactivetools = tool_evaluator.populate_interactivetools()
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/evaluation.py", line 535, in populate_interactivetools
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     val = fill_template(
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/template.py", line 115, in fill_template
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     return fill_template(
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/template.py", line 115, in fill_template
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     return fill_template(
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/template.py", line 115, in fill_template
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     return fill_template(
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   [Previous line repeated 7 more times]
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/template.py", line 123, in fill_template
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     raise first_exception or e
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/template.py", line 87, in fill_template
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     return unicodify(t, log_exception=False)
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/util/__init__.py", line 1153, in unicodify
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     value = str(value)
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "/mnt/galaxy/venv/lib/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:     return getattr(self, mainMethName)()
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]:   File "cheetah_DynamicallyCompiledCheetahTemplate_1707364503_2717764_60215.py", line 87, in respond
Feb 08 03:55:03 dev-handlers galaxyctl[3189957]: NameMapper.NotFound: cannot find 'infile'
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia Dev, release_23.2

I've stopped it from breaking at this point on the dev server by reverting the change to the file `lib/galaxy/jobs/__init__.py` in this PR https://github.com/galaxyproject/galaxy/commit/cf3fe8883b52f590c921c0a3e30507c7de74f078.  Since `tool_evaulator.populate_interactivetools` now occurs before `tool_evaluator.set_compute_environment`, the tool_params dict is empty and a value like "Phinch Visualisation of $infile.display_name" cannot be templated. Ping @sveinugu

**Comment by sveinugu** [comment]
@natefoo This issue will currently cause `Panoply` and `Phinch` to fail on `usegalaxy.org`, I believe (based on the code, have not tested). @mvdbeek has provided a fix (yet to be merged).

Btw: `RStudio` is also not working, probably due to the need to configure nginx for path-based interactive tools: https://docs.galaxyproject.org/en/master/admin/special_topics/interactivetools.html#nginx-proxy-server-configuration-in-production
