### ISSUE TITLE
s3fs file source plugin (and possibly others) unusable with `AttributeError: 'FilesSourceOptions' object has no attribute 'extra_props'`

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#17442]
**Describe the bug**
```pytb
galaxy.managers.remote_files WARNING 2024-02-08 11:38:24,307 [pN:main.1,p:741299,tN:MainThread] Problem listing file source path FileSourcePath(file_source=<galaxy.files.sources.s3fs.S3FsFilesSource object at 0x7f3757090210>, path='/')
Traceback (most recent call last):
  File "/home/nate/work/galaxy/lib/galaxy/managers/remote_files.py", line 84, in index
    index = file_source.list(
            ^^^^^^^^^^^^^^^^^
  File "/home/nate/work/galaxy/lib/galaxy/files/sources/__init__.py", line 296, in list
    return self._list(path, recursive, user_context, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nate/work/galaxy/lib/galaxy/files/sources/s3fs.py", line 54, in _list
    fs = self._open_fs(user_context=user_context, opts=opts)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nate/work/galaxy/lib/galaxy/files/sources/s3fs.py", line 84, in _open_fs
    extra_props = opts.extra_props or {} if opts else {}
                  ^^^^^^^^^^^^^^^^
AttributeError: 'FilesSourceOptions' object has no attribute 'extra_props'
```

Breaking commit from bisect is 6fb9349541c36263883114ec2701e3bcbafa7c23

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2.dev0
Commit: 6fb9349541c36263883114ec2701e3bcbafa7c23

**To Reproduce**
1. Configure file source:
   ```yaml
   - type: s3fs
     label: Genome Ark
     id: genomeark
     doc: Access to Genome Ark open data on AWS.
     bucket: genomeark
     anon: true
   ```
2. Attempt to "Choose remote files" from this file source

**Comment by davelopez** [comment]
> Breaking commit from bisect is https://github.com/galaxyproject/galaxy/commit/6fb9349541c36263883114ec2701e3bcbafa7c23

Sorry... and wild... I would not expect adding a prop to break this, but it might certainly be related to what Marius mentioned here https://github.com/galaxyproject/galaxy/pull/17445#discussion_r1484048431

**Comment by natefoo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17445, thank you @nuwang!
