### ISSUE TITLE
Error building phylocanvas during fresh installation of Galaxy

### ISSUE THREAD

**Issue by erik-azn** [galaxyproject/galaxy#17599]
**Describe the bug**
I'm installing Galaxy (release_23.2) on a linux server (Debian) and while building the client I get the following error:

```
Building phylocanvas
$ parcel build src/script.js -d static
🚨  /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/@loaders.gl/core/node_modules/@probe.gl/log/dist/utils/hi-res-timestamp.js: Unexpected token: punc (.)
    at Z.get (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:577:19)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 7)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 4)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 4)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 7)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 4)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 1)
    at async Bundler.loadAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/srv/galaxy/config/plugins/visualizations/phylocanvas/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error building phylocanvas, not saving build state.  Please report this issue to the Galaxy Team.
No changes detected for pv
No changes detected for nora
No changes detected for venn
No changes detected for ts_visjs
No changes detected for new_user
[11:49:27] Finished 'buildPlugins' after 7.41 s
[11:49:27] Starting 'cleanPlugins'...
[11:49:27] Finished 'fonts' after 7.42 s
Building icon pack "galaxy"
 - loading icon "gxd galaxyLogo" from file "galaxyLogo.duotone.svg"
 - loading icon "gxd textLarger" from file "textLarger.duotone.svg"
 - loading icon "gxd textSmaller" from file "textSmaller.duotone.svg"
Saving generated Icon Pack to: "./src/assets/icons.json"
Icons built successfully
[11:49:28] Finished 'icons' after 7.48 s
[11:49:28] Finished 'cleanPlugins' after 81 ms
[11:49:28] Starting 'stagePlugins'...
[11:49:28] Finished 'stagePlugins' after 471 ms
[11:49:28] Finished 'default' after 7.96 s
$ GXY_BUILD_SOURCEMAPS=1 NODE_ENV=production webpack
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Galaxy client build failed. See ./client/README.md for more information, including how to get help.
```
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2

**To Reproduce**
1. `git clone -b release_23.2 https://github.com/galaxyproject/galaxy.git`
2. `cd galaxy`
3. `virtualenv .venv`
4. `. ./.venv/bin/activate`
5. `sh run.sh`

**Expected behavior**
Complete installation of Galaxy

**Screenshots**

**Additional context**

**Comment by erik-azn** [comment]
Never mind. It was an out of memory error. I added more swap and the build was succesfull.

**Comment by dannon** [comment]
@erik-azn Thanks for following up, glad you sorted it out!
