### ISSUE TITLE
gunicorn/celery/ fails with no such file or directory

### ISSUE THREAD

**Issue by ChristophKnapp** [galaxyproject/galaxy#17633]
**Describe the bug**
I'm trying to reinstall the galaxy server. It was installed on the computer before and worked. We had problems installing modules so we decided to reinstall. The install finishes but there are problems with gunicorn/celery. Galaxy seems to run but its not available via localhost or in the network. In all log files in .../database/gravity/log/ the following error can be found.

```
Working directory: /home/galaxy/galaxy
Executing: PYTHONPATH=lib GALAXY_CONFIG_FILE=/home/galaxy/galaxy/config/galaxy.yml celery --app galaxy.celery beat --loglevel DEBUG --schedule /home/galaxy/galaxy/database/gravity/celery-beat-schedule
Traceback (most recent call last):
  File "/home/galaxy/galaxy/.venv/bin/galaxyctl", line 8, in <module>
    sys.exit(galaxyctl())
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/gravity/commands/cmd_exec.py", line 21, in cli
    pm.exec(instance_names=instances_services, service_instance_number=service_instance, no_exec=no_exec)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/gravity/process_manager/__init__.py", line 349, in exec
    return self._process_executor.exec(config, service, service_instance_number=service_instance_number, no_exec=no_exec)
  File "/home/galaxy/galaxy/.venv/lib/python3.10/site-packages/gravity/process_manager/__init__.py", line 291, in exec
    os.execvpe(cmd[0], cmd, env)
  File "/usr/local/lib/python3.10/os.py", line 584, in execvpe
    _execvpe(file, args, env)
  File "/usr/local/lib/python3.10/os.py", line 617, in _execvpe
    raise last_exc
  File "/usr/local/lib/python3.10/os.py", line 608, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory: b'/opt/yasara/celery'
```

In /opt/yasara is a program installed on the system which has nothing to do with galaxy. See 
http://www.yasara.org/.
I'm not sure why its looking for files there. Yasara was already there when galaxy was installed the first time. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
I'm not sure you will be able to, but any insight is much appreciated. 

**Expected behavior**

**Screenshots**

**Additional context**
I changed the galaxy.yml according to https://galaxyproject.org/admin/get-galaxy/#configure so it is accessible in the network and added email addresses for admin users as well as changed the port to 6060. 
see file for output from 
output of sh run.sh > install.log 
[celery.log](https://github.com/galaxyproject/galaxy/files/14525836/celery.log)
[celery-beat.log](https://github.com/galaxyproject/galaxy/files/14525837/celery-beat.log)
[gunicorn.log](https://github.com/galaxyproject/galaxy/files/14525838/gunicorn.log)
[install.log](https://github.com/galaxyproject/galaxy/files/14525848/install.log)

**Comment by ChristophKnapp** [comment]
After I set a value for log_destination in galaxy.yml it works again. For some reason it would not write logs in in database/gravity/log directory.
