### ISSUE TITLE
objectstore: _call_method failed: get_filename

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1765]
In rare cases I get this in my log. I can not really reproduce it but sometimes it happes during copying histories.

```
galaxy.objectstore WARNING 2016-02-19 09:03:43,522 The backend object store ID (None) for Dataset object with ID 92807 is invalid
galaxy.datatypes.interval ERROR 2016-02-19 09:03:43,523 Exception caught attempting to generate viewport for dataset '104946'
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/datatypes/interval.py", line 169, in get_estimated_display_viewport
    fh = open( dataset.file_name )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1853, in get_file_name
    return self.dataset.get_file_name()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1658, in get_file_name
    filename = self.object_store.get_filename( self )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 477, in get_filename
    return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 498, in _call_method
    % ( method, str( obj ), str( kwargs ) ) )
ObjectNotFound: objectstore, _call_method failed: get_filename on <galaxy.model.Dataset object at 0x20995250>, kwargs: {}
galaxy.objectstore WARNING 2016-02-19 09:03:44,272 The backend object store ID (None) for Dataset object with ID 92811 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:44,620 The backend object store ID (None) for Dataset object with ID 92812 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:45,478 The backend object store ID (None) for Dataset object with ID 92816 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:45,953 The backend object store ID (None) for Dataset object with ID 92817 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:46,277 The backend object store ID (None) for Dataset object with ID 92818 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:46,581 The backend object store ID (None) for Dataset object with ID 92819 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:46,882 The backend object store ID (None) for Dataset object with ID 92820 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:47,185 The backend object store ID (None) for Dataset object with ID 92821 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:47,460 The backend object store ID (None) for Dataset object with ID 92822 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:47,782 The backend object store ID (None) for Dataset object with ID 92823 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:48,143 The backend object store ID (None) for Dataset object with ID 97473 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:48,421 The backend object store ID (None) for Dataset object with ID 97474 is invalid
galaxy.objectstore WARNING 2016-02-19 09:03:48,628 The backend object store ID (None) for Dataset object with ID 97475 is invalid
```

This is my objectstore conf file:

```
<?xml version="1.0"?>
<object_store type="hierarchical">
    <backends>
        <object_store type="distributed" id="primary" order="0">
            <backends>
                <backend id="files2" type="disk" weight="1">
                    <files_dir path="/data/2/galaxy_db/files"/>
                    <extra_dir type="temp" path="/data/2/galaxy_db/tmp"/>
                    <extra_dir type="job_work" path="/data/2/galaxy_db/job_working_directory"/>
                </backend>
                <backend id="files3" type="disk" weight="1">
                    <files_dir path="/data/3/galaxy_db/files"/>
                    <extra_dir type="temp" path="/data/3/galaxy_db/tmp"/>
                    <extra_dir type="job_work" path="/data/3/galaxy_db/job_working_directory"/>
                </backend>
            </backends>
        </object_store>
        <object_store type="disk" id="secondary" order="1">
            <files_dir path="/data/0/galaxy_db/files"/>
            <extra_dir type="temp" path="/data/0/galaxy_db/tmp"/>
            <extra_dir type="job_work" path="/data/0/galaxy_db/job_working_directory"/>
        </object_store>
    </backends>
</object_store>

```

**Comment by bgruening** [comment]
@dannon do you have any idea how I can debug this further? I have bumped in this again. It seems that the entire history can not import and that all datasets can not be imported into Jupyter for example with the same error message. So bioblend fetching this file also does not work.

**Comment by bgruening** [comment]
![pastedimage](https://cloud.githubusercontent.com/assets/469983/16995376/503ccc46-4eac-11e6-80b1-1ce118b7aa56.png)

One new occurrence, this time copying a dataset into a data library.

**Comment by dannon** [comment]
@bgruening Interesting.  I haven't tried to reproduce this here yet, but if you do the same operation again (adding those same datasets to the same library), does it fail?

**Comment by bgruening** [comment]
Yes, it always fails. In the above example it helped to copy the dataset into a new history. Not sure about the screenshot, I just ask if copying the dataset helped here as well.

**Comment by bgruening** [comment]
New stacktrace with 17.01:
```
galaxy.jobs.runners ERROR 2017-03-01 16:02:12,603 Unhandled exception checking active jobs
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 542, in monitor
    self.check_watched_items()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/drmaa.py", line 301, in check_watched_items
    if ajs.check_limits():
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 477, in check_limits
    limit_state = self.job_wrapper.check_limits( runtime=runtime )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1574, in check_limits
    for outfile, size in self.get_output_sizes():
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1564, in get_output_sizes
    output_paths = self.get_output_fnames()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1636, in get_output_fnames
    self.compute_outputs()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1661, in compute_outputs
    dataset_path = DatasetPath( da.dataset.dataset.id, da.dataset.file_name, false_path=da_false_path, mutable=mutable )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1911, in get_file_name
    return self.dataset.get_file_name()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1716, in get_file_name
    filename = self.object_store.get_filename( self )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 495, in get_filename
    return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 516, in _call_method
    % ( method, str( obj ), str( kwargs ), str(obj.id), str(obj.external_filename), str(obj.state) ) )
ObjectNotFound: objectstore, _call_method failed: get_filename on <galaxy.model.Dataset object at 0x2f80e610>, kwargs: {}

```

**Comment by bgruening** [comment]
Two of these errors (but not all) do have this in the database:
```
galaxy=> select * from dataset where id = 3798934;
   id    |        create_time        |        update_time         |  state  | deleted | purged | purgable | external_filename | _extra_files_path | file_size | total_size | object_store_id |               uuid               
---------+---------------------------+----------------------------+---------+---------+--------+----------+-------------------+-------------------+-----------+------------+-----------------+----------------------------------
 3798934 | 2017-03-10 15:00:07.70034 | 2017-03-15 07:45:09.351817 | running | t       | t      | t        |                   |                   |         0 |          0 | files2          | a8f97fcd05c34daa9eb47006ab75fe72
(1 row)

galaxy=> 
galaxy=> select * from dataset where id = 3786913;
   id    |        create_time         |        update_time         |  state  | deleted | purged | purgable | external_filename | _extra_files_path | file_size | total_size | object_store_id |               uuid               
---------+----------------------------+----------------------------+---------+---------+--------+----------+-------------------+-------------------+-----------+------------+-----------------+----------------------------------
 3786913 | 2017-03-07 13:49:41.592104 | 2017-03-10 14:55:11.587073 | running | t       | t      | t        |                   |                   |         0 |          0 | files4          | 1f2c4ee3ddee47ada6b65c5e0ee6ccc7
(1 row)
```

Running, but deleted?
