### ISSUE TITLE
TypeError: get_tag_by_id() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1766]
Just had this on our production instance's server log

```
[pid: 43373|app: 0|req: 2354/8115] 81.64.220.159 () {46 vars in 1532 bytes} [Tue Feb 16 00:25:30 2016] GET /workflow/load_workflow?id=e8482118860a7e3e&_=1455578730118 => generated 667485 bytes in 3580 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 2)
81.64.220.159 - - [16/Feb/2016:00:25:42 +0200] "GET /tag/tag_autocomplete_data?item_id=e8482118860a7e3e&item_class=StoredWorkflow&q=gras HTTP/1.1" 500 - "https://mississippi.snv.jussieu.fr/workflow/editor?id=e8482118860a7e3e" "Mozilla/5.0 (Macintosh; Intel Mac OS X $
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    return self.app( environ, start_response )
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 22, in __call__
    return self.app( environ, start_response )
  File "lib/galaxy/web/framework/middleware/translogger.py", line 70, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 163, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 178, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/usr/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 151, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 126, in __call__
    return self.handle_request( environ, start_response )
  File "lib/galaxy/web/framework/base.py", line 184, in handle_request
    body = method( trans, **kwargs )
  File "lib/galaxy/web/framework/decorators.py", line 66, in decorator
    return func( self, trans, *args, **kwargs )
  File "lib/galaxy/webapps/galaxy/controllers/tag.py", line 96, in tag_autocomplete_data
    return self._get_tag_autocomplete_names( trans, q, limit, timestamp, user, item, item_class )
  File "lib/galaxy/webapps/galaxy/controllers/tag.py", line 130, in _get_tag_autocomplete_names
    tag = self.get_tag_handler( trans ).get_tag_by_id( trans, row[0] )
TypeError: get_tag_by_id() takes exactly 2 arguments (3 given)
```

Unfortunately I don't really now how to trigger this.

**Comment by mvdbeek** [comment]
This is on release_16.01, commit ff29b263630614b96c617eb9468afcec9d04d72f

**Comment by mvdbeek** [comment]
Haven't seen this in the last month. Closing.
