### ISSUE TITLE
set metadata fails with `AttributeError: 'str' object has no attribute 'get'`

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#17823]
Seen after 24.0 update.
```
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]: galaxy.jobs.runners ERROR 2024-03-23 13:03:54,287 [pN:handler_sn06_0,p:2718919,tN:CondorRunner.work_thread-1] (68201246/48592776) Job wrapper finish method failed
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]: Traceback (most recent call last):
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:   File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 655, in _finish_or_resubmit_job
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:     job_wrapper.finish(
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:   File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1883, in finish
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:     if check_output_detected_state == DETECTED_JOB_STATE.OK and not tool_provided_metadata.has_failed_outputs():
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:   File "/opt/galaxy/server/lib/galaxy/tool_util/provided_metadata.py", line 222, in has_failed_outputs
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:     if meta.get("failed", False):
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]:        ^^^^^^^^
Mar 23 13:03:54 sn06.galaxyproject.eu python[2718919]: AttributeError: 'str' object has no attribute 'get'
```

**Comment by mvdbeek** [comment]
I think this might have been a transient issue for a s all subset of jobs that started before the 24.0 upgrade and finished after. I think it's difficult to provide a decent fix for this and it's not likely to re-occur from here on.
