### ISSUE TITLE
[24.0] IUC tool test failure

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17822]
**Describe the bug**

[IUC tool test](https://github.com/galaxyproject/tools-iuc/pull/5896) fails with

```
galaxy.web.framework.decorators ERROR 2024-03-23 11:15:57,832 [pN:main.1,p:4619,tN:WSGI_0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/web/framework/decorators.py", line 346, in decorator
    rval = func(self, trans, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/webapps/galaxy/api/tools.py", line 593, in create
    return self.service._create(trans, payload, **kwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/webapps/galaxy/services/tools.py", line 171, in _create
    vars = tool.handle_input(
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/__init__.py", line 1885, in handle_input
    all_params, all_errors, rerun_remap_job_id, collection_info = self.expand_incoming(
                                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/__init__.py", line 1844, in expand_incoming
    populate_state(
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 409, in populate_state
    _populate_state_legacy(
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 520, in _populate_state_legacy
    state[input.name] = input.get_initial_value(request_context, context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/grouping.py", line 796, in get_initial_value
    rval[child_input.name] = child_input.get_initial_value(trans, child_context)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 1107, in get_initial_value
    options = list(self.get_options(trans, other_values))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 960, in get_options
    return self.options.get_options(trans, other_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/dynamic_options.py", line 874, in get_options
    options = self.get_fields(trans, other_values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/dynamic_options.py", line 753, in get_fields
    options += self.get_user_options(trans.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/dynamic_options.py", line 769, in get_user_options
    by_dbkey.update(self.hda_to_table_entries(hda, self.tool_data_table_name))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp0iydugny/galaxy-dev/lib/galaxy/tools/parameters/dynamic_options.py", line 781, in hda_to_table_entries
    if dbkey := value.get("dbkey"):
                ^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: 

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**

See IUC CI

**Comment by mvdbeek** [comment]
One of the preceding tests generated a tool data table and the heuristic that determines if this is a data bundle (size != total size) failed *and* this data table doesn't contain dbkeys and likely a third factor made this fail ...
