### ISSUE TITLE
user authentication fails with error "Uncaught exception in exposed API method" due to duplicate private role associations in Galaxy DB

### ISSUE THREAD

**Issue by sanjaysrikakulam** [galaxyproject/galaxy#17848]
**Describe the bug**
**A clear and concise description of what the bug is.**
A couple of users of https://usegalaxy.eu raised an issue about being unable to log in with their user accounts. They see the error `Uncaught exception in exposed API method`. 

Looking at the Gunicorn logs, we see the below 

```
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]: galaxy.webapps.galaxy.controllers.user DEBUG 2024-03-27 10:36:57,751 [pN:main.3,p:2415770,tN:WSGI_1] trans.app.config.auth_config_file: /opt/galaxy/config/auth_conf.xml
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]: galaxy.auth.providers.localdb DEBUG 2024-03-27 10:36:57,751 [pN:main.3,p:2415770,tN:WSGI_1] User: 355, LOCALDB: True
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[1834821]: uvicorn.access INFO 2024-03-27 10:36:57,755 [pN:main.2,p:1971643,tN:MainThread] 132.230.153.41:0 - "GET /api/entry_points?running=true HTTP/1.0" 200
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[3163677]: uvicorn.access INFO 2024-03-27 10:36:57,755 [pN:main.2,p:2412062,tN:MainThread] 130.113.246.226:0 - "GET /api/notifications/status?since=2024-03-27T09%3A36%3A52.137 HTTP/1.0" 200
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]: galaxy.web.framework.decorators ERROR 2024-03-27 10:36:57,759 [pN:main.3,p:2415770,tN:WSGI_1] Uncaught exception in exposed API method:
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]: Traceback (most recent call last):
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/web/framework/decorators.py", line 346, in decorator
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     rval = func(self, trans, *args, **kwargs)
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/user.py", line 143, in login
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     return self.__validate_login(trans, payload, **kwd)
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/user.py", line 200, in __validate_login
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     trans.handle_user_login(user)
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/webapps/base/webapp.py", line 841, in handle_user_login
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     self.app.security_agent.create_user_role(user, self.app)
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/model/security.py", line 754, in create_user_role
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     self.get_private_user_role(user, auto_create=True)
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/server/lib/galaxy/model/security.py", line 775, in get_private_user_role
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     role = self.sa_session.execute(stmt).scalar_one_or_none()
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1225, in scalar_one_or_none
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     return self._only_one_row(
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:            ^^^^^^^^^^^^^^^^^^^
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]:     raise exc.MultipleResultsFound(
Mar 27 10:36:57 sn06.galaxyproject.eu gunicorn[2375622]: sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
```

As an admin user, impersonation also fails with the error, `Admin access required for /admins/users`, and the admin user is immediately logged out.

In the Gunicorn logs, we can see the following

```
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]: galaxy.webapps.galaxy.controllers.admin ERROR 2024-03-26 22:02:51,067 [pN:main.4,p:1806988,tN:WSGI_5] Error fetching user for impersonation
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]: Traceback (most recent call last):
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/controllers/admin.py", line 632, in impersonate
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     trans.handle_user_login(user)
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/server/lib/galaxy/webapps/base/webapp.py", line 841, in handle_user_login
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     self.app.security_agent.create_user_role(user, self.app)
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/server/lib/galaxy/model/security.py", line 754, in create_user_role
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     self.get_private_user_role(user, auto_create=True)
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/server/lib/galaxy/model/security.py", line 775, in get_private_user_role
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     role = self.sa_session.execute(stmt).scalar_one_or_none()
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1225, in scalar_one_or_none
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     return self._only_one_row(
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:            ^^^^^^^^^^^^^^^^^^^
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]:     raise exc.MultipleResultsFound(
Mar 26 22:02:51 sn06.galaxyproject.eu gunicorn[1674243]: sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
```

As admin user, I also tried to reset the password and the login with the new password which also fails with a similar message as above and we can see the following in the logs,

```
Mar 27 10:31:44 sn06.galaxyproject.eu gunicorn[2636082]: uvicorn.access INFO 2024-03-27 10:31:44,284 [pN:main.4,p:2761284,tN:MainThread] 103.144.27.130:0 - "GET /api/entry_points?running=true HTTP/1.0" 200
Mar 27 10:31:44 sn06.galaxyproject.eu gunicorn[2098977]: galaxy.webapps.galaxy.controllers.user DEBUG 2024-03-27 10:31:44,298 [pN:main.3,p:2225471,tN:WSGI_2] trans.app.config.auth_config_file: /opt/galaxy/config/auth_conf.xml
Mar 27 10:31:44 sn06.galaxyproject.eu gunicorn[2098977]: galaxy.auth.providers.localdb DEBUG 2024-03-27 10:31:44,298 [pN:main.3,p:2225471,tN:WSGI_2] User: 355, LOCALDB: False
Mar 27 10:31:44 sn06.galaxyproject.eu gunicorn[2098977]: uvicorn.access INFO 2024-03-27 10:31:44,299 [pN:main.3,p:2225471,tN:MainThread] 132.230.153.41:0 - "POST /user/login HTTP/1.0" 400
```

With the help of @davelopez and the traceback, we further looked into the DB after translating the [sqlalchemy query to raw SQL](https://github.com/galaxyproject/galaxy/blob/6b96bb17b2099c527fd5e6b02699e8f6b81b6593/lib/galaxy/model/security.py#L767-L775) and found out that the users have redundant private role associations, for example (2 different users):

```
galaxy=> SELECT Role.* FROM Role JOIN user_role_association ON Role.id = user_role_association.role_id WHERE user_role_association.user_id=355  AND type='private';
 id  |        create_time         |        update_time        |               name                |                    description                     |  type   | deleted
-----+----------------------------+---------------------------+-----------------------------------+----------------------------------------------------+---------+---------
 470 | 2016-03-21 09:51:57.783569 | 2023-08-21 11:44:49.61498 | XXXXXXX | Private role for XXXXXXX | private | f
 470 | 2016-03-21 09:51:57.783569 | 2023-08-21 11:44:49.61498 | XXXXXXX | Private role for XXXXXXX | private | f
(2 rows)

galaxy=> select * from user_role_association where user_id=355;
  id   | user_id | role_id |        create_time         |        update_time
-------+---------+---------+----------------------------+----------------------------
   944 |     355 |     470 | 2016-03-21 09:51:57.880974 | 2016-03-21 09:51:57.88101
  1015 |     355 |     470 | 2016-07-07 07:27:54.516883 | 2016-07-07 07:27:54.516912
 61958 |     355 |  516498 | 2022-09-07 10:48:27.798524 | 2022-09-07 10:48:27.798541
 68163 |     355 |  522523 | 2022-11-30 13:24:24.601055 | 2022-11-30 13:24:24.601058
 92362 |     355 |      44 | 2023-11-22 15:01:42.380959 | 2023-11-22 15:01:42.380964
(5 rows)


galaxy=> SELECT Role.* FROM Role JOIN user_role_association ON Role.id = user_role_association.role_id WHERE user_role_association.user_id=431  AND type='private';
 id  |        create_time         |        update_time         |                    name                    |                         description                         |  type   | deleted
-----+----------------------------+----------------------------+--------------------------------------------+-------------------------------------------------------------+---------+---------
 582 | 2016-11-29 10:32:32.686664 | 2017-05-26 13:15:04.262206 | YYYYYYY | Private role for YYYYYYY | private | f
 582 | 2016-11-29 10:32:32.686664 | 2017-05-26 13:15:04.262206 | YYYYYYY | Private role for YYYYYYY | private | f
(2 rows)

galaxy=> select * from user_role_association where user_id=431;
  id   | user_id | role_id |        create_time         |        update_time
-------+---------+---------+----------------------------+----------------------------
  1313 |     431 |     582 | 2016-11-29 10:32:32.751182 | 2016-11-29 10:32:32.751218
  1314 |     431 |     582 | 2016-11-29 10:33:55.138342 | 2016-11-29 10:33:55.138365
  1562 |     431 |     719 | 2017-02-13 15:11:57.180841 | 2017-02-13 15:11:57.180871
  1682 |     431 |     760 | 2017-05-31 13:13:47.21879  | 2017-05-31 13:13:47.218821
  2368 |     431 |      28 | 2018-03-03 17:09:22.209563 | 2018-03-03 17:09:22.209588
  4660 |     431 |    3181 | 2018-11-07 16:07:27.534022 | 2018-11-07 16:07:27.534043
 29240 |     431 |   89158 | 2020-12-22 09:58:03.746384 | 2020-12-22 09:58:03.746396
 42525 |     431 |  407877 | 2021-09-14 09:58:01.21973  | 2021-09-14 09:58:01.219741
 15746 |     431 |   13573 | 2020-02-12 14:43:59.982101 | 2020-02-12 14:43:59.98212
 61812 |     431 |  516356 | 2022-09-03 12:21:29.050981 | 2022-09-03 12:21:29.050986
(10 rows)
```

The `create_time` shows that the role associations were created in 2016 (also, with another SQL query (see below), we see 265 entries having more than 1 private role association (some even have more than 2)). This could have been a bug in the 2016 release and later fixed. However, this has only become a problem now with the latest 24.0 release. 

Query shared by @hexylena 
```
with cte as (select user_id::text || '-' || role_id::text as j, count(*) as count, min(create_time) as create_time from user_role_association group by j) select * from cte where count > 1 order by create_time asc;
```

In the past, Galaxy used `one_or_none`, and now in release 24.0 `scalar_one_or_none` [in](https://github.com/galaxyproject/galaxy/commit/3fd5b0252f840dbb92aaebf31b9d21034b21c578#diff-b07a08502698738be2736c7f8dccd7614ccc084764e3895a8956c1495cfd3e6fL761). In both cases,. This should have resulted in a `MultipleResultsFound` error and should have failed even in the past. 

**Edit**
In the EU, we see 265 entries with more than 1 private role association and `create_time` range between 2013-02-18 and 2017-09-14.

**Comment by sanjaysrikakulam** [comment]
ping @bgruening.

**Comment by mvdbeek** [comment]
milestones are issues that prevent a release, given this is an old bug this does not prevent a release. I'm not even certain this requires any change in galaxy, db admins will likely have to clean this up out of band

**Comment by mvdbeek** [comment]
This has nothing to do with 24.0, we've been seeing this for years. We have an established release process that we follow for handling bugs.

**Comment by mvdbeek** [comment]
> However, this has only become a problem now with the latest 24.0 release.

What is that based on ?

> This should have resulted in a MultipleResultsFound error and should have failed even in the past.

And it has

**Comment by mvdbeek** [comment]
Few people ever complained for us either, but this has been present in the logs for years. It's a moot point, we'll obviously fix it, but it is much easier for maintainers if we don't need to bother with nonsense labels that don't affect the fix, but do delay the release for no reason.

Here's an older example from 23.2, but again, it's been there for much longer: https://sentry.galaxyproject.org/share/issue/1cde4db202a04ca7b384be00f0f354c2/

You can cause this by changing your email address to one already taken.

**Comment by bgruening** [comment]
Not sure what you want us here to prove.

Users, that you know, used their account last week and can NOT log in anymore in 24.0. I would call that a good reason and not nonsense. But ok ... your call.

To summarize, I do not care how the multiple roles are created, or if they existed for 10 years, the point is that those users can for 2 days not log in anymore in 24.0 which they could before.

**Comment by mvdbeek** [comment]
https://github.com/usegalaxy-eu/galaxy/issues/232#issuecomment-2022660384 sure sounds like it would cause that, all I'm saying is that the label doesn't make sense and that it would be great if you know and used the label correctly in the future.

**Comment by bgruening** [comment]
Thanks for your comment.
I try to sum up, we have currently 3 users reporting that they can not log in anymore, and potentially 200 more. All of them get an error message on the login page. I do consider that release-blocking issues. You don't. Good.
