### ISSUE TITLE
Tool Recommendations doesn't work with Python 3.11 and tensorflow 2.16.1

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17857]
**Describe the bug**
We currently pin the conditional requirement for `tensorflow` to `2.9.3` (and that is fine for Python versions below 3.11). In case we unpin it to use Python 3.11 then there is a breaking change in [TensorFlow 2.16.1](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1) that affects tool recommendations.

So with Python 3.11 the last version of tensorflow that works is 2.15.1.

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Use at least Python 3.11 for your Galaxy
2. Enable tool recommendations in the config `enable_tool_recommendations: true`
3. Run a tool, for example `Filter1`
4. Observe the error in the server console.

**Expected behavior**
We should update the conditional requirement depending on the Python version or fix the code in tool recommendations.

**Additional context**
```
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]: galaxy.web.framework.decorators ERROR 2024-03-26 21:02:28,265 [pN:main.3,p:2366310,tN:WSGI_4] Uncaught exception in exposed API method:
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]: Traceback (most recent call last):
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/server/lib/galaxy/web/framework/decorators.py", line 346, in decorator
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     rval = func(self, trans, *args, **kwargs)
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/server/lib/galaxy/webapps/galaxy/api/workflows.py", line 573, in get_tool_predictions
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     tool_sequence, recommended_tools = self.tool_recommendations.get_predictions(
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/server/lib/galaxy/tools/recommendations.py", line 123, in get_predictions
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     self.__set_model(trans, remote_model_url)
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/server/lib/galaxy/tools/recommendations.py", line 134, in __set_model
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     self.loaded_model = self.create_transformer_model(len(self.reverse_dictionary) + 1)
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/server/lib/galaxy/tools/recommendations.py", line 108, in create_transformer_model
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     x, weights = transformer_block(x)
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:                  ^^^^^^^^^^^^^^^^^^^^
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/opt/galaxy/venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     raise e.with_traceback(filtered_tb) from None
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/usr/local/tools/_conda/envs/__python@3.11.5/lib/python3.11/inspect.py", line 3212, in bind
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     return self._bind(args, kwargs)
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:   File "/usr/local/tools/_conda/envs/__python@3.11.5/lib/python3.11/inspect.py", line 3127, in _bind
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]:     raise TypeError(msg) from None
Mar 26 21:02:28 sn06.galaxyproject.eu gunicorn[2211518]: TypeError: missing a required argument: 'training'
```

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/20434 .
