### ISSUE TITLE
History archivals fail if a history item's hid is null

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#18032]
**Describe the bug**
When using tasked history export archives, if an item in that history has an empty (`null`/`None`) `hid`, exporting fails:

```pytb
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/celery/__init__.py", line 184, in wrapper
    rval = app.magic_partial(func)(*args, **kwds)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/lagom/wrapping.py", line 28, in _bound_func
    return inner_func(*bound_args, **bound_kwargs)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.11/site-packages/lagom/wrapping.py", line 45, in _error_handling_func
    return func(*args, **kwargs)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/celery/tasks.py", line 400, in write_history_to
    model_store_manager.write_history_to(request)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/managers/model_stores.py", line 217, in write_history_to
    with model.store.get_export_store_factory(
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2462, in __exit__
    self._finalize()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2830, in _finalize
    super()._finalize()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2331, in _finalize
    datasets_attrs_out.write(to_json(datasets_attrs))
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2327, in to_json
    return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 2327, in <listcomp>
    return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 399, in serialize
    return self._serialize(id_encoder, serialization_options)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 5272, in _serialize
    self._handle_serialize_files(id_encoder, serialization_options, rval)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 4983, in _handle_serialize_files
    serialization_options.serialize_files(self, rval)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 387, in serialize_files
    self.serialize_files_handler.serialize_files(dataset, as_dict)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/store/__init__.py", line 1976, in serialize_files
    assert dataset_hid, as_dict
AssertionError: {'model_class': 'HistoryDatasetAssociation', 'create_time': '2010-03-08 01:04:31.488817', 'update_time': '2010-03-08 01:04:40.110421', 'name': 'Convert BED to GeneTrack Index on data 27', 'info': '', 'blurb': 'data', 'peek': 'binary data', 'extension': 'genetrack', 'metadata': {'dbkey': 'hg18'}, 'designation': 'output1', 'deleted': False, 'visible': True, 'dataset_uuid': None, 'validated_state': 'unknown', 'validated_state_message': None, 'encoded_id': 'deadbeef', 'state': 'ok', 'hid': None, 'annotation': None, 'tags': [], 'tool_version': None, 'history_encoded_id': 'deadbeef', 'copied_from_history_dataset_association_id_chain': []}
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0.1.dev0
Commit: 5addd0093380118954d73ead601cc5ecc0e8b154

**Comment by davelopez** [comment]
I guess the issue is: how did we get a `hid: None` in the first place... :sweat_smile:

Could that happen in a normal scenario without other issues (unrelated to the history export)? :thinking: 
And how would we recover from that at this point?

**Comment by mvdbeek** [comment]
We've had this bug happen frequently in the past, we used to commit the dataset without setting a hid and then retrieved the hid and set it, which is of course prone to fail in various ways. We've fixed this and now got some extensive tracking that should prevent this  (https://github.com/galaxyproject/galaxy/blob/9d715cecc4bce4359ae4c6ac64025da4231a0d17/lib/galaxy/model/__init__.py#L5030), but that's relatively recent.

HDAs without a history (yes, that doesn't really make sense) exist for custom builds: 

https://github.com/galaxyproject/galaxy/blob/9d715cecc4bce4359ae4c6ac64025da4231a0d17/lib/galaxy/webapps/galaxy/api/users.py#L491-L504

these don't get added to a history, so for the purposes of history exports that's not a problem.

We may still have some weird patterns in the code where we commit without a HID, as we do have a handful of new datasets in the database without a HID. Running that query know but it's incredibly slow to filter on the info field since there's no index on it:

```
galaxy_main=> select id, hid, name, create_time, state, info, blurb from history_dataset_association where hid is null order by id desc limit 10;
    id     | hid |                 name                  |        create_time         | state |          info          | blurb
-----------+-----+---------------------------------------+----------------------------+-------+------------------------+--------
 127643631 |     | brevibacillus laterosporus            | 2024-04-19 15:59:44.345448 |       | custom build .len file |
 127563757 |     | SDHA reference                        | 2024-04-18 17:37:09.184156 |       | custom build .len file |
 127501853 |     | MpTak                                 | 2024-04-17 20:34:39.040431 |       | custom build .len file |
 127467091 |     | Bmpr2                                 | 2024-04-17 08:53:09.013192 |       | custom build .len file |
 127396796 |     | Unnamed dataset                       | 2024-04-16 01:32:09.830552 |       |                        | queued
 127319817 |     | Ref B 07                              | 2024-04-14 20:02:19.925396 |       | custom build .len file |
 127319813 |     | Ref A                                 | 2024-04-14 20:00:49.345706 |       | custom build .len file |
 127249158 |     | Unnamed dataset                       | 2024-04-12 16:57:48.849562 |       |                        | queued
 127249151 |     | Unnamed dataset                       | 2024-04-12 16:57:32.883682 |       |                        | queued
 127221342 |     | HISAT2 on data 1: unaligned reads (L) | 2024-04-12 10:18:18.22252  |       |                        | queued
```

None of these have a job id assigned. The `Unnamed dataset` name sounds like it might be created by uploads, https://github.com/galaxyproject/galaxy/pull/18014/files is a potential fix for that.

> And how would we recover from that at this point?

These histories are currently not even serializable in the API. We probably shouldn't assign a random valid HID or something like that automatically. For ancient histories like this the admin could go in and assign `-1` as the hid ? For exports specifically we don't really need the hid, we only use it to generate a unique path on disk, you could fall back to the dataset uuid or id if we don't have a hid ?

**Comment by natefoo** [comment]
Not sure in all cases but we have many:
```
galaxy_main=> select count(*) from history_dataset_association where hid is null;
  count
---------
 2175237
(1 row)
```

The example above is an implicit conversion, but I thought those typically had a hid in the DB, just that it was the same hid as the input? Interestingly the overwhelming majority of these in the DB are from late 2019 to early 2021. Starting late 2021 there's typically less than 100 per month.

**Comment by bgruening** [comment]
EU stats:
```
galaxy=> select count(*) from history_dataset_association where hid is null;

  count  
---------
 7527368
(1 row)
```

**Comment by mvdbeek** [comment]
I've done some more digging and found the source of the missing hids for implicitly converted datasets, as well as why our tests were not catching this in #18036 ... we didn't run the strict checks on new objects 🤕.

That then also revealed a whole slew of other issues that I had already been suspecting 😅:
```
ERROR    galaxy.web.framework.decorators:decorators.py:361 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py", line 346, in decorator
    rval = func(self, trans, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 593, in create
    return self.service._create(trans, payload, **kwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/services/tools.py", line 171, in _create
    vars = tool.handle_input(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 1905, in handle_input
    execution_tracker = execute_job(
                        ^^^^^^^^^^^^
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/execute.py", line 160, in execute
    execution_tracker.ensure_implicit_collections_populated(history, mapping_params.param_template)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/execute.py", line 386, in ensure_implicit_collections_populated
    self.precreate_output_collections(history, params)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/execute.py", line 437, in precreate_output_collections
    trans.sa_session.commit()
  File "<string>", line 2, in commit
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3478, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.11/site-packages/sqlalchemy/event/attr.py", line 247, in __call__
    fn(*args, **kw)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/base.py", line 184, in before_flush
    obj.__strict_check_before_flush__()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/model/__init__.py", line 7149, in __strict_check_before_flush__
    assert self.element_object, "Dataset Collection Element without child entity detected, this is not valid"
```
