### ISSUE TITLE
Object store selection is available to anon users (but only works partially?)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18153]
It's unclear to me if anon users should be able to select object stores.
Currently they can, as we show the `Preferred Storage Location` button in the history.
If a user clicks on that they can select the object store, however the API returns null and so that somewhat breaks the UI.

If you do upload a dataset to that history it goes to scratch storage, so this seems at least somewhat functional.

Sentry Issue: [GALAXY-MAIN-YAR](https://sentry.galaxyproject.org/organizations/galaxy/issues/152635/?referrer=github_integration)

```
TypeError: Cannot read properties of null (reading 'quota_source_label')
  at get QuotaUsage.rawSourceLabel (webpack://@galaxyproject/galaxy-client/./src/components/User/DiskUsage/Quota/model/QuotaUsage.ts:18:33)
  at get QuotaUsage.sourceLabel (webpack://@galaxyproject/galaxy-client/./src/components/User/DiskUsage/Quota/model/QuotaUsage.ts:25:27)
  at isDefaultQuota (webpack://@galaxyproject/galaxy-client/./src/components/User/DiskUsage/Quota/QuotaUsageBar.vue?b65b:17:37)
  at Watcher.prototype.get (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:4164:33)
  at Watcher.prototype.evaluate (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:4265:27)
...
(21 additional frame(s) were not displayed)
```

**Comment by jmchilton** [comment]
I'll add this to my to do list - thank you for the issue!
