### ISSUE TITLE
Error when running jupyter IT

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#18501]
**Describe the bug**

I get the following Traceback when running the jupyter IT (with podman):

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 520, in launch_instance
    serverapp.start()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2100, in start
    self.start_app()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2054, in start_app
    self.write_server_info_file()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1881, in write_server_info_file
    with secure_write(self.info_file) as f:
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/paths.py", line 471, in secure_write
    raise RuntimeError("Permissions assignment failed for secure file: '{file}'."
RuntimeError: Permissions assignment failed for secure file: '/home/jovyan/.local/share/jupyter/runtime/jpserver-11.json'. Got '0o655' instead of '0o0600'.
```

A workaround is to set:

```
export JUPYTER_ALLOW_INSECURE_WRITES="true" &&
```

But I'm not sure if this is a proper fix.

xref https://github.com/jupyter/notebook/issues/5058

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**
Operating System: Rocky9

**Comment by bgruening** [comment]
Have you tried setting JUPYTER_RUNTIME_DIR=/tmp ?
