### ISSUE TITLE
TextToolParameter validation fails when loading up tool.

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1860]
I noticed this on the latest dev.
If I try to load the datamash tool from the toolbox, I get the following exception.

```
galaxy.web.framework.decorators ERROR 2016-03-04 15:59:11,664 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/marius/src/galaxy/lib/galaxy/web/framework/decorators.py", line 259, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/Users/marius/src/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 97, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "/Users/marius/src/galaxy/lib/galaxy/tools/__init__.py", line 1751, in to_json
    self.populate_state( request_context, self.inputs, params.__dict__, state_inputs, state_errors )
  File "/Users/marius/src/galaxy/lib/galaxy/tools/__init__.py", line 1850, in populate_state
    value, error = check_param( request_context, input, param_value, context )
  File "/Users/marius/src/galaxy/lib/galaxy/tools/parameters/__init__.py", line 106, in check_param
    param.validate( value, trans )
  File "/Users/marius/src/galaxy/lib/galaxy/tools/parameters/basic.py", line 265, in validate
    return super( TextToolParameter, self ).validate( value, trans )
  File "/Users/marius/src/galaxy/lib/galaxy/tools/parameters/basic.py", line 190, in validate
    validator.validate( value, trans )
  File "/Users/marius/src/galaxy/lib/galaxy/tools/parameters/validation.py", line 61, in validate
    if re.match( self.expression, value ) is None:
  File "/Users/marius/src/galaxy/.venv/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

In this instance this is a text type parameter that has a validator associated to it
(https://github.com/galaxyproject/tools-iuc/blob/master/tools/datamash/datamash-ops.xml#L29).
Since on first load the value is `None` the validation fails ...
I guess the validator should be skipped when loading a tool from the toolbox?

**Comment by mvdbeek** [comment]
Is there something like `workflow_building_mode` as in PR #1859 , but for tools that are being loaded for display? ping @guerler

**Comment by bgruening** [comment]
I also want to add here that we need to switch `column_select` parameters to text fields in `workflow_building_mode`. For example the new `cut` tool has a `column_select` parameter and is not useable in workflows.

**Comment by guerler** [comment]
Thanks a lot for reporting this. I think its better to fix the validator itself. Validators should be robust either way, then the front end can decide whether to display errors or not.
