### ISSUE TITLE
setting job resource parameters via api fails when subworkflow input comes from a subworkflow

### ISSUE THREAD

**Issue by crutching** [galaxyproject/galaxy#18712]
(v21.05) Hi, I've been trying to figure out why my job resource parameters do not seem to fill properly for tools within subworkflows.  In general, I send tool param payloads that look roughly like this:

```
{'2': {'2|__job_resource|__job_resource__select': 'yes', '2|__job_resource|__current_case__': '1', '2|__job_resource|qos': 'rank3', '3|__job_resource|__job_resource__select': 'yes', '3|__job_resource|__current_case__': '1', '3|__job_resource|qos': 'rank3'}, '3': {'2|__job_resource|__job_resource__select': 'yes', '2|__job_resource|__current_case__': '1', '2|__job_resource|qos': 'rank3', '3|__job_resource|__job_resource__select': 'yes', '3|__job_resource|__current_case__': '1', '3|__job_resource|qos': 'rank3'}, '4': {'__job_resource|__job_resource__select': 'yes', '__job_resource|__current_case__': '1', '__job_resource|qos': 'rank3'}, '5': {'__job_resource|__job_resource__select': 'yes', '__job_resource|__current_case__': '1', '__job_resource|qos': 'rank3'}}
```

You can see the job resource parameters are set properly for both subworkflow and parent workflow tools.  I can confirm this with a small test workflow where the parameter properly fills for workflows without subworkflows and workflows with a single subworkflow.  When I add a second subworkflow that accepts input from another subworkflow, I get the following error:

```
Traceback (most recent call last):
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/modules.py", line 1724, in execute
    visit_input_values(tool.inputs, execution_state.inputs, callback, no_replacement_value=NO_REPLACEMENT, replace_optional_connections=True)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/tools/parameters/__init__.py", line 170, in visit_input_values
    visit_input_values(input.cases[values['__current_case__']].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/tools/parameters/__init__.py", line 176, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/tools/parameters/__init__.py", line 137, in callback_helper
    new_value = callback(**args)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/modules.py", line 1693, in callback
    input_dict = all_inputs_by_name[prefixed_name]
KeyError: '__job_resource|qos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/run.py", line 271, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/modules.py", line 526, in execute
    subworkflow_invoker.invoke()
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/run.py", line 271, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/home/exacloud/clinical/clinglxydev/galaxy/lib/galaxy/workflow/modules.py", line 1728, in execute
    raise exceptions.MessageException(message)
galaxy.exceptions.MessageException: Error due to input mapping of 'Cutadapt' in ''__job_resource|qos''.  A common cause of this is conditional outputs that cannot be determined until runtime, please review your workflow.
```

This is not a tool-specific error, I can reproduce the same thing with a variety of tools.  I'm providing a screenshot of the workflow also.  Current workaround is to either not use more than one subworkflow, or create a text input workflow parameter that attaches to each step.  We have to fill this parameter during workflow creation and it will change from invocation to invocation.

<img width="1195" alt="Screenshot 2024-08-15 at 4 39 39 PM" src="https://github.com/user-attachments/assets/f7e6ff0e-1c3d-4def-a9a7-daa4debbbb4f">

**Comment by mvdbeek** [comment]
We don't support job resource parameters in workflows and are ignoring them in newer Galaxy versions (https://github.com/galaxyproject/galaxy/pull/16579). These parameters aren't portable, are prone to breaking when their definition is altered etc.
