### ISSUE TITLE
Python 2.6 breaks due to dependency on svgwrite 1.1.16

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1882]
Currently Galaxy still supports Python 2.6, see #1596. The Galaxy dev branch is currently broken under Python 2.6, this example failure is from https://travis-ci.org/peterjc/galaxy_blast/jobs/107255016 (which I may restart later, which could change the output):

```
...
Collecting svgwrite==1.1.6 (from -r requirements.txt (line 54))
  Downloading https://wheels.galaxyproject.org/packages/svgwrite-1.1.6-py2-none-any.whl (62kB)
...
galaxy.workflow.scheduling_manager DEBUG 2016-03-07 15:02:18,832 Starting workflow schedulers
functional_tests.py INFO 2016-03-07 15:02:18,846 Embedded Universe application started
galaxy.web.framework.base DEBUG 2016-03-07 15:02:18,916 Enabling 'admin' controller, class: AdminGalaxy
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 531, in <module>
    sys.exit( main() )
  File "./scripts/functional_tests.py", line 365, in main
    use_translogger=False, static_enabled=STATIC_ENABLED )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/webapps/galaxy/buildapp.py", line 47, in app_factory
    return paste_app_factory( global_conf, **kwargs )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/webapps/galaxy/buildapp.py", line 84, in paste_app_factory
    webapp.add_ui_controllers( 'galaxy.webapps.galaxy.controllers', app )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/web/framework/webapp.py", line 115, in add_ui_controllers
    module = import_module( module_name )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/util/backports/importlib/__init__.py", line 40, in import_module
    __import__(name)
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py", line 32, in <module>
    from tool_shed.util import workflow_util
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/tool_shed/util/workflow_util.py", line 14, in <module>
    from galaxy.workflow.render import WorkflowCanvas
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/workflow/render.py", line 1, in <module>
    import svgwrite
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/svgwrite/__init__.py", line 51, in <module>
    from svgwrite.drawing import Drawing
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/svgwrite/drawing.py", line 29, in <module>
    from svgwrite.container import SVG, Defs
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/svgwrite/container.py", line 27, in <module>
    from svgwrite.base import BaseElement
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/svgwrite/base.py", line 12, in <module>
    from svgwrite.etree import etree
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/svgwrite/etree.py", line 33, in <module>
    original_serialize_xml = etree._serialize_xml
AttributeError: 'module' object has no attribute '_serialize_xml'
galaxy.jobs.handler INFO 2016-03-07 15:02:19,016 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-03-07 15:02:19,016 job handler queue stopped
galaxy.jobs.runners INFO 2016-03-07 15:02:19,017 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2016-03-07 15:02:19,017 LocalRunner: Sending stop signal to 5 worker threads
galaxy.jobs.handler INFO 2016-03-07 15:02:19,017 sending stop signal to worker thread
galaxy.jobs.handler INFO 2016-03-07 15:02:19,018 job handler stop queue stopped
```

I believe this is due to https://github.com/galaxyproject/galaxy/commit/6f72338b449c9f92ca8a58e42f898716b0edcc74 which added a dependency on svgwrite 1.1.6

See also https://bitbucket.org/mozman/svgwrite/issues/15/cant-import-svgwrite-116-_serialize_xml

**Comment by dannon** [comment]
@peterjc This is correct, and expected behavior.  We've removed 2.6 compatibility tests from -dev and are now using non-2.6 compatible libraries (well, svgwrite is the only one so far).  Release 16.01 is the last release that will support python 2.6.

**Comment by dannon** [comment]
Closing this, updating check_python to force 2.7.
