### ISSUE TITLE
24.1 /admin/users hangs with browser console error

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#18878]
**Describe the bug**

The URL /admin/users /admin/group /admin/roles /admin/forms fails. 

the `/api/users` api call works fine. 
I turned on database log reporting and no issues.

Chrome/edge console error is
```
grid-template.js:368 
 Uncaught TypeError: e.columns is not iterable
    at Object.grid_filters (grid-template.js:368:38)
    at Object.grid_header (grid-template.js:83:22)
    at Object.grid (grid-template.js:17:48)
    at r.init_grid (grid-view.js:115:33)
    at Object.success (grid-view.js:58:26)
    at l (jquery.js:3187:31)
    at Object.fireWith [as resolveWith] (jquery.js:3317:7)
    at x (jquery.js:8757:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9123:9)
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1
Commit: 2a7954c51bcc2fb6a33879fe157735fb68198f83
and also tried latest commit 2a7954c51bcc2fb6a33879fe157735fb68198f83

**Comment by alpapan** [comment]
same behaviour on firefox.

output with enabledebugging on edge console

```
JQMIGRATE: Migrate is installed with logging active, version 1.4.1
monitor.js:20  accessing (get) window.Galaxy /admin/users
get @ monitor.js:20
81924 @ monitor.js:33
__webpack_require__ @ bootstrap:19
56667 @ monitor.js:33
__webpack_require__ @ bootstrap:19
53515 @ bundleEntries-exposed.js:1
__webpack_require__ @ bootstrap:19
(anonymous) @ startup:5
__webpack_require__.O @ chunk loaded:25
(anonymous) @ startup:7
(anonymous) @ startup:7
console.js:34 The Galaxy console has been enabled.  You can disable it by running disableDebugging() in devtools.
index.js:31 Galaxy Client 'production' build, dated 2024-03-25T14:15:42.267Z
singleton.js:12  setGalaxyInstance /admin/users
_ @ singleton.js:12
m @ defaultAppFactory.js:11
(anonymous) @ standardInit.js:38
(anonymous) @ map.js:7
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
u @ debounceTime.js:16
c @ debounceTime.js:27
e._execute @ AsyncAction.js:62
e.execute @ AsyncAction.js:50
e.flush @ AsyncScheduler.js:21
setInterval
setInterval @ intervalProvider.js:12
e.requestAsyncId @ AsyncAction.js:33
e.schedule @ AsyncAction.js:28
t.schedule @ Scheduler.js:10
(anonymous) @ debounceTime.js:33
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
(anonymous) @ filter.js:6
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
e._subscribe @ BehaviorSubject.js:19
t._trySubscribe @ Observable.js:38
e._trySubscribe @ Subject.js:95
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
t._subscribe @ Observable.js:66
(anonymous) @ Observable.js:30
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ filter.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ debounceTime.js:29
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ combineLatest.js:40
d @ combineLatest.js:67
c @ combineLatest.js:37
(anonymous) @ combineLatest.js:57
d @ combineLatest.js:67
(anonymous) @ combineLatest.js:31
t._trySubscribe @ Observable.js:38
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
F @ standardInit.js:45
(anonymous) @ index.ts:27
load
57394 @ index.ts:27
__webpack_require__ @ bootstrap:19
(anonymous) @ startup:6
__webpack_require__.O @ chunk loaded:25
(anonymous) @ startup:7
(anonymous) @ startup:7
Show 53 more frames
Show less
standardInit.js:46 runInitializations app /admin/users
installMonitor.js:118 monitor init
initSentry.js:10 initSentry
iframesAreTerrible.js:32 addIframeClass
iframesAreTerrible.js:6 adjustIframeLinks
initModals.js:6 initModals
initTooltips.js:5 initTooltips
init_refresh_on_change.js:4 init_refresh_on_change
replace_big_select_inputs.js:18 replace_big_select_inputs
index.ts:10 App setup
userStore.ts:51  [BootstrapVue warn]: tooltip - The provided target is no valid HTML element.
o @ warn.js:14
(anonymous) @ bv-tooltip.js:241
(anonymous) @ vue.esm.js:3861
er @ vue.esm.js:3783
Promise.then
Jn @ vue.esm.js:3808
ar @ vue.esm.js:3873
t.$nextTick @ vue.esm.js:2518
created @ bv-tooltip.js:231
Yn @ vue.esm.js:3735
gn @ vue.esm.js:3136
t._init @ vue.esm.js:4713
a @ vue.esm.js:5836
a @ create-new-child-component.js:10
P @ tooltip.js:189
(anonymous) @ tooltip.js:262
(anonymous) @ vue.esm.js:3861
er @ vue.esm.js:3783
Promise.then
Jn @ vue.esm.js:3808
ar @ vue.esm.js:3873
componentUpdated @ tooltip.js:261
eo @ vue.esm.js:7278
(anonymous) @ vue.esm.js:7226
u @ vue.esm.js:1597
Yn @ vue.esm.js:3735
n @ vue.esm.js:1547
E @ vue.esm.js:6942
(anonymous) @ vue.esm.js:6794
E @ vue.esm.js:6920
(anonymous) @ vue.esm.js:6794
E @ vue.esm.js:6920
Pa.nodeOps @ vue.esm.js:7088
t._update @ vue.esm.js:2874
r @ vue.esm.js:2980
t.get @ vue.esm.js:4164
t.run @ vue.esm.js:4240
kn @ vue.esm.js:3226
(anonymous) @ vue.esm.js:3861
er @ vue.esm.js:3783
Promise.then
Jn @ vue.esm.js:3808
ar @ vue.esm.js:3873
On @ vue.esm.js:3312
Ln.b.update @ vue.esm.js:3502
t.notify @ vue.esm.js:807
set @ vue.esm.js:1050
(anonymous) @ userStore.ts:51
(anonymous) @ userStore.ts:7
u @ userStore.ts:3
(anonymous) @ userStore.ts:49
Promise.then
loadUser @ userStore.ts:49
(anonymous) @ pinia.mjs:1380
(anonymous) @ App.vue:109
Yn @ vue.esm.js:3735
p @ vue.esm.js:3362
Ln.b.run @ vue.esm.js:3471
Ln @ vue.esm.js:3513
Bn @ vue.esm.js:3341
setup @ App.vue:103
Yn @ vue.esm.js:3735
(anonymous) @ vue.esm.js:2296
Nr @ vue.esm.js:4318
t._init @ vue.esm.js:4711
a @ vue.esm.js:5836
(anonymous) @ vue.esm.js:5044
init @ vue.esm.js:4906
(anonymous) @ vue.esm.js:6578
h @ vue.esm.js:6532
Pa.nodeOps @ vue.esm.js:7120
t._update @ vue.esm.js:2870
r @ vue.esm.js:2980
t.get @ vue.esm.js:4164
t @ vue.esm.js:4154
(anonymous) @ vue.esm.js:2997
li.$mount @ vue.esm.js:9312
li.$mount @ vue.esm.js:11877
t._init @ vue.esm.js:4721
li @ vue.esm.js:5772
(anonymous) @ index.ts:16
(anonymous) @ standardInit.js:47
(anonymous) @ standardInit.js:47
t.next @ Subscriber.js:96
e._next @ Subscriber.js:63
e.next @ Subscriber.js:34
(anonymous) @ combineLatest.js:47
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
(anonymous) @ map.js:7
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
u @ debounceTime.js:16
c @ debounceTime.js:27
e._execute @ AsyncAction.js:62
e.execute @ AsyncAction.js:50
e.flush @ AsyncScheduler.js:21
setInterval
setInterval @ intervalProvider.js:12
e.requestAsyncId @ AsyncAction.js:33
e.schedule @ AsyncAction.js:28
t.schedule @ Scheduler.js:10
(anonymous) @ debounceTime.js:33
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
(anonymous) @ filter.js:6
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
e._subscribe @ BehaviorSubject.js:19
t._trySubscribe @ Observable.js:38
e._trySubscribe @ Subject.js:95
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
t._subscribe @ Observable.js:66
(anonymous) @ Observable.js:30
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ filter.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ debounceTime.js:29
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ combineLatest.js:40
d @ combineLatest.js:67
c @ combineLatest.js:37
(anonymous) @ combineLatest.js:57
d @ combineLatest.js:67
(anonymous) @ combineLatest.js:31
t._trySubscribe @ Observable.js:38
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
F @ standardInit.js:45
(anonymous) @ index.ts:27
load
57394 @ index.ts:27
__webpack_require__ @ bootstrap:19
(anonymous) @ startup:6
__webpack_require__.O @ chunk loaded:25
(anonymous) @ startup:7
(anonymous) @ startup:7
Show 128 more frames
Show less
grid-template.js:368  Uncaught TypeError: e.columns is not iterable
    at Object.grid_filters (grid-template.js:368:38)
    at Object.grid_header (grid-template.js:83:22)
    at Object.grid (grid-template.js:17:48)
    at r.init_grid (grid-view.js:115:33)
    at Object.success (grid-view.js:58:26)
    at l (jquery.js:3187:31)
    at Object.fireWith [as resolveWith] (jquery.js:3317:7)
    at x (jquery.js:8757:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9123:9)
grid_filters @ grid-template.js:368
grid_header @ grid-template.js:83
grid @ grid-template.js:17
init_grid @ grid-view.js:115
success @ grid-view.js:58
l @ jquery.js:3187
fireWith @ jquery.js:3317
x @ jquery.js:8757
(anonymous) @ jquery.js:9123
load
send @ jquery.js:9142
ajax @ jquery.js:8656
initialize @ grid-view.js:53
e.View @ backbone.js:1340
r @ backbone.js:2101
mounted @ Grid.vue:21
Yn @ vue.esm.js:3735
gn @ vue.esm.js:3136
insert @ vue.esm.js:4923
k @ vue.esm.js:6953
Pa.nodeOps @ vue.esm.js:7164
t._update @ vue.esm.js:2874
r @ vue.esm.js:2980
t.get @ vue.esm.js:4164
t.run @ vue.esm.js:4240
kn @ vue.esm.js:3226
(anonymous) @ vue.esm.js:3861
er @ vue.esm.js:3783
Promise.then
Jn @ vue.esm.js:3808
ar @ vue.esm.js:3873
On @ vue.esm.js:3312
t.update @ vue.esm.js:4231
t.notify @ vue.esm.js:807
set @ vue.esm.js:1050
(anonymous) @ configurationStore.ts:24
s @ configurationStore.ts:4
Promise.then
l @ configurationStore.ts:6
(anonymous) @ configurationStore.ts:7
s @ configurationStore.ts:3
i @ configurationStore.ts:19
(anonymous) @ configurationStore.ts:39
t.run @ vue.esm.js:3558
(anonymous) @ pinia.mjs:1450
t.run @ vue.esm.js:3558
(anonymous) @ pinia.mjs:1450
G @ pinia.mjs:1134
Q @ pinia.mjs:1448
l @ pinia.mjs:1717
a @ config.ts:5
setup @ Masthead.vue:22
Yn @ vue.esm.js:3735
(anonymous) @ vue.esm.js:2296
Nr @ vue.esm.js:4318
t._init @ vue.esm.js:4711
a @ vue.esm.js:5836
(anonymous) @ vue.esm.js:5044
init @ vue.esm.js:4906
(anonymous) @ vue.esm.js:6578
h @ vue.esm.js:6532
g @ vue.esm.js:6651
h @ vue.esm.js:6555
g @ vue.esm.js:6651
h @ vue.esm.js:6555
Pa.nodeOps @ vue.esm.js:7082
t._update @ vue.esm.js:2870
r @ vue.esm.js:2980
t.get @ vue.esm.js:4164
t @ vue.esm.js:4154
(anonymous) @ vue.esm.js:2997
li.$mount @ vue.esm.js:9312
li.$mount @ vue.esm.js:11877
init @ vue.esm.js:4907
(anonymous) @ vue.esm.js:6578
h @ vue.esm.js:6532
Pa.nodeOps @ vue.esm.js:7120
t._update @ vue.esm.js:2870
r @ vue.esm.js:2980
t.get @ vue.esm.js:4164
t @ vue.esm.js:4154
(anonymous) @ vue.esm.js:2997
li.$mount @ vue.esm.js:9312
li.$mount @ vue.esm.js:11877
t._init @ vue.esm.js:4721
li @ vue.esm.js:5772
(anonymous) @ index.ts:16
(anonymous) @ standardInit.js:47
(anonymous) @ standardInit.js:47
t.next @ Subscriber.js:96
e._next @ Subscriber.js:63
e.next @ Subscriber.js:34
(anonymous) @ combineLatest.js:47
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
(anonymous) @ map.js:7
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
u @ debounceTime.js:16
c @ debounceTime.js:27
e._execute @ AsyncAction.js:62
e.execute @ AsyncAction.js:50
e.flush @ AsyncScheduler.js:21
setInterval
setInterval @ intervalProvider.js:12
e.requestAsyncId @ AsyncAction.js:33
e.schedule @ AsyncAction.js:28
t.schedule @ Scheduler.js:10
(anonymous) @ debounceTime.js:33
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
(anonymous) @ filter.js:6
s._next @ OperatorSubscriber.js:15
e.next @ Subscriber.js:34
e._subscribe @ BehaviorSubject.js:19
t._trySubscribe @ Observable.js:38
e._trySubscribe @ Subject.js:95
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
t._subscribe @ Observable.js:66
(anonymous) @ Observable.js:30
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ filter.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ debounceTime.js:29
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:27
o @ errorContext.js:19
t.subscribe @ Observable.js:23
(anonymous) @ combineLatest.js:40
d @ combineLatest.js:67
c @ combineLatest.js:37
(anonymous) @ combineLatest.js:57
d @ combineLatest.js:67
(anonymous) @ combineLatest.js:31
t._trySubscribe @ Observable.js:38
(anonymous) @ Observable.js:32
o @ errorContext.js:19
t.subscribe @ Observable.js:23
F @ standardInit.js:45
(anonymous) @ index.ts:27
load
57394 @ index.ts:27
__webpack_require__ @ bootstrap:19
(anonymous) @ startup:6
__webpack_require__.O @ chunk loaded:25
(anonymous) @ startup:7
(anonymous) @ startup:7
Show 120 more frames
Show less
user-model.js:39 User(bf4685cfedf41e3a:30042108:30042108@westernsydney.edu.au) has changed: r {cid: 'c1', attributes: {…}, _changing: true, _previousAttributes: {…}, changed: {…}, …} undefined
```

**Comment by guerler** [comment]
Has this issue been resolved? To my knowledge, `grid-template.js` is not used in 24.1, we vueified the components.
