### ISSUE TITLE
cannot install new tools and found hg error

### ISSUE THREAD

**Issue by HelloYLee** [galaxyproject/galaxy#19080]
**Describe the bug**
hi, I build docker images using branch release24. When execute docker run and start a container, I found 'hg' cannot run. it shows:
hg --version
Traceback (most recent call last):
  File "/galaxy/server/.venv/bin/hg", line 57, in <module>
    from mercurial import dispatch
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/galaxy/server/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 257, in exec_module
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/galaxy/server/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 267, in exec_module
AttributeError: partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)
![image](https://github.com/user-attachments/assets/d0955efe-5b4f-44c6-90d5-fd0c7ce656e1)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)
https://github.com/galaxyproject/galaxy/tree/release_24.1

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
That's pretty old now and likely an old bug in mercurial. Sorry we didn't get back to you earlier.
