### ISSUE TITLE
Fix vue warnings when running WorkflowComment.test.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#19200]
The icons errors are probably an easy fix. There are some examples in https://github.com/galaxyproject/galaxy/pull/19186/files - like VaultSecret.vue. I tried to fix this transform injection thing for a while though and failed. 

```
jest --config tests/jest/jest.config.js WorkflowComment
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
  console.error
    Could not find one or more icon(s) { prefix: null, iconName: 'textSmaller' } {}

      372 |

      at apply (node_modules/@fortawesome/vue-fontawesome/index.js:323:34)
      at log (node_modules/@fortawesome/vue-fontawesome/index.js:515:16)
      at createFunctionalComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4303:34)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4443:16)
      at _createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2830:17)
      at createElement$1 (node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
      at vm.$createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2549:41)
      at createElement (node_modules/@vue/test-utils/dist/vue-test-utils.js:2530:38)
      at Proxy.render (src/components/Workflow/Editor/Comments/TextComment.vue:374:19)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14067:21)
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:106:30
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:8:71
      at Object.<anonymous>.__awaiter (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:4:12)
      at Object.<anonymous> (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:105:56)

  console.error
    Could not find one or more icon(s) { prefix: null, iconName: 'textLarger' } {}



      at apply (node_modules/@fortawesome/vue-fontawesome/index.js:323:34)
      at log (node_modules/@fortawesome/vue-fontawesome/index.js:515:16)
      at createFunctionalComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4303:34)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4443:16)
      at _createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2830:17)
      at createElement$1 (node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
      at vm.$createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2549:41)
      at createElement (node_modules/@vue/test-utils/dist/vue-test-utils.js:2530:38)
      at Proxy.render (src/components/Workflow/Editor/Comments/TextComment.vue:393:19)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14067:21)
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:106:30
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:8:71
      at Object.<anonymous>.__awaiter (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:4:12)
      at Object.<anonymous> (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:105:56)

  console.error
    [Vue warn]: injection "transform" not found.
    
    found in
    
    ---> <Draggable>
           <DraggablePan>
             <TextComment>
               <WorkflowComment>
                 <Root>

      59 | let dragImg: HTMLImageElement | null = null;
      60 | const draggable = ref();
    > 61 | const size = reactive(useAnimationFrameSize(draggable));
         |                                        ^
      62 | const transform: Ref<ZoomTransform> | undefined = inject("transform");
      63 |
      64 | type Position = { x: number; y: number };

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at inject (node_modules/vue/dist/vue.runtime.common.dev.js:1699:13)
      at setup (src/components/Workflow/Editor/Draggable.vue:61:40)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:30)
      at initSetup (node_modules/vue/dist/vue.runtime.common.dev.js:2352:29)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:5300:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5615:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14067:21)
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:106:30
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:8:71
      at Object.<anonymous>.__awaiter (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:4:12)
      at Object.<anonymous> (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:105:56)

  console.error
    [Vue warn]: toRefs() expects a reactive object but received a plain one.
    
    found in
    
    ---> <Draggable>
           <DraggablePan>
             <TextComment>
               <WorkflowComment>
                 <Root>

      79 | const onStart = (_position: Position, event: DragEvent) => {
      80 |     emit("mousedown", event);
    > 81 |     hasMoved = false;
         |                                                    ^
      82 |
      83 |     if (!shouldMultidrag.value) {
      84 |         emit("start");

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at Object.toRefs (node_modules/vue/dist/vue.runtime.common.dev.js:1192:9)
      at storeToRefs (node_modules/pinia/dist/pinia.cjs:1923:24)
      at setup (src/components/Workflow/Editor/Draggable.vue:81:55)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:30)
      at initSetup (node_modules/vue/dist/vue.runtime.common.dev.js:2352:29)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:5300:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5615:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14067:21)
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:106:30
      at src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:8:71
      at Object.<anonymous>.__awaiter (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:4:12)
      at Object.<anonymous> (src/components/Workflow/Editor/Comments/WorkflowComment.test.ts:105:56)

  console.error
    [Vue warn]: injection "transform" not found.
    
    found in
    
    ---> <Draggable>
           <DraggablePan>
             <MarkdownComment>
               <WorkflowComment>
                 <Root>

      59 | let dragImg: HTMLImageElement | null = null;
      60 | const draggable = ref();
    > 61 | const size = reactive(useAnimationFrameSize(draggable));
         |                                        ^
      62 | const transform: Ref<ZoomTransform> | undefined = inject("transform");
      63 |
      64 | type Position = { x: number; y: number };

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at inject (node_modules/vue/dist/vue.runtime.common.dev.js:1699:13)
      at setup (src/components/Workflow/Editor/Draggable.vue:61:40)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:30)
      at initSetup (node_modules/vue/dist/vue.runtime.common.dev.js:2352:29)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:5300:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5615:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at updateChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6738:21)
      at patchVnode (node_modules/vue/dist/vue.runtime.common.dev.js:6831:21)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6997:17)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3722:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at Watcher.run (node_modules/vue/dist/vue.runtime.common.dev.js:3476:32)
      at flushSchedulerQueue (node_modules/vue/dist/vue.runtime.common.dev.js:4073:17)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:3045:20)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:2967:18)

  console.error
    [Vue warn]: toRefs() expects a reactive object but received a plain one.
    
    found in
    
    ---> <Draggable>
           <DraggablePan>
             <MarkdownComment>
               <WorkflowComment>
                 <Root>

      79 | const onStart = (_position: Position, event: DragEvent) => {
      80 |     emit("mousedown", event);
    > 81 |     hasMoved = false;
         |                                                    ^
      82 |
      83 |     if (!shouldMultidrag.value) {
      84 |         emit("start");

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at Object.toRefs (node_modules/vue/dist/vue.runtime.common.dev.js:1192:9)
      at storeToRefs (node_modules/pinia/dist/pinia.cjs:1923:24)
      at setup (src/components/Workflow/Editor/Draggable.vue:81:55)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:30)
      at initSetup (node_modules/vue/dist/vue.runtime.common.dev.js:2352:29)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:5300:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5615:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at updateChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6738:21)
      at patchVnode (node_modules/vue/dist/vue.runtime.common.dev.js:6831:21)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6997:17)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3722:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at Watcher.run (node_modules/vue/dist/vue.runtime.common.dev.js:3476:32)
      at flushSchedulerQueue (node_modules/vue/dist/vue.runtime.common.dev.js:4073:17)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:3045:20)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:2967:18)
```

**Comment by jmchilton** [comment]
Icon errors fixed in https://github.com/galaxyproject/galaxy/pull/19743. Still no clue how to fix the transform inject warning without just disabling the output. Maybe that would be fine?
