### ISSUE TITLE
sam to bam not working in workflow editor

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1925]
The reference genome is not displayed in the workflow editor. So I guess this needs to be a special cased in the editor. This is what we get after running the workflow. Rereunning the crashed tool works.

```
job traceback:
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 166, in prepare_job
    job_wrapper.prepare()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 873, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 56, in set_compute_environment
    self.tool.handle_unvalidated_param_values( incoming, self.app )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1756, in handle_unvalidated_param_values
    self.handle_unvalidated_param_values_helper( self.inputs, input_values, app )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1775, in handle_unvalidated_param_values_helper
    self.handle_unvalidated_param_values_helper( input.cases[current].inputs, values, app, context, prefix )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1796, in handle_unvalidated_param_values_helper
    raise LateValidationError( message )
LateValidationError
```

Removing the validator from the tool fixes it, but this is not the way to do :)

ping @guerler

**Comment by guerler** [comment]
Can you tell me on which branch this happens?

**Comment by bgruening** [comment]
16.01 latest patches

**Comment by guerler** [comment]
Thanks for reporting this. So the workflow editor does not display any options since they depend on the missing input dataset due to `<filter column="1" key="dbkey" ref="input1" type="data_meta" />`. We should improve this by ignoring the filter when loading the workflow editor form, I will add an issue for this enhancement.

Regarding the bug, I tried to reproduce it on main and release_16.01 but was not successful so far. UnvalidatedValues have been stripped from dev so this should not be an issue for future releases, fyi. Can you share the workflow with me? Can you also please try to edit and save the workflow to check if this changes the outcome? Thanks again.

**Comment by bgruening** [comment]
![illustration](https://cloud.githubusercontent.com/assets/469983/13954299/72a0b8d0-f040-11e5-9a7f-fa74c58bab16.png)

The using reference genome field is empty. This is due to this line: `<filter column="1" key="dbkey" ref="input1" type="data_meta" />` in this tool: https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/samtools/sam_to_bam/sam_to_bam.xml#L34

Commenting this line out fixes it for us.

**Comment by nsoranzo** [comment]
@guerler I think this is a regression, so `kind/bug` label seems more appropriate to me.

**Comment by guerler** [comment]
![refgenome](https://cloud.githubusercontent.com/assets/2105447/13963567/3e6d2930-f03c-11e5-89b6-af15a200a9af.png)

**Comment by guerler** [comment]
Switched back to `enhancement` since it seems to behave the same way in 14.10. Feel free to correct the labeling otherwise.

**Comment by hexylena** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/1132
And another: https://github.com/galaxyproject/galaxy/issues/7292

I guess this affects quite a few people, quite often
