### ISSUE TITLE
`ToolPanel.test.ts` fails intermittently

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#19315]
```bash
FAIL src/components/Panels/ToolPanel.test.ts
  ● ToolPanel › test navigation of tool panel views menu

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      67 |
      68 |         const dropdownMenu = wrapper.find(".dropdown-menu.show");
    > 69 |         expect(dropdownMenu.exists()).toBe(true);
         |                                       ^
      70 |
      71 |         // Test: check if the dropdown menu has all the panel views
      72 |         const dropdownItems = dropdownMenu.findAll(".dropdown-item");

      at src/components/Panels/ToolPanel.test.ts:69:39
      at fulfilled (src/components/Panels/ToolPanel.test.ts:5:58)
```

**Comment by ahmedhamidawan** [comment]
Fixed in #19733
