### ISSUE TITLE
pseudobulk-worflow-decoupler-edger fails on 24.2

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#19328]
planemo test --biocontainers --no_dependency_resolution --no_conda_auto_init --docker_extra_volume ./ --tool_data_table /cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml --tool_data_table /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml --docker_extra_volume /cvmfs --shed_tool_conf /tmp/shed_tool_conf.xml --shed_tool_path /tmp/shed_dir --database_connection ***localhost:5432/galaxy --galaxy_source https://github.com/galaxyproject/galaxy --galaxy_branch release_24.2 --galaxy_python_version 3.11 --test_timeout 86400 --test_output_json json_output/tmp.5BkAFEw1G9.json workflows/scRNAseq/pseudobulk-worflow-decoupler-edger
```
galaxy.workflow.run ERROR 2024-12-10 13:44:31,042 [pN:main.1,p:9889,tN:WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1508, in _init_compiled
    d_param = {
              ^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1510, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/sql/type_api.py", line 2052, in process
    fixed_process_param(value, dialect)
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/model/custom_types.py", line 98, in process_bind_param
    value = json_encoder.encode(value).encode()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/model/custom_types.py", line 40, in default
    return json.JSONEncoder.default(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type NoReplacement is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/workflow/run.py", line 249, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/workflow/run.py", line 337, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/workflow/modules.py", line 2401, in execute
    execution_tracker = execute(
                        ^^^^^^^^
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/tools/execute.py", line 200, in execute
    trans.sa_session.commit()
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1143, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1821, in _execute_context
    self._handle_dbapi_exception(
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1508, in _init_compiled
    d_param = {
              ^
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1510, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/runner/.planemo/gx_venv_3.11_release_24.2/lib/python3.11/site-packages/sqlalchemy/sql/type_api.py", line 2052, in process
    fixed_process_param(value, dialect)
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/model/custom_types.py", line 98, in process_bind_param
    value = json_encoder.encode(value).encode()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/tmp/tmplm2__5_v/galaxy-dev/lib/galaxy/model/custom_types.py", line 40, in default
    return json.JSONEncoder.default(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type NoReplacement is not JSON serializable
[SQL: INSERT INTO workflow_invocation_output_value (workflow_invocation_id, workflow_step_id, workflow_output_id, value) SELECT p0::INTEGER, p1::INTEGER, p2::INTEGER, p3::BYTEA FROM (VALUES (%(workflow_invocation_id)s, %(workflow_step_id)s, %(workflow_output_id)s, %(value)s)) AS imp_sen(p0, p1, p2, p3, sen_counter) ORDER BY sen_counter RETURNING workflow_invocation_output_value.id, workflow_invocation_output_value.id AS id__1]
[parameters: [{'value': <galaxy.workflow.modules.NoReplacement object at 0x7f1ad58c8810>, 'workflow_step_id': 69, 'workflow_output_id': 23, 'workflow_invocation_id': 7}, {'value': 'cell_type', 'workflow_step_id': 70, 'workflow_output_id': 24, 'workflow_invocation_id': 7}, {'value': 'individual', 'workflow_step_id': 71, 'workflow_output_id': 25, 'workflow_invocation_id': 7}, {'value': 'counts', 'workflow_step_id': 72, 'workflow_output_id': 26, 'workflow_invocation_id': 7}, {'value': 'disease', 'workflow_step_id': 73, 'workflow_output_id': 27, 'workflow_invocation_id': 7}, {'value': '~ 0 + disease', 'workflow_step_id': 74, 'workflow_output_id': 28, 'workflow_invocation_id': 7}, {'value': 'gene_symbol', 'workflow_step_id': 75, 'workflow_output_id': 29, 'workflow_invocation_id': 7}]]
```

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/19332
