### ISSUE TITLE
gops tools are failing parsing on Main (16.04)

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2152]
The tools themselves did not change afaik.

main traceback:
https://gist.github.com/natefoo/144f38933dd79127e74678122a917e04

I also see it when booting up 16.04 Galaxy locally:

```
galaxy.tools.toolbox.base ERROR 2016-04-13 13:43:53,865 Error reading tool from path: evolution/codingSnps.xml
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/lib/galaxy/tools/toolbox/base.py", line 586, in _load_tool_tag_set
    tool = self.load_tool( os.path.join( tool_path, path ), guid=guid, repository_id=repository_id, use_cached=internal )
  File "/Users/marten/devel/git/galaxy/lib/galaxy/tools/toolbox/base.py", line 734, in load_tool
    tool = self.create_tool( config_file=config_file, repository_id=repository_id, guid=guid, **kwds )
  File "/Users/marten/devel/git/galaxy/lib/galaxy/tools/__init__.py", line 129, in create_tool
    tool = ToolClass( config_file, tool_source, self.app, guid=guid, repository_id=repository_id, **kwds )
  File "/Users/marten/devel/git/galaxy/lib/galaxy/tools/__init__.py", line 299, in __init__
    raise e
ImportError: cannot import name DataToolParameter
```

**Comment by mvdbeek** [comment]
Was probably fixed by https://github.com/galaxyproject/galaxy/pull/2156
