### ISSUE TITLE
Import error with 16.04 embedded pulsar

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#2192]
This is on the latest dev with 16.04 merge in (to get #2184)

```
galaxy.jobs DEBUG 2016-04-19 11:10:04,918 Loaded job runner 'galaxy.jobs.runners.local:LocalJobRunner' as 'local'
Traceback (most recent call last):
  File "/Users/marius/src/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 63, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/Users/marius/src/galaxy/lib/galaxy/app.py", line 174, in __init__
    self.job_manager = manager.JobManager( self )
  File "/Users/marius/src/galaxy/lib/galaxy/jobs/manager.py", line 23, in __init__
    self.job_handler = handler.JobHandler( app )
  File "/Users/marius/src/galaxy/lib/galaxy/jobs/handler.py", line 32, in __init__
    self.dispatcher = DefaultJobDispatcher( app )
  File "/Users/marius/src/galaxy/lib/galaxy/jobs/handler.py", line 723, in __init__
    self.job_runners = self.app.job_config.get_job_runner_plugins( self.app.config.server_name )
  File "/Users/marius/src/galaxy/lib/galaxy/jobs/__init__.py", line 632, in get_job_runner_plugins
    module = __import__( module_name )
  File "/Users/marius/src/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 22, in <module>
    import pulsar.core
ImportError: No module named core
```

This only happens when specifying a pulsar job runner in job_conf.xml.
Here's mine, if that helps:

```
<job_conf>
    <plugins>
         <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
         <plugin id="pulsar" type="runner" load="galaxy.jobs.runners.pulsar:PulsarEmbeddedJobRunner">
             <param id="pulsar_config">/Users/marius/pulsar/app.yml</param>
         </plugin>
        <!-- <plugin id="pulsar" type="runner" load="galaxy.jobs.runners.pulsar:PulsarLegacyJobRunner"/> -->
    </plugins>
    <handlers>
        <handler id="main"/>
    </handlers>
    <destinations default="local">
        <destination id="local" runner="local">
         <env file="/Users/marius/src/galaxy/.venv/bin/activate" />
        </destination>
        <destination id="pulsar_quv" runner="pulsar">
            <param id="manager">quv</param>
            <param id="jobs_directory">/work/vandenbeek/staging</param>
            <param id="file_action_config">/Users/marius/src/galaxy/config/pulsar_action_quv.yml</param>
        </destination>
        <destination id="pulsar_qice" runner="pulsar">
            <param id="manager">qice</param>
            <param id="jobs_directory">/lustrework/vandenbeek/staging</param>
            <param id="file_action_config">/Users/marius/src/galaxy/config/pulsar_action_qice.yml</param>
        </destination>
        </destinations>
    <tools>
        <tool id="bowtie2" destination="pulsar_quv" />
        <tool id="printenv" destination="pulsar_qice" />
    </tools>
</job_conf>
```

I can see pulsar getting installed at first startup, so I'm not quite sure why importing pulsar.core fails.

**Comment by mvdbeek** [comment]
Ahh, this was because I still had the empty lib/pulsar/client and lib/pulsar/managers directories around. Shouldn't git checkout dev have removed them? Well, it's working now.
