### ISSUE TITLE
HistoryDatasetCollectionAssociation not serializable

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2224]
this happens on Main when trying to run Deseq2
https://sentry.galaxyproject.org/sentry/main/issues/12943/

```
galaxy.tools ERROR 2016-04-21 15:40:02,442 Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1140, in handle_single_execution
    job, out_data = self.execute( trans, incoming=params, history=history, rerun_remap_job_id=rerun_remap_job_id, mapping_over_collection=mapping_over_collection, execution_cache=execution_cache )
  File "lib/galaxy/tools/__init__.py", line 1218, in execute
    return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
  File "lib/galaxy/tools/actions/__init__.py", line 469, in execute
    self._record_inputs( trans, tool, job, incoming, inp_data, inp_dataset_collections, current_user_roles )
  File "lib/galaxy/tools/actions/__init__.py", line 584, in _record_inputs
    for name, value in tool.params_to_strings( incoming, trans.app ).iteritems():
  File "lib/galaxy/tools/__init__.py", line 1221, in params_to_strings
    return params_to_strings( self.inputs, params, app )
  File "lib/galaxy/tools/parameters/__init__.py", line 149, in params_to_strings
    rval[ key ] = str( dumps( value ) )
  File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7fc8bfbec990> is not JSON serializable
```

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/pull/2238
