### ISSUE TITLE
Unable to finish job :

### ISSUE THREAD

**Issue by ChaoyuanYeh** [galaxyproject/galaxy#2225]
I installed a Galaxy locally on Ubuntu 14.04 LTS.  With a fresh install, I came into the same problem twice. First was when I tried to run Bowtie2. I got this error message:

`Traceback (most recent call last):
File "/home/chuonglab/galaxy-dev/lib/galaxy/jobs/runners/local.py", line 128, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
File "/home/chuonglab/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1248, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
File "/home/chuonglab/galaxy-dev/lib/galaxy/datatypes/binary.py", line 339, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

The other time, again with a fresh install, I ran into the same problem when I tried to run RNA-Star. In both cases, it can be solved by manually adding the path to samtools binary to the system PATH variable. I'm tempted to think this is an issue because supposedly dependency should be automatically handled. (?) I checked and was able to find env.sh in the folder where the samtools is installed. It would appear that it's not sourced by Galaxy prior to the job? 

The other reason I think this could be an issue is because RNA-Star and Bowtie2 require different versions of samtools. By manually adding path to one samtools version to the system PATH variable, I'm preventing one program access to its required samtools version.

I'm hoping to get some insight into this issue. Could there be something wrong when I installed Galaxy?

**Comment by ChaoyuanYeh** [comment]
I did two things and this problem is now gone.
First, instead of downloading Galaxy source file as a zip, I used git clone. 
Second, I installed virtualenv.

**Comment by ChaoyuanYeh** [comment]
Previously I tried getting Galaxy using git and also tried installing virtualenv package ( although I didn't run galaxy server in a new virtual env). 

Eventually I realized that the binary.py requires samtools that's available system-wide, independent from the samtools installed by other repository tools.
