### ISSUE TITLE
Upgrade Deeptools to the latest version to avoid a white-space-in-dataset-name issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2331]
Details here: https://biostar.usegalaxy.org/p/17538/#17553

Thanks @bgruening for the work-around!

Could you help with the update @davebx or help me to organize that with whoever can help?

**Comment by jennaj** [comment]
Status: repo update in progress by @martenson, followed by config updates by @natefoo

Please lmk when done so can test on Main after and notify users who are watching this ticket (or who reported elsewhere). Tx!

**Comment by natefoo** [comment]
Updates were done but all the dependencies are broken, @martenson @davebx can you help fix?

**Comment by jennaj** [comment]
@natefoo @martenson @davebx

The tool is still erroring out. Do we have time to do this before GCC?

For any users tracking this: The current work-around is to avoid spaces in the input dataset names. Click on the pencil icon for each to modify the name.

**Comment by martenson** [comment]
There is no new deeptools version available in the MTS - we have the latest on Main.

**Comment by jennaj** [comment]
@martenson It is a tool fix, @bgruening and @nsoranzo are helping. _might_ be related to this https://github.com/galaxyproject/tools-iuc/issues/835

**Comment by natefoo** [comment]
So I've upgraded the DeepTools and installed the dependencies with conda, but when the job runs and conda attempts to create the environment for the job, it fails due to permissions problems with files installed by conda (`/galaxy/main/deps` is a symlink to `/cvmfs/main.galaxyproject.org/deps`):

``` pytb
Traceback (most recent call last):
  File "/galaxy/main/deps/_conda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/galaxy/main/deps/_conda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/galaxy/main/deps/_conda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/galaxy/main/deps/_conda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: '/galaxy/main/deps/_conda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh'
```

This despite the fact that the installer runs with umask `0022`. I fixed the permissions manually (with `find | xargs chmod` and now correctGCBias fails with:

``` pytb
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy-repl/main/jobdir/014/022/14022283/conda-env/bin/correctGCBias", line 4, in <module>
    from deeptools.correctGCBias import main
  File "/galaxy-repl/main/jobdir/014/022/14022283/conda-env/lib/python2.7/site-packages/deeptools/correctGCBias.py", line 10, in <module>
    import twobitreader as twobit
ImportError: No module named twobitreader
```

...

**Comment by natefoo** [comment]
I manually installed `twobitreader` and correctGCBias is working now. This will also be fixed upstream in bioconda/bioconda-recipes#2523

**Comment by jennaj** [comment]
Passed

**Comment by jennaj** [comment]
Needs a retest against the latest repo version, once on Main: https://github.com/galaxyproject/tools-iuc/pull/1005
