### ISSUE TITLE
Broken pipe: No access to Galaxy for a few seconds

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/galaxy#2341]
Hi,

I am on Galaxy 16.01, on a CentOs 6.7. Regularly, my Galaxy stops responding for a few minutes and then prints in paster.log a Broken Pipe:

```
128.164.102.245 - - [11/May/2016:08:58:26 -0400] "GET / HTTP/1.1" 200 - "http://161.253.199.24:8080/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
----------------------------------------
Exception happened during processing of request from ('128.164.102.245', 58114)
Traceback (most recent call last):
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
128.164.102.245 - - [11/May/2016:08:58:16 -0400] "GET /api/histories/f597429621d6eb2b/contents/datasets/1cd8e2f6b131e891 HTTP/1.1" 200 - "http://161.253.199.24:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
128.164.102.245 - - [11/May/2016:09:05:37 -0400] "GET /api/datatypes?extension_only=False& HTTP/1.1" 200 - "http://161.253.199.24:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
```

I can access to my WebServer without any troubles during this hang ;/.

**Comment by remimarenco** [comment]
Could it be possible my sqlite version is the one causing troubles? => Mine is 3.6.20 (2009-11-04)

**Comment by summerghw** [comment]
@remimarenco did you fix the problem, I met same problem as you.

**Comment by martenson** [comment]
@summerghw this is a 3 year old issue about Galaxy form 2016, if you have problem with some newer Galaxy, please create a new issue
