### ISSUE TITLE
OperationalError: (sqlite3.OperationalError) near "񐁓񐁌���𐀠������": syntax error

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/galaxy#2343]
Hi,

When I launch my Galaxy on one of my server, I have this error:

```
migrate.versioning.repository DEBUG 2016-05-11 10:07:34,446 Config: OrderedDict([('db_settings', OrderedDict([('__name__', 'db_settings'), ('repository_id', 'Galaxy'), ('version_table', 'migrate_version'), ('required_dbs', '[]')]))])
/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\x80\x81\xb0\xfa\x90\x81\xa1\xf8\x80\x81\xae\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:298: SAWarning: Exception attempting to detect unicode returns: OperationalError('(sqlite3.OperationalError) near "\xf1\x90\x81\x93\xf1\x90\x81\x8c\xf5\x80\x81\x83\xf0\xb0\x80\xa0\xf4\xb0\x81\x81\xfa\x80\x81\x94\xfd\x80\x80\xa7\xfc\xb0\x81\xa5\xf8\x80\x81\xb4\xfb\xa0\x81\xb5\xf8\xb0\x81\xa9\xf9\x80\x81\xaf\xf8\x80\x81\xa5\xf9\x90\x81\xb2\xfd\x90\x81\xb4\xfb\xa0\x81\xb2\xf9\xb0\x81\xb3\xf0\x90\x80\xa0\xf8\x80\x81\x93\xf0\x90\x81\x96\xf0\xb0\x81\x92\xf0\x90\x81\x88\xfa\x80\x81\x92\xfc\x80\x80\xb6\xfa\x90\x80\xa9\xf0\x90\x80\xa0\xf8\x80\x81\x93\xfb\xa0\x81\xa1\xfb\xa0\x81\xaf\xfc\x90\x81\x9f": syntax error',)
  "detect unicode returns: %r" % de)
Traceback (most recent call last):
  File "/home/svc_galaxy/remi/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 63, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/home/svc_galaxy/remi/galaxy/lib/galaxy/app.py", line 60, in __init__
    self._configure_models( check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file )
  File "/home/svc_galaxy/remi/galaxy/lib/galaxy/config.py", line 860, in _configure_models
    create_or_verify_database( db_url, config_file, self.config.database_engine_options, app=self )
  File "/home/svc_galaxy/remi/galaxy/lib/galaxy/model/migrate/check.py", line 50, in create_or_verify_database
    Table( "dataset", meta, autoload=True )
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 416, in __new__
    metadata._remove_table(name, schema)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 411, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 484, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 508, in _autoload
    self, include_columns, exclude_columns
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1971, in run_callable
    with self.contextual_connect() as conn:
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 454, in __init__
    exec_once(self.connection, self)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 246, in exec_once
    self(*args, **kw)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 1312, in go
    return once_fn(*arg, **kw)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 165, in first_connect
    dialect.initialize(c)
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 256, in initialize
    self._check_unicode_description(connection):
  File "/home/svc_galaxy/remi/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 343, in _check_unicode_description
    ]).compile(dialect=self)
OperationalError: (sqlite3.OperationalError) near "񐁓񐁌���𐀠������": syntax error
```

Do you know why?

Thanks

**Comment by martenson** [comment]
related to the closed issue linked above I believe
