### ISSUE TITLE
Fail to install on Ubuntu 16.04. Error: setuptools pkg_resources pip wheel failed with error code 1

### ISSUE THREAD

**Issue by gifi** [galaxyproject/galaxy#2513]
``` Bash
$ cat /etc/os-release 
```

``` Text
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

``` Bash
$ cd ~ && git clone https://github.com/galaxyproject/galaxy/
$ cd galaxy
$ git checkout -b master origin/master
$ sh run.sh
```

``` Text
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /home/galaxy/galaxy/.venv/bin/python2
Also creating executable in /home/galaxy/galaxy/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/galaxy/galaxy/.venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/home/galaxy/galaxy/.venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/scripts.py", line 14, in <module>
  File "/home/galaxy/galaxy/.venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/galaxy/galaxy/.venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1
```

Googling on that error suggests the error is related to locale settings. So I explicitly set the charset and the collation values in `~/galaxy/config/local_env.sh` as follows:

``` Bash
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```

But that didn't resolve the issue. Help of any kind is much welcome.

**Comment by gifi** [comment]
Please ignore this issue.
I found out Python wasn't well configured. A colleague of mine had made a custom Python installation in `/usr/local`, and after I had wept all of those home-brew binaries so that `apt-get install python` would carry on its task, there was no installation bug anymore.
