### ISSUE TITLE
Galaxy 16.04 history api error

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2551]
This POST request:

```
128.118.2.75 - - [25/Jun/2016:15:33:17 -0400] "POST /api/histories/XXX/contents?key=<some key> HTTP/1.1" 200 - "-" "python-requests/2.8.1"
```

Produces this error:

```
128.118.2.75 - - [25/Jun/2016:15:33:27 -0400] "PUT /api/histories/XXX/contents/YYY?key=<some key> HTTP/1.1" 500 - "-" "python-requests/2.8.1"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    return self.app( environ, start_response )
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 22, in __call__
    return self.app( environ, start_response )
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 163, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 178, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/.venv/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/gpfs/cyberstar/pughhpc/galaxy-cegr/python/ucs4/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 151, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 131, in __call__
    return self.handle_request( environ, start_response )
  File "lib/galaxy/web/framework/base.py", line 190, in handle_request
    body = method( trans, **kwargs )
  File "lib/galaxy/web/framework/decorators.py", line 227, in decorator
    kwargs['payload'] = __extract_payload_from_request(trans, func, kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 152, in __extract_payload_from_request
    content_type = trans.request.headers['content-type']
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/.venv/lib/python2.7/site-packages/webob/headers.py", line 139, in __getitem__
    return self.environ[_trans_name(hname)]
KeyError: 'CONTENT_TYPE'
```

**Comment by dannon** [comment]
Having trouble reproducing this one.  Is it a POST or a PUT (the two calls above differ)?  And what's the payload you're sending?

**Comment by gregvonkuster** [comment]
Thanks for taking alook at this @dannon 

I'm making the following bioblend API call.

```
gi.histories.update_dataset(history_id=history_id, dataset_id=dataset_id, genome_build=dbkey)
```

My temporary work-around is to do this:

```
diff --git a/lib/galaxy/web/framework/decorators.py b/lib/galaxy/web/framework/decorators.py
index 4460b49..5919dab 100644
--- a/lib/galaxy/web/framework/decorators.py
+++ b/lib/galaxy/web/framework/decorators.py
@@ -149,7 +149,10 @@ def expose_api( func, to_json=True, user_required=True ):


 def __extract_payload_from_request(trans, func, kwargs):
-    content_type = trans.request.headers['content-type']
+    try:
+        content_type = trans.request.headers['content-type']
+    except KeyError:
+        content_type = 'application/json'
     if content_type.startswith('application/x-www-form-urlencoded') or content_type.startswith('multipart/form-data'):
         # If the content type is a standard type such as multipart/form-data, the wsgi framework parses the request body
```

**Comment by dannon** [comment]
@gregvonkuster Sorry for the slow followup here, still catching up from GCC.  I'm running the following, and it works against both dev and release_16.04 for me, using bioblend 0.7.0.

```
import bioblend.galaxy
server = 'http://localhost:8080/'
api_key = '028b061160a8888f365c1dbeef03de99'
gi = bioblend.galaxy.GalaxyInstance(url=server, key=api_key)
gi.histories.update_dataset('72ad249754f05d26', '113b5e0ab7b052dd', genome_build='foo')
```

Are your Galaxy and/or bioblend versions different?

**Comment by dannon** [comment]
It also occurs to me that maybe a proxy server is in the mix and is potentially manipulating headers?  I'm having trouble coming up with other reasons this might happen.

**Comment by gregvonkuster** [comment]
I'm running Galaxy 16.04:

```
$ git status
# On branch release_16.04

$ git log
commit 15a4734aed73aabaf70f0da8a1eb54adeb75553b
Merge: dad193e 67c4df7
Author: Dannon Baker <dannon.baker@gmail.com>
Date:   Tue Jun 21 14:56:33 2016 -0400
```

I'm running Galaxy within a VM that has port 8080 opened.  I didn't set up the VM, so I suppose there could be some proxy stuff involved.  What is wierd is that this is the only API call I've encountered that is resulting in  this behavior, and I'm making a lot of API calls.

I'm using bioblend 0.7.0 - here it is in ~/galaxy/.venv/lib/python2.7/site-packages:

```
drwxrwxr-x.   6 galaxy-pugh galaxy-pugh  16384 Jun  3 13:05 bioblend
drwxrwxr-x.   2 galaxy-pugh galaxy-pugh  16384 May 23 10:08 bioblend-0.7.0.dist-info
```

I'm doing this in my script:

```
from bioblend import galaxy
...
gi = galaxy.GalaxyInstance(url=galaxy_base_url, key=api_key)
...
gi.histories.update_dataset(history_id=history_id, dataset_id=dataset_id, genome_build=dbkey)
```

I'm not quite sure what could be causing this either.  I do have the tweaky work-around, so if no one else is encountering this, maybe we can just leave this open for a bit and not spend any more time one it for now?  I have a feeling, though, that not many in the community are making this particular API call in their environments.

**Comment by dannon** [comment]
@gregvonkuster One last idea, and then I'm happy to shelve it for now since you have your workaround: can you verify the version of WebOb that's being used by the Galaxy process?

**Comment by gregvonkuster** [comment]
It looks like 1.4.1:

```
drwxrwxr-x.   2 galaxy-pugh galaxy-pugh  16384 May 23 10:08 webob
drwxrwxr-x.   2 galaxy-pugh galaxy-pugh  16384 May 23 10:08 WebOb-1.4.1.dist-info
```

**Comment by dannon** [comment]
@gregvonkuster Argh, ok.  WebOb does the header handling, so I was wondering if somehow you had a different version of that which manipulated defaults, but apparently not.

So, when I print my header items at the point in the code where you applied your workaround, I _do_ see the Content-Type entry, but it's empty.  

```
ipdb> print trans.request.headers.items()
[('Content-Length', '23'), ('User-Agent', 'python-requests/2.8.1'), ('Connection', 'keep-alive'), ('Host', 'localhost:8080'), ('Accept', '*/*'), ('Content-Type', ''), ('Accept-Encoding', 'gzip, deflate')]
```

The accessor automatically lower()s keys for matching, so that's not it.  I'd be interested to know what's actually showing up for you, though I definitely understand if you want to just move on for now :)

@nsoranzo You haven't seen this before, right?

**Comment by gregvonkuster** [comment]
@dannon Here's some info - looks like the headers in my are, in fact missing the content-type.

galaxy.web.framework.decorators DEBUG 2016-07-08 13:38:45,449 headers:

```
{'controller_action_key': u'api.history_contents.update', 'wsgi.multiprocess': True, 'paste.recursive.forward': <paste.recursive.Forwarder from />, 'webob._parsed_query_vars': (GET([(u'key', u'XXX')]), 'key=XXX'), 'paste.recursive.include': <paste.recursive.Includer from />, 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'PUT', 'UWSGI_ROUTER': 'http', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': 'key=XXX', 'paste.throw_errors': True, 'CONTENT_LENGTH': '32', 'HTTP_USER_AGENT': 'python-requests/2.8.1', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': 'hera.rcc.psu.edu', 'REMOTE_ADDR': '128.118.2.75', 'paste.expected_exceptions': [<class 'paste.httpexceptions.HTTPException'>], 'wsgi.url_scheme': 'http', 'webob._body_file': (<_io.BufferedReader>, <uwsgi._Input object at 0x2b137c486648>), 'SERVER_PORT': '8080', 'uwsgi.node': 'hera.rcc.psu.edu', 'uwsgi.core': 0, 'paste.recursive.script_name': '', 'wsgi.input': <_io.BytesIO object at 0x2b137c394050>, 'HTTP_HOST': 'galaxy-cegr.psu.edu:8080', 'paste.recursive.include_app_iter': <paste.recursive.IncluderAppIter from />, 'wsgi.multithread': True, 'paste.httpexceptions': <paste.httpexceptions.HTTPExceptionHandler object at 0x2b137d862410>, 'is_api_request': True, 'REQUEST_URI': '/api/histories/3462eb7d92da2810/contents/95656302c972ae30?key=XXX', 'HTTP_ACCEPT': '*/*', 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x2b137dbfb9c0>, 'REMOTE_PORT': '62155', 'paste.cookies': (<SimpleCookie: >, ''), 'uwsgi.version': '2.0.13.1', 'webob.is_body_seekable': True, 'request_id': 'd1f256f8453211e694cb005056ad0a39', 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>, 'HTTP_ACCEPT_ENCODING': 'gzip, deflate', 'PATH_INFO': '/api/histories/3462eb7d92da2810/contents/95656302c972ae30'}
```

kwargs:

```
{'history_id': u'3462eb7d92da2810', 'id': u'95656302c972ae30', u'key': u'XXX'}
```

**Comment by nsoranzo** [comment]
@dannon No, I haven't (or I don't remember!).
