### ISSUE TITLE
Conda resolver fails to build job environment

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2786]
I'm running the dev branch, and I see this on both Linux and OS X.  My Galaxy configuration sets conda as the primary dependency resolver.  I've made sure that the conda_prefix setting is a short path - here are all of my conda config settings:

```
conda_prefix = /home/greg/_conda
conda_exec = /home/greg/_conda/bin/conda
conda_debug = True
conda_ensure_channels = r,bioconda,iuc
conda_auto_install = True
conda_verbose_install_check = False
conda_auto_init = True
```

My PATH setting is this:

```
$ echo $PATH
/home/greg/work/git_workspace/galaxy/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
```

No conda executable is found on my PATH:

```
$ which conda
/usr/bin/which: no conda in (/home/greg/work/git_workspace/galaxy/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin)
```

I've installed this tool from the tool shed into my local Galaxy instance.

```
https://testtoolshed.g2.bx.psu.edu/view/greg/bmsb/303a662c7881
```

Attempting to execute the tool on Linux produces this error:

```
127.0.0.1 - - [15/Aug/2016:11:09:25 -0400] "GET /api/histories/1cd8e2f6b131e891/contents?details=fd767e8b7355e21a%2C3cc0effd29705aa3%2C915ae9a80309f157%2Cfa6833a4eadf9064&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2016-08-15T15%3A09%3A21.000Z&qv=False&qv=False HTTP/1.1" 200 - "http://localhost:8763/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
Error: ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: glib-2.43.0-2
galaxy.jobs.runners ERROR 2016-08-15 11:09:26,051 (47) Failure preparing job
Traceback (most recent call last):
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/jobs/__init__.py", line 901, in prepare
    self.dependency_shell_commands = self.tool.build_dependency_shell_commands(job_directory=self.working_directory)
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/tools/__init__.py", line 1291, in build_dependency_shell_commands
    metadata=metadata,
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/tools/deps/__init__.py", line 98, in dependency_shell_commands
    **kwds )
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/tools/deps/__init__.py", line 116, in find_dep
    dependency = resolver.resolve( name, version, type, **kwds )
  File "/home/greg/work/git_workspace/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 181, in resolve
    raise Exception("Conda dependency seemingly installed but failed to build job environment.")
Exception: Conda dependency seemingly installed but failed to build job environment.
```

A similar error occurs on OS X, but it is this:

```
DEBUG:conda.instructions: LINK('ncurses-5.9-8 /Users/gvk/_conda/pkgs 1')
INFO:progress.update:('ncurses', 14)
DEBUG:conda.install:pkgs_dir='/Users/gvk/_conda/pkgs', prefix='/Users/gvk/work/git_workspace/galaxy/database/job_working_directory/003/3034/conda-env', dist='ncurses-5.9-8', linktype=1
Error: ERROR: placeholder '/Users/ray/r_3_3_1-x64-3.5/envs/_build_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-8
galaxy.jobs.runners ERROR 2016-08-15 10:59:02,643 (3034) Failure preparing job
Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/jobs/__init__.py", line 901, in prepare
    self.dependency_shell_commands = self.tool.build_dependency_shell_commands(job_directory=self.working_directory)
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/__init__.py", line 1291, in build_dependency_shell_commands
    metadata=metadata,
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/deps/__init__.py", line 98, in dependency_shell_commands
    **kwds )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/deps/__init__.py", line 116, in find_dep
    dependency = resolver.resolve( name, version, type, **kwds )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 177, in resolve
    raise Exception("Conda dependency seemingly installed but failed to build job environment.")
Exception: Conda dependency seemingly installed but failed to build job environment.
```

Help is much appreciated!  ;)

**Comment by mvdbeek** [comment]
OK, we're getting closer, though it looks a bit strange, .apparently your conda prefix is still not short enough:

```
Error: ERROR: placeholder '/Users/ray/r_3_3_1-x64-3.5/envs/_build_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-8
```

**Comment by mvdbeek** [comment]
Can you try setting your job_working_directory to something short as well?

**Comment by gregvonkuster** [comment]
Thanks @mvdbeek that solves this one!  I see these short directory path requirements posing some problems for those desiring to migrate from the old tool_dependencies.xml to conda.  ;)

**Comment by mvdbeek** [comment]
Absolutely, I didn't even think about the job_working_directory, so it's very good to have your feedback. I opened https://github.com/galaxyproject/galaxy/pull/2789 to make things a bit smoother, and I hope it will be fixed on the conda side soon (1-2 weeks was the latest estimate in https://github.com/rtfd/readthedocs.org/issues/1902#issuecomment-239642982)

**Comment by gregvonkuster** [comment]
Thanks so much for all of your help with this @mvdbeek and @bgruening !  I'm on my way to getting some new R tools for the future Galaxy-entomology flavor working using conda dependencies.  ;)
