### ISSUE TITLE
Type mis-match in SelectToolParameter vs DynamicOptions filters

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#2987]
Found while working on a GMAP test as part of https://github.com/galaxyproject/tools-iuc/pull/964 testing with Galaxy from git under Mac OS X.

```
$ planemo test gmap.xml --galaxy_root ~/repositories/galaxy
...
Traceback (most recent call last):
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 289, in create
    vars = tool.handle_input( trans, incoming, history=target_history )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/__init__.py", line 1148, in handle_input
    self.populate_state( request_context, self.inputs, expanded_incoming, params, errors )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/__init__.py", line 1773, in populate_state
    state[ input.name ] = input.get_initial_value( request_context, context )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/parameters/grouping.py", line 585, in get_initial_value
    rval[ child_input.name ] = child_input.get_initial_value( trans, child_context )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/parameters/basic.py", line 853, in get_initial_value
    value = [ optval for _, optval, selected in options if selected ]
ValueError: too many values to unpack
...
```

Problem from https://github.com/galaxyproject/galaxy/blob/7dadb932d827ee168acefacbf041dad671d36c7f/lib/galaxy/tools/parameters/basic.py#L853

```
class SelectToolParameter( ToolParameter ):
    ...

    def get_initial_value( self, trans, other_values ):
        options = list( self.get_options( trans, other_values ) )
        if len(options) == 0 and trans.workflow_building_mode:
            return None
        value = [ optval for _, optval, selected in options if selected ]
        if len( value ) == 0:
            if not self.optional and not self.multiple and options:
                # Nothing selected, but not optional and not a multiple select, with some values,
                # so we have to default to something (the HTML form will anyway)
                value = options[ 0 ][ 1 ]
            else:
                value = None
        elif len( value ) == 1:
            value = value[0]

```

The `SelectToolParameter.get_initial_value` code expects `options` to be a list/tuple of options expressed as three-entry tuples. With debugging added:

```
$ planemo test gmap.xml --galaxy_root ~/repositories/galaxy
...
galaxy.tools.parameters.basic: DEBUG: There are 3 options
galaxy.tools.parameters.basic: DEBUG: Option: ('No quality scores', '', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Sanger quality scores', 'sanger', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Illumina quality scores', 'illumina', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 3 options
galaxy.tools.parameters.basic: DEBUG: Option: ('Use a built-in index', 'indexed', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Use gmapdb from the history', 'gmapdb', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Use a fasta reference sequence from the history', 'history', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning []
galaxy.tools.parameters.basic: DEBUG: There are 0 options
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing filter '<galaxy.tools.parameters.dynamic_options.ParamValueFilter object at 0x10c104810>'
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing filter '<galaxy.tools.parameters.dynamic_options.MultipleSplitterFilter object at 0x10c104910>'
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing filter '<galaxy.tools.parameters.dynamic_options.AdditionalValueFilter object at 0x10c104950>'
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing filter '<galaxy.tools.parameters.dynamic_options.SortByColumnFilter object at 0x10c104990>'
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [['', '', '', '']]
galaxy.tools.parameters.basic: DEBUG: There are 1 options
galaxy.tools.parameters.basic: DEBUG: Option: ['', '', '', '']
galaxy.web.framework.decorators: ERROR: Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 289, in create
    vars = tool.handle_input( trans, incoming, history=target_history )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/__init__.py", line 1148, in handle_input
    self.populate_state( request_context, self.inputs, expanded_incoming, params, errors )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/__init__.py", line 1773, in populate_state
    state[ input.name ] = input.get_initial_value( request_context, context )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/parameters/grouping.py", line 585, in get_initial_value
    rval[ child_input.name ] = child_input.get_initial_value( trans, child_context )
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/parameters/basic.py", line 862, in get_initial_value
    value = [ optval for _, optval, selected in options if selected ]
ValueError: too many values to unpack
```

The problem is that `DynamicOptions.get_options` returns a list whose entries are not three-entry tuples, rather a four entry list. Clearly there is an API mismatch here.

See https://github.com/galaxyproject/galaxy/blob/7dadb932d827ee168acefacbf041dad671d36c7f/lib/galaxy/tools/parameters/dynamic_options.py#L641

```
class DynamicOptions( object ):
    """Handles dynamically generated SelectToolParameter options"""
    ...

    def get_options( self, trans, other_values ):
        rval = []
        if self.file_fields is not None or self.tool_data_table is not None or self.dataset_ref_name is not None:
            options = self.get_fields( trans, other_values )
            for fields in options:
                rval.append( ( fields[self.columns['name']], fields[self.columns['value']], False ) )
        else:
            for filter in self.filters:
                rval = filter.filter_options( rval, trans, other_values )
        return rval
```

This is calling the filter code, but is not doing an `rval.append(...)` here - so only the final filter will have any effect, which looks like a bug in itself. Switching to an append does not magically fix it.

Debugging patch:

```
$ git diff
diff --git a/lib/galaxy/tools/parameters/basic.py b/lib/galaxy/tools/parameters/basic.py
index 75b8a0c..7d870d9 100644
--- a/lib/galaxy/tools/parameters/basic.py
+++ b/lib/galaxy/tools/parameters/basic.py
@@ -682,8 +682,10 @@ def DEFAULT_VALUE_MAP(x):
 def parse_dynamic_options(param, input_source):
     options_elem = input_source.parse_dynamic_options_elem()
     if options_elem is None:
+        log.debug("parse_dynamic_options returning None")
         options = None
     else:
+        log.debug("parse_dynamic_options returning dynamic_options.DynamicOptions( options_elem, param )")
         options = dynamic_options.DynamicOptions( options_elem, param )
     return options

@@ -734,6 +736,7 @@ class SelectToolParameter( ToolParameter ):
         self.legal_values = set()
         self.dynamic_options = input_source.get( 'dynamic_options', None )
         self.options = parse_dynamic_options( self, input_source )
+        log.debug("Created SelectToolParameter for %s with options %r" % (self.name, self.options))
         if self.options is not None:
             for validator in self.options.validators:
                 self.validators.append( validator )
@@ -752,15 +755,18 @@ class SelectToolParameter( ToolParameter ):

     def get_options( self, trans, other_values ):
         if self.options:
+            log.debug("Returning self.options.get_options( trans, other_values )")
             return self.options.get_options( trans, other_values )
         elif self.dynamic_options:
             call_other_values = self._get_dynamic_options_call_other_values( trans, other_values )
             try:
+                log.debug("Returning eval( self.dynamic_options, self.tool.code_namespace, call_other_values )")
                 return eval( self.dynamic_options, self.tool.code_namespace, call_other_values )
             except Exception as e:
                 log.debug( "Error determining dynamic options for parameter '%s' in tool '%s':", self.name, self.tool.id, exc_info=e )
                 return []
         else:
+            log.debug("Returning self.static_options")
             return self.static_options

     def get_legal_values( self, trans, other_values ):
@@ -850,6 +856,9 @@ class SelectToolParameter( ToolParameter ):
         options = list( self.get_options( trans, other_values ) )
         if len(options) == 0 and trans.workflow_building_mode:
             return None
+        log.debug("There are %i options" % len(options))
+        for o in options:
+            log.debug("Option: %s" % repr(o))
         value = [ optval for _, optval, selected in options if selected ]
         if len( value ) == 0:
             if not self.optional and not self.multiple and options:
diff --git a/lib/galaxy/tools/parameters/dynamic_options.py b/lib/galaxy/tools/parameters/dynamic_options.py
index 2483017..3de349b 100644
--- a/lib/galaxy/tools/parameters/dynamic_options.py
+++ b/lib/galaxy/tools/parameters/dynamic_options.py
@@ -635,10 +635,13 @@ class DynamicOptions( object ):
         if self.file_fields is not None or self.tool_data_table is not None or self.dataset_ref_name is not None:
             options = self.get_fields( trans, other_values )
             for fields in options:
+                log.debug("DynamicOptions.get_options doing fields %r" % repr(fields))
                 rval.append( ( fields[self.columns['name']], fields[self.columns['value']], False ) )
         else:
             for filter in self.filters:
+                log.debug("DynamicOptions.get_options doing filter %r" % repr(filter))
                 rval = filter.filter_options( rval, trans, other_values )
+        log.debug("DynamicOptions.get_options returning %s" % repr(rval))
         return rval

     def column_spec_to_index( self, column_spec ):
```

**Comment by yhoogstrate** [comment]
I think planemo is looking for a `.loc` file while there is only a `.loc.sample` file. If you copy the `.loc.sample` file into $planemo-galaxy-root/tool-data/ and run the test this error does not occur.

**Comment by peterjc** [comment]
Confirming, a missing `.loc` file triggers this - creating it avoids the `ValueError`:

```
$ touch ~/repositories/galaxy/tool-data/gmap_indices.loc
$ planemo test gmap.xml --galaxy_root ~/repositories/galaxy
...
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 3 options
galaxy.tools.parameters.basic: DEBUG: Option: ('No quality scores', '', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Sanger quality scores', 'sanger', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Illumina quality scores', 'illumina', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 3 options
galaxy.tools.parameters.basic: DEBUG: Option: ('Use a built-in index', 'indexed', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Use gmapdb from the history', 'gmapdb', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Use a fasta reference sequence from the history', 'history', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning []
galaxy.tools.parameters.basic: DEBUG: There are 0 options
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: There are 1 options
galaxy.tools.parameters.basic: DEBUG: Option: ('', '', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: There are 1 options
galaxy.tools.parameters.basic: DEBUG: Option: ('', '', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning []
galaxy.tools.parameters.basic: DEBUG: There are 0 options
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning []
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: There are 1 options
galaxy.tools.parameters.basic: DEBUG: Option: ('', '', False)
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: Returning self.options.get_options( trans, other_values )
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: There are 1 options
galaxy.tools.parameters.basic: DEBUG: Option: ('', '', False)
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options doing fields "['', '', '', '', '']"
galaxy.tools.parameters.dynamic_options: DEBUG: DynamicOptions.get_options returning [('', '', False)]
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 2 options
galaxy.tools.parameters.basic: DEBUG: Option: ('Use default settings', 'default', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Set Computation Options', 'advanced', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 2 options
galaxy.tools.parameters.basic: DEBUG: Option: ('Use default settings', 'default', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Set Options', 'used', False)
galaxy.tools.parameters.basic: DEBUG: Returning self.static_options
galaxy.tools.parameters.basic: DEBUG: There are 20 options
galaxy.tools.parameters.basic: DEBUG: Option: ('GMAP default output', 'gmap', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Summary of alignments', 'summary', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Alignment', 'align', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Alignment in three continuous lines', 'continuous', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Alignment in three lines per exon', 'continuous-by-exon', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Print output in compressed format', 'compress', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Print exons cDNA', 'exons_dna', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Print exons genomic', 'exons_gen', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Print protein sequence (cDNA)', 'protein_dna', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('Print protein sequence (genomic)', 'protein_gen', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('PSL (BLAT) format', 'psl', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('GFF3 gene format', 'gff3_gene', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('GFF3 match cDNA format', 'gff3_match_cdna', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('GFF3 match EST format', 'gff3_match_est', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('splicesites output (for GSNAP)', 'splicesites', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('introns output (for GSNAP)', 'introns', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('IIT FASTA exon map format', 'map_exons', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('IIT FASTA map format', 'map_ranges', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('coords in table format', 'coords', False)
galaxy.tools.parameters.basic: DEBUG: Option: ('SAM format', 'sam', True)
galaxy.tools: DEBUG: Validated and populated state for tool request (88.107 ms)
...
```

That ought to help fixing this bug within Galaxy (and then reporting the missing `.loc` file as a further enhancement).

(My test is failing with `Error creating a job for these tool inputs - Parameter gmapindex requires a value, but has no legal values defined.` which I can look into further)

**Comment by peterjc** [comment]
See also https://github.com/galaxyproject/planemo/issues/530 for having planemo handle `example.loc` when given `example.loc.sample` only.

**Comment by peterjc** [comment]
When there is (an empty) `.loc` file, this is going via the fields branch https://github.com/galaxyproject/galaxy/blob/7dadb932d827ee168acefacbf041dad671d36c7f/lib/galaxy/tools/parameters/dynamic_options.py#L638 and returns the list of 3-entry tuples expected:

```
class DynamicOptions( object ):
    """Handles dynamically generated SelectToolParameter options"""
    ...

    def get_options( self, trans, other_values ):
        rval = []
        if self.file_fields is not None or self.tool_data_table is not None or self.dataset_ref_name is not None:
            options = self.get_fields( trans, other_values )
            for fields in options:
                rval.append( ( fields[self.columns['name']], fields[self.columns['value']], False ) )
        else:
            for filter in self.filters:
                rval = filter.filter_options( rval, trans, other_values )
        return rval
```

i.e. This avoids the bug in the filters branch of the code.

**Comment by peterjc** [comment]
Reading the filter code `dynamic_options.py` it is clear that the assorted `filter.filter_options` methods just return a list of strings, not of 3-entry tuples expected.

I don't understand where the filters are handled in an else clause either...
