### ISSUE TITLE
Galaxy doesn't recognize conda in a conda-forge environment

### ISSUE THREAD

**Issue by blankclemens** [galaxyproject/galaxy#3018]
A fresh created Python 2 conda environment won't work with Galaxy if the conda-forge channel is activated.

I created a plain Python 2 environment through:

`conda create -n py2forge pyhon=2.7`

Starting Galaxy it looks like it doesn't recognize conda:

```
Fetching https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1679k  100 1679k    0     0  1890k      0 --:--:-- --:--:-- --:--:-- 1888k
Verifying /tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2.tar.gz checksum is aabc8ef18cddbd8a2a9c7f92bc43e2fea54b1147330d65db920ef3ce9812e3dc
New python executable in .venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/clemens/MEGA/g...axy/.venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/__init__.py", line 17, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/commands/__init__.py", line 6, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/commands/completion.py", line 4, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/basecommand.py", line 17, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/req/__init__.py", line 3, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/req/req_install.py", line 17, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 20, in <module>
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 48, in Evaluator
  File "/home/clemens/miniconda3/envs/py2plain/lib/python2.7/platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "/home/clemens/miniconda3/envs/py2plain/lib/python2.7/platform.py", line 1420, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.12 (default, Jul  1 2016, 15:12:24) \n[GCC 5.4.0 20160609]'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv.py", line 2363, in <module>
    main()
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/tmp/galaxy-virtualenv-NOcw7r/virtualenv-13.1.2/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/clemens/MEGA/g...axy/.venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

Doing the same with `conda-forge` disabled works fine - Galaxy starts with the usual `Warning: You have Conda installed. Skipping virtualenv activation. This could cause missing dependencies.`.

I have checked this also on a fresh ubuntu docker container to remove possible problems with my local setup - the result, that Galaxy doesn't find conda, is the same.

Can somebody confirm this? My package list with conda-forge enabled is (I guess the error messages are probably not key here):

```
ca-certificates           2016.8.31                     0    conda-forge
certifi                   2016.8.31                py27_0    conda-forge
ncurses                   5.9                           9    conda-forge
openssl                   1.0.2h                        2    conda-forge
pip                       8.1.2                    py27_0    conda-forge
python                    2.7.12                        1    conda-forge
readline                  6.2                           0    conda-forge
setuptools                26.1.1                   py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

With the default channel:

```
openssl                   1.0.2j                        0  
pip                       8.1.2                    py27_0  
python                    2.7.12                        1  
readline                  6.2                           2  
setuptools                27.2.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  
```

**Comment by hexylena** [comment]
This should be improved since you opened the issue, they've rewritten how conda works at startup. Thanks for the bug report Clemens

**Comment by blankclemens** [comment]
Thanks for closing!
