### ISSUE TITLE
Conda dependency issue with "Deeptools compute matrix" at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3022]
**Server**: http://usegalaxy.org

**Tool ID**: 
toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_compute_matrix/deeptools_compute_matrix/2.3.5.0

**Error**:

> Job Information
> 
> Conda dependency seemingly installed but failed to build job environment.
> Job Traceback
> 
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/**init**.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/**init**.py", line 901, in prepare
>     self.dependency_shell_commands = self.tool.build_dependency_shell_commands(job_directory=self.working_directory)
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/**init**.py", line 1291, in build_dependency_shell_commands
>     metadata=metadata,
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/deps/**init**.py", line 99, in dependency_shell_commands
>     **kwds )
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/deps/**init**.py", line 118, in find_dep
>     dependency = resolver.resolve( name, version, type, *_kwds )
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 203, in resolve
>     *_raise Exception("Conda dependency seemingly installed but failed to build job environment.")
> Exception: Conda dependency seemingly installed but failed to build job environment.**

**Comment by jennaj** [comment]
Already captured - follow this ticket for retest status https://github.com/galaxyproject/galaxy/issues/2331
