### ISSUE TITLE
Tool Shed installed section names not escaped

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3084]
Earlier today I installed https://toolshed.g2.bx.psu.edu/view/peterjc/tmhmm_and_signalp/ into our new Galaxy instance, and then for unrelated reasons had to restart the instance. It failed to start up again:

```
...
galaxy.jobs DEBUG 2016-10-24 14:39:57,371 Loading job configuration from ./config/job_conf.xml
galaxy.jobs DEBUG 2016-10-24 14:39:57,372 Read definition for handler 'main'
galaxy.jobs INFO 2016-10-24 14:39:57,373 Setting <handlers> default to child with id 'main'
galaxy.jobs DEBUG 2016-10-24 14:39:57,374 <destinations> default set to child with id or tag 'all.q'
galaxy.jobs DEBUG 2016-10-24 14:39:57,374 Done loading job configuration
beaker.container DEBUG 2016-10-24 14:39:58,124 data file ./database/citations/data/container_file/4/48/48e563f148dc04d8b31c94878c138019862e580d.cache
Traceback (most recent call last):
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/webapps/galaxy/buildapp.py", line 63, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/app.py", line 93, in __init__
    self._configure_toolbox()
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/config.py", line 775, in _configure_toolbox
    self.reload_toolbox()
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/config.py", line 761, in reload_toolbox
    self.toolbox = tools.ToolBox( tool_configs, self.config.tool_path, self )
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 111, in __init__
    app=app,
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/base.py", line 1051, in __init__
    super(BaseGalaxyToolBox, self).__init__(config_filenames, tool_root_dir, app)
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/base.py", line 71, in __init__
    self._init_integrated_tool_panel( app.config )
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/integrated_panel.py", line 36, in _init_integrated_tool_panel
    self._load_integrated_tool_panel_keys()
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/tools/toolbox/base.py", line 355, in _load_integrated_tool_panel_keys
    tree = parse_xml( self._integrated_tool_panel_config )
  File "/mnt/shared/galaxy/galaxy-dist/lib/galaxy/util/__init__.py", line 187, in parse_xml
    root = tree.parse( fname, parser=ElementTree.XMLParser( target=DoctypeSafeCallbackTarget() ) )
  File "/mnt/shared/galaxy/apps/python/2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/mnt/shared/galaxy/apps/python/2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/mnt/shared/galaxy/apps/python/2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 164, column 40
Removing PID file paster.pid
```

The first bug is that Galaxy does not not handle this exception gracefully and fails to say which XML file is at fault. Luckily my guess was accurate.

Here is line 164 onwards from `integrated_tool_panel.xml`

```
    <section id="protein_&_gene_analysis" name="Protein & gene analysis" version="">
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/promoter2/0.0.10" />
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/Psortb/0.0.7" />
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/wolf_psort/0.0.9" />
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/signalp3/0.0.15" />
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/tmhmm2/0.0.14" />
        <tool id="toolshed.g2.bx.psu.edu/repos/peterjc/tmhmm_and_signalp/rxlr_motifs/0.0.11" />
    </section>
```

Likewise in `config/shed_tool_conf.xml` Galaxy has failed to escape the ampersand which I entered as the tool section name when installing this suite from the Tool Shed via the Galaxy Admin web interface.

I could manually fix this in `config/shed_tool_conf.xml` and `integrated_tool_panel.xml` using the word `and` instead (having had some frustration with the auto-regeneration of `integrated_tool_panel.xml` when trying to use `&amp;` instead).

**Comment by mvdbeek** [comment]
Hi @peterjc,

i confirm this is a bug, and thanks for pointing this our on the ML.
I'll have a look if I can find a solution.

**Comment by mvdbeek** [comment]
Let us know if we should port this back to older releases, I would consider this a serious limitation if galaxy doesn't start back up.

**Comment by peterjc** [comment]
At least two people have fallen over this bug now (me and Miuki, reported via the mailing list) and it does seem very easy to trigger - entering an ampersand (or any other character needing escaping) as a new Tool Section name.

Since this is a very small change, with little risk of side effects, I would recommend back porting it.

**Comment by peterjc** [comment]
Separately, as noted in the original issue, can the logging here specify which XML file was invalid?

**Comment by mvdbeek** [comment]
Sure, that's a good idea.
