### ISSUE TITLE
sub-workflows chaining problem

### ISSUE THREAD

**Issue by eteriSokhoyan** [galaxyproject/galaxy#3120]
Unfortunately it seems i can't chain 2 simple workflows. 
As u can see in picture 1 and 2 i have very simple workflows, then i want to chain them in 'super workflow' like in picture 3. When i run the 'super' workflow it runs the first sub workflow but doesn't reach to the second one. 

pic:1 

![sub1](https://cloud.githubusercontent.com/assets/12526955/19964119/39b77054-a1c0-11e6-840e-711c0f982017.png)

pic:2
![sub2](https://cloud.githubusercontent.com/assets/12526955/19964125/40998010-a1c0-11e6-9efe-52a3961bffbd.png)

pic:3
![superflow](https://cloud.githubusercontent.com/assets/12526955/19964129/44ed171c-a1c0-11e6-85da-df242ceccfa8.png)

Here is the error i get:

```
Traceback (most recent call last):
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 160, in invoke
    jobs = self._invoke_step( step )
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 230, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/modules.py", line 435, in execute
    subworkflow_invoker = progress.subworkflow_invoker( trans, step )
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 353, in subworkflow_invoker
    subworkflow_progress = self.subworkflow_progress(step)
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 381, in subworkflow_progress
    is_data=is_data,
  File "/home/eteri/GalaxyProject/galaxy/lib/galaxy/workflow/run.py", line 305, in replacement_for_connection
    raise Exception( message )
Exception: Workflow evaluation problem - failed to find output_name 1:out_file1 in step_outputs {None: <galaxy.model.HistoryDatasetAssociation object at 0x7f323f703890>}

```

Any help is appreciated :)

**Comment by bgruening** [comment]
@jmchilton any idea about this one? Thanks!

**Comment by mvdbeek** [comment]
This is pretty old by now but still current ... The issue is that the subworkflows need to define a `Label` under configure outputs, and then that label needs to be used in the connection.

The UX here is really not clear ... I wonder if we can make a fallback work somehow.
