### ISSUE TITLE
AttributeError: 'HistoryDatasetCollectionAssociation' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#3194]
This looks like a collections bug possibly originating when a collection is selected as input to Cuffmerge in particular and setting _Use Sequence Data_ to _Yes_, the list of reference genome goes empty:
![screen shot 2016-11-17 at 5 22 54 pm](https://cloud.githubusercontent.com/assets/338642/20410350/9475f04e-acea-11e6-86cc-d6f0c7b5ce27.png)

Not selecting the collection, works fine:
![screen shot 2016-11-17 at 5 23 14 pm](https://cloud.githubusercontent.com/assets/338642/20410369/a0997030-acea-11e6-968a-ab1c60130b6c.png)

When embedded as part of a workflow, it appears to result in the following:
```
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/mnt/galaxy/galaxy-app/lib/galaxy/jobs/__init__.py", line 893, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/evaluation.py", line 63, in set_compute_environment
    visit_input_values( self.tool.inputs, incoming, validate_inputs )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 104, in visit_input_values
    visit_input_values( input.cases[ values[ '__current_case__' ] ].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 104, in visit_input_values
    visit_input_values( input.cases[ values[ '__current_case__' ] ].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 110, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 75, in callback_helper
    new_value = callback( **args )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/evaluation.py", line 61, in validate_inputs
    value = input.from_json( value, request_context, context )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/basic.py", line 901, in from_json
    legal_values = self.get_legal_values( trans, other_values )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/basic.py", line 866, in get_legal_values
    return set( v for _, v, _ in self.options.get_options( trans, other_values ) )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/dynamic_options.py", line 632, in get_options
    options = self.get_fields( trans, other_values )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/dynamic_options.py", line 598, in get_fields
    options = filter.filter_options( options, trans, other_values )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/dynamic_options.py", line 137, in filter_options
    this_meta_value = single_ref.metadata.get( self.key, None )
AttributeError: 'HistoryDatasetCollectionAssociation' object has no attribute 'metadata'
```

**Comment by abretaud** [comment]
That's an old issue, but found a similar error with 20.01 when a user tried to use cuffcompare with data collection.
Here's the error:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 471, in create
    return self._create(trans, payload, **kwd)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 529, in _create
    vars = tool.handle_input(trans, incoming, history=target_history, use_cached_job=use_cached_job)
  File "lib/galaxy/tools/__init__.py", line 1480, in handle_input
    all_params, all_errors, rerun_remap_job_id, collection_info = self.expand_incoming(trans=trans, incoming=incoming, request_context=request_context)
  File "lib/galaxy/tools/__init__.py", line 1460, in expand_incoming
    populate_state(request_context, self.inputs, expanded_incoming, params, errors)
  File "lib/galaxy/tools/parameters/__init__.py", line 316, in populate_state
    state[input.name] = input.get_initial_value(request_context, context)
  File "lib/galaxy/tools/parameters/grouping.py", line 702, in get_initial_value
    rval[child_input.name] = child_input.get_initial_value(trans, child_context)
  File "lib/galaxy/tools/parameters/grouping.py", line 702, in get_initial_value
    rval[child_input.name] = child_input.get_initial_value(trans, child_context)
  File "lib/galaxy/tools/parameters/basic.py", line 916, in get_initial_value
    options = list(self.get_options(trans, other_values))
  File "lib/galaxy/tools/parameters/basic.py", line 816, in get_options
    return self.options.get_options(trans, other_values)
  File "lib/galaxy/tools/parameters/dynamic_options.py", line 708, in get_options
    options = self.get_fields(trans, other_values)
  File "lib/galaxy/tools/parameters/dynamic_options.py", line 674, in get_fields
    options = filter.filter_options(options, trans, other_values)
  File "lib/galaxy/tools/parameters/dynamic_options.py", line 188, in filter_options
    this_meta_value = single_ref.metadata.get(self.key, None)
AttributeError: 'HistoryDatasetCollectionAssociation' object has no attribute 'metadata'
```

And commenting this line in the wrapper was enough to avoid this error:
https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/cufflinks/cuffcompare/cuffcompare_wrapper.xml#L77

Looking at the code, https://github.com/galaxyproject/galaxy/blob/release_20.01/lib/galaxy/tools/parameters/dynamic_options.py#L175 is supposed to make sure HistoryDatasetCollectionAssociation are replaced before https://github.com/galaxyproject/galaxy/blob/release_20.01/lib/galaxy/tools/parameters/dynamic_options.py#L187, I don't understand why there's still a HistoryDatasetCollectionAssociation there...

**Comment by mvdbeek** [comment]
Pretty sure we fixed this recently, don't have the exact commit at hand though.
