### ISSUE TITLE
api + collection error

### ISSUE THREAD

**Issue by fmareuil** [galaxyproject/galaxy#3219]
Hello,

We encountered an error with the last version of galaxy with the galaxy api, when we want to get details of a tool that has an output data collection.
`{"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}`
We encountered this error directly with the API or with bioblend.
You can see the traceback below:
```
galaxy.web.framework.decorators ERROR 2016-11-25 16:20:25,242 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File ".../galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func( self, trans, *args, **kwargs )
  File ".../galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 86, in show
    return tool.to_dict( trans, io_details=io_details, link_details=link_details )
  File ".../galaxy/lib/galaxy/tools/__init__.py", line 1657, in to_dict
    tool_dict[ 'outputs' ] = [ output.to_dict( app=self.app ) for output in self.outputs.values() ]
TypeError: to_dict() got an unexpected keyword argument 'app'

```
Thank you for your help,
Best regards,

Fabien

**Comment by fmareuil** [comment]
cc @hmenager
