### ISSUE TITLE
Run stable integration tests against PRs

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3360]
- [x] Get them to pass consistently on n6 against dev.
   - [x] Fix failing Conda tests on n6.
   - [x] Fix one failing re-submission test on n6.
   - [x] Fix xunit report problem.
- [x] Enable this to work using the PR builder and targeting n4.

Failing Conda tests:

```
Python 2.7.11 :: Continuum Analytics, Inc.
Error: PREFIX too long: 142 characters, but only 128 allowed
Error: post-link failed for: openssl-1.0.2g-0
test_conda_clean (integration.test_resolvers.CondaResolutionIntegrationTestCase) ... /bin/sh: 1: /tmp/tmpDCTnSd/tmpSmJ2pu/tmpXTpi9c/database/new_files_path_HC6QrN/tmpDIBNxj/tmpmjrQFA/tmp1FYW7m/database/new_files_path_mIbgx5/tmp2v_E03/conda/bin/conda: not found
/bin/sh: 1: /tmp/tmpDCTnSd/tmpSmJ2pu/tmpXTpi9c/database/new_files_path_HC6QrN/tmpDIBNxj/tmpmjrQFA/tmp1FYW7m/database/new_files_path_mIbgx5/tmp2v_E03/conda/bin/conda: not found
ok
test_conda_install_through_tools_api (integration.test_resolvers.CondaResolutionIntegrationTestCase) ... FAIL
Test that dependency is not installed (response['dependency_type'] == 'null'). ... ok
Test installation of GNUPLOT dependency. ... FAIL
Test installation of gnuplot with a version that does not exist. ... FAIL
GET request to dependency_resolvers/dependency with GNUPLOT dependency. ... FAIL
GET request to dependency_resolvers/dependency with GNUPLOT dependency. ... FAIL
```

Failing re-submission test:

```

======================================================================
FAIL: test_condition_any_failure (integration.test_job_resubmission.JobResubmissionIntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/galaxy/test/integration/test_job_resubmission.py", line 58, in test_condition_any_failure
    "failure_state": "unknown_error"})
  File "/galaxy/test/integration/test_job_resubmission.py", line 98, in _assert_job_fails
    assert exception_thrown
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
```

**Comment by jmchilton** [comment]
Tests and xunit problems have been fixed by #3370 #3365. I think this needs to be relocated to n4 and have the pull request watchers stuff enabled. I'll wait until Jenkins stabilizes a bit first.

**Comment by jmchilton** [comment]
I believe everything is fine with the job against dev thanks to some fixes for regressions including #3439. I guess I should enable these tests.

**Comment by jmchilton** [comment]
All done - there is an extra green dot on PRs now.

**Comment by martenson** [comment]
perfect, thanks @jmchilton !
