### ISSUE TITLE
ht-condor job runner crash with docker universe

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3455]
```
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "/galaxy-central/lib/galaxy/jobs/runners/condor.py", line 69, in queue_job
    container = self.find_container( job_wrapper )
AttributeError: 'CondorJobRunner' object has no attribute 'find_container'
```

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/condor.py#L69

ping @abdulrahmanazab

**Comment by bgruening** [comment]
It used to be https://github.com/galaxyproject/galaxy/commit/ba409e75181224c80f0acf02530cac31fe28461c but changed here https://github.com/galaxyproject/galaxy/commit/917c882255ff1261bb99bb4bfc8bd1e165e26b96. I will try to track this down tomorrow.
