### ISSUE TITLE
Infinite loop of _complete_terminal_job using slurm if no accounting is available and jobs die quickly

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/galaxy#3456]
This is likely related to #2402. I'm running 16.10 via Björn's docker container and sending jobs to a slurm-based cluster where `sacct` isn't in use. I've recently noticed that if a jobs gets run on the cluster and dies quickly (an error is thrown in <1 second) that I get an infinite repeat of the following:

    galaxy.jobs.runners ERROR 2017-01-20 14:48:23,561 Unhandled exception checking active jobs
    Traceback (most recent call last):
      File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 527, in monitor
        self.check_watched_items()
      File "/galaxy-central/lib/galaxy/jobs/runners/drmaa.py", line 293, in check_watched_items
        if self._complete_terminal_job( ajs, drmaa_state=state ) is not None:
      File "/galaxy-central/lib/galaxy/jobs/runners/slurm.py", line 133, in _complete_terminal_job
        return super( SlurmJobRunner, self )._complete_terminal_job( ajs, drmaa_state=drmaa_state )
      File "/galaxy-central/lib/galaxy/jobs/runners/drmaa.py", line 235, in _complete_terminal_job
        self._handle_metadata_externally( ajs.job_wrapper, resolve_requirements=True )
      File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 277, in _handle_metadata_externally
        kwds={ 'overwrite' : False } )
      File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 1682, in setup_external_metadata
        **kwds )
      File "/galaxy-central/lib/galaxy/model/metadata.py", line 830, in setup_external_metadata
        " ".join( map( __metadata_files_list_to_cmd_line, metadata_files_list ) ),
      File "/galaxy-central/lib/galaxy/model/metadata.py", line 758, in __metadata_files_list_to_cmd_line
        __get_filename_override(),
      File "/galaxy-central/lib/galaxy/model/metadata.py", line 750, in __get_filename_override
        if dataset_path.real_path == metadata_files.dataset.file_name:
      File "/galaxy-central/lib/galaxy/model/__init__.py", line 1891, in get_file_name
        return self.dataset.get_file_name()
      File "/galaxy-central/lib/galaxy/model/__init__.py", line 1696, in get_file_name
        filename = self.object_store.get_filename( self )
      File "/galaxy-central/lib/galaxy/objectstore/__init__.py", line 487, in get_filename
        return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
      File "/galaxy-central/lib/galaxy/objectstore/__init__.py", line 508, in _call_method
        % ( method, str( obj ), str( kwargs ) ) )
    ObjectNotFound: objectstore, _call_method failed: get_filename on <galaxy.model.Dataset object at 0x7fb27ceacfd0>, kwargs: {}

I've added in a few `log.warn()` in the code to diagnose this and this will only happen if galaxy is looking for an output file (e.g., `/data/galaxy/files/000/124/dataset_124805.dat`) that wasn't created due to the job running into an error. The error code (e.g., from `job_working_directory/087/87768/galaxy_87768.ec`) is 1, so it shouldn't be overly surprising that the object store can't find the file. If I `touch` the file then of course the error immediately goes away. For whatever reason the drmaa state in `lib/galaxy/jobs/runners/slurm.py` is getting set to `done`, which I presume is related to the lack of `sacct` not running.

For what it's worth, I've only been seeing these sorts of errors since Tuesday, when I created an `object_store_conf.xml` file (we added a second storage mount point and I wan't to use a `distributed` object store).

I would assume that the ideal behavior would be for the job monitor to just create an empty output file in cases like this.

**Comment by nsoranzo** [comment]
I don't know much about the object store, but Galaxy looks for the output dataset because it thinks the job terminated successfully. This can happen if:
- the job really terminated successfully or
- `scontrol` for the job returns 'slurm_load_jobs error: Invalid job id specified' (usually because after 5' the job is removed from Slurm's active database, see MinJobAge in https://slurm.schedmd.com/slurm.conf.html ) and you don't have `sacct` correctly configured.

**Comment by dpryan79** [comment]
Hmm, well I've convinced IT to setup job accounting, so hopefully this issue will go away. I'll close this unless it reoccurs.
