### ISSUE TITLE
Regression in unit tests using compressed FASTQ input files

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3527]
Example from https://github.com/peterjc/pico_galaxy/blob/master/tools/seq_filter_by_mapping/seq_filter_by_mapping.xml

``` xml
	<test>
            <param name="input_file" value="SRR639755_mito_pairs.fastq.gz" ftype="fastqsanger" />
            <param name="mapping_file" value="SRR639755_sample_by_coord.sam" ftype="sam" />
            <param name="pair_mode" value="lax" />
            <param name="output_choice" value="pos" />
            <output name="output_pos" file="SRR639755_sample_lax.fastq" ftype="fastqsanger" />
        </test>
```

The tool ships with a gzipped FASTQ file of test data, which until recently would automatically get unzipped by Galaxy when creating the history as part of running the tests, effectively running this:

```
$ tools/seq_filter_by_mapping/seq_filter_by_mapping.py -i test-data/SRR639755_mito_pairs.fastq -f "fastqsanger" -m lax -p positive_matches.fastq test-data/SRR639755_sample_by_coord.sam 
Loaded 5 mapped IDs
Looking for SRR639755.2301126, SRR639755.6035319, SRR639755.6451003, SRR639755.6955680, SRR639755.7076397
Generating matching FASTQ file
10 mapped and 1054 unmapped reads.
In total 1064 reads, of which 0.9% mapped
```

This is now failing on Galaxy's dev branch, but still works on Galaxy's stable master branch, see e.g. https://travis-ci.org/peterjc/pico_galaxy/jobs/197266012 

```
-------------------- >> begin captured stdout << ---------------------
History with id 0e797101c95aea67 in error - summary of datasets in error below.
--------------------------------------
| 3 - SRR639755_mito_pairs.fastq.gz (mapped) (HID - NAME) 
| Dataset Blurb:
|  error
| Dataset Info:
|  Loaded 5 mapped IDs
|  Looking for SRR639755.2301126, SRR639755.6035319, SRR639755.6451003, SRR639755.6955680, SRR639755.7076397
|  Generating matching FASTQ file
|  Fatal error: Exit code 1 ()
|  Traceback (most recent call last):
|  File "/home/travis/build/peterjc
| Dataset Job Standard Output:
|  Loaded 5 mapped IDs
|  Looking for SRR639755.2301126, SRR639755.6035319, SRR639755.6451003, SRR639755.6955680, SRR639755.7076397
|  Generating matching FASTQ file
| Dataset Job Standard Error:
|  Fatal error: Exit code 1 ()
|  Traceback (most recent call last):
|  File "/home/travis/build/peterjc/pico_galaxy/tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 373, in <module>
|  pos_count, neg_count = sequence_filter(in_file, out_positive_file, out_negative_file, ids)
|  File "/home/travis/build/peterjc/pico_galaxy/tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 304, in fastq_filter
|  for title, seq, qual in FastqGeneralIterator(handle):
|  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 915, in FastqGeneralIterator
|  raise ValueError("End of file without quality information.")
|  ValueError: End of file without quality information.
|
```

Using the dev branch after merging of #3145, it appears that despite the tool XML saying ``sangerfastq``, Galaxy is putting the file into the test history as is, as can be mimicked at the command line:

```
$ tools/seq_filter_by_mapping/seq_filter_by_mapping.py -i test-data/SRR639755_mito_pairs.fastq.gz -f "fastqsanger" -m lax -p positive_matches.fastq test-data/SRR639755_sample_by_coord.sam 
Loaded 5 mapped IDs
Looking for SRR639755.2301126, SRR639755.6035319, SRR639755.6451003, SRR639755.6955680, SRR639755.7076397
Generating matching FASTQ file
Traceback (most recent call last):
  File "tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 373, in <module>
    pos_count, neg_count = sequence_filter(in_file, out_positive_file, out_negative_file, ids)
  File "tools/seq_filter_by_mapping/seq_filter_by_mapping.py", line 304, in fastq_filter
    for title, seq, qual in FastqGeneralIterator(handle):
  File "/home/pc40583/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 915, in FastqGeneralIterator
    raise ValueError("End of file without quality information.")
ValueError: End of file without quality information.
```

The ambiguous error message from the tool is my fault. I may now catch compressed inputs and cope with them nicely...

See also #3511

**Comment by martenson** [comment]
Hi Peter,

we have worked on fixes regarding the compressed fastq files in the
release_17.01 branch and did not merge forward yet. I have created a PR for
the merge - afterwards the dev branch should auto-unpack archives by
default again.

Is that the behavior that was giving you trouble?

Martin

**Comment by peterjc** [comment]
That should fix this, thanks @martenson - I assumed that the ``dev`` branch would already have had the recent fixes for compressed FASTQ files.

Will it be possible to deliberately use a compressed FASTQ file as input in a test, e.g.

``` xml
<param name="input_file" value="SRR639755_mito_pairs.fastq.gz" ftype="fastqsanger.gz" />
```

**Comment by martenson** [comment]
@peterjc I believe so. If it does not that is a bug.

**Comment by peterjc** [comment]
OK - I'll revisit this at some point to take advantage of compressed FASTQ support.

In the short term I'll wait for the fix to be merged into the dev branch.

**Comment by martenson** [comment]
@peterjc merged now

**Comment by peterjc** [comment]
That fixed it - a passing build where I have not changed anything relevant to the compressed FASTQ test files: https://travis-ci.org/peterjc/pico_galaxy/builds/197353234

Thank you!
