### ISSUE TITLE
History import does not work well with subdirectories

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#3628]
I am trying to import a history from an old Galaxy server. The exported history is composed of subdirectories (e.g from FastaQC runs), say:

```
datasets/FastQC_on_data_5__Webpage_7.html
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc.html
datasets/extra_files_path_7/rgFastQCSCQT0L.log
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc.zip
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/summary.txt
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/fastqc_data.txt
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/fastqc_report.html
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/Images/
datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc/Images/per_sequence_quality.png
```

The import code chokes on these directories (i.e. if there is deep directory structure), I get this error:
`IOError: [Errno 21] Is a directory: u'/export/galaxy-central/database/files/tmphbQyRK/datasets/extra_files_path_7/INV.clipped_1.paired_1.groom_fastqc'`

I have tracked the error on  `galaxy/tools/imp_exp/__init__.py` (around line 177 - did not find the code easily on github)

```
                                if file_list:
                                    for extra_file in file_list:
                                        self.app.object_store.update_from_file(
                                            hda.dataset, extra_dir='dataset_%s_files' % hda.dataset.id,
                                            alt_name=extra_file, file_name=os.path.join( archive_dir, dataset_extra_files_path, extra_file ),
                                            create=True )

```

**Comment by mvdbeek** [comment]
@jmchilton this is still an issue on dev:
```
galaxy.jobs ERROR 2019-04-08 15:02:24,310 [p:13596,w:0,m:4] [LocalRunner.work_thread-2] Unable to cleanup job 798
Traceback (most recent call last):
  File "lib/galaxy/jobs/__init__.py", line 1518, in cleanup
    galaxy.tools.imp_exp.JobImportHistoryArchiveWrapper(self.app, self.job_id).cleanup_after_job()
  File "lib/galaxy/tools/imp_exp/__init__.py", line 50, in cleanup_after_job
    model_store.perform_import(new_history, job=job, new_history=True)
  File "lib/galaxy/model/store/__init__.py", line 169, in perform_import
    self._import_datasets(object_import_tracker, datasets_attrs, history, new_history, job)
  File "lib/galaxy/model/store/__init__.py", line 328, in _import_datasets
    create=True)
  File "lib/galaxy/objectstore/__init__.py", line 485, in update_from_file
    raise ex
IOError: [Errno 21] Is a directory: u'/Users/mvandenb/src/galaxy/database/tmp/tmpYBPdK0/datasets/extra_files_path_8/1000trimmed_fastq_bz2_fastqc'
```

**Comment by jmchilton** [comment]
I noticed this would be a problem when reviewing the code, didn't know there was an issue for this. I'll see what I can do.

**Comment by jmchilton** [comment]
Fix and unit test is here (https://github.com/galaxyproject/galaxy/pull/7058/commits/39c13ca3339b12db8258c69cac66d75fde17ab7e). It is conflicted against dev but I'll figure something out.
