### ISSUE TITLE
404'd while installing requirements.txt

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#3885]
I am running 15.10, fresh virtualenv with python 2.7. 

```
pip install -r requirements.txt
Downloading/unpacking http://svgfig.googlecode.com/files/svgfig-1.1.6.tgz (from -r requirements.txt (line 63))
  HTTP error 404 while getting http://svgfig.googlecode.com/files/svgfig-1.1.6.tgz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/galaxy/.venv/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 795, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

Storing debug log for failure in /home/le-me/.pip/pip.log

```

**Comment by MatthewRalston** [comment]
It looks like the code base has moved to github. Replacing the line in requirements.txt with the correct url fixed this error. 

https://github.com/jpivarski/svgfig/releases
