### ISSUE TITLE
Create DBKey and Reference Genome: Uncaught exception in exposed API method

### ISSUE THREAD

**Issue by lifepillar** [galaxyproject/galaxy#3902]
I am trying to add a reference genome to a local instance in my Ubuntu box. Using Galaxy 17.01.

I have installed the data_manager_fetch_genome_dbkeys_all_fasta and other the data managers for indexing (data_manager_sam_fasta_index_builder, data_manager_picard_index_builder, and data_manager_twobit_builder). When I visit *Admin > Local data > Create DBKey and Reference Genome*, I get an error: *Uncaught exception in exposed API method*. This is what I see in the console:

```
galaxy.web.framework.decorators ERROR 2017-04-08 10:22:00,380 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/var/galaxy/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "/var/galaxy/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 98, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "/var/galaxy/galaxy/lib/galaxy/tools/__init__.py", line 1874, in to_json
    tools = self.app.toolbox.get_loaded_tools_by_lineage( self.id )
  File "/var/galaxy/galaxy/lib/galaxy/tools/toolbox/base.py", line 492, in get_loaded_tools_by_lineage
    tool_lineage = self._lineage_map.get( tool_id )
  File "/var/galaxy/galaxy/lib/galaxy/tools/toolbox/lineages/factory.py", line 38, in get
    lineage = ToolShedLineage.from_tool_id( self.app, tool_id )
  File "/var/galaxy/galaxy/lib/galaxy/tools/toolbox/lineages/tool_shed.py", line 70, in from_tool_id
    return ToolShedLineage( app, tool_version )
  File "/var/galaxy/galaxy/lib/galaxy/tools/toolbox/lineages/tool_shed.py", line 53, in __init__
    self.tool_version_id = tool_version.id
  File "/var/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/var/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = state._load_expired(state, passive)
  File "/var/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/var/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 610, in load_scalar_attributes
    (state_str(state)))
DetachedInstanceError: Instance <ToolVersion at 0x7f20d07ef390> is not bound to a Session; attribute refresh operation cannot proceed
```

How can I fix that?

**Comment by lifepillar** [comment]
Ah, I am using revision 16ab4dd6a0e5 of data_manager_fetch_genome_dbkeys_all_fasta.

**Comment by lifepillar** [comment]
FYI, I have fixed the problem (which affected also the other data managers installed) by restarting the Galaxy instance, and logging out and in again.

**Comment by bgruening** [comment]
In 17.01 you might need restart after installing the data managers. This will be better in 17.05.
Glad it is working for you now!

**Comment by mvdbeek** [comment]
I am pushing out a fix in minute.

**Comment by mvdbeek** [comment]
@lifepillar this should be fixed if you update your galaxy to the latest commit in release 17.01.
Please re-open the issue if you encounter this issue again.
