### ISSUE TITLE
Picard indexing fails with JAVA_JAR_PATH KeyError

### ISSUE THREAD

**Issue by lifepillar** [galaxyproject/galaxy#3907]
Hi,
in a freshly installed local instance (release 17.01), when I try to launch the Picard data manager (data_manager_picard_index_builder), the job fails with this error:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_picard_index_builder/dc28cd6a1d44/data_manager_picard_index_builder/data_manager/picard_index_builder.py", line 81, in <module>
    main()
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_picard_index_builder/dc28cd6a1d44/data_manager_picard_index_builder/data_manager/picard_index_builder.py", line 74, in main
    build_picard_index( data_manager_dict, options.fasta_filename, params, target_directory, dbkey, sequence_id, sequence_name, data_table_name=options.data_table_name or DEFAULT_DATA_TABLE_NAME )
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_picard_index_builder/dc28cd6a1d44/data_manager_picard_index_builder/data_manager/picard_index_builder.py", line 34, in build_picard_index
    args = [ 'java', '-Xmx4G', '-jar', os.path.join( os.environ[ 'JAVA_JAR_PATH' ], 'CreateSequenceDictionary.jar' ), 'R=%s' % sym_linked_fasta_filename, 'O=%s.dict' % prefix ]
  File "/var/galaxy/galaxy/.venv/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'JAVA_JAR_PATH'
```

I have tried to reset metadata, but without success. I have Java installed through the OpenJDK 9 Ubuntu package.

Do I need to define JAVA_JAR_PATH anywhere? If so, how and with what value?

**Comment by mvdbeek** [comment]
Hi @lifepillar, thanks for reporting this. You didn't do anything wrong, this is a mistake in the datamanager that crept in with the latest update. I have opened a Pull request at https://github.com/galaxyproject/tools-iuc/issues/1242 that should fix this problem.

Just to let you know, galaxy will attempt to install all dependencies necessary to run a tool when the tool is being installed though the Tool Shed, which means that you don't need to install dependencies systemwide, like OpenJDK. Most likely these will not be used by galaxy anyway.

**Comment by lifepillar** [comment]
Thanks for the quick reply! I have monkey-patched the code and now it appears to be working (even without system-wide Java). Thanks again!
