### ISSUE TITLE
SnpEff error or content problems when genome is not natively indexed at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3969]
cc @davebx @galaxyproject/guac 

Error occurs if the dbkey is not a native genome indexed at the server. Problematic example genomes tested WBcel235.76 and WBcel235.81 (below). A genome that does not error is AgamP3.22 (assigned dbkey/database AgamP3 in user interface)

If the option to download the genome first is used for WBcel235.76 or WBcel235.81, the tool is successful but the chromosome titles are missing for the HTML output graphs "Chromosome variants plots" (see last graphic below). AgamP3.22 works either way. 

**Fix idea for http://usegalaxy.org:** Should all genomes used with SnpEff be indexed at least for: len, fasta, samtools, picard ??

**Work-arounds:** 
 - Use the tool with the option to use a downloaded snpeff database and tollerate the graph label problems.
 - Use the tool in a local/cloud Galaxy with native indexes for the target genome(s) - using Data Managers - before using this tool.

**Error WBcel235.76 with "Genome source - Named on Demand"**

```
Dataset generation errors
Dataset 43: SnpEff on data 10

Tool execution generated the following error message:
Fatal error: Exit code 1 (Error)
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/X/X/X/_galaxy_tmp -Xmx7680m -Xms256m
java.lang.RuntimeException: java.lang.RuntimeException: Cannot create directory '/cvmfs/main.galaxyproject.org/deps/_conda/envs/__snpEff@4.1/share/snpeff-4.1l-4/data/WBcel235.76'
	at ca.mcgill.mcb.pcingola.util.Download.unzip(Download.java:255)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:85)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:71)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:920)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.loadDb(SnpEff.java:320)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:938)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:921)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)
Caused by: java.lang.RuntimeException: Cannot create directory '/cvmfs/main.galaxyproject.org/deps/_conda/envs/__snpEff@4.1/share/snpeff-4.1l-4/data/WBcel235.76'
	at ca.mcgill.mcb.pcingola.util.Download.unzip(Download.java:223)
	... 9 more
java.lang.RuntimeException: Genome download failed!
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.loadDb(SnpEff.java:321)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:938)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:921)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)
mv: cannot stat `/galaxy-repl/main/files/019/706/dataset_19706438.dat.genes.txt': No such file or directory
```

**Contents of `https://snpeff-data.galaxyproject.org/databases/v4_1/` (genome is present):**

<img width="775" alt="screen shot 2017-04-24 at 1 55 39 pm" src="https://cloud.githubusercontent.com/assets/8999735/25358920/fdcc59dc-28f7-11e7-8e0a-1535ff12f7b3.png">

**Tool form settings (genome is a match for  `https://snpeff-data.galaxyproject.org/databases/v4_1/`):**

<img width="1059" alt="screen shot 2017-04-24 at 2 07 28 pm" src="https://cloud.githubusercontent.com/assets/8999735/25359015/61e710d8-28f8-11e7-9aa6-e837a2bc476d.png">
**

**Poor graph formatting for WBcel235.76 with "Genome source - Reference genome from your history", first obtained with the tool _SnpEff Download_:**
<img width="483" alt="screen shot 2017-04-24 at 2 20 17 pm" src="https://cloud.githubusercontent.com/assets/8999735/25359717/11811910-28fb-11e7-95c3-27b8e30df615.png">
**

**Comment by jennaj** [comment]
Self-ping to retest with updated tool version 4.3k.0

**Comment by jennaj** [comment]
Fails. Linked to https://github.com/galaxyproject/tools-iuc/issues/1354
