### ISSUE TITLE
Workflow run with empty collection input silently fails

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#4025]
How to reproduce:

1) Create empty collection. I did this by:
  a. Select Operations on multiple datasets
  b. Choose to create list:pair
  c. Set the filter to select some datasets but *do not* in fact select datasets. Give collection a name and Create List
2) Select to Run a workflow and choose the empty collection as an input.

The UI states that your workflow has been submitted. No output datasets become visible and consulting the handler job this error appears:

````
galaxy.workflow.run ERROR 2017-05-04 13:33:25,868 Failed to schedule Workflow[id=72,name=Variant Calling], problem occurred on WorkflowStep[index=2,type=tool].
Traceback (most recent call last):
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/run.py", line 158, in invoke
    jobs = self._invoke_step( step )
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/modules.py", line 1097, in execute
    workflow_invocation_uuid=invocation.uuid.hex
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/tools/execute.py", line 92, in execute
    raise Exception(message)
Exception: Attempting to map over an empty collection, this is not yet implemented. colleciton_info is [<galaxy.dataset_collections.matching.MatchingCollections object at 0x7fd816e86050>]
galaxy.workflow.run ERROR 2017-05-04 13:33:25,875 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/run.py", line 80, in __invoke
    outputs = invoker.invoke()
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/run.py", line 158, in invoke
    jobs = self._invoke_step( step )
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/workflow/modules.py", line 1097, in execute
    workflow_invocation_uuid=invocation.uuid.hex
  File "/net/ceph-mon2.sanbi.ac.za/datastore2/galaxy/cbtgx/galaxy/lib/galaxy/tools/execute.py", line 92, in execute
    raise Exception(message)
Exception: Attempting to map over an empty collection, this is not yet implemented. colleciton_info is [<galaxy.dataset_collections.matching.MatchingCollections object at 0x7fd816e86050>]
````
Expected behaviour:

Arguably the faulty procedure in step 1 should not be as easy to perform as it is. The bug reported here is what happens in step 2.

I think this is related to but distinct from #3554.

**Comment by jmchilton** [comment]
Both are indeed problems - thanks for the issue creation @pvanheus.
