### ISSUE TITLE
IndexError in _clean_cache method of S3ObjectStore

### ISSUE THREAD

**Issue by zzsoni** [galaxyproject/galaxy#4054]
Hi, 

The _clean_cache method in S3ObjectStore is not functional in galaxy 16.10 with python 2.7.9:

```galaxy.objectstore.s3 INFO 2017-05-09 11:15:57,703 Initiating cache cleaning: current cache size: 18.59GB; clean until smaller than: 9.00GB
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/core/python-2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/core/python-2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3.py", line 154, in __cache_monitor
    self.__clean_cache(file_list, delete_this_much)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3.py", line 178, in __clean_cache
    deleted_amount += entry[2]
IndexError: tuple index out of range
```

This simple patch solves the bug for us :
```diff --git a/lib/galaxy/objectstore/s3.py b/lib/galaxy/objectstore/s3.py
index 919d9d1..bd4a64c 100644
--- a/lib/galaxy/objectstore/s3.py
+++ b/lib/galaxy/objectstore/s3.py
@@ -169,7 +169,7 @@ class S3ObjectStore(ObjectStore):
         # exceed delete_this_much; start deleting from the front of the file list,
         # which assumes the oldest files come first on the list.
         deleted_amount = 0
-        for entry in enumerate(file_list):
+        for i,entry in enumerate(file_list):
             if deleted_amount < delete_this_much:
                 deleted_amount += entry[2]
                 os.remove(entry[1])
```

Thanks.

**Comment by dannon** [comment]
@zzsoni Thanks!  I'll take a look and test this locally.

**Comment by nsoranzo** [comment]
@zzsoni Thanks for the report! I think a better fix would be to just use:
```python
        for entry in file_list:
```

**Comment by nsoranzo** [comment]
Introduced in commit https://github.com/galaxyproject/galaxy/commit/1880f94c2649fc9501345dc6fd1345cde4cf1437 (release_15.03).

**Comment by dannon** [comment]
@nsoranzo Yep.  Looks like I was removing that enumerate and... forgot to remove the enumerate.
