### ISSUE TITLE
Repeats do not show up in workflow when using postgres

### ISSUE THREAD

**Issue by glormph** [galaxyproject/galaxy#4106]
I use a number of tools which use `<repeats>` to enable multiple dataset input. Among those are `cat`, either [in bgruening's repo](https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cat.xml) or the internal one.

Have recently upgraded to 17.05 and ran into a possible bug: when adding dataset repeats in the workflow GUI, no dataset input-points are added. This behaviour I have not seen in 16.10. I did some more testing and found that if I switch from postgres to SQLite the bug disappears.

A stacktrace from when it happens looks like this (from uwsgi.log):
```
galaxy.web.framework.decorators ERROR 2017-05-22 12:39:15,677 Uncaught exception in exposed API method:
Traceback (most recent call last):
File "lib/galaxy/web/framework/decorators.py", line 281, in decorator rval = func( self, trans, *args, **kwargs )
File "lib/galaxy/webapps/galaxy/api/workflows.py", line 367, in build_module populate_state( trans, module.get_inputs(), inputs, module_state, check=False )
File "lib/galaxy/tools/parameters/__init__.py", line 277, in populate_state populate_state( request_context, input.inputs, incoming, new_state, errors, prefix=rep_prefix + '|', context=context )
File "lib/galaxy/tools/parameters/__init__.py", line 316, in populate_state value, error = check_param( request_context, input, param_value, context ) if check else [ param_value, None ]
File "lib/galaxy/tools/parameters/__init__.py", line 132, in check_param value = param.from_json( value, trans, param_values )
File "lib/galaxy/tools/parameters/basic.py", line 1635, in from_json rval = trans.sa_session.query( trans.app.model.HistoryDatasetAssociation ).get( value )
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 831, in get return self._get_impl(ident, loading.load_on_ident)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 864, in _get_impl return fallback_fn(self, key)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident return q.one()
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2718, in one ret = list(self)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__ return self._execute_and_instances(context)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances result = conn.execute(querycontext.statement, self._params)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute return meth(self, multiparams, params)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement compiled_sql, distilled_params
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context context)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception exc_info
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context context)
File "/mnt/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute cursor.execute(statement, parameters) DataError: (psycopg2.DataError) invalid input syntax for integer: "__class__" LINE 3: WHERE history_dataset_association.id = '__class__' ^ [SQL: 'SELECT history_dataset_association.id AS history_dataset_association_id, history_dataset_association.history_id AS history_dataset_association_history_id, history_dataset_association.dataset_id AS history_dataset_association_dataset_id, history_dataset_association.create_time AS history_dataset_association_create_time, history_dataset_association.update_time AS history_dataset_association_update_time, history_dataset_association.state AS history_dataset_
```

The SELECT statement continues for a while but ends in:
```FROM history_dataset_association LEFT OUTER JOIN dataset AS dataset_1 ON dataset_1.id = history_dataset_association.dataset_id \nWHERE history_dataset_association.id = %(param_1)s'] [parameters: {'param_1': '__class__'}]```

**Comment by glormph** [comment]
More readable stacktrace is at:
https://gitter.im/galaxyproject/Lobby?at=5922dc59eec422e415d8f007

**Comment by mvdbeek** [comment]
I have seen this as well. @guerler do you have any idea what may have changed here?

**Comment by glormph** [comment]
Oh yeah, thank you very much for the super quick fix!

**Comment by mvdbeek** [comment]
Works for me too, thanks @guerler !

**Comment by martenson** [comment]
@glormph @mvdbeek thank you guys for using dev branch so we can catch more of these pre-release!
