### ISSUE TITLE
gd_prepare_population_structure 1.1.0 needs dependency correction

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4108]
**Tool**

`http://toolshed.g2.bx.psu.edu/repos/miller-lab/genome_diversity/gd_prepare_population_structure/1.1.0
`
**Error**

```
Traceback (most recent call last):
  File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/miller-lab/genome_diversity/cba0d7a63b82/genome_diversity/prepare_population_structure.py", line 9, in <module>
    import gd_composite
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/miller-lab/genome_diversity/cba0d7a63b82/genome_diversity/gd_composite.py", line 3, in <module>
    from galaxy import eggs
ImportError: No module named galaxy
```

@jmchilton This looks like the same problem as with some of the MAF tools. Is also older. Same fix?

**Comment by jennaj** [comment]
Passes testing at http://usegalaxy.org. Also tested other non-updated tools still at revision 1.1.0 (ex: Admixture). Private test history, ask for a share directly if internal and want to review in run info.
