### ISSUE TITLE
Unloadable history when merging incompatible collections

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4118]
By accident I did the following operations:
I flattened a list:pair collection and I filtered the failed datasets of the of another list:pair collection.
Then I did a merge collection between the new list:pair and list collection.
Loading the history now results in this stacktrace:
```
galaxy.web.framework.decorators ERROR 2017-05-29 09:12:22,527 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 76, in index
    return self.__index_v2( trans, history_id, **kwd )
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 638, in __index_v2
    user=trans.user, trans=trans, view=view, **serialization_params )
  File "lib/galaxy/managers/base.py", line 719, in serialize_to_view
    return self.serialize( item, all_keys, **context )
  File "lib/galaxy/managers/base.py", line 632, in serialize
    returned[ key ] = self.serializers[ key ]( item, key, **context )
  File "lib/galaxy/managers/hdcas.py", line 197, in <lambda>
    return lambda i, k, **c: self.dc_serializer.serialize( i.collection, [ k ], **c )[ k ]
  File "lib/galaxy/managers/base.py", line 637, in serialize
    returned[ key ] = self.default_serializer( item, key, **context )
  File "lib/galaxy/managers/base.py", line 661, in default_serializer
    return getattr( item, key )
  File "lib/galaxy/model/__init__.py", line 3172, in populated
    return all(e.child_collection.populated for e in self.elements)
  File "lib/galaxy/model/__init__.py", line 3172, in <genexpr>
    return all(e.child_collection.populated for e in self.elements)
AttributeError: 'NoneType' object has no attribute 'populated'
```
I guess merging collections should be reserved for collections of the same type.
I was able to load the history by chaninging `return all(e.child_collection.populated for e in self.elements)` to `return all(e.child_collection.populated for e in self.elements if e.child_collection)`.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/commit/040b5eb495a1690806d344712a8f6032a8d87baf
