### ISSUE TITLE
Error when setting up Galaxy 17.05

### ISSUE THREAD

**Issue by apark229** [galaxyproject/galaxy#4195]
Galaxy fails to start when I run the setup file.

```
Mac-MacBook-Pro:galaxy mac$ sh run.sh
Activating virtualenv at .venv
Requirement already satisfied: pip>=8.1 in ./.venv/lib/python2.7/site-packages
Requirement already satisfied: bx-python==0.7.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe==0.23 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: PyYAML==3.11 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: SQLAlchemy==1.0.15 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: mercurial==3.7.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: numpy==1.9.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pycrypto==2.6.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: Paste==2.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: PasteDeploy==1.5.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: docutils==0.12 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: wchartype==0.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: repoze.lru==0.6 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: Routes==2.4.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: WebOb==1.4.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: WebHelpers==1.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: Mako==1.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: pytz==2015.4 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: Babel==2.1.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: Beaker==1.7.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: dictobj==0.3.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: nose==1.3.7 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: Parsley==1.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: six==1.10.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: Whoosh==2.7.4 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: testfixtures==4.10.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied: galaxy_sequence_utils==1.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied: Cheetah==2.4.4 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied: Markdown==2.6.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 37))
Requirement already satisfied: bioblend==0.7.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied: boto==2.38.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied: requests==2.8.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 42))
Requirement already satisfied: requests-toolbelt==0.4.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 43))
Requirement already satisfied: kombu==3.0.30 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 46))
Requirement already satisfied: amqp==1.4.8 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 47))
Requirement already satisfied: anyjson==0.3.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied: psutil==4.1.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied: pulsar-galaxy-lib==0.7.0.dev5 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 52))
Requirement already satisfied: sqlalchemy-migrate==0.10.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 55))
Requirement already satisfied: decorator==4.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 56))
Requirement already satisfied: Tempita==0.5.3dev in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 57))
Requirement already satisfied: sqlparse==0.1.16 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 58))
Requirement already satisfied: pbr==1.8.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied: svgwrite==1.1.6 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 62))
Requirement already satisfied: pyparsing==2.1.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 63))
Requirement already satisfied: Fabric==1.10.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied: paramiko==1.15.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 67))
Requirement already satisfied: ecdsa==0.13 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 68))
Requirement already satisfied: pysam==0.8.4+gx5 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 71))
Requirement already satisfied: PasteScript in ./.venv/lib/python2.7/site-packages (from pulsar-galaxy-lib==0.7.0.dev5->-r requirements.txt (line 52))
Activating virtualenv at .venv
DEBUG:galaxy.app:python path is: /Users/mac/Documents/GitHub/galaxy/scripts, /Users/mac/Documents/GitHub/galaxy/lib, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python27.zip, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/plat-darwin, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/plat-mac, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/plat-mac/lib-scriptpackages, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/lib-tk, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/lib-old, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/lib-dynload, /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7, /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin, /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk, /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac, /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages, /Users/mac/Documents/GitHub/galaxy/.venv/lib/python2.7/site-packages
Traceback (most recent call last):
  File "/Users/mac/Documents/GitHub/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 58, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/Users/mac/Documents/GitHub/galaxy/lib/galaxy/app.py", line 58, in __init__
    self.config = config.Configuration( **kwargs )
  File "/Users/mac/Documents/GitHub/galaxy/lib/galaxy/config.py", line 615, in __init__
    self.containers_conf = parse_containers_config(self.containers_config_file)
  File "/Users/mac/Documents/GitHub/galaxy/lib/galaxy/containers/__init__.py", line 310, in parse_containers_config
    conf.update(c.get('containers', {}))
AttributeError: 'NoneType' object has no attribute 'get'
```

What can I do to fix this?
Thank you!

**Comment by martenson** [comment]
@apark229 Galaxy seems misconfigured. Check for changed/missing configuration files and let us know if the problem persists. Also https://biostar.usegalaxy.org is a better place to troubleshoot your isntance than the main repository.
