### ISSUE TITLE
`discover_datasets` error on empty tabular output file.

### ISSUE THREAD

**Issue by pkrog** [galaxyproject/galaxy#4231]
When using `discover_datasets` on tabular files:
```xml
     <data format="tabular" name="w4m_all_assays">
            <discover_datasets pattern="__designation_and_ext__" directory="w4m" visible="true"/>
        </data>
```
If one of the output file is empty, we get the following error:
```
Traceback (most recent call last):
  File "/home/pierrick/dev/galaxy/lib/galaxy/jobs/runners/local.py", line 130, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/home/pierrick/dev/galaxy/lib/galaxy/jobs/__init__.py", line 1386, in finish
    'primary': self.tool.collect_primary_datasets(out_data, tool_working_directory, input_ext, input_dbkey)
  File "/home/pierrick/dev/galaxy/lib/galaxy/tools/__init__.py", line 1613, in collect_primary_datasets
    return output_collect.collect_primary_datasets( self, output, job_working_directory, input_ext, input_dbkey=input_dbkey )
  File "/home/pierrick/dev/galaxy/lib/galaxy/tools/parameters/output_collect.py", line 325, in collect_primary_datasets
    primary_data.set_meta()
  File "/home/pierrick/dev/galaxy/lib/galaxy/model/__init__.py", line 2038, in set_meta
    return self.datatype.set_meta( self, **kwd )
  File "/home/pierrick/dev/galaxy/lib/galaxy/datatypes/tabular.py", line 978, in set_meta
    data_row = next(reader)
StopIteration
```
The error comes from the fact that no row is available for detecting column types automatically.

This issue double be related to issue #1804.

**Comment by jmchilton** [comment]
Closed by #4240.
