### ISSUE TITLE
DRMAA as real user upload jobs fail

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4300]
When drmaa is used in the real user configuration then upload jobs fail, because the ownership of some files is not changed back to the galaxy user. 

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 425, in <module>
    __main__()
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 413, in __main__
    add_file( dataset, registry, json_file, output_path )
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 325, in add_file
    shutil.move( dataset.path, output_path )
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/database/tmp/strio_url_paste_aqTRvr'
```

As a work around one configure upload to run locally:
```
<tools>
        <tool id="upload1" handler="handlers" destination="local"/>
</tools>
```

Thanks to @pvanheus for the tip with the job_conf.xml.

**Comment by bernt-matthias** [comment]
I realized that missing permissions were the problem (777 for database/tmp and missing execute permission on the galaxy root for the group owning the directory).
