### ISSUE TITLE
conda dependencies 

### ISSUE THREAD

**Issue by marijazmf** [galaxyproject/galaxy#4301]
Hi,
I have issue installing tool dependencies over conda (over Manage Tool Dependencies in Admin panel):

  ```

Traceback (most recent call last):
  File "/home/data/galaxy_tool_dep/_conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/gateways/download.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs

```

If I run stand alone command:
`/home/data/galaxy_tool_dep/_conda/bin/conda --debug create -y --name __hisat2@_uv_ hisat2`
it works fine. 
What can be the issue?
Thanks,
Marija

**Comment by bgruening** [comment]
This seems to be a general issue with SSL and your python version in your venv. Which version is this? Can you update your python2 version?

**Comment by marijazmf** [comment]
I have python 2.7.9 installed on my machine and python 2.7.9 in my .venv. I also have issues to activate conda environment: 
```
from itertools import chain
ImportError: No module named itertools
```
I checked in `usr/lib/python2.7/lib-dynload/` and realize that there is no `itertools.so` file.

Anyhow, if I run python from command line and do:
```
>>> import sys
>>> print sys.builtin_module_names
('__builtin__', '__main__', '_ast', '_bisect', '_codecs', '_collections', '_functools', '_heapq', '_io', '_locale', '_md5', '_random', '_sha', '_sha256', '_sha512', '_socket', '_sre', '_struct', '_symtable', '_warnings', '_weakref', 'array', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'datetime', 'errno', 'exceptions', 'fcntl', 'gc', 'grp', 'imp', 'itertools', 'marshal', 'math', 'operator', 'posix', 'pwd', 'select', 'signal', 'spwd', 'strop', 'sys', 'syslog', 'thread', 'time', 'unicodedata', 'xxsubtype', 'zipimport', 'zlib')
```
I can see that there is somewhere `itertools `builtin module.

**Comment by marijazmf** [comment]
I also add some code at the beginning of `compat.py`  file to check what do I have in env:
`>>> sys.executable`
`/home/data/galaxy_tool_dep/_conda/bin/python`
`>>> sys.version_info`
`sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)`
`>>> sys.builtin_module_names`
`('__builtin__', '__main__', '_ast', '_codecs', '_sre', '_symtable', '_warnings', '_weakref', 'errno', 'exceptions', 'gc', 'imp', 'marshal', 'posix', 'pwd', 'signal', 'sys', 'thread', 'xxsubtype', 'zipimport')`
`>>> sys.path`
`['/home/data/galaxy_tool_dep/_conda/bin', '/home/galaxy/galaxy/.venv/lib/python27.zip', '/home/galaxy/galaxy/.venv/lib/python2.7', '/home/galaxy/galaxy/.venv/lib/python2.7/plat-linux2', '/home/galaxy/galaxy/.venv/lib/python2.7/lib-tk', '/home/galaxy/galaxy/.venv/lib/python2.7/lib-old', '/home/galaxy/galaxy/.venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/lib-tk', '/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages', '/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/pbs', '/home/galaxy/galaxy/.venv/lib/python2.7/site-packages', '/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/pbs']`

So `/home/galaxy/galaxy/.venv/lib/python2.7/lib-dynload` is symlink to `usr/lib/python2.7/lib-dynload/`
and as I mentioned in the previous post there is no `itertools.so` in that directory. I also tried to copy it from another directory, but then `operators.so` was missing and so on ... 
Copy those modules from third part - definitely not a solution and at some point it won't work. 
But I have no idea how to solve it! Any hint?
Thanks,
Marija

**Comment by hexylena** [comment]
You can try running Galaxy inside a conda environment? maybe this will help. https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html#conda
