### ISSUE TITLE
DRMAAJobRunner as real user fails when jobs are resubmitted

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4308]
For resubmission (I guess only the automatic resubmission due to run time or memory violations) the owner ship of the job directory is not changed back to the galaxy user. Which leads to an error. 

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 366, in _handle_runner_state
    handler(self.app, self, job_state)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/state_handlers/resubmit.py", line 75, in failure
    _handle_resubmit_definitions(resubmit_definitions, app, job_runner, job_state)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/state_handlers/resubmit.py", line 116, in _handle_resubmit_definitions
    job_state.job_wrapper.clear_working_directory()
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 937, in clear_working_directory
    shutil.move( self.working_directory, arc_dir )
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/gpfs1/data/galaxy_server/galaxy-dev/jobs_dir/000/76/working/core.104128', '/gpfs1/data/galaxy_server/galaxy-dev/jobs_dir/_cleared_contents/000/76/20170712-133512/working/core.104128', "[Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/jobs_dir/000/76/working/core.104128'"), ('/gpfs1/data
/galaxy_server/galaxy-dev/jobs_dir/000/76/set_metadata_apjSIM.py', '/gpfs1/data/galaxy_server/galaxy-dev/jobs_dir/_cleared_contents/000/76/20170712-133512/set_metadata_apjSIM.py', "[Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/jobs_dir/000/76/set_metadata_apjSIM.py'")]

```

**Comment by bernt-matthias** [comment]
A similar error appears when a history is imported: 

```
Tool produced standard error failing job - [Error unpacking tar/gz archive: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/database/t
mp/tmpfvUDYp/tmpLObT_w'
]
galaxy.jobs INFO 2017-07-19 11:17:00,611 Collecting metrics for Job 85
galaxy.jobs DEBUG 2017-07-19 11:17:00,619 job 85 ended (finish() executed in (175.427 ms))
galaxy.jobs ERROR 2017-07-19 11:17:00,630 Unable to cleanup job 85
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1458, in cleanup
    galaxy.tools.imp_exp.JobImportHistoryArchiveWrapper( self.app, self.job_id ).cleanup_after_job()
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tools/imp_exp/__init__.py", line 78, in cleanup_after_job
    history_attr_str = read_file_contents( history_attr_file_name )
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tools/imp_exp/__init__.py", line 44, in read_file_contents
    fp = open( file_path, 'rb' )
IOError: [Errno 2] No such file or directory: u'/gpfs1/data/galaxy_server/galaxy-dev/database/tmp/tmpfvUDYp/history_attrs.txt'
```

**Comment by nsoranzo** [comment]
The 2 errors seem separate issues to me.

**Comment by bernt-matthias** [comment]
@nsoranzo it seems that you are right. should I open a new issue?

**Comment by nsoranzo** [comment]
Yes, please! If you also can add the Galaxy version you're using and how to reproduce, thanks!

**Comment by bernt-matthias** [comment]
I'm on the branch from PR #4275 i.e. the dev branch where the drmaa runner has the functionality to trigger job resubmission when run time/memory violations are found.

**Comment by bernt-matthias** [comment]
Might be solved by this https://github.com/galaxyproject/galaxy/pull/9001
