### ISSUE TITLE
Galaxy Pages: Display issue when embedded particular (in term of encoding ?) datasets

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy#4323]
Hi everyone, When I try to embed some datasets with french text, content is not displayed on the page.
![image](https://user-images.githubusercontent.com/7910679/28311118-ec98fb4e-6bae-11e7-8f9d-a8f0d22a1683.png).

Maybe due to ASCII / UTF8 encoding problem...

**Comment by nsoranzo** [comment]
Thanks for the report! Which Galaxy version? Any error in the logs?

**Comment by yvanlebras** [comment]
Thanks for your rapid message @nsoranzo !

Galaxy version: 17.05
Log:

```
62.193.50.99 - - [18/Jul/2017:15:32:24 +0000] "GET /dataset/get_item_content_async?id=6c528a25ae52bbbf HTTP/1.0" 200 - "http://openstack-192-168-100-44.genouest.org/u/                                        ylebras/p/test-projet-laure-lichens" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
62.193.50.99 - - [18/Jul/2017:15:32:24 +0000] "GET /dataset/get_item_content_async?id=6c528a25ae52bbbf HTTP/1.0" 500 - "http://openstack-192-168-100-44.genouest.org/u/                                        ylebras/p/test-projet-laure-lichens" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
----------------------------------------
Exception happened during processing of request from ('192.168.100.44', 49394)
Traceback (most recent call last):
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/root/galaxy/lib/galaxy/web/framework/middleware/batch.py", line 75, in __call__
    return self.application( environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    return self.app( environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 22, in __call__
    return self.app( environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "/root/galaxy/lib/galaxy/web/framework/middleware/error.py", line 164, in __call__
    exc_info)
  File "/root/galaxy/lib/galaxy/web/framework/middleware/translogger.py", line 70, in replacement_start_response
    return start_response( status, headers, exc_info )
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 173, in wsgi_start_response
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/root/galaxy/lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "/root/galaxy/lib/galaxy/web/framework/base.py", line 135, in __call__
    return self.handle_request( environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/base.py", line 220, in handle_request
    return body_renderer( trans, body, environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/base.py", line 227, in _render_body
    return body( environ, start_response )
  File "/root/galaxy/lib/galaxy/web/framework/webapp.py", line 922, in render
    template.render_context( context )
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/mako/template.py", line 468, in render_context
    **kwargs)
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/root/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/root/galaxy/database/compiled_templates/dataset/item_content.mako.py", line 37, in render_body
    __M_writer(unicode(render_item( item, item_data )))
  File "/root/galaxy/database/compiled_templates/dataset/display.mako.py", line 163, in render_render_item
    __M_writer(filters.html_escape(unicode( data_to_render )))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 151: ordinal not in range(128)
----------------------------------------
```

**Comment by yvanlebras** [comment]
So this is apparently related to an encoding error... Do you think there is a "easy way" to fix this kind of issue @nsoranzo ?

**Comment by nsoranzo** [comment]
@yvanlebras Can you share the dataset causing this? I won't be able to look at this for a couple of weeks, maybe someone else in the meantime.

**Comment by yvanlebras** [comment]
I have shared a Galaxy page with 2 datasets (one without french encoding things one with) https://usegalaxy.org/page/sharing?id=bd20ebe903dde19a 
Thank you for your help! Nice holidays (if this is the reason you won't be able to look at this ;) )
