### ISSUE TITLE
DRMAA Job runner as real user fails when importing history

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4325]
```
Tool produced standard error failing job - [Error unpacking tar/gz archive: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/database/t
mp/tmpfvUDYp/tmpLObT_w'
]
galaxy.jobs INFO 2017-07-19 11:17:00,611 Collecting metrics for Job 85
galaxy.jobs DEBUG 2017-07-19 11:17:00,619 job 85 ended (finish() executed in (175.427 ms))
galaxy.jobs ERROR 2017-07-19 11:17:00,630 Unable to cleanup job 85
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1458, in cleanup
    galaxy.tools.imp_exp.JobImportHistoryArchiveWrapper( self.app, self.job_id ).cleanup_after_job()
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tools/imp_exp/__init__.py", line 78, in cleanup_after_job
    history_attr_str = read_file_contents( history_attr_file_name )
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tools/imp_exp/__init__.py", line 44, in read_file_contents
    fp = open( file_path, 'rb' )
IOError: [Errno 2] No such file or directory: u'/gpfs1/data/galaxy_server/galaxy-dev/database/tmp/tmpfvUDYp/history_attrs.txt'
```

I'm in the dev branch corresponding to PR #4275

**Comment by nsoranzo** [comment]
Thanks! Does this happen for a particular history or for any?

**Comment by bernt-matthias** [comment]
I just tested one. Unfortunately I will not be able to reproduce the error in the next two weeks (vacations) if necessary I can do this after my return.

**Comment by bernt-matthias** [comment]
just stumbled over this one again. 

https://github.com/galaxyproject/galaxy/issues/6120

**Comment by bernt-matthias** [comment]
Might be solved by https://github.com/galaxyproject/galaxy/pull/9001
