### ISSUE TITLE
show a more user-friendly error when the webserver port is blocked

### ISSUE THREAD

**Issue by wilzbach** [galaxyproject/galaxy#434]
Currently the user sees the following:

```
galaxy.queue_worker INFO 2015-07-06 14:26:12,785 Binding and starting galaxy control worker for main
Starting server in PID 22842.
Traceback (most recent call last):
  File "./scripts/paster.py", line 37, in <module>
    serve.run()
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/serve.py", line 1049, in run
    invoke(command, command_name, options, args[1:])
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/serve.py", line 1055, in invoke
    exit_code = runner.run(args)
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/serve.py", line 220, in run
    result = self.command()
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/serve.py", line 670, in command
    serve()
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/serve.py", line 654, in serve
    server(app)
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 292, in server_wrapper
    **context.local_conf)
  File "/home/xsebi/programs/galaxy/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 97, in fix_call
    val = callable(*args, **kw)
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1342, in server_runner
    serve(wsgi_app, **kwargs)
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1291, in serve
    request_queue_size=request_queue_size)
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1134, in __init__
    request_queue_size=request_queue_size)
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1113, in __init__
    request_queue_size=request_queue_size)
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 328, in __init__
    HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 423, in __init__
    self.server_close()
  File "/home/xsebi/programs/galaxy/galaxy/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpserver.py", line 1105, in server_close
    self.thread_pool.shutdown(60)
AttributeError: 'WSGIThreadPoolServer' object has no attribute 'thread_pool'
```

How to reproduce:
- start any other server on port 8080 before starting galaxy

**Comment by souravsingh** [comment]
I would like to work on this.Where do I start?

**Comment by hexylena** [comment]
@souravsingh I think about 95% of the cases here could be eliminated with a simple check early in the run to see if the port was free, and exiting immediately if it wasn't. I'll see if I can find an easy link on how one tests if a port is free.

**Comment by hexylena** [comment]
Probably something like

``` python
def bind(host, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR,1)
    s.bind((host, port))
    s.listen(0)
    return s

try:
  q = bind(host, port)
  q.close()
except Exception, e:
  # Check that this is the correct exception
  # if it's an  [Errno 98] Address already in use, 
  # then sys.exit(1) to quit the galaxy bootup process
```

**Comment by souravsingh** [comment]
Where do we need to add the test?

**Comment by jmchilton** [comment]
For me this is what I see:

```
Traceback (most recent call last):
  File "./scripts/paster.py", line 27, in <module>
    serve.run()
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/serve.py", line 1052, in run
    invoke(command, command_name, options, args[1:])
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/serve.py", line 1058, in invoke
    exit_code = runner.run(args)
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/serve.py", line 221, in run
    result = self.command()
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/serve.py", line 664, in command
    serve()
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/serve.py", line 648, in serve
    server(app)
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 294, in server_wrapper
    **context.local_conf)
  File "/home/john/workspace/galaxy/lib/galaxy/util/pastescript/loadwsgi.py", line 99, in fix_call
    val = callable(*args, **kw)
  File "/home/john/workspace/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1342, in server_runner
    serve(wsgi_app, **kwargs)
  File "/home/john/workspace/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1291, in serve
    request_queue_size=request_queue_size)
  File "/home/john/workspace/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1134, in __init__
    request_queue_size=request_queue_size)
  File "/home/john/workspace/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1113, in __init__
    request_queue_size=request_queue_size)
  File "/home/john/workspace/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 328, in __init__
    HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

Anyone know how I can reproduce the stacktrace from this bug?

**Comment by hexylena** [comment]
@jmchilton this is the exact error I get, not sure how to tell you how to reproduce. I'll see if I can throw together a docker image...

**Comment by hexylena** [comment]
I can just:
- clone galaxy
- new terminal, `python -mSimpleHTTPServer 8080`
- `sh run.sh`

**Comment by jmchilton** [comment]
xref https://bitbucket.org/ianb/paste/issues/5/invalid-error-message-when-the-socket-is

**Comment by hexylena** [comment]
@natefoo can we get an updated paste?

**Comment by jmchilton** [comment]
I believe the error occurs, I don't need a docker image. Hmm... we could just wait for the an upstream release of paste and revise our dependency - or we could roll our own version with the fix.

**Comment by shano** [comment]
I can reproduce with the same issue as @erasche.

**Comment by shano** [comment]
Implementing the fixes referenced [here](https://bitbucket.org/ianb/paste/commits/2f65c88ba4fb) does seem to fix the error message within galaxy.

**Comment by jmchilton** [comment]
Two most realistic fixes IMO are to catch this error in our code that calls paste or upgrade paste. Upgrading paste would probably require a PR to starforge.

```
22:27 < jmchilton> Or upgrade to 2
22:27 < erasche> or ping upstream
22:27 < jmchilton> https://pypi.python.org/pypi/Paste
22:27 < mrscribe> Title: Paste 2.0.2 : Python Package Index (at pypi.python.org)
22:27 < erasche> neat
22:27 < erasche> let's do that
22:27 < erasche> assuming it doesn't require changes
22:27 < jmchilton> I guess it shouldn't - it dropped 2.5 support but so did we
22:30 < erasche> or we could monkey patch paste
22:31 < erasche> but that sounds hella ugly
22:32 < jmchilton> we also control pastescript that calls paste (it is in lib/galaxy/util 
                   somewhere), we could catch AttributeError and look for that string and 
                   print a better message
```

**Comment by shano** [comment]
Would incrementing the paste version in the requirements.txt to a latter version work?

**Comment by jmchilton** [comment]
@shano that would be the first step, we also needs the Galaxy server we fetch our dependencies from to contain the updated wheel. This is the reference to starforge I made above. https://github.com/galaxyproject/starforge/. The process is pretty new and I am not sure I have seen documentation for how to upgrade Galaxy dependencies.

**Comment by shano** [comment]
I could take a look into catching an AttributeError from paste and printing something better for the time being or is there other reasons to upgrade paste?

**Comment by shano** [comment]
I've [updated the pull request](https://github.com/galaxyproject/galaxy/pull/1320/files) to instead catch the invalid exception from paste and throw a socket error instead(as paste should be). It may not be useful but could be added in until paste is upgraded.

**Comment by natefoo** [comment]
I pinned Paste to 1.7.5.1 because trying to use 2.0.2 resulted in a traceback, but now I can't replicate it. So we can go ahead and attempt to upgrade to 2.0.2. I'm sure if there are any issues, we'll discover them.

**Comment by natefoo** [comment]
Built in galaxyproject/starforge#48 and available on wheels.galaxyproject.org. Unless someone tells me not to, I'll make a PR updating requirements.txt.

**Comment by hexylena** [comment]
Please do @natefoo
