### ISSUE TITLE
Error invoking workflow with bioblend

### ISSUE THREAD

**Issue by fbartusch** [galaxyproject/galaxy#4399]
I have a workflow that can be executed from browser without throwing an error. Invoking the workflow with bioblend, with the same input data and options fails. This happens with Galaxy 17.01 and 17.05. The failing tool is bcftools_call v.1.4.0.

The error message is:

```
galaxy.jobs.runners ERROR 2017-07-19 15:19:29,114 (122) Failure preparing job
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/galaxy/lib/galaxy/jobs/__init__.py", line 967, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/galaxy/lib/galaxy/tools/evaluation.py", line 72, in set_compute_environment
    visit_input_values( self.tool.inputs, incoming, validate_inputs )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 109, in visit_input_values
    visit_input_values( input.inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 111, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 76, in callback_helper
    new_value = callback( **args )
  File "/galaxy/lib/galaxy/tools/evaluation.py", line 71, in validate_inputs
    input.validate( value, request_context )
  File "/galaxy/lib/galaxy/tools/parameters/basic.py", line 266, in validate
    return super( TextToolParameter, self ).validate( value, trans )
  File "/galaxy/lib/galaxy/tools/parameters/basic.py", line 200, in validate
    validator.validate( value, trans )
  File "/galaxy/lib/galaxy/tools/parameters/validation.py", line 63, in validate
    if re.match( self.expression, value or '' ) is None:
  File "/galaxy/.venv/lib64/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

I asked this on [Biostars](https://biostar.usegalaxy.org/p/24061/#24189) three weeks ago, but there's no solution until now.
Galaxy is installed at /, because Galaxy and the workflow is installed in a Singularity container.

**Comment by mvdbeek** [comment]
From your biostars post it looks like some mandatory parameters have not been specified.
Have a look at http://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html?highlight=invoke#bioblend.galaxy.workflows.WorkflowClient.invoke_workflow, specifically about the params_dict.

**Comment by mvdbeek** [comment]
That said the failure message should be much better.

**Comment by fbartusch** [comment]
> From your biostars post it looks like some mandatory parameters have not been specified.

I invoke the workflow via bioblend the same way as in the broswer. I do not set any parameters (except input files) in the browser, too. Therefore I expect that the same error message would pop up when I invoke the workflow in the browser.

I imported the workflow from a .ga file that ran without an error in the browser. For every tool, the tool state is present in the .ga file. Hence I would expect that all mandatory parameters are specified and it should work with bioblend, too.

I work on archiving and reproducing Galaxy workflows, that's why I'm really interested in the difference between invoking the workflow in the browser and via bioblend.

**Comment by mvdbeek** [comment]
Can you share your workflow somewhere ?

**Comment by fbartusch** [comment]
I have the workflow and some test data (~ 10Mb) in my GitHub repo:
[Workflow + Test data](https://github.com/Fex021/galaxy2singularity/tree/master/test)
All workflow steps are installable from ToolSheds. You have to import the fastq files as fastqsanger.

**Comment by mvdbeek** [comment]
Step 7 and Step 13 contain runtime parameters that you have to include. ~~In the UI you see that those are blue~~.
FWIW, this is the API request emitted through the UI:
```json
{
  "new_history_name": null,
  "history_id": "c385e49b9fe1853c",
  "replacement_params": {},
  "parameters": {
    "0": {
      "input": {
        "values": [
          {
            "src": "hda",
            "name": "https://raw.githubusercontent.com/Fex021/galaxy2singularity/master/test/input/r1_subset.fq",
            "tags": [],
            "keep": false,
            "hid": 2,
            "id": "a40b6b1bc78914d2"
          }
        ],
        "batch": false
      }
    },
    "1": {
      "input": {
        "values": [
          {
            "src": "hda",
            "name": "https://raw.githubusercontent.com/Fex021/galaxy2singularity/master/test/input/r2_subset.fq",
            "tags": [],
            "keep": false,
            "hid": 3,
            "id": "a32a1d9364c1b029"
          }
        ],
        "batch": false
      }
    },
    "2": {
      "input": {
        "values": [
          {
            "src": "hda",
            "name": "https://raw.githubusercontent.com/Fex021/galaxy2singularity/master/test/input/ref.fa",
            "tags": [],
            "keep": false,
            "hid": 1,
            "id": "47b494785f085395"
          }
        ],
        "batch": false
      }
    },
    "3": {
      "singlePaired|sPaired": "paired",
      "singlePaired|trimming|trimming_select": "",
      "singlePaired|trim1": "false",
      "singlePaired|three_prime_clip_R1": "",
      "singlePaired|three_prime_clip_R2": "",
      "params|settingsType": "default",
      "rrbs|settingsType": "default"
    },
    "4": {
      "library|type": "paired",
      "library|unaligned_file": "false",
      "library|aligned_file": "false",
      "library|paired_options|paired_options_selector": "no",
      "reference_genome|source": "history",
      "rg|rg_selector": "do_not_set",
      "analysis_type|analysis_type_selector": "simple",
      "analysis_type|presets": "no_presets",
      "save_mapping_stats": "false"
    },
    "5": {
      "coverage_min": "1",
      "coverage_max": "1000",
      "coverage_step": "1",
      "remove_dups": "false",
      "split_output|split_output_selector": "no",
      "filter_by_flags|filter_flags": "nofilter",
      "gc_depth": "20000.0",
      "insert_size": "8000",
      "read_length": "0",
      "most_inserts": "0.99",
      "trim_quality": "0",
      "use_reference|use_ref_selector": "no"
    },
    "6": {
      "reference_source|reference_source_selector": "history",
      "genotype_likelihood_computation_type|genotype_likelihood_computation_type_selector": "perform_genotype_likelihood_computation",
      "genotype_likelihood_computation_type|output_format": "--VCF",
      "genotype_likelihood_computation_type|compressed": "false",
      "genotype_likelihood_computation_type|output_tags": null,
      "genotype_likelihood_computation_type|perform_indel_calling|perform_indel_calling_selector": "perform_indel_calling_def",
      "advanced_options|advanced_options_selector": "basic"
    },
    "7": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_restrict|samples": "",
      "sec_restrict|invert_samples": "false",
      "sec_restrict|samples_file": null,
      "sec_restrict|invert_samples_file": "false",
      "sec_consensus_variant_calling|variant_calling|method": "consensus",
      "sec_consensus_variant_calling|variant_calling|genotypes|constrain": "none",
      "sec_consensus_variant_calling|variant_calling|targets|targets_src": "__none__",
      "sec_consensus_variant_calling|pval_threshold": "0.5",
      "sec_consensus_variant_calling|prior": "0.0011",
      "sec_file_format|ploidy": null,
      "sec_file_format|ploidy_file": null,
      "sec_file_format|regions|regions_src": "__none__",
      "sec_file_format|samples": "",
      "sec_file_format|invert_samples": "false",
      "sec_file_format|samples_file": null,
      "sec_file_format|invert_samples_file": "false",
      "sec_input_output|keep_alts": "false",
      "sec_input_output|format_fields": "",
      "sec_input_output|keep_masked_ref": "false",
      "sec_input_output|skip_variants": null,
      "sec_input_output|variants_only": "false",
      "output_type": "v"
    },
    "8": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_restrict|targets|targets_src": "__none__",
      "sec_restrict|include": "",
      "sec_restrict|exclude": "%QUAL<20 || (RPB<0.1 && %QUAL<25) || (AC<2 && %QUAL<25)",
      "sec_filter|SnpGap": "3",
      "sec_filter|IndelGap": "10",
      "sec_filter|mode": null,
      "sec_filter|soft_filter": "LowQual",
      "sec_filter|select_set_GTs": null,
      "output_type": "v"
    },
    "9": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_restrict|targets|targets_src": "__none__",
      "sec_restrict|include": "Type=\"snp\"",
      "sec_restrict|exclude": "",
      "sec_filter|SnpGap": "",
      "sec_filter|IndelGap": "",
      "sec_filter|mode": null,
      "sec_filter|soft_filter": "",
      "sec_filter|select_set_GTs": null,
      "output_type": "v"
    },
    "10": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_restrict|targets|targets_src": "__none__",
      "sec_restrict|include": "Type=\"indel\"",
      "sec_restrict|exclude": "",
      "sec_filter|SnpGap": "",
      "sec_filter|IndelGap": "",
      "sec_filter|mode": null,
      "sec_filter|soft_filter": "",
      "sec_filter|select_set_GTs": null,
      "output_type": "v"
    },
    "11": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_restrict|targets|targets_src": "__none__",
      "sec_restrict|include": "AF=1",
      "sec_restrict|exclude": "",
      "sec_filter|SnpGap": "",
      "sec_filter|IndelGap": "",
      "sec_filter|mode": null,
      "sec_filter|soft_filter": "",
      "sec_filter|select_set_GTs": null,
      "output_type": "v"
    },
    "12": {
      "sec_restrict|regions|regions_src": "__none__",
      "sec_default|mode|naive": "no",
      "sec_default|mode|overlaps|allow_overlaps": "yes",
      "sec_default|mode|overlaps|rm_dups": null,
      "sec_default|mode|ligate": "false",
      "sec_default|compact_PS": "false",
      "sec_default|min_PQ": "30",
      "output_type": "b"
    },
    "13": {
      "sec_default|mask": null,
      "sec_default|iupac_codes": "false",
      "sec_default|sample": "",
      "sec_default|select_haplotype": null,
      "chain": "false"
    }
  },
  "parameters_normalized": true,
  "batch": true
}
```

**Comment by mvdbeek** [comment]
It is weird though that in the workflow editor nothing appears to be marked as a runtime value. @guerler can you take a look at this ?

**Comment by mvdbeek** [comment]
Perhaps something is wrong with the `optional="true"` handling ?

**Comment by mvdbeek** [comment]
So the parameter in question is this one https://github.com/galaxyproject/tools-iuc/blob/master/tools/bcftools/bcftools_call.xml#L191

`value` in that case is a `RuntimeValue` object, which fails in this statement `if re.match( self.expression, value or '' ) is None:`. So ... why do we get a `RuntimeValue` during a Job in the middle of a workflow execution ? Is this normal, and the regex validator should ignore `RuntimeValue` objects, or did something go wrong during the workflow building ?

**Comment by mvdbeek** [comment]
Actually this parameter is set as a `RuntimeValue` in the workflow editor, it's just collapsed and hard to find. @Fex021 if you are in the workflow editor and you click on bcftools call, then Input/output options, you see that the `Format Fields` setting is collapsed, which means that this value must be specified at runtime. So either you set this to something static, or you provide the value in `params_dict` of your bioblend call.

On the galaxy side, we should not allow to launch this workflow though, and give a clear error message if any RuntimeValues remain.

**Comment by mvdbeek** [comment]
I have opened #4428 to track how we can avoid this problem in the first place. If you still can't run your workflow via bioblend after eliminating the runtime value or providing it in the `params_dict` feel free to reopen the isssue.

**Comment by fbartusch** [comment]
First thank you for your help @mvdbeek. I eliminated the runtime value and it worked.
Now I tried to set the runtime value in my script, but it's not succesful.

This is how I specify the runtime value:
```
runtime_params = dict()
runtime_params['7'] = {'format_fields':'GP'} 
# Also tried uuid of the step and following values: '', 'PL', 'GQ', 'GP'

wf_invocation = wfc.invoke_workflow(wf_id,
  inputs=wf_input,
  params=runtime_params,
  history_id=output_history_id,
  history_name=None,
  import_inputs_to_history=None,
  replacement_params=None,
  allow_tool_state_corrections=None)
```

I get the error message I described in the first post for all values I tested.
Because I don't have much experience with .vcf files and bcftools it is possible that the problem sits in front of the screen ...
Therefore I looked at the vcf-file specification and the bcftools call manual what the format fields parameter does, but that did not help.

**Comment by fbartusch** [comment]
The problem sat in front of the screen ...
Changing the params to the correct form solved the problem:

`runtime_params['7'] = {'sec_input_output': {"format_fields": ""}}`

I didn't notice that the params for a tool are usually organized as a nested dictionary. But know it's quite obvious.
