### ISSUE TITLE
steps fail when job cleanup is turned on in workflow

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#4525]
<pre>
Traceback (most recent call last):
File "/home/galaxy/galaxy/lib/galaxy/jobs/runners/init.py", line 630, in finish_job
job_state.job_wrapper.finish( stdout, stderr, exit_code )
File "/home/galaxy/galaxy/lib/galaxy/jobs/init.py", line 1266, in finish
dataset.datatype.set_meta( dataset, overwrite=False )
File "/home/galaxy/galaxy/lib/galaxy/datatypes/binary.py", line 391, in set_meta
exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
File "/home/galaxy/lib/python2.7/subprocess.py", line 522, in call
return Popen(popenargs, *kwargs).wait()
File "/home/galaxy/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/home/galaxy/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

**Comment by mvdbeek** [comment]
The traceback points to samtools not being available (see https://github.com/galaxyproject/galaxy/blob/release_17.05/lib/galaxy/datatypes/binary.py#L391) on PATH for bam index generation during metadata setting. Can you confirm that is the problem ?

**Comment by mvdbeek** [comment]
(Job cleanup however is a little brittle -- I have definitely seen instances of datasets being marked as deleted before their last use. As a workaround i add the tag `deleteme` in the workflow editor and then I delete them manually).
