### ISSUE TITLE
UX history refresh error - history_content_type of undefined.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4708]
browser.log error:

http://galaxy:8080/static/scripts/bundled/analysis.bundled.js?v=1506521240 6:11869 Uncaught TypeError: Cannot read property 'history_content_type' of undefined

from

https://jenkins.galaxyproject.org/job/selenium/656/artifact/656-test-errors/test_upload_pair_specify_extension2017092710551506524111/browser.log.json

Test traceback:

```
Traceback (most recent call last):
  File "/var/jenkins/workspace/selenium/test/selenium_tests/framework.py", line 73, in func_wrapper
    return f(self, *args, **kwds)
  File "/var/jenkins/workspace/selenium/test/selenium_tests/test_uploads.py", line 89, in test_upload_pair_specify_extension
    self.history_panel_wait_for_hid_ok(1)
  File "/var/jenkins/workspace/selenium/test/galaxy_selenium/navigates_galaxy.py", line 165, in history_panel_wait_for_hid_ok
    self.history_panel_wait_for_hid_state(hid, 'ok', timeout=timeout, allowed_force_refreshes=allowed_force_refreshes)
  File "/var/jenkins/workspace/selenium/test/galaxy_selenium/navigates_galaxy.py", line 231, in history_panel_wait_for_hid_state
    raise self.prepend_timeout_message(e, message)
TimeoutException: Message: Failed waiting on history item 1 state to change to [ok] current state [queued]. Timeout waiting on CSS selector [#dataset-5564089c81cf7fe8.state-ok] to become visible.
```

https://jenkins.galaxyproject.org/job/selenium/656/artifact/656-test-errors/test_upload_pair_specify_extension2017092710551506524111/browser.log.json

**Comment by guerler** [comment]
Uploading pairs through the uploader interface seems to work well now. Closing this issue accordingly.
