### ISSUE TITLE
The default value for integer/float input parameters is a required field

### ISSUE THREAD

**Issue by mkempenaar** [galaxyproject/galaxy#4736]
When omitting the `value=` in an input parameter of type `integer` or `float`, Galaxy is unable to load the tool even though the documentation states this field is optional. Adding a default value results in Galaxy loading and displaying the tool.

Documentation used: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param --> `Parameter Types` -> `integer and float` -> `Attributes table`

Galaxy release: 17.05

**Comment by mvdbeek** [comment]
I can confirm this (I just took a away a default value from `filters/CreateInterval.xml`), and I think this wasn't always the case:
```
galaxy.tools.toolbox.base ERROR 2017-10-03 10:56:15,151 Error reading tool from path: filters/CreateInterval.xml
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/toolbox/base.py", line 563, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/toolbox/base.py", line 747, in load_tool
    tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 264, in create_tool
    return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 267, in _create_tool_from_source
    return create_tool_from_source(self.app, tool_source, **kwds)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 212, in create_tool_from_source
    tool = ToolClass(config_file, tool_source, app, **kwds)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/__init__.py", line 441, in __init__
    raise e
ValueError: The settings for the field named 'start' require a 'value' setting and optionally a default value which must be an integer
```

**Comment by nsoranzo** [comment]
It was unfortunately already the case, I've reported it and @guerler opened https://github.com/galaxyproject/galaxy/pull/3917 to fix it, but it was never merged due to @jmchilton concerns. Feel free to re-open the PR!

**Comment by mkempenaar** [comment]
While I have no direct opinion on the linked issue, I would however advice to alter the documentation to clearly state that the `value` field is required (and note that an empty value (`value=""`) works, too)

Furthermore, the shown output by @mvdbeek above is / would be very helpful as this makes the issue clear with an XML file that adheres to the documentation and passes the `planemo lint` command (it's not available in the current release).

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/16966 .
