### ISSUE TITLE
Tool parameters no longer populated with proper access to other values.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4809]
This breaks tools using `dynamic_options` that rely on a previously set parameter's value. e.g. the Rsync with g2 data manager tool. When the tool page is loaded, the call to populate parameters is made several times, sometimes with other values, sometimes without. When it hits a call where `other_values` is not provided, the dynamic parameter function call fails.

```
    <inputs>
        <param name="dbkey" type="genomebuild" label="dbkey to search for Reference Data" help="Specify ? to show all"/>

        <param name="data_table_names" type="select" display="checkboxes" multiple="True" optional="True" refresh_on_change="dbkey"
            label="Choose Desired Data Tables" dynamic_options="galaxy_code_get_available_data_tables( __trans__ )" />

        <param name="data_table_entries" type="select" display="checkboxes" multiple="true" optional="false" refresh_on_change="dbkey"
            label="Choose Desired Data Tables Entries" dynamic_options="galaxy_code_get_available_data_tables_entries( __trans__, dbkey, data_table_names )" />
    </inputs>
```

```
127.0.0.1 - - [16/Oct/2017:11:41:28 -0400] "GET /history/current_history_json HTTP/1.1" 200 - "http://localhost:8082/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fdata_manager_rsync_g2%2Fdata_manager_rsync_g2%2F0.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,820 name: data_table_names
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,820 other vals: {'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,820 call_other_values: {'__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,820 name: data_table_entries
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,822 other vals: {'data_table_names': None, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,823 call_other_values: {'data_table_names': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 name: data_table_names
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 other vals: {'data_table_names': None, 'data_table_entries': None, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 call_other_values: {'data_table_names': None, 'data_table_entries': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 name: data_table_names
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 other vals: {}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,885 call_other_values: {'__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 name: data_table_names
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 other vals: {'data_table_names': None, 'data_table_entries': None, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 call_other_values: {'data_table_names': None, 'data_table_entries': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 name: data_table_entries
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 other vals: {'data_table_names': None, 'data_table_entries': None, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,886 call_other_values: {'data_table_names': None, 'data_table_entries': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,887 name: data_table_entries
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,887 other vals: {}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,888 call_other_values: {'__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,888 Error determining dynamic options for parameter 'data_table_entries' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/data_manager_rsync_g2/data_manager_rsync_g2/0.0.1':
Traceback (most recent call last):
  File "/Users/blanked2/git/galaxy/lib/galaxy/tools/parameters/basic.py", line 816, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'dbkey' is not defined
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,888 name: data_table_entries
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,888 other vals: {'data_table_names': None, 'data_table_entries': None, 'dbkey': ['?', '?']}
galaxy.tools.parameters.basic DEBUG 2017-10-16 11:41:28,889 call_other_values: {'data_table_names': None, 'data_table_entries': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
127.0.0.1 - - [16/Oct/2017:11:41:28 -0400] "GET /api/tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_rsync_g2/data_manager_rsync_g2/0.0.1/build HTTP/1.1" 200 - "http://localhost:8082/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fdata_manager_rsync_g2%2Fdata_manager_rsync_g2%2F0.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```

**Comment by blankenberg** [comment]
diff for log statements (on 17.09):

```diff
diff --git a/lib/galaxy/tools/parameters/basic.py b/lib/galaxy/tools/parameters/basic.py
index f38694a9f8..f3d8e99116 100644
--- a/lib/galaxy/tools/parameters/basic.py
+++ b/lib/galaxy/tools/parameters/basic.py
@@ -810,6 +810,9 @@ class SelectToolParameter(ToolParameter):
         elif self.dynamic_options:
             call_other_values = self._get_dynamic_options_call_other_values(trans, other_values)
             try:
+                log.debug( 'name: %s', self.name )
+                log.debug('other vals: %s', other_values)
+                log.debug('call_other_values: %s', call_other_values)
                 return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
             except Exception as e:
                 log.debug("Error determining dynamic options for parameter '%s' in tool '%s':", self.name, self.tool.id, exc_info=e)
```

**Comment by guerler** [comment]
`other_values` can be empty when requesting an initial tool state through the API in which case default parameters will be used to populate the state. For dynamic parameters this can mean that they cannot be initialized (the eval-function throws an error) until non-default parameters are selected through the UI. Does the PR you opened fix the issue for you? Let me know and I can dig further in case this is something else and related to a recent change of the tool framework.

**Comment by blankenberg** [comment]
Looking into this further, we can see that `dbkey` is being populated initially as a list with 2 elements:
```
call_other_values: {'data_table_names': None, '__trans__': <galaxy.work.context.WorkRequestContext object at 0x114e0a5d0>, 'dbkey': ['?', '?']}
```
where this is actually a single-item select list. If we select a table, then unselect it, it is a single string (which is expected):
```
other vals: {'data_table_names': None, 'data_table_entries': None, 'dbkey': u'?'}
```
This is preventing the list of available entries from being populated on initial tool load. This is addressed with https://github.com/galaxyproject/galaxy/pull/4834.

**Comment by mvdbeek** [comment]
I assume #4834 has fixed this, thanks Dan!
