### ISSUE TITLE
Batch installation of tools unstable

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#5031]
These are three different issues I have seen while installing, presumably all due to multiple threads getting in each others' way while writing / moving files.

```
Exception in thread ToolConfWatcher.thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lib/galaxy/tools/toolbox/watcher.py", line 138, in check
    self.reload_callback()
  File "lib/galaxy/webapps/galaxy/config_watchers.py", line 24, in <lambda>
    self.tool_config_watcher = get_tool_conf_watcher(reload_callback=lambda: reload_toolbox(self.app), tool_cache=self.app.tool_cache)
  File "lib/galaxy/queue_worker.py", line 92, in reload_toolbox
    _get_new_toolbox(app)
  File "lib/galaxy/queue_worker.py", line 111, in _get_new_toolbox
    new_toolbox = tools.ToolBox(tool_configs, app.config.tool_path, app)
  File "lib/galaxy/tools/__init__.py", line 226, in __init__
    app=app,
  File "lib/galaxy/tools/toolbox/base.py", line 1061, in __init__
    super(BaseGalaxyToolBox, self).__init__(config_filenames, tool_root_dir, app)
  File "lib/galaxy/tools/toolbox/base.py", line 87, in __init__
    self._save_integrated_tool_panel()
  File "lib/galaxy/tools/toolbox/integrated_panel.py", line 46, in _save_integrated_tool_panel
    self._write_integrated_tool_panel_config_file()
  File "lib/galaxy/tools/toolbox/integrated_panel.py", line 106, in _write_integrated_tool_panel_config_file
    os.chmod(self._integrated_tool_panel_config, 0o644)
OSError: [Errno 2] No such file or directory: '/data/users/mvandenb/gx/config/integrated_tool_panel.xml'
```

and 
```
Error - <type 'exceptions.TypeError'>: coercing to Unicode: need string or buffer, NoneType found
URL: http://10.50.10.172/admin_toolshed/manage_repositories
File 'lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/bioinfo/guests/mvandenb/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/bioinfo/guests/mvandenb/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 136 in __call__
  return self.handle_request(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 215 in handle_request
  body = method(trans, **kwargs)
File 'lib/galaxy/web/framework/decorators.py', line 98 in decorator
  return func(self, trans, *args, **kwargs)
File 'lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py', line 648 in manage_repositories
  reinstalling=reinstalling,
File 'lib/tool_shed/galaxy_install/install_manager.py', line 852 in install_repositories
  tool_panel_section_mapping=tool_panel_section_mapping)
File 'lib/tool_shed/galaxy_install/install_manager.py', line 902 in install_tool_shed_repository
  tool_panel_section_mapping=tool_panel_section_mapping)
File 'lib/tool_shed/galaxy_install/install_manager.py', line 599 in __handle_repository_contents
  cdl.alter_config_and_load_prorietary_datatypes(datatypes_config, files_dir, override=False)
File 'lib/tool_shed/galaxy_install/datatypes/custom_datatype_manager.py', line 26 in alter_config_and_load_prorietary_datatypes
  tree, error_message = xml_util.parse_xml(datatypes_config)
File 'lib/tool_shed/util/xml_util.py', line 122 in parse_xml
  if not os.path.exists(file_name):
File '/bioinfo/guests/mvandenb/galaxy/.venv/lib/python2.7/genericpath.py', line 18 in exists
  os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

and

```
galaxy.util ERROR 2017-11-17 09:20:12,842 Error parsing file /data/users/mvandenb/gx/config/shed_tool_data_table_conf.xml
Traceback (most recent call last):
  File "lib/galaxy/util/__init__.py", line 217, in parse_xml
    root = tree.parse(fname, parser=ElementTree.XMLParser(target=DoctypeSafeCallbackTarget()))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
```

**Comment by mvdbeek** [comment]
This should be much better with #5099 and #5119.

**Comment by martenson** [comment]
Thank you Marius. 🥇
