### ISSUE TITLE
Conda errors: EnforceUnusedAdapter + fail to remove tarballs

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#5032]
Hi,
I'm working on https://github.com/galaxy-genome-annotation/docker-galaxy-genome-annotation/pull/23 and I have some errors in the log when installing weblogo3 and glimmer3 tools.

They are not completely condafied (ie there are some conda packages, but not the same versions or name), so I'm not very surprised that they fail to install properly.

But I feel like galaxy maybe could handle better the installation errors (I can be wong :)).
It's using the 17.09 docker image with conda 4.3.24

Here's the log for weblogo3 (when installing the [ghostscript dep](https://github.com/galaxyproject/tools-devteam/blob/master/tools/weblogo3/rgWebLogo3.xml#L6)):

```
galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:54:37,322 Executing command: /export/tool_deps/_conda/bin/conda list --name __ghostscript@9.10 --export > /export/galaxy-central/database/files/jobdepsrbSfB7fb7696a0ed6cba871a6383718efd5a20fd3493956ce80387341bde6ac096ea73/__ghostscript@9.10
galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:54:38,118 Executing command: /export/tool_deps/_conda/bin/conda install -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --channel r --unknown --offline --prefix /export/tool_deps/_cache/2da8ca80 --file /export/galaxy-central/database/files/jobdepsrbSfB7fb7696a0ed6cba871a6383718efd5a20fd3493956ce80387341bde6ac096ea73/__ghostscript@9.10 > /dev/null

CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)


galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:54:43,556 Executing command: /export/tool_deps/_conda/bin/conda clean --tarballs -y
Cache location: 
There are no tarballs to remove
galaxy.web.framework.decorators ERROR 2017-11-17 08:54:45,499 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy-central/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py", line 528, in install_repository_revision
    payload)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 706, in install
    install_options
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 805, in __initiate_and_install_repositories
    return self.install_repositories(tsr_ids, decoded_kwd, reinstalling=False)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 852, in install_repositories
    tool_panel_section_mapping=tool_panel_section_mapping)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 912, in install_tool_shed_repository
    [self.app.toolbox.dependency_manager.build_cache(r) for r in new_requirements]
  File "/galaxy-central/lib/galaxy/tools/deps/__init__.py", line 237, in build_cache
    [dep.build_cache(hashed_dependencies_dir) for dep in cacheable_dependencies]
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 446, in build_cache
    self.build_environment()
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 465, in build_environment
    raise DependencyException("Conda dependency seemingly installed but failed to build job environment.")
DependencyException: Conda dependency seemingly installed but failed to build job environment.

```

And for glimmer3:

```
galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:56:20,748 Executing command: /export/tool_deps/_conda/bin/conda list --name __glimmer@_uv_ --export > /export/galaxy-central/database/files/jobdepsdQtRQh7b7961f71108520d7c54df0cc9163fd1ed127c494fea7941c494ba18d4341e6c/__glimmer@_uv_
galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:56:21,344 Executing command: /export/tool_deps/_conda/bin/conda install -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --channel r --unknown --offline --prefix /export/tool_deps/_cache/4212d142 --file /export/galaxy-central/database/files/jobdepsdQtRQh7b7961f71108520d7c54df0cc9163fd1ed127c494fea7941c494ba18d4341e6c/__glimmer@_uv_ > /dev/null

CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/bioconda/linux-64/glimmer-3.02-2.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/bioconda/linux-64/glimmer-3.02-2.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/bioconda/linux-64/glimmer-3.02-2.tar.bz2\nThis command is using a remote connection in offline mode.\n',)


galaxy.tools.deps.conda_util DEBUG 2017-11-17 08:56:26,730 Executing command: /export/tool_deps/_conda/bin/conda clean --tarballs -y
Cache location: 
There are no tarballs to remove
galaxy.web.framework.decorators ERROR 2017-11-17 08:56:27,404 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy-central/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py", line 528, in install_repository_revision
    payload)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 706, in install
    install_options
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 805, in __initiate_and_install_repositories
    return self.install_repositories(tsr_ids, decoded_kwd, reinstalling=False)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 852, in install_repositories
    tool_panel_section_mapping=tool_panel_section_mapping)
  File "/galaxy-central/lib/tool_shed/galaxy_install/install_manager.py", line 912, in install_tool_shed_repository
    [self.app.toolbox.dependency_manager.build_cache(r) for r in new_requirements]
  File "/galaxy-central/lib/galaxy/tools/deps/__init__.py", line 237, in build_cache
    [dep.build_cache(hashed_dependencies_dir) for dep in cacheable_dependencies]
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 446, in build_cache
    self.build_environment()
  File "/galaxy-central/lib/galaxy/tools/deps/resolvers/conda.py", line 465, in build_environment
    raise DependencyException("Conda dependency seemingly installed but failed to build job environment.")
DependencyException: Conda dependency seemingly installed but failed to build job environment.
```

**Comment by nsoranzo** [comment]
@abretaud Unfortunately that's a known conda issue https://github.com/conda/conda/issues/5370

The only workaround is to condafy all the tool dependencies.

**Comment by abretaud** [comment]
Ah ok thanks! I hadn't found this issue
Feel free to close if you prefer
I'm condafying both in https://github.com/galaxyproject/tools-devteam/pull/495 and https://github.com/bgruening/galaxytools/pull/660

**Comment by nsoranzo** [comment]
The conda issue has been fixed in https://github.com/conda/conda/pull/6371 but only for the unreleased 4.4.x branch.
