### ISSUE TITLE
Charts Broken on dev

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5067]
Charts seems broken on dev to me - I also can get the rebuild to work.

Web Console:

```
Uncaught TypeError: Utils.get is not a function
    at app.js:12
    at Object.execCb (require.js?v=1511537801:1)
    at b.check (require.js?v=1511537801:1)
    at b.<anonymous> (require.js?v=1511537801:1)
    at require.js?v=1511537801:1
    at require.js?v=1511537801:1
    at each (require.js?v=1511537801:1)
    at b.emit (require.js?v=1511537801:1)
    at b.check (require.js?v=1511537801:1)
```

Build:

```
yarn run build-charts
yarn run v1.1.0
$ webpack -p --config ../config/plugins/visualizations/charts/webpack.config.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/john/workspace/galaxy-clean/config/plugins/visualizations/charts/webpack.config.js:3:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by dannon** [comment]
This was discussed in #4978 (briefly) and IRC afterwards.  I'll get a fix out for charts.

**Comment by dannon** [comment]
(damn that close and comment button)
