### ISSUE TITLE
Galaxy looks in incorect job directory when completing job

### ISSUE THREAD

**Issue by medcelerate** [galaxyproject/galaxy#5082]
We found this issue while running our galaxy instance. It appears to move a dataset to the files_directory but then attempts to look for the same file in the jobs directory.
```
galaxy.jobs.runners DEBUG 2017-11-24 13:25:47,989 executing external
set_meta script for job 319:
GALAXY_LIB="/mnt/ceph/home/galaxy/galaxy/lib/"; if [ "$GALAXY_LIB" !=
"None" ]; then if [ -n "$PYTHONPATH" ]; then
PYTHONPATH="$GALAXY_LIB:$PYTHONPATH"; else PYTHONPATH="$GALAXY_LIB"; fi;
export PYTHONPATH; fi;
GALAXY_VIRTUAL_ENV="/mnt/ceph/home/galaxy/galaxy/dependencies/.venv"; if
[ "$GALAXY_VIRTUAL_ENV" != "None" -a -z "$VIRTUAL_ENV" -a -f
"$GALAXY_VIRTUAL_ENV/bin/activate" ]; then .
"$GALAXY_VIRTUAL_ENV/bin/activate"; fi; python
"/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/set_metadata_qJnLkL.py"
"/mnt/lustre01/scratch/galaxy/tmphHSn9J"
"/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/working/galaxy.json"
"/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/metadata_in_HistoryDatasetAssociation_430_2dYgqz,/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/metadata_kwds_HistoryDatasetAssociation_430_XjwG5i,/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/metadata_out_HistoryDatasetAssociation_430_kBgecU,/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/metadata_results_HistoryDatasetAssociation_430_4_N_p0,/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/galaxy_dataset_430.dat,/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/metadata_override_HistoryDatasetAssociation_430_l_OTSK"
5242880
galaxy.jobs.runners DEBUG 2017-11-24 13:26:22,487 execution of external
set_meta for job 319 finished
galaxy.jobs DEBUG 2017-11-24 13:26:22,631 finish(): Moved
/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/galaxy_dataset_430.dat
to /mnt/ceph/home/galaxy/galaxy/files_directory/000/dataset_400.dat
galaxy.model.metadata DEBUG 2017-11-24 13:26:22,749 setting metadata
externally failed for HistoryDatasetAssociation 430: [Errno 2] No such
file or directory
galaxy.jobs.runners ERROR 2017-11-24 13:26:22,847 (319/179071) Job
wrapper finish method failed
Traceback (most recent call last):
   File "/var/web_services/galaxy/lib/galaxy/jobs/runners/__init__.py",
line 630, in finish_job
     job_state.job_wrapper.finish( stdout, stderr, exit_code )
   File "/var/web_services/galaxy/lib/galaxy/jobs/__init__.py", line
1266, in finish
     dataset.datatype.set_meta( dataset, overwrite=False )
   File "/var/web_services/galaxy/lib/galaxy/datatypes/binary.py", line
391, in set_meta
     exit_code = subprocess.call( args=command, stderr=open(
stderr_name, 'wb' ) )
   File "/usr/lib64/python2.7/subprocess.py", line 524, in call
     return Popen(*popenargs, **kwargs).wait()
   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
     errread, errwrite)
   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
     raise child_exception
OSError: [Errno 2] No such file or directory
galaxy.jobs ERROR 2017-11-24 13:26:22,896 fail(): Missing output file in
working directory: [Errno 2] No such file or directory:
'/mnt/ceph/home/galaxy/galaxy/scratch/jobs_directory/000/319/galaxy_dataset_430.dat'
```

**Comment by mvdbeek** [comment]
Not exactly, galaxy just didn't find the samtools binary necessary to create the bam index and collect metadata.
You can install samtools on the global path or you can install the dependencies for the external metadata tool (admin panel -> tick the box next to "Set External Metadata " and click install dependencies using conda). It should work then.

**Comment by medcelerate** [comment]
Where under the admin panel is that option located?

**Comment by mvdbeek** [comment]
In the main menu on the left in the admin panel. This has been introduced in release 17.05, if you don't see it it would probably be a good idea to update galaxy. If that's not an option you can just install samtools anywhere on galaxy's PATH.

**Comment by medcelerate** [comment]
Last I checked we are running 17.05 but I don't see that option on the sidebar. I loaded samtools as a module in our galaxy user and I am seeing if that resolves the problem.

**Comment by mvdbeek** [comment]
That's strange, it should be there. You can check your galaxy version by going to <galaxy_url>/api/version. But the module should work as well.

**Comment by medcelerate** [comment]
That Returns {"extra": {}, "version_major": "17.05"}

**Comment by nsoranzo** [comment]
I think there's part missing from @mvdbeek's explanation above: you need to click "Admin" on the top menu bar, then "Manage Tool Dependencies" on the left menu, then search for "Set External Metadata".

**Comment by medcelerate** [comment]
Ok I am still working on samtools but the other issue had to do with enabling outputs_to_working_directory option in galaxy.ini. Once disabled the files moving issue disappeared.

**Comment by natefoo** [comment]
Sounds like you have things working, please feel free to comment if you're still having trouble and we can reopen the issue.
