### ISSUE TITLE
tool secure_hash_message_digest does not seem to validate presence of mandatory input

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5084]
&version=0.0.1

when no algorithm is selected, tool executes and gives 

```
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/tools/filters/secure_hash_message_digest.py", line 48, in 
    __main__()
  File "/Users/marten/devel/git/galaxy/tools/filters/secure_hash_message_digest.py", line 24, in __main__
    for algorithm in options.algorithms:
TypeError: 'NoneType' object is not iterable
```

**Comment by mvdbeek** [comment]
Yeah, stumbled across this as well recently.
