### ISSUE TITLE
Retry metadata internally and outputs_to_working_directory don't work together.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5097]
I haven't verified this but it was reported on galaxy-dev by Evan Clark.

```
galaxy.jobs DEBUG 2017-11-24 17:53:19,057 finish(): Moved /var/web_services/galaxy/database/jobs_directory/000/320/galaxy_dataset_431.dat to /mnt/ceph/home/galaxy/galaxy/files_directory/000/dataset_401.dat
galaxy.model.metadata DEBUG 2017-11-24 17:53:19,128 setting metadata externally failed for HistoryDatasetAssociation 431: [Errno 2] No such file or directory
galaxy.jobs.runners ERROR 2017-11-24 17:53:19,319 (320/179084) Job wrapper finish method failed
Traceback (most recent call last):
  File "/var/web_services/galaxy/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/var/web_services/galaxy/lib/galaxy/jobs/__init__.py", line 1266, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/var/web_services/galaxy/lib/galaxy/datatypes/binary.py", line 391, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
galaxy.jobs ERROR 2017-11-24 17:53:19,337 fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/var/web_services/galaxy/database/jobs_directory/000/320/galaxy_dataset_431.dat'
```

**Comment by mvdbeek** [comment]
Looks more like samtools not installed

**Comment by djevo1** [comment]
Samtools was one issue, but this error only stopped when outputs_to_working_directory was set to false.

**Comment by mvdbeek** [comment]
Do you have a log from when this happens after you installed samtools but where outputs_to_working_directory is True ?

**Comment by mvdbeek** [comment]
This is fairly old now. I think this wouldn't occur with recent Galaxy anymore as we use pysam instead of samtools at the line that raises the exception. Feel free to re-open if this is still an issue.
