### ISSUE TITLE
Tool Shed, delete folder or unique file in it

### ISSUE THREAD

**Issue by ValentinChCloud** [galaxyproject/galaxy#5123]
# Test on Toolshed test and on a local toolshed
After creating a repository -> repository action -> Upload files from to repository -> tool_test.tar
It looks like that
![image](https://user-images.githubusercontent.com/26431997/33548254-ecaad314-d8e6-11e7-9369-44ac684e0dcb.png)
I would like to delete some files/folders in these repository, but it seems to be impossible to delete:
 - folder
 - or an unique file in a folder, because folder checkbox  automatically selected when I tried to delete a file
![image](https://user-images.githubusercontent.com/26431997/33548436-7354c91a-d8e7-11e7-9bd7-253d2c9e6f82.png)
If you try on the main toolshed test, it display " can"t reach the page"
But on the local toolshed if you try many times it crashs the toolshed
The problem seems to be delete a folder. There is the log _from tool_shed_webapp.log_
```
galaxy.webapps.tool_shed.controllers.repository DEBUG 2017-12-04 10:33:55,416 Error removing the following file using the mercurial API:
 database/community_files/000/repo_84/a/
galaxy.webapps.tool_shed.controllers.repository DEBUG 2017-12-04 10:33:55,416 The error was: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
galaxy.webapps.tool_shed.controllers.repository DEBUG 2017-12-04 10:33:55,416 Attempting to remove the file using a different approach.
# I add this line, I was wondering what looks like the variables
galaxy.webapps.tool_shed.controllers.repository DEBUG 2017-12-04 10:33:55,416 What is in relative_selected_file : a/b/
----------------------------------------
Exception happened during processing of request from ('192.168.100.1', 50064)
Traceback (most recent call last):
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 136, in __call__
    return self.handle_request(environ, start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 215, in handle_request
    body = method(trans, **kwargs)
  File "/home/galaxy/galaxy/lib/galaxy/webapps/tool_shed/controllers/repository.py", line 2361, in select_files_to_delete
    repo.dirstate.write()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/mercurial/dirstate.py", line 731, in write
    self._writedirstate(st)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/mercurial/dirstate.py", line 754, in _writedirstate
    st.write(parsers.pack_dirstate(self._map, self._copymap, self._pl, now))
TypeError: expected string key

```

I didn't find any issue related to that tell me if it's relevant.

**Comment by hexylena** [comment]
I guess the solution here is to fix the tarball and upload a new one?
