### ISSUE TITLE
Trackster - cannot add bams

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5167]
First off, this may be related to my instance setup (17.09), but I don't get any sensible feedback from Galaxy, see also: https://gitter.im/galaxyproject/Lobby?at=5a2a948cc65707ba2b29a559

When trying to add a BAM (with correct build key) no new track is displayed and the a 500 request is shown: 
```
/api/datasets/72448455b327e8d5?data_type=track_config&hda_ldda=ldda => "Error in dataset API at listing contents: 'NoneType' object has no attribute 'get_filters'"
```

The related server log:
```
[pid: 94346|app: 0|req: 256/517] 10.11.68.156 () {48 vars in 904 bytes} [Fri Dec  8 13:55:42 2017] GET /visualization/list_history_datasets?f-dbkey=mm9 => generated 8227 bytes in 80 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
galaxy.webapps.galaxy.api.datasets ERROR 2017-12-08 13:55:47,053 Error in dataset API at listing contents: 'NoneType' object has no attribute 'get_filters': 'NoneType' object has no attribute 'get_filters'
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/api/datasets.py", line 74, in show
    rval = self.get_new_track_config(trans, dataset)
  File "lib/galaxy/web/base/controller.py", line 1058, in get_new_track_config
    "filters": {'filters' : track_data_provider.get_filters()},
AttributeError: 'NoneType' object has no attribute 'get_filters'
10.11.68.156 - - [08/Dec/2017:13:55:46 +0200] "GET /api/datasets/01d8f0a000a1a531?data_type=track_config&hda_ldda=hda HTTP/1.1" 500 - "http://gbcs/visualization/trackster" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
```

**Comment by scholtalbers** [comment]
FYI this also happens on usegalaxy.org: "Error in dataset API at listing contents: 'NoneType' object has no attribute 'get_filters'" (on GET https://usegalaxy.org/api/datasets/bbd44e69cb8906b5ba180c4443b3a966?data_type=track_config&hda_ldda=hda)

**Comment by hrhotz** [comment]
Hi Dannon and Jelle

Any news regarding this issue? It is still broken in our local 18.05 installations.

Regards, Hans-Rudolf

**Comment by dannon** [comment]
@hrhotz Thanks for the ping here, this one fell through the cracks.  I'll take a look now.

**Comment by some2** [comment]
Hi all,

we probably have the same error in our Galaxy 18.01 (3707fb4) installation:

Visualization -> New track Browser -> Create -> Add Datasets to Visualization -> Select Data -> Add -> Nothing happens

Galaxy Log:

```
1.2.3.4 - - [20/Jun/2018:10:57:22 +0200] "GET /galaxy/visualization/list_library_datasets HTTP/1.1" 200 - "https://hostname/galaxy/visualization/trackster" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0; WIA enabled) Gecko/20100101 Firefox/52.0"
1.2.3.4 - - [20/Jun/2018:10:57:22 +0200] "GET /galaxy/visualization/list_history_datasets?f-dbkey=mm10 HTTP/1.1" 200 - "https://hostname/galaxy/visualization/trackster" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0; WIA enabled) Gecko/20100101 Firefox/52.0"
galaxy.webapps.galaxy.api.datasets ERROR 2018-06-20 10:57:26,029 Error in dataset API at listing contents: 'NoneType' object has no attribute 'get_filters': 'NoneType' object has no attribute 'get_filters'
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy_dist/lib/galaxy/webapps/galaxy/api/datasets.py", line 79, in show
    rval = self.get_new_track_config(trans, dataset)
  File "/usr/local/galaxy/galaxy_dist/lib/galaxy/web/base/controller.py", line 1049, in get_new_track_config
    "filters": {'filters' : track_data_provider.get_filters()},
AttributeError: 'NoneType' object has no attribute 'get_filters'
1.2.3.4 - - [20/Jun/2018:10:57:25 +0200] "GET /galaxy/api/datasets/958f5e363738281a?data_type=track_config&hda_ldda=hda HTTP/1.1" 500 - "https://hostname/galaxy/visualization/trackster" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0; WIA enabled) Gecko/20100101 Firefox/52.0"
```

Thanks for your help

**Comment by dannon** [comment]
@some2 Yeah, that looks like the same error to me.  I've reproduced this locally and I'm hoping to get a fix out today.

**Comment by dannon** [comment]
xref 7e2727bc0a74868198e7e457f99df3d1e39f1ddb, which removed the converter that this uses.  Trying to figure out if we actually do need that back, or if we can skip it, now.

**Comment by hrhotz** [comment]
Thanks!

**Comment by some2** [comment]
Trackster works for us again, thanks!
