### ISSUE TITLE
Cloning subworkflow steps doesn't appear to work

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5171]
Introduced in https://github.com/galaxyproject/galaxy/pull/5087.

We should fix or remove the button from this module type.

```
127.0.0.1 - - [08/Dec/2017:14:31:27 -0400] "POST /api/workflows/build_module HTTP/1.1" 200 - "http://127.0.0.1:8080/workflow/editor?id=a799d38679e985db" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
galaxy.web.framework.decorators ERROR 2017-12-08 14:33:01,410 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/john/workspace/galaxy/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 487, in build_module
    module = module_factory.from_dict(trans, payload)
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/modules.py", line 999, in from_dict
    return self.module_types[type].from_dict(trans, d, **kwargs)
  File "/Users/john/workspace/galaxy/lib/galaxy/workflow/modules.py", line 269, in from_dict
    raise Exception("Step associated subworkflow could not be found.")
Exception: Step associated subworkflow could not be found.
```

**Comment by anatskiy** [comment]
@jmchilton I'll remove the button!
