### ISSUE TITLE
Galaxy Docker images does not build `dev` anymore

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#5178]
Hi the Galaxy Docker images is running a few more advanced tests then the main Galaxy code base for example to test different schedulers or FTP upload, SFTP and so on ... currently the dev branch is not building anymore because of the recent changes.

I will use this issue to report errors which I have seen so far:

### Sample tracking removal:
```
galaxy.web.framework.base DEBUG 2017-12-09 22:37:22,690 Enabling 'home' controller, class: HomePage
Traceback (most recent call last):
  File "./scripts/paster.py", line 26, in <module>
    serve.run()
  File "/galaxy-central/lib/galaxy/util/pastescript/serve.py", line 1055, in run
    invoke(command, command_name, options, args[1:])
  File "/galaxy-central/lib/galaxy/util/pastescript/serve.py", line 1061, in invoke
    exit_code = runner.run(args)
  File "/galaxy-central/lib/galaxy/util/pastescript/serve.py", line 226, in run
    result = self.command()
  File "/galaxy-central/lib/galaxy/util/pastescript/serve.py", line 642, in command
    app = loadapp(app_spec, name=app_name, relative_to=base, global_conf=vars)
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 293, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 319, in loadobj
    return context.create()
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 761, in create
    return self.object_type.invoke(self)
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 275, in invoke
    filtered = context.next_context.create()
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 761, in create
    return self.object_type.invoke(self)
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 187, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/galaxy-central/lib/galaxy/util/pastescript/loadwsgi.py", line 90, in fix_call
    val = callable(*args, **kw)
  File "/galaxy-central/lib/galaxy/webapps/reports/buildapp.py", line 67, in app_factory
    add_ui_controllers(webapp, app)
  File "/galaxy-central/lib/galaxy/webapps/reports/buildapp.py", line 42, in add_ui_controllers
    module = __import__(module_name)
  File "/galaxy-central/lib/galaxy/webapps/reports/controllers/sample_tracking.py", line 17, in <module>
    class SpecifiedDateListGrid(grids.Grid):
  File "/galaxy-central/lib/galaxy/webapps/reports/controllers/sample_tracking.py", line 68, in SpecifiedDateListGrid
    model_class = model.Request
AttributeError: 'module' object has no attribute 'Request'
```

**Comment by jmchilton** [comment]
Looks like it might be fixed when https://github.com/galaxyproject/galaxy/pull/5182 is merged.

**Comment by dannon** [comment]
@bgruening Is it building again now?

**Comment by mmiladi** [comment]
@dannon It's building now.

**Comment by dannon** [comment]
@mmiladi Great!

**Comment by bgruening** [comment]
This is still an issue. The tests do not pass in the dev branch - need to investigate what is currently broken.

**Comment by mvdbeek** [comment]
The [current failures](https://travis-ci.org/bgruening/docker-galaxy-stable/jobs/317829620#L6259) are because we don't have samtools as a dependency on set external metadata anymore. We should change the test to something else ...

**Comment by hexylena** [comment]
I guess things are building since then :)
