### ISSUE TITLE
Subworkflow scheduling exceptions are not reported in UI

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/galaxy#5179]
In the `dev branch different scenarios can cause a subworkflow scheduling to fail. In the UI no error is reported in the history panel. Some of these failures can be checked during the workflow creation.  

1.  Missing connections within a sub-workflow:
```
galaxy.workflow.run DEBUG 2017-12-08 17:23:42,215 Workflow step 240 of invocation 3 invoked (222.785 ms)
galaxy.workflow.run ERROR 2017-12-08 17:23:42,248 Failed to schedule Workflow[id=41,name=Copy of initial_clustering_vrna (imported f
rom uploaded file)], problem occurred on WorkflowStep[index=5,type=subworkflow].
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 185, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 258, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans, self.progress, invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/modules.py", line 342, in execute
    subworkflow_invoker = progress.subworkflow_invoker(trans, step)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 441, in subworkflow_invoker
    subworkflow_progress = self.subworkflow_progress(step)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 476, in subworkflow_progress
    raise Exception("Could not find connections for all subworkflow inputs.")
Exception: Could not find connections for all subworkflow inputs.
galaxy.workflow.run ERROR 2017-12-08 17:23:42,248 Failed to execute scheduled workflow.
```

**Comment by mmiladi** [comment]
2. Optional output of a tool being marked as output of the subworkflow:
```
galaxy.workflow.run ERROR 2017-12-08 17:36:41,485 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 80, in __invoke
    outputs = invoker.invoke()
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 185, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 258, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans, self.progress, invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/modules.py", line 349, in execute
    replacement = subworkflow_progress.get_replacement_workflow_output(workflow_output)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 374, in get_replacement_workflow_output
    return step_outputs[output_name]
KeyError: u'fast_cluster_m'

Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 185, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 258, in _invoke_step
    incomplete_or_none = invocation_step.workflow_step.module.execute(self.trans, self.progress, invocation_step)
  File "/galaxy-central/lib/galaxy/workflow/modules.py", line 349, in execute
    replacement = subworkflow_progress.get_replacement_workflow_output(workflow_output)
  File "/galaxy-central/lib/galaxy/workflow/run.py", line 374, in get_replacement_workflow_output
    return step_outputs[output_name]
KeyError: u'hfile'

```

**Comment by mvdbeek** [comment]
Implemented together with conditional workflows.
