### ISSUE TITLE
set_environment tool dependency causing "Conda dependency seemingly installed but failed to build job environment"?

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5187]
For a somewhat older tool [BAMEdit](https://toolshed.g2.bx.psu.edu/repository?repository_id=57bdf6799bfc0837&changeset_revision=eb166cebbe3c) I occassionally get the error below. @mvdbeek mentions "Oh wait, this is creating a mulled envronment, presumably because of SCRIPT_PATH ... tricky" See also: https://gitter.im/galaxyproject/Lobby?at=5a2e617187680e6230f92be5

```bash
galaxy.jobs.handler INFO 2017-12-11 11:32:50,786 (2963) Job dispatched
galaxy.tools.deps DEBUG 2017-12-11 11:32:51,010 Using dependency SCRIPT_PATH version None of type tool_shed_package
galaxy.tools.deps DEBUG 2017-12-11 11:32:51,012 Using dependency samtools version 0.1.12 of type conda
galaxy.tools.deps.conda_util DEBUG 2017-12-11 11:32:51,018 Executing command: /galaxy/database/dependencies/_conda/bin/conda list --name __samtools@0.1.12 --export > /scratch/tmp/jobdepsSH92gjca2e9a9581188ac776f465e0bcce17b47
e34e226a504b46d51800d34d00615da/__samtools@0.1.12
galaxy.tools.deps.conda_util DEBUG 2017-12-11 11:32:52,299 Executing command: /galaxy/database/dependencies/_conda/bin/conda create -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --channel r --
unknown --offline --prefix /galaxy/database/jobs_directory/002/2963/conda-env --copy --file /scratch/tmp/jobdepsSH92gjca2e9a9581188ac776f465e0bcce17b47e34e226a504b46d51800d34d00615da/__samtools@0.1.12 > /dev/null

CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)


galaxy.tools.deps.conda_util DEBUG 2017-12-11 11:32:57,288 Executing command: /galaxy/database/dependencies/_conda/bin/conda clean --tarballs -y
Cache location: /galaxy/database/dependencies/_conda/pkgs
Will remove the following tarballs:

/galaxy/database/dependencies/_conda/pkgs
--------------------------------------------------------------
ncurses-5.9-10.tar.bz2                       904 KB

---------------------------------------------------
Total:                                       904 KB

Removed ncurses-5.9-10.tar.bz2
galaxy.jobs.runners ERROR 2017-12-11 11:32:58,313 (2963) Failure preparing job
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/galaxy/lib/galaxy/jobs/__init__.py", line 886, in prepare
    self.dependency_shell_commands = self.tool.build_dependency_shell_commands(job_directory=self.working_directory)
  File "/galaxy/lib/galaxy/tools/__init__.py", line 1450, in build_dependency_shell_commands
    tool_instance=self
  File "/galaxy/lib/galaxy/tools/deps/__init__.py", line 113, in dependency_shell_commands
    return [dependency.shell_commands(requirement) for requirement, dependency in requirement_to_dependency.items()]
  File "/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 470, in shell_commands
    self.build_environment()
  File "/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 465, in build_environment
    raise DependencyException("Conda dependency seemingly installed but failed to build job environment.")
DependencyException: Conda dependency seemingly installed but failed to build job environment.
galaxy.tools.error_reports DEBUG 2017-12-11 11:32:58,417 Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x9e61c90> generated response None
```

Possible relevant `galaxy.ini` entries:
```ini
conda_ensure_channels = iuc,bioconda,conda-forge,defaults,r
conda_auto_install = False
conda_auto_init = True
conda_copy_dependencies = True
use_cached_dependency_manager = False
```

**Comment by nsoranzo** [comment]
This is due to https://github.com/conda/conda/issues/5370 .

**Comment by mvdbeek** [comment]
Right, but that's just part of the problem, the other issue is that we build a mulled environment for a single dependency which seems to be properly installed. If that wouldn't have happened (and that's a galaxy bug IMO) the in-place building of a mulled environment wouldn't have failed because it wouldn't be necessary.

**Comment by nsoranzo** [comment]
The conda issue has been fixed in https://github.com/conda/conda/pull/6371 but only for the unreleased 4.4.x branch.

**Comment by NCEichner** [comment]
Hi! 
We had the same problem since we updated from version 17.05 to 17.09 about two weeks ago. The url of the CondaError as well as the line numbers in the following traceback block vary slightly from the ones posted by @scholtalbers:
`CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.11.5-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)`
Complete reinstallation of galaxy 17.09 didn't help. After installing some tools in the new environment we got the same error again and any job we tried to submit was instantly aborted.

Today I found this issue and studied also the bunch of referenced issue posts. For me it seems that the conda problem is not yet solved in our particular environment. We run galaxy 17.09 with postgresql on Debian "stretch" (amd64) .
Deletion of all the "mulled dependencies" via conda and uninstallation of the associated tools did not solve the problem for us.
Finally I 'reverted' the change from @natefoo introduced in #4701 and altered the first version of conda which will be allowed to use the "--offline" parameter again from "4.3.18" to "4.4" (according to @nsoranzo; see above)
After restarting galaxy this decent hack seems to work well so far as the errors described before are gone now and jobs will be executed again.
This may not solve the basic problem but my colleagues want to analyse their data ASAP.... ;-)
I will keep an eye on this ...

**Comment by nsoranzo** [comment]
> Finally I 'reverted' the change from @natefoo introduced in #4701 and altered the first version of conda which will be allowed to use the "--offline" parameter again from "4.3.18" to "4.4"

@NCEichner That seems a proper workaround, would you like to open a pull request to fix it?

**Comment by NCEichner** [comment]
Hi, everyone!
Finally I got PR #5233 added here for testing and discussion. Sorry for the delay but we first wanted to test this for our own before publishing nonsense.
Please read my annotations in the PR because this seems not to be a decent hotfix which is easily pulled and merged in a running galaxy instance and everything is running fine again.
If the database used by galaxy is affected e.g. after starting workflows then this will not repair anything!
