### ISSUE TITLE
uploading files with non-utf8 characters is not possible

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#5250]
Upload the following file via paste/fetch URL: 
`http://rfam.xfam.org/family/RF01960/alignment?acc=RF01960&amp;format=stockholm&amp;download=1`

yields to this error:

```
'utf8' codec can't decode byte 0xfc in position 1324: invalid start byte
```

**Comment by nsoranzo** [comment]
I doubt that it's possible/sensible to guess the encoding.

**Comment by bgruening** [comment]
Its a standard `ü` character and we should provide a way to include those text files with citations imho. I can be wrong but I guess 17.05 did not had this problem. This file is 4 month old: https://github.com/ASaiM/framework/blob/master/config/data_library.yaml

ping @bebatut to confirm that it worked with 17.05

**Comment by nsoranzo** [comment]
A standard ü character can be encoded in UTF-8. I'm on a phone, can you check which encoding this file uses?

**Comment by nsoranzo** [comment]
To answer my own question, `file` says this uses ISO-8859 encoding.

**Comment by bernt-matthias** [comment]
Similar peoblem here. A user has a tsv file exported from Excel. We tried all different export options: Text, Text unicode, Text MDSOS, Text Macintosh. 

`file` says ASCII text, with very long lines, with CRLF line terminators

I tested in the latest dev and 18.05. 

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 329, in <module>
    __main__()
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 322, in __main__
    metadata.append(add_file(dataset, registry, output_path))
  File "/gpfs1/data/galaxy_server/galaxy-dev/tools/data_source/upload.py", line 128, in add_file
    convert_spaces_to_tabs=dataset.space_to_tab,
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/upload_util.py", line 54, in handle_upload
    convert_spaces_to_tabs=convert_spaces_to_tabs,
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/sniff.py", line 778, in handle_uploaded_dataset_file_internal
    line_count, _converted_path = convert_fxn(converted_path, in_place=in_place, tmp_dir=tmp_dir, tmp_prefix=tmp_prefix)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/sniff.py", line 122, in convert_newlines
    for i, line in enumerate(io.open(fname, mode="U", encoding='utf-8')):
  File "/gpfs1/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 727: invalid continuation byte
```

File is here https://nc.ufz.de/s/XdaQXeikLm7iSKo  pass is galaxypw

**Comment by FredericBGA** [comment]
Hi,

I've tried to upload a file with this content:
```
Start
Maïs
End
```
It should be detected as a simple `txt` file. But here Galaxy creates it and set the format to `data`.
If I set the datatype to `txt` (when I import the file or with the edit attributes function), I've an error:
```
Error: Cannot count lines in dataset
formattxt
database?
uploaded txt file
ERROR:galaxy.datatypes.data:Unable to count lines in file /data/dnb03/galaxy_db/job_working_directory/011/807/11807363/outputs/galaxy_dataset_011be725-d82d-4848-bf3b-c3c7b6950c6c.dat
```

I've tried on my own Galaxy server (20_05) and https://usegalaxy.eu/

**Comment by nsoranzo** [comment]
@FredericBGA Copy-pasting your text in a file on a my workstation and uploading to https://usegalaxy.eu/ works absolutely fine. Please check that your locale encoding is UTF-8 and then the encoding of the file:
```console
$ file foo.txt
foo.txt: UTF-8 Unicode text
```

**Comment by FredericBGA** [comment]
@nsoranzo hi Nicola, the file encoding is `Test-Mais-WITH.txt: ISO-8859 text`. How I can deal with that? As this is part of a use case where our users need to upload files that come from the lab. I'm afraid that I won't be able to change encoding of the file.

**Comment by nsoranzo** [comment]
I was indeed going to suggest to use `iconv`. Alternatives are:
- "fixing" the locale of the machine in the lab that generates the files to upload
- https://github.com/galaxyproject/galaxy/pull/9452

**Comment by bernt-matthias** [comment]
Still a problem...

**Comment by wm75** [comment]
Maybe this deserves a better error message? One that explains what to do?

I don't think there's much else that can be done. As @nsoranzo said, it doesn't make much sense to guess the encoding because if you're getting it wrong, you're silently altering the uploaded data, and not trying to assume utf-8 would with high likelihood just postpone the problem and cause trouble with tool runs?

**Comment by wm75** [comment]
but, of course, if https://github.com/galaxyproject/galaxy/pull/9452 really works reliably maybe that's an option.
