### ISSUE TITLE
"Hidden" failed workflow step invocation

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5322]
(17.09) On a workflow of ~22 steps I got the below message in the logs. The resulting history looked fine, but one dataset/step was just missing. Only in the logs this can be found. 
In this case, the particular step includes a output rename, which depends on a workflow parameter. And I believe, it might be that the user started filling out the workflow parameter in the workflow run form, before the form was completely loaded (this can take several seconds!). 

```
galaxy.workflow.run ERROR 2018-01-15 16:04:05,009 Failed to schedule Workflow[id=214,name=imported: Clip_Map], problem occurred on WorkflowStep[index=22,type=tool
].
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/workflow/run.py", line 173, in invoke
    jobs = self._invoke_step(step)
  File "/galaxy/lib/galaxy/workflow/run.py", line 245, in _invoke_step
    jobs = step.module.execute(self.trans, self.progress, self.workflow_invocation, step)
  File "/galaxy/lib/galaxy/workflow/modules.py", line 800, in execute
    collections_to_match = self._find_collections_to_match(tool, progress, step)
  File "/galaxy/lib/galaxy/workflow/modules.py", line 928, in _find_collections_to_match
    visit_input_values(tool.inputs, step.state.inputs, callback)
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 112, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 77, in callback_helper
    new_value = callback(**args)
  File "/galaxy/lib/galaxy/workflow/modules.py", line 916, in callback
    data = progress.replacement_for_tool_input(step, input, prefixed_name)
  File "/galaxy/lib/galaxy/workflow/run.py", line 301, in replacement_for_tool_input
    replacement = self.replacement_for_connection(connection[0], is_data=is_data)
  File "/galaxy/lib/galaxy/workflow/run.py", line 322, in replacement_for_connection
    raise Exception(message)
Exception: Workflow evaluation problem - failed to find output_name output_full in step_outputs {'output_summary': <galaxy.model.HistoryDatasetAssociation object at 0x14050f10>, 'output_fea
ture_lengths': <galaxy.model.HistoryDatasetAssociation object at 0x11f15210>, 'output_short': <galaxy.model.HistoryDatasetAssociation object at 0x12d0ce10>}
```

**Comment by mvdbeek** [comment]
Does this tool have an output named `output_full ` and is that conditional on some other parameter ?
I am suspecting (completely out of the blue) a problem with the workflow editor that lets you connect an output that is not going to be produced. In which case the workflow editor should do better, but also the workflow validation should complain.

**Comment by scholtalbers** [comment]
The xml:
```
<tool id="NFS_transfer" name="NFS_transfer" version="1.1">
   <description>Transfer a file to a pre-defined or new location with different options to rename it</description>
   <command interpreter="python">
   NFS_transfer.py $galaxyFile 
   #if $chooseDir.destDir=="Specified path":
       "$chooseDir.user_path" 
   #else:
       "$chooseDir.destDir"
   #end if
   $fileFormat.typeFile
   "$fileFormat.prefix1"
   "$galaxyFile.dataset.name"
   "$galaxyFile.dataset.history.name"
   $galaxyFile.ext
   "$gzip"
   $__user_email__
   $ignore_file_type
   > $outFile
   </command>
   <!-- basic error handling -->
   <stdio>
       <exit_code range="1:" level="fatal" description="Tool exception" />
   </stdio>
   <inputs>
       <param type="data" name="galaxyFile" label="File to transfer"/>
        <conditional name="chooseDir">
            <param name="destDir" type="select" label="Select a pre-defined output directory (referenced by its project name)" help="If you need other projects to be listed there">
               <option value="/scratch" selected="true">Scratch</option>
               <option value="Specified path">Specify a custom path</option>
           </param>
           <when value="Specified path">
               <param name="user_path" label="Output directory location" type="text" size="100" value="e.g. /share/my_directory/">
                   <!--  see http://galaxy-dist.readthedocs.org/en/latest/_modules/galaxy/tools/parameters/validation.html
                   -->
                   <validator type="expression" message="Please specify a sensible and absolute directory path, starting from root(/)">value.startswith('/share/') or value.startswith('/scratch/')</validator>
               </param>
           </when>
       </conditional>   
       
       <conditional name="fileFormat">
           <param name="typeFile" type="select" label="Select the pattern type of file name" help="You can either choose any of these formats to name your file or can use the format you like specifying a different combination of these keywords,including 'timestamp'">
               <option value="1">prefix_datasetname_historyname.ext</option>
               <option value="2">prefix_datasetname.ext</option>
               <option value="3">datasetname_date.ext</option>
               <option value="4">datasetname_timestamp.ext</option>
           </param>
           <when value="1">
                <param name="prefix1" label="Modified selected file name pattern (optional)" type="text" size="100" value="prefix_&lt;datasetname&gt;_&lt;historyname&gt;.&lt;ext&gt;"/>
           </when>
           <when value="2">
                <param name="prefix1" label="Modified selected file name pattern (optional)" type="text" size="100" value="prefix_&lt;datasetname&gt;.&lt;ext&gt;"/>
           </when>
          <when value="3">
                <param name="prefix1" label="Modified selected file name pattern (optional)" type="text" size="100" value="&lt;datasetname&gt;_&lt;date&gt;.&lt;ext&gt;"/>
           </when>
           <when value="4">
               <param name="prefix1" label="Modified selected file name pattern (optional)" type="text" size="100" value="&lt;datasetname&gt;_&lt;timestamp&gt;.&lt;ext&gt;"/>
           </when>
       </conditional>
       <param name="gzip" type="select" label="Compress the transferred file?" help="Ignored if BAM file (already compressed). Will create a gzip file or zip archive when dealing with reports" display="radio">
         <option value="1">yes</option>
         <option value="0" selected="true">no</option>
       </param>
       <param name="ignore_file_type" type="select" multiple="True" label="Ignore file types for transfer"
         help="When transfering e.g. a report, you may not need the underlying raw data. Select those 'secondary' file types to ignore and save precious space! This has no effect on the primary dataset selected for transfer!">
         <option value="*.fastq" selected="true">*.fastq</option>
         <option value="*.bam,*.sam" selected="true">*.bam/sam</option>
         <option value="*.gz" selected="true">*.gz</option>
       </param>
   </inputs>
   <outputs>
       <data format="txt" name="outFile"/>
   </outputs>

</tool>
```

**Comment by scholtalbers** [comment]
The related workflow step:

```
"22": {
            "annotation": "", 
            "content_id": "NFS_transfer", 
            "errors": null, 
            "id": 22, 
            "input_connections": {
                "galaxyFile": {
                    "id": 13, 
                    "output_name": "output_full"
                }
            }, 
            "inputs": [
                {
                    "description": "runtime parameter for tool NFS_transfer", 
                    "name": "galaxyFile"
                }
            ], 
            "label": null, 
            "name": "NFS_transfer", 
            "outputs": [
                {
                    "name": "outFile", 
                    "type": "txt"
                }
            ], 
            "position": {
                "left": 1661, 
                "top": 1367
            }, 
            "post_job_actions": {
                "HideDatasetActionoutFile": {
                    "action_arguments": {}, 
                    "action_type": "HideDatasetAction", 
                    "output_name": "outFile"
                }
            }, 
            "tool_id": "NFS_transfer", 
            "tool_state": "{\"galaxyFile\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"chooseDir\": \"{\\\"user_path\\\": \\\"${TRANSFER_DIR}/analysis/featureCounts\\\", \\\"__current_case__\\\": 0, \\\"destDir\\\": \\\"Specified path\\\"}\", \"__page__\": null, \"__rerun_remap_job_id__\": null, \"ignore_file_type\": \"[\\\"*.fastq\\\", \\\"*.bam,*.sam\\\", \\\"*.gz\\\"]\", \"gzip\": \"\\\"0\\\"\", \"fileFormat\": \"{\\\"typeFile\\\": \\\"1\\\", \\\"prefix1\\\": \\\"<datasetname>\\\", \\\"__current_case__\\\": 0}\"}", 
            "tool_version": "1.1", 
            "type": "tool", 
            "uuid": "14ebcec0-3f5e-4565-abf8-abac82983ba2", 
            "workflow_outputs": []
        }, 

```

**Comment by scholtalbers** [comment]
This is still an issue for our users and me. If a workflow step invocation fails for some reason the user is not made aware. Especially for larger workflows its hard to figure out that history items are missing and which step is the cause of this.

This error I get in the handler log when the wrong macs2 output is chosen:
```
Exception: Workflow evaluation problem - failed to find output_name output_broadpeaks in step_outputs {'output_summits': <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f4834cf1050>, 'output_narrowpeaks': <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f4834ce4bd0>}
galaxy.workflow.run ERROR 2019-01-03 09:26:21,693 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/modules.py", line 899, in execute
    collections_to_match = self._find_collections_to_match(tool, progress, step)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/modules.py", line 1044, in _find_collections_to_match
    visit_input_values(tool.inputs, step.state.inputs, callback)
  File "/g/funcgen/galaxy-production/lib/galaxy/tools/parameters/__init__.py", line 167, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/g/funcgen/galaxy-production/lib/galaxy/tools/parameters/__init__.py", line 130, in callback_helper
    new_value = callback(**args)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/modules.py", line 1038, in callback
    data = progress.replacement_for_tool_input(step, input, prefixed_name)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/run.py", line 338, in replacement_for_tool_input
    replacement = self.replacement_for_connection(connection[0], is_data=is_data)
  File "/g/funcgen/galaxy-production/lib/galaxy/workflow/run.py", line 359, in replacement_for_connection
    raise Exception(message)
Exception: Workflow evaluation problem - failed to find output_name output_broadpeaks in step_outputs {'output_summits': <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f4834cf1050>, 'output_narrowpeaks': <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f4834ce4bd0>}
```

**Comment by hexylena** [comment]
At least 6 separate people have been annoyed by this across three issues. (Just the  ones on github thumbing up these issues)

Could anyone familiar with the tool form maybe give us some pointers on fixing this? Or at least exposing the error to the user? That error seems pretty safe to expose. @guerler?

**Comment by mvdbeek** [comment]
We're now (tip of 19.01) filtering out outputs that aren't going to be produced in the workflow editor, so while you can still run into this with old workflows it should be harder to create broken workflows now. If a workflow doesn't run now you can open them up in the workflow editor and check that all steps are properly connected. The plan is still to prevent submission of these workflows, at which point we could actually grey out conditional outputs but still offer to connect outputs that are conditional, for workflows that are intentionally designed to have these optional branches of execution.
Thanks a lot for reporting this @scholtalbers and @erasche, I hope this will cause much less pain now.
