### ISSUE TITLE
missing options from the new config_schema.yml

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5339]
With #5105 in place we now have schema that should describe all valid Galaxy config options, however over time we have added options that were not in the sample but are still being used if present = we should maybe include them and complete the schema.

- [ ] index_tool_help
- [ ] distributed_object_store_config_file
- [ ] irods_root_collection_path
- [ ] irods_default_resource

**Comment by natefoo** [comment]
The object store ones are deprecated in favor of the object store config file and may no longer work.

**Comment by scholtalbers** [comment]
I just updated to 21.05 (from 21.01) and got an `ObjectNotFound` error. Looking at the responsible code `lib/galaxy/objectstore/__init__.py:601-609` I noticed the option `object_store_check_old_style`. Only after setting this option to true would the handlers run... AFAIK there is no mention of this option in the example yml or in the docs/deprecation warnings.

**Comment by mvdbeek** [comment]
That is definitely not correct. What was the error?

**Comment by scholtalbers** [comment]
@mvdbeek After removing the option, this is what I get on starting a handler:
```
Aug  2 16:35:22 gbcs-srv03 supervisord: 2021-08-02 16:35:22,836 INFO spawned: 'handler0' with pid 128163
Aug  2 16:35:27 gbcs-srv03 supervisord: 2021-08-02 16:35:27,903 DEBG 'handler0' stderr output:
Aug  2 16:35:27 gbcs-srv03 supervisord: DEBUG:galaxy.app:python path is: /g/funcgen/galaxy-production/scripts, /g/funcgen/galaxy-production/lib, /g/funcgen/galaxy-production/.condavenv/lib/python39.zip, /g/funcgen/galaxy-production/.condavenv/lib/python3.9, /g/funcgen/galaxy-production/.condavenv/lib/python3.9/lib-dynload, /usr/local/lib/python3.9, /g/funcgen/galaxy-production/.condavenv/lib/python3.9/site-packages
Aug  2 16:35:27 gbcs-srv03 supervisord: 2021-08-02 16:35:27,905 DEBG 'handler0' stderr output:
Aug  2 16:35:27 gbcs-srv03 supervisord: DEBUG:galaxy.config:Configuration directory is /g/funcgen/galaxy-production/config
Aug  2 16:35:27 gbcs-srv03 supervisord: 2021-08-02 16:35:27,905 DEBG 'handler0' stderr output:
Aug  2 16:35:27 gbcs-srv03 supervisord: DEBUG:galaxy.config:Data directory is /g/funcgen/galaxy-production/database
Aug  2 16:35:27 gbcs-srv03 supervisord: DEBUG:galaxy.config:Managed config directory is /g/funcgen/galaxy-production/config
Aug  2 16:35:29 gbcs-srv03 supervisord: 2021-08-02 16:35:29,087 DEBG 'handler0' stderr output:
Aug  2 16:35:29 gbcs-srv03 supervisord: /g/funcgen/galaxy-production/lib/galaxy/datatypes/registry.py:99: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
Aug  2 16:35:29 gbcs-srv03 supervisord: if root_dir and config:
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,672 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: Failed to initialize Galaxy application
Aug  2 16:35:40 gbcs-srv03 supervisord: Traceback (most recent call last):
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 140, in app_loop
Aug  2 16:35:40 gbcs-srv03 supervisord: galaxy_app = load_galaxy_app(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 108, in load_galaxy_app
Aug  2 16:35:40 gbcs-srv03 supervisord: app = UniverseApplication(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/app.py", line 322, in __init__
Aug  2 16:35:40 gbcs-srv03 supervisord: self.application_stack.register_postfork_function(self.job_manager.start)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/web_stack/__init__.py", line 67, in register_postfork_function
Aug  2 16:35:40 gbcs-srv03 supervisord: f(*args, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/manager.py", line 50, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_handler.start()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 66, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_queue.start()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 202, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: self.__check_jobs_at_startup()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 275, in __check_jobs_at_startup
Aug  2 16:35:40 gbcs-srv03 supervisord: self.dispatcher.recover(job, job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 1086, in recover
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_runners[runner_name].recover(job, job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/runners/drmaa.py", line 383, in recover
Aug  2 16:35:40 gbcs-srv03 supervisord: ajs = AsynchronousJobState(files_dir=job_wrapper.working_directory, job_wrapper=job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/__init__.py", line 1201, in working_directory
Aug  2 16:35:40 gbcs-srv03 supervisord: self.__working_directory = self.app.object_store.get_filename(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 312, in get_filename
Aug  2 16:35:40 gbcs-srv03 supervisord: return self._invoke('get_filename', obj, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 291, in _invoke
Aug  2 16:35:40 gbcs-srv03 supervisord: return self.__getattribute__("_" + delegate)(obj=obj, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 609, in _get_filename
Aug  2 16:35:40 gbcs-srv03 supervisord: raise ObjectNotFound
Aug  2 16:35:40 gbcs-srv03 supervisord: galaxy.exceptions.ObjectNotFound: No such object found.
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,672 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: Traceback (most recent call last):
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 278, in <module>
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,673 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: main()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 274, in main
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,674 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: func(args, log)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 140, in app_loop
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,674 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: galaxy_app = load_galaxy_app(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/./scripts/galaxy-main", line 108, in load_galaxy_app
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,674 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: app = UniverseApplication(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/app.py", line 322, in __init__
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,675 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.application_stack.register_postfork_function(self.job_manager.start)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/web_stack/__init__.py", line 67, in register_postfork_function
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,675 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: f(*args, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/manager.py", line 50, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,675 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_handler.start()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 66, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,676 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_queue.start()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 202, in start
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,676 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.__check_jobs_at_startup()
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 275, in __check_jobs_at_startup
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,677 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.dispatcher.recover(job, job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/handler.py", line 1086, in recover
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,677 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.job_runners[runner_name].recover(job, job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/runners/drmaa.py", line 383, in recover
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,678 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: ajs = AsynchronousJobState(files_dir=job_wrapper.working_directory, job_wrapper=job_wrapper)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/jobs/__init__.py", line 1201, in working_directory
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,678 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: self.__working_directory = self.app.object_store.get_filename(
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 312, in get_filename
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,678 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: return self._invoke('get_filename', obj, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 291, in _invoke
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,679 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: return self.__getattribute__("_" + delegate)(obj=obj, **kwargs)
Aug  2 16:35:40 gbcs-srv03 supervisord: File "/g/funcgen/galaxy-production/lib/galaxy/objectstore/__init__.py", line 609, in _get_filename
Aug  2 16:35:40 gbcs-srv03 supervisord: 2021-08-02 16:35:40,680 DEBG 'handler0' stderr output:
Aug  2 16:35:40 gbcs-srv03 supervisord: raise ObjectNotFound
Aug  2 16:35:40 gbcs-srv03 supervisord: galaxy.exceptions.ObjectNotFound: No such object found.
Aug  2 16:35:41 gbcs-srv03 supervisord: 2021-08-02 16:35:41,943 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140413257664704 for <Subprocess at 140413257655576 with name handler0 in state STARTING> (stdout)>
Aug  2 16:35:41 gbcs-srv03 supervisord: 2021-08-02 16:35:41,943 DEBG fd 15 closed, stopped monitoring <POutputDispatcher at 140413239994776 for <Subprocess at 140413257655576 with name handler0 in state STARTING> (stderr)>
Aug  2 16:35:41 gbcs-srv03 supervisord: 2021-08-02 16:35:41,943 INFO exited: handler0 (exit status 1; not expected)
Aug  2 16:35:41 gbcs-srv03 supervisord: 2021-08-02 16:35:41,943 DEBG received SIGCLD indicating a child quit
```

**Comment by innovate-invent** [comment]
check_upload_content appears to be missing and undocumented
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py#L831
https://github.com/galaxyproject/galaxy/blame/dev/tools/data_source/upload.py#L111-L112

**Comment by ic4f** [comment]
@innovate-invent thank you for catching this!
