### ISSUE TITLE
distutils bug under Python3: replace with packaging?

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#5408]
While testing Galaxy under Python3, I've encountered a [distutils bug](https://bugs.python.org/issue14894) (open since 2012) which causes this traceback (only on Python3):
```
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 125, in __init__
    self._configure_toolbox()
  File "lib/galaxy/config.py", line 930, in _configure_toolbox
    self.toolbox = tools.ToolBox(tool_configs, self.config.tool_path, self)
  File "lib/galaxy/tools/__init__.py", line 232, in __init__
    app=app,
  File "lib/galaxy/tools/toolbox/base.py", line 1056, in __init__
    super(BaseGalaxyToolBox, self).__init__(config_filenames, tool_root_dir, app)
  File "lib/galaxy/tools/toolbox/base.py", line 84, in __init__
    self._load_tool_panel()
  File "lib/galaxy/tools/toolbox/base.py", line 358, in _load_tool_panel
    self.__add_tool_to_tool_panel(section_val, section, section=True)
  File "lib/galaxy/tools/toolbox/base.py", line 278, in __add_tool_to_tool_panel
    related_tool = self._lineage_in_panel(panel_dict, tool=tool)
  File "lib/galaxy/tools/toolbox/base.py", line 961, in _lineage_in_panel
    lineage_tool_versions = reversed(tool_lineage.get_versions())
  File "lib/galaxy/tools/toolbox/lineages/interface.py", line 77, in get_versions
    return [ToolLineageVersion(tool_id, tool_version) for tool_id, tool_version in zip(self.tool_ids, self.tool_versions)]
  File "lib/galaxy/tools/toolbox/lineages/interface.py", line 55, in tool_ids
    return ["%s/%s" % (tool_id, version) for version in self.tool_versions]
  File "lib/galaxy/tools/toolbox/lineages/interface.py", line 49, in tool_versions
    return sorted(self._tool_versions, key=LooseVersion)
  File "/usr/lib/python3.4/distutils/version.py", line 58, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.4/distutils/version.py", line 343, in _cmp
    if self.version < other.version:
TypeError: unorderable types: str() < int()
```
when a tool version contains a letter in the "wrong" place (e.g. in the first position).

A solution which seems to work is replace `distutils.version.LooseVersion` with `packaging.version.LegacyVersion`, which requires adding [packaging](https://pypi.python.org/pypi/packaging) to the Galaxy requirements. I'm going to do that, unless someone thinks it's not a good idea.

**Comment by mvdbeek** [comment]
I think that's a good idea, I was already thinking about using `packaging.version.Version` when we got rid of the ShedLineage!

**Comment by nsoranzo** [comment]
`packaging.version.Version` strictly implements [PEP 440](https://www.python.org/dev/peps/pep-0440/), so it would not accept the version strings used by many Galaxy tool authors. `packaging.version.LegacyVersion` seems to work fine instead.

**Comment by mvdbeek** [comment]
Right ... where possible we should probably use https://packaging.pypa.io/en/latest/version/#packaging.version.parse to construct the version.

IIRC that would allow alpha, beta and similar suffixes to sort lower than the release version.
