### ISSUE TITLE
psycopg2 wheel failure on ubuntu 18.04

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5696]
Traceback on fresh Ubuntu 18.04 w/ Postgres 10.2

```
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 83, in __init__
    self._configure_models(check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "lib/galaxy/config.py", line 1032, in _configure_models
    create_or_verify_database(db_url, config_file, self.config.database_engine_options, app=self)
  File "lib/galaxy/model/migrate/check.py", line 33, in create_or_verify_database
    new_database = not database_exists(url)
  File "/home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 461, in database_exists
    engine = sa.create_engine(url)
  File "/home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
    import psycopg2
  File "/home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /home/yoplait/galaxy/.venv/local/lib/python2.7/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

Some googling leads me to think this might be a manylinux/auditwheel bug?

**Comment by mvdbeek** [comment]
Did you try a newer psycopg2 ? Maybe an incompatible change in the shared libraries brought by postgresql ?

**Comment by mvdbeek** [comment]
Though psyocpg2 2.6.1 and postgres 10.3 seem to play nice on OSX.

**Comment by mvdbeek** [comment]
There are psycopg2 wheels for all platforms here: https://pypi.python.org/pypi/psycopg2 -- maybe we can ship those ?

**Comment by dannon** [comment]
@mvdbeek Yeah, I got it working fine with the 2.7.4 wheel from pypi.
