### ISSUE TITLE
Unable to rerun job after registering account

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5827]
1. Run a job as unregistered user  (on dev branch)
2. Register
3. Trying to rerun the prev. job, causes `API error`:

```
galaxy.web.framework.decorators ERROR 2018-04-03 12:38:58,279 [p:67164,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 224, in build_for_rerun
    job = self.__get_job(trans, id)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 264, in __get_job
    if not self.dataset_manager.is_accessible(data_assoc.dataset.dataset, trans.user):
AttributeError: 'JobController' object has no attribute 'dataset_manager'
127.0.0.1 - - [03/Apr/2018:12:38:58 +0200] "GET /api/jobs/33b43b4e7093c91f/build_for_rerun HTTP/1.1" 500 - "http://localhost:8080/?job_id=33b43b4e7093c91f&__identifer=0wu9avqh55x" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0"
```

**Comment by hexylena** [comment]
At least after login this seems to work? I did not test with registration? Please reopen if still an issue :)
