### ISSUE TITLE
Database not controlled error

### ISSUE THREAD

**Issue by ooobik** [galaxyproject/galaxy#5895]
Hi,
I've been moving our galaxy 17.09 release to 18.01  and in the last few days it seems you have moved the manage_db.sh script. First and foremost I am getting thing error
```
galaxy.queue_worker INFO 2018-04-17 11:20:13,561 [p:23544,w:0,m:0] [MainThread] Initializing main Galaxy Queue Worker on sqlalchemy+postgresql:///galaxy?host=/var/run/postgresql
galaxy.model.migrate.check INFO 2018-04-17 11:20:15,633 [p:23544,w:0,m:0] [MainThread] At database version 140
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 78, in __init__
    self._configure_models(check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "lib/galaxy/config.py", line 1058, in _configure_models
    verify_tools(self, install_db_url, config_file, install_database_options)
  File "lib/tool_shed/galaxy_install/migrate/check.py", line 65, in verify_tools
    raise Exception("Error attempting to update the value of migrate_tools.version: %s" % output)
Exception: Error attempting to update the value of migrate_tools.version: Activating virtualenv at /gpfs/rocket/nfs/galaxy/venv
Traceback (most recent call last):
  File "./scripts/manage_db.py", line 24, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 20, in invoke_migrate_main
    main(repository=repo, url=db_url)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<string>", line 2, in _migrate
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 342, in _migrate
    schema = ControlledSchema(engine, repository)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/migrate/versioning/schema.py", line 45, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 440, in __new__
    metadata._remove_table(name, schema)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 435, in __new__
    table._init(name, metadata, *args, **kw)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 510, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _autoload
    self, include_columns, exclude_columns
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1972, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1477, in run_callable
    return callable_(self, *args, **kwargs)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 364, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 571, in reflecttable
    raise exc.NoSuchTableError(table.name)
migrate.exceptions.DatabaseNotControlledError: migrate_tools
```

I have a feeling this is because of lib/tool_shed/galaxy_install/migrate/check.py trying to invoke manage_db.sh not manage_db.py.
Currently i have no good way to debug this, but first launch from run.sh works perfect, after a restart it seems to me that it tries to check the DB, but the script has changed.

EDIT1: I have just confirmed this happening on fresh installations. I have an ansible-playbook setup to install dependencies, setup the psql server and setup folders. After that i run run.sh manually to init the venv. Now atfirst galaxy launches with an error in uwsgi.log, but still serves. After a restart, galaxy no longer boots, log shows the error above. 

This is the psql error I get on first launch. I made a new VM, set my ansible script working on it and an run.sh.
This is release_18.01 from git at the time I write this.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/mixins.py", line 177, in run
    for _ in self.consume(limit=None):  # pragma: no cover
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/mixins.py", line 193, in consume
    with self.consumer_context(**kwargs) as (conn, channel, consumers):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/mixins.py", line 186, in consumer_context
    with self.Consumer() as (connection, channel, consumers):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/mixins.py", line 235, in Consumer
    with self._consume_from(*self.get_consumers(cls, channel)) as c:
  File "lib/galaxy/queue_worker.py", line 236, in get_consumers
    callbacks=[self.process_task])]
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/messaging.py", line 364, in __init__
    self.revive(self.channel)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/messaging.py", line 376, in revive
    self.declare()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/messaging.py", line 386, in declare
    queue.declare()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare
    self.queue_declare(nowait, passive=False)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare
    nowait=nowait)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 80, in _new_queue
    self._get_or_create(queue)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 68, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 63, in session
    _, Session = self._open()
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 56, in _open
    metadata.create_all(engine)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3748, in create_all
    tables=tables)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 730, in visit_metadata
    _is_metadata_operation=True)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 764, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/gpfs/rocket/nfs/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "kombu_queue" already exists
 [SQL: '\nCREATE TABLE kombu_queue (\n\tid INTEGER NOT NULL, \n\tname VARCHAR(200), \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n)\n\n']
```

**Comment by ooobik** [comment]
Closing issue as i found a solution from [here](https://botbot.me/freenode/galaxyproject/2018-03-23/?tz=America%2FLos_Angeles&page=1).
