### ISSUE TITLE
Converter problem in dev

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5970]
```
galaxy.datatypes.registry DEBUG 2018-04-24 15:24:27,801 Loaded converter: CONVERTER_fasta_to_tabular
galaxy.datatypes.registry DEBUG 2018-04-24 15:24:27,805 Loaded converter: CONVERTER_gz_to_uncompressed
galaxy.datatypes.registry ERROR 2018-04-24 15:24:27,806 Error loading converter (./lib/galaxy/datatypes/converters)
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/datatypes/registry.py", line 596, in load_datatype_converters
    converter = toolbox.load_tool(config_path, use_cached=use_cached)
  File "/galaxy/lib/galaxy/tools/toolbox/base.py", line 751, in load_tool
    tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
  File "/galaxy/lib/galaxy/tools/__init__.py", line 266, in create_tool
    raise e
IOError: [Errno 2] No such file or directory: './lib/galaxy/datatypes/converters/bz2_to_uncompressed.xml'
```

I wonder if I forgot to git add a file...

**Comment by bernt-matthias** [comment]
Same here.

**Comment by jacmarjorie** [comment]
Was this fixed? I cloned a few days ago and was also seeing this bug.

**Comment by bernt-matthias** [comment]
I guess no -- But I do not know for sure, since I did not update my dev branch in the last 2 weeks.

**Comment by jmchilton** [comment]
Completely forgot I made an issue for this. Fix was just merged with https://github.com/galaxyproject/galaxy/pull/6101 into release_18.05, once that branch gets merged into dev this should be fixed. Sorry all.
