### ISSUE TITLE
update_dataset_size.py error in release_17.09

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#5974]
I got https://raw.githubusercontent.com/galaxyproject/galaxy/release_17.09/scripts/cleanup_datasets/update_dataset_size.py for my local galaxy, but it seems someting wong when I running it.
```
(.venv)galaxy@ecs-steven 11:04:30 /data/steven/galaxy 
$ python scripts/cleanup_datasets/update_dataset_size.py config/galaxy.ini
DEBUG:galaxy.app:python path is: /data/steven/galaxy/scripts/cleanup_datasets, /data/steven/galaxy/lib, /data/steven/galaxy/.venv/lib/python27.zip, /data/steven/galaxy/.venv/lib/python2.7, /data/steven/galaxy/.venv/lib/python2.7/plat-linux2, /data/steven/galaxy/.venv/lib/python2.7/lib-tk, /data/steven/galaxy/.venv/lib/python2.7/lib-old, /data/steven/galaxy/.venv/lib/python2.7/lib-dynload, /usr/local/software/python-2.7.14/lib/python2.7, /usr/local/software/python-2.7.14/lib/python2.7/plat-linux2, /usr/local/software/python-2.7.14/lib/python2.7/lib-tk, /data/steven/galaxy/.venv/lib/python2.7/site-packages
DEBUG:galaxy.containers:config file './config/containers_conf.yml' does not exist, running with default config
INFO:galaxy.config:Logging at '10' level to 'stdout'
galaxy.queue_worker INFO 2018-04-25 11:04:40,456 Initializing main Galaxy Queue Worker on sqlalchemy+postgresql://galaxy:********@localhost/galaxydb
tool_shed.tool_shed_registry DEBUG 2018-04-25 11:04:40,516 Loading references to tool sheds from ./config/tool_sheds_conf.xml.sample
tool_shed.tool_shed_registry DEBUG 2018-04-25 11:04:40,516 Loaded reference to tool shed: Galaxy Main Tool Shed
Traceback (most recent call last):
  File "scripts/cleanup_datasets/update_dataset_size.py", line 54, in <module>
    main()
  File "scripts/cleanup_datasets/update_dataset_size.py", line 38, in main
    app = galaxy.app.UniverseApplication(global_conf=ini_file, **configuration)
  File "/data/steven/galaxy/lib/galaxy/app.py", line 72, in __init__
    config_file = kwargs.get('global_conf', {}).get('__file__', None)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by bernt-matthias** [comment]
wonder if the problem is caused by the galaxy.ini file parameter. Do you have an ini file? Or switched to yml already? 

For other scripts the parameter was dropped recently: https://github.com/galaxyproject/galaxy/pull/5956. Maybe this can be done here as well.

**Comment by hexylena** [comment]
This script was not updated to the new framework. It will not process a yaml file.

**Comment by bernt-matthias** [comment]
@erasche do you think that it should be ported? or deprecated in case of a better alternative?

**Comment by hexylena** [comment]
It seems it was already deprecated:
https://github.com/galaxyproject/galaxy/blob/dev/scripts/cleanup_datasets/update_dataset_size.py#L6
