### ISSUE TITLE
rulebuilder - autodetect of compressed files fails 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6108]
with 'The uploaded binary file contains inappropriate content'.

The only difference here is the datatype, green ones have fasta.gz selected, red had autodetect

![screenshot 2018-05-09 15 24 44](https://user-images.githubusercontent.com/1814954/39835127-2a7b1bfa-539d-11e8-809c-fd2b50212a28.png)

full exception:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 325, in <module>
    main()
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 42, in main
    galaxy_json = _request_to_galaxy_json(upload_config, request)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 52, in _request_to_galaxy_json
    fetched_target = _fetch_target(upload_config, target)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 183, in _fetch_target
    elements = elements_tree_map(_resolve_src, items)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 211, in elements_tree_map
    new_items.append(f(item))
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 128, in _resolve_src
    data_type, ext, path, name, is_binary, requested_ext, check_content, registry
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/datatypes/upload_util.py", line 26, in handle_unsniffable_binary_check
    raise UploadProblemException('The uploaded binary file contains inappropriate content')
galaxy.datatypes.upload_util.UploadProblemException
```

**Comment by martenson** [comment]
Together with bug in implicit conversion (xref https://github.com/galaxyproject/galaxy/issues/6088) this makes many novel workflows on Main unachievable.

**Comment by martenson** [comment]
closed by https://github.com/galaxyproject/galaxy/pull/6141
