### ISSUE TITLE
Toolshed manage email alerts undefined object

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6131]
```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 74, in decorator
    return func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/tool_shed/controllers/repository.py", line 1839, in manage_email_alerts
    status=status)
  File "lib/galaxy/web/framework/webapp.py", line 919, in fill_template
    return self.fill_template_mako(filename, **kwargs)
  File "lib/galaxy/web/framework/webapp.py", line 933, in fill_template_mako
    return template.render(**data)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/base.mako.py", line 69, in render_body
    __M_writer(unicode(next.body()))
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/webapps/tool_shed/user/manage_email_alerts.mako.py", line 56, in render_body
    __M_writer(unicode(render_checkbox(new_repo_alert_check_box)))
TypeError: 'Undefined' object is not callable
[pid: 279745|app: 0|req: 24/58] 127.0.0.1 () {42 vars in 907 bytes} [Mon May 14 12:13:30 2018] GET /repository/manage_email_alerts?cntrller=user => generated 0 bytes in 8 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
```

(saw this on my `gdpr` branch, but think it applies to 18.05 where I branched from.)

**Comment by nsoranzo** [comment]
Can you reproduce it after deleting the compiled makos ( `rm -rf database/compiled_templates/` )? Sometimes these issues arise when changing branch without cleaning them up.

**Comment by hexylena** [comment]
Yes, I can.

**Comment by hexylena** [comment]
(sorry, busy, don't want to file duplicate issues since I haven't confirmed them yet against dev/18.X)

```
re 2)
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 727, in create
    show_user_prepopulate_form = is_admin and trans.app.config.show_user_prepopulate_form
AttributeError: 'Configuration' object has no attribute 'show_user_prepopulate_form'
[pid: 318741|app: 0|req: 47/78] 127.0.0.1 () {42 vars in 863 bytes} [Mon May 14 13:38:20 2018] GET /user/create?cntrller=admin => generated 0 bytes in 5 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by hexylena** [comment]
Same disclaimer as above. Here I used the (undocumented) `allow_user_deletion = True`

```
[pid: 352177|app: 0|req: 19/19] 127.0.0.1 () {42 vars in 829 bytes} [Mon May 14 13:57:27 2018] GET /admin/users => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 98, in decorator
    return func(self, trans, *args, **kwargs)
  File "lib/tool_shed/util/admin_util.py", line 844, in users
    return self.user_list_grid(trans, **kwd)
  File "lib/galaxy/webapps/reports/framework/grids.py", line 292, in __call__
    kwargs=kwargs)
  File "lib/galaxy/web/framework/webapp.py", line 919, in fill_template
    return self.fill_template_mako(filename, **kwargs)
  File "lib/galaxy/web/framework/webapp.py", line 933, in fill_template_mako
    return template.render(**data)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/hxr/arbeit/galaxy/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/base.mako.py", line 69, in render_body
    __M_writer(unicode(next.body()))
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/legacy/grid_base.mako.py", line 79, in render_body
    __M_writer(unicode(self.load()))
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/legacy/grid_base.mako.py", line 107, in render_load
    __M_writer(unicode( h.dumps( self.get_grid_config( embedded=embedded, insert=insert ) ) ))
  File "/home/hxr/arbeit/galaxy/database/compiled_templates/community/legacy/grid_base.mako.py", line 226, in render_get_grid_config
    'allow_multiple'        : operation.allow_multiple,
AttributeError: 'NoneType' object has no attribute 'allow_multiple'
[pid: 352177|app: 0|req: 20/20] 127.0.0.1 () {42 vars in 829 bytes} [Mon May 14 13:57:27 2018] GET /admin/users => generated 0 bytes in 13 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 3)
```

**Comment by hexylena** [comment]
Tested both of the above, they've been issues since 18.01 up to dev. Unable to create or delete users. (User creation I don't care about, just noticed. Non-functional user deletion is an issue.)

**Comment by hexylena** [comment]
Fixed deletion of users in GDPR branch. Could be extricated + backported.

**Comment by hexylena** [comment]
https://github.com/galaxyproject/galaxy/pull/6069/commits/15ceedfbc059494da18e077336f0264e65e5a7cb is the relevant commit

**Comment by hexylena** [comment]
I think I fixed this?
