### ISSUE TITLE
Relabel List Identifiers from contents of a file on collection fails without telling user why

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#6156]
Get a job submission error message, which is good. But it doesn't give any feed back to the user on why, so that they might fix it.

![image](https://user-images.githubusercontent.com/1231190/40140528-2fbfef3a-5921-11e8-89c4-6816f9f5d128.png)

From log, some reasons may be:

```
galaxy.tools DEBUG 2018-05-16 15:48:42,977 [p:1970348,w:4,m:0] [uWSGIWorker4Core2] Validated and populated state for tool request (3112.794 ms)
galaxy.tools ERROR 2018-05-16 15:48:49,352 [p:1970348,w:4,m:0] [uWSGIWorker4Core2] Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1416, in handle_single_execution
    completed_job=completed_job,
  File "lib/galaxy/tools/__init__.py", line 1497, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/model_operations.py", line 57, in execute
    self._produce_outputs(trans, tool, out_data, output_collections, incoming=incoming, history=history, tags=preserved_tags)
  File "lib/galaxy/tools/actions/model_operations.py", line 71, in _produce_outputs
    tool.produce_outputs(trans, out_data, output_collections, incoming, history=history, tags=tags)
  File "lib/galaxy/tools/__init__.py", line 2641, in produce_outputs
    new_labels_dict = {source: new_label for source, new_label in source_new_label}
  File "lib/galaxy/tools/__init__.py", line 2641, in <dictcomp>
    new_labels_dict = {source: new_label for source, new_label in source_new_label}
ValueError: too many values to unpack
galaxy.tools.execute WARNING 2018-05-16 15:48:49,359 [p:1970348,w:4,m:0] [uWSGIWorker4Core2] There was a failure executing a job for tool [__RELABEL_FROM_FILE__] - Error executing tool: too many values to unpack
galaxy.tools.execute DEBUG 2018-05-16 15:48:49,359 [p:1970348,w:4,m:0] [uWSGIWorker4Core2] Executed 1 job(s) for tool __RELABEL_FROM_FILE__ request: (6382.382 ms)
```
if I give it a 3 column file when it expects only 2. Maybe it could use just the first 2?

or

```
galaxy.tools ERROR 2018-05-16 15:56:13,615 [p:1970348,w:4,m:0] [uWSGIWorker4Core0] Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1416, in handle_single_execution
    completed_job=completed_job,
  File "lib/galaxy/tools/__init__.py", line 1497, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/model_operations.py", line 57, in execute
    self._produce_outputs(trans, tool, out_data, output_collections, incoming=incoming, history=history, tags=preserved_tags)
  File "lib/galaxy/tools/actions/model_operations.py", line 71, in _produce_outputs
    tool.produce_outputs(trans, out_data, output_collections, incoming, history=history, tags=tags)
  File "lib/galaxy/tools/__init__.py", line 2657, in produce_outputs
    raise Exception("Invalid new colleciton identifier [%s]" % key)
Exception: Invalid new colleciton identifier [Stool314:511]
galaxy.tools.execute WARNING 2018-05-16 15:56:13,626 [p:1970348,w:4,m:0] [uWSGIWorker4Core0] There was a failure executing a job for tool [__RELABEL_FROM_FILE__] - Error executing tool: Invalid new colleciton identifier [Stool314:511]
galaxy.tools.execute DEBUG 2018-05-16 15:56:13,633 [p:1970348,w:4,m:0] [uWSGIWorker4Core0] Executed 1 job(s) for tool __RELABEL_FROM_FILE__ request: (116530.094 ms)
```
where the 2nd column has `:` in the id. Should probably also list the identifier restrictions in the tool help.

**Comment by mpaya** [comment]
Hi. I'm also finding this issue. Is there a fix or an alternative tool to do this renaming? Thank you

**Comment by bitbarbie** [comment]
Hi, I've had the same error message. Solved it by omitting "." in my file names. ( "-" was ok).
I agree with @blankenberg that the issue could be solved by adding the identifier restrictions in the help.
Thx.

**Comment by sneumann** [comment]
The tool XML is in https://github.com/galaxyproject/galaxy/blob/master/lib/galaxy/tools/relabel_from_file.xml
and the help page in line 135 onwards. The actual implementation in 
https://github.com/galaxyproject/galaxy/blob/f6011bab5b8adbabae4986a45849bb9158ffc8bb/lib/galaxy/tools/__init__.py#L2868

checks this regular expression: https://github.com/galaxyproject/galaxy/blob/f6011bab5b8adbabae4986a45849bb9158ffc8bb/lib/galaxy/tools/__init__.py#L2911
