### ISSUE TITLE
Problem Uploading Images

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#6209]
Reported by @qiagu in Gitter:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/Users/guq/galaxy/tools/data_source/upload.py", line 323, in <module>
    __main__()
  File "/Users/guq/galaxy/tools/data_source/upload.py", line 316, in __main__
    metadata.append(add_file(dataset, registry, output_path))
  File "/Users/guq/galaxy/tools/data_source/upload.py", line 150, in add_file
    ext = sniff.guess_ext(dataset.path, registry.sniff_order, is_binary=is_binary)
  File "/Users/guq/galaxy/lib/galaxy/datatypes/sniff.py", line 484, in guess_ext
    get_headers(file_prefix, None)
  File "/Users/guq/galaxy/lib/galaxy/datatypes/sniff.py", line 230, in get_headers
    return list(iter_headers(fname_or_file_prefix=fname_or_file_prefix, sep=sep, count=count, comment_designator=comment_designator))
  File "/Users/guq/galaxy/lib/galaxy/datatypes/sniff.py", line 197, in iter_headers
    for line in fname_or_file_prefix.line_iterator():
  File "/Users/guq/galaxy/lib/galaxy/datatypes/sniff.py", line 590, in line_iterator
    s = self.string_io()
  File "/Users/guq/galaxy/lib/galaxy/datatypes/sniff.py", line 582, in string_io
    raise Exception("Attempting to create a StringIO object for binary data.")
Exception: Attempting to create a StringIO object for binary data.
```

**Comment by jmchilton** [comment]
@qiagu I'm trying to reproduce this and I cannot. I took a SVS file from here http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs (http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/). I tried to upload this, upload it to a library, import to a library with a link, take the results and move them in and out of histories. This looks like something that could easily have been broken recently but I need some help to generate the Traceback I think. Can you give me some advice on how to reproduce this - a link to a small example file, a set of actions to take, etc..? Also is this something that worked before the latest release and was broken recently or do you not know?

**Comment by qiagu** [comment]
I'm not sure that I could reproduce the issue, but I'll try my best. 
It may relate to one of these, `library_import_dir`, `user_library_import_dir`, `user_library_import_dir_auto_creation`,  in the `galaxy.yml` file.

**Comment by mvdbeek** [comment]
This code has evolved a lot since last year. If this is still an issue feel free to re-open (ideally with instructions on how to reproduce).
