### ISSUE TITLE
Pulsar jobs do not fail if missing required parameters, just hang in queued

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6318]
```
galaxy.jobs.runners ERROR 2018-06-12 12:31:32,476 (3962747) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 113, in run_next
    method(arg)
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/pulsar.py", line 273, in queue_job
    self._populate_parameter_defaults(job_destination)
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/pulsar.py", line 420, in _populate_parameter_defaults
    raise Exception("Pulsar destination does not define required parameter %s" % key)
Exception: Pulsar destination does not define required parameter jobs_directory
```

Jobs experiencing this just hang in queued rather than propagating the error up properly. cc @jmchilton

**Comment by hexylena** [comment]
Additionally: pulsar does not like it if the `jobs_directory` param is not specified in the `job_conf.xml`. We were generating it as part of a dynamic destination and it seemed to generate the same error without ever talking to our dynamic destination.

I have not investigated yet if I can set that to some dummy value like /tmp, and then override that in the dynamic destination, but that will be checked soon.
