### ISSUE TITLE
failure for resubmitted upload job

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6328]
I have a huge upload job which needs more time then initially granted. Resubmission fails with the following error: 

```
Failure preparing job
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 192, in prepare_job
    job_wrapper.prepare()
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 871, in prepare
    self.__prepare_upload_paramfile(tool_evaluator)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 838, in __prepare_upload_paramfile
    shutil.move(tool_evaluator.param_dict['paramfile'], new)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: SafeStringWrapper(str:__lt__class __sq__galaxy.tools.wrappers.ToolParameterValueWrapper__sq____gt__,__lt__class __sq__galaxy.util.object_wrapper.SafeStringWrapper__s
q____gt__,__lt__class __sq__numbers.Number__sq____gt__,__lt__type __sq__NoneType__sq____gt__,__lt__type __sq__NotImplementedType__sq____gt__,__lt__type __sq__bool__sq____gt__,__lt__type __sq__bytearray__sq____gt
__,__lt__type __sq__ellipsis__sq____gt__) object at 7f6ec5a25d40 on: __sq__/work/songalax/galaxy-dev/database/tmp/upload_params_qi0OSw__sq__
```
The file `/work/songalax/galaxy-dev/database/tmp/upload_params_qi0OSw` actually is missing. 

I'm working on dev and submit jobs as real user.

**Comment by bernt-matthias** [comment]
Resubmissions seem to work now.
