### ISSUE TITLE
tags not working

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6411]
On 18.09 when I add a new tag to a pasted file I get:

```
galaxy.web.framework.decorators ERROR 2018-06-29 11:33:21,072 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/webapps/galaxy/api/history_contents.py", line 581, in update
    return self.__update_dataset(trans, history_id, id, payload, **kwd)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/webapps/galaxy/api/history_contents.py", line 614, in __update_dataset
    self.hda_deserializer.deserialize(hda, payload, user=trans.user, trans=trans)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/managers/base.py", line 772, in deserialize
    new_dict[key] = self.deserializers[key](item, key, val, **context)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/managers/taggable.py", line 90, in deserialize_tags
    _tags_from_strings(item, self.app.tag_handler, new_tags_list, user=user)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/managers/taggable.py", line 40, in _tags_from_strings
    tag_handler.apply_item_tags(user, item, unicodify(new_tags_str, 'utf-8'))
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/managers/tags.py", line 182, in apply_item_tags
    self.apply_item_tag(user, item, name, value)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/managers/tags.py", line 146, in apply_item_tag
    lc_name = name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

On dev I can assign tags, but they are seemingly not transferred downstream analyses (tested with a uploaded fastqsanger.gz processed by FastQC).

**Comment by dannon** [comment]
@bernt-matthias Is this 17.09, or 18.05 (or something else entirely)?  (sounds familiar, like we may have fixed this already and it just needs a backport)

**Comment by bernt-matthias** [comment]
I meant 18.05 (latest release).

**Comment by mvdbeek** [comment]
I might have fixed the traceback with 366701c, but not sure about this without knowing what `new_tags_str` was in that case. I haven't seen a name tag disappear yet (except for some collection operation tools, but I thought we fixed that too). There isn't really anything special about the fastqc in/out files, so we'd need to know more about the actual tags used, I think.

**Comment by bernt-matthias** [comment]
Unfortunatelly I can not find the Traceback in our logs anymore ... and therefore I can also not tell you more about the tags that have been used. Should have thought about this when reporting :( 

But still, the main point is that on my 18.05 and dev instances tags are seemingly not in transferred to any resulting data set.

![screenshot from 2018-08-28 11-27-36](https://user-images.githubusercontent.com/25689525/44714570-f02bb980-aab5-11e8-82a3-2071deca9df0.png)

**Comment by mvdbeek** [comment]
That's the expected behavior, only nametags (either name:my_tag or #my_tag) are transferred.

**Comment by mvdbeek** [comment]
I'll go ahead and close this one, if the traceback pops up again let us know.
