### ISSUE TITLE
internal error on resume paused jobs

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6495]
this is on dev

```
127.0.0.1 - - [12/Jul/2018:13:52:53 -0400] "GET /history/resume_paused_jobs?current=True HTTP/1.1" 500 - "http://127.0.0.1:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 75, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 166, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 181, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/history.py", line 1090, in resume_paused_jobs
    history.resume_paused_jobs()
  File "lib/galaxy/model/__init__.py", line 1533, in resume_paused_jobs
    for i, job in self.paused_jobs:
TypeError: 'Job' object is not iterable
[pid: 76548|app: 0|req: 28/58] 127.0.0.1 () {46 vars in 1050 bytes} [Thu Jul 12 13:52:53 2018] GET /history/resume_paused_jobs?current=True => generated 0 bytes in 22 msecs (HTTP/1.1 500) 1 headers in 63 bytes (0 switches on core 1)
```

**Comment by martenson** [comment]
@mvdbeek looks like the `i` is superfluous here?

```
    @property
    def paused_jobs(self):
        db_session = object_session(self)
        return db_session.query(Job).filter(Job.history_id == self.id,
                                            Job.state == Job.states.PAUSED).all()
```
```
        for i, job in self.paused_jobs:
            job.resume(flush=False)
```
