### ISSUE TITLE
GRT export.py fails with database version error when `share_toolbox: True`

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#6534]
I have Galaxy 18.05 installed with the database fully updated. When I try and export GRT data I get an error about database version:

```
$ python scripts/grt/export.py
galaxy.web.stack DEBUG 2018-07-25 12:20:41,872 server_name set to: main
galaxy.queue_worker INFO 2018-07-25 12:20:41,874 Initializing main Galaxy Queue Worker on sqlalchemy+sqlite:///./database/control.sqlite?isolation_level=IMMEDIATE
galaxy.app DEBUG 2018-07-25 12:20:42,012 Using "galaxy.ini" config file: /net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/config/galaxy.yml
Traceback (most recent call last):
  File "scripts/grt/export.py", line 442, in <module>
    main(sys.argv)
  File "scripts/grt/export.py", line 175, in main
    model, object_store, gxconfig, app = _init(args, need_app=config['grt']['share_toolbox'])
  File "scripts/grt/export.py", line 38, in _init
    app = galaxy.app.UniverseApplication(global_conf={'__file__': config_file, 'here': os.getcwd()})
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/lib/galaxy/app.py", line 84, in __init__
    self._configure_models(check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/lib/galaxy/config.py", line 1111, in _configure_models
    create_or_verify_database(db_url, config_file, self.config.database_engine_options, app=self)
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/lib/galaxy/model/migrate/check.py", line 121, in create_or_verify_database
    raise Exception("%s. %s%s" % (expect_msg, instructions, backup_msg))
Exception: Your database has version '140' but this code expects version '141'. Please backup your database and then migrate the database schema by running 'sh manage_db.sh -c ./config/galaxy.yml upgrade'.
```

My `grt.yml` config file is as follows:

```
# Location of your galaxy config file. The radio telescope will need to
# partially initialize a copy of galaxy in order to share your toolbox
galaxy_config: config/galaxy.yml

grt:
    # Go to https://telescope.galaxyproject.org to obtain an Instance ID and API key
    instance_id: "5"
    api_key: "DELETED"
    # Galaxy Project offers a public galactic-radio-telescope instance, however
    # you are free to run your own if you need. We would love it if you were
    # willing and able to contribute your data publicly.
    url: https://telescope.galaxyproject.org
    # Are you willing to share your toolbox? I.e. what tools are installed.
    # If your instance is public, this can help us direct users to your
    # instance. If you elect to not send your entire toolbox, we will still
    # (necessarily) receive a list of tools that have been run, just not the
    # complete list.
    share_toolbox: True


sanitization:
    # Blacklist the entire tool from appearing
    tools:
        - __SET_METADATA__
        - upload1
    # Or you can blacklist individual parameters from being submitted, e.g. if
    # you have API keys as a tool parameter.
    tool_params:
        # Or to blacklist under a specific tool, just specify the ID
        some_tool_id:
            - dbkey
            # If you need to specify a parameter multiple levels deep, you can
            # do that as well. Currently we only support blacklisting via the
            # full path, rather than just a path component. So everything under
            # `path.to.parameter` will be blacklisted.
            - path.to.parameter
            # However you could not do "parameter" and have everything under
            # `path.to.parameter` be removed.
            # Repeats are rendered as an *, e.g.: repeat_name.*.values
```

If I set `share_toolbox: False` the export completes with no error.

**Comment by mvdbeek** [comment]
The latest commit on 18.05 is indeed expecting database version 141, which manipulates open ID related things. This was a late update, you may want to run sh manage_db.sh upgrade

**Comment by hexylena** [comment]
@mvdbeek, this occurs whenever `share_toolbox: True`, I experience the same thing. I looked into it a bit, but couldn't figure it out. For some reason it sees a different database or loads a different configuration despite what is passed. I will be removing this functionality as it has not shown to be useful.

**Comment by pvanheus** [comment]
I can (belatedly) confirm what @erasche is saying. My Galaxy database shows that it is version 141 but I still got that message.
