### ISSUE TITLE
GRT upload fails because of error on `api/whoami`

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#6535]
I have a Galaxy 18.05 server register with Galactic Radio Telescope. When I try and upload stats with `python scripts/grt/upload.py` I get an error:

```
Traceback (most recent call last):
  File "scripts/grt/upload.py", line 68, in <module>
    main(sys.argv)
  File "scripts/grt/upload.py", line 48, in main
    data = r.json()
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/.venv/local/lib/python2.7/site-packages/requests/models.py", line 893, in json
    return complexjson.loads(self.text, **kwargs)
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/.venv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/.venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/net/datasrv3hs.sanbi.ac.za/datastore/cip0/software/galaxy/galaxy-ctb/galaxy/.venv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The source of the error is trying to decode HTML as JSON - in the [upload.py](https://github.com/galaxyproject/galaxy/blob/dev/scripts/grt/upload.py#L49) script it tries to query an API endpoint `api/whoami` and fails, receiving instead the following HTML:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/whoami was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at telescope.galaxyproject.org Port 443</address>
</body></html>
```

(BTW for ease of debugging, my instance ID is [5](https://telescope.galaxyproject.org/grt-admin/galaxy/5/))

**Comment by martenson** [comment]
use `url: https://telescope.galaxyproject.org/grt-admin/` in your grt.yml. The newest sample should have this fixed

**Comment by hexylena** [comment]
@pvanheus solved?

**Comment by pvanheus** [comment]
Sadly not. I get `<h1>Server Error (500)</h1>` with the updated URL. Full URL that is loaded is `https://telescope.galaxyproject.org/grt-admin/api/whoami` and the headers sent are `{'AUTHORIZATION': '5:<AUTHKEY>'}`.

**Comment by hexylena** [comment]
Weird! Can you test with `curl https://telescope.galaxyproject.org/grt-admin/api/whoami -H 'AUTHORIZATION: 5:<your key>' -X POST` for me?

Alternatively can you re-run upload.py? I've enabled debugging to capture the stack trace.

**Comment by pvanheus** [comment]
It is working now.. both the `curl` and the `upload.py` work.
