### ISSUE TITLE
Error on tool API when io_details=True

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#6537]
Hi,

The API (via bioblend) is failing for some tools (not all) when asking for `io_details`.

For example, on usegalaxy.org/eu, the tool Trim Galore (`tool_id = "toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.0"`):

- Without `io_details = True`

   ```
   >> gi.tools.show_tool(tool_id)
   {'panel_section_id': 'fasta_fastq_manipulation', 'edam_operations': [], 'panel_section_name': 'FASTA/FASTQ manipulation', 'edam_topics': [], 'version': '0.4.3.0', 'form_style': 'regular', 'id': 'toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.0', 'model_class': 'Tool', 'name': 'Trim Galore!', 'tool_shed_repository': {'changeset_revision': '1bf4789584dc', 'owner': 'bgruening', 'tool_shed': 'toolshed.g2.bx.psu.edu', 'name': 'trim_galore'}, 'description': 'Quality and adapter trimmer of reads', 'labels': []}
   ```

- With `io_details = True`

   ```
   >>> gi.tools.show_tool(tool_id, io_details = True)
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/path/to/bioblend/galaxy/tools/__init__.py", line 98, in show_tool
       return self._get(id=tool_id, params=params)
     File "/path/to/bioblend/galaxy/client.py", line 136, in _get
       status_code=r.status_code)
   bioblend.ConnectionError: GET: error 500: b'{"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}', 0 attempts left: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
   ```

But not for all tools (for example no issue with FastQC)

Any idea what could be the issue? Is it with the Galaxy API or specific to Bioblend?

Bérénice

**Comment by nsoranzo** [comment]
That's Galaxy-specific, see https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.1?io_details=True .

I've replicated this on our server, here's the traceback:
```
[pid: 13951|app: 0|req: 4786/9589] 149.155.222.206 () {46 vars in 1124 bytes} [Wed Jul 25 16:54:41 2018] GET /api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.1 => generated 671 bytes in 32 msecs (HTTP/1.1 200) 3 headers in 124 bytes (1 switches on core 2)
galaxy.web.framework.decorators ERROR 2018-07-25 16:55:11,505 [p:14720,w:2,m:0] [uWSGIWorker2Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/tools.py", line 101, in show
    return tool.to_dict(trans, io_details=io_details, link_details=link_details)
  File "lib/galaxy/tools/__init__.py", line 1815, in to_dict
    tool_dict['outputs'] = [output.to_dict(app=self.app) for output in self.outputs.values()]
TypeError: to_dict() got an unexpected keyword argument 'app'
149.155.222.206 - - [25/Jul/2018:16:55:10 +0100] "GET /api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.1?io_details=True HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
```

**Comment by jmchilton** [comment]
I see the problem - want me to fix this or are you working on it @nsoranzo ?

**Comment by nsoranzo** [comment]
I'm leaving for 20-day holiday in few minutes, can't do it, sorry!

**Comment by jmchilton** [comment]
No problem at all - I've got this just wanted to make sure you weren't about to open a competing PR. Enjoy the holiday!

**Comment by bebatut** [comment]
Thanks!
@nsoranzo enjoy your holidays!

**Comment by hexylena** [comment]
@bebatut I can pull in latest code on usegalaxy.eu tomorrow or so.

**Comment by bebatut** [comment]
It would be nice. Thanks!
