### ISSUE TITLE
scripts/grt/ weird behaviour with grt.yml present

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#6547]
I setup my own galactic-radio-telescope.   
I subsequently created the Galaxies in this.   
I then used the generated text in the text field as my grt.yml (as described).   
   
Then I tried to run: `python scripts/grt/export.py`. This failed with the following error:
```
(.venv)USER@SERVER:~/galaxy$ python scripts/grt/export.py -l debug
INFO:root:Loading GRT configuration...
INFO:root:Loading Galaxy...
DEBUG:galaxy.containers:config file './config/containers_conf.yml' does not exist, running with default config
DEBUG:galaxy.app:python path is: /home/USER/galaxy/scripts/grt, /home/USER/galaxy/lib, /home/USER/galaxy/.venv/lib/python2.7, /home/USER/galaxy/.venv/lib/python2.7/plat-x86_64-linux-gnu, /home/USER/galaxy/.venv/lib/python2.7/lib-tk, /home/USER/galaxy/.venv/lib/python2.7/lib-old, /home/USER/galaxy/.venv/lib/python2.7/lib-dynload, /usr/lib/python2.7, /usr/lib/python2.7/plat-x86_64-linux-gnu, /usr/lib/python2.7/lib-tk, /home/USER/galaxy/.venv/local/lib/python2.7/site-packages
DEBUG:galaxy.containers:config file './config/containers_conf.yml' does not exist, running with default config
galaxy.web.stack DEBUG 2018-07-27 09:12:31,349 server_name set to: main
galaxy.queue_worker INFO 2018-07-27 09:12:31,349 Initializing main Galaxy Queue Worker on sqlalchemy+sqlite:///./database/control.sqlite?isolation_level=IMMEDIATE
galaxy.app DEBUG 2018-07-27 09:12:31,393 Using "galaxy.ini" config file: /home/USER/galaxy/config/galaxy.yml
Traceback (most recent call last):
  File "scripts/grt/export.py", line 442, in <module>
    main(sys.argv)
  File "scripts/grt/export.py", line 175, in main
    model, object_store, gxconfig, app = _init(args, need_app=config['grt']['share_toolbox'])
  File "scripts/grt/export.py", line 38, in _init
    app = galaxy.app.UniverseApplication(global_conf={'__file__': config_file, 'here': os.getcwd()})
  File "/home/USER/galaxy/lib/galaxy/app.py", line 84, in __init__
    self._configure_models(check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "/home/USER/galaxy/lib/galaxy/config.py", line 1120, in _configure_models
    create_or_verify_database(db_url, config_file, self.config.database_engine_options, app=self)
  File "/home/USER/galaxy/lib/galaxy/model/migrate/check.py", line 121, in create_or_verify_database
    raise Exception("%s. %s%s" % (expect_msg, instructions, backup_msg))
Exception: Your database has version '134' but this code expects version '141'. Please backup your database and then migrate the database schema by running 'sh manage_db.sh -c ./config/galaxy.yml upgrade'.
```

My Galaxy instances (2 instances, 18.01 and 18.05) both run a postgresql database.   
In the grt.yml file, I used the `galaxy_config` parameter, but this didn't work either.   
   
I have now gotten around this issue by doing the following:
   
1. in `scripts/grt/` don't name a file grt.yml
2. For `export.py`, run it without specifying the YAML file.
3. For `upload.py`, use the YAML file (but it can't be called grt.yml) with the -g flag.

These steps don't cause errors to pop up.

**Comment by hexylena** [comment]
Please set `share_toolbox: False` and this should be fixed. Let me know if that works for you and we can close this. I've removed the functionality in #6553
