### ISSUE TITLE
Should keep old tools if reloading new tool failed

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6584]
That's a bit annoying with planemo serve and development. If you break the XML, the tool disappears, and hence isn't being watched anymore. Either we only load valid new tools, or we somehow keep watching.

```
galaxy.tools.toolbox.base INFO 2018-08-09 10:57:04,513 Parsing the tool configuration /private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpicezz6xb/tool_conf.xml
galaxy.tools.toolbox.base ERROR 2018-08-09 10:57:04,519 Error reading tool from path: /Users/mvandenb/src/tools-iuc/tools/fastp/fastp.xml
Traceback (most recent call last):
  File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpicezz6xb/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 567, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False)
  File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpicezz6xb/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 751, in load_tool
    tool = self.create_tool(config_file=config_file, repository_id=repository_id, guid=guid, **kwds)
  File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpicezz6xb/galaxy-dev/lib/galaxy/tools/__init__.py", line 270, in create_tool
    raise e
KeyError: 'adapter_trimming_options'
```

**Comment by mblue9** [comment]
Oh if this can be changed that would be great! This has bitten me many times! Would be great not to have to restart planemo serve and reload data in every time this happens (or is there a workaround?), that would save a chunk of time.
