### ISSUE TITLE
Galaxy 18.05 Unable to install Tools (stays in status NEW)

### ISSUE THREAD

**Issue by gad83** [galaxyproject/galaxy#6679]
Hello gents,

I have a brand new installation of galaxy 18.05 with Apache proxy and a job configuration that sends upload1 to"local" and everything else to "drmaa".

When I try to install a tools in a new panel I get the following error in galaxy.log:
`galaxy.queue_worker ERROR 2018-09-07 12:41:32,995 [p:27809,w:1,m:0] [uWSGIWorker1Core0] Error sending control task: {'task': 'create_panel_section', 'kwargs': {'version': '', 'name': u'ESI Tools Panel', 'id': 'esi_tools_panel'}}.
Traceback (most recent call last):
  File "lib/galaxy/queue_worker.py", line 56, in send_control_task
    routing_key='control')
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/common.py", line 129, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/common.py", line 135, in _maybe_declare
    entity.declare(channel=channel)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/entity.py", line 605, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/entity.py", line 614, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/entity.py", line 649, in queue_declare
    nowait=nowait,
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 531, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 82, in _new_queue
    self._get_or_create(queue)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 70, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 65, in session
    _, Session = self._open()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 58, in _open
    metadata.create_all(engine)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/galaxy/galaxy-18.05/.venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (_mysql_exceptions.OperationalError) (1040, 'Too many connections') (Background on this error at: http://sqlalche.me/e/e3q8)
galaxy.tools.toolbox.base DEBUG 2018-09-07 12:41:33,023 [p:27809,w:1,m:0] [uWSGIWorker1Core0] Loading new tool panel section: ESI Tools Panel
galaxy.tools.toolbox.base DEBUG 2018-09-07 12:41:33,047 [p:27809,w:1,m:0] [uWSGIWorker1Core0] Appending to tool panel section: ESI Tools Panel
10.33.158.247 - - [07/Sep/2018:12:41:32 -0400] "POST /galaxy-prod/admin_toolshed/prepare_for_install HTTP/1.1" 200 - "http://server.domain.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install?changeset_revisions=17062a0decb7&repository_ids=126c0918b5459666&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"
[pid: 27809|app: 0|req: 29/97] 10.33.158.247 () {64 vars in 1717 bytes} [Fri Sep  7 12:41:32 2018] POST /galaxy-prod/admin_toolshed/prepare_for_install => generated 11506 bytes in 692 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
`

------

I also get the following error in the Apache logs:
`[Fri Sep 07 12:41:33 2018] [crit] [client 10.33.158.247] configuration error:  couldn't perform authentication. AuthType not set!: /galaxy-prod/static/style/base.css, referer: http://server.domainl.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install
[Fri Sep 07 12:41:33 2018] [crit] [client 10.33.158.247] configuration error:  couldn't perform authentication. AuthType not set!: /galaxy-prod/static/scripts/bundled/extended.bundled.js, referer: http://server.domain.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install
[Fri Sep 07 12:41:33 2018] [crit] [client 10.33.158.247] configuration error:  couldn't perform authentication. AuthType not set!: /galaxy-prod/static/scripts/libs/require.js, referer: http://server.domain.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install
[Fri Sep 07 12:41:33 2018] [crit] [client 10.33.158.247] configuration error:  couldn't perform authentication. AuthType not set!: /galaxy-prod/static/scripts/bundled/libs.bundled.js, referer: http://server.domain.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install
[Fri Sep 07 12:41:33 2018] [crit] [client 10.33.158.247] configuration error:  couldn't perform authentication. AuthType not set!: /galaxy-prod/static/style/bootstrap-tour.css, referer: http://server.domain.ca:8081/galaxy-prod/admin_toolshed/prepare_for_install
`

Any ideas?
Please help!

Edgar

**Comment by gad83** [comment]
Missing tool shed directory!
