### ISSUE TITLE
Missing tools in subworkflow cause API exception

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6689]
These need to be carried forward:

```
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 403, in workflow_dict
    ret_dict = self.workflow_contents_manager.workflow_to_dict(trans, stored_workflow, style=style)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/workflows.py", line 387, in workflow_to_dict
    return self._workflow_to_dict_run(trans, stored)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/managers/workflows.py", line 423, in _workflow_to_dict_run
    raise exceptions.MessageException('Following tools missing: %s' % ', '.join(missing_tools))
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by mvdbeek** [comment]
Fixed with https://github.com/galaxyproject/galaxy/pull/7227
