### ISSUE TITLE
Need more descriptive message on workflow upload failure.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6976]
Currently my user sees:

```
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

with the command line. It would be helpful if the internal exception could be exposed:

```traceback
galaxy.web.framework.decorators ERROR 2018-11-06 11:23:22,360 [p:4004472,w:5,m:0] [uWSGIWorker5Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 318, in create
    return self.__api_import_from_archive(trans, archive_data, "uploaded file")
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 561, in __api_import_from_archive
    workflow, missing_tool_tups = self._workflow_from_dict(trans, data, source=source)
  File "lib/galaxy/web/base/controller.py", line 1252, in _workflow_from_dict
    exact_tools=exact_tools,
  File "lib/galaxy/managers/workflows.py", line 232, in build_workflow_from_dict
    exact_tools=exact_tools,
  File "lib/galaxy/managers/workflows.py", line 337, in _workflow_from_dict
    self.__connect_workflow_steps(steps, steps_by_external_id)
  File "lib/galaxy/managers/workflows.py", line 948, in __connect_workflow_steps
    conn.output_step = steps_by_external_id[conn_dict['id']]
KeyError: 2
```

**Comment by mvdbeek** [comment]
I don't think we can just propagate exceptions here, that would be a potential security risk. I do think that we can do some basic linting as you suggested in https://github.com/galaxyproject/planemo/issues/885. In that context we might then also do that before actually ~~uploading~~ importing the workflow.

I don't think this is a bug (but feel free to relabel!), that's why I relabelled this to feature-request (which is up-front validation of workflow connections)

**Comment by hexylena** [comment]
No, propagating exceptions would be bad and not what I intended from my issue, the title was more accurate, we just need to expose a more detailed exception.

Edit: yeah, ok, feature not bug, sure. That was a mistag on my part, thanks :)

**Comment by bernt-matthias** [comment]
How about printing a unique _"bug ID"_ (e.g. a hash of the Traceback) to the user and the log. Then the message could be 

```
Uncaught exception in exposed API method: 

Please get in contact with the admins and mention this id: ....
```

Or have an error report form like for tool errors.

Then users can report to admins with a specific bug and admins can find the details in the log. Ideally the log would contain also the userid.

**Comment by hexylena** [comment]
We have that with sentry a bit. It'd be nice for sure.

**Comment by hexylena** [comment]
So I keep having these issues though, issues where the user could (maybe) solve the problem for themselves but three people on the EU server can see the error message. For 27k users.

Currently it's `Exception: Subworkflow step must define either subworkflow or content_id.` which is completely cryptic, and only appears when there's a subworkflow in the WF, but, no one could see this except people with administrative access to EU servers. Not admins, access to the galaxy logs themselves.

And I know there can be issues exposing exceptions but I really think we could/should be exposing more. Every time someone I work with runs into an issue with workflows there's just zero user facing feedback. If they know to ask me, they do. If they don't, they end up re-creating the entire workflow from scratch just to try and figure out what went wrong.

**Comment by afgane** [comment]
This is all a user sees, which is not much to go on:
![image](https://user-images.githubusercontent.com/338642/121075454-348a2f00-c7a3-11eb-9653-769c2d203967.png)

In the case of `Subworkflow step must define either subworkflow or content_id.`, even the exception is cryptic because it's still not clear which subworkflow or step is missing.

**Comment by mvdbeek** [comment]
@afgane Can you create an issue with the current commit this Galaxy is running and how to reproduce this, if you it ?

**Comment by afgane** [comment]
This is the last PR that was included: https://github.com/galaxyproject/galaxy/pull/11314

I've pulled this version locally and can reproduce the issue by just starting Galaxy with `sh run.sh`, then creating a workflow A, and then creating another workflow where I add workflow A and clicking `Save`.
