### ISSUE TITLE
Fastq.gz datatype not recognized on import to data library

### ISSUE THREAD

**Issue by cpreviti** [galaxyproject/galaxy#7068]
I came across another issue after our update from 17.09 to 18.05. When trying to import fastq.gz files into a data library (linking the files from a user directory), the format is not recognized either automatically or in any way reliably. 
I specifically have to set the data type to fastq.gz in order for it to work at all and even then it sometimes ends up throwing an error (state = error). Here are the relevant lines from galaxy.log: 
[error_upload.log](https://github.com/galaxyproject/galaxy/files/2640179/error_upload.log)
Best regards,
Christopher Previti

```
172.21.153.213 - - [03/Dec/2018:16:49:13 +0200] "GET / HTTP/1.1" 302 - "-" "check_http/v2.2.1.git (nagios-plugins 2.2.1)"
galaxy.jobs DEBUG 2018-12-03 16:53:52,143 (16941) Working directory for job is: /opt/galaxy/galaxy/database/jobs_directory/016/16941
galaxy.jobs.handler DEBUG 2018-12-03 16:53:52,155 (16941) Dispatching to slurm runner
galaxy.jobs DEBUG 2018-12-03 16:53:52,166 (16941) Persisting job destination (destination id: galaxy)
galaxy.jobs.runners DEBUG 2018-12-03 16:53:52,173 Job [16941] queued (17.253 ms)
galaxy.jobs.handler INFO 2018-12-03 16:53:52,183 (16941) Job dispatched
galaxy.jobs.runners ERROR 2018-12-03 16:53:52,282 (16941) Failure preparing job
Traceback (most recent call last):
  File "/opt/galaxy/galaxy/lib/galaxy/jobs/runners/__init__.py", line 192, in prepare_job
    job_wrapper.prepare()
  File "/opt/galaxy/galaxy/lib/galaxy/jobs/__init__.py", line 863, in prepare
    self.__prepare_upload_paramfile(tool_evaluator)
  File "/opt/galaxy/galaxy/lib/galaxy/jobs/__init__.py", line 830, in __prepare_upload_paramfile
    shutil.move(tool_evaluator.param_dict['paramfile'], new)
  File "/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: SafeStringWrapper(str:__lt__class __sq__galaxy.tools.wrappers.ToolParameterValueWrapper__sq____gt__,__lt__class __sq__galaxy.util.object_wrapper.SafeStringWrapper__sq____gt__,__lt__class __sq__numbers.Number__sq____gt__,__lt__type __sq__NoneType__sq____gt__,__lt__type __sq__NotImplementedType__sq____gt__,__lt__type __sq__bool__sq____gt__,__lt__type __sq__bytearray__sq____gt__,__lt__type __sq__ellipsis__sq____gt__) object at 7f545063f9e0 on: __sq__/opt/galaxy/galaxy/database/tmp/upload_params_d2LPm2__sq__
galaxy.model.metadata DEBUG 2018-12-03 16:53:52,467 Cleaning up external metadata files
172.21.153.213 - - [03/Dec/2018:16:54:13 +0200] "GET / HTTP/1.1" 302 - "-" "check_http/v2.2.1.git (nagios-plugins 2.2.1)"

```

**Comment by cpreviti** [comment]
A little update, I found that setting the datatype to fastqsanger.gz leads to a correct import of the files.
It's only "fastq.gz" that results in errors.

**Comment by cpreviti** [comment]
I stand corrected, it'a also .zip files that are incorrectly imported. I tried to import some .fastqc.zip files (output of fastqc) and it decided to make them .png files. Could this be a general compression issue?

**Comment by mshamash** [comment]
Hello,

Did you ever manage to fix this? We're having the same issue with the Galaxy instance set up for us on our compute cluster. Can't upload any files at all (tried .fastq, fastq.gz, .fasta, and raw data pasted), without getting this error each time.
