### ISSUE TITLE
Migrations on dev broken ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7107]
This is on 58dd7e6a458440d057140a2c130b1f9a11a7b879

```
Activating virtualenv at .venv
144 -> 145...

Migration script for workflow step input table.

Traceback (most recent call last):
  File "./scripts/manage_db.py", line 24, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 20, in invoke_migrate_main
    main(repository=repo, url=db_url)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "lib/galaxy/model/migrate/versions/0145_add_workflow_step_input.py", line 48, in upgrade
    OldWorkflowStepConnection_table.rename("workflow_step_connection_preupgrade145")
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/changeset/schema.py", line 507, in rename
    run_single_visitor(engine, visitorcallable, self, connection, **kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/changeset/databases/visitor.py", line 85, in run_single_visitor
    fn(element, **kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 164, in visit_table
    self.execute()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "workflow_step_connection_preupgrade145" already exists
 [SQL: '\nALTER TABLE workflow_step_connection RENAME TO workflow_step_connection_preupgrade145'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by nsoranzo** [comment]
That would happen only if the migration failed before.

**Comment by mvdbeek** [comment]
This was the first one, which as far as I can tell from reflog was also 58dd7e6:
```
Creating workflow_step_input table failed.
Traceback (most recent call last):
  File "lib/galaxy/model/migrate/versions/0145_add_workflow_step_input.py", line 113, in _create
    table.create()
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 779, in create
    checkfirst=checkfirst)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "workflow_step_input" already exists
 [SQL: '\nCREATE TABLE workflow_step_input (\n\tid SERIAL NOT NULL, \n\tworkflow_step_id INTEGER, \n\tname TEXT, \n\tmerge_type TEXT, \n\tscatter_type TEXT, \n\tvalue_from BYTEA, \n\tvalue_from_type TEXT, \n\tdefault_value BYTEA, \n\tdefault_value_set BOOLEAN, \n\truntime_value BOOLEAN, \n\tPRIMARY KEY (id), \n\tUNIQUE (workflow_step_id, name), \n\tFOREIGN KEY(workflow_step_id) REFERENCES workflow_step (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "./scripts/manage_db.py", line 24, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 20, in invoke_migrate_main
    main(repository=repo, url=db_url)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "lib/galaxy/model/migrate/versions/0145_add_workflow_step_input.py", line 68, in upgrade
    migrate_engine.execute(insert_step_inputs_cmd)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2075, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "workflow_step_input_workflow_step_id_name_key"
DETAIL:  Key (workflow_step_id, name)=(11, showsize) already exists.
 [SQL: 'INSERT INTO workflow_step_input (workflow_step_id, name) SELECT DISTINCT input_step_id, input_name FROM workflow_step_connection_preupgrade145'] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by dannon** [comment]
Hrmm.  You sure this didn't fail before?  The fixes in #7103 only affect (and fix) downgrade behavior, not upgrade as seen here.  Though, of course, pre-7103 downgrades would have broken like you're seeing.

**Comment by mvdbeek** [comment]
Oh, I don't think https://github.com/galaxyproject/galaxy/pull/7103 is related

**Comment by mvdbeek** [comment]
(I had seen this before at the EGD, but rolled back the database, hoping that https://github.com/galaxyproject/galaxy/pull/7029 would fix this)

**Comment by dannon** [comment]
Oh, ok, I misunderstood!  So, yeah, they definitely *were* broken :)   Do you have a backup database you can test this against to try to reproduce?

**Comment by mvdbeek** [comment]
Nope, it's my dev machine, no backups here.

**Comment by dannon** [comment]
Might have to manually drop the columns and indexes and try a reupgrade?  I was lucky enough to have a version from a few months ago when I was testing something, when I hit this.

**Comment by nsoranzo** [comment]
Should we remove the `_create()` and `_drop()` functions in lib/galaxy/model/migrate/versions/0145_add_workflow_step_input.py , which in case of error log the exception and let the migration continue?

xref. https://github.com/galaxyproject/galaxy/issues/6028

**Comment by nsoranzo** [comment]
`ProgrammingError: (psycopg2.ProgrammingError) relation "workflow_step_input" already exists`

The `workflow_step_input` table should exist only in case of another previous failed migration.

**Comment by mvdbeek** [comment]
that's weird, I don't think that was the case. but I also can't exclude it.

**Comment by mvdbeek** [comment]
Alright, after some troubleshooting on gitter (thanks a lot @nsoranzo ) I did have some remains from a previous migration in my db. It's all fixed now, and I doubt anyone will run into this.
For reference, if it does happen, backup the database and (assuming postgresql):

```
DROP TABLE workflow_step_connection;
DROP TABLE workflow_step_input;
ALTER TABLE workflow_step_connection_preupgrade145 RENAME TO workflow_step_connection;
UPDATE migrate_version SET version=144;
```
