### ISSUE TITLE
dbkeys with + character are not rendered during data import -> dbkey error

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#7271]
<pre>
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 192, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 857, in prepare
    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
  File "lib/galaxy/tools/evaluation.py", line 73, in set_compute_environment
    visit_input_values(self.tool.inputs, incoming, validate_inputs)
  File "lib/galaxy/tools/parameters/__init__.py", line 168, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "lib/galaxy/tools/parameters/__init__.py", line 131, in callback_helper
    new_value = callback(**args)
  File "lib/galaxy/tools/evaluation.py", line 71, in validate_inputs
    value = input.from_json(value, request_context, context)
  File "lib/galaxy/tools/parameters/basic.py", line 905, in from_json
    raise ValueError("An invalid option was selected for %s, %r, please verify." % (self.name, value))
ValueError: An invalid option was selected for dbkey, 'grch38_core bs_controls', please verify.
</pre>

I think the form should probably be escaping such character to avoid it bering turned into a space.

This is important since some tools check to be sure that the dbkeys match between aligned reads and other files.

**Comment by mvdbeek** [comment]
@bwlang  We did fix some escaping things recently. I've tried regular uploads, imports from the data library interface, running data managers, mapping jobs etc for a dbkey with a `+`, this all seems to work fine on 19.05. If this happens again let us know how to reproduce this.
