### ISSUE TITLE
Tool migration checks at startup do not read the correct Galaxy config file when not using PasteDeploy

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#7273]
The Galaxy config file to read for determining the `database_connection` for tool migration is pulled from the `global_conf` kwarg (it's a dict) key `__file__` in `app.py`, but `global_conf` is automatically passed by PasteDeploy and does not exist under uWSGI. So the tool migration check is working from the default config and attempting to open `database/universe.sqlite`, which does not exist and it cannot create when running with privilege separation.

### Example of how to reproduce

- Galaxy owned by root in `/srv/galaxy/server`
- Galaxy config owned by root in `/srv/galaxy/config/galaxy.yml`
- Start Galaxy for the first time in cwd `/srv/galaxy/server` with `uwsgi --yaml ../config/galaxy.yml`

### Workarounds

- Disable the `check_migrate_tools` Galaxy config opt
- Maybe (untested, but no `global_conf` is I believe why I added these options) in the `uwsgi` section of `galaxy.yml`:
    ```yaml
    uwsgi:
      set: galaxy_config_file=/srv/galaxy/config/galaxy.yml
      set: galaxy_root=/srv/galaxy/server
    ```
- Maybe (untested, should create `database/universe.sqlite` and satisfy the bug though):
    ```console
    sudo -iu <privsep user>
    cd /srv/galaxy/server
    . <path to venv>/bin/activate
    sh create_db.sh
    sh manage_db.sh upgrade tools'`
    ```

In addition to fixing the bug, I propose we disable `check_migrate_tools` by default in 19.01, this is code that nobody needs to run at this point and as far as I know we have no more tool migrations planned.

### Traceback

```pytb
Traceback (most recent call last):
  File "/srv/galaxy/server/lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/srv/galaxy/server/lib/galaxy/app.py", line 86, in __init__
    self._configure_models(check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "/srv/galaxy/server/lib/galaxy/config.py", line 1143, in _configure_models
    verify_tools(self, install_db_url, config_file, install_database_options)
  File "/srv/galaxy/server/lib/tool_shed/galaxy_install/migrate/check.py", line 65, in verify_tools
    raise Exception("Error attempting to update the value of migrate_tools.version: %s" % output)
Exception: Error attempting to update the value of migrate_tools.version: Traceback (most recent call last):
  File "./scripts/manage_db.py", line 24, in <module>
    invoke_migrate_main()
  File "./scripts/manage_db.py", line 20, in invoke_migrate_main
    main(repository=repo, url=db_url)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 342, in _migrate
    schema = ControlledSchema(engine, repository)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 45, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1287, in _do_get
    return self._create_connection()
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 674, in __connect
    connection = pool._invoke_creator(self)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/srv/galaxy/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
migrate.exceptions.DatabaseNotControlledError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by mvdbeek** [comment]
We've disabled the tool migrations by default in https://github.com/galaxyproject/galaxy/pull/7275. I doubt at this point you'll want to jump from a many year old setup to a current release, and if you do you'll have to migrate the tools at an older Galaxy version with a paste setup.
