### ISSUE TITLE
ToolShed - repositories I own/deprecated repositories I own - HTTP 500 Error

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#7304]
I was working on some of my tools. Then I tried to access the pages described in the title. Subsequently I came by the following error in a stack trace:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/routes/middleware.py", line 141, in __call__
    response = self.app(environ, start_response)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 143, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 222, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/webapps/tool_shed/controllers/repository.py", line 356, in browse_repositories_i_own
    return self.repositories_i_own_grid(trans, **kwd)
  File "lib/galaxy/webapps/reports/framework/grids.py", line 292, in __call__
    kwargs=kwargs)
  File "lib/galaxy/web/framework/webapp.py", line 927, in fill_template
    return self.fill_template_mako(filename, **kwargs)
  File "lib/galaxy/web/framework/webapp.py", line 940, in fill_template_mako
    return template.render(**data)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "GLXTS/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "GLXTS/.venv/local/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "GLXTS/database/compiled_templates/community/base.mako.py", line 69, in render_body
    __M_writer(unicode(next.body()))
  File "GLXTS/database/compiled_templates/community/legacy/grid_base.mako.py", line 81, in render_body
    __M_writer(unicode(self.load()))
  File "GLXTS/database/compiled_templates/community/legacy/grid_base.mako.py", line 109, in render_load
    __M_writer(unicode( h.dumps( self.get_grid_config( embedded=embedded, insert=insert ) ) ))
  File "GLXTS/database/compiled_templates/community/legacy/grid_base.mako.py", line 287, in render_get_grid_config
    value = column.get_value( trans, grid, item )
  File "lib/tool_shed/grids/repository_grids.py", line 119, in get_value
    rev_label, rev_date = option_items.split(' ')
ValueError: need more than 1 value to unpack
```

**Comment by martenson** [comment]
I think you need to reset metadata on the given repository. The option is available under the admin menu.

**Comment by selten** [comment]
That worked, however it would be nice if this would be handled in a better way than showing a HTTP 500 error

**Comment by martenson** [comment]
I suspect this happens when the metadata entries in the database do not correspond to the changeset in mercurial. Were you manipulating the hg repositories directly?

**Comment by selten** [comment]
What I actually did was the following:

- Tool couldn't be updated in ToolShed
- Rename tool to tool + _oldX
- Add it again with slightly different data (e.g. scripts)
- Rename this iteration to tool + _oldX
- Add it again with again different data (e.g. different/less scripts)
- This works again

After this the ToolShed had issues with the metadata

**Comment by martenson** [comment]
The best option here probably would be that toolshed should regenerate metadata on fail (once) and try again.

**Comment by martenson** [comment]
this is likely obsolete with the switch to TS2.0
