### ISSUE TITLE
building WSGI app fails when setting URL with subfolder

### ISSUE THREAD

**Issue by lcodo** [galaxyproject/galaxy#7378]
Galaxy release 19.01 installation in a clean ubuntu18 VM results in the following error when setting uWSGI  in galaxy.yml with `mount: /prefix=galaxy.webapps.galaxy.buildapp:uwsgi_app()`:

`config/galaxy.yml`
```
uwsgi:
  socket: unix:///srv/galaxy/var/uwsgi.sock
  mount: /galaxy-devel=galaxy.webapps.galaxy.buildapp:uwsgi_app()
  manage-script-name: true
```
`./run.sh`
```
[...]
galaxy.webapps.util DEBUG 2019-02-18 17:09:57,801 [p:7240,w:0,m:0] [MainThread] Enabling 'RequestIDMiddleware' middleware
galaxy.webapps.util DEBUG 2019-02-18 17:09:57,801 [p:7240,w:0,m:0] [MainThread] Enabling 'BatchMiddleware' middleware
galaxy.webapps.util WARNING 2019-02-18 17:09:57,802 [p:7240,w:0,m:0] [MainThread] 'wrap_in_static' is enabled in your configuration but the uWSGI application stack does not support it, this middleware has been disabled
galaxy.webapps.galaxy.buildapp DEBUG 2019-02-18 17:09:57,802 [p:7240,w:0,m:0] [MainThread] Prior to webapp return, Galaxy thread <_MainThread(MainThread, started 140704018896704)> is alive.
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0x55722bfbf2f0 pid: 7240 (default app)
mounting galaxy.webapps.galaxy.buildapp:uwsgi_app() on /galaxy-devel
added lib/ to pythonpath.
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 12, in <module>
    import galaxy.app
  File "lib/galaxy/app.py", line 12, in <module>
    from galaxy import config, jobs
  File "lib/galaxy/config.py", line 27, in <module>
    from galaxy.tools.deps.container_resolvers.mulled import DEFAULT_CHANNELS
  File "lib/galaxy/tools/__init__.py", line 32, in <module>
    from galaxy.tools.actions import DefaultToolAction
  File "lib/galaxy/tools/actions/__init__.py", line 14, in <module>
    from galaxy.tools.parameters.wrapped import WrappedParameters
  File "lib/galaxy/tools/parameters/wrapped.py", line 11, in <module>
    from galaxy.tools.wrappers import (
  File "lib/galaxy/tools/wrappers.py", line 9, in <module>
    from galaxy.util.none_like import NoneDataset
  File "lib/galaxy/util/none_like.py", line 5, in <module>
    from galaxy.datatypes.registry import Registry
  File "lib/galaxy/datatypes/registry.py", line 17, in <module>
    from . import (
  File "lib/galaxy/datatypes/binary.py", line 19, in <module>
    import pysam
  File "/home/user/galaxy-central/.venv/local/lib/python2.7/site-packages/pysam/__init__.py", line 47, in <module>
    ["SamtoolsError"] +\
NameError: name 'libctabixproxies' is not defined
unable to load app 1 (mountpoint='/galaxy-devel') (callable not found or import error)
```

Certainly, `.venv/local/lib/python2.7/site-packages/pysam/__init__.py` has the relevant module imports commented:
```
#import pysam.libctabixproxies as libctabixproxies
#from pysam.libctabixproxies import *
```

Uncomenting them allow WSGI correctly tobuild the application, yet the another error arises:
```
[...]
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x5567be3bc2f0 pid: 7461 (default app)
mounting galaxy.webapps.galaxy.buildapp:uwsgi_app() on /galaxy-devel
added lib/ to pythonpath.
[...]
galaxy.tools.toolbox.base DEBUG 2019-02-18 17:18:20,635 [p:7461,w:0,m:0] [MainThread] Loaded tool id: master2pgSnp, version: 1.0.0 into tool panel..
galaxy.tools.toolbox.base DEBUG 2019-02-18 17:18:20,635 [p:7461,w:0,m:0] [MainThread] Loading tool panel finished (21.315 ms)
galaxy.tools.deps DEBUG 2019-02-18 17:18:20,638 [p:7461,w:0,m:0] [MainThread] Unable to find config file './dependency_resolvers_conf.xml'
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 130, in __init__
    self._configure_toolbox()
  File "lib/galaxy/config.py", line 1073, in _configure_toolbox
    self.toolbox_search = galaxy.tools.search.ToolBoxSearch(self.toolbox, index_help)
  File "lib/galaxy/tools/search/__init__.py", line 50, in __init__
    self.storage, self.index = self._index_setup()
  File "lib/galaxy/tools/search/__init__.py", line 61, in _index_setup
    index = storage.create_index(self.schema)
  File "/home/user/galaxy-central/.venv/local/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 150, in create_index
    return indexclass.create(self, schema, indexname)
  File "/home/user/galaxy-central/.venv/local/lib/python2.7/site-packages/whoosh/index.py", line 425, in create
    TOC.create(storage, schema, indexname)
  File "/home/user/galaxy-central/.venv/local/lib/python2.7/site-packages/whoosh/index.py", line 611, in create
    toc.write(storage, indexname)
  File "/home/user/galaxy-central/.venv/local/lib/python2.7/site-packages/whoosh/index.py", line 699, in write
    raise TypeError("%s %s=%r" % (e, fieldname, field))
TypeError: can't pickle function objects description=TEXT(format=Positions(boost=1.0), scorable=True, stored=False, unique=None)
```

**Comment by mvdbeek** [comment]
There's an update to the required settings in https://github.com/galaxyproject/galaxy/pull/7216/, could you try following these and report back ?

**Comment by martenson** [comment]
also fwiw 19.01 has not yet been released

**Comment by lcodo** [comment]
Thank you so much for the quick answer! It works!
