### ISSUE TITLE
fix 2 failing -framework tests

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#744]
Full log: https://jenkins.galaxyproject.org/view/Tests/job/G-framework/4/console

```
FAIL: output_format ( output_format ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 289, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 73, in do_it
    raise e
JobOutputsError: Dataset metadata verification for [file_ext] failed, expected [fastqsolexa] but found [fastqsanger].
```

```
======================================================================
FAIL: output_format ( output_format ) > Test-2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 289, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 73, in do_it
    raise e
JobOutputsError: Dataset metadata verification for [file_ext] failed, expected [fastqillumina] but found [txt].
```

**Comment by martenson** [comment]
installed samtools on n2, now 3 tests are failing, the above two and

```
FAIL: compare_bam_as_sam ( compare_bam_as_sam ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 289, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 73, in do_it
    raise e
JobOutputsError: History item  different than expected, difference (using diff):
( /tmp/tmpZtcu66/tmpaSR218/new_files_path_ckRhAB/local_bam_converted_to_sam_SjShwu.sam v. /tmp/tmpZtcu66/tmpaSR218/new_files_path_ckRhAB/history_bam_converted_to_sam_du001X.sam )
--- local_file
+++ history_data
@@ -1,4 +1,4 @@
-@HD    VN:1.0  SO:unsorted
+@HD    VN:1.0  SO:coordinate
 @SQ    SN:chr10    LN:135374737
 @SQ    SN:chr10_random LN:113275
 @SQ    SN:chr11    LN:134452384
@@ -62,12 +62,12 @@
 @SQ    SN:chr15_random LN:784346
 @SQ    SN:chr16    LN:88827254
 HWI-EAS91_1_30788AAXX:1:1:1095:605 0   chrM    23  25  36M *   0   0   AAGCAAGNNACTGAAAATGCCTAGATGAGTATTCTT    IIIIIII""IIIIIIIIIIIIIIIEIIIIIIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:606:460  0   chrM    4552    25  36M *   0   0   TTAATTTNNATTATAATAACACTCACAATATTCATA    IIIIIII""IIIIIIIIIIIIIIIIII?I6IIIII6    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:1082:719 16  chrM    7191    25  36M *   0   0   TAAATTAACCCATACCAGCACCATAGANNCTCAAGA    <III0EII3+3I29I>III8AIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:1059:362 16  chrM    7348    25  36M *   0   0   GGCCACCAATGATACTGAAGCTACGAGNNTACCGAT    II/<)2IIIIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:799:192  16  chrM    8421    25  36M *   0   0   CCTGTAGCCCTAGCCGTGCGGCTAACCNNTAACATT    II%::I<IIIIIEIII8IIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:1746:1180    16  chrM    12013   25  36M *   0   0   CCTAAGCTTCAAACTAGATTACTTCTCNNTAATTTT    IIIIIIIIFIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
+HWI-EAS91_1_30788AAXX:1:1:1273:600 16  chrM    13855   25  36M *   0   0   GTATTAGACACCCATACCTCAGGATACNNCTCAGTA    IIIIIIIIIIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
 HWI-EAS91_1_30788AAXX:1:1:1650:1185    0   chrM    14956   25  36M *   0   0   ACCCCAGNNAACCCTCTCAGCACTCCCCCTCATATT    IIIIIII""IIIIIIIIIIII6IIIIIIIII5I-II    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:799:192  16  chrM    8421    25  36M *   0   0   CCTGTAGCCCTAGCCGTGCGGCTAACCNNTAACATT    II%::I<IIIIIEIII8IIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:1082:719 16  chrM    7191    25  36M *   0   0   TAAATTAACCCATACCAGCACCATAGANNCTCAAGA    <III0EII3+3I29I>III8AIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:1746:1180    16  chrM    12013   25  36M *   0   0   CCTAAGCTTCAAACTAGATTACTTCTCNNTAATTTT    IIIIIIIIFIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:606:460  0   chrM    4552    25  36M *   0   0   TTAATTTNNATTATAATAACACTCACAATATTCATA    IIIIIII""IIIIIIIIIIIIIIIIII?I6IIIII6    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:1059:362 16  chrM    7348    25  36M *   0   0   GGCCACCAATGATACTGAAGCTACGAGNNTACCGAT    II/<)2IIIIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
 HWI-EAS91_1_30788AAXX:1:1:1483:1161    16  chrM    15080   25  36M *   0   0   TCCTGATCCTAGCACTCATCCCCACCCNNCACATAT    HIIIIIFIIAIHIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
-HWI-EAS91_1_30788AAXX:1:1:1273:600 16  chrM    13855   25  36M *   0   0   GTATTAGACACCCATACCTCAGGATACNNCTCAGTA    IIIIIIIIIIIIIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
 HWI-EAS91_1_30788AAXX:1:1:1190:1283    16  chrM    15338   25  36M *   0   0   TATATCGCACATTACCCTGGTCTTGTANNCCAGAAA    EIII?-IIIIIAIIIIIIIIIIIIIII""IIIIIII    NM:i:1  X1:i:1  MD:Z:7N0N27
```

details: https://jenkins.galaxyproject.org/job/G-framework/5/console

**Comment by nsoranzo** [comment]
```
-@HD    VN:1.0  SO:unsorted
+@HD    VN:1.0  SO:coordinate
```

I think this is the problem.

**Comment by nsoranzo** [comment]
There is also:

```
ERROR: metadata_BCF ( metadata_bcf ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 289, in test_tool
    self.do_it( td )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/functional/test_toolbox.py", line 38, in do_it
    stage_data_in_history( galaxy_interactor, testdef.test_data(), test_history, shed_tool_id )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/base/interactor.py", line 39, in stage_data_in_history
    upload_wait()
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/base/interactor.py", line 280, in wait
    while not self.__history_ready( history_id ):
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/base/interactor.py", line 298, in __history_ready
    return self._state_ready( state, error_msg="History in error state." )
  File "/var/lib/jenkins/jobs/G-framework/workspace/test/base/interactor.py", line 357, in _state_ready
    raise Exception( error_msg )
Exception: History in error state.
```

which is due to:

```
galaxy.datatypes.metadata: DEBUG: setting metadata externally failed for HistoryDatasetAssociation 118: [Errno 2] No such file or directory: '/tmp/tmpZtcu66/tmpaSR218/job_working_directory_LAYSS5/000/91/__dataset_118_metadata_temp_file_hXSPtI.csi'
```

Do you have `bcftools` installed and in PATH?

**Comment by bgruening** [comment]
I guess he has it installed. We talked about this yesterday. It's very strange. If samtools and bcftools are installed this should not happen :(

**Comment by mvdbeek** [comment]
The samtools bam-sam comparison failures are probably due to how samtools is used in the test framework (./test/base/twilltestcase.py).
I noticed a similar problem using planemo shed_test, while planemo test was passing.
I'll see if I still have the patch concerning this.

**Comment by nsoranzo** [comment]
I've fixed the 2 output_format tests, will open a PR soon.

**Comment by mvdbeek** [comment]
OK, maybe the sam-to-bam comparison could be fixed with this https://gist.github.com/mvdbeek/20c04a5563ea021c9515 .
It helped for planemo shed_test when comparing bam outputs.
Should I do a seperate Issue and/or PR for this?

Edit: that was the wrong one, this is the one that fixed the tests:
https://gist.github.com/mvdbeek/91d6acb442e94a98519b

**Comment by nsoranzo** [comment]
> I guess he has it installed. We talked about this yesterday. It's very strange. If samtools and bcftools are installed this should not happen :(

I think this may be due to an old version of bcftools: bcftools < 1.0 creates a `.bci` index file, while bcftools >= 1.0 creates a `.csi` file. Does it make sense to support the old format?

**Comment by bgruening** [comment]
ping @davebx. He was working on the bcf file format as far as I know.

**Comment by martenson** [comment]
samtools and bcftools 0.1.19 are present

**Comment by martenson** [comment]
@nsoranzo I think we should support the old format.

**Comment by nsoranzo** [comment]
The `output_format` FAILs are fixed by #752. `metadata_BCF` should be fixed by updating bcftools to >= 1.0 .

**Comment by martenson** [comment]
re-running now

**Comment by martenson** [comment]
the output format fails are fixed (thanks @nsoranzo )
we now have 2 last fails:

```
 functional.test_toolbox.TestForTool_compare_bam_as_sam.test_tool_000000
 functional.test_toolbox.TestForTool_metadata_bam.test_tool_000000
```

details: https://jenkins.galaxyproject.org/job/G-framework/9/testReport/
the box is now running samtools 1.2

**Comment by martenson** [comment]
this seems fully resolved, thanks everyone
https://jenkins.galaxyproject.org/job/G-framework/
