### ISSUE TITLE
All workflow work stuck and constant Uncaught exception in exposed API method

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#7447]
Hello 

version: dev, 1 week old but tried with current before submitting ticket (just checked out ).

Part 1:
A couple of hours ago I tried to run a workflow that uses Trinity Abundance estimation with a collection 24 datasets. It never started the job but it stayed in the 'creating jobs' state:

![image](https://user-images.githubusercontent.com/608484/53682964-5e945180-3d4f-11e9-99c4-c4088fb90fd1.png)

This was a few hours ago. I tried selecting delete and then stopping the galaxy server process and restarted it but there was no difference no matter what I did.

Part 2:
Then i noticed that i cannot copy the history that contains this run. It reads : 

```
Uncaught exception in exposed API method
```

Part 3: 
Then i realised that I can run jobs but I cannot run or save any workflows for **any** user.
Here is an empty one with just the input dataset:

![image](https://user-images.githubusercontent.com/608484/53682986-b03cdc00-3d4f-11e9-9b0e-de627decb85d.png)

Importantly, no user can run any workflows. Restarting the server doesn't fix it.

Here is some part of the log file:
```
220.233.79.26 - - [03/Mar/2019:00:51:47 +1100] "GET /api/webhooks HTTP/1.1" 200 - "https://galaxy.gpi.westernsydney.edu.au/workflow/editor?id=79f88a7654569b51" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
galaxy.web.framework.decorators ERROR 2019-03-03 00:51:51,469 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 545, in update
    **from_dict_kwds
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 362, in update_workflow_from_raw_description
    **kwds
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 420, in _workflow_from_raw_description
    module, step = self.__module_from_dict(trans, steps, steps_by_external_id, step_dict, **kwds)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 1088, in __module_from_dict
    self.__set_default_label(step, module, step_dict.get('tool_state'))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 1203, in __set_default_label
    if util.unicodify(default_label).lower() not in ['input dataset', 'input dataset collection']:
AttributeError: 'NoneType' object has no attribute 'lower'
220.233.79.26 - - [03/Mar/2019:00:51:51 +1100] "PUT /api/workflows/79f88a7654569b51 HTTP/1.1" 500 - "https://galaxy.gpi.westernsydney.edu.au/workflow/editor?id=79f88a7654569b51" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
galaxy.web.framework.decorators ERROR 2019-03-03 00:51:57,570 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 545, in update
    **from_dict_kwds
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 362, in update_workflow_from_raw_description
    **kwds
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 420, in _workflow_from_raw_description
    module, step = self.__module_from_dict(trans, steps, steps_by_external_id, step_dict, **kwds)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 1088, in __module_from_dict
    self.__set_default_label(step, module, step_dict.get('tool_state'))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 1203, in __set_default_label
    if util.unicodify(default_label).lower() not in ['input dataset', 'input dataset collection']:
AttributeError: 'NoneType' object has no attribute 'lower'
```

Any ideas of how to move forward....? I've been banging my head for a couple of hours now.

I think it is related to that failed workflow run but i have no idea why it could cause so much trouble

I tried to look into the database but I don't know what to look for.

When I restart the galaxy process, this is the error I get every time:

```
Starting server in PID 3326.
serving on http://137.154.19.162:16039
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'is
oforms_counts_salmon'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'in
puts|right_input'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'in
puts|left_input'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'ge
nes_counts_salmon'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/execute.py", line 112, in worker
    execute_single_job(params)
TypeError: execute_single_job() takes exactly 2 arguments (1 given)

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/execute.py", line 112, in worker
    execute_single_job(params)
TypeError: execute_single_job() takes exactly 2 arguments (1 given)

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/execute.py", line 112, in worker
    execute_single_job(params)
TypeError: execute_single_job() takes exactly 2 arguments (1 given)

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/execute.py", line 112, in worker
    execute_single_job(params)
TypeError: execute_single_job() takes exactly 2 arguments (1 given)
```

thanks

**Comment by alpapan** [comment]
I don't know if this JSON helps...:

```
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T14:06:01.717125",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: genes counts",
type_id: "dataset_collection-4ee74ca3dd3d746c",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "b9b633d5c701ee1a",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T14:06:01.717120",
hid: 529,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/4ee74ca3dd3d746c",
collection_type: "list",
element_count: 24,
id: "4ee74ca3dd3d746c",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T14:06:01.664351",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: isoforms counts",
type_id: "dataset_collection-148c604a4ef51387",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "b9b633d5c701ee1a",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T14:06:01.664343",
hid: 528,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/148c604a4ef51387",
collection_type: "list",
element_count: 24,
id: "148c604a4ef51387",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T13:25:46.702039",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: genes counts",
type_id: "dataset_collection-f029ba6cb72a82dd",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "5f857394fe03da63",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T13:25:46.702033",
hid: 515,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/f029ba6cb72a82dd",
collection_type: "list",
element_count: 24,
id: "f029ba6cb72a82dd",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T13:25:46.646177",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: isoforms counts",
type_id: "dataset_collection-9a7f5488a8335e60",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "5f857394fe03da63",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T13:25:46.646169",
hid: 514,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/9a7f5488a8335e60",
collection_type: "list",
element_count: 24,
id: "9a7f5488a8335e60",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T13:19:19.958116",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: genes counts",
type_id: "dataset_collection-4d1cd5fe62bd4d30",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "9fb804d0e68f8dc8",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T13:19:19.958111",
hid: 513,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/4d1cd5fe62bd4d30",
collection_type: "list",
element_count: 24,
id: "4d1cd5fe62bd4d30",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T13:19:19.905708",
populated_state_message: null,
name: "Align reads and estimate abundance on collection 485 and collection 460: isoforms counts",
type_id: "dataset_collection-378929a692bd48f4",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: "9fb804d0e68f8dc8",
job_source_type: "ImplicitCollectionJobs",
create_time: "2019-03-02T13:19:19.905701",
hid: 512,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/378929a692bd48f4",
collection_type: "list",
element_count: 24,
id: "378929a692bd48f4",
populated_state: "new"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T11:41:57.800788",
populated_state_message: null,
name: "YA_RightReads",
type_id: "dataset_collection-1119f4dc104ab89b",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: null,
job_source_type: null,
create_time: "2019-03-02T11:41:57.800781",
hid: 485,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/1119f4dc104ab89b",
collection_type: "list",
element_count: 24,
id: "1119f4dc104ab89b",
populated_state: "ok"
},
{
history_content_type: "dataset_collection",
update_time: "2019-03-02T11:41:33.000714",
populated_state_message: null,
name: "YA_LeftReads",
type_id: "dataset_collection-c23ff84d4df3e66d",
deleted: false,
type: "collection",
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
visible: true,
job_source_id: null,
job_source_type: null,
create_time: "2019-03-02T11:41:33.000705",
hid: 460,
url: "/api/histories/c5bb8d0e0e1b243f/contents/dataset_collections/c23ff84d4df3e66d",
collection_type: "list",
element_count: 24,
id: "c23ff84d4df3e66d",
populated_state: "ok"
},
{
history_content_type: "dataset",
update_time: "2019-03-02T13:44:16.502903",
name: "YA10_R1",
extension: "fastqsanger",
type_id: "dataset-09d5a6643e835a9c",
deleted: false,
history_id: "c5bb8d0e0e1b243f",
tags: [ ],
id: "09d5a6643e835a9c",
visible: true,
state: "ok",
create_time: "2019-03-02T11:35:24.006516",
hid: 435,
url: "/api/histories/c5bb8d0e0e1b243f/contents/09d5a6643e835a9c",
dataset_id: "1b5dfd3b9762b925",
type: "file",
purged: false
},

[..]
```

**Comment by alpapan** [comment]
An update:
I purged the datasets using the helper scripts [https://galaxyproject.org/admin/config/performance/purge-histories-and-datasets/] but I still cannot launch workflows. ..

The error is:

```

/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'meta'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'copy_inputs_to_history'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
/scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'use_cached_job'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
```

**Comment by mvdbeek** [comment]
There's a couple of things going on here, let me start with the easy stuff:

---------

```
TypeError: execute_single_job() takes exactly 2 arguments (1 given)
```
This happens if you turn on `tool_submission_burst_threads` (i.e set it to a value higher than 1), this is currently broken and we need to remove it ASAP. If you comment this option or set it back to 1 that should go away, and is probably the source of the workflows not running.

-------

```
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/managers/workflows.py", line 1203, in __set_default_label
    if util.unicodify(default_label).lower() not in ['input dataset', 'input dataset collection']:
AttributeError: 'NoneType' object has no attribute 'lower'
```
This one's on me, while fixing another issue I broke this, I'll have a patch in a minute.

--------

> /scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'meta'. (this warning may be suppressed after 10 occurrences)
>   (util.ellipses_string(value),),
> /scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'copy_inputs_to_history'. (this warning may be suppressed after 10 occurrences)
>   (util.ellipses_string(value),),
> /scratch_cory/sysadmin/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:255: SAWarning: Unicode type received non-unicode bind param value 'use_cached_job'. (this warning may be suppressed after 10 occurrences)
>   (util.ellipses_string(value),),

This is not an error.

**Comment by alpapan** [comment]
You're a star!

Thanks for doing this over a weekend
a
