### ISSUE TITLE
Another lethal API exception

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#7450]
hello

branch: dev current

After running RNA-Star (from iuc) on a collection I get this error that prevents **any** tools from being selected:

Do you think this is a galaxy, my galaxy setup, or a iuc tool setup issue (well it does block **any** tool or job from being submitted if **that particular (rnastar) history is active** so i think it might be both?)?

(I admit i may have some configurations from a previous version of galaxy and may not have fully migrated.)

```
_identifer=vwfeb26jv7s&tool_version=3.38.3%2Bgalaxy1 HTTP/1.1" 500 - "https://galaxy.gpi.westernsydney.edu.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Flimma_voo
m%2Flimma_voom%2F3.38.3%2Bgalaxy1&version=3.38.3%2Bgalaxy1&__identifer=vwfeb26jv7s" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) C
hrome/72.0.3626.119 Safari/537.36"
galaxy.web.framework.decorators ERROR 2019-03-03 13:34:26,431 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 123, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/__init__.py", line 1905, in to_json
    self.populate_model(request_context, self.inputs, state_inputs, tool_model['inputs'])
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/__init__.py", line 1974, in populate_model
    tool_dict = input.to_dict(request_context)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/basic.py", line 1959, in to_dict
    match = dataset_collection_matcher.hdca_match(hdca)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/dataset_matcher.py", line 226, in hdca_match
    converted_ext, _ = datatypes_registry.find_conversion_destination_for_dataset_by_extensions(extension, formats)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/datatypes/registry.py", line 893, in find_conversion_destination_for_dataset_by_extensions
    self.log.warning("Datatype class not found for extension '%s', which is used as target for conversion from datatype '%s'" % (convert_ext, dataset.ext))
AttributeError: 'NoneType' object has no attribute 'ext'
220.233.79.26 - - [03/Mar/2019:13:34:26 +1100] "GET /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/goseq/goseq/1.34.0/build?version=1.34.0&__identifer=03njocaxd29c&tool_v
ersion=1.34.0 HTTP/1.1" 500 - "https://galaxy.gpi.westernsydney.edu.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fgoseq%2Fgoseq%2F1.34.0&version=1.34.0&__identife
r=03njocaxd29c" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
220.233.79.26 - - [03/Mar/2019:13:34:27 +1100] "GET /api/histories/ff7344b1cec45645/contents?details=ead207706e1dfae6%2Cab889561e9de6206%2C568156d3c66d9e47%2C22b0faf98
96a427f%2C01ee566d04021e12%2C1b99261ddbe89aba%2C8043c64c3388db08%2C12172def2da0438e%2Cbf1cff4a5da47131%2C8c70a232e82bf244%2C0ba1945268333247%2C106b933f0db1ded1%2C0badd
8f3d93ff385&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2019-03-03T02%3A34%3A22.000Z&qv=False&qv=False HTTP/1.1" 200 - "https://galaxy.gpi.westernsydney.edu
.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fgoseq%2Fgoseq%2F1.34.0&version=1.34.0&__identifer=03njocaxd29c" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWeb
Kit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
galaxy.web.framework.decorators ERROR 2019-03-03 13:34:27,704 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/webapps/galaxy/api/tools.py", line 123, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/__init__.py", line 1905, in to_json
    self.populate_model(request_context, self.inputs, state_inputs, tool_model['inputs'])
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/__init__.py", line 1953, in populate_model
    tool_dict = input.to_dict(request_context)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/grouping.py", line 708, in to_dict
    cond_dict["cases"] = list(map(nested_to_dict, self.cases))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/grouping.py", line 706, in nested_to_dict
    return input.to_dict(trans)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/grouping.py", line 726, in to_dict
    when_dict["inputs"] = list(map(input_to_dict, self.inputs.values()))
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/grouping.py", line 724, in input_to_dict
    return input.to_dict(trans)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/basic.py", line 1959, in to_dict
    match = dataset_collection_matcher.hdca_match(hdca)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/tools/parameters/dataset_matcher.py", line 226, in hdca_match
    converted_ext, _ = datatypes_registry.find_conversion_destination_for_dataset_by_extensions(extension, formats)
  File "/scratch_cory/sysadmin/galaxy/lib/galaxy/datatypes/registry.py", line 893, in find_conversion_destination_for_dataset_by_extensions
    self.log.warning("Datatype class not found for extension '%s', which is used as target for conversion from datatype '%s'" % (convert_ext, dataset.ext))
AttributeError: 'NoneType' object has no attribute 'ext'
220.233.79.26 - - [03/Mar/2019:13:34:27 +1100] "GET /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.6.0b-1/build?version=2.6.0b-1&__identifer=e6r1ongdcxj&tool_version=2.6.0b-1 HTTP/1.1" 500 - "https://galaxy.gpi.westernsydney.edu.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Frgrnastar%2Frna_star%2F2.6.0b-1&version=2.6.0b-1&__identifer=e6r1ongdcxj" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
```

**Comment by alpapan** [comment]
Hello

I managed to see what datasets were causing the problem: it is a collection of bam files. 

![image](https://user-images.githubusercontent.com/608484/53691234-8e823a00-3dcd-11e9-88c1-8cd9762a600a.png)

![image](https://user-images.githubusercontent.com/608484/53691241-9a6dfc00-3dcd-11e9-8115-ed3909c6cf8a.png)

![image](https://user-images.githubusercontent.com/608484/53691244-a5289100-3dcd-11e9-9440-9304a80fa9a2.png)

The error happens for any tool:

![image](https://user-images.githubusercontent.com/608484/53691254-ce492180-3dcd-11e9-8977-4a97d3ab41fc.png)

**Comment by mvdbeek** [comment]
I think this was a short-lived bug that we fixed some time ago. If you still see this after updating the instance let us know and we can troubleshoot this.
