### ISSUE TITLE
Pip version outdated causing run.sh to fail

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7489]
Experienced with @joachimwolff on 19.01, `sh run.sh` creates the virtualenv but crashes shortly on `pip config list` failing. The pip installed to his virtualenv was 18 (matching his system version) but needed to be increased manually (`. .venv/bin/activate; pip install -U pip`) to allow `sh run.sh` to complete successfully.

**Comment by nsoranzo** [comment]
Can you post the error message, if any?

Another pip-related issue that we may want to solve together with this is https://github.com/galaxyproject/galaxy/issues/7375 .

**Comment by hexylena** [comment]
```
ValueError: failed to parse CPython sys.version: '2.7.15rc1 (default, Nov 12 2018, 14:31:15) \n[GCC 7.3.0]'
----------------------------------------
Traceback (most recent call last):
  File "/home/wolffj/miniconda2/envs/_galaxy_/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 1087, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 964, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 1038, in _pip_config
    remove_from_env=["PIP_VERBOSE", "PIP_QUIET"],
  File "/home/wolffj/.local/lib/python2.7/site-packages/virtualenv.py", line 886, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /home/wolffj/src/galaxy/.venv/bin/python -m pip config list failed with error code 1
```

**Comment by nsoranzo** [comment]
`virtualenv` from conda seems to call code from `~/.local/`

I'd suggest to remove the `.venv` and `~/miniconda2/envs/_galaxy_` directories and try again. If that doesn't work, post the full log of `./run.sh` .
