### ISSUE TITLE
No permissions to rerun dataset despite being admin

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7503]
![image](https://user-images.githubusercontent.com/458683/54117474-c1898680-43e8-11e9-9ef4-c2d0f8d95562.png)

also looks like an unencoded ID but dunno if that is seen by normal users. Additionally the dataset access form is rendered like this, for some reason, making it unusable.

![image](https://user-images.githubusercontent.com/458683/54117633-28a73b00-43e9-11e9-8fd1-bcc4a1b7edec.png)

**Comment by hexylena** [comment]
Trying to make history public

```
galaxy.web.framework.decorators ERROR 2019-03-11 12:04:40,147 [p:1385141,w:3,m:0] [uWSGIWorker3Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 157, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/web/base/controller.py", line 1410, in sharing
    shared, skipped = self._make_members_public(trans, item)
  File "lib/galaxy/web/base/controller.py", line 1465, in _make_members_public
    log.warning("User without permissions tried to make dataset with id: %s public.").format(dataset.id)
AttributeError: 'NoneType' object has no attribute 'format'
```

(I've imported this history to my account, and tried to make my copy public)

![image](https://user-images.githubusercontent.com/458683/54119630-ba18ac00-43ed-11e9-8d27-fe05a41eea80.png)
