### ISSUE TITLE
Jobs not entering failed state when drmaa submission fails

### ISSUE THREAD

**Issue by ooobik** [galaxyproject/galaxy#7513]
Hello,
During some galaxy testing I did, our cluster had a "blip" and timed out. Now, as far as the user is concerned the job in galaxy stays in the gray "Waiting to run" state, while in actuality we get the error
```
Running command ['sudo', '-E', '/srv/galaxy/server/scripts/drmaa_external_runner.py', '--assign_all_groups', '38227', '/srv/galaxy/slurm/1050.jt_json'
galaxy.jobs.runners ERROR 2019-03-12 12:58:02,459 (1050) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "/srv/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 113, in run_next 
    method(arg)
  File "/srv/galaxy/server/lib/galaxy/jobs/runners/drmaa.py", line 210, in queue_job
    external_job_id = self.external_runjob(external_runjob_script, filename, pwent[2]).strip()
  File "/srv/galaxy/server/lib/galaxy/jobs/runners/drmaa.py", line 384, in external_runjob
    raise RuntimeError("External_runjob failed (exit code %s)\nChild process reported error:\n%s" % (str(exitcode), stderrdata))
RuntimeError: External_runjob failed (exit code 1)
Child process reported error:
Traceback (most recent call last):
  File "/srv/galaxy/server/scripts/drmaa_external_runner.py", line 138, in <module> 
    main()
  File "/srv/galaxy/server/scripts/drmaa_external_runner.py", line 129, in main
    jobId = s.runJob(jt)
  File "/usr/lib/python2.7/site-packages/drmaa/session.py", line 314, in runJob
    c(drmaa_run_job, jid, sizeof(jid), jobTemplate)
  File "/usr/lib/python2.7/site-packages/drmaa/helpers.py", line 302, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/usr/lib/python2.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
drmaa.errors.DrmCommunicationException: code 2: slurm_submit_batch_job error: Socket timed out on send/recv operation
```

Would be nice if the user saw that that job submission failed instead of waiting indefinitely. Tested on release_18.09

**Comment by ooobik** [comment]
Testing on 19.01 reveals this is fixed.
