### ISSUE TITLE
S3 objectstore cannot use job_working_directory that starts with "/" such as /tmp/job_working_directory

### ISSUE THREAD

**Issue by markxiao** [galaxyproject/galaxy#7649]
I am using 19.01. When I am trying with S3 objectstore, everything works fine with the default setup. When I set <extra_dir type="job_work" path="database/job_working_directory_s3"/> to something like <extra_dir type="job_work" path="/tmp/job_working_directory_s3"/>, which points to a directory outside of the Galaxy directory. I had the following error when trying to upload datasets:

galaxy.jobs.handler ERROR 2019-04-02 16:26:14,164 failure running job 11786
Traceback (most recent call last):
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 381, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 975, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 139, in put
    job_wrapper.enqueue()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1186, in enqueue
    self._set_object_store_ids(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1211, in _set_object_store_ids
    self._setup_working_directory(job=job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 897, in _setup_working_directory
    working_directory = self._create_working_directory(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 930, in _create_working_directory
    job, base_dir='job_work', dir_only=True, obj_dir=True)
  File "/opt/galaxy/lib/galaxy/objectstore/__init__.py", line 829, in create
    self.backends[0].create(obj, **kwargs)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 546, in create
    if not self.exists(obj, **kwargs):
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 520, in exists
    in_s3 = self._key_exists(rel_path)
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 381, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 975, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 139, in put
    job_wrapper.enqueue()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1186, in enqueue
    self._set_object_store_ids(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1211, in _set_object_store_ids
    self._setup_working_directory(job=job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 897, in _setup_working_directory
    working_directory = self._create_working_directory(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 930, in _create_working_directory
    job, base_dir='job_work', dir_only=True, obj_dir=True)
  File "/opt/galaxy/lib/galaxy/objectstore/__init__.py", line 829, in create
    self.backends[0].create(obj, **kwargs)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 546, in create
    if not self.exists(obj, **kwargs):
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 520, in exists
    in_s3 = self._key_exists(rel_path)
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 381, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 975, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 139, in put
    job_wrapper.enqueue()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1186, in enqueue
    self._set_object_store_ids(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1211, in _set_object_store_ids
    self._setup_working_directory(job=job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 897, in _setup_working_directory
    working_directory = self._create_working_directory(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 930, in _create_working_directory
    job, base_dir='job_work', dir_only=True, obj_dir=True)
  File "/opt/galaxy/lib/galaxy/objectstore/__init__.py", line 829, in create
    self.backends[0].create(obj, **kwargs)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 546, in create
    if not self.exists(obj, **kwargs):
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 520, in exists
    in_s3 = self._key_exists(rel_path)
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 381, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 975, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 139, in put
    job_wrapper.enqueue()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1186, in enqueue
    self._set_object_store_ids(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1211, in _set_object_store_ids
    self._setup_working_directory(job=job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 897, in _setup_working_directory
    working_directory = self._create_working_directory(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 930, in _create_working_directory
    job, base_dir='job_work', dir_only=True, obj_dir=True)
  File "/opt/galaxy/lib/galaxy/objectstore/__init__.py", line 829, in create
    self.backends[0].create(obj, **kwargs)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 546, in create
    if not self.exists(obj, **kwargs):
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 520, in exists
    in_s3 = self._key_exists(rel_path)
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 381, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/opt/galaxy/lib/galaxy/jobs/handler.py", line 975, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 139, in put
    job_wrapper.enqueue()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1186, in enqueue
    self._set_object_store_ids(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 1211, in _set_object_store_ids
    self._setup_working_directory(job=job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 897, in _setup_working_directory
    working_directory = self._create_working_directory(job)
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 930, in _create_working_directory
    job, base_dir='job_work', dir_only=True, obj_dir=True)
  File "/opt/galaxy/lib/galaxy/objectstore/__init__.py", line 829, in create
    self.backends[0].create(obj, **kwargs)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 546, in create
    if not self.exists(obj, **kwargs):
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 520, in exists
    in_s3 = self._key_exists(rel_path)
  File "/opt/galaxy/lib/galaxy/objectstore/s3.py", line 387, in _key_exists
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

I fixed it by commenting out lines 381 and 382 (if rel_path[0] == '/': raise) in s3.py, but not sure what this will impact.

**Comment by dannon** [comment]
This sounds eerily familiar -- @VJalili and @erasche, I think, ran into something similar recently?

**Comment by VJalili** [comment]
I think this PR: https://github.com/galaxyproject/galaxy/pull/7294

**Comment by mvdbeek** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/7294
