### ISSUE TITLE
Sort collection operation silently dies

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7668]
This is related to #1724.
The sort collection operation when sorting against a file silently dies when in a workflow.
Took me a bit to realize it was even the tool that was having the issue.
It isn't even in the galaxy log.

**Comment by innovate-invent** [comment]
To add to this, it also silently fails when the file does not meet its criteria. It throws an exception in the log but does not show it in the History.

```log
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1491, in handle_single_execution
    collection_info=collection_info,
  File "lib/galaxy/tools/__init__.py", line 1573, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/model_operations.py", line 59, in execute
    self._produce_outputs(trans, tool, out_data, output_collections, incoming=incoming, history=history, tags=preserved_tags)
  File "lib/galaxy/tools/actions/model_operations.py", line 73, in _produce_outputs
    tool.produce_outputs(trans, out_data, output_collections, incoming, history=history, tags=tags)
  File "lib/galaxy/tools/__init__.py", line 2866, in produce_outputs
    raise Exception(message % (data_lines, len(elements)))
Exception: Number of lines must match number of list elements (2), but file has 7 lines
```

Related: #6156
