### ISSUE TITLE
k8s runner can fall into handled exception 

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#7685]
Today I have seen on an instance (that has already handled more than 3,000 jobs, some of them with failures) the following error:

```
galaxy.jobs.runners ERROR 2019-04-08 09:04:46,664 Unhandled exception checking active jobs
Traceback (most recent call last):
  File "/export/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 599, in monitor
    self.check_watched_items()
  File "/export/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 626, in check_watched_items
    new_async_job_state = self.check_watched_item(async_job_state)
  File "/export/galaxy-central/lib/galaxy/jobs/runners/kubernetes.py", line 445, in check_watched_item
    elif failed > 0 and self.__job_failed_due_to_low_memory(job_state):
  File "/export/galaxy-central/lib/galaxy/jobs/runners/kubernetes.py", line 499, in __job_failed_due_to_low_memory
    pod = Pod(self._pykube_api, pods.response['items'][0])
IndexError: list index out of range
```

This is in the older version of the runner (18.05 and 19.01), but could still happen in the newer one.

**Comment by mvdbeek** [comment]
I guess it's this part that failed
```
pods.response['items'][0]
```
Do you know in what conditions `pods.response['items']` can be empty ?
Would it be sufficient just do something like
```
response_items = pods.response['items']
if not response items:
     return False
```
 ?

**Comment by pcm32** [comment]
Yes, I added some tidbit like that on my patch here. This is an strange error, I'm guessing it happened due to a job being deleted from the Kubernetes side, but we should be protected against it of course. It could also happen due to miscommunications with the API server, but I guess that should be catched higher up.

**Comment by mvdbeek** [comment]
Agreed, it's probably reasonable to assume in the absence of evidence to assume that the job didn't die due to low memory ?

**Comment by pcm32** [comment]
In general I see that check_watched_items in different runners is very easy to break, and possibly should be more defensive in handling errors and exceptions (and in getting out of the watched queue jobs that break it for some reason).
