### ISSUE TITLE
/api/genomes/[id] throws exception

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7729]
I haven't actually installed any genomes and am just using the default configuration.
The api endpoint currently fails with:

```sh
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 166, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 181, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/galaxy_venv/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/tool_deps/_conda/lib/python2.7/urlparse.py", line 409, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/galaxy_venv/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/remoteuser.py", line 92, in __call__
    return self.app(environ, start_response)
  File "/galaxy_venv/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 143, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 222, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 57, in call_and_format
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/genomes.py", line 44, in show
    rval = self.app.genomes.chroms(trans, dbkey=id, num=num, chrom=chrom, low=low)
  File "lib/galaxy/visualization/genomes.py", line 332, in chroms
    rval = genome.to_dict(num=num, chrom=chrom, low=low)
  File "lib/galaxy/visualization/genomes.py", line 121, in to_dict
    len_file_enumerate = enumerate(open(self.len_file))
TypeError: coercing to Unicode: need string or buffer, NoneType found
[pid: 459|app: 0|req: 404/806] 172.20.0.2 () {50 vars in 1158 bytes} [Fri Apr 12 16:47:14 2019] GET /api/genomes/16079/ => generated 0 bytes in 24 msecs (HTTP/1.0 500) 1 headers in 63 bytes (0 switches on core 3)
```

**Comment by nsoranzo** [comment]
Likely fixed by commit 94e2cc7fd75d6029afc4869a565b937261ba99f4 .
