### ISSUE TITLE
setting metadata for zipped sequences failures

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7753]
Get various errors related to setting metadata for zipped sequence files (which are all empty). I guess this might be solved by `try - except` just catching everything + testing manually before if the file exists and permissions are sufficient. 

I guess in part might also be the tools fault. Maybe I try force it to generate uncompressed sequence files and compress them manually with gzip...

```
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/output_collect.py", line 191, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "lib/galaxy/tools/parameters/output_collect.py", line 505, in populate_collection_elements
    hashes=hashes,
  File "lib/galaxy/tools/parameters/output_collect.py", line 418, in create_dataset
    primary_data.set_meta()
  File "lib/galaxy/model/__init__.py", line 2366, in set_meta
    return self.datatype.set_meta(self, **kwd)
  File "lib/galaxy/datatypes/sequence.py", line 665, in set_meta
    for line in in_file:
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
```

```
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/output_collect.py", line 191, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "lib/galaxy/tools/parameters/output_collect.py", line 505, in populate_collection_elements
    hashes=hashes,
  File "lib/galaxy/tools/parameters/output_collect.py", line 418, in create_dataset
    primary_data.set_meta()
  File "lib/galaxy/model/__init__.py", line 2366, in set_meta
    return self.datatype.set_meta(self, **kwd)
  File "lib/galaxy/datatypes/sequence.py", line 665, in set_meta
    for line in in_file:
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 332, in _read
    self._read_eof()
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x79b348b != 0x1c14af20L
```

```
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/output_collect.py", line 191, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "lib/galaxy/tools/parameters/output_collect.py", line 505, in populate_collection_elements
    hashes=hashes,
  File "lib/galaxy/tools/parameters/output_collect.py", line 418, in create_dataset
    primary_data.set_meta()
  File "lib/galaxy/model/__init__.py", line 2366, in set_meta
    return self.datatype.set_meta(self, **kwd)
  File "lib/galaxy/datatypes/sequence.py", line 665, in set_meta
    for line in in_file:
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/gzip.py", line 319, in _read
    uncompress = self.decompress.decompress(buf)
error: Error -3 while decompressing: invalid code lengths set
```

```
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/output_collect.py", line 191, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "lib/galaxy/tools/parameters/output_collect.py", line 505, in populate_collection_elements
    hashes=hashes,
  File "lib/galaxy/tools/parameters/output_collect.py", line 418, in create_dataset
    primary_data.set_meta()
  File "lib/galaxy/model/__init__.py", line 2366, in set_meta
    return self.datatype.set_meta(self, **kwd)
  File "lib/galaxy/datatypes/sequence.py", line 665, in set_meta
    for line in in_file:
  File "/gpfs1/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I also get warnings/errors if I unzip these files with `gunzip`

```
gzip: D_ITH_C.reverse.fq.gz: invalid compressed data--format violated

gzip: D_ITZ_A.forward.fq.gz: decompression OK, trailing garbage ignored

gzip: U_COR_12.forward.fq.gz: invalid compressed data--crc error

gzip: U_COR_12.forward.fq.gz: invalid compressed data--length error
```

**Comment by mvdbeek** [comment]
If those files are invalid I don't think there is anything Galaxy can or should do. That said also make sure you run on a recent commit of 19.01 -- fasta.gz files were broken until recently.

**Comment by mvdbeek** [comment]
xref https://github.com/galaxyproject/galaxy/pull/7682

**Comment by bernt-matthias** [comment]
I think https://github.com/galaxyproject/galaxy/pull/7682 because its neither uploaded or implicitly converted. Just gz files generated by a tool. 

Maybe I describe the effect of the error: 

- The job is reported as success
- An empty collection is the output

So the user has no indication that something failed .. But I guess that both would be fixed as well by disabling gz output for the tool (stacks in this case).

**Comment by bernt-matthias** [comment]
So, maybe the actual problem is that "auto discovered" collections become empty if metadata setting for some files fails.

**Comment by bernt-matthias** [comment]
Happened again with a slightly different message: 

```
galaxy.job_execution.output_collect ERROR 2020-06-19 02:31:20,726 [p:13987,w:0,m:1] [UnivaJobRunner.work_thread-0] Problem gathering output collection.
Traceback (most recent call last):
  File "lib/galaxy/job_execution/output_collect.py", line 157, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "lib/galaxy/model/store/discover.py", line 227, in populate_collection_elements
    created_from_basename=created_from_basename,
  File "lib/galaxy/model/store/discover.py", line 175, in create_dataset
    primary_data.set_meta()
  File "lib/galaxy/model/__init__.py", line 2616, in set_meta
    return self.datatype.set_meta(self, **kwd)
  File "lib/galaxy/datatypes/sequence.py", line 667, in set_meta
    for line in in_file:
  File "/software/easybuild-broadwell/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/gzip.py", line 289, in read1
    return self._buffer.read1(size)
  File "/software/easybuild-broadwell/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/software/easybuild-broadwell/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/software/easybuild-broadwell/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\xfa\x92')
```

Job is shown as successful, but collection is empty. Also it would be nice if the jobid would be shown in the error message.
