### ISSUE TITLE
I can't access to galaxy server

### ISSUE THREAD

**Issue by arturomarin** [galaxyproject/galaxy#7761]
Hello, I am completely new with Galaxy. Well in since I can installed it. When I start the Galaxy server with sh run.sh there is no problem:

```
Starting server in PID 955.
serving on http://localhost:8080
```

but, when I try access to the Galaxy server using different web browsers there are errors and I can see nothing

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    environ['request_id'] = uuid.uuid1().hex
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
[pid: 955|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 592 bytes} [Wed Apr 17 12:12:24 2019] GET / => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    environ['request_id'] = uuid.uuid1().hex
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
[pid: 955|app: 0|req: 2/2] 127.0.0.1 () {36 vars in 592 bytes} [Wed Apr 17 12:12:24 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 2)
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 80, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    environ['request_id'] = uuid.uuid1().hex
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/arturo/miniconda3/envs/_galaxy_/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
[pid: 955|app: 0|req: 3/3] 127.0.0.1 () {36 vars in 592 bytes} [Wed Apr 17 12:12:24 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
```

I am using a macOS 10.13.6 with Safari 12.1 and Firefox 66.0.3
Any suggestion?

**Comment by nsoranzo** [comment]
Thanks for the report. I think you are encountering this Python issue: https://bugs.python.org/issue32502

This should be fixed by upgrading your Python 2.7 in the Conda environment `/Users/arturo/miniconda3/envs/_galaxy_` to Python 2.7.16 (only available from the `default` channel, not yet on conda-forge https://github.com/conda-forge/python-feedstock/issues/257 ).

**Comment by arturomarin** [comment]
Please, Can you explain the commands that I need run?

**Comment by nsoranzo** [comment]
```
/Users/arturo/miniconda3/bin/conda install -n _galaxy_ 'python=2.7.16'
```

**Comment by arturomarin** [comment]
Thank you very much Nicola Soranzo, now Galaxy it is working.
