### ISSUE TITLE
encoding bytes in send_activation_email

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7809]
```
Traceback (most recent call last):
  File "lib/galaxy/managers/users.py", line 365, in send_activation_email
    util.send_mail(frm, to, subject, body, self.app.config)
  File "lib/galaxy/util/__init__.py", line 1436, in send_mail
    msg = email_mime_text.MIMEText(body.encode('ascii', 'replace'))
  File "/cvmfs/test.galaxyproject.org/deps/_conda/envs/_galaxy_/lib/python3.6/email/mime/text.py", line 34, in __init__
    _text.encode('us-ascii')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by nsoranzo** [comment]
Weird, I think `body` should be a `str`

**Comment by martenson** [comment]
this is the body as captured by the log:

https://gist.github.com/martenson/8c1882ecbebcba999c61bc214d0b6f3e
