### ISSUE TITLE
Old job unexpected finishing triggers deletion of newer job on multiple resubmissions of the same job

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#7820]
Using the cli runner with LSF I have noticed the following failure scenario when a job gets resubmitted twice (sequentially). 

- Job A runs with external identifier 1 and fails on a resubmit-able condition
- Job A is resubmitted with external identifier 2 on a different destination and fails on a resubmit-able condition
- Job A is resubmitted with external identifier 3. On Start of external identifier 3, check_watched_items enquires about the state Job A with external identifier 1, it doesn't find it, and marks Job A/1 as done, which in turn signals the finishing of Job A/3 which only started running. Because it is a user cancelation, Job A/3 gets marked as failed. Job A/2 also gets the same treatment, again triggering a finish signal for A/3.

You can see this from these logs, where A/1 is 2292/6149125, A/2 is 2292/6152223 and A/3 is 2292/6160157.
```
galaxy.jobs.runners.cli INFO 2019-04-25 01:26:48,515 [p:35980,w:2,m:0] [ShellRunner.work_thread-3] (2292) queued with identifier: 6160157
galaxy.jobs DEBUG 2019-04-25 01:26:48,515 [p:35980,w:2,m:0] [ShellRunner.work_thread-3] (2292) Persisting job destination (destination id: dynamic-lsf-large)
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:26:49,932 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6160157) state change: from new to queued
[pid: 35975|app: 0|req: 2292/4578] 10.7.35.87 () {38 vars in 630 bytes} [Thu Apr 25 01:38:43 2019] GET /api/histories/c333314861e68c5c?key=d6bfcf542103ec809d5f7c230b12788b => generated 2844 bytes in 198 msecs (HTTP/1.1 200) 3 headers in 124 bytes (1 switches on core 3)
[pid: 35980|app: 0|req: 2292/4588] 10.7.35.87 () {38 vars in 630 bytes} [Thu Apr 25 01:40:25 2019] GET /api/histories/c333314861e68c5c?key=d6bfcf542103ec809d5f7c230b12788b => generated 2844 bytes in 305 msecs (HTTP/1.1 200) 3 headers in 124 bytes (1 switches on core 0)
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:22,039 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6149125) job not found in batch state check
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:22,174 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6149125) state change: from error to ok
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:22,174 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6149125) job execution finished, running job wrapper finish method
galaxy.jobs.runners ERROR 2019-04-25 01:50:22,277 [p:35980,w:2,m:0] [ShellRunner.work_thread-2] (2292/6149125) Job output not returned from cluster: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.o'
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:22,468 [p:35980,w:2,m:0] [ShellRunner.work_thread-2] (2292/6160157) Terminated at user's request
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:32,925 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6160157) state change: from queued to error
galaxy.jobs.runners.cli DEBUG 2019-04-25 01:50:33,490 [p:35980,w:2,m:0] [ShellRunner.work_thread-1] (2292/6160157) User killed running job, but error encountered during termination: Job <6160157>: Job has already finished
galaxy.jobs.runners DEBUG 2019-04-25 01:50:34,749 [p:35980,w:2,m:0] [ShellRunner.work_thread-1] (2292/6160157) Unable to cleanup /nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.sh: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.sh'
galaxy.jobs.runners DEBUG 2019-04-25 01:50:34,783 [p:35980,w:2,m:0] [ShellRunner.work_thread-1] (2292/6160157) Unable to cleanup /nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.o: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.o'
galaxy.jobs.runners DEBUG 2019-04-25 01:50:34,809 [p:35980,w:2,m:0] [ShellRunner.work_thread-1] (2292/6160157) Unable to cleanup /nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.e: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.e'
galaxy.jobs.runners DEBUG 2019-04-25 01:50:34,844 [p:35980,w:2,m:0] [ShellRunner.work_thread-1] (2292/6160157) Unable to cleanup /nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.ec: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.ec'
galaxy.jobs.runners.cli DEBUG 2019-04-25 02:26:58,698 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6152223) job not found in batch state check
galaxy.jobs.runners.cli DEBUG 2019-04-25 02:26:59,007 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6152223) state change: from error to ok
galaxy.jobs.runners.cli DEBUG 2019-04-25 02:26:59,007 [p:35980,w:2,m:0] [ShellRunner.monitor_thread] (2292/6152223) job execution finished, running job wrapper finish method
galaxy.jobs.runners ERROR 2019-04-25 02:26:59,037 [p:35980,w:2,m:0] [ShellRunner.work_thread-0] (2292/6152223) Job output not returned from cluster: [Errno 2] No such file or directory: '/nfs/production3/ma/home/pmoreno/galaxy-lsf/galaxy-dev/database/jobs_directory/002/2292/galaxy_2292.o'
galaxy.jobs.runners.cli DEBUG 2019-04-25 02:26:59,168 [p:35980,w:2,m:0] [ShellRunner.work_thread-0] (2292/6160157) User killed running job, but error encountered during termination: Job <6160157>: Job has already finished
```

Would the resubmitted jobs need to be removed from the list of watched items once the subsequent job gets triggered? They seem to be to different Job objects (although the all have the same galaxy internal id), isn't it?

For some reason this doesn't happen when the second job A/2 gets submitted, but only with the third one. It consistently happens.

Thanks!

**Comment by pcm32** [comment]
If I avoid adding the job to the watched items here 

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/cli.py#L183

after being marked as failed, I get the following error on resubmission:

```
galaxy.jobs.runners ERROR 2019-04-25 16:33:02,531 [p:62995,w:1,m:0] [ShellRunner.work_thread-3] (2325) Failure preparing job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 223, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 869, in prepare
    self.__prepare_upload_paramfile(tool_evaluator)
  File "lib/galaxy/jobs/__init__.py", line 836, in __prepare_upload_paramfile
    shutil.move(tool_evaluator.param_dict['paramfile'], new)
  File "/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: SafeStringWrapper(unicode:__lt__class __sq__galaxy.tools.wrappers.ToolParameterValueWrapper__sq____gt__,__lt__class __sq__galaxy.util.object_wrapper.SafeStringWrapper__sq____gt__,__lt__class __sq__numbers.Number__sq____gt__,__lt__type __sq__NoneType__sq____gt__,__lt__type __sq__NotImplementedType__sq____gt__,__lt__type __sq__bool__sq____gt__,__lt__type __sq__bytearray__sq____gt__,__lt__type __sq__ellipsis__sq____gt__) object at d7fd050 on: u__sq__/galaxy-lsf/galaxy-dev/database/tmp/upload_params_yiIu7v__sq__
```

so that doesn't seem to be the way out....

**Comment by pcm32** [comment]
mmm, strange, not sure if the error above is actually related....

**Comment by pcm32** [comment]
The above error was a disk error that happened by coincidence. The issue is sorted by not adding the job to the watched items once it is marked as failed. PR'ing that now.
