### ISSUE TITLE
KubernetesJobRunner, how to catch failed jobs?

### ISSUE THREAD

**Issue by markxiao** [galaxyproject/galaxy#8134]
Hi, I am using 19.05 and testing its KubernetesJobRunner. I am testing how Galaxy would catch job errors with Kebernetes. I purposely failed a job by inserting some "raise" code in the job script. There is Error message in the stderr in the job summary. But Galaxy still shows the job as success (green). I also tried to add this:
```
  <stdio>
    <regex match="error"
           source="both"
           level="fatal"
           description="error encountered" />
  </stdio>
```
to the job xml file. The result is the same, the job is still shown as success even though it failed. Is there a way to catch failed jobs with KubernetesJobRunner? In the past, I use condor runner, it worked fine.

**Comment by bernt-matthias** [comment]
I have no experience with this runner, is there anything in the logs? 

The runners code is here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/kubernetes.py .. I guess that the functions `check_watched_item` and `_handle_job_failure` might be of interest. 

Stupid question is the string `error` actually contained in the output?

**Comment by markxiao** [comment]
The stderr is something like this:
`
Traceback (most recent call last):
  File "/opt/galaxy/tools/sr_mapping/bwa_wrapper.py", line 407, in <module>
    if __name__=="__main__": __main__()
  File "/opt/galaxy/tools/sr_mapping/bwa_wrapper.py", line 104, in __main__
    raise 
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType`

**Comment by mvdbeek** [comment]
@markxiao great that you got the kubernetes runner working. The tool you're testing with has long been deprecated and does not ship with Galaxy anymore, it may not be set up to detect this specific error from the stderr.

We test the stderr, stdout and exit code detection for the Kubernetes runner as part of the integration tests in https://github.com/galaxyproject/galaxy/blob/49757608de0a6809aad5af15445106c2bd7591fb/test/integration/test_kubernetes_runner.py

If you want to do a similar test against your Galaxy instance you can start Galaxy with the `GALAXY_CONFIG_OVERRIDE_TOOL_CONFIG_FILE="test/functional/tools/samples_tool_conf.xml" sh run.sh` or include `test/functional/tools/job_properties.xml` in your tool conf file.
You can then find the `job_properties` tool and set for instance the `The failure property` parameter to true and the job should properly fail.
