### ISSUE TITLE
k8s runner not collecting logs for failed job

### ISSUE THREAD

**Issue by ilveroluca** [galaxyproject/galaxy#8146]
Hi.  I'm running a job through the Kubernetes runner.  The job seems to fail improperly (I'm not sure it sets an appropriate error code), so there's a subsequent error as galaxy tries to assemble the output dataset.  The problem is that when the error occurs the runner doesn't collect the job logs, so nothing except "tool error. An error occurred with this dataset: Unable to finish job" is reported to the user.

Here's the exception traceback:

```
galaxy.jobs.handler DEBUG 2019-06-13 11:07:57,002 (1) Dispatching to k8s runner
galaxy.jobs DEBUG 2019-06-13 11:07:57,082 (1) Persisting job destination (destination id: None)
galaxy.jobs.runners DEBUG 2019-06-13 11:07:57,174 Job [1] queued (171.119 ms)
galaxy.jobs.handler INFO 2019-06-13 11:07:57,213 (1) Job dispatched
galaxy.jobs.runners.kubernetes DEBUG 2019-06-13 11:07:57,220 Starting queue_job for job 1
galaxy.jobs.command_factory INFO 2019-06-13 11:07:58,885 Built script [/export/galaxy-central/database/job_working_directory/000/1/tool_script.sh] for tool command [mtbls-dwnld  -q -T  -M  -H "/export/galaxy-central/database/files/000/dataset_1.dat" -o "/export/galaxy-central/database/job_working_directory/000/1/dataset_1_files"   "MTBLS855xx"]
galaxy.jobs WARNING 2019-06-13 11:08:04,773 Unable to generate primary composite file automatically for 1: [Errno 2] No such file or directory: '/export/galaxy-central/database/files/000/dataset_1_files'
galaxy.jobs.runners ERROR 2019-06-13 11:08:04,856 (1/galaxy-1) Job wrapper finish method failed
Traceback (most recent call last):
  File "/export/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 685, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/export/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 432, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/export/galaxy-central/lib/galaxy/jobs/__init__.py", line 1317, in finish
    dataset.set_peek()
  File "/export/galaxy-central/lib/galaxy/model/__init__.py", line 2166, in set_peek
    return self.datatype.set_peek(self)
  File "/export/galaxy-central/lib/galaxy/datatypes/isa.py", line 309, in set_peek
    raise RuntimeError("Unable to find the main file within the 'files_path' folder")
RuntimeError: Unable to find the main file within the 'files_path' folder
galaxy.tools.error_reports DEBUG 2019-06-13 11:08:05,099 Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x7f48d68e0f50> generated response None
```

I'm running Galaxy 18.01 on PhenoMeNal (which is admittedly a bit dated) but I have also reproduced the error with [a newer version of the k8s runner plugged into the installation](https://github.com/galaxyproject/galaxy/pull/6886), so this report might still be relevant with the current Galaxy version.

**Comment by ilveroluca** [comment]
The image of the tool I'm running:  `container-registry.phenomenal-h2020.eu/phnmnl/mtbls-dwnld:v4.1.3_cv2.0.34`.  To reproduce the error it's sufficient to ask the tool to download an inexistent metabolights dataset.

**Comment by mvdbeek** [comment]
It's not practical for us to use these images. We have tests in place that demonstrate proper reading of exit code and stderr, so this actually looks like a tool issue -- if a failing exit code is not a cause for tool failure (the old defaults) this will happen. If you want to convince yourself I'd recommend testing out the instructions I posted in https://github.com/galaxyproject/galaxy/issues/8134#issuecomment-501004963

**Comment by mvdbeek** [comment]
I should mention if that's the case the job will also not fail in any runner. If it does fail in other runners but not kubernetes I can take a look if you can tell m where to find the tool.
If it doesn't properly fail I'd recommend either setting `<command detect_errors="exit_code"/>` or setting the [profile attribute](https://docs.galaxyproject.org/en/latest/dev/schema.html#attributes) to something recent (> 16.04 should be fine for more sane defaults).

**Comment by ilveroluca** [comment]
I'm afraid I didn't explain myself properly.  I think the tool here wrongly reports success.  The Galaxy instance then rightly tries to execute the composite data type initialization code for the dataset (see `lib/galaxy/datatypes/isa.py`) which raises the exception.  In short, it looks like the runner doesn't collect the logs if there's an exception during the finalization of a successful job.

**Comment by mvdbeek** [comment]
I have understood that. But a failing exit code is unfortunately not always equivalent to a failed job.
And if the job properly fails we'll not collect the datasets.

As you said:

> I think the tool here wrongly reports success.

So the tool should be fixed, right ?

**Comment by ilveroluca** [comment]
The tool is besides the point; I just needed something to test my installation.

My point is that *I* would expect job logs to always be collected, regardless of the outcome of job execution or whether the tool is broken or even if doesn't implement tool interface properly. If on the other hand the expected behaviour is that logs are collected only when a tool works properly, then there is no problem and we can close the issue :-)

**Comment by mvdbeek** [comment]
> My point is that _I_ would expect job logs to always be collected, regardless of the outcome of job execution or whether the tool is broken or even if doesn't implement tool interface properly. If on the other hand the expected behaviour is that logs are collected only when a tool works properly, then there is no problem and we can close the issue :-)

That surely is also a problem, but that's not a Kubernetes issue then.

**Comment by mvdbeek** [comment]
And It'd really help if you could tell us which tool you're using, or at the very least how your command section looks like.

**Comment by ilveroluca** [comment]
Docker tool image:  container-registry.phenomenal-h2020.eu/phnmnl/mtbls-dwnld:v4.1.3_cv2.0.34

Tool definition: https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/develop/tools/phenomenal/w4m/mtbls-dwnld.xml

If it's of any use, I think you could reproduce the problem when any no op tool definition that defines an `isa-tab` output.  Let me know if I can help in any other way.

**Comment by mvdbeek** [comment]
Alright, thanks. Just to clarify: if you change https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/db052bbb0b7da5d76ef7723dfa0e9e5513061bc7/tools/phenomenal/w4m/mtbls-dwnld.xml#L2

to `<tool id="mtbls-dwnld" name="Metabolights downloader" version="4.1.3" profile="16.04">` you get the desired behavior ?

**Comment by ilveroluca** [comment]
Just tested.  No change.
