### ISSUE TITLE
Jobs dispatched to misconfigured pulsar queue do not error properly

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8158]
```
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: galaxy.jobs.runners ERROR 2019-06-17 10:50:55,676 (5422770) Unhandled exception calling queue_job
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: Traceback (most recent call last):
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 130, in run_next
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: method(arg)
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: File "/opt/galaxy/server/lib/galaxy/jobs/runners/pulsar.py", line 273, in queue_job
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: self._populate_parameter_defaults(job_destination)
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: File "/opt/galaxy/server/lib/galaxy/jobs/runners/pulsar.py", line 430, in _populate_parameter_defaults
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: raise Exception("Pulsar destination does not define required parameter %s" % key)
Jun 17 10:50:55 sn04.bi.uni-freiburg.de python[3627432]: Exception: Pulsar destination does not define required parameter jobs_directory
```

they just continue to report queued in the database.

**Comment by mvdbeek** [comment]
So these stay in new state but should fail, right ?

**Comment by hexylena** [comment]
They hung out in queued state for a while until we manually killed them.
