### ISSUE TITLE
Log message: unable to fail job

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8171]
```
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: galaxy.jobs.handler ERROR 2019-06-18 10:35:00,649 (5412255) Caught exception while attempting to fail job.
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: Traceback (most recent call last):
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/handler.py", line 475, in __filter_jobs_with_invalid_input_states
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: job_wrapper.fail(fail_message)
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1021, in fail
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: for dataset_path in self.get_output_fnames():
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1647, in get_output_fnames
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: self.compute_outputs()
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1661, in compute_outputs
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: dataset_path_rewriter = self.dataset_path_rewriter
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 731, in dataset_path_rewriter
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: return self._job_dataset_path_rewriter
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 724, in _job_dataset_path_rewriter
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: self._dataset_path_rewriter = OutputsToWorkingDirectoryPathRewriter(self.working_directory)
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 922, in working_directory
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: job, base_dir='job_work', dir_only=True, obj_dir=True)
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 558, in get_filename
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 768, in _call_method
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: % (method, self._repr_object_for_exception(obj), str(kwargs)))
Jun 18 10:35:00 sn04.bi.uni-freiburg.de python[3848076]: ObjectNotFound: objectstore, _call_method failed: get_filename on Job(id=5412255), kwargs: {'obj_dir': True, 'dir_only': True, 'base_dir': 'job_work'}
```

Not sure this should stop the job from being failed?

**Comment by mvdbeek** [comment]
Yeah, that shouldn't happen. I think that occurs when a jobs' input dataset(s) are deleted before the job starts.
