### ISSUE TITLE
Use of walltime limit can raise TypeError

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#8190]
Using this job_conf.xml:

```xml
<?xml version="1.0"?>
<job_conf>
    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
    </plugins>
    <destinations>
        <destination id="local" runner="local"/>
    </destinations>
    <limits>
        <limit type="walltime">24:00:00</limit>
        <limit type="total_walltime" window="30">24:00:00</limit>
    </limits>
</job_conf>
```

Results in this exception:

```pytb
galaxy.jobs DEBUG 2019-06-18 16:45:41,086 [p:1745,w:1,m:0] [JobHandlerQueue.monitor_thread] (39909) Working directory for job is: /galaxy_share/database/job_working_directory1/039/39909
galaxy.jobs.handler ERROR 2019-06-18 16:45:41,591 [p:1745,w:1,m:0] [JobHandlerQueue.monitor_thread] failure running job 39909
Traceback (most recent call last):
  File "lib/galaxy/jobs/handler.py", line 326, in __monitor_step
    job_state = self.__check_job_state(job)
  File "lib/galaxy/jobs/handler.py", line 400, in __check_job_state
    state, job_destination = self.__verify_job_ready(job, job_wrapper)
  File "lib/galaxy/jobs/handler.py", line 472, in __verify_job_ready
    time_spent += finished - started
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

Presumably the conditions inside this loop are not met or `job.state_history` is empty [here](https://github.com/galaxyproject/galaxy/blob/fda02672a5fef35a8ba097a7a74d2f8929d6d814/lib/galaxy/jobs/handler.py#L573).

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/11876 :)
