### ISSUE TITLE
can't import data that is not accessible by the galaxy system user

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8217]
The issue title might seem nonsensical, but it makes perfect sense in settings where jobs run as real user.

When adding files (that is links to files of the user which can't be accessed by the galaxy system user) to a user library the following shows up in the logs: 

```
galaxy.jobs.runners ERROR 2019-06-24 12:33:03,516 [p:73571,w:0,m:1] [UnivaJobRunner.work_thread-2] (31633/5309256) Job wrapper finish method failed
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 509, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "lib/galaxy/jobs/__init__.py", line 1393, in finish
    dataset.set_peek()
  File "lib/galaxy/model/__init__.py", line 2536, in set_peek
    return self.datatype.set_peek(self)
  File "lib/galaxy/datatypes/proteomics.py", line 115, in set_peek
    dataset.peek = data.get_file_peek(dataset.file_name)
  File "lib/galaxy/datatypes/data.py", line 1053, in get_file_peek
    with compression_utils.get_fileobj(file_name, "U") as temp:
  File "lib/galaxy/util/compression_utils.py", line 30, in get_fileobj
    return get_fileobj_raw(filename, mode, compressed_formats)[1]
  File "lib/galaxy/util/compression_utils.py", line 56, in get_fileobj_raw
    return compressed_format, io.open(filename, mode, encoding='utf-8')
IOError: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/library_import_user/USERMAILADDRESS/test2/FILENAME.mzML'
```

In this case `/gpfs1/data/galaxy_server/library_import_user/USERMAILADDRESS/test2/FILENAME.mzML` is a symbolic link to a file which is not accessible by the Galaxy system user.

This adds to the list of errors happening when jobs run as real user: https://github.com/galaxyproject/galaxy/issues/4308, https://github.com/galaxyproject/galaxy/issues/4325 and to an issue that the files are not visible in the library UI: https://github.com/galaxyproject/galaxy/issues/6407

**Comment by bernt-matthias** [comment]
More recent Traceback

```
Traceback (most recent call last):
  File "lib/galaxy/jobs/__init__.py", line 1494, in _finish_dataset
    dataset.set_peek(line_count=line_count)
TypeError: set_peek() got an unexpected keyword argument 'line_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 521, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "lib/galaxy/jobs/__init__.py", line 1605, in finish
    dataset_assoc.name, dataset, job, context, final_job_state, remote_metadata_directory
  File "lib/galaxy/jobs/__init__.py", line 1497, in _finish_dataset
    dataset.set_peek()
  File "lib/galaxy/model/__init__.py", line 2609, in set_peek
    return self.datatype.set_peek(self)
  File "lib/galaxy/datatypes/sequence.py", line 118, in set_peek
    dataset.peek = data.get_file_peek(dataset.file_name)
  File "lib/galaxy/datatypes/data.py", line 1082, in get_file_peek
    with compression_utils.get_fileobj(file_name, "U") as temp:
  File "lib/galaxy/util/compression_utils.py", line 30, in get_fileobj
    return get_fileobj_raw(filename, mode, compressed_formats)[1]
  File "lib/galaxy/util/compression_utils.py", line 61, in get_fileobj_raw
    return compressed_format, io.open(filename, mode, encoding='utf-8')
PermissionError: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/library_import_user/USERNAME/DIR/LINK.fastq.gz'
```

**Comment by bernt-matthias** [comment]
Guess this is by design.

Modern file sources are a good solution.
