### ISSUE TITLE
OIDC Registered accounts do not create a default private role

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8244]
This was noticed today when one of our users was testing things under their AAI account and could not edit a dataset.

Old accounts which were created, and later linked with OIDC:

```
galaxy=> select user_id, username from oidc_user_authnz_tokens ouat left join galaxy_user on ouat.user_id = galaxy_user.id where ouat.user_id in (select user_id from user_role_association);
 user_id |     username
---------+------------------
     625 | hrasche
       7 | bgruening
     693 | xxx
    2014 | xxx
     937 | xxx
     922 | xxx
    1737 | xxx
    5741 | xxx
    3982 | xxx
(9 rows)
```

On the other hand, all of these new accounts are not mentioned anywhere in the role table:

```
galaxy=> select user_id, username from oidc_user_authnz_tokens ouat left join galaxy_user on ouat.user_id = galaxy_user.id where ouat.user_id not in (select user_id from user_role_association);
 user_id |             username
---------+----------------------------------
    6516 | 8d34ab8d5c6a49f18fea36c031cbcd2f
    6517 | 87d25cda700e42fa917c60bb142e8c3a
    6520 | f71d363e996343cf851156c4cf728134
    6522 | 950c76b1f43c47498fc3910df6ed6fc3
    6528 | 31534e147b6e41a2b4e904a90bcc401a
    6534 | daf357b5cca7435f96617209201f6379
    6536 | cfb38b7c56764d708d228f12c04971dd
    6550 | 3700222f854c401797c3732ecb7a8694
    6551 | 051073b7687f4e93a570868ff26908c2
    6555 | f1f0cc27b42346359ae65583c82dc597
    6571 | ebfc0310b05e48779ead55b018a7892a
    6573 | b7c05b38b67f4c72843f79e9cb6e70bf
    6592 | 5dbf7f05329e49c98b31243b5f35045c
    6593 | 4253fe85232346a88b19042b05c591a8
    6598 | bb4b786d24264d5ab74b92ab497df4c2
    6633 | f75a6269116247748b3c148dceab720c
    6634 | 874b21dd730840108dc8d0afc8830134
    6638 | 83db107e89ed41cfa9895c789ee6ddfb
    6649 | b8ef5f469fed4f6aa9b8038c4ee656b7
    6665 | b01f118c90854791b61aea52a684caf2
    6701 | 664bbb5a1aa6484e86650e0fb278cd73
(21 rows)
```

Since they do not have a private role, they also don't have a `default_history_permissions`, nor `default_user_permissions`

```
galaxy=> select * from default_user_permissions where user_id in (select user_id from oidc_user_authnz_tokens ouat where ouat.user_id not in (select user_id from user_role_association));
 id | user_id | action | role_id
----+---------+--------+---------
(0 rows)
```

The end result that editing datasets is impossible as the controller responsible tries to serialise a None object. I don't think the assumption there is wrong, my gut says it is wrong that they don't have a default role.

```
galaxy.web.framework.decorators ERROR 2019-06-28 11:34:49,594 [p:3710196,w:3,m:0] [uWSGIWorker3Core0] Uncaught exception in exposed API method:                                                                                                Traceback (most recent call last):
File "lib/galaxy/web/framework/decorators.py", line 157, in decorator
rval = func(self, trans, *args, **kwargs)                                                                                                                                                                                                      File "lib/galaxy/webapps/galaxy/controllers/dataset.py", line 268, in get_edit
all_roles = [(r.name, trans.security.encode_id(r.id)) for r in trans.app.security_agent.get_legitimate_roles(trans, data.dataset, 'root')]
File "lib/galaxy/model/security.py", line 214, in get_legitimate_roles                                                                                                                                                                         return self.get_all_roles(trans, cntrller)
File "lib/galaxy/model/security.py", line 80, in get_all_roles                                                                                                                                                                                 return self.sort_by_attr([role for role in roles], 'name')
File "lib/galaxy/model/security.py", line 46, in sort_by_attr                                                                                                                                                                                  intermed = [(getattr(v, attr), i, v) for i, v in enumerate(seq)]
AttributeError: 'NoneType' object has no attribute 'name'
ww.xx.yy.zz - - [28/Jun/2019:11:34:49 +0200] "GET /datason et/get_edit?dataset_id=11ac94870d0bb33ae56dabba5ce5c93a HTTP/1.1" 500 - "https://usegalaxy.eu/datasets/edit?dataset_id=11ac9
```

Noticed thanks to a bug @gmauro reproduced which I had dismissed when I saw it on our test server.

**Comment by hexylena** [comment]
These also present as the *only* rows in dataset_permissions with a null role ID. We should probably add a `NOT NULL` constraint to that or?

```
galaxy=> select * from dataset_permissions where role_id is null;
    id    |        create_time         |        update_time         |       action       | dataset_id | role_id
----------+----------------------------+----------------------------+--------------------+------------+---------
 18283614 | 2019-06-28 09:23:48.104502 | 2019-06-28 09:23:48.104518 | manage permissions |    9876936 |
 18283549 | 2019-06-28 09:16:18.053338 | 2019-06-28 09:16:18.053352 | manage permissions |    9876894 |
...
```

**Comment by hexylena** [comment]
I have added two functions to [`gxadmin`](https://github.com/usegalaxy-eu/gxadmin) to help fix this.

- https://github.com/usegalaxy-eu/gxadmin/blob/master/docs/README.mutate.md#mutate-oidc-role-fix
- https://github.com/usegalaxy-eu/gxadmin/blob/master/docs/README.mutate.md#mutate-oidc-role-find-affected

Which we at EU are running regularly with:

```bash
for user in $(gxadmin mutate oidc-role-find-affected); do 
    gxadmin mutate oidc-role-fix $user;
done;
```
