### ISSUE TITLE
setting a tag "t=6" produces a 500 error on main

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#8255]
"time=6" works fine

**Comment by bwlang** [comment]
I just discovered this issue when working with new galaxy user

**Comment by hexylena** [comment]
Reproduced on EU.

```pytb
galaxy.web.framework.decorators ERROR 2019-07-02 17:57:37,217 [p:2508760,w:2,m:0] [uWSGIWorker2Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
rval = func(self, trans, *args, **kwargs)
File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 670, in update
return self.__update_dataset(trans, history_id, id, payload, **kwd)
File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 684, in __update_dataset
self.__deserialize_dataset(hda, payload, trans)
File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 711, in __deserialize_dataset
self.hda_deserializer.deserialize(hda, payload, user=trans.user, trans=trans)
File "lib/galaxy/managers/base.py", line 745, in deserialize
new_dict[key] = self.deserializers[key](item, key, val, **context)
File "lib/galaxy/managers/taggable.py", line 93, in deserialize_tags
_tags_from_strings(item, self.app.tag_handler, new_tags_list, user=user)
File "lib/galaxy/managers/taggable.py", line 43, in _tags_from_strings
tag_handler.apply_item_tags(user, item, unicodify(new_tags_str, 'utf-8'))
File "lib/galaxy/model/tags.py", line 187, in apply_item_tags
self.apply_item_tag(user, item, name, value)
File "lib/galaxy/model/tags.py", line 151, in apply_item_tag
lc_name = name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
