### ISSUE TITLE
if a stale link matches pattern discovery of collection elements fails but tool is successful

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8259]
This bug https://github.com/galaxyproject/tools-iuc/issues/2479 is caused by a link to a non-existent file that is created by the tool. The discovery pattern matches to the link which leads to the following Trace:

```
Problem gathering output collection.
Traceback (most recent call last):
  File "/tmp/tmp2nvvlcsf/galaxy-dev/lib/galaxy/tools/parameters/output_collect.py", line 155, in collect_dynamic_outputs
    metadata_source_name=output_collection_def.metadata_source,
  File "/tmp/tmp2nvvlcsf/galaxy-dev/lib/galaxy/model/store/discover.py", line 219, in populate_collection_elements
    hashes=hashes,
  File "/tmp/tmp2nvvlcsf/galaxy-dev/lib/galaxy/model/store/discover.py", line 126, in create_dataset
    self.object_store.update_from_file(primary_data.dataset, file_name=filename, create=True)
  File "/tmp/tmp2nvvlcsf/galaxy-dev/lib/galaxy/objectstore/__init__.py", line 493, in update_from_file
    raise ex
IOError: [Errno 2] No such file or directory: '/tmp/tmp2nvvlcsf/job_working_directory/000/11/working/stacks_outputs/batch_1.genotypes.tsv'
```

The job itself is successful but the collection is empty (even if other discover pattern .. even from other `discover_datasets` tags are successful).

Bug in the tool needs a fix. The actual galaxy bug is that either 
- the job should be marked as failed (which seems to be the preference of @jmchilton) or
- at least the other data sets should be added to the collection (plus a warning in the logs)

**Comment by nsoranzo** [comment]
I agree with John, I think we need to catch the exception and fail the job.
