### ISSUE TITLE
Argument list too Long

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/galaxy#8340]
Argument list too long" error when using bioblend:
Function call:

```
from bioblend import galaxy
gi = galaxy.GalaxyInstance(args.url, args.key)
gID = gi.libraries.get_folders(libID, name = var)

```

produces a set_meta job with extremely long argument list
```
galaxy.jobs.runners DEBUG 2019-07-15 14:10:33,635 [p:115540,w:0,m:1] [DRMAARunner.monitor_thread] executing external set_meta script for job
xport PATH=$PATH:'/sc1/groups/md/RMS/galaxy/database/dependencies/_conda/envs/__bcftools@1.5/bin' &&GALAXY_LIB="/sc1/groups/md/RMS/galaxy/lib"; if [ "$GALAXY_LIB" != "None" ]; then if [ -n "$PYTHONPATH" ]; then PYTHONPATH="$GALAXY_LIB:$PYTHONPATH"; else PYTHONPATH="$GALAXY_LIB"; fi; export PYTHONPATH; fi; GALAXY_VIRTUAL_ENV="/sc1/groups/md/RMS/galaxy/.venv"; if [ "$GALAXY_VIRTUAL_ENV" != "None" -a -z "$VIRTUAL_ENV" -a -f "$GALAXY_VIRTUAL_ENV/bin/activate" ]; then . "$GALAXY_VIRTUAL_ENV/bin/activate"; fi; python "/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/set_metadata_lceqEE.py" "/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/registry.xml" "/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/working/galaxy.json" "/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/metadata_in_LibraryDatasetDatasetAssociation_122878_0E8xxu,/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/metadata_kwds_LibraryDatasetDatasetAssociation_122878_WxvmHk,/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/metadata_out_LibraryDatasetDatasetAssociation_122878_duDm83,/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/metadata_results_LibraryDatasetDatasetAssociation_122878_4n5yWG,/sc1/groups/md/RMS/miseq/current/190712_M00206_0287_000000000-D6NYY/Data/Intensities/BaseCalls/L001/C163.1/s_1_1102.bcl,/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85426/metadata_override_LibraryDatasetDatasetAssociation_122878_qzpcO4"....
.
.

galaxy.jobs.runners ERROR 2019-07-15 13:37:36,160 [p:115540,w:0,m:1] [DRMAARunner.monitor_thread] Unhandled exception checking active jobs
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 599, in monitor
    self.check_watched_items()
  File "lib/galaxy/jobs/runners/drmaa.py", line 298, in check_watched_items
    if self._complete_terminal_job(ajs, drmaa_state=state) is not None:
  File "lib/galaxy/jobs/runners/drmaa.py", line 240, in _complete_terminal_job
    self._handle_metadata_externally(ajs.job_wrapper, resolve_requirements=True)
  File "lib/galaxy/jobs/runners/__init__.py", line 314, in _handle_metadata_externally
    preexec_fn=os.setpgrp)
  File "/sc1/apps/spack/v1.1.0/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-2.7.15-zgxjro5h32atmovyoxbj3veg5kybs7xu/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/sc1/apps/spack/v1.1.0/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-2.7.15-zgxjro5h32atmovyoxbj3veg5kybs7xu/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

```

```

**Comment by nsoranzo** [comment]
I don't think that this error is due to the BioBlend call `get_folders()`, which doesn't submit any jobs.

**Comment by dwightkuo** [comment]
The only other calls are to these functions:
```
libs = gi.libraries.get_libraries(name = LibName, deleted = False)
....
s = gi.libraries.create_library(LibName)
```

**Comment by dwightkuo** [comment]
Making the user an admin user fixes this problem
