### ISSUE TITLE
Caught exception while attempting to fail job

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8411]
```
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: galaxy.jobs.handler ERROR 2019-08-05 13:57:49,190 (5658189) Caught exception while attempting to fail job.
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: Traceback (most recent call last):
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/handler.py", line 476, in __filter_jobs_with_invalid_input_states
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: job_wrapper.fail(fail_message)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1021, in fail
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: for dataset_path in self.get_output_fnames():
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1650, in get_output_fnames
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: self.compute_outputs()
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1664, in compute_outputs
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: dataset_path_rewriter = self.dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 731, in dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: return self._job_dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 724, in _job_dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: self._dataset_path_rewriter = OutputsToWorkingDirectoryPathRewriter(self.working_directory)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 922, in working_directory
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: job, base_dir='job_work', dir_only=True, obj_dir=True)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 558, in get_filename
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 768, in _call_method
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: % (method, self._repr_object_for_exception(obj), str(kwargs)))
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: ObjectNotFound: objectstore, _call_method failed: get_filename on Job(id=5658189), kwargs: {'obj_dir': True, 'dir_only': True, 'base_dir': 'job_work'}
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: galaxy.jobs.handler ERROR 2019-08-05 13:57:49,245 (5673509) Caught exception while attempting to fail job.
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: Traceback (most recent call last):
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/handler.py", line 476, in __filter_jobs_with_invalid_input_states
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: job_wrapper.fail(fail_message)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1021, in fail
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: for dataset_path in self.get_output_fnames():
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1650, in get_output_fnames
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: self.compute_outputs()
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1664, in compute_outputs
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: dataset_path_rewriter = self.dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 731, in dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: return self._job_dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 724, in _job_dataset_path_rewriter
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: self._dataset_path_rewriter = OutputsToWorkingDirectoryPathRewriter(self.working_directory)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 922, in working_directory
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: job, base_dir='job_work', dir_only=True, obj_dir=True)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 558, in get_filename
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: File "/opt/galaxy/server/lib/galaxy/objectstore/__init__.py", line 768, in _call_method
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: % (method, self._repr_object_for_exception(obj), str(kwargs)))
Aug 05 13:57:49 sn04.bi.uni-freiburg.de python[2443297]: ObjectNotFound: objectstore, _call_method failed: get_filename on Job(id=5673509), kwargs: {'obj_dir': True, 'dir_only': True, 'base_dir': 'job_work'}
```

maybe xref #8171?

**Comment by hexylena** [comment]
Wait, that's only in dev, sorry for noise.
