### ISSUE TITLE
Kubernetes runner breaks on setting decimal memory values

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#8453]
When running the current version of the k8s runner with memory requests/limits I'm getting:

```
galaxy.jobs.runners ERROR 2019-08-13 15:40:06,842 [p:423,w:1,m:0] [KubernetesRunner.work_thread-0] (553) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 130, in run_next
    method(arg)
  File "lib/galaxy/jobs/runners/kubernetes.py", line 130, in queue_job
    "spec": self.__get_k8s_job_spec(ajs)
  File "lib/galaxy/jobs/runners/kubernetes.py", line 221, in __get_k8s_job_spec
    k8s_job_spec = {"template": self.__get_k8s_job_spec_template(ajs)}
  File "lib/galaxy/jobs/runners/kubernetes.py", line 235, in __get_k8s_job_spec_template
    "containers": self.__get_k8s_containers(ajs)
  File "lib/galaxy/jobs/runners/kubernetes.py", line 275, in __get_k8s_containers
    resources = self.__get_resources(ajs.job_wrapper)
  File "lib/galaxy/jobs/runners/kubernetes.py", line 293, in __get_resources
    mem_request = self.__get_memory_request(job_wrapper)
  File "lib/galaxy/jobs/runners/kubernetes.py", line 325, in __get_memory_request
    return self.__transform_memory_value(job_destinantion.params['requests_memory'])
  File "lib/galaxy/jobs/runners/kubernetes.py", line 356, in __transform_memory_value
    return ByteSize(mem_value).value
  File "lib/galaxy/util/bytesize.py", line 32, in __init__
    self.value = parse_bytesize(value)
  File "lib/galaxy/util/bytesize.py", line 51, in parse_bytesize
    value = value.upper()
AttributeError: 'float' object has no attribute 'upper'
```

**Comment by pcm32** [comment]
Ok, this was because the new runner was expecting only float values when having a Unit, not in the way I was using on my dynamic destinations with the previous versions.
