### ISSUE TITLE
planemo test Exception 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8487]
Have the followiing error here https://github.com/galaxyproject/tools-iuc/pull/2539 
https://travis-ci.org/galaxyproject/tools-iuc/jobs/574822038

```
Traceback (most recent call last):

  File "/tmp/tmpD9TmgX/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 224, in prepare_job

    job_wrapper.prepare()

  File "/tmp/tmpD9TmgX/galaxy-dev/lib/galaxy/jobs/__init__.py", line 871, in prepare

    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()

  File "/tmp/tmpD9TmgX/galaxy-dev/lib/galaxy/tools/evaluation.py", line 451, in build

    raise e

AttributeError: 'super' object has no attribute '__gt__'

FAIL
```

**Comment by jmchilton** [comment]
I think we had some tool fixes last fall/winter that would have corrected this. Any chance you can retry? Are those tests still failing?

**Comment by mvdbeek** [comment]
I'm afraid with the logs gone and the PR merged we don't have enough to look into it anymore. Maybe a rerun was all that was needed ?
