### ISSUE TITLE
Exception thrown when trying to view dataset details

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8566]
I am running a tool input with multiple=true mapped over a list:list.
When viewing the output details it throws this exception:

```log
File 'lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 143 in __call__
  return self.handle_request(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 222 in handle_request
  body = method(trans, **kwargs)
File 'lib/galaxy/webapps/galaxy/controllers/dataset.py', line 1114 in show_params
  has_parameter_errors=has_parameter_errors)
File 'lib/galaxy/web/framework/webapp.py', line 923 in fill_template
  return self.fill_template_mako(filename, **kwargs)
File 'lib/galaxy/web/framework/webapp.py', line 936 in fill_template_mako
  return template.render(**data)
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/mako/template.py', line 462 in render
  return runtime._render(self, self.callable_, args, data)
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 838 in _render
  **_kwargs_for_callable(callable_, data))
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 873 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/home/ncm3/galaxy-19.05-git/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py', line 899 in _exec_template
  callable_(context, *args, **kwargs)
File '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/compiled_templates/base.mako.py', line 69 in render_body
  __M_writer(unicode(next.body()))
File '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/compiled_templates/show_params.mako.py', line 150 in render_body
  __M_writer(unicode( inputs_recursive( tool.inputs, params_objects, depth=1, upgrade_messages=upgrade_messages ) ))
File '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/compiled_templates/show_params.mako.py', line 42 in inputs_recursive
  return render_inputs_recursive(context._locals(__M_locals),input_params,param_values,depth,upgrade_messages)
File '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/compiled_templates/show_params.mako.py', line 364 in render_inputs_recursive
  if element.history_content_type == "dataset":
AttributeError: 'DatasetCollectionElement' object has no attribute 'history_content_type'
```

Galaxy version 19.05

**Comment by innovate-invent** [comment]
I am not sure if this is a different issue but I have ran into a different error when trying to view dataset details generated by a different tool. 
```sh
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 176, in show
    return self.__show_dataset(trans, id, **kwd)
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 263, in __show_dataset
    **self._parse_serialization_params(kwd, 'detailed'))
  File "lib/galaxy/managers/base.py", line 692, in serialize_to_view
    return self.serialize(item, all_keys, **context)
  File "lib/galaxy/managers/hdas.py", line 367, in serialize
    return super(HDASerializer, self).serialize(hda, keys, user=user, **context)
  File "lib/galaxy/managers/datasets.py", line 604, in serialize
    serialized = super(DatasetAssociationSerializer, self).serialize(dataset_assoc, keys, **context)
  File "lib/galaxy/managers/base.py", line 605, in serialize
    returned[key] = self.serializers[key](item, key, **context)
  File "lib/galaxy/managers/hdas.py", line 374, in serialize_display_apps
    for display_app in hda.get_display_applications(trans).values():
  File "lib/galaxy/model/__init__.py", line 2757, in get_display_applications
    return self.datatype.get_display_applications_by_dataset(self, trans)
  File "lib/galaxy/datatypes/data.py", line 551, in get_display_applications_by_dataset
    value = value.filter_by_dataset(dataset, trans)
  File "lib/galaxy/datatypes/display_applications/application.py", line 309, in filter_by_dataset
    if link_value.filter_by_dataset(data, trans):
  File "lib/galaxy/datatypes/display_applications/application.py", line 95, in filter_by_dataset
    if fill_template(filter_elem.text, context=context) != filter_elem.get('value', 'True'):
  File "lib/galaxy/util/template.py", line 91, in fill_template
    raise first_exception or e
NotFound: cannot find 'dataset'
142.58.16.193 - - [18/Oct/2019:17:48:54 +0000] "GET /api/histories/9ce617df390851fc/contents/c6a73850c3326872 HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

**Comment by mvdbeek** [comment]
Just gave this another shot and it seems to work fine now (list:list into multiple="true"). We're not using the show_params.mako anymore, but not sure that was the only fix, we may have also changed how mapping over nested collections work since 19.05.
Thanks for the repo @innovate-invent and tet me know if this is still happening.
