### ISSUE TITLE
obj_id being set to "None" in decode_id

### ISSUE THREAD

**Issue by crutching** [galaxyproject/galaxy#858]
Attempting to instantiate small workflow via BioBlend, stack trace below.  Workflow inputs defined through 'ldda'.  No params are being passed. 

```
galaxy.web.framework.decorators ERROR 2015-10-06 11:04:27,741 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/web/framework/decorators.py", line 251, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/webapps/galaxy/api/workflows.py", line 190, in create
    run_config = build_workflow_run_config( trans, workflow, payload )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/run_request.py", line 222, in build_workflow_run_config
    trans.security.decode_id(input_id))
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/web/security/__init__.py", line 102, in decode_id
    return int( id_cipher.decrypt( obj_id.decode( 'hex' ) ).lstrip( "!" ) )
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by nsoranzo** [comment]
It seems you have some input which is `{'src': 'ldda', 'id': None}`. Can this be the reason?

**Comment by crutching** [comment]
@nsoranzo Thanks for the suggestion, let me search back through to see if I have overlooked something.

**Comment by crutching** [comment]
@nsoranzo It turns out my code was doing something unintended, thanks for the help.
