### ISSUE TITLE
Data Managers in Tool Shed issues

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#8641]
I'm using Galaxy 19.09 on Python 3.7.

I have a tool shed repository with multiple data managers.

## `data_manager_conf.xml`
These were all added to `data_manager_conf.xml` in the following way:
```xml
<?xml version="1.0"?>
<data_managers>

    <!-- Comment 1 -->
    <data_manager tool_file="data_manager/DM1.xml" id="dm1" version="VERSION">
        <data_table name="DT1">
            <output>
               columns here
            </output>
        </data_table>
    </data_manager>

    <!-- Comment 2 -->
    <data_manager tool_file="data_manager/DM2.xml" id="dm2" version="VERSION">
        <data_table name="DT2">
            <output>
                columns here
            </output>
        </data_table>
    </data_manager>
</data_managers>
```

In the parser, where the exception is thrown, I added a traceback that's shown for debugging purposes, this gave me the following error:
```
tool_shed.galaxy_install.tools.data_manager WARNING 2019-09-12 19:47:44,394 [p:54106,w:1,m:0] [uWSGIWorker1Core1] Encountered unexpected element '<function Comment at 0x7f26eb7d7488>':
<!-- Comment 1 -->
    
galaxy.tools.data_manager.manager DEBUG 2019-09-12 19:47:44,456 [p:54106,w:1,m:0] [uWSGIWorker1Core1] Loaded Data Manager: TOOLSHED/repos/USER/REPO/data_manager/DM2/VERSION
tool_shed.galaxy_install.tools.data_manager WARNING 2019-09-12 19:47:44,456 [p:54106,w:1,m:0] [uWSGIWorker1Core1] Encountered unexpected element '<function Comment at 0x7f26eb7d7488>':
<!-- Comment 2-->
```

I changed them to:
```xml
<?xml version="1.0"?>
<data_managers>
    <data_manager tool_file="data_manager/DM1.xml" id="dm1" version="VERSION">
        <data_table name="DT1">
            <output>
               columns here
            </output>
        </data_table>
    </data_manager>

    <data_manager tool_file="data_manager/DM2.xml" id="dm2" version="VERSION">
        <data_table name="DT2">
            <output>
                columns here
            </output>
        </data_table>
    </data_manager>
</data_managers>
```

## `tool_data_table_conf.xml.sample`
I had a comment on the first line and the rest similar to:
```xml
<!-- Use the file tool_data_table_conf.xml.oldlocstyle if you don't want to update your loc files as changed in revision 4550:535d276c92bc-->
<tables>
    <!-- DT1 -->
    <table name="dt1" comment_char="#" allow_duplicate_entries="False">
        <columns>columns</columns>
        <file path="tool-data/dt1.txt" />
    </table>

    <!-- DT2 -->
    <table name="dt2" comment_char="#" allow_duplicate_entries="False">
        <columns>columns</columns>
        <file path="tool-data/dt2.txt" />
    </table>
</tables>
```

Which threw the following error:
```
tool_shed.util.xml_util ERROR 2019-09-12 19:47:44,334 [p:54106,w:1,m:0] [uWSGIWorker1Core1] Exception attempting to parse GLXFOLDER/tool-data/TOOLSHED/repos/USER/REPO/REVISION/tool_data_table_conf.xml: multiple elements on top level
Traceback (most recent call last):
  File "lib/tool_shed/util/xml_util.py", line 87, in parse_xml
    tree = XmlET.parse(fobj, parser=XmlET.XMLParser(target=Py27CommentedTreeBuilder()))
  File "PYTHON3.7/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "PYTHON3.7/lib/python3.7/xml/etree/ElementTree.py", line 604, in parse
    parser.feed(data)
  File "<string>", line None
xml.etree.ElementTree.ParseError: multiple elements on top level
```

I fixed that by changing it to:
```xml
<?xml version="1.0"?>
<tables>
    <!-- DT1 -->
    <table name="dt1" comment_char="#" allow_duplicate_entries="False">
        <columns>columns</columns>
        <file path="tool-data/dt1.txt" />
    </table>

    <!-- DT2 -->
    <table name="dt2" comment_char="#" allow_duplicate_entries="False">
        <columns>columns</columns>
        <file path="tool-data/dt2.txt" />
    </table>
</tables>
```

And this solved that issue. However, this worked fine in 19.05 + Python 2.7.
For the latter one, I believe this is something that can't be fixed in Galaxy as it seems to be a library included by Python. However, I do believe it is good to document this.

**Comment by mvdbeek** [comment]
Thanks for the report and fixes. I think this is working now with https://github.com/galaxyproject/galaxy/pull/8643 and https://github.com/galaxyproject/galaxy/pull/8634
