### ISSUE TITLE
weberror library + python3

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#8642]
I believe this issue was caused by my compiled mako templates being outdated (python 2 instead of python 3 templates) as discussed here: https://github.com/galaxyproject/galaxy/issues/8617.

However, somehow in the whole list of dependencies for Galaxy the 'weberror' library seems to be included. This library is, at the time of writing this issue, not python 3 compatible. I have created a pull request to make it Python 3 compatible though (https://github.com/Pylons/weberror/pull/21).

It throws the following errors (examples):
```
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 190, in uwsgi_app
    return galaxy.web.framework.webapp.build_native_uwsgi_app(app_factory, "galaxy")
  File "lib/galaxy/web/framework/webapp.py", line 988, in build_native_uwsgi_app
    uwsgi_app = paste_factory({}, load_app_kwds=app_kwds)
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 163, in app_factory
    webapp = wrap_in_middleware(webapp, global_conf, app.application_stack, **kwargs)
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 1185, in wrap_in_middleware
    from weberror import evalexception
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/weberror/evalexception.py", line 127
    except ValueError, ve:
                     ^
SyntaxError: invalid syntax
```

```
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 190, in uwsgi_app
    return galaxy.web.framework.webapp.build_native_uwsgi_app(app_factory, "galaxy")
  File "lib/galaxy/web/framework/webapp.py", line 988, in build_native_uwsgi_app
    uwsgi_app = paste_factory({}, load_app_kwds=app_kwds)
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 163, in app_factory
    webapp = wrap_in_middleware(webapp, global_conf, app.application_stack, **kwargs)
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 1185, in wrap_in_middleware
    from weberror import evalexception
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/weberror/evalexception.py", line 25, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```

This seems to have obfuscated the actual issue, which were my Mako templates which were out of date (I am assuming this at least).

**Comment by nsoranzo** [comment]
`weberror` is a conditional dependency that is installed only if both `debug` and `use_interactive` are set to `true` in `config/galaxy.yml` , see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/__init__.py#L162-L164 .

See also #1715 , where I summarised that state of this as: "WebError: unmaintained, even the latest 0.13.1 release doesn't support Python 3 and there is no interest in adding support, see e.g. Pylons/weberror#18 . It could be replaced with [Werkzeug](https://palletsprojects.com/p/werkzeug/), as suggested in #1017"

**Comment by selten** [comment]
I'll close this issue. I didn't find it when I searched for issues.
