### ISSUE TITLE
CVMFS datatypes_conf.xml mismatch bcf_to_bcf_bgzip_converter.xml

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy#8688]
`/cvmfs/main.galaxyproject.org/config/datatypes_conf.xml` has entries:
```
<converter file="bcf_to_bcf_bgzip_converter.xml" target_datatype="bcf_bgzip"/>
    <datatype extension="bcf_bgzip" type="galaxy.datatypes.binary:Binary" mimetype="application/octet-stream" subclass="True">
      <converter file="bcf_bgzip_to_bcf_converter.xml" target_datatype="bcf"/>
```
but the converters were changed in https://github.com/galaxyproject/galaxy/commit/da5b72a030d8d07c663566527fc64560e067eb54 to `bcf_to_bcf_uncompressed_converter.xml`/`bcf_uncompressed_to_bcf_converter.xml`, and the mismatch is causing errors when installing some tools with configs from CVMFS:
```
galaxy.datatypes.registry ERROR 2019-09-19 17:37:29,287 Error loading converter (./lib/galaxy/datatypes/converters)
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/datatypes/registry.py", line 599, in load_datatype_converters
    converter = toolbox.load_tool(config_path, use_cached=use_cached)
  File "/galaxy/server/lib/galaxy/tools/toolbox/base.py", line 790, in load_tool
    tool = self.create_tool(config_file=config_file, tool_shed_repository=tool_shed_repository, guid=guid, **kwds)
  File "/galaxy/server/lib/galaxy/tools/__init__.py", line 278, in create_tool
    raise e
IOError: [Errno 2] No such file or directory: './lib/galaxy/datatypes/converters/bcf_bgzip_to_bcf_converter.xml'
```

**Comment by mvdbeek** [comment]
Is there anything before and after that in the logs ? Does this stop the installation ? If no (and I think this is a caught and dealt with error) I'd say this isn't a Galaxy issue, the `datatypes_conf.xml` file needs to be updated.

**Comment by almahmoud** [comment]
Yes, the issue isn't in Galaxy, just a matter of updating the file (assuming the file is still being kept up to date?). Wasn't sure where the appropriate place for the issue was for that...

**Comment by jmchilton** [comment]
Main issues generally belong in usegalaxy-playbook.
