### ISSUE TITLE
19.09 error: lazy load operation of attribute 'tool_dependencies' cannot proceed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#8769]
This is happening unregularly with 19.09. We have seen this a few times during various workshops this week.

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 237, in prepare_job
    stderr_file=stderr_file,
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 278, in build_command_line
    stderr_file=stderr_file,
  File "/opt/galaxy/server/lib/galaxy/jobs/command_factory.py", line 71, in build_command
    __handle_dependency_resolution(commands_builder, job_wrapper, remote_command_params)
  File "/opt/galaxy/server/lib/galaxy/jobs/command_factory.py", line 182, in __handle_dependency_resolution
    if local_dependency_resolution and job_wrapper.dependency_shell_commands:
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 920, in dependency_shell_commands
    job_directory=self.working_directory
  File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1646, in build_dependency_shell_commands
    installed_tool_dependencies=self.installed_tool_dependencies,
  File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1657, in installed_tool_dependencies
    installed_tool_dependencies = self.tool_shed_repository.tool_dependencies_installed_or_in_error
  File "/opt/galaxy/server/lib/galaxy/model/tool_shed_install/__init__.py", line 418, in tool_dependencies_installed_or_in_error
    for tool_dependency in self.tool_dependencies:
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 688, in _load_for_state
    % (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fe9e356de50> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```

ping @erasche

**Comment by bgruening** [comment]
A different tool, same error.

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 237, in prepare_job
    stderr_file=stderr_file,
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 278, in build_command_line
    stderr_file=stderr_file,
  File "/opt/galaxy/server/lib/galaxy/jobs/command_factory.py", line 71, in build_command
    __handle_dependency_resolution(commands_builder, job_wrapper, remote_command_params)
  File "/opt/galaxy/server/lib/galaxy/jobs/command_factory.py", line 182, in __handle_dependency_resolution
    if local_dependency_resolution and job_wrapper.dependency_shell_commands:
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 920, in dependency_shell_commands
    job_directory=self.working_directory
  File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1646, in build_dependency_shell_commands
    installed_tool_dependencies=self.installed_tool_dependencies,
  File "/opt/galaxy/server/lib/galaxy/tools/__init__.py", line 1657, in installed_tool_dependencies
    installed_tool_dependencies = self.tool_shed_repository.tool_dependencies_installed_or_in_error
  File "/opt/galaxy/server/lib/galaxy/model/tool_shed_install/__init__.py", line 418, in tool_dependencies_installed_or_in_error
    for tool_dependency in self.tool_dependencies:
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 688, in _load_for_state
    % (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f61ac338390> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)

```

**Comment by hexylena** [comment]
We've seen this a LOT this morning.

```
galaxy@sn04:~$ GDPR_MODE=1 gxadmin query training-queue gallantries | grep error | grep rna

error   | 6131942 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | b897a33c483 | 2019-10-08 11:04:50.318966+02
 error   | 6132184 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 72a0b8e5462 | 2019-10-08 11:26:15.487051+02
 error   | 6132192 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 1f1b1992419 | 2019-10-08 11:26:56.442144+02
 error   | 6132194 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 42c62f37aa0 | 2019-10-08 11:26:56.528128+02
 error   | 6132196 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 47f39a815e6 | 2019-10-08 11:26:56.609987+02
 error   | 6132222 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | a1ff99b7ed1 | 2019-10-08 11:26:59.493741+02
 error   | 6132227 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 1c74208a25d | 2019-10-08 11:26:59.908235+02
 error   | 6132243 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 36dde97cbf8 | 2019-10-08 11:27:01.936056+02
 error   | 6132245 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | d11ff03d2c4 | 2019-10-08 11:27:01.980491+02
 error   | 6132246 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 080497bb245 | 2019-10-08 11:27:02.261701+02
 error   | 6132247 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | d11ff03d2c4 | 2019-10-08 11:27:02.375057+02
 error   | 6132249 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | cd5d68417c6 | 2019-10-08 11:27:02.835824+02
 error   | 6132252 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 0ce767b0036 | 2019-10-08 11:27:03.707667+02
 error   | 6132253 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 0ce767b0036 | 2019-10-08 11:27:04.083868+02
 error   | 6132257 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 9c5b73868f3 | 2019-10-08 11:27:08.086075+02
 error   | 6132263 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 47f39a815e6 | 2019-10-08 11:27:34.746383+02
 error   | 6132268 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | b942ef51713 | 2019-10-08 11:27:50.280582+02
 error   | 6132269 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | b942ef51713 | 2019-10-08 11:27:51.19461+02
 error   | 6132272 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 47f39a815e6 | 2019-10-08 11:28:03.883507+02
 error   | 6132281 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 42c62f37aa0 | 2019-10-08 11:28:30.265488+02
 error   | 6132286 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 42c62f37aa0 | 2019-10-08 11:28:50.161113+02
 error   | 6132292 |         | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | 080497bb245 | 2019-10-08 11:28:56.676152+02
 error   | 6132299 | 1487332 | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | d11ff03d2c4 | 2019-10-08 11:29:20.996063+02
 error   | 6132300 | 1487331 | toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.2b                       | d11ff03d2c4 | 2019-10-08 11:29:21.703004+02
```


```
galaxy@sn04:~$ gxadmin query training-queue gallantries | grep error | grep rna | awk '{print $3}' | xargs gxadmin query aq job traceback | grep Detached
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7febdc259610> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f5fe0201310> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00da0e50d0> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00e42d3f10> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f71db419350> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fbee8f92f10> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f5fe0201310> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f71db419350> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fe9d1047510> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7febdc259610> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fe9d1047510> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f61ac338390> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fbe841579d0> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fbee8f92f10> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00ae679750> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00da0e50d0> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00e42d3f10> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f5fe0201310> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00ae679750> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f0106326190> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7fe9d1047510> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
 DetachedInstanceError: Parent instance <ToolShedRepository at 0x7f00da0e50d0> is not bound to a Session; lazy load operation of attribute 'tool_dependencies' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)+
```

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/3904?

**Comment by martenson** [comment]
This is not fixed, because we had to revert the fix. See https://github.com/galaxyproject/galaxy/pull/8791

**Comment by guerler** [comment]
Noticed that the same error is (sometimes) triggered when accessing the "Manage Dependencies" view in the admin panel. fyi.

**Comment by ooobik** [comment]
As @guerler said, this broke our "Manage dependencies" completely. I'll try hack some better debug output over the next few days if i have time.

**Comment by mvdbeek** [comment]
fixed by https://github.com/galaxyproject/galaxy/pull/8824
