### ISSUE TITLE
Cheetah odd behaviour

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#8804]
I had the following stack-trace pop up when trying to run a tool:
```
Traceback (most recent call last):
  File "lib/galaxy/util/__init__.py", line 1035, in unicodify
    value = text_type(value)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1570634376_8492055_76540.py", line 91, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: PARAM expected at least 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/util/template.py", line 67, in fill_template
    return unicodify(t)
  File "lib/galaxy/util/__init__.py", line 1041, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1570634376_8492055_76540.py", line 91, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: PARAM expected at least 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 230, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 1061, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 477, in build
    raise e
  File "lib/galaxy/tools/evaluation.py", line 473, in build
    self.__build_command_line()
  File "lib/galaxy/tools/evaluation.py", line 498, in __build_command_line
    command_line = fill_template(command, context=param_dict, python_template_version=self.tool.python_template_version)
  File "lib/galaxy/util/template.py", line 111, in fill_template
    python_template_version=python_template_version,
  File "lib/galaxy/util/template.py", line 113, in fill_template
    raise first_exception or e
  File "lib/galaxy/util/template.py", line 67, in fill_template
    return unicodify(t)
  File "lib/galaxy/util/__init__.py", line 1041, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1570633880_415516_50351.py", line 89, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: PARAM expected at least 1 arguments, got 0
```

The tool XML parameter that it references:
```xml
<param name="PARAM" type="text" label="LABEL" help="HELP. E.g.: 2 10 10 EXAMPLE VALUES. Whitespace separated" value="2 10 10"/>
```

I'm running a version of 19.09 (I believe from the 11th of October) on Python 3.7. The compiled templates have all been deleted from database/compiled_templates in the past.

**Comment by mvdbeek** [comment]
Can you post a minimal tool xml file please ?
Also it looks like you're not using the C extension of Cheetah, do you know why that is the case ?

**Comment by selten** [comment]
I now use the C extension (I assume this because of the lack of an error message). I now get the following stack-trace:
```
RefactoringTool DEBUG 2019-10-15 13:43:49,759 [p:7525,w:1,m:0] [DRMAARunner.work_thread-0] Refactoring auto_translate_cheetah
galaxy.jobs.runners ERROR 2019-10-15 13:43:49,860 [p:7525,w:1,m:0] [DRMAARunner.work_thread-0] (217311) Failure preparing job
Traceback (most recent call last):
  File "lib/galaxy/util/__init__.py", line 1035, in unicodify
    value = text_type(value)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1571139829_8114624_26363.py", line 91, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: pop expected at least 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/util/template.py", line 67, in fill_template
    return unicodify(t)
  File "lib/galaxy/util/__init__.py", line 1041, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1571139829_8114624_26363.py", line 91, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: pop expected at least 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 230, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 1066, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 477, in build
    raise e
  File "lib/galaxy/tools/evaluation.py", line 473, in build
    self.__build_command_line()
  File "lib/galaxy/tools/evaluation.py", line 498, in __build_command_line
    command_line = fill_template(command, context=param_dict, python_template_version=self.tool.python_template_version)
  File "lib/galaxy/util/template.py", line 111, in fill_template
    python_template_version=python_template_version,
  File "lib/galaxy/util/template.py", line 113, in fill_template
    raise first_exception or e
  File "lib/galaxy/util/template.py", line 67, in fill_template
    return unicodify(t)
  File "lib/galaxy/util/__init__.py", line 1041, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1571139829_6929507_31700.py", line 89, in respond
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "GLXFOLDER/.venv/lib/python3.7/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    obj = nextObj()
TypeError: pop expected at least 1 arguments, got 0
```

Minimal XML:
```xml
<tool id="tool_id" name="Tool Name" version="1.0.0">
  <description>Tool Description</description>

  <requirements>
    <requirement type="package" version="1.0.0">Conda Package</requirement>
  </requirements>
  
  <command>
    <![CDATA[
     $__tool_directory__/tool -param1 '$param1' -param2 '$param2' > $out
    ]]>
  </command>
  
   <configfiles>
   </configfiles>
  

  <inputs>
    <param name="param1" type="text" label="LABEL" help="HELP. E.g.: 2 10 10 EXAMPLE VALUES. Whitespace separated" value="2 10 10"/>

    <param name="param2" type="integer" label="param2" value="1000 "/>
  </inputs>

  <outputs>
    <data name="out" label="${tool.name} on ${on_string}" format="txt"/>
  </outputs>


  <tests>
  </tests>
</tool>

```

**Comment by mvdbeek** [comment]
That minimal xml isn't entirely correct (package name isn't valid, and the binary doesn't exist of course). I've changed this to:
```xml
<tool id="tool_id" name="Tool Name" version="1.0.0">
  <description>Tool Description</description>
  <command>
    <![CDATA[
    echo "'$param1' -param2 '$param2'" > $out
    ]]>
  </command>
  <inputs>
    <param name="param1" type="text" label="LABEL" help="HELP. E.g.: 2 10 10 EXAMPLE VALUES. Whitespace separated" value="2 10 10"/>
    <param name="param2" type="integer" label="param2" value="1000 "/>
  </inputs>
  <outputs>
    <data name="out" label="${tool.name} on ${on_string}" format="txt"/>
  </outputs>
</tool>
```

which runs fine on python 3.7.4.

In any case it's not unicodify that is at fault here, it just uses a `except Exception` to catch whatever exception occured while converting the template back to a string.

To me it vaguely looks like you have a problem in your cheetah code, but without the real code I can't help you more. Feel free to send it as a private message on gitter.

**Comment by selten** [comment]
Turns out this was due to the name of param1 being `pop`. 
Accessing this through `$pop` caused the error above.
