### ISSUE TITLE
19.09: some tools do not load (nested macros)

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#8805]
Reported by @bgruening for the tools [je-clip](https://toolshed.g2.bx.psu.edu/view/gbcs-embl-heidelberg/je_clip/7f3d516cb0e2) and [je-demultiplex](https://toolshed.g2.bx.psu.edu/view/gbcs-embl-heidelberg/je_demultiplex/bd3cdf128bcb).
Source can be found here: https://github.com/gbcs-embl/Je/blob/master/src/galaxy/je-clip.xml

The tools are working fine in 19.05 but don't load in 19.09. From planemo I get:
```
galaxy.tools.toolbox.base ERROR 2019-10-15 10:55:57,876 Failed to load potential tool /Users/scholtalbers/workspace/je-suite/src/galaxy/je-clip.xml.
Traceback (most recent call last):
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 772, in quick_load
    tool = self.load_tool(tool_file)
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 808, in load_tool
    tool = self.create_tool(config_file=config_file, tool_shed_repository=tool_shed_repository, guid=guid, **kwds)
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/__init__.py", line 274, in create_tool
    raise e
AssertionError
galaxy.tools.toolbox.base ERROR 2019-10-15 10:55:57,887 Failed to load potential tool /Users/scholtalbers/workspace/je-suite/src/galaxy/je-demultiplex.xml.
Traceback (most recent call last):
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 772, in quick_load
    tool = self.load_tool(tool_file)
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 808, in load_tool
    tool = self.create_tool(config_file=config_file, tool_shed_repository=tool_shed_repository, guid=guid, **kwds)
  File "/private/var/folders/cf/k7c5rjhj1sggk6x8z1jnw4b80000gp/T/tmpFw8KvW/galaxy-dev/lib/galaxy/tools/__init__.py", line 274, in create_tool
    raise e
AssertionError
```

**Comment by mvdbeek** [comment]
Thanks for the report, this should be fixed by https://github.com/galaxyproject/galaxy/pull/8806

**Comment by scholtalbers** [comment]
ping @bgruening & @cgirardot
On usegalaxy.eu for je-clip when selecting `paired-end`, the option `BPOS` doesn't show and causes the tool to not execute as `library.BPOS` cannot be found.

On our local instance, still at 19.05, we do get this option. I assume this is related to this issue and related fixes.

How the UI should look (on 19.05):
<img width="512" alt="Screenshot 2020-02-18 at 10 47 43" src="https://user-images.githubusercontent.com/102411/74724450-933d3980-523c-11ea-8505-fa87a8df70f9.png">


How it looks on usegalaxy.eu:
<img width="482" alt="Screenshot 2020-02-18 at 10 49 33" src="https://user-images.githubusercontent.com/102411/74724307-5e30e700-523c-11ea-8144-55b5fc9a5353.png">

**Comment by mvdbeek** [comment]
This works fine locally on 20.01, so I guess this is .eu specific:
<img width="1645" alt="Screenshot 2020-02-18 at 11 08 14" src="https://user-images.githubusercontent.com/6804901/74725990-ff20a180-523e-11ea-8a50-32bdab915466.png">
