### ISSUE TITLE
Galaxy is reading from data_manager_conf.xml.sample

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#8811]
The sample was missing, which was fixed in #8784, but that also made it clear that Galaxy is reading from the sample, which it should not be as of #921 (and according to my checklist there, it wasn't, but that must've changed).

**Comment by natefoo** [comment]
It's apparently looking for `shed_data_manager_conf.xml` which I'm pretty sure is a regression since #921 was merged:

```pytb
galaxy.tools.search DEBUG 2019-10-15 19:10:08,785 [p:1,w:0,m:0] [MainThread] Toolbox index finished (10130.351 ms)
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/galaxy/server/lib/galaxy/app.py", line 137, in __init__
    self.data_managers = DataManagers(self)
  File "/galaxy/server/lib/galaxy/tools/data_manager/manager.py", line 38, in __init__
    self.load_from_xml(self.app.config.shed_data_manager_config_file, store_tool_path=True)
  File "/galaxy/server/lib/galaxy/tools/data_manager/manager.py", line 45, in load_from_xml
    tree = util.parse_xml(xml_filename)
  File "/galaxy/server/lib/galaxy/util/__init__.py", line 236, in parse_xml
    root = tree.parse(fname, parser=ElementTree.XMLParser(target=DoctypeSafeCallbackTarget()))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/galaxy/server/config/shed_data_manager_conf.xml'
```

**Comment by jdavcs** [comment]
From what I see so far, It doesn't look like this was caused by any recent changes to how config is loaded, but I'll take a closer look today.

**Comment by jdavcs** [comment]
This appears to have been fixed. Closing for now, please feel free to reopen if this happens again.
