### ISSUE TITLE
Galaxy api exception for gff files

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8826]
When trying to view dataset details for datasets formatted as gff of gff3 an exception is thrown:
```py
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 176, in show
    return self.__show_dataset(trans, id, **kwd)
  File "lib/galaxy/webapps/galaxy/api/history_contents.py", line 263, in __show_dataset
    **self._parse_serialization_params(kwd, 'detailed'))
  File "lib/galaxy/managers/base.py", line 692, in serialize_to_view
    return self.serialize(item, all_keys, **context)
  File "lib/galaxy/managers/hdas.py", line 367, in serialize
    return super(HDASerializer, self).serialize(hda, keys, user=user, **context)
  File "lib/galaxy/managers/datasets.py", line 604, in serialize
    serialized = super(DatasetAssociationSerializer, self).serialize(dataset_assoc, keys, **context)
  File "lib/galaxy/managers/base.py", line 605, in serialize
    returned[key] = self.serializers[key](item, key, **context)
  File "lib/galaxy/managers/hdas.py", line 374, in serialize_display_apps
    for display_app in hda.get_display_applications(trans).values():
  File "lib/galaxy/model/__init__.py", line 2757, in get_display_applications
    return self.datatype.get_display_applications_by_dataset(self, trans)
  File "lib/galaxy/datatypes/data.py", line 551, in get_display_applications_by_dataset
    value = value.filter_by_dataset(dataset, trans)
  File "lib/galaxy/datatypes/display_applications/application.py", line 309, in filter_by_dataset
    if link_value.filter_by_dataset(data, trans):
  File "lib/galaxy/datatypes/display_applications/application.py", line 95, in filter_by_dataset
    if fill_template(filter_elem.text, context=context) != filter_elem.get('value', 'True'):
  File "lib/galaxy/util/template.py", line 91, in fill_template
    raise first_exception or e
NotFound: cannot find 'dataset'
142.58.16.193 - - [18/Oct/2019:17:48:54 +0000] "GET /api/histories/9ce617df390851fc/contents/c6a73850c3326872 HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

I am not sure what is causing this, the instance of Galaxy I am using was working a few days prior.
Setting the dataset format to txt does not throw this error.

**Comment by innovate-invent** [comment]
An update occurred on the system, touching an installation of python. This may have affected it.
Closing this issue for now.
