### ISSUE TITLE
Cli runner fails cryptically when the executable for the scheduling system is not in the $PATH

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#8906]
When using the cli plugin runners and the schedulers binary is not in the path, `cli.py` tends fails too cryptically:

```
galaxy.jobs.runners ERROR 2019-10-29 22:43:07,651 [p:20839,w:0,m:2] [ShellRunner.work_thread-0] (2) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 131, in run_next
    method(arg)
  File "lib/galaxy/jobs/runners/cli.py", line 105, in queue_job
    external_job_id = stdout.strip().split()[-1]
IndexError: list index out of range
```

Probably the cli runners should have a method to check and alert that the required executables are in the path and are executable within the shell where the galaxy process is running.

**Comment by pcm32** [comment]
The above error is from the tip of `release_19.05`.

**Comment by MetraneAbdelmounim** [comment]
hello , i got the same error 
my job config xml looks like
        <destination id="cli_default" runner="cli">
           <param id="shell_plugin">SecureShell</param>
           <param id="job_plugin">Slurm</param>
           <param id="shell_hostname">ip.ip.ip.ip</param>
           <param id="shell_username">aaaaaa</param>
    </destination>

**Comment by MetraneAbdelmounim** [comment]
i have the same probleme
what should i do to resolve the problem ? 
i'm using the cli unnner plugin

**Comment by marcarcla** [comment]
Hi, this error still persists on `release_21.09`.
We have  `Slurm 20.11.0.1` on `Ubuntu 20.04`.
Any ideas on how to solve this?

**Comment by bernt-matthias** [comment]
Easiest solution/workaround seems to be to put the scheduler binary to the `PATH`, or?

**Comment by marcarcla** [comment]
> Easiest solution/workaround seems to be to put the scheduler binary to the `PATH`, or?
Do you mean the slurm binaries such as `sbatch`, `srun`, etc.? In our system, the user `galaxy` can run jobs using the slurm binaries. If you just ask `which sbatch`, for instance, you will get `/usr/local/bin/sbatch`, although this file is physically located in another server (our cluster), being shared across an NFS.
