### ISSUE TITLE
Dynamic options input causes workflow to fail to enter the run form

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/galaxy#8974]
A tool that takes a tabular file to generate dynamic options gives the workflow run form a strike.
```
galaxy.web.framework.decorators ERROR 2019-11-12 02:51:28,110 [p:13883,w:1,m:0] [uWSGIWorker1Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/workflows.py", line 447, in workflow_dict
    ret_dict = self.workflow_contents_manager.workflow_to_dict(trans, stored_workflow, style=style, version=version)
  File "lib/galaxy/managers/workflows.py", line 474, in workflow_to_dict
    wf_dict = self._workflow_to_dict_run(trans, stored, workflow=workflow)
  File "lib/galaxy/managers/workflows.py", line 519, in _workflow_to_dict_run
    module_injector.inject(step, steps=workflow.steps, exact_tools=False)
  File "lib/galaxy/workflow/modules.py", line 1515, in inject
    step.upgrade_messages = module.check_and_update_state()
  File "lib/galaxy/workflow/modules.py", line 1024, in check_and_update_state
    return self.tool.check_and_update_param_values(self.state.inputs, self.trans, workflow_building_mode=True)
  File "lib/galaxy/tools/__init__.py", line 1627, in check_and_update_param_values
    visit_input_values(self.inputs, values, validate_inputs)
  File "lib/galaxy/tools/parameters/__init__.py", line 162, in visit_input_values
    visit_input_values(input.cases[values['__current_case__']].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "lib/galaxy/tools/parameters/__init__.py", line 166, in visit_input_values
    visit_input_values(input.inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "lib/galaxy/tools/parameters/__init__.py", line 154, in visit_input_values
    visit_input_values(input.inputs, d, callback, new_name_prefix, new_label_prefix, parent_prefix=new_name_prefix, **payload)
  File "lib/galaxy/tools/parameters/__init__.py", line 168, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "lib/galaxy/tools/parameters/__init__.py", line 131, in callback_helper
    new_value = callback(**args)
  File "lib/galaxy/tools/__init__.py", line 1613, in validate_inputs
    value, error = check_param(request_context, input, value, context)
  File "lib/galaxy/tools/parameters/__init__.py", line 185, in check_param
    value = param.from_json(value, trans, param_values)
  File "lib/galaxy/tools/parameters/basic.py", line 850, in from_json
    legal_values = self.get_legal_values(trans, other_values)
  File "lib/galaxy/tools/parameters/basic.py", line 838, in get_legal_values
    return set(v for _, v, _ in self.options.get_options(trans, other_values))
  File "lib/galaxy/tools/parameters/dynamic_options.py", line 708, in get_options
    options = self.get_fields(trans, other_values)
  File "lib/galaxy/tools/parameters/dynamic_options.py", line 658, in get_fields
    if os.path.getsize(path) < 1048576:
  File "/home/galaxy/galaxy/.venv/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: ''
```
It doesn't always happen though.

**Comment by bernt-matthias** [comment]
Can you tell us the tool and it's version. Also which galaxy version are you using?

Can you share the workflow?

**Comment by mvdbeek** [comment]
@qiagu any chance you can reproduce this error ?

**Comment by qiagu** [comment]
Ah, this happened long time ago. I can't recall all the details and can't guarantee I am able to reproduce the problem. Let me close this issue for now and reopen it when I meet similar problem again?

**Comment by qiagu** [comment]
Sorry, I missed the reply from @bernt-matthias.
