### ISSUE TITLE
TS does not handle api/users/current correctly

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#9008]
Possibly related to recent refactorings.

```
galaxy.web.framework.decorators ERROR 2019-11-18 21:28:07,413 [p:43202,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 157, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/tool_shed/webapp/api/users.py", line 112, in show
    user = suc.get_user(trans.app, id)
  File "lib/galaxy/tool_shed/util/shed_util_common.py", line 169, in get_user
    return sa_session.query(app.model.User).get(app.security.decode_id(id))
  File "lib/galaxy/security/idencoding.py", line 84, in decode_id
    return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
127.0.0.1 - - [18/Nov/2019:21:28:07 -0400] "GET /api/users/current HTTP/1.1" 500 - "http://127.0.0.1:9009/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
```

**Comment by jmchilton** [comment]
I think this has been fixed - seems to work for me now. 

```
{"model_class": "User", "id": "1de29d50c3c44272", "username": "devteam", "url": "/api/users/1de29d50c3c44272"}
```
