### ISSUE TITLE
Tool parameter casting issues

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9148]
This includes https://github.com/galaxyproject/galaxy/pull/9144, seen in test 3 of bowtie2:
```
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/util/__init__.py", line 1039, in unicodify
    value = text_type(value)
  File "/Users/mvandenb/src/galaxy/.venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1576771185_4247239_70901.py", line 680, in respond
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 94, in __ne__
    return not self == other
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 91, in __eq__
    return self._get_cast_value(other) == other
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 88, in _get_cast_value
    return cast.get(self.input.type, str)(self)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 117, in __int__
    return int(float(self))
  File "/Users/mvandenb/src/galaxy/lib/galaxy/tools/wrappers.py", line 120, in __float__
    return float(str(self))
ValueError: could not convert string to float:
```

**Comment by mvdbeek** [comment]
```
diff --git a/lib/galaxy/tools/wrappers.py b/lib/galaxy/tools/wrappers.py
index 3f1b3eabf8..75f81390ba 100644
--- a/lib/galaxy/tools/wrappers.py
+++ b/lib/galaxy/tools/wrappers.py
@@ -77,7 +77,7 @@ class InputValueWrapper(ToolParameterValueWrapper):
         if self.input.type == 'boolean' and isinstance(other, string_types):
             return str(self)
         # For backward compatibility, allow `$wrapper != ""` for optional non-text param
-        if self.input.optional and self.value is None and isinstance(other, string_types):
+        if self.input.optional and self.value is None and self.input_type != 'boolean':
             return str(self)
         cast = {
             'text': str,
```
would work ... since neither int or float could be cast if the value is None anyway.
