### ISSUE TITLE
Accessing certain datasets throws uncaught exception

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#9164]
At this point, on multiple occasions, accessing a specific dataset throws:
```
[pid: 69|app: 0|req: 21232/21358] 10.0.8.7 () {60 vars in 1752 bytes} [Tue Dec 24 14:33:31 2019] GET /default/galaxy/api/histories/c385e49b9fe1853c/contents?order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2019-12-24T14%3A33%3A26.635Z&qv=False&qv=False => generated 2 bytes in 28 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
galaxy.web.framework.decorators ERROR 2019-12-24 14:33:33,877 [p:69,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
File "/galaxy/server/lib/galaxy/web/framework/decorators.py", line 282, in decorator
rval = func(self, trans, *args, **kwargs)
File "/galaxy/server/lib/galaxy/webapps/galaxy/api/history_contents.py", line 176, in show
return self.__show_dataset(trans, id, **kwd)
File "/galaxy/server/lib/galaxy/webapps/galaxy/api/history_contents.py", line 263, in __show_dataset
**self._parse_serialization_params(kwd, 'detailed'))
File "/galaxy/server/lib/galaxy/managers/base.py", line 692, in serialize_to_view
return self.serialize(item, all_keys, **context)
File "/galaxy/server/lib/galaxy/managers/hdas.py", line 372, in serialize
return super(HDASerializer, self).serialize(hda, keys, user=user, **context)
File "/galaxy/server/lib/galaxy/managers/datasets.py", line 612, in serialize
serialized = super(DatasetAssociationSerializer, self).serialize(dataset_assoc, keys, **context)
File "/galaxy/server/lib/galaxy/managers/base.py", line 605, in serialize
returned[key] = self.serializers[key](item, key, **context)
File "/galaxy/server/lib/galaxy/managers/datasets.py", line 517, in <lambda>
return lambda i, k, **c: serializer(i.dataset, key or k, **c)
File "/galaxy/server/lib/galaxy/managers/datasets.py", line 221, in serialize_permissions
'manage' : [self.app.security.encode_id(perm.role.id) for perm in management_permissions],
AttributeError: 'NoneType' object has no attribute 'id'
```
I can't force this to happen at will but once it happens for a given dataset, it continues to happen forever on the same dataset. This specific one is for a BWA-MEM output and it seems the only lead is that the reference used is a custom-built one using the BWA DM. IIRC, one of the inputs used to build the reference was shared with a user, who then uploaded another piece of the ref and ran the DM. Just throwing out there anything that might help...

**Comment by guerler** [comment]
Should be fixed by #9168. Please re-open if not.
