### ISSUE TITLE
Unable to edit dataset attributes

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#9165]
Trying to edit attributes of any dataset leads to the following:
```
[pid: 69|app: 0|req: 21388/21516] 10.0.8.7 () {60 vars in 1524 bytes} [Tue Dec 24 14:42:34 2019] GET /default/galaxy/api/histories/c385e49b9fe1853c/contents/datasets/b2b14618626cd012 => generated 101563 bytes in 44 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
galaxy.web.framework.decorators ERROR 2019-12-24 14:42:35,857 [p:69,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
File "/galaxy/server/lib/galaxy/web/framework/decorators.py", line 157, in decorator
rval = func(self, trans, *args, **kwargs)
File "/galaxy/server/lib/galaxy/webapps/galaxy/controllers/dataset.py", line 268, in get_edit
all_roles = [(r.name, trans.security.encode_id(r.id)) for r in trans.app.security_agent.get_legitimate_roles(trans, data.dataset, 'root')]
File "/galaxy/server/lib/galaxy/model/security.py", line 214, in get_legitimate_roles
return self.get_all_roles(trans, cntrller)
File "/galaxy/server/lib/galaxy/model/security.py", line 80, in get_all_roles
return self.sort_by_attr([role for role in roles], 'name')
File "/galaxy/server/lib/galaxy/model/security.py", line 46, in sort_by_attr
intermed = [(getattr(v, attr), i, v) for i, v in enumerate(seq)]
AttributeError: 'NoneType' object has no attribute 'name'
```
If case it's relevant, this instance is configured to use OIDC for auth. And it's Galaxy 19.09.

**Comment by hexylena** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/8244
