### ISSUE TITLE
Inifinite loop in job failure method

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#9272]
There are a fair number of cases where failures in the `fail_job()` method:

```pytb
galaxy.objectstore CRITICAL 2020-01-28 12:58:35,885 Error copying /galaxy-repl/main/jobdir/026/631/26631908/metadata/metadata_temp_file_5t_twwuv to /galaxy-repl/main/files/_metadata_files/002/842/metadata_2842448.dat: [Errno 2] No such file or directory: '/galaxy-repl/main/jobdir/026/631/26631908/metadata/metadata_temp_file_5t_twwuv'
galaxy.jobs.runners ERROR 2020-01-28 12:58:35,904 (26631908) Unhandled exception calling fail_job
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 137, in run_next
    method(arg)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 475, in fail_job
    job_state.job_wrapper.fail(getattr(job_state, 'fail_message', 'Job failed'), exception=exception)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1293, in fail
    self.tool.job_failed(self, message, exception)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/__init__.py", line 2467, in job_failed
    return self.exec_after_process(job_wrapper.app, inp_data, {}, job_wrapper.get_param_dict(), job=job)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/__init__.py", line 2441, in exec_after_process
    external_metadata.load_metadata(dataset, name, sa_session, working_directory=working_directory)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/metadata/__init__.py", line 212, in load_metadata
    self._load_metadata_from_path(dataset, metadata_output_path, working_directory, remote_metadata_directory)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/metadata/__init__.py", line 89, in _load_metadata_from_path
    dataset.metadata.from_JSON_dict(metadata_output_path, path_rewriter=path_rewriter)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/metadata.py", line 186, in from_JSON_dict
    value = param.from_external_value(external_value, dataset, **from_ext_kwds)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/metadata.py", line 566, in from_external_value
    alt_name=os.path.basename(mf.file_name))
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/objectstore/__init__.py", line 566, in update_from_file
    return self._call_method('update_from_file', obj, ObjectNotFound, True, **kwargs)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/objectstore/__init__.py", line 766, in _call_method
    return self.backends[object_store_id].__getattribute__(method)(obj, **kwargs)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/objectstore/__init__.py", line 494, in update_from_file
    raise ex
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/objectstore/__init__.py", line 490, in update_from_file
    shutil.copy(file_name, path)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/galaxy-repl/main/jobdir/026/631/26631908/metadata/metadata_temp_file_5t_twwuv'
```
Cause an infinite loop on failing the job because there's a an exception in attempting to clean up:

```pytb
galaxy.jobs.runners.drmaa ERROR 2020-01-28 12:58:36,094 (26631908/21246355) User killed running job, but error encountered removing from DRM queue
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/drmaa.py", line 360, in stop_job
    self.ds.kill(ext_id)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/pulsar/managers/util/drmaa/__init__.py", line 73, in kill
    return DrmaaSession.session.control(str(external_job_id), JobControlAction.TERMINATE)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/drmaa/session.py", line 381, in control
    c(drmaa_control, jobId, string_to_control_action(operation))
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/drmaa/helpers.py", line 302, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
drmaa.errors.InternalException: code 1: slurm_terminate_job error: Job/step already completing or completed,job_id: 21246355
```

This cycle repeats indefinitely.

**Comment by mvdbeek** [comment]
At least the first exception should be fixed by https://github.com/galaxyproject/galaxy/pull/9395.
I'm not sure if we need to fix the second exception and how, `Job/step already completing or completed,job_id: 21246355` sounds like we should just catch the exception and not fail here ?

**Comment by dannon** [comment]
We ran into the same with the PJA action failing, causing fail() to fail, repeating.  It does seem like we should just catch the fail() exception, set datasets to error, job state to fail, and exit.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/11673 should cover this now

**Comment by natefoo** [comment]
Thanks @mvdbeek !
