### ISSUE TITLE
Exception during workflow scheduling

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#9284]
I'm on 19.09 (47c5a0e108) and had the following error when executing a dada2 workflow (https://github.com/galaxyproject/iwc/pull/14): 

```
Traceback (most recent call last):
  File "lib/galaxy/workflow/run.py", line 353, in replacement_for_connection
    replacement = step_outputs[output_name]
KeyError: 'stable_uniques'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "lib/galaxy/workflow/modules.py", line 1189, in execute
    collection_info = self.compute_collection_info(progress, step, all_inputs)
  File "lib/galaxy/workflow/modules.py", line 309, in compute_collection_info
    progress, step, all_inputs
  File "lib/galaxy/workflow/modules.py", line 327, in _find_collections_to_match
    data = progress.replacement_for_input(step, input_dict)
  File "lib/galaxy/workflow/run.py", line 337, in replacement_for_input
    replacement = self.replacement_for_connection(connection[0], is_data=is_data)
  File "lib/galaxy/workflow/run.py", line 364, in replacement_for_connection
    raise Exception(message)
Exception: Workflow evaluation problem - failed to find output_name stable_uniques in step_outputs {'stable_sequencetable': <galaxy.model.HistoryDatasetAssociation(213519) at 0x2b1e5133c668>}
```

to the user in the history it appeared that the workflow was executed fine .. but there was some error / error message during the scheduling.

Looks a bit like https://github.com/galaxyproject/galaxy/issues/1724 .. but this should be fixed already.

**Comment by jmchilton** [comment]
@mvdbeek did a lot of work to make these conditional output problems less of an issue. Is it possible if you rebuilt the workflow this wouldn't be an issue?

xref https://github.com/galaxyproject/galaxy/issues/10006#issuecomment-661187424 - I suspect dynamic outputs are the problem here?

**Comment by bernt-matthias** [comment]
@jmchilton .. so your suggestion is to rebuild the workflow from scratch and test again?

**Comment by jmchilton** [comment]
Rebuild it from scratch maybe or just reconnect the outputs that are conditional.

**Comment by mvdbeek** [comment]
And since November we've had another large round of fixes ... I'm gonna say let's close it for now.
