### ISSUE TITLE
Tools running on containers can fail when not having access to a writable home directory

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#9401]
This happened to us in particular with our scanpy-cli tools (one of them for instance https://toolshed.g2.bx.psu.edu/repository?user_id=1aaf1010134c91da). One of the dependencies in the container apparently uses numba which does JIT compilation. When this was triggered inside the biocontainer generated from bioconda in a setup where the user running the job is not the root user, then the job failed with:

```
Traceback (most recent call last):
  File "/usr/local/bin/scanpy-read-10x", line 6, in <module>
    from scanpy_scripts.cmds import READ_CMD
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/__init__.py", line 15, in <module>
    from . import lib
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/lib/__init__.py", line 5, in <module>
    from ._read import read_10x
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/lib/_read.py", line 6, in <module>
    import scanpy as sc
  File "/usr/local/lib/python3.6/site-packages/scanpy/__init__.py", line 31, in <module>
    from . import tools as tl
  File "/usr/local/lib/python3.6/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing._simple import pca
  File "/usr/local/lib/python3.6/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/usr/local/lib/python3.6/site-packages/scanpy/preprocessing/_recipes.py", line 4, in <module>
    from . import _simple as pp
  File "/usr/local/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py", line 1040, in <module>
    replace: bool = True, inplace: bool=False):
  File "/usr/local/lib/python3.6/site-packages/numba/decorators.py", line 194, in wrapper
    disp.enable_caching()
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 679, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/local/lib/python3.6/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/local/lib/python3.6/site-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '_downsample_array': no locator available for file '/usr/local/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py'
```

Solution suggested by @mvdbeek was to set the tool profile to 18.01, and this did sort the issue.

However, having to modify tools for this might be problematic in some scenarios, and probably we should have an easier solution to apply across the board. A few ideas of more systematic solutions could be:

- Have a general Galaxy setting that sets the default profile for all those tools that don't have a profile set, meaning that we could have enacted the change without changing a single tool. This could be done in a way that if the profile is not compatible with a particular tool this could be iteratively downgraded.
- (proposed by @mvdbeek) Provide by default the writable home directory that `profile="18.01"` triggers for any tool that is running as a container.

Thanks!

**Comment by pcm32** [comment]
I'm getting this for other tools as well @mvdbeek, and changing the profile and leaving tools behind that don't work is not ideal. Could you please advise on where I could PR a change in the setup so that the writable `/home` is provided to all container based workload? Thanks!

**Comment by mvdbeek** [comment]
I can take care of this, but it would be good if you could contribute those changes back to the original authors and let them know why it's good to set a reasonable `profile` version.

**Comment by pcm32** [comment]
We are the original authors (blushed), but we have like ~70 tool wrappers; changing them all and leaving all the previous versions in a non-working state (for some container setups), which are tagged in various workflows that we have, is not ideal. We will clearly set profiles as we go from now on. And of course, if it helps, I'm happy to do the PR legwork with a pointer of where I need to start.

**Comment by pcm32** [comment]
otherwise, thanks for taking care of it!

**Comment by mvdbeek** [comment]
OK, looking at the code we probably need to move some things around, so I don't think we should squeeze that into 20.01. That said there is a solution that should work today:
Set `<param id="shared_home_dir">$_GALAXY_JOB_HOME_DIR</param>` in your job destination.

**Comment by pcm32** [comment]
Using @mvdbeek suggestion works! My example of usage is here: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/feature/move_to_helm_chart_v3/rules/k8s_destinations.py#L90
