### ISSUE TITLE
tool stdout/stderr will crash tool

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#9428]
I just found this in our bug reports. It seems that a wired character in the stdout/stderr can lead to a crashing tool.

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 509, in _finish_or_resubmit_job
    self.sa_session.flush()
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/galaxy/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
DataError: (psycopg2.errors.CharacterNotInRepertoire) invalid byte sequence for encoding "UTF8": 0xed 0xb7 0xbc

[SQL: UPDATE job SET update_time=%(update_time)s, job_messages=%(job_messages)s, job_stdout=%(job_stdout)s, job_stderr=%(job_stderr)s, tool_stdout=%(tool_stdout)s, tool_stderr=%(tool_stderr)s WHERE job.id = %(job_id)s]
[parameters: {'update_time': datetime.datetime(2020, 2, 20, 15, 5, 15, 856001), 'job_id': 7023172, 'job_stderr': u'', 'tool_stderr': u'', 'tool_stdout': u'\n\n     ______  ____   ____  ____   ____  ______  __ __\n    |      ||    \\ |    ||    \\ |    ||      ||  |  |\n    |      ||  D  ) |  | |  _  |  ... (24119 characters truncated) ... ::run_normalization(200, ARRAY(0x561c57a8e5a8), ARRAY(0x561c57a8e548)) called at /usr/local/tools/_conda/envs/__trinity@2.9.1/bin/Trinity line 1351\n', 'job_messages': <psycopg2.extensions.Binary object at 0x7f6fc4b5cbe8>, 'job_stdout': u''}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by mvdbeek** [comment]
Hmm, that is interesting, do you know what the text was / any way you can share the history (just the inputs and the dataset would be enough). We strip unicode control characters now, but `0xed 0xb7 0xbc` looks like it really is something binary.

**Comment by mvdbeek** [comment]
So actually it probably isn't stdout or stderr, those get passed through unicodify which will replace non-utf8 characters. It should be the job_messages object that is at fault.

**Comment by mvdbeek** [comment]
And even those contents are sanitized at https://github.com/mvdbeek/galaxy/blame/38d2eecae65e5dfd28c60407bdd3e316bbb86727/lib/galaxy/tool_util/output_checker.py#L53, so I don't understand how that is possible.

**Comment by mvdbeek** [comment]
Pretty sure that's fixed in https://github.com/galaxyproject/galaxy/pull/9430
