### ISSUE TITLE
Segmentation Fault on run.sh

### ISSUE THREAD

**Issue by vinita84** [galaxyproject/galaxy#9472]
**sh run.sh throws the following error:**
`The Galaxy client has not yet been built and will be built now.
Installing node into /home/vinitab/workspaces/AMP-GALAXY-GIT/galaxy/.venv with nodeenv.
 * Install prebuilt node (10.13.0) ..... done.
 * Appending data to /home/vinitab/workspaces/AMP-GALAXY-GIT/galaxy/.venv/bin/activate
 * Appending data to /home/vinitab/workspaces/AMP-GALAXY-GIT/galaxy/.venv/bin/activate.fish
Installing yarn into /home/vinitab/workspaces/AMP-GALAXY-GIT/galaxy/.venv with npm.
Segmentation fault (core dumped)
`

**Even the make client doesn't work** 
vinitab@vinita-dell:~/workspaces/AMP-GALAXY-GIT/galaxy$ make client
`Traceback (most recent call last):
  File "scripts/bootstrap_history.py", line 705, in <module>
    main(sys.argv)
  File "scripts/bootstrap_history.py", line 466, in main
    raise Exception("Requests library not found, please pip install requests")
Exception: Requests library not found, please pip install requests
cd client && yarn install --network-timeout 300000 --check-files
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @handsontable/vue@2.0.0" has incorrect peer dependency "handsontable@^4.0.0".
warning "vue-styleguidist > webpack-dev-server@2.11.3" has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "vue-styleguidist > vue-webpack-loaders > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
warning "vue-styleguidist > vue-webpack-loaders > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "vue-styleguidist > vue-webpack-loaders > html-webpack-plugin@2.30.1" has incorrect peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "vue-styleguidist > webpack-dev-server > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
[1/6] ⡀ bootstrap-vue
[2/6] ⡀ phantomjs-prebuilt
[3/6] ⡀ node-sass
[4/6] ⡀ sinon
error /home/vinitab/workspaces/AMP-GALAXY-GIT/galaxy/client/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 139
Command: node install.js
Arguments: 

make: *** [Makefile:144: node-deps] Error 139
`

**Comment by quacksawbones** [comment]
I managed to find a workaround for this. I am using Ubuntu 20.04 (upgraded from 10.04 with WSL on Windows 10) and installing Galaxy 20.01. Instructions source here: https://linuxize.com/post/how-to-install-node-js-on-ubuntu-20-04/

I removed the previously installed nodejs and npm (`sudo apt remove nodejs npm`) and installed node 12.x from NodeSource (`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`, then `sudo apt install nodejs`). I then removed the previosu galaxy virtual environment ('sudo rm -r .venv') and reran run.sh. It installed without a hitch.

I vaguely remember reading something about npm or node being dodgy in Ubuntu 20.04, but I can't find the article now. Hope this helps.
