### ISSUE TITLE
Login problem after upgrading to 20.01

### ISSUE THREAD

**Issue by MarijaDur** [galaxyproject/galaxy#9506]
Hi,
I faced some troubles with login after I did upgrade to new galaxy 20.01:

```
`LDAP authenticate: whoami is u:MUGAD\o_durdevic
galaxy.auth.providers.ldap_ad DEBUG 2020-03-09 16:42:36,023 [p:251282,w:3,m:0] [uWSGIWorker3Core3] LDAP authentication successful
galaxy.web.framework.decorators ERROR 2020-03-09 16:42:36,037 [p:251282,w:3,m:0] [uWSGIWorker3Core3] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 122, in login
    return self.__validate_login(trans, payload, **kwd)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 178, in __validate_login
    trans.handle_user_login(user)
  File "lib/galaxy/web/framework/webapp.py", line 721, in handle_user_login
    self.app.security_agent.create_user_role(user, self.app)
  File "lib/galaxy/model/security.py", line 666, in create_user_role
    self.create_private_user_role(user)
  File "lib/galaxy/model/security.py", line 685, in create_private_user_role
    self.sa_session.flush()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_role_name"
DETAIL:  Key (name)=(marija.durdevic@medunigraz.at) already exists.

[SQL: INSERT INTO role (create_time, update_time, name, description, type, deleted) VALUES (%(create_time)s, %(update_time)s, %(name)s, %(description)s, %(type)s, %(deleted)s) RETURNING role.id]
[parameters: {'update_time': datetime.datetime(2020, 3, 9, 15, 42, 36, 35168), 'name': u'marija.durdevic@medunigraz.at', 'deleted': False, 'create_time': datetime.datetime(2020, 3, 9, 15, 42, 36, 35151), 'type': 'private', 'description': u'Private Role for marija.durdevic@medunigraz.at'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
10.208.17.53 - - [09/Mar/2020:16:42:35 +0200] "POST /user/login HTTP/1.1" 500 - "https://galaxy.medunigraz.at/root/login?redirect=%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
[pid: 251282|app: 0|req: 6/26] 10.208.17.53 () {58 vars in 1136 bytes} [Mon Mar  9 16:42:35 2020] POST /user/login => generated 71 bytes in 42 msecs (HTTP/1.1 500) 3 headers in 158 bytes (1 switches on core 3)
galaxy.webapps.galaxy.controllers.user DEBUG 2020-03-09 16:42:39,628 [p:251282,w:3,m:0] [uWSGIWorker3Core2] trans.app.config.auth_config_file: /home/galaxy/galaxy/config/auth_conf.xml
`
```

Any idea what could be and how to solve it?

Thanks,
Marija

**Comment by nsoranzo** [comment]
@MarijaDur Thanks for the report, this seems related to https://github.com/galaxyproject/galaxy/pull/9168 

Can you run the following SQL query on your database and see if you see duplications or anything else suspicious?

```sql
SELECT * FROM role LEFT OUTER JOIN user_role_association ON role.id = user_role_association.role_id LEFT OUTER JOIN galaxy_user ON user_role_association.user_id = galaxy_user.id WHERE role.name ILIKE 'marija.durdevic@medunigraz.at';
```

**Comment by jmchilton** [comment]
I'm going to hope this was fixed, please ping us if you're still having problems. Very sorry about issues 😞
