### ISSUE TITLE
Jenkins needs docker for selenium admin containers test

### ISSUE THREAD

**Issue by davebx** [galaxyproject/galaxy#9624]
Per #3241, the admin panel's dependency containers grid needs selenium tests, but the test fails on jenkins because the testing vm can't find docker:

See also [console output](https://jenkins.galaxyproject.org/job/docker-selenium-py3/3729/console) for a prior test in #9618 

```
galaxy.web.framework.decorators: ERROR: Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/web/framework/decorators.py", line 295, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy/lib/galaxy/web/framework/decorators.py", line 101, in decorator
    return func(self, trans, *args, **kwargs)
  File "/galaxy/lib/galaxy/webapps/galaxy/api/container_resolution.py", line 84, in resolve_toolbox
    return self._view.resolve_toolbox(**kwds)
  File "/galaxy/lib/galaxy/tool_util/deps/views.py", line 391, in resolve_toolbox
    rval.append(self.resolve(tool_id=tool_id, **resolve_kwds))
  File "/galaxy/lib/galaxy/tool_util/deps/views.py", line 367, in resolve
    **find_best_kwds
  File "/galaxy/lib/galaxy/tool_util/deps/containers.py", line 58, in resolve
    return self.container_registry.resolve(enabled_container_types, tool_info, **kwds)
  File "/galaxy/lib/galaxy/tool_util/deps/containers.py", line 257, in resolve
    container_description = container_resolver.resolve(enabled_container_types, tool_info, resolution_cache=resolution_cache)
  File "/galaxy/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 351, in resolve
    return docker_cached_container_description(targets, self.namespace, hash_func=self.hash_func, shell=self.shell, resolution_cache=resolution_cache)
  File "/galaxy/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 203, in docker_cached_container_description
    cached_images = list_docker_cached_mulled_images(namespace, hash_func=hash_func, resolution_cache=resolution_cache)
  File "/galaxy/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 71, in list_docker_cached_mulled_images
    images_and_versions = unicodify(subprocess.check_output(command)).strip().splitlines()
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
```

**Comment by davebx** [comment]
I believe this is within the wheelhouses of, among others, @natefoo and @mvdbeek (ping)

**Comment by nsoranzo** [comment]
I guess you meant Jenkins instead of TravisCI in the issue title?

**Comment by davebx** [comment]
Exactly correct

**Comment by nsoranzo** [comment]
Actually one option could be to move also these tests to GitHub Workflows.

**Comment by davebx** [comment]
#9652 resolves this
