### ISSUE TITLE
problems in submit slurm jobs with real_system_username

### ISSUE THREAD

**Issue by lihang598602** [galaxyproject/galaxy#9671]
Someone had succefully configure galaxy with slurm clusters?  I‘m configuring galaxy v20.01 with a slurm cluster, following the guidence from https://docs.galaxyproject.org/en/master/admin/cluster.html#submitting-jobs-as-the-real-user. 
 Deliverying jobs with galaxy common user works well, while  deliverying jobs with real_system_username failed with permission errors.I found that jobs were successfully submitted, and the  ownership of "job_working_directory" seems  changed as expected, to "real_system_username" and then to galaxy common user. But the fold "file_path" got empty result files,with permission  rwxr-x---.

**the following was a  error log for simple upload job:**
**Error from webserver:**
        Traceback (most recent call last):
          File "/home/galaxy/galaxy/tools/data_source/upload.py", line 326, in <module>
            __main__()
          File "/home/galaxy/galaxy/tools/data_source/upload.py", line 319, in __main__
           ........
          File "/home/galaxy/galaxy/.venv/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
            fd = _os.open(file, flags, 0o600)
        PermissionError: [Errno 13] Permission denied: '/home/galaxy/galaxy/database/files/000/data_id_62_upload_tyl_wxu1'

**Error from "galaxy.log":**
galaxy.jobs.runners.drmaa INFO 2020-04-28 14:48:17,080 [p:12540,w:2,m:0] [SlurmRunner.work_thread-0] Running command ['sudo', '-E', 'LD_LIBRARY_PATH=/opt/slurm/lib/slurm:/opt/slurm/lib', 'DRMAA_LIBRARY_PATH=/home/slurm/slurm-drmaa-1.1.1/
lib/libdrmaa.so', 'PYTHONPATH=/home/galaxy/galaxy/lib:/home/galaxy/galaxy/.venv/lib/python3.6/site-packages:$PYTHONPATH', 'scripts/drmaa_external_runner.py', '--assign_all_groups', '1006', '/home/galaxy/slurm/63.jt_json']
galaxy.jobs.runners.drmaa INFO 2020-04-28 14:48:17,158 [p:12540,w:2,m:0] [SlurmRunner.work_thread-0] (63) queued as 59
t #310c [    28.02] -> drmaa_job_ps(job_id=59)
t #310c [    28.02] -> fsd_job_set_get(job_id=59)
........
t #310c [    30.08] <- fsd_job_release
t #310c [    30.08] <- drmaa_job_ps(job_id=59) =0: remote_ps=running (0x20)
galaxy.jobs.runners.slurm ERROR 2020-04-28 14:48:23,357 [p:12540,w:2,m:0] [SlurmRunner.monitor_thread] (63/59) Failure in SLURM _complete_terminal_job(), job final state will be: done
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/slurm.py", line 161, in _complete_terminal_job
    with open(ajs.error_file, 'r') as rfh:
PermissionError: [Errno 13] Permission denied: '/home/galaxy/galaxy/database/database/jobs_directory/000/63/galaxy_63.e'

**my configures:** 
/etc/sudoers:
galaxy  ALL = (root) NOPASSWD: SETENV: /home/galaxy/galaxy/scripts/drmaa_external_runner.py
galaxy  ALL = (root) NOPASSWD: SETENV: /home/galaxy/galaxy/scripts/drmaa_external_killer.py
galaxy  ALL = (root) NOPASSWD: SETENV: /home/galaxy/galaxy/scripts/external_chown_script.py
galaxy  ALL = (root) NOPASSWD: SETENV: /home/galaxy/galaxy/.venv/bin/python

galaxy.yml:
drmaa_external_runjob_script: sudo -E LD_LIBRARY_PATH="***" DRMAA_LIBRARY_PATH="***"   PYTHONPATH="***"  scripts/drmaa_external_runner.py --assign_all_groups

drmaa_external_killjob_script: sudo -E LD_LIBRARY_PATH="***"  DRMAA_LIBRARY_PATH=  "***"  PYTHONPATH="***"  scripts/drmaa_external_killer.py

external_chown_script: sudo -E  LD_LIBRARY_PATH="***"  DRMAA_LIBRARY_PATH= "***" scripts/external_chown_script.py

real_system_username: username
outputs_to_working_directory: ture
environment_setup_file: '/etc/profile.d/slurm.sh'

/etc/profile.d/slurm.sh:
PATH=/opt/slurm/bin:$PATH
PATH=/opt/slurm/sbin:$PATH
PATH=/home/galaxy/galaxy/.venv/bin:$PATH
export PATH
LD_LIBRARY_PATH=/opt/slurm/lib/slurm:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=/opt/slurm/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
export DRMAA_LIBRARY_PATH=/home/slurm/slurm-drmaa-1.1.1/lib/libdrmaa.so
export PYTHONPATH=/home/galaxy/galaxy/lib:/home/galaxy/galaxy/.venv/lib/python3.6/site-packages/:$PYTHONPATH

**Comment by lihang598602** [comment]
I had solved the problem, the umask value which I neglected must be set to 022 or 027. It should be  modified in /etc/profile, in both manage and compute nodes
