### ISSUE TITLE
run.sh stalling 

### ISSUE THREAD

**Issue by herbercr** [galaxyproject/galaxy#9804]
Ive had issues just installing galaxy because it keeps stalling. I thought i had finally got it installed but when i change the config file- it wont make my account admin even when its changed. I tried run.sh again to see if I installed it correctly and I got this warning
 
*** WARNING: you are running uWSGI without its master process manager ***

and it stalls at 
galaxy.model.database_heartbeat DEBUG 2020-05-21 10:43:15,574 [p:1239,w:1,m:0] [database_heartbeart_main.web.1.thread] 
main.web.1 is config watcher

I then changed the https from local to http: 0.0.0.0 and now I get stalling at the same place but now with the error below occurring right before.

 `Traceback (most recent call last):                                                                                      
File "lib/galaxy/web_stack/__init__.py", line 626, in _do_uwsgi_postfork                                                f(*args, **kwargs)                                                                                                  
File "lib/galaxy/webapps/galaxy/buildapp.py", line 206, in postfork_setup                                               app.application_stack.log_startup()                                                                                 
File "lib/galaxy/web_stack/__init__.py", line 476, in log_startup                                                       
for s in UWSGIApplicationStack._serving_on():                                                                       
File "lib/galaxy/web_stack/__init__.py", line 298, in _serving_on                                                       yield UWSGIApplicationStack._socket_opt_to_str(opt, val)                                                           
File "lib/galaxy/web_stack/__init__.py", line 276, in _socket_opt_to_str                                                host, port = val.rsplit(':', 1)                                                                                   
ValueError: not enough values to unpack (expected 2, got 1)`

I am trying to set up galaxy to use conda if that makes a difference. I also just upgraded my memory since before I was told it may be stalling due to lack of memory so now I know that's not the issue.

**Comment by mvdbeek** [comment]
Your config file is malformatted. If you want to expose port Galaxy on port 8080 you would need to say `http: 0.0.0.0:8080` in the uwsgi section. I'd recommend posting your question on https://help.galaxyproject.org.
