### ISSUE TITLE
Odd error uploading file on 20.05

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9839]
```
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 236, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 1096, in prepare
    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
  File "lib/galaxy/tools/evaluation.py", line 107, in set_compute_environment
    param_dict = self.build_param_dict(
  File "lib/galaxy/tools/evaluation.py", line 148, in build_param_dict
    self.__populate_wrappers(param_dict, input_datasets, job_working_directory)
  File "lib/galaxy/tools/evaluation.py", line 273, in __populate_wrappers
    self.__walk_inputs(self.tool.inputs, param_dict, wrap_input)
  File "lib/galaxy/tools/evaluation.py", line 184, in __walk_inputs
    do_walk(inputs, input_values)
  File "lib/galaxy/tools/evaluation.py", line 177, in do_walk
    do_walk(input.cases[current].inputs, values)
IndexError: list index out of range
```

I uploaded 10 datasets with manually pasted content, where the content was each time
```
A
B
C
```
one out of those 10 ended with the traceback above

**Comment by ic4f** [comment]
Cannot reproduce this. Tried 12 in a row, then same but resetting dialog after each. Running on my local linux. Not logged in as admin. Can you reproduce this?
