### ISSUE TITLE
traceback when executing workflow with large collection

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#9842]
```

Failed to schedule Workflow[id=9189,name=DNA PE +
 seq frag remap + contamination + aggregate v.0.2.1], problem occurred on WorkflowStep[index=14,type=tool].
Traceback (most recent call last):
  File "lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "lib/galaxy/workflow/modules.py", line 1279, in execute
    workflow_resource_parameters=resource_parameters
  File "lib/galaxy/tools/execute.py", line 96, in execute
    execute_single_job(execution_slice, completed_jobs[i])
  File "lib/galaxy/tools/execute.py", line 68, in execute_single_job
    execution_tracker.record_success(execution_slice, job, result)
  File "lib/galaxy/tools/execute.py", line 406, in record_success
    self.job_callback(job)
  File "lib/galaxy/workflow/modules.py", line 1277, in <lambda>
    job_callback=lambda job: self._handle_post_job_actions(step, job, invocation.replacement_dict),
  File "lib/galaxy/workflow/modules.py", line 1348, in _handle_post_job_actions
    self.trans.sa_session.flush()
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2446, in flush
    self._flush(objects)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2544, in _flush
    flush_context.execute()
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
    statement, params
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/home/galaxy/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near ")"
LINE 1: ..._reads.expected_genome_unmapped_both_mates_bam', (), '\x7b22...
                                                             ^
 [SQL: 'INSERT INTO history_dataset_association_history (history_dataset_association_id, update_time, version, name, extension, metadata, extended_metadata_id) VALUES (%(history_dataset_association_id)s, %(update_time)s, %(version)s, %(name)s, %(extension)s, %(_metadata)s, %(extended_metadata_id)s) RETURNING history_dataset_association_history.id'] [parameters: {'update_time': datetime.datetime(2020, 6, 1, 2, 39, 19, 993876), 'history_dataset_association_id': 5201205, 'extension': (), 'extended_metadata_id': None, '_metadata': <psycopg2.extensions.Binary object at 0x7f11c4ac2120>, 'version': 3, 'name': u'2020_05_15_100ng_13_Test3_B9.1.3e5_reads.expected_genome_unmapped_both_mates_bam'}] (Background on this error at: http://sqlalche.me/e/f405)
galaxy.workflow.run ERROR 2020-05-31 22:39:22,467 [p:5386,w:0,m:1] [WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
```

**Comment by bwlang** [comment]
this is on 19.05

**Comment by mvdbeek** [comment]
There's a good chance this has been fixed in the meantime. This does not seem to be related to large collections but the extension being a tuple.

**Comment by bwlang** [comment]
Hi @mvdbeek 

Thanks for your quick reply! 

I'll try to update soon... but I think i should mention - when I run this workflow on a small collection of 2 dataset pairs (instead of 96) it renders reliably, so I don't think this is related to simple bug in which a tuple is passed instead of a single value.

**Comment by mvdbeek** [comment]
The exception shows a tuple being passed as a value for the extension for HDA 5201205.

**Comment by jmchilton** [comment]
I suspect Marius was right and the problem was with metadata on one of the other pairs right?

**Comment by bwlang** [comment]
I guess i didn't understand Marius' point here... i think we can close this out.
