### ISSUE TITLE
Failed to execute scheduled workflow

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/galaxy#9843]
I am running several workflows with planemo (version 0.70.0) on a Galaxy instance (20.01).
For most of my workflows, it works fine but for some, I didn't find why, only some of the jobs are executed or only inputs datasets are uploaded after that, nothing happens and planemo is waiting forever.
I got the following error in galaxy handler logs when it happens:
```
galaxy.workflow.run ERROR 2020-06-03 10:04:06,200 Failed to schedule Workflow[id=827,name=GTN - Sequence Analyses - Mapping], problem occurred on WorkflowStep[index=2,type=tool].
Traceback (most recent call last):
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/modules.py", line 1691, in execute
    visit_input_values(tool.inputs, execution_state.inputs, callback, no_replacement_value=NO_REPLACEMENT, replace_optional_connections=True)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 171, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 140, in callback_helper
    input_values[input.name] = input.value
AttributeError: 'DataToolParameter' object has no attribute 'value'
galaxy.workflow.run ERROR 2020-06-03 10:04:06,234 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/run.py", line 190, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/run.py", line 266, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/workflow/modules.py", line 1691, in execute
    visit_input_values(tool.inputs, execution_state.inputs, callback, no_replacement_value=NO_REPLACEMENT, replace_optional_connections=True)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 171, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/shared/mfs/data/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 140, in callback_helper
    input_values[input.name] = input.value
AttributeError: 'DataToolParameter' object has no attribute 'value'
galaxy.workflow.scheduling_manager DEBUG 2020-06-03 10:04:06,284 Workflow invocation [489] scheduled

```

When I run the same workflow from Galaxy interface it works, but not when I run it from planemo.

**Comment by mvdbeek** [comment]
Make sure you connect all input datasets. The UI just fills in a compatible datasets, this doesn't work when running a workflow through the API.

**Comment by davidchristiany** [comment]
Yes I connected all input datasets, it is correcty uploaded in the step 0 and 1, the step 2 cause an error and use the dataset uploaded in step 0:
```
  "steps": {
    "0": {
      "annotation": "",
      "content_id": null,
      "errors": null,
      "id": 0,
      "input_connections": {},
      "inputs": [
        {
          "description": "",
          "name": "wt_H3K4me3_read1.fastqsanger"
        }
      ],
      "label": "R1",
      "name": "Input dataset",
      "outputs": [],
      "position": {
        "left": 204,
        "top": 333
      },
      "tool_id": null,
      "tool_state": "{\"name\": \"reads_1\"}",
      "tool_version": null,
      "type": "data_input",
      "uuid": "71f77373-c9b8-441c-bbf3-b168fbb69220",
      "workflow_outputs": [
        {
          "label": null,
          "output_name": "output",
          "uuid": "84ca7fba-f3a1-4b15-9d20-ce6468a0bd35"
        }
      ]
    },
    "1": {
      "annotation": "",
      "content_id": null,
      "errors": null,
      "id": 1,
      "input_connections": {},
      "inputs": [
        {
          "description": "",
          "name": "wt_H3K4me3_read2.fastqsanger"
        }
      ],
      "label": "R2",
      "name": "Input dataset",
      "outputs": [],
      "position": {
        "left": 200,
        "top": 458
      },
      "tool_id": null,
      "tool_state": "{\"name\": \"reads_2\"}",
      "tool_version": null,
      "type": "data_input",
      "uuid": "3da9f126-0edf-4243-88f7-e1d1528840f6",
      "workflow_outputs": [
        {
          "label": null,
          "output_name": "output",
          "uuid": "93a3c29c-fab2-407b-87dd-e49758644ddf"
        }
      ]
    },
    "2": {
      "annotation": "",
      "content_id": "toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1",
      "errors": null,
      "id": 2,
      "input_connections": {
        "input_file": {
          "id": 0,
          "output_name": "output"
        }
      },
      "inputs": [
        {
          "description": "runtime parameter for tool FastQC",
          "name": "limits"
        },
        {
          "description": "runtime parameter for tool FastQC",
          "name": "contaminants"
        },
        {
          "description": "runtime parameter for tool FastQC",
          "name": "adapters"
        }
      ],
      "label": null,
      "name": "FastQC",
      "outputs": [
        {
          "name": "html_file",
          "type": "html"
        },
        {
          "name": "text_file",
          "type": "txt"
        }
      ],
      "position": {
        "left": 608,
        "top": 147
      },
      "post_job_actions": {},
      "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1",
      "tool_shed_repository": {
        "changeset_revision": "e7b2202befea",
        "name": "fastqc",
        "owner": "devteam",
        "tool_shed": "toolshed.g2.bx.psu.edu"
      },
      "tool_state": "{\"min_length\": \"\\\"\\\"\", \"kmers\": \"\\\"7\\\"\", \"limits\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"input_file\": \"{\\\"__class__\\\": \\\"ConnectedValue\\\"}\", \"__page__\": null, \"adapters\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"__rerun_remap_job_id__\": null, \"contaminants\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"chromInfo\": \"\\\"/usr/local/galaxy/galaxy-dist/tool-data/shared/ucsc/chrom/?.len\\\"\", \"nogroup\": \"\\\"false\\\"\"}",
      "tool_version": "0.72+galaxy1",
      "type": "tool",
      "uuid": "003a08a2-3374-4d21-ac16-37e98704ef43",
      "workflow_outputs": [
        {
          "label": null,
          "output_name": "html_file",
          "uuid": "06217b29-26ad-458f-9892-fca118ab0aa8"
        },
        {
          "label": null,
          "output_name": "text_file",
          "uuid": "3a7cf686-5c98-45db-91c6-fef52f874201"
        }
      ]
    },
```
