### ISSUE TITLE
unicode error on planemo test using release 20.05

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#9868]
```
2020-06-11 19:04:26,650 ERROR [galaxy.queue_worker] Error running control task type: rebuild_toolbox_search_index
Traceback (most recent call last):
  File "/tmp/tmphwvnj7yy/galaxy-dev/lib/galaxy/queue_worker.py", line 388, in process_task
    result = f(self.app, **body['kwargs'])
  File "/tmp/tmphwvnj7yy/galaxy-dev/lib/galaxy/queue_worker.py", line 252, in rebuild_toolbox_search_index
    app.reindex_tool_search()
  File "/tmp/tmphwvnj7yy/galaxy-dev/lib/galaxy/config/__init__.py", line 1040, in reindex_tool_search
    self.toolbox_search.build_index(tool_cache=self.tool_cache)
  File "/tmp/tmphwvnj7yy/galaxy-dev/lib/galaxy/tools/search/__init__.py", line 92, in build_index
    writer.add_document(**add_doc_kwds)
  File "/home/berntm/.planemo/gx_venv_release_20.05/local/lib/python2.7/site-packages/whoosh/writing.py", line 1021, in add_document
    self._record("add_document", args, kwargs)
  File "/home/berntm/.planemo/gx_venv_release_20.05/local/lib/python2.7/site-packages/whoosh/writing.py", line 1001, in _record
    getattr(self.writer, method)(*args, **kwargs)
  File "/home/berntm/.planemo/gx_venv_release_20.05/local/lib/python2.7/site-packages/whoosh/writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/home/berntm/.planemo/gx_venv_release_20.05/local/lib/python2.7/site-packages/whoosh/fields.py", line 156, in index
    raise ValueError("%r is not unicode or sequence" % value)
ValueError: 'CONVERTER_sdf_to_smiles' is not unicode or sequence
```

**Comment by mvdbeek** [comment]
20.05 doesn't support python 2.7, but we do have to make planemo try harder to use a python 3 virtualenv. This should not be an issue on python 3.

**Comment by bernt-matthias** [comment]
Ahh. `--galaxy_python_version 3.7` fixes this and also the stalling issue I reported on gitter.
