### ISSUE TITLE
History export does not include dataset collections

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#987]
I recently downloaded a history and it did not include any of the dataset collection datasets. (This was an attempt to get around #740 until that's fixed)

**Comment by hexylena** [comment]
Seems to still be an issue.

**Comment by hexylena** [comment]
Happy belated 3rd birthday! :cake: 

Found this because it bit @shiltemann as well. Xref #6120

**Comment by hexylena** [comment]
This history fails: https://usegalaxy.eu/u/saskia/h/gmt-benchmarking---tutorial-samples-20

With an internal server error on 18.05 @jmchilton:

```
w.x.y.z - - [20/Nov/2018:13:52:45 +0200] "GET /history/export_archive?preview=True HTTP/1.1" 500 - "https://usegalaxy.eu/histories/list" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/batch.py", line 75, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "lib/galaxy/web/framework/middleware/translogger.py", line 71, in __call__
    return self.application(environ, replacement_start_response)
  File "lib/galaxy/web/framework/middleware/error.py", line 166, in __call__
    response = self.exception_handler(exc_info, environ)
  File "lib/galaxy/web/framework/middleware/error.py", line 181, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/paste/request.py", line 107, in parse_querystring
    strict_parsing=False)
  File "/usr/lib64/python2.7/urlparse.py", line 408, in parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/middleware/statsd.py", line 40, in __call__
    req = self.application(environ, start_response)
  File "/opt/galaxy/venv/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 142, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 221, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/history.py", line 1233, in export_archive
    self.queue_history_export(trans, history, gzip=gzip, include_hidden=include_hidden, include_deleted=include_deleted)
  File "lib/galaxy/web/base/controller.py", line 418, in queue_history_export
    history_exp_tool.execute(trans, incoming=params, history=history, set_output_hid=True)
  File "lib/galaxy/tools/__init__.py", line 1497, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/history_imp_exp.py", line 124, in execute
    include_deleted=incoming['include_deleted'])
  File "lib/galaxy/tools/imp_exp/__init__.py", line 495, in setup_job
    jobs_attrs_out.write(dumps(jobs_attrs, cls=HistoryDatasetAssociationEncoder))
  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "lib/galaxy/tools/imp_exp/__init__.py", line 374, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7fcd119cf110> is not JSON serializable
```

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/7367
