### ISSUE TITLE
Disassociating an external user prevents future login

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#9887]
Login with username and password and then connect an external identity via the manage third-party identities user preferences. Then dissociate the this external identity but try to login using it. The server returns the following exception:
```
Traceback (most recent call last):
  File "lib/galaxy/authnz/managers.py", line 289, in callback
    return success, message, backend.callback(state_token, authz_code, trans, login_redirect_url)
  File "lib/galaxy/authnz/custos_authnz.py", line 118, in callback
    raise exceptions.AuthenticationFailed(message)
galaxy.exceptions.AuthenticationFailed: There already exists a user this email.  To associate this external login, you must first be logged in as that existing account.
```

The exception is understandable but it's not handled properly and the browser just receives http 500 error.

**Comment by afgane** [comment]
Similar issue if the secret is incorrect, the server just crashes without a message to the user.

```
Traceback (most recent call last):
  File "lib/galaxy/authnz/managers.py", line 289, in callback
    return success, message, backend.callback(state_token, authz_code, trans, login_redirect_url)
  File "lib/galaxy/authnz/custos_authnz.py", line 72, in callback
    token = self._fetch_token(oauth2_session, trans)
  File "lib/galaxy/authnz/custos_authnz.py", line 193, in _fetch_token
    verify=self._get_verify_param())
  File "/Users/ea/projects/ppy/galaxy/releases-repo/.venv/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/ea/projects/ppy/galaxy/releases-repo/.venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/ea/projects/ppy/galaxy/releases-repo/.venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/Users/ea/projects/ppy/galaxy/releases-repo/.venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/ea/projects/ppy/galaxy/releases-repo/.venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Invalid client secret
```

**Comment by dannon** [comment]
xref #10075
