### ISSUE TITLE
NameError: global name 'IsADirectoryError' is not defined

### ISSUE THREAD

**Issue by sanman-99** [galaxyproject/galaxy#9900]
Running on Galaxy version 19.09 we are running into an error when attempting to delete a history.  We are using S3 as an object store.  The following error occurs in the logs:

```
galaxy.web.framework.decorators ERROR 2020-06-22 00:04:00,313 [p:32511,w:4,m:0] [uWSGIWorker4Core2] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/histories.py", line 439, in update
    self.deserializer.deserialize(history, payload, user=trans.user, trans=trans)
  File "lib/galaxy/managers/base.py", line 745, in deserialize
    new_dict[key] = self.deserializers[key](item, key, val, **context)
  File "lib/galaxy/managers/deletable.py", line 109, in deserialize_purged
    self.manager.purge(item, flush=False)
  File "lib/galaxy/managers/histories.py", line 99, in purge
    self.hda_manager.purge(hda, flush=True)
  File "lib/galaxy/managers/hdas.py", line 144, in purge
    super(HDAManager, self).purge(hda, flush=flush)
  File "lib/galaxy/managers/datasets.py", line 271, in purge
    self.dataset_manager.purge(dataset_assoc.dataset)
  File "lib/galaxy/managers/datasets.py", line 71, in purge
    dataset.full_delete()
  File "lib/galaxy/model/__init__.py", line 2328, in full_delete
    self.object_store.delete(self)
  File "lib/galaxy/objectstore/__init__.py", line 551, in delete
    return self._call_method('delete', obj, False, False, **kwargs)
  File "lib/galaxy/objectstore/__init__.py", line 585, in _call_method
    return store.__getattribute__(method)(obj, **kwargs)
  File "lib/galaxy/objectstore/s3.py", line 622, in delete
    except IsADirectoryError:
NameError: global name 'IsADirectoryError' is not defined
```

**Comment by nsoranzo** [comment]
I can't find `IsADirectoryError` anywhere in the Galaxy objectstore code base, do you have any local modification by any chance?

**Comment by sanman-99** [comment]
You are correct, that is my mistake.  We had added that because we were previously getting an exception when s3.py was attempting to delete a cache file and it was failing without an exception catching the failure.
