### ISSUE TITLE
issue with extended metadata_strategy and pulsar

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#9968]
I am testing the pr https://github.com/galaxyproject/galaxy/pull/9956 and my set up is:
* a pulsar destination with `<param id="metadata_strategy">directory</param>`enabled
* a backend with `store_by=uuid` enabled
* Galaxy release_20.05

I have uploaded a bam file two times, the first time with `metadata_strategy=extended' and then without.
Then I have executed the "samtools stats" tool on them against the pulsar destination.

The job using the dataset uploaded without the `metadata_strategy=extended' runs correctly, the other one fails with this error:
```
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.handler DEBUG 2020-07-08 11:25:23,014 Grabbed job(s): 787
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.mapper DEBUG 2020-07-08 11:25:23,065 (787) Mapped job to destination id: static_remote_cluster_mq_it01
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.handler DEBUG 2020-07-08 11:25:23,097 (787) Dispatching to pulsar_eu_it01 runner
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs DEBUG 2020-07-08 11:25:23,109 (787) Persisting job destination (destination id: static_remote_cluster_mq_it01)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.objectstore DEBUG 2020-07-08 11:25:23,125 Selected backend 'dnb03' for creation of Dataset 877
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.objectstore DEBUG 2020-07-08 11:25:23,160 Using preferred backend 'dnb03' for creation of Job 787
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs DEBUG 2020-07-08 11:25:23,172 (787) Working directory for job is: /data/dnb03/galaxy_db/test/job_working_directory/000/787
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.runners DEBUG 2020-07-08 11:25:23,177 Job [787] queued (80.007 ms)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.handler INFO 2020-07-08 11:25:23,186 (787) Job dispatched
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.runners.pulsar INFO 2020-07-08 11:25:23,201 pulsar_version is 0.14.0.dev3
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.runners.pulsar INFO 2020-07-08 11:25:23,293 input_metadata_rewrite is /data/share/staging/787/inputs/metadata_None from None
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: pulsar.client.staging.up WARNING 2020-07-08 11:25:23,340 __action_for_transfer called on non-existent file - [None]
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs ERROR 2020-07-08 11:25:23,353 fail(): Missing output file in working directory: [Errno 2] No such file or directory: '/data/dnb03/galaxy_db/test/job_working_directory/000/787/outputs/galaxy_dataset_54f254f3-919d-4419-a312-c0b17ea6afcc.dat'
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.tools.error_reports DEBUG 2020-07-08 11:25:23,449 Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x7f23114b5780> generated response None
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: galaxy.jobs.runners.pulsar ERROR 2020-07-08 11:25:23,458 failure running job 787
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: Traceback (most recent call last):
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/server/lib/galaxy/jobs/runners/pulsar.py", line 390, in queue_job
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: job_id = pulsar_submit_job(client, client_job_description, remote_job_config)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 27, in submit_job
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: file_stager = FileStager(client, client_job_description, job_config)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 123, in __init__
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: self.__upload_input_files()
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 236, in __upload_input_files
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: self.__upload_input_metadata_file(client_input.action_source)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 255, in __upload_input_metadata_file
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: self.transfer_tracker.handle_transfer_source(input_action_source, path_type.INPUT, name=remote_name)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 462, in handle_transfer_source
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: action = self.__action_for_transfer(source, type, contents)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: File "/opt/galaxy/venv/lib/python3.6/site-packages/pulsar/client/staging/up.py", line 518, in __action_for_transfer
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: raise Exception(message)
Jul 08 11:25:23 test.internal.usegalaxy.eu.novalocal python[873067]: Exception: __action_for_transfer called on non-existent file - [None]

```

**Comment by mvdbeek** [comment]
This is surprising, once the file is successfully uploaded there shouldn't be a difference between `metadata_extended` or not. Can you check if the index file is present after upload with `metadata_strategy: extended` ?

**Comment by mvdbeek** [comment]
Yep, can repoduce that, looks like the index indeed isn't being loaded back:
```
[E::idx_find_and_load] Could not retrieve index file for '/Users/mvandenb/src/galaxy/database/tmp/74ded2a0f6e9dcf2-1594204905970-39973'
[E::idx_find_and_load] Could not retrieve index file for '/Users/mvandenb/src/galaxy/database/jobs_directory/007/7909/outputs/galaxy_dataset_b89aedac-e788-447f-97ad-3c8c8c837d12.dat'

[E::idx_find_and_load] Could not retrieve index file for '/Users/mvandenb/src/galaxy/database/jobs_directory/007/7909/outputs/galaxy_dataset_b89aedac-e788-447f-97ad-3c8c8c837d12.dat'
[E::idx_find_and_load] Could not retrieve index file for '/Users/mvandenb/src/galaxy/database/jobs_directory/007/7909/outputs/galaxy_dataset_b89aedac-e788-447f-97ad-3c8c8c837d12.dat'
```

**Comment by mvdbeek** [comment]
Can you try a txt file, just to see if it works otherwise ? I'm working on a fix.

**Comment by gmauro** [comment]
How to say... is going different.
Now I have an error from the Pulsar side:
HTTP Error 403: Forbidden

but it works correctly with the same dataset uploaded without `metadata_extended`

**Comment by mvdbeek** [comment]
@gmauro https://github.com/galaxyproject/galaxy/pull/9974 should fix the problem you saw with the bam file. Is there anything besides the 403 in the logs ? Do you know for which route you received the 403 ? The file that works and the one that doesn't work are both in the same object store, and both use `store_by: uuid` ?

**Comment by gmauro** [comment]
I am not yet using your patch

txt file uploaded with 'metadata_strategy_extended`
```
Jul 09 15:58:33 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs.runners.condor INFO 2020-07-09 15:58:33,191 (823) queued as 112
Jul 09 15:58:49 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:58:49,140 (823/112) job is now running
Jul 09 15:58:58 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:58:58,299 (823/112) job is now running
Jul 09 15:59:02 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:59:02,393 (823/112) job is now running
Jul 09 15:59:02 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:59:02,446 (823/112) job has completed
Jul 09 15:59:02 test.internal.usegalaxy.eu.novalocal python[2601944]: galaxy.jobs DEBUG 2020-07-09 15:59:02,721 job_wrapper.finish for job ${job_id} executed (220.636 ms)

```
and the path is:

`Full Path: | /data/dnb03/galaxy_db/test/job_working_directory/000/821/outputs/galaxy_dataset_e8d69029-566e-46cc-aa18-4cc47e864ada.dat`

txt file uploaded without 'metadata_strategy_extended`
```
Jul 09 15:55:11 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs.runners.condor INFO 2020-07-09 15:55:11,584 (822) queued as 111
Jul 09 15:55:29 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:55:29,382 (822/111) job is now running
Jul 09 15:55:38 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:55:38,530 (822/111) job is now running
Jul 09 15:55:40 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:55:40,592 (822/111) job is now running
Jul 09 15:55:40 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs.runners.condor DEBUG 2020-07-09 15:55:40,645 (822/111) job has completed
Jul 09 15:55:40 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs DEBUG 2020-07-09 15:55:40,730 finish(): Moved /data/dnb03/galaxy_db/test/job_working_directory/000/822/outputs/galaxy_dataset_a0d9b09b-2c0d-4f07-ba52-b8a6c39016ee.dat to /data/dnb03/galaxy_db/test/files/a/0/d/dataset_a0d9b09b-2c0d-4f07-ba52-b8a6c39016ee.dat
Jul 09 15:55:40 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.model.metadata DEBUG 2020-07-09 15:55:40,766 loading metadata from file for: HistoryDatasetAssociation 913
Jul 09 15:55:40 test.internal.usegalaxy.eu.novalocal python[2599996]: galaxy.jobs DEBUG 2020-07-09 15:55:40,917 job_wrapper.finish for job ${job_id} executed (217.126 ms)
```
and the path is:
`Full Path: | /data/dnb03/galaxy_db/test/files/a/0/d/dataset_a0d9b09b-2c0d-4f07-ba52-b8a6c39016ee.dat`

**Comment by gmauro** [comment]
I expected to find both files in the path /data/dnb03/galaxy_db/test/files ..., right?

**Comment by mvdbeek** [comment]
Right. Do you have outputs_to_working_directory set to true ?

**Comment by gmauro** [comment]
> Right. Do you have outputs_to_working_directory set to true ?

yes

**Comment by mvdbeek** [comment]
Ah, I think in the test cases we never configured https://github.com/usegalaxy-eu/infrastructure-playbook/blob/new_20.05_config/files/galaxy-test/config/object_store_conf.xml#L12, in combination with extended_metadata. I've noted https://github.com/mvdbeek/galaxy/blob/dev/test/integration/objectstore/test_swift_objectstore.py#L92, that might be a common cause here.

**Comment by gmauro** [comment]
I removed the extra_dir https://github.com/usegalaxy-eu/infrastructure-playbook/commit/8e85dab743ad7897a8597b78a5847ab4f14ab9d4 but the result is the same; the file remain into the working_dir
