### ISSUE TITLE
slurm-drmaa loading failed on CentOS7

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/galaxy#9979]
I tried to install a slurm cluster following this tutorial [Connecting Galaxy to a compute cluster](https://training.galaxyproject.org/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html#running-with-more-resources), but can't get slurm-drmaa to work. I always get the following errors in my galaxy log:

```
Jul 10 12:19:26 myserver.local uwsgi[26820]: OSError: "/usr/lib64/libdrmaa.so.1": cannot open shared object file: No such file or directory
...
Jul 10 12:19:26 myserver.local uwsgi[26820]: galaxy.app DEBUG 2020-07-10 12:19:26,135 [p:27213,w:0,m:1] [MainThread] python path is: /srv/galaxy/server/lib/, /srv/galaxy/server/lib, ., , /srv/galaxy/venv/bin, /srv/galaxy/server/lib/galaxy/jobs/rules, /srv/galaxy/venv/lib64/python36.zip, /srv/galaxy/venv/lib64/python3.6, /srv/galaxy/venv/lib64/python3.6/lib-dynload, /usr/lib64/python3.6, /usr/lib/python3.6, /srv/galaxy/venv/lib/python3.6/site-packages
```

The installed lib comes from the galaxy-repo ` slurm-drmaa-1.1.1-1.el7.x86_64`
The files for libdrmaa can be found in /usr/lib64, so i had to change the path in my galaxy config
```
galaxy_systemd_zergling_env: "DRMAA_LIBRARY_PATH=\"/usr/lib64/libdrmaa.so.1\""
```

```
(venv) [galaxy@myserver server]$ ls -lh /usr/lib64 | grep libdrmaa
-rw-r--r--   1 root root 296K  2. Apr 21:53 libdrmaa.a
-rwxr-xr-x   1 root root  959  2. Apr 21:53 libdrmaa.la
lrwxrwxrwx   1 root root   17 10. Jul 10:43 libdrmaa.so -> libdrmaa.so.1.0.8
lrwxrwxrwx   1 root root   17 10. Jul 10:43 libdrmaa.so.1 -> libdrmaa.so.1.0.8
-rwxr-xr-x   1 root root 176K  2. Apr 21:53 libdrmaa.so.1.0.8
```

The systemd defintion looks like this:
```
...
[Service]
UMask=022
Type=simple
User=galaxy
Group=galaxy
WorkingDirectory=/srv/galaxy/server
TimeoutStartSec=10
ExecStart=/srv/galaxy/venv/bin/uwsgi --yaml /srv/galaxy/config/galaxy.yml --stats 127.0.0.1:4010
Environment=HOME=/srv/galaxy VIRTUAL_ENV=/srv/galaxy/venv PATH=/srv/galaxy/venv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin DOCUTILSCONFIG= PYTHONPATH=/srv/galaxy/server/lib/galaxy/jobs/rules DRMAA_LIBRARY_PATH="/usr/lib64/libdrmaa.so.1"
...
```

I am using CentOS7 in a VM with a fresh galaxy instance running, installed with Ansible [Galaxy Installation with Ansible](https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html)

<details>
<summary>view full error-log</summary>

```
Jul 10 12:19:25 myserver.local uwsgi[26820]: galaxy.jobs.runners DEBUG 2020-07-10 12:19:25,993 [p:27204,w:0,m:2] [MainThread] Starting 4 LocalRunner workers
Jul 10 12:19:25 myserver.local uwsgi[26820]: galaxy.jobs DEBUG 2020-07-10 12:19:25,994 [p:27204,w:0,m:2] [MainThread] Loaded job runner 'galaxy.jobs.runners.local:LocalJobRunner' as 'local'
Jul 10 12:19:25 myserver.local uwsgi[26820]: galaxy.jobs.runners.state_handler_factory DEBUG 2020-07-10 12:19:25,996 [p:27204,w:0,m:2] [MainThread] Loaded 'failure' state handler from module galaxy.jobs.runners.state_handlers.resubmit
Jul 10 12:19:26 myserver.local uwsgi[26820]: Failed to initialize Galaxy application
Jul 10 12:19:26 myserver.local uwsgi[26820]: Traceback (most recent call last):
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 141, in app_loop
Jul 10 12:19:26 myserver.local uwsgi[26820]: attach_to_pools=args.attach_to_pool,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 108, in load_galaxy_app
Jul 10 12:19:26 myserver.local uwsgi[26820]: **kwds
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/app.py", line 217, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_manager = manager.JobManager(self)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/manager.py", line 26, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_handler = handler.JobHandler(app)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 51, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.dispatcher = DefaultJobDispatcher(app)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 952, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_runners = self.app.job_config.get_job_runner_plugins(self.app.config.server_name)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/__init__.py", line 803, in get_job_runner_plugins
Jul 10 12:19:26 myserver.local uwsgi[26820]: rval[id] = runner_class(self.app, runner.get('workers', JobConfiguration.DEFAULT_NWORKERS), **runner.get('kwds', {}))
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/runners/drmaa.py", line 66, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: drmaa = __import__("drmaa")
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/__init__.py", line 65, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from .session import JobInfo, JobTemplate, Session
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: _lib = CDLL(libpath, mode=RTLD_GLOBAL)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self._handle = _dlopen(self._name, mode)
Jul 10 12:19:26 myserver.local uwsgi[26820]: OSError: "/usr/lib64/libdrmaa.so.1": cannot open shared object file: No such file or directory
Jul 10 12:19:26 myserver.local uwsgi[26820]: Traceback (most recent call last):
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 298, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: main()
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 294, in main
Jul 10 12:19:26 myserver.local uwsgi[26820]: app_loop(args, log)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 141, in app_loop
Jul 10 12:19:26 myserver.local uwsgi[26820]: attach_to_pools=args.attach_to_pool,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "lib/galaxy/main.py", line 108, in load_galaxy_app
Jul 10 12:19:26 myserver.local uwsgi[26820]: **kwds
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/app.py", line 217, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_manager = manager.JobManager(self)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/manager.py", line 26, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_handler = handler.JobHandler(app)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 51, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.dispatcher = DefaultJobDispatcher(app)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/handler.py", line 952, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self.job_runners = self.app.job_config.get_job_runner_plugins(self.app.config.server_name)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/__init__.py", line 803, in get_job_runner_plugins
Jul 10 12:19:26 myserver.local uwsgi[26820]: rval[id] = runner_class(self.app, runner.get('workers', JobConfiguration.DEFAULT_NWORKERS), **runner.get('kwds', {}))
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/server/lib/galaxy/jobs/runners/drmaa.py", line 66, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: drmaa = __import__("drmaa")
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/__init__.py", line 65, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from .session import JobInfo, JobTemplate, Session
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/srv/galaxy/venv/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
Jul 10 12:19:26 myserver.local uwsgi[26820]: _lib = CDLL(libpath, mode=RTLD_GLOBAL)
Jul 10 12:19:26 myserver.local uwsgi[26820]: File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
Jul 10 12:19:26 myserver.local uwsgi[26820]: self._handle = _dlopen(self._name, mode)
Jul 10 12:19:26 myserver.local uwsgi[26820]: OSError: "/usr/lib64/libdrmaa.so.1": cannot open shared object file: No such file or directory
Jul 10 12:19:26 myserver.local uwsgi[26820]: OOOPS mule 1 (pid: 27203) crippled...trying respawn...
Jul 10 12:19:26 myserver.local uwsgi[26820]: spawned uWSGI mule 1 (pid: 27213)
Jul 10 12:19:26 myserver.local uwsgi[26820]: galaxy.web_stack DEBUG 2020-07-10 12:19:26,106 [p:27213,w:0,m:1] [MainThread] Calling postfork function: <function _mule_fixup at 0x7f06f56e8c80>
Jul 10 12:19:26 myserver.local uwsgi[26820]: galaxy.app DEBUG 2020-07-10 12:19:26,135 [p:27213,w:0,m:1] [MainThread] python path is: /srv/galaxy/server/lib/, /srv/galaxy/server/lib, ., , /srv/galaxy/venv/bin, /srv/galaxy/server/lib/galaxy/jobs/rules, /srv/galaxy/venv/lib64/python36.zip, /srv/galaxy/venv/lib64/python3.6, /srv/galaxy/venv/lib64/python3.6/lib-dynload, /usr/lib64/python3.6, /usr/lib/python3.6, /srv/galaxy/venv/lib/python3.6/site-packages
```

</details>

**Comment by charmichaeld** [comment]
We have Galaxy on a Slurm cluster with the following in the config/job_conf.xml to specify the drmaa_library_path
```
    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner"/>
        <plugin id="slurm" type="runner" load="galaxy.jobs.runners.slurm:SlurmJobRunner" workers="10">
            <param id="drmaa_library_path">/usr/lib64/libdrmaa.so</param>
        </plugin>
        <plugin id="dynamic" type="runner">
            <param id="rules_module">galaxy.jobs.rules</param>
        </plugin>
    </plugins>
```

**Comment by maikknebel** [comment]
I am using this line now in group_vars, which is working without problems:
```
galaxy_systemd_zergling_env: DRMAA_LIBRARY_PATH="/usr/lib64/libdrmaa.so.1"
```
