### ISSUE TITLE
Invalid casting of parameters

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#998]
One of our users was able to produce the following error with the standard velvetg tool in Galaxy.

```
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 862, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 422, in build
    raise e
ValueError: invalid literal for int() with base 10: '-1.0'
```

To fix this problem we have changed `#if int($reads.options.max_divergence) > 0:` to `#if float($reads.options.max_divergence) > 0.0:`. Not only that this should not happen, this tool worked fine half year back during our last training course. So this seems to be a regression.
I'm wondering if this can be some `locale` issue.
We are running `enable_beta_tool_command_isolation = True`.

**Comment by peterjc** [comment]
In the case of the GMAP wrappers, the casting error was:

```
galaxy.jobs.runners: ERROR: (3) Failure preparing job
Traceback (most recent call last):
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/jobs/__init__.py", line 905, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/Volumes/Hitachi-3TB-mirrored/repositories/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
    raise e
ValueError: invalid literal for int() with base 10: ''
```

Editing the `<command>` string to remove two case of this "fixed" it:

```
#if $split_output == True
```

where:

``` xml
<param name="split_output" type="boolean" truevalue="--split-output=gmap_out" falsevalue="" checked="false" label="Separate outputs for nomapping, uniq, mult, and chimer\
a" help="(chimera only when chimera-margin is selected)"/>
```

**Comment by mvdbeek** [comment]
Fixed with https://github.com/galaxyproject/galaxy/pull/7634
